### ISSUE TITLE
Define and categorize metrics

### ISSUE THREAD

**Issue by rviscomi** [HTTPArchive/almanac.httparchive.org#1]
Refer to the [Content Brainstorm](https://docs.google.com/document/d/1sCIMeErYvaQb5x9Acdb6ImYdn0-buHRhYGvz2HoysmM/edit?usp=sharing) doc for the latest draft

- [x] define a list of high-level "sections" (eg content, experience, distribution, publishing, etc)
- [x] define a list of mid-level "chapters" (eg for content: JS, CSS, img, etc)
- [x] define a list of low-level metrics (eg for JS: bytes, bootup time, libraries, etc)

**Comment by bazzadp** [comment]
@rviscomi approximately how many metrics do you expect in a chapter?

The [original post](https://discuss.httparchive.org/t/planning-the-web-almanac-2019/1553) had the following:

> Subject Matter Expert (Author)
> Responsible for providing an interpretation of the HTTP Archive data for specific chapters aligned with their area of expertise. For example, in the JS chapter, explain what the implications are for the number of bytes and CPU execution time to be rising. 1-2 paragraphs per metric are expected plus an intro and summary conclusion. Think of it like one blog post in a series written by many authors.
> During the planning phase 5, experts should ensure that their chapters contain the necessary metrics to accurately capture their state. Also help us identify if there are any metrics that we are currently unable to capture so we can work on getting them in place for next year’s edition.
> Time commitment: 2 hours in April to coordinate on chapters’ metrics, 4 hours in August to write interpretations.

So you thinking about 5 metrics in a chapter with a paragraph or two for each? Or 3? Or 10? Or 100? While it can of course depend on the topic and the author, I think it would be good to set a rough benchmark as a guideline so we're all roughly on the same page.

**Comment by rviscomi** [comment]
@bazzadp great question. 10 metrics per chapter on average sounds like a good amount. It's a balance between being comprehensive while respecting authors' time and readers' attention.

And 1-2 paragraphs per metric SGTM. We want readers to understand the implications of each statistic but we don't need to be overly verbose to get the point across.
