### ISSUE TITLE
Query 04_05: Microdata usage (og:image, twitter:image, etc)

### ISSUE THREAD

**Issue by dougsillars** [HTTPArchive/almanac.httparchive.org#102]
Colin or Rick,
going through the media queries:
Is there a good list of microdata examples that I can query on?  Or other handle that I can grab from the data?

Thanks

**Comment by rviscomi** [comment]
I'm not as familiar with microdata but IIUC it's not the same type of structured data format as `og:image`. The former seems to be inline attributes giving semantic meaning to the markup while the latter is a type of `head > meta` property.

Here are a few examples of [microdata usage](https://developer.mozilla.org/en-US/docs/Web/HTML/Microdata#Example), [twitter:image usage](https://developer.twitter.com/en/docs/tweets/optimize-with-cards/overview/summary-card-with-large-image.html), and [og:image usage](http://ogp.me/).

Does that answer your question or am I misreading? Hope it helps.
