### ISSUE TITLE
Add a web archiving chapter

### ISSUE THREAD

**Issue by ibnesayeed** [HTTPArchive/almanac.httparchive.org#1025]
I was wondering if web archiving is something we should report in a chapter. HTTP Archive itself is a web archive, then we have the [Internet Archive](https://web.archive.org/), and many more as the [International Internet Preservation Consortium (IIPC) members](https://netpreserve.org/about-us/members/). I think it would be great if we could report how well and how much are we archiving our web year by year as well as how unarchivable (or archiving unfriendly) the web is becoming. We can also track how many sites are serving versioned resources (such as wiki and git) on the web and how many of them utilize standard means of time-based resources like [Memento](https://tools.ietf.org/html/rfc7089). I am not entirely sure what are all the things we would want to report, but perhaps some IIPC members would be willing to contribute to it, if we decide to add the chapter.

**Comment by rviscomi** [comment]
My first impression is that this chapter may be too narrowly focused and may have some challenges getting metrics. Happy to be convinced otherwise.

For topics that don't quite fit as a standalone chapter or as a subsection of other chapters, I've been encouraging contributors to submit their content to the dev.to/httparchive blog instead, which is a more versatile platform for deep dives into esoteric corners of web transparency. @ibnesayeed would you be open to writing this as a blog post?

**Comment by ibnesayeed** [comment]
> @ibnesayeed would you be open to writing this as a blog post?

My plate is too full for the next couple of months (graduation and job search) so I cannot promise for anything like this right now, but I will keep this in my mind.

**Comment by rviscomi** [comment]
Ok, I'll close this issue for now and we can consider this next year during content planning if there's interest.

**Comment by rviscomi** [comment]
And congratulations on your graduation! 🎉 :)

**Comment by ibnesayeed** [comment]
> Ok, I'll close this issue for now and we can consider this next year during content planning if there's interest.

Next year sounds good to me, hopefully I will be able to contribute as a co-author and analyst. There is certainly interest in the Web archiving community to report something in the Web Almanac (I am saying this based on my conversation with people in the IIPC community).

> And congratulations on your graduation!  :)

Thanks! :heart:
