### ISSUE TITLE
Chapter navigation padding

### ISSUE THREAD

**Issue by catalinred** [HTTPArchive/almanac.httparchive.org#1033]
There is some huge `rem` padding added by the `#chapter-navigation ` selector in a #979 [commit](https://github.com/HTTPArchive/almanac.httparchive.org/pull/979/commits/27073a2a0d6dec7add69cd9ebab1686aae8dec0e#diff-60c992f3e3a9ff942fca734de02a5b51R288) and I guess this is not intended.

<img width="1658" alt="extra-padding" src="https://user-images.githubusercontent.com/1867900/87520326-79890c80-c68b-11ea-98e8-3f15862d781f.png">

**Comment by bazzadp** [comment]
Oops! Fixing ASAP.

**Comment by bazzadp** [comment]
Fixed and deployed. May take up to 3 hours for CDN to see new CSS in cache depending on your location. Think there's a way to clear the cache on GCP but not done that before so will just wait the 3 hours.

Thanks for raising!
