### ISSUE TITLE
Sort contributor teams by locale

### ISSUE THREAD

**Issue by rviscomi** [HTTPArchive/almanac.httparchive.org#1045]
I noticed the list of teams is sorted alphabetically in [English](https://almanac.httparchive.org/en/2020/contributors):
![image](https://user-images.githubusercontent.com/1120896/87738314-15f60080-c7ab-11ea-853e-efd5ddcc5f54.png)

In other languages like [French](https://almanac.httparchive.org/fr/2020/contributors), the list is still sorted using the English spelling:
![image](https://user-images.githubusercontent.com/1120896/87738235-e3e49e80-c7aa-11ea-9787-800db245b694.png)

Should the list of teams be sorted according to the localized team names?

**Comment by bazzadp** [comment]
Yes, we should.

I'm in that code anyway as part of #1042 so to avoid any conflicts I've added the fix to that branch with this commit: https://github.com/HTTPArchive/almanac.httparchive.org/pull/1042/commits/f0da9bd5b14eb768f8e23e0dd32b01cf95488410

As part of that I've removed the fallback to config team names - translations not must have this in their template (even if untranslated and just in English), similar to other required template blocks.
