### ISSUE TITLE
Update third party domain/category map on BigQuery

### ISSUE THREAD

**Issue by rviscomi** [HTTPArchive/almanac.httparchive.org#1061]
Last year we used the [mapping](https://console.cloud.google.com/bigquery?p=httparchive&d=almanac&t=third_parties&page=table) of third party domains to categories from @patrickhulce's [Third Party Web](https://almanac.httparchive.org/en/2019/methodology#third-party-web) project.

We should just be able to overwrite `httparchive.almanac.third_parties` with [`lighthouse-infrastructure.third_party_web.2020_05_01`](https://console.cloud.google.com/bigquery?p=lighthouse-infrastructure&d=third_party_web&t=2020_05_01&page=table) (the latest table).

@patrickhulce any plans to cut a newer release in the next couple of months? It's probably fine if not since I don't expect these domains to change _too_ much.

**Comment by patrickhulce** [comment]
I was planning on doing a September cut but if youd like one sooner the instructions for generating the table are in the repo if @simonhearne wants to do it sooner :)

**Comment by max-ostapenko** [comment]
@patrickhulce Does 'Septemeber cut' mean that it will be available on 2020_09_01?

**Comment by patrickhulce** [comment]
No it would mean it would be available shortly after the September run of HTTPArchive completes, usually around 3rd of 4th week of the month.

**Comment by rviscomi** [comment]
@patrickhulce is it possible to cut a 2020_08_01 version of the BigQuery table? We can pull this into the `almanac` dataset for analysis in this year's edition.

**Comment by patrickhulce** [comment]
@rviscomi sure you just need the domain mapping table, right?

**Comment by rviscomi** [comment]
Yes please! The mapping of domains to third party categories. Thanks!

**Comment by patrickhulce** [comment]
Done. `lighthouse-infrastructure.third_party_web.2020_08_01`

Also attached here in zipped CSV if you want to reupload that way only ~1.5MB of ~34k domains to category
[domain-map.csv.zip](https://github.com/HTTPArchive/almanac.httparchive.org/files/5132907/domain-map.csv.zip)

**Comment by rviscomi** [comment]
Thanks @patrickhulce!!

**Comment by rviscomi** [comment]
Merged `lighthouse-infrastructure.third_party_web.2020_08_01` with [`almanac.third_parties`](https://console.cloud.google.com/bigquery?p=httparchive&d=almanac&t=third_parties&page=table) and added a new partitioned `date` field to differentiate 2019 and 2020 data.
