### ISSUE TITLE
Team name word wrapping in Japanese Contributors page

### ISSUE THREAD

**Issue by rviscomi** [HTTPArchive/almanac.httparchive.org#1074]
For example, some [contributors](https://almanac.httparchive.org/ja/2019/contributors) are members of multiple teams and the team names span multiple lines:

![image](https://user-images.githubusercontent.com/1120896/88120781-c12efd00-cb91-11ea-8fc5-c05baacdb8d5.png)

On Katie and Una's tiles the team `ブレインストーマー` is broken up onto multiple lines. Would it make more sense in Japanese to set the `white-space: nowrap;` style on the `.contributor-team` rule, so that the characters in the team name are all rendered to the same line, like this:

![image](https://user-images.githubusercontent.com/1120896/88120954-45818000-cb92-11ea-8cff-cc0a44af9353.png)

This could also be useful for other languages with longer translations.

**Comment by SaptakS** [comment]
I think this makes sense. Would love to work on this if no one else is looking into it.

**Comment by bazzadp** [comment]
Go for it - shout if you need any help!
