### ISSUE TITLE
Tweak the contributors "Join the team" SVG

### ISSUE THREAD

**Issue by rviscomi** [HTTPArchive/almanac.httparchive.org#1076]
Small nit: could we edit the speech bubble SVG in the "Join the team" tile so that the pointed line at the bottom of the bubble is pointing in the direction of the character's mouth, rather than its hand?

![image](https://user-images.githubusercontent.com/1120896/88121856-fee15500-cb94-11ea-97e6-a49b7781fc54.png)

cc @catalinred

**Comment by catalinred** [comment]
I'll give it a try!
