### ISSUE TITLE
Add contributor section to 2020 landing page

### ISSUE THREAD

**Issue by rviscomi** [HTTPArchive/almanac.httparchive.org#1083]
Now that we've published the 2020 [Contributors](https://almanac.httparchive.org/en/2020/contributors) page, we could add the related section to the [landing](https://almanac.httparchive.org/en/2020/) page to highlight the number of contributors.

Not having a "featured chapter" section makes the design a bit awkward because there's not a lot of room below the angled header background graphic. I've mocked up a version of the 2020 landing page without the `alt-bg` inverted styles on the contributor section:

![0 0 0 0_8080_en_2020_ (1)](https://user-images.githubusercontent.com/1120896/88313981-46292c00-cce2-11ea-9d10-a25226589610.png)

Open to other design ideas!

Related issue: #1082

**Comment by bazzadp** [comment]
To save redesigning this, what about something else in the Featured Quote section instead?

What about quotes/praise about the 2019 edition? Didn't you have a list somewhere?

**Comment by rviscomi** [comment]
That'd require some redesigning of the feature chapter section too, but that also works for me. Let me know which approach you'd prefer.

**Comment by bazzadp** [comment]
Completed in #1383
