### ISSUE TITLE
header::after background causing phantom glitches

### ISSUE THREAD

**Issue by rviscomi** [HTTPArchive/almanac.httparchive.org#1084]
Manipulating the page zoom causes a phantom bar to appear sometimes. In the screenshot below it appears in the middle of the featured chapter section when setting the zoom to 75%:

![almanac httparchive org_en_2019_ (1)](https://user-images.githubusercontent.com/1120896/88314412-e41cf680-cce2-11ea-8034-041f6e224f7b.png)

I've traced it to the `header::after` style.

https://github.com/HTTPArchive/almanac.httparchive.org/blob/496a03b09d60ae021cb364d7ec2e63c0a58ad7d3/src/static/css/index.css#L20-L31

@bazzadp any ideas how to mitigate this?

**Comment by bazzadp** [comment]
To be honest we could probably just drop this. It was added in an abundance of caution in case the SVG didn't load as then had white text on white background which was obviously unreadable. But as it's base64 encoded to be inlined to the CSS, and as [SVG has great support](https://caniuse.com/#feat=svg-css), it's very unlikely it won't be loaded. And the main `header.alt-bg` class has a couple of fallbacks anyway.
