### ISSUE TITLE
Add releases in a repo

### ISSUE THREAD

**Issue by max-ostapenko** [HTTPArchive/almanac.httparchive.org#1086]
Mark every new content release (e.g. version 2020:JP) to be able to subscribe for releases.
Currently there is no way to learn that new localization of Almanac was released.

Hopefully can be implemented as Action.

**Comment by rviscomi** [comment]
@max-ostapenko could you elaborate on the benefits of releases?

What workflow changes do we need to adopt in order to accommodate them?

**Comment by bazzadp** [comment]
Closing as have started doing this: https://github.com/HTTPArchive/almanac.httparchive.org/releases/
