### ISSUE TITLE
Figure 7 in 2019 Media Chapter image is not a Google Sheets image

### ISSUE THREAD

**Issue by bazzadp** [HTTPArchive/almanac.httparchive.org#1099]
https://almanac.httparchive.org/en/2019/media#fig-7 is just a PNG and without the `data-` attributes necessary to convert it to an interactive iFrame.

Looks like the nicely formatted image in the PNG is no longer there in the [Google Sheets version](https://docs.google.com/spreadsheets/d/1hj9bY6JJZfV9yrXHsoCRYuG8t8bR-CHuuD98zXV7BBQ/edit#gid=1419236152).

@rviscomi / @colinbendell any ideas how to format that same as the PNG? If so, and can give me the sheets published URL, then I can update the markup.

**Comment by rviscomi** [comment]
IIRC @colinbendell generated this chart outside of Sheets, like [Figure 10](https://almanac.httparchive.org/en/2019/media#fig-10), so I'm not sure that we'd be able to generate the interactive iframe.

**Comment by colinbendell** [comment]
Yes, I used ggplot to generate the tree. google sheets doesn't do tree diagrams very well (at all).

**Comment by bazzadp** [comment]
Fair enough closing then. Though can't see I honest can see much difference (other than the colour) myself! 😀

**Comment by colinbendell** [comment]
> Fair enough closing then. Though can't see I honest can see much difference (other than the colour) myself! 😀

I haven't looked at the trees from google sheets lately. maybe it has been rev'd? I know I struggled with the labels and formatting and just gave up to use a tool that was better for formatting ;)
