### ISSUE TITLE
Finalize assignments: Chapter 9. Accessibility

### ISSUE THREAD

**Issue by rviscomi** [HTTPArchive/almanac.httparchive.org#11]
Section | Chapter | Authors | Reviewers
-- | -- | -- | --
II. User Experience | 9. Accessibility | Nektarios Paisios, @nadinarama, @obto |@rachellcostello @kleinab

In an effort to be more accessible to Nektarios, planning for this chapter is being done in a Google Doc. See [Planning the Accessibility chapter](https://docs.google.com/document/d/1rpFtES6BXGYmsRR1peKsEY6ZLN9-FklOgk9qos_sK1Q/edit?usp=sharing).

I'll keep this issue in sync in terms of status and AIs.

**To do:**
- [x] Assign subject matter experts (coauthors)
- [x] Finalize peer reviewers
- [x] Finalize metrics

**Comment by rviscomi** [comment]
Adding @obto as coauthor. Note that this chapter is being iterated in a separate, more accessible Google Doc.

**Comment by obto** [comment]
@rviscomi Just edited and added a few more things to the google doc. After the couple questions I posed to the group are answered we're good to go.

**Comment by rviscomi** [comment]
[The doc](https://docs.google.com/document/d/1rpFtES6BXGYmsRR1peKsEY6ZLN9-FklOgk9qos_sK1Q/edit?usp=sharing) is in a good place, so I'll close this issue.
