### ISSUE TITLE
Support LinkedIn contributor links

### ISSUE THREAD

**Issue by rviscomi** [HTTPArchive/almanac.httparchive.org#1136]
Per #1134 contributors should be able to add their LinkedIn profile to their social media links seen on the Contributors and chapter pages.

This will be a `linkedin` property on the contributor object with a value of their user name. In the HTML templates we should generate a LinkedIn URL like `"https://www.linkedin.com/in/{{ contributor.linkedin }}/"`.

We will also need a new LinkedIn icon.

- [x] convert existing linkedin.com `website` values to use the `linkedin` property in 2019 and 2020 configs
- [x] add a LinkedIn icon similar in size/style to our other social icons
- [x] render the LinkedIn icon/link on the chapter and Contributors pages

**Comment by bazzadp** [comment]
@catalinred would you be able to come up with an SVG version of LinkedIn icon?

**Comment by catalinred** [comment]
> @catalinred would you be able to come up with an SVG version of LinkedIn icon?

Sure. Is there a branch already for that?

**Comment by bazzadp** [comment]
Not yet!
