### ISSUE TITLE
[Ebook] Author alignment and social links

### ISSUE THREAD

**Issue by rviscomi** [HTTPArchive/almanac.httparchive.org#1140]
For example, see my author bio in the [2019 ebook](https://almanac.httparchive.org/static/pdfs/web_almanac_2019_en.pdf):

![image](https://user-images.githubusercontent.com/1120896/89117279-92a30300-d46a-11ea-8fe6-2bd0c8bdcb3f.png)

I'd suggest two changes:

1. Change the alignment to more closely match the [web](https://almanac.httparchive.org/en/2019/performance#authors) version in which the photo is to the left of the bio.

2. Add footnote citations to the social links so that their URLs are readable in the footer, similar to the links in the bio.

![image](https://user-images.githubusercontent.com/1120896/89117234-4a83e080-d46a-11ea-951c-ce24d66126c6.png)

On a related note, the Appendix B section for contributors has the social icons but no footnotes. Maybe we should drop the social icons from this section of the ebook? Otherwise the footnotes alone would take up pages.

![image](https://user-images.githubusercontent.com/1120896/89117369-2ecd0a00-d46b-11ea-990e-24187633d8b1.png)

@bazzadp what are your thoughts on these changes?

**Comment by bazzadp** [comment]
Yup. Makes sense.
