### ISSUE TITLE
No clickable deeplink for CDN figure 2

### ISSUE THREAD

**Issue by rviscomi** [HTTPArchive/almanac.httparchive.org#1154]
See https://almanac.httparchive.org/en/2019/cdn#fig-2

![image](https://user-images.githubusercontent.com/1120896/89252910-1c78da80-d5e9-11ea-8132-1368f58b9166.png)

I'd expect the text "Figure 2" to link to the URL above, but there is no link. Is this because it is suffixed with `:` rather than `.`? Should be an easy fix.

**Comment by bazzadp** [comment]
Hopefully #1138 will be the longer term fix to prevent this from happening.
