### ISSUE TITLE
Use deep-linked figures as the meta image for social sharing

### ISSUE THREAD

**Issue by rviscomi** [HTTPArchive/almanac.httparchive.org#1155]
Using the [Twitter card validator](https://cards-dev.twitter.com/validator) we can test how chapters would appear in tweets.

For example https://almanac.httparchive.org/en/2019/cdn will appear like this:

![image](https://user-images.githubusercontent.com/1120896/89253163-d4a68300-d5e9-11ea-90e5-4a7c90aa23f3.png)

If the sharer wanted to deep-link to a specific figure like https://almanac.httparchive.org/en/2019/cdn#fig-8, the same image would be used. This is usually ok but specifically for linking figures, in context I think it would be more useful to get a preview of the thing being shared rather than the chapter's illustration.

I'd like to propose a new feature (possibly blocked on #1138) that would dynamically swap the meta images like `<meta property="og:image">` and `<meta name="twitter:image">` with the corresponding figure's image, if available. In this example it would be https://almanac.httparchive.org/static/images/2019/cdn/html_tls_negotiation_time.png:

![CDN chapter figure 8](https://almanac.httparchive.org/static/images/2019/cdn/html_tls_negotiation_time.png)

**Comment by bazzadp** [comment]
We can do some tests but I think that might be impossible. Hash-params are not sent to server as they are meant for the client, so can't change the image server-side, and apparently [Twitter Bot does not execute JavaScript](https://stackoverflow.com/questions/51899920/twitter-card-api-open-twitter-dialog-via-javascript-and-set-meta-tags-dynamica) (or at least didn't 2 years ago) so cannot be done client-side either. So kind of stuck - unless you have any other ideas how to do this?

**Comment by Tiggerito** [comment]
You could create a share on twitter links/buttons next to each image that pass a customised URL with query parameters to enable the server to modify the meta tags. e.g.

https://almanac.httparchive.org/en/2019/cdn?fig=8#fig-8

Here's the docs from Twitter. It looks like you add a data-url attribute to specify a custom destination like that:

https://developer.twitter.com/en/docs/twitter-for-websites/tweet-button/overview

**Comment by bazzadp** [comment]
> You could create a share on twitter links/buttons next to each image that pass a customised URL with query parameters to enable the server to modify the meta tags. e.g.
> 
> https://almanac.httparchive.org/en/2019/cdn?fig=8#fig-8

Could do, but seems a bit hacky to be honest. And it would require either creating a "Tweet this" button, or changing the deep link URLs to include this, causing a page reload when clicking on one of these.

> Here's the docs from Twitter. It looks like you add a data-url attribute to specify a custom destination like that:
> 
> https://developer.twitter.com/en/docs/twitter-for-websites/tweet-button/overview

That's only for the button script. Not sure it's worth adding another external dependency just to create a button - we could do that easily ourselves, but I'd prefer to keep this as a link rather than litter the chapter with blue buttons.

**Comment by bazzadp** [comment]
I tested the [JavaScript option with a test deploy](https://20200804t092305-dot-webalmanac.uk.r.appspot.com/en/2019/javascript#fig-1) and confirmed Twitter doesn't update the image so looks like it still doesn't execute JavaScript.

What do you think @rviscomi - do we look at using URL params and changing this server side? Might be more complicated and fragile as can't use the `querySelector` in Python to interrogate the DOM to get the image URL, and then set the `meta` tag.

**Comment by rviscomi** [comment]
With #1138, URL params like `fig=8` might work but I'm surprised to (finally) learn that anchors like `#fig-8` aren't sent to the server. Given that I'm ok to close this as infeasible.
