### ISSUE TITLE
Contributors flex setting

### ISSUE THREAD

**Issue by bazzadp** [HTTPArchive/almanac.httparchive.org#1162]
We currently flex grow the social icons:

https://github.com/HTTPArchive/almanac.httparchive.org/blob/8318a3208f60664a3d45680d0c1dde13c0edcc87/src/templates/base/2019/contributors.html#L132-L134

This effectively means we bottom align the teams the contributor is in:

![Bottom aligned teams](https://user-images.githubusercontent.com/10931297/89417991-5a7c1880-d727-11ea-845b-5c1a77caae41.png)

Would these be better by removing this `flex: 1` to make them top aligned?

![Top aligned teams](https://user-images.githubusercontent.com/10931297/89418298-c9f20800-d727-11ea-924f-8912a2458dfb.png)

**Comment by rviscomi** [comment]
Make it so!
