### ISSUE TITLE
Viper in 2019 Media chapter?

### ISSUE THREAD

**Issue by bazzadp** [HTTPArchive/almanac.httparchive.org#1182]
As noted in https://github.com/HTTPArchive/almanac.httparchive.org/pull/1181#issue-465147230 the Media chapter has this note:

>Note: this is only looking at the CSS layout for both the viper and the volume of layout content. It is not evaluating the effectiveness of the responsive images or the effectiveness of providing high DPR content.

What does "viper" mean? Is that a typo?

**Comment by colinbendell** [comment]
DPR

**Comment by bazzadp** [comment]
Pardon my ignorance @colinbendell are you saying it is a typo and I can just change it to DPR?

**Comment by colinbendell** [comment]
yep!
