### ISSUE TITLE
ISBN?

### ISSUE THREAD

**Issue by rviscomi** [HTTPArchive/almanac.httparchive.org#1219]
Should we get an [ISBN](https://en.wikipedia.org/wiki/International_Standard_Book_Number) for the ebook and/or print book? Would especially love to hear from anyone with experience in self-publishing. All feedback welcome.

From https://www.myidentifiers.com/identify-protect-your-book/isbn/buy-isbn:
> There are many reasons to purchase an ISBN for your title, including:
>
>- An ISBN improves the likelihood your book will be found and purchased
>- An ISBN links to essential information about your book
>- An ISBN enables more efficient marketing and distribution of your title
>- Most retailers require ISBNs
>- Correct use of the ISBN allows different product forms and editions of a book, printed or digital, to be differentiated clearly, ensuring that customers receive the version they require
>- An ISBN helps you collect and analyze book sales data
>- An ISBN ensures your book’s information will be stored in the [Books In Print](http://www.bowker.com/products/Books-In--Print.html) database
>- Books In Print is consulted by publishers, retailers and libraries around world when searching for title information
>- The ISBN conveys no legal or copyright protection, however, the use of ISBNs for publications is prescribed by law in some countries
>- In some countries a book will be charged higher tax if it does not have an ISBN
>- ISBNs are the global standard for book identification

**Comment by bazzadp** [comment]
This seems like a good resource: https://www.editage.com/info/book-editing-services/articles/10-faqs-on-isbn-every-self-publishing-author-must-know.html as does this: https://editorialservice.com/do-you-need-an-isbn/

In short, an ISBN is not needed for an ebook, but is needed if you want others to sell printed books. It will register your book so make it more likely to appear in book catalogues and review sites like goodreads.com.

If we went with this, we’d need a separate ISBN per format (Printed book, PDF, Mobi...etc. - though only printed book needs ISBN), translation and major edition (year). You can get 10 ISBNs for $295 and 100 ISBNs for $595 so the 100 would probably make most sense.

Note ISBNs are non-transferable and are issued to companies/people and that is company/person is then down as the “publisher of record”. So probably makes sense to get our own ISBN, that get a free or cheap alternative unless we’re happy to be associated with that company/person forever.
