### ISSUE TITLE
Should we remove generate content from git repo?

### ISSUE THREAD

**Issue by bazzadp** [HTTPArchive/almanac.httparchive.org#1221]
@HTTPArchive/developers , question for you all:

We auto generate some content, including:
- Chapters `.html` files (from chapters `.md` files)
- The `sitemap.xml`
- Potentially `featured_chapters.html` (depending on outcome of #1104)
- Ebook `.html` and `.pdfs`

This creates some confusion as searching the code base (e.g. to fix a typo) leads to multiple hits - but only the `.md` files should be edited. It also means some people edit both `.md` and `.html` files when they don't need to.

We could remove these files from the Git repo (and add the relevant `.gitignore` entries to ensure they are not re-uploaded).

The generated HTML files will still be generated, tested and linted as part of our GitHub action so don't think we lose anything with that.

We should also add the `npm run generate` to the `npm run deploy` script as they need to be generated and uploaded to App Engine to actually run the site.

The one downside is developers will now need to run `npm run generate` to generate these `.html` files, to be able to run and be able to develop the website. So a developer just making some CSS changes but nothing else, now has an extra step to complete. Do we see that being a problem?

Thoughts?

**Comment by borisschapira** [comment]
I find it relevant to **remove generated elements from the tracked code**. In the development context, even for CSS only, I don't think the `npm run generate` is any more complicated than installing the dependencies via Python and running the web server. If you do the latter, I doni’ think s.o. will have any difficulties with the former.

**Comment by ibnesayeed** [comment]
I would vote for removing non-source files, unless necessary.

**Comment by bazzadp** [comment]
One thing where storing the assets is useful is when EJS upgrades (like in #1225 ) - we can run the script and see no templates have changed and so know the upgrade does not impact us. In the past we've noticed changes to the HTML generated. Not an insurmountable problem, and it is rare, but it is something that is a little tougher if we do this.
