### ISSUE TITLE
Keeping track of Last Updated timestamps

### ISSUE THREAD

**Issue by bazzadp** [HTTPArchive/almanac.httparchive.org#1224]
We have a need to track the last update time for a page.

This is done for a few different reasons (mostly to do with SEO):
- We have [Article Structured Data](https://developers.google.com/search/docs/data-types/article#article-types) on each page and the `dateModified` is [recommended](https://developers.google.com/search/docs/data-types/article#article-types) - and basically shows as an error if you don't have it.
- Our [sitemap lists it](https://almanac.httparchive.org/sitemap.xml) which Search Engines can use to prioritise which pages to crawl.
- We even talked [in the past about exposing this to the users](https://github.com/HTTPArchive/almanac.httparchive.org/issues/518#issuecomment-555663257)
- We may use this if we ever implement the RSS feed discussed in #1079 

Now it took us a while to get this working, and we use a [GitHub Action](https://github.com/HTTPArchive/almanac.httparchive.org/blob/main/.github/workflows/generate_chapters.yml) which runs on merges to `main` branch, runs [some fancy `sed` commands](https://github.com/HTTPArchive/almanac.httparchive.org/blob/main/src/tools/scripts/update_timestamps_versions.sh) and then opens a pull request to commit the changes. See #1186 as an example.

It also updates the CSS and JS hash to give it a unique value based off of timestamp for cache-busting reasons (e.g. `static/css/2019.css?v=20200730202229`), but I'm less worried about that.

This may sound a bit over the top and convoluted but has several advantages:
- It's automated so doesn't depend on anyone updating the timestamp when making a change
- Doing it after merging avoids merge conflicts if two PRs are altering the same code so it doesn't matter which order they are merged in.
- It doesn't depend on any time settings on people's machines.
- Timestamps should only go forward.

However the big disadvantage is that it produces a second pull request for every commit that changes which is irritating, noisy, and pollutes our git history. We also tried to turn on branch protections in GitHub so tests must pass, but PRs coming from GitHub Actions don't kick off other Github Actions (to avoid recursions!) so they don't run so must be force pushed 😞

**Do we even need to do this?**

My experience is yes - it's good to have a last updated time for an article for all the reasons given above and more. Setting this all the same to the deploy time is just wrong to me (especially as we launch 2020 and future years and likely update past years content less, and less). We also have had indexing problems in the past (see #884) and have still not cleaned these up two months later (though only one 2019 chapter remains unindexed at this time - ironically the French SEO chapter 😀 ). So, despite being small, Google doesn't crawl our entire site like it could and we appear to have a very small crawl budget - so we should prioritise recently updated content.

**Is there a better way to handle the timestamps?**

In the past we tried to do it based on GitHub commit time (see #317), but as soon as we commit that obviously updates that and problems ensue. Perhaps if we do #1221 and stop generating the site, then we should tackle this at the same time and  just grab the last committed timestamp direct from the `origin/main` branch, update the deployment, but NOT commit it back to Git? It feels a little flakey basing this on Git commit timestamps though but, on the other hand, it's not super critical if it ever goes wrong.

Any other ideas?

**Comment by rviscomi** [comment]
> Do we even need to do this? My experience is yes - it's good to have a last updated time for an article for all the reasons given above and more. Setting this all the same to the deploy time is just wrong to me (especially as we launch 2020 and future years and likely update past years content less, and less). 

Could you elaborate on what's wrong to you? I think if we have a way to distinguish which files changes in the deploy, this would be ok.

Also curious to hear from @HTTPArchive/developers

**Comment by bazzadp** [comment]
As discussed offline:

You propose:
- We have an `src/config/page_timestamps.json` file with each filename, a hash (based on contents), an "initial published" date and a "last updated" date (initially populated from metadata).
- On deploy date we run a script to read this file, hash each file, compare it with the previous hash and, if different, update the timestamp to today.
- Save that JSON file with updated timestamps.
- Read that JSON file dynamically in our server on start up so can expose the data to the Jinja2 templates.
- We submit one PR to update this file in git on deploy date. Instead of one PR for each merge. This reduces the noise.

That could work!

We could potentially add this update script to the "Generate Ebooks" workflow as already need to run that before deploy, and it already raises a PR. We could then rename that to "Prepare for Deploy" or something.

Anyone from @HTTPArchive/developers fancy this? @ibnesayeed this sounds right up your street 😁

**Comment by bazzadp** [comment]
I'm gonna tackle this one as it's starting to annoy me now too and think we have a path forwards. If anyone else has made a start on it already let me know and I'll back off (or work with you on it if you want!).

**Comment by ibnesayeed** [comment]
> @ibnesayeed this sounds right up your street

I am sorry, I did not notice this before as I was super busy in wrapping my graduation up (breaking news, I have a doctorate degree now). :tada:

> We have an `src/config/page_timestamps.json` file with each filename, a hash (based on contents), an "initial published" date and a "last updated" date (initially populated from metadata).

I think we do not need yet another file to keep track of it, we can leverage Git fro that. Simply, tag the repo each time the site is deployed, and then we can get the info by comparing changes (and listing changed files) since the last time a deploy related tag was made.

Slightly unrelated and more demanding, but I would really like to see built-in [Memento support](https://tools.ietf.org/html/rfc7089) in Web Almanac, so clients can content negotiate on the time dimension and resolve to a prior state of a page. This will have one more justification for having a dynamic web server instead of serving pages as static files.

**Comment by bazzadp** [comment]
> I think we do not need yet another file to keep track of it, we can leverage Git fro that. Simply, tag the repo each time the site is deployed, and then we can get the info by comparing changes (and listing changed files) since the last time a deploy related tag was made.

Possibly, but without tracking the timestamp in a file somewhere won't we have to iterate through all tags to get the last updated timestamp for each page? And I want to avoid having to change each chapter as it leads to a huge number of meaningless commits to each chapter just to update the timestamp. One commit to one central file is a lot less noise.

> Slightly unrelated and more demanding, but I would really like to see built-in Memento support in Web Almanac, so clients can content negotiate on the time dimension and resolve to a prior state of a page. This will have one more justification for having a dynamic web server instead of serving pages as static files.

Not sure I agree. I don't think we need to expose typos and other corrections and, other than that, the chapters are basically moments in time. To compare changes look at 2019 version of that chapter versus 2020. Don't see why you need to see all the edits within a year - we have git for that.

**Comment by ibnesayeed** [comment]
> Possibly, but without tracking the timestamp in a file somewhere won't we have to iterate through all tags to get the last updated timestamp for each page?

Not really. You compare current `HEAD` with the last deploy tag to get a list of changed files, then filter out files you don't care about, and then `checkout` the last deploy tag to see the timestamp of each file you care about.

**Comment by ibnesayeed** [comment]
> Not sure I agree. I don't think we need to expose typos and other corrections and, other than that, the chapters are basically moments in time. To compare changes look at 2019 version of that chapter versus 2020. Don't see why you need to see all the edits within a year - we have git for that.

I think we can discuss this elsewhere later, because it is a more involved topic that this thread can afford.
