### ISSUE TITLE
Add result spreadsheet metadata to each chapter

### ISSUE THREAD

**Issue by rviscomi** [HTTPArchive/almanac.httparchive.org#1233]
Before the August crawl completes and analysts begin running their queries, we need to provide spreadsheets for them to save their results and share with the rest of the content team. Let's use this issue to track progress on getting these sheets set up. Here are the tasks for each chapter:

- make a copy of the [template](https://docs.google.com/spreadsheets/d/1PTkM-V33bEvbNIeTJC27DKijwGRs2D-_9poyCicTWDg/edit?usp=sharing)
  - name the copy "[CHAPTER TITLE] results (Web Almanac 2020)"
  - select "Share it with the same people" and "Copy comments"
- update the `~results-sheet` placeholder in the chapter issue metadata
- leave a [comment](https://github.com/HTTPArchive/almanac.httparchive.org/issues/898#issuecomment-677046414) in the issue, because editing the metadata doesn't trigger notifications
```
I've updated the chapter metadata at the top of this issue to link to the [public spreadsheet][~results-sheet] that will be used for this chapter's query results. The sheet serves 3 purposes:

1. Enable authors/reviewers to analyze the results for each metric without running the queries themselves
2. Generate data visualizations to be embedded in the chapter
3. Serve as a public audit trail of this chapter's data collection/analysis, linked from the chapter footer

[~results-sheet]: https://docs.google.com/spreadsheets/d/1sMWXWjMujqfAREYxNbG_t1fOJKYCA6ASLwtz4pBQVTw/edit?usp=sharing
```
- invite analysts to the sheet as editors, using their emails from the draft doc

Todo list of chapters:

- [x] 1. CSS
- [x] 2. JavaScript
- [x] 3. Markup
- [x] 4. Fonts
- [x] 5. Media
- [x] 6. Third Parties
- [x] 7. SEO
- [x] 8. Accessibility
- [x] 9. Performance
- [x] 10. Privacy
- [x] 11. Security
- [x] 12. Mobile Web
- [x] 13. Capabilities
- [x] 14. PWA
- [x] 15. CMS
- [x] 16. Ecommerce
- [x] 17. Jamstack
- [x] 18. Page Weight
- [x] 19. Compression
- [x] 20. Caching
- [x] 21. Resource Hints
- [x] 22. HTTP/2

**Comment by rviscomi** [comment]
I've made copies of the results sheet for each chapter. They should all be accessible in [this Drive folder](https://drive.google.com/drive/folders/1ZmW8dZsSFuEhh2o1VqLIlZTljiGppw8p?usp=sharing). @obto do you have time today to update the chapter issues with their respective sheet links?

**Comment by obto** [comment]
All chapters have been updated, and authors and analysts invited to their respective google sheets. Closing this out
