### ISSUE TITLE
Comma separating two contributors

### ISSUE THREAD

**Issue by rviscomi** [HTTPArchive/almanac.httparchive.org#1247]
On chapter pages like [Media](https://almanac.httparchive.org/en/2019/media), when there are two authors or reviewers, the contributor names are separated by ", and".

I would only expect the names to be separated by "and". For example:

A
A and B
A, B, and C

![image](https://user-images.githubusercontent.com/1120896/91072368-6745ab00-e607-11ea-82ed-00eafb1a3173.png)

This affects both the chapter pages and the ebook.

**Comment by bazzadp** [comment]
Presume you still want an oxford comma for 3 or more names?

**Comment by rviscomi** [comment]
Yes, clarified the desired behavior.

**Comment by bazzadp** [comment]
Added another clarification that this impacts both chapter and ebook.

A bit of Jinja2 templating dev if any of the @HTTPArchive/developers want to take a stab at it? Good one for learning how our templating works and happy to give any guidance here!
