### ISSUE TITLE
Finalize assignments: Chapter 11. PWA

### ISSUE THREAD

**Issue by rviscomi** [HTTPArchive/almanac.httparchive.org#13]
Section | Chapter | Authors | Reviewers
-- | -- | -- | --
II. User Experience | 11. PWA | @tomayac @jeffposnick | @hyperpress

**Due date:** To help us stay on schedule, please complete the action items in this issue by June 3.

**To do:**
- [x] Assign subject matter experts (coauthors)
- [x] Finalize peer reviewers
- [x] Finalize metrics

**Current list of metrics:**

- % of pages with SW installs
- Manifest
- Stats on different service worker events
- Stats on different web app manifest properties
- Workbox adoption/usage
- beforeinstallprompt usage

👉**AI (coauthors):** Peer reviewers are trusted experts who can support you when brainstorming metrics, interpreting results, and writing the report. Ideally this chapter will have multiple reviewers who can promote a diversity of perspectives. You currently have 1 peer reviewer.

👉 **AI (coauthors):** Finalize which metrics you might like to include in an annual "state of PWAs" report powered by HTTP Archive. Community contributors have initially sketched out a few ideas to get the ball rolling, but it's up to you, the subject matter experts, to know exactly which metrics we should be looking at. You can use [the brainstorming doc](https://docs.google.com/document/d/1sCIMeErYvaQb5x9Acdb6ImYdn0-buHRhYGvz2HoysmM/edit#heading=h.iznoa2266s2c) to explore ideas.

The metrics should paint a holistic, data-driven picture of the PWA landscape. The HTTP Archive does have its limitations and blind spots, so if there are metrics out of scope it's still good to identify them now during the brainstorming phase. We can make a note of them in the final report so readers understand why they're not discussed and the HTTP Archive team can make an effort to improve our telemetry for next year's Almanac.

**Next steps:** Over the next couple of months analysts will write the queries and generate the results, then hand everything off to you to write up your interpretation of the data.

**Additional resources:**
- [All chapter assignments](https://github.com/HTTPArchive/httparchive.org/issues/140)
- [Project timeline](https://docs.google.com/spreadsheets/d/1LR29JpI2XJSjan_z6uP1YpRy4EYYivYZPqCIG-9sfFY/edit?usp=sharing)
- [About the project](https://discuss.httparchive.org/t/planning-the-web-almanac-2019/1553)

**Comment by mikegeyser** [comment]
Hi! 

A quick question. Is it possible from the data set to get an idea of number (or %) of installs? (Sorry, I genuinely don't know.) 

If we can, then wouldn't it be interesting to see what form factors (mobile/desktop/etc) PWAs were being installed in? Especially with the recent drive for PWA adoption on desktop. 

(Ok, so technically two questions.)

**Comment by jeffposnick** [comment]
I'll defer to @tomayac in case he has any opinions otherwise, but both that list of metrics and the suggested peer reviewer (thanks @hyperpress!) seem good to me.

**Comment by hyperpress** [comment]
Thanks all. Good to go here.

**Comment by rviscomi** [comment]
@mikegeyser what you're asking about would need to come from a field dataset like the Chrome UX Report, which doesn't include installs/PWA stats. To my knowledge I'm not aware of another dataset that includes those metrics. HTTP Archive data could tell us how many sites are PWA-capable, but not necessarily the user experience of installing them.

**Comment by tomayac** [comment]
Sounds all good to me.

**Comment by Eccenux** [comment]
Note that Chrome/Blink requires an app to have a PNG image in the manifest of at least 144px in size. Only then it can be installed. So to be installable the manifest must contain at least the text `144x144` and `image/png`. Official criteria talk about 192 and 512px but they either don't check this or accept SVG too.

Anyway I think it would be interesting to know what types of icons and what sizes are found in manifests.

**Comment by rviscomi** [comment]
@tomayac @jeffposnick I know you've both done some HA analysis in the past. Would you be interested in writing the queries for this chapter?

**Comment by rviscomi** [comment]
@tomayac @jeffposnick @hyperpress if everyone is happy with the list of metrics in https://github.com/HTTPArchive/almanac.httparchive.org/issues/13#issue-446806272 could you tick the checkbox and close this issue? I'd also recommend finding at least one more peer reviewer if possible.

@hyperpress also, please accept your invitation to join the reviewers team.

**Comment by hyperpress** [comment]
I don't remember seeing an invite. Can you direct me to the correct
location, or resend it to me? Thanks very much.

**Comment by rviscomi** [comment]
@hyperpress sure, just resent the invitation. You can also accept it at https://github.com/HTTPArchive. Thanks!

**Comment by hyperpress** [comment]
Done. Thanks again. I'll dig into the rest tomorrow. Looking forward to
collaboration ahead.

**Comment by hyperpress** [comment]
I've reached out to peers over in @polymer Lit General Channel to see if we can add another reviewer. But I believe metrics look good for moving ahead, and for closing the issue for now. We can adjust if need be.
