### ISSUE TITLE
Implement Chapter page design

### ISSUE THREAD

**Issue by rviscomi** [HTTPArchive/almanac.httparchive.org#130]
See below for the Chapter mockup. This will be the design template for non-home pages.

@HTTPArchive/developers 

![chapter-001f](https://user-images.githubusercontent.com/1120896/63997472-9b59bf00-cacc-11e9-9c34-b9f722e05d1d.jpg)

**Comment by tanhengyeow** [comment]
Some questions I have in mind:
1. Is the side navigation menu's position intended (some margin to the right)? Or should we flush it to the left?
2. I've not looked at `generate_chapters.py` in detail yet but from the looks of it it
   - HTML rendering is covered for this part:
![image](https://user-images.githubusercontent.com/25320782/64004342-a6e6cd80-cb40-11e9-8035-479c1634b6a3.png)
   - Graph visualization is covered for this part:
![image](https://user-images.githubusercontent.com/25320782/64004361-b49c5300-cb40-11e9-9ffa-d85a358c3d50.png)

Are we missing anything needed to implement this page? For e.g.
1. Mapping of authors to chapters
2. Source query link for the visualization

**Comment by rviscomi** [comment]
> Is the side navigation menu's position intended (some margin to the left)? Or should we flush it to the left?

There's a grid layout being used where the main body of the page is fixed width and centered. Also see how it aligns with the footer content. I think we might also want to change the header to fit within this same grid, so the background is 100% but the header contents are fixed width and centered like the footer.

> HTML rendering is covered for this part:

This is just an example of embedding a code sample, you can disregard for now.

> Chart visualization is covered for this part:

Data visualization will be covered by #114 so it can be left out of this issue's scope.

> Mapping of authors to chapters

Handled by #70 

> Source query link for the visualization

The actual contents of the chapter are still being written, so for now you can use the placeholder content written by @mikegeyser: https://github.com/HTTPArchive/almanac.httparchive.org/blob/master/src/content/en/2019/javascript.md

**Comment by rviscomi** [comment]
Mobile designs are also available here: https://drive.google.com/open?id=1ud4iZWxUB7vMZlcKUrPUkLuT1haBV_B6

**Comment by rviscomi** [comment]
@HTTPArchive/developers is anyone available to work on this?

**Comment by tyohan** [comment]
We need this before able to work on #199. So I'll try to do this as well. @tanhengyeow did you work on this already? do you want to push on a working branch so I can continue it from there?

**Comment by tanhengyeow** [comment]
Hi @tyohan 

I haven't started work on this yet, have been occupied with stuff. Please go ahead if you would like to work on it 😄

**Comment by tyohan** [comment]
@rviscomi i saw the methodology page already implemented the design but it use it's own stylesheet. I think we can reuse the stylesheet for this chapter page but then we need to refactor the methodology page to use some shared CSS classes. 

What do you think? 
Keep it in separate stylesheet or refactor the methodology page and reuse the stylesheet.

**Comment by rviscomi** [comment]
Yes good catch! Methodology and Chapter pages both have a sidebar and a main content area and it would make a lot of sense to consolidate these into a reusable style in the global `2019.css` stylesheet. Also, for both pages' mobile RWD, the sidebar collapses into an expandable "Index":

![image](https://user-images.githubusercontent.com/1120896/67264325-c7fcd800-f478-11e9-8278-ac83298d4373.png)

![image](https://user-images.githubusercontent.com/1120896/67264336-cfbc7c80-f478-11e9-92af-6a5c69750085.png)

Any JS to support this functionality should also be in a reusable/cacheable script.

**Comment by tyohan** [comment]
@rviscomi @mikegeyser I'll continue to work on this after PR #251. Some stuff that I will work on within this week
- generate author list with macro
- create prev next button with macro

**Comment by mikegeyser** [comment]
Would it make sense to generate it statically using an EJS template? It doesn't really need to be done at runtime, because it won't really change?

**Comment by rviscomi** [comment]
My only hesitation is that it requires everyone to know that a change to the contributors config must also be followed by regenerating the chapter contents and rendering new author markup. WDYT?

**Comment by tyohan** [comment]
I prefer to do it on rendering so less manual code generation whenever we have some updates.

**Comment by mikegeyser** [comment]
We could add a [commit hook](https://github.com/typicode/husky) that generates the output automatically? 

Although I don't really mind, it was just an idea, and perhaps what is simplest and most expedient would be best at this point. :)

**Comment by tyohan** [comment]
Yes, that's possible too. But anyway i just made it with a mix of macro and code in app router.
