### ISSUE TITLE
Write content: Chapter 1. JavaScript

### ISSUE THREAD

**Issue by rviscomi** [HTTPArchive/almanac.httparchive.org#131]
Part | Chapter | Authors | Reviewers | Analysts | Metrics | Analysis
-- | -- | -- | -- | -- | -- | --
I. Page Content | 1. JavaScript | @addyosmani @housseindjirdeh @mathiasbynens | @rwaldron @RReverser | @rviscomi | #3 | #82

### Due by: October 7

- [x] Review the [results spreadsheet](https://docs.google.com/spreadsheets/d/1kBTglETN_V9UjKqK_EFmFjRexJnQOmLLr-I2Tkotvic/edit?usp=sharing) and work with your analyst(s) (@rviscomi) if you have any questions about the data.
- [x] Write the contents of your chapter and get it peer reviewed (@rwaldron @RReverser).
- [x] File a PR to merge your written contents in markdown format to the [src/content/en/2019](https://github.com/HTTPArchive/almanac.httparchive.org/tree/master/src/content/en/2019) directory.

Refer to the [Authors' Guide](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Authors'-Guide) for writing advice.

**Comment by rviscomi** [comment]
I just realized the [results spreadsheet](https://docs.google.com/spreadsheets/d/1kBTglETN_V9UjKqK_EFmFjRexJnQOmLLr-I2Tkotvic/edit?usp=sharing) only included a handful of metrics. I've gone through all of the queries, [updated](https://github.com/HTTPArchive/almanac.httparchive.org/pull/152) them to use client/percentiles, and saved their results to the sheet.

@mathiasbynens @addyosmani @housseindjirdeh you should have everything you need to write the chapter now. Friendly reminder that we're looking to have the first draft done and ready for review by October 7 so that we can launch in time for CDS on November 4. Houssein, did Addy mention that he was hoping you'd start the draft? 😁

**Comment by housseindjirdeh** [comment]
Yep I was glad to start writing the draft :)

Complete draft is here:m https://docs.google.com/document/d/1BxNG02SMojcWyVTSInUoVd0KlPQHmI2Wsc892vHJlnE/edit?usp=sharing

🚀

**Comment by obto** [comment]
@housseindjirdeh Can you give me (david@lookzook.com) and Paul (paul@httparchive.org) access to the document?
