### ISSUE TITLE
Write content: Chapter 2. CSS

### ISSUE THREAD

**Issue by rviscomi** [HTTPArchive/almanac.httparchive.org#132]
Part | Chapter | Authors | Reviewers | Analysts | Metrics | Analysis
-- | -- | -- | -- | -- | -- | --
I. Page Content | 2. CSS | @una @argyleink | @meyerweb @huijing | @rviscomi | #4 | #83

### Due by: October 7

- [x] Review the [results spreadsheet](https://docs.google.com/spreadsheets/d/1uFlkuSRetjBNEhGKWpkrXo4eEIsgYelxY-qR9Pd7QpM/edit?usp=sharing) and work with your analyst(s) (@rviscomi) if you have any questions about the data.
- [ ] Write the contents of your chapter and get it peer reviewed (@meyerweb @huijing).
- [ ] File a PR to merge your written contents in markdown format to the [src/content/en/2019](https://github.com/HTTPArchive/almanac.httparchive.org/tree/master/src/content/en/2019) directory.

Refer to the [Authors' Guide](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Authors'-Guide) for writing advice.

**Comment by argyleink** [comment]
can you link me something that explains this chapter more please? i'm not feeling confident in what that task entails, thanks!

**Comment by rviscomi** [comment]
I threw some advice in the [Authors' Guide](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Authors'-Guide#writing-the-chapter) wiki. Let me know if you still have unanswered questions and I can iterate on the wiki.

**Comment by rviscomi** [comment]
👋 Greetings! Just checking in to make sure this is progressing and remind you of the October 7 deadline timed so we can launch at Chrome Dev Summit.

The checklist above indicates that you still need to review the results, write content, and get it reviewed. Feel free to reach out if you have any questions about the process.

**Comment by argyleink** [comment]
we're making progress, stay tuned
