### ISSUE TITLE
Write content: Chapter 5. Third Parties

### ISSUE THREAD

**Issue by rviscomi** [HTTPArchive/almanac.httparchive.org#134]
Part | Chapter | Authors | Reviewers | Analysts | Metrics | Analysis
-- | -- | -- | -- | -- | -- | --
I. Page Content | 5. Third Parties | @patrickhulce | @simonhearne @flowlabs @jasti @zeman | @patrickhulce | #8 | #86

### Due by: October 7

- [x] Write the contents of your chapter and get it peer reviewed (@simonhearne @flowlabs @jasti @zeman).
- [ ] File a PR to merge your written contents in markdown format to the [src/content/en/2019](https://github.com/HTTPArchive/almanac.httparchive.org/tree/master/src/content/en/2019) directory.

Refer to the [Authors' Guide](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Authors'-Guide) for writing advice.

**Comment by rviscomi** [comment]
👋 Greetings! Just checking in to make sure this is progressing and remind you of the October 7 deadline timed so we can launch at Chrome Dev Summit.

The checklist above indicates that you still need to write content and get it reviewed. Feel free to reach out if you have any questions about the process.

**Comment by patrickhulce** [comment]
Alright @simonhearne @flowlabs @jasti @zeman, it's your time to shine! :)

Comments/feedback/reviews/edits welcome: https://docs.google.com/document/d/1q52f7pRSO0g6J1zbiVq-iVCYdGs6UdYQTCLOAFglz94/edit?usp=sharing

**Comment by patrickhulce** [comment]
Hey reviewers! Friendly reminder to try to get your thoughts in on the chapter **by EOD tomorrow** if you'd like your feedback to be included, so I can turn it around over the weekend.

**Comment by rviscomi** [comment]
🛎 @simonhearne @zeman @flowlabs @jasti

**Comment by rviscomi** [comment]
@patrickhulce could you start a PR with the markdown version of your doc and perhaps we can get it peer reviewed on the PR?

**Comment by patrickhulce** [comment]
Sure @rviscomi  👍

**Comment by patrickhulce** [comment]
Reviewers please see https://github.com/HTTPArchive/almanac.httparchive.org/pull/189 instead of the Google doc now :)
