### ISSUE TITLE
Write content: Chapter 13. Ecommerce

### ISSUE THREAD

**Issue by rviscomi** [HTTPArchive/almanac.httparchive.org#135]
Part | Chapter | Authors | Reviewers | Analysts | Metrics | Analysis
-- | -- | -- | -- | -- | -- | --
III. Content Publishing | 13. Ecommerce | @samdutton @alankent | @voltek62 @wizardlyhel | @rviscomi | #15 | #94

### Due by: October 7

- [x] Review the [results spreadsheet](https://docs.google.com/spreadsheets/d/1FUMHeOPYBgtVeMU5_pl2r33krZFzutt9vkOpphOSOss/edit?usp=sharing) and work with your analyst(s) (@rviscomi) if you have any questions about the data.
- [x] Write the contents of your chapter and get it peer reviewed (@voltek62 @wizardlyhel).
- [x] File a PR to merge your written contents in markdown format to the [src/content/en/2019](https://github.com/HTTPArchive/almanac.httparchive.org/tree/master/src/content/en/2019) directory.

Refer to the [Authors' Guide](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Authors'-Guide) for writing advice.

**Comment by alankent** [comment]
Feel free to ping me again in a few days time. Trying to stay hyper
focussed on AMP Contributor summit which is running behind schedule.
Thanks!
Alan

**Comment by wizardlyhel** [comment]
Looking forward for reviewing this! The data analysis looks amazing!

**Comment by samdutton** [comment]
Thanks for this! Will check it out shortly.

**Comment by rviscomi** [comment]
@alankent @samdutton note that as part of the fix for #165, I've had to rerun all of the queries for this chapter to include OpenCart data. The aggregate data has changed vary slightly as a result. Just FYI in case you've already started writing about the specific values.

**Comment by rviscomi** [comment]
Just checking in to say I'm happy to see this moving along! Thanks everyone for your help getting this launched on time! 🤜💥 🤛

**Comment by voltek62** [comment]
@samdutton Are you ready to merge into  src/content/en/2019 directory ?
