### ISSUE TITLE
Highlight H4s in sidebar TOC

### ISSUE THREAD

**Issue by rviscomi** [HTTPArchive/almanac.httparchive.org#1363]
The green "you are here" indicator in the Table of Contents sidebar appears to only highlight H1-3 content. As you scroll through subsections of H4s, the indicator doesn't highlight those nested headings. It only seems to be updated when a new H1-3 comes into view. This causes unexpected behavior, like when scrolling up, a long subsection doesn't update the indicator:

1. Go to https://almanac.httparchive.org/en/2019/performance#conclusion
2. Scroll up into the FID section above
3. Indicator is stuck on "Conclusion" until the FID H3 becomes visible

![image](https://user-images.githubusercontent.com/1120896/96186829-feddc080-0f09-11eb-8a31-24b9b42e4968.png)

Should the indicator also highlight H4s?

**Comment by SaptakS** [comment]
I can work on this if no one has started yet.
