### ISSUE TITLE
Make 2020 the default year

### ISSUE THREAD

**Issue by rviscomi** [HTTPArchive/almanac.httparchive.org#1381]
Right now, traffic to almanac.httparchive.org (no file path) is redirected to the 2019 landing page.

Let's redirect that traffic to the 2020 landing page to make readers aware that 2020 is on the way and start generating interest/anticipation. We don't need to promote the exact release date yet, because we'll make a big announcement when it's ready.

This should be a simple config change to the server. Any @HTTPArchive/developers interested to take this? Any other thoughts on this, @bazzadp?

**Comment by bazzadp** [comment]
Changing the default is really easy as you say but the page is a bit short at the moment in my opinion. It really is a place holder.

I had planned to add some quotes about the 2019 edition and the rest of the home page content but never got round to it. It’s a long weekend here this weekend so should have some time, so let me have a look at that before we make this change.

Also, while we’re always happy to take on new contributors, I think the core writing, reviewing and analysis teams are set for 2020 so what do you think about replacing that “Join the Team” primary CTA with a “Read 2019 Edition” button instead? I just worry that “Coming Soon” could mean that some new visitors miss the fact that we’ve a wealth of content from 2019 to read while they wait!

**Comment by rviscomi** [comment]
Good point about not needing new contributors. Would those content changes require retranslation or is it ok for some languages to be out of sync?

**Comment by bazzadp** [comment]
They can be out of sync.

Depends what I come up with. I think a “Read 2019 Edition” could be auto translated with Google Translate at least for an initial stab at it, and the Contributors section could come straight from 2019 and Methodology would only require small tweaks so might be able to figure out myself with a bit of Google Translate.

If we add a Quotes section that would require an actual translation but can try to make that section optional.

Of course if any of the @HTTPArchive/translators want to review and pull request I can up with and review language or fill in the bits I couldn’t do, that would be greatly appreciated. Will tag them in it for review.
