### ISSUE TITLE
Overflow of the language picker divider

### ISSUE THREAD

**Issue by rviscomi** [HTTPArchive/almanac.httparchive.org#1386]
![image](https://user-images.githubusercontent.com/1120896/97094764-eebe9300-1625-11eb-8b85-aa437ad35d87.png)

The divider in the language picker appears to be exceeding the width of the select button, even though the options may be wider than the button itself.

This seems to be an edge case when content is only available in English, which would only affect the 2020 chapters.

**Comment by bazzadp** [comment]
I wonder if we should just remove this dotted line? We don't use it in other places - for example when a future year version of a page doesn't exist we offer that years home page, but don't separate this with a dotted line:

![image](https://user-images.githubusercontent.com/10931297/97100625-417f6580-168d-11eb-92bd-2b25b764ff5b.png)

So either should remove the dotted line completely, or if we can fix it, then maybe should add it to above as well?
