### ISSUE TITLE
Allow auto deployment of test versions to App Engine

### ISSUE THREAD

**Issue by bazzadp** [HTTPArchive/almanac.httparchive.org#1387]
It can be handy to build a test deployment for a branch as easier to review the pull request once you see something in action. We've used this a few times and it's quite handy - especially for those without the full dev environment set up or less technical in nature.

This will be especially useful as chapters start to be submitted by authors now.

Thoughts:
- Auto-deploy on opening a pull request with `.*py`, `*.json`, `.*md`, `.*html`, `*.js` or `.css` (i.e. basically everything but PRs with only `*.sql` files). Or maybe just on every PR open if easier?
- Only deploy on completion of successful build.
- Ability to redeploy somehow (e.g. if a certain comment (`GitHub deploy`) or label is added?) as I think redeploying on every push to an open pull request could be too much.
- Run through GitHub actions.
- The action should comment on the PR with the test deploy URL.
- Also add ability to manually deploy for a branch
- What about auto deploying a test version on merge to master as well?
- Should have some clear down job of test deployments - either when PR is accepted, or nightly/weekly.
- Need to keep our App Engine account secure but tested using GitHub secrets and believe it can be made secure (will test some more).

We've got a service account set up so will start testing this but opening this issue to track this and invite comments/suggestions.

If this goes well, perhaps could consider deploying to prod as well through manual triggering of a separate action? Will open a separate issue for that once this one is resolved as it has other things to consider e.g. version numbering, how to update release (I've [an open issue with GitHub CLI](https://github.com/cli/cli/issues/1997) that would be needed to fully automate this)) and when to auto deploy. But noting here as long term goal.

**Comment by rviscomi** [comment]
> Auto-deploy on opening a pull request with .*py, *.json, .*md, .*html, *.js or .css (i.e. basically everything but PRs with only *.sql files). Or maybe just on every PR open if easier?

A different heuristic that could be useful may be "did any of the prod files change as a result of building the PR?" For sql the answer would be no, so nothing to deploy/stage.

**Comment by bazzadp** [comment]
As discussed on slack, closing this until Github gives us better ways to restrict access to secrets to certain branches or users.
