### ISSUE TITLE
Add a section on GitHub Desktop to the Git Guide wiki

### ISSUE THREAD

**Issue by bazzadp** [HTTPArchive/almanac.httparchive.org#1397]
Does anyone here use GitHub Desktop and fancy writing a little about it in our [Git Guide wiki](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Git-Guide) for future new joiners to the project?

Know some of you use it and I feel it’s a big missing piece from that guide but I don’t know it at all to be honest, so would prefer someone else write this up rather than me and all my command line prejudices

**Comment by Tiggerito** [comment]
Do you want a new section related to it, or should I intertwine 'how to' bits in with your instructions.  e.g. add the GitHub Desktop way after your command lines. Probably screenshots would be self explanatory in many cases.

I also use TortoiseGit  which is worth a mention but I don't think needs full instructions. It basically adds icons and menus to windows explorer so that you can use the GUI to do git commands.

**Comment by bazzadp** [comment]
I think a new section at the bottom and link mentions of it previously to that.

Yeah let’s leave Tortoise Git out for now.

**Comment by Tiggerito** [comment]
What's the proper way to edit a wiki? Just inline?

And how do I properly add images?

**Comment by bazzadp** [comment]
> What's the proper way to edit a wiki? Just inline?

Yup. It has a revision history so easy enough to revert.

> And how do I properly add images?

Easiest way I’ve found is paste an image in a comment on a real issue, GitHub then uploads the image and enters the markdown for you. Then copy that markdown and paste to wiki, and delete the comment instead of committing it. Seems a bit of a random way of going about it but it works! Just don’t actually commit the comment on the completely unrelated issue! 😀

**Comment by rviscomi** [comment]
^ Same!

**Comment by Tiggerito** [comment]
See what you think.

**Comment by bazzadp** [comment]
Looks great! Thanks for that. Only thing I notice is there's no discussion on forks. Think you worked in the main repo mostly so maybe that's why. Any ideas how forks work in GitHub desktop to resync back to original repo?

**Comment by Tiggerito** [comment]
I'll work on something to say. I don't think the app is much involved in forking. The main difference is you pull the forked repository and the process is different when merging back, which you do on the website.

And I use your set of commands to re-create the forks main/master branch before creating my own branch.

**Comment by bazzadp** [comment]
> And I use your set of commands to re-create the forks main/master branch before creating my own branch.

Yeah that was main thing I was asking about. Ok so no easier way to do this in GitHub Desktop. Worth saying that at least anyway.

Rest looks great so add that and think we’re done. Thanks again for adding this.

**Comment by Tiggerito** [comment]
Added some stuff. Can people send feedback if there are inaccuracies? I feel like a novice teaching experts. That's probably why I rely on GUIs to do it for me 😂

**Comment by bazzadp** [comment]
Looks good to me! Closing this. Thanks a lot @Tiggerito - hopefully this will be useful to people in future!
