### ISSUE TITLE
Add more content to 2020 Methodology page

### ISSUE THREAD

**Issue by bazzadp** [HTTPArchive/almanac.httparchive.org#1404]
Following on from #1383 we merged this without a full review so raising separate issue for this.

- [ ] - @rviscomi talked about adding content on CSS and Rework AST
- [ ] - Number of queries is currently set to TBC

**Comment by rviscomi** [comment]
I think the only thing we should add is related to the CSS tools. What I said about COVID was that it's a better fit for the Foreword than Methodology.

**Comment by bazzadp** [comment]
Cool - updated first comment. And this just reminded me to add another issue for the Foreword 😀
