### ISSUE TITLE
Write content: Chapter 6. Fonts

### ISSUE THREAD

**Issue by rviscomi** [HTTPArchive/almanac.httparchive.org#143]
Part | Chapter | Authors | Reviewers | Analysts | Metrics | Analysis
-- | -- | -- | -- | -- | -- | --
I. Page Content | 6. Fonts | @davelab6 @zachleat | @hyperpress @AymenLoukil | @tjmonsi @rviscomi | #7 | #87

### Due by: October 7

- [x] Review the [results spreadsheet](https://docs.google.com/spreadsheets/d/108g6LXdC3YVsxmX1CCwrmpZ3-DmbB8G_wwgQHX5pn6Q/edit?usp=sharing) and work with your analyst(s) (@tjmonsi  @rviscomi) if you have any questions about the data.
- [x] Write the contents of your chapter and get it peer reviewed (@hyperpress @AymenLoukil).
- [x] File a PR to merge your written contents in markdown format to the [src/content/en/2019](https://github.com/HTTPArchive/almanac.httparchive.org/tree/master/src/content/en/2019) directory.

Refer to the [Authors' Guide](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Authors'-Guide) for writing advice.

**Comment by rviscomi** [comment]
Checking in. Any questions about the [results](https://docs.google.com/spreadsheets/d/108g6LXdC3YVsxmX1CCwrmpZ3-DmbB8G_wwgQHX5pn6Q/edit?usp=sharing)? If not we can check off the first item.

**Comment by rviscomi** [comment]
👋 Greetings! Just checking in again to make sure this is progressing and remind you of the October 7 deadline timed so we can launch at Chrome Dev Summit.

The checklist above indicates that you still need to review the results, write content, and get it reviewed. Feel free to reach out if you have any questions about the process.

**Comment by rviscomi** [comment]
🛎 just a ping to see if any progress has been made on this. Let me know!

**Comment by zachleat** [comment]
@rviscomi I’m going through this now—hope to have a preliminary draft together by tomorrow morning!

**Comment by zachleat** [comment]
Put up an early PR here https://github.com/HTTPArchive/almanac.httparchive.org/pull/192 and forwarded it on to @davelab6 👍

**Comment by rviscomi** [comment]
Fixed by #370
