### ISSUE TITLE
Overflow of the contributors section on the 2020 home page 

### ISSUE THREAD

**Issue by rviscomi** [HTTPArchive/almanac.httparchive.org#1433]
![image](https://user-images.githubusercontent.com/1120896/98418708-858d4580-2051-11eb-8cff-8b85df5a16a9.png)

The "120" seems to be too big and the red character with the markup symbols is overlapping with the graphic in the previous section.

The issue may just be that there's not enough whitespace between the first and second sections. @bazzadp did you remove some of the 2020 home page styles in anticipation of normalizing it with 2019? If we have a 2020 featured chapter section maybe this is less of an issue.

**Comment by bazzadp** [comment]
Look at latest main branch where we have 2019 featured chapters for now (also [on production](https://almanac.httparchive.org/en/2020/) as just released there) and its less of an issue but could still do with some taming.

This is one reason I wanted to do one last pre-release release to 😁

**Comment by rviscomi** [comment]
I found this in a development branch and it turns out I didn't run `npm run generate` first, so the featured chapter section was missing. I can confirm that the issue goes away after building correctly first. 😅
