### ISSUE TITLE
Write content: Chapter 18. Page Weight

### ISSUE THREAD

**Issue by rviscomi** [HTTPArchive/almanac.httparchive.org#144]
Part | Chapter | Authors | Reviewers | Analysts | Metrics | Analysis
-- | -- | -- | -- | -- | -- | --
IV. Content Distribution | 18. Page Weight | @khempenius @tammyeverts | @paulcalvano @flowlabs | @khempenius | #20 | #99

### Due by: October 7

- [x] Review the [results spreadsheet](https://docs.google.com/spreadsheets/d/1nWOo8efqDgzmA0wt1ipplziKhlReAxnVCW1HkjuFAxU/edit?usp=sharing) and work with your analyst(s) (@khempenius) if you have any questions about the data.
- [x] Write the contents of your chapter and get it peer reviewed (@paulcalvano @flowlabs).
- [x] File a PR to merge your written contents in markdown format to the [src/content/en/2019](https://github.com/HTTPArchive/almanac.httparchive.org/tree/master/src/content/en/2019) directory.

Refer to the [Authors' Guide](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Authors'-Guide) for writing advice.

**Comment by rviscomi** [comment]
👋 Greetings! Just checking in to make sure this is progressing and remind you of the October 7 deadline timed so we can launch at Chrome Dev Summit.

The checklist above indicates that you still need to review the results, write content, and get it reviewed. Feel free to reach out if you have any questions about the process.

**Comment by tammyeverts** [comment]
Hi all! I'll be wrapping up my contribution over the weekend. Just to make sure we're all on the same page, my understanding is that I'm writing more of an introduction to the chapter than an analysis of the data. 

This is the outline of what I'll be writing, based on Rick's and my discussion a few months back:

- 1-2 paragraphs explaining each metric
- Comparison of YOY numbers (with the caveat that the datasets for previous years are different from that used for this report)
- Outside research demonstrating correlations between page weight and user behaviour and business metrics

Let me know if I'm off base or missing anything. I'll be drafting this in a Google doc, which I'm happy to share with you all when it's ready.

**Comment by khempenius** [comment]
@tammyeverts Ah good to know, I've been starting at a blank google doc the past couple day's with writer's block.

If you want to send your doc over to me once it's done, I can fill in the analysis part. I was planning on making graphs/visuals to represent the results of most of the queries.

**Comment by tammyeverts** [comment]
@khempenius Will do!

**Comment by rviscomi** [comment]
If it helps, I'm keeping track of the drafts other authors are writing in [this sheet](https://docs.google.com/spreadsheets/d/1LR29JpI2XJSjan_z6uP1YpRy4EYYivYZPqCIG-9sfFY/edit?ts=5d13c7d0#gid=2048624140) (column I). Feel free to take a peek at any for inspiration.

**Comment by tammyeverts** [comment]
Thanks, Rick! 

Quick question about graphs: Is there a standard format you want to use for them? (I'm assuming there is.) I might want to include some graphs using outside data. What's the best way to make sure they match what Katie's creating with the HA data?

**Comment by khempenius** [comment]
Stylistically, I was thinking the graphs would probably each look a bit different because I don't think one format is going to work for all of them.

It's probably not what you're asking about, but if it helps, I've aggregated all the results from the HA data into one Google Sheet, so if that would be helpful resource I can share it with you. (It's on my corp account, so I think the only way I can share it externally is on an individual basis, otherwise I'd just paste the link here.)

**Comment by khempenius** [comment]
Hahah, nevermind, it looks like Rick had already done the exact same thing :)

**Comment by rviscomi** [comment]
Good question. We're designing our own Almanac data viz from scratch using the raw data in the spreadsheets. 

I've just given you all edit access to the [results sheet](https://docs.google.com/spreadsheets/d/1nWOo8efqDgzmA0wt1ipplziKhlReAxnVCW1HkjuFAxU/edit?usp=sharing). So one option is to create your own charts in the sheet and copy/paste them into your draft doc, without worrying about their design. The design/development teams will work on stylizing them to be consistent with the rest of the Almanac.

Alternatively, the other option is to simply leave a placeholder in your doc with a note for the editor to insert the chart. Make sure to mention what kind of chart you have in mind and which metric it corresponds to (each tab in the spreadsheet is prefixed with a unique metric ID).

@tammyeverts If you have the raw data from the outside datasets, you could put those in the sheet and follow the same process. Otherwise feel free to copy/paste the images/URLs into the doc and we can add them to the chapter the old fashioned way with a simple `<img>` tag. Keep in mind that the third and final step for this issue is to submit a PR in markdown format, so externally hosted image URLs would be helpful, otherwise we'll need to find a place to host it locally.

**Comment by tammyeverts** [comment]
Perfect – thanks!

**Comment by tammyeverts** [comment]
Hey all! I thought I'd be able to wrap up my contribution this morning, but I'd forgotten that two of my fellow SpeedCurvers are on vacation this week, and I'm helping cover for them – ack! I should be able to finish things up this evening. Is that ok?

**Comment by rviscomi** [comment]
No problem! Thanks for the heads up.

**Comment by tammyeverts** [comment]
Intro is DONE. Thanks for your patience, everyone! It turns out that covering for two people who are on vacation is a bit more time-consuming than I'd expected.

Here's the link to view and edit: https://docs.google.com/document/d/1FlJIcfjLLZ_U5JhfBy3fZq_VCLd8oC8kDoLsxsQTzRs/edit?usp=sharing

**Comment by tammyeverts** [comment]
Hey all. I'm a bit fuzzy about the next phase. I see at the top of this ticket that we're supposed to get the chapter peer reviewed by Paul and Rich. Who's supposed to do that?

**Comment by rviscomi** [comment]
@khempenius and @henrisgh should contribute their sections to the doc. Have you all divided up which parts will be written by whom?

You could have @paulcalvano  and @flowlabs review the sections that are already written or it may be best to do it all at once when it's complete.

**Comment by khempenius** [comment]
I've added the analysis section to the doc. I'm not quite done with it - but I'll add the remainder later tonight.

**Comment by khempenius** [comment]
After going back and forth a lot on this, I ended up not adding a section to the doc re: file format sizes. The more I looked at the results, the more I felt that more investigation would be needed to do it justice. Otherwise I think it would be easy to draw the incorrect conclusions from the data - e.g. "X format is better than Y format because median file size is smaller" - but that's masking that X format is used for icons; and Y format is used for large photos. And I think that data would take a bit of legwork to collect.

**Comment by rviscomi** [comment]
Thanks @khempenius. I think your reaction is totally valid and would still be appropriate to discuss in the chapter. One of the things that makes the Almanac special compared to [a report like this](https://httparchive.org/reports/state-of-the-web) is that authors provide context and their interpretation of the data. So if you've found pitfalls in the results, that's all the more reason to talk about them and make sure others don't fall for them. You could also describe what could be done differently to be able to make those conclusions and that could be a note for us to improve next year.

**Comment by khempenius** [comment]
Discussion added 👍 (unfortunately it's kind of long).

**Comment by rviscomi** [comment]
@khempenius @tammyeverts @henrisgh The draft is looking great so far. There's still some unfinished content. Would it be possible to wrap this up by the end of the week?

@paulcalvano @flowlabs: Do you have time to give the current draft a review?

**Comment by khempenius** [comment]
@rviscomi I'll take a look today. Sorry for delay - it looks like I don't get notifications for google doc comments.

**Comment by khempenius** [comment]
Updated

**Comment by tammyeverts** [comment]
I've updated my section. Thanks for the great feedback @rviscomi!

I looked at the rest of the chapter, as well. Looks awesome, @khempenius!

**Comment by rviscomi** [comment]
Agreed, looks great. Left one suggestion with a writing prompt for a conclusion.

Also, @paulcalvano @flowlabs now is a good time to go through the draft and do a peer review.

**Comment by rviscomi** [comment]
Henri has been MIA so removing as an author :(

**Comment by tammyeverts** [comment]
Great! I'm assuming the writing prompt is for Katie, since it's at the end
of her section? Let me know if you need me to help with that.

What do you need from me in terms of author bio? I don't think I've sent
over anything yet.

Tammy

**Comment by rviscomi** [comment]
The conclusion could be written by either/both of you. @khempenius do you have time to write it?

Good call on the bio. I just opened #239. Could you add yours as a comment there?

**Comment by tammyeverts** [comment]
Awesome – thanks for the update!

I just added my bio to #239. Let me know if you need anything else.

**Comment by khempenius** [comment]
Add conclusion

**Comment by rviscomi** [comment]
@paulcalvano @flowlabs have you had a chance to review the [draft doc](https://docs.google.com/document/d/1FlJIcfjLLZ_U5JhfBy3fZq_VCLd8oC8kDoLsxsQTzRs/edit?usp=sharing)?

**Comment by paulcalvano** [comment]
Just added some comments to the doc. Great job on this!

**Comment by rviscomi** [comment]
I think the doc is in great shape. @khempenius or @tammyeverts can you file a PR to get the markdown merged?

**Comment by khempenius** [comment]
@rviscomi @tammyeverts - I'm starting on creating the markdown for this.
