### ISSUE TITLE
Credit analysts as "Analyzed by" for tense consistency

### ISSUE THREAD

**Issue by rviscomi** [HTTPArchive/almanac.httparchive.org#1442]
![image](https://user-images.githubusercontent.com/1120896/98448514-829a5f80-20fa-11eb-9a37-c3bed88c4b3c.png)

Nit: Authors and reviewers are credited in the chapter masthead as "written by" and "reviewed by". For consistency, analysts should be credited in the past tense as "analyzed by" rather than "analysis by".

**Comment by bazzadp** [comment]
Unless I get further knowledge, I'm going to assume the Translations are correct and this is an English only issue and fix this with #1454 

@HTTPArchive/translators can you check your languages and let us know one way or another if there's a similar issue there?
