### ISSUE TITLE
Support code formatting for headings in chapter outline sidebar

### ISSUE THREAD

**Issue by rviscomi** [HTTPArchive/almanac.httparchive.org#1445]
![image](https://user-images.githubusercontent.com/1120896/98449729-f7be6280-2103-11eb-92a7-1f45d9ced99c.png)

The heading "`viewport` specifications" includes a code block for the word "viewport". This block is formatted in the heading itself, but not its entry in the chapter outline sidebar, making it appear as if the word is plain and should be capitalized for consistency with other headings.

Headings in the outline should retain the code formatting.

**Comment by bazzadp** [comment]
HTML is not supported in ToC as discussed in #656 .

Will have another look to see if anything's changed since then or if I can think of a better way of supporting it than I came up with last time.

**Comment by rviscomi** [comment]
Good find, yeah it'd be nice to revisit this to see if we can support similar use cases.

**Comment by bazzadp** [comment]
Actually it was supported then, but just messed up the anchor link. So not exactly the same. But almost certainly related. Anyway will have a look if no one grabs it before me.

**Comment by bazzadp** [comment]
Turns out this was easier than I thought. Shown doesn't support HTML in Headings for ToC (so #656 is still a problem) but it does support Markdown so we can solve this.

PR coming up...
