### ISSUE TITLE
Add syntax highlighting capabilities

### ISSUE THREAD

**Issue by bazzadp** [HTTPArchive/almanac.httparchive.org#1450]
Authors sometimes include small code snippets to illustrate example usage. It would be nice to syntax highlight that for readability.

We do support a limited form and use it in the methodology page but it basically needs to be lovingly written by hand at the moment:

https://github.com/HTTPArchive/almanac.httparchive.org/blob/a5cbe77943ab7202c9ed55fdef71b20560a62033/src/templates/en/2020/methodology.html#L88-L104

That may be sufficient for now but a nicer code formatter would be better so something to look at at some point.

@HTTPArchive/developers anyone any suggestions of a (lightweight!) third-party one?

**Comment by ibnesayeed** [comment]
The choices will depend on whether we want server-side preprocessing for syntax highlighting in the markup itself (which will include spans with specific classes around each token of the markup and will need either a CSS file or inline style) or a JavaScript-based solution that can be configured to look for code block and syntax highlight on the client-side.

**Comment by bazzadp** [comment]
My preference would be server side for performance reasons.

**Comment by ibnesayeed** [comment]
> My preference would be server side for performance reasons.

I think [Pygments](https://pygments.org/] is the go to Python library for server side syntax highlighting. There are many wrapper libraries that use it underneath to support in different environments.

**Comment by rviscomi** [comment]
Can we do it at built time?

**Comment by bazzadp** [comment]
Yes that's what I meant. Sorry I wasn't clear.

think we also need to ask if we really need this? We do not have that much code and don't think we should be encouraging it too much - to me the Web Almanac is about analysing usage, not writing tutorials. So expect there to only be very small snippets here and there. Maybe just need to handle this like we do in Methodology and offer more manual options for this?

Just need to weight up code complexity versus benefits.

Either way I don't think this is a super critical issue, but a nice to have for future years.

**Comment by rviscomi** [comment]
Yeah I don't expect that this would get much use, and I agree that it's probably better if it doesn't. If there's an easy off-the-shelf solution available, I'd still be open to it. But if it's any kind of maintenance or development hassle, we can forgo it.

**Comment by bharatagsrwal** [comment]
Hey everyone, may I know which scripting or languages we will need to support for syntax highlighting capabilities

**Comment by bazzadp** [comment]
It's simple HTML, JS or CSS snippets. Though have one example of SQL.

Like this, [from the 2019 JavaScript chapter](https://almanac.httparchive.org/en/2019/javascript):

![JS Chapter code example](https://user-images.githubusercontent.com/10931297/99780680-b61fb580-2b0e-11eb-8734-ca468485ffe8.png)

Or this from the [2020 Capabilities chapter](https://almanac.httparchive.org/en/2020/capabilities#notification-triggers-api):

![Capabilities Chapter code example](https://user-images.githubusercontent.com/10931297/99780767-d780a180-2b0e-11eb-8490-8d04163bd950.png)

Here's an HTML example from the [2020 Markup Chapter](https://almanac.httparchive.org/en/2020/markup#details-and-summary)

![Markup Chapter code example](https://user-images.githubusercontent.com/10931297/99780995-2e867680-2b0f-11eb-9c82-b47edd1740be.png)

As you can see they are all really small snippets. So I'm weary of adding a huge library (especially during the front end!) just for these. though if we could do something during chapter generation so there's no load on the front end, then that might be OK. Alternatively we just add some more CSS and hand craft these manually?

We do that for the [Methodology page](https://almanac.httparchive.org/en/2019/methodology#dataset):

![Methodology SQL](https://user-images.githubusercontent.com/10931297/99781251-858c4b80-2b0f-11eb-969d-be21a71e5403.png)

Anyway lets brainstorm any ideas you might have here so we can weigh up the pros and cons of this, before we spend too much effort implementing something we might not want to accept into the code base.

**Comment by bharatagsrwal** [comment]
Okay, If its only HTML, CSS, and JS then we might not need any Library or any other package for this, [https://www.w3schools.com/howto/tryit.asp?filename=tryhow_syntax_highlight](https://www.w3schools.com/howto/tryit.asp?filename=tryhow_syntax_highlight) we can take help from this and can implement easily in the frontend itself, Have a look at it, might help us in achieving this

**Comment by bazzadp** [comment]
That rainbow one might work and looks like it can be called from node too so my preference would be to use that as part of `generate_chapter.js` to get it to add the classes to the HTML

And then I'd also manually add the highlighting needed to `2019.css` rather than import another stylesheet just for this. I imagine we'd only use a few classes for JS, HTML, CSS and SQL.

**Comment by bharatagsrwal** [comment]
> That rainbow one might work and looks like it can be called from node too so my preference would be to use that as part of `generate_chapter.js` to get it to add the classes to the HTML
> 
> And then I'd also manually add the highlighting needed to `2019.css` rather than import another stylesheet just for this. I imagine we'd only use a few classes for JS, HTML, CSS and SQL.

I completely agree with you @bazzadp there may be many CSS and JS which we are not going to use, that's why this rainbow thing is customizable also, so the languages which we are using, we can choose those only and it will include only that JS and CSS things.
as in the image, I selected a few only
![image](https://user-images.githubusercontent.com/43988371/99785188-d36e7700-2b42-11eb-93ac-a1a1be0efd18.png)


After Downloading Custom one 
![image](https://user-images.githubusercontent.com/43988371/99785345-0e70aa80-2b43-11eb-9541-6767d0a3b0a2.png)

**Comment by bazzadp** [comment]
Our markdown convert (Showdown) already converts this:

https://github.com/HTTPArchive/almanac.httparchive.org/blob/9a4f3181c0051d88c10b9718f0d92c98040bb644/src/content/en/2019/javascript.md#L329-L331

to this:

```
<pre><code class="html language-html">&lt;script type="module" src="main.mjs"&gt;&lt;/script&gt;</code></pre>
```

So we could do something like this in ``generate_chaper.js`:

```js
html = html = converter.makeHtml(markdown);
const dom = new JSDOM(html);
const htmlsnippet = dom.window.document.querySelectorAll('code.language-html').innerText;
const htmlsnippetclean = htmlsnippet.replace(/&lt;/g, '<').replace(/&gt;/g, '>')
const htmlsnippetconverted = rainbow.colorSync(htmlsnippet, 'html');
html = html.replace(htmlsnippet, htmlsnippetconverted);
```

Which would add the classes in the generated HTML we serve server side. Then no need for client side JS at all!

Then we do similar for javascript:

```js
const jslsnippet = dom.window.document.querySelectorAll('code.language-js').innerText;
const jssnippetclean = htmlsnippet.replace(/&lt;/g, '<').replace(/&gt;/g, '>')
const jssnippetconverted = rainbow.colorSync(jssnippet, 'js');
html = html.replace(jssnippet, jssnippetconverted);
```

And CSS and SQL...etc.

**Comment by bharatagsrwal** [comment]
Yes, @bazzadp I got your point, so should we give it a try?

**Comment by bazzadp** [comment]
Go for it!

**Comment by bharatagsrwal** [comment]
For which one should I go with
![image](https://user-images.githubusercontent.com/43988371/99934253-83322780-2d83-11eb-8c18-a96bd567a1ec.png)

or 

![image](https://user-images.githubusercontent.com/43988371/99934279-91804380-2d83-11eb-986d-6735ab4a2f92.png)

**Comment by bazzadp** [comment]
I thought we'd agreed to do this as part of the site build above? So we don't need to include the JS at all client side, as the conversion will have already been done well before that.

Just need to add to `src/package.json` so it's included in `npm install` and then include the code from `src/generate/generate_chapters.js`.

**Comment by bharatagsrwal** [comment]
> I thought we'd agreed to do this as part of the site build above? So we don't need to include the JS at all client side, as the conversion will have already been done well before that.
> 
> Just need to add to `src/package.json` so it's included in `npm install` and then include the code from `src/generate/generate_chapters.js`.

Yap that's what I have done and added its CSS to static folder 
![image](https://user-images.githubusercontent.com/43988371/99941764-98fc1880-2d94-11eb-83c5-2d5af192d56d.png)
something like that

**Comment by bazzadp** [comment]
OK so no need to include the JS in the page then as won't be run again then.

As to what theme to use, that's an interesting question! Will need to have a look. But my thoughts are to include whatever theme's CSS directly in the `2019.css` file, rather than have another CSS file dependency (however light it is). also means we can customise it as much as we want so don't have to use the exact theme they have.

**Comment by bharatagsrwal** [comment]
I have created a pull request [https://github.com/HTTPArchive/almanac.httparchive.org/pull/1574](https://github.com/HTTPArchive/almanac.httparchive.org/pull/1574), please check it once.
