### ISSUE TITLE
2020 Methodology updates for French and Japanese

### ISSUE THREAD

**Issue by bazzadp** [HTTPArchive/almanac.httparchive.org#1460]
@HTTPArchive/french-translators , @ksakae1216 / @MSakamaki we recently merged in the 2020 Methodology translation with your help.

However, we've made [some more changes](https://github.com/HTTPArchive/almanac.httparchive.org/pull/1449/files) to the English version so need some extra updates whenever you get a chance.

Could you put your name next to you language and comment on this issue if you plan to take this on, so the other Translators don't do it as well?

- [x] - French @borisschapira 
- [x] - Japanese @ksakae1216

**Comment by ksakae1216** [comment]
Maybe I will translate 11/14 or 11/15

**Comment by bazzadp** [comment]
Thanks @ksakae1216 !
