### ISSUE TITLE
2020 chapter metadata still uses 2019

### ISSUE THREAD

**Issue by rviscomi** [HTTPArchive/almanac.httparchive.org#1468]
```html
<title>Capabilities | 2019 | The Web Almanac by HTTP Archive</title>
<meta property="og:title" content="Capabilities | 2019 | The Web Almanac by HTTP Archive">
<meta property="og:image" content="https://almanac.httparchive.org/images/2019/capabilities/hero_lg.jpg">
<meta name="twitter:title" content="Capabilities | 2019 | The Web Almanac by HTTP Archive">
<meta name="twitter:image" content="https://almanac.httparchive.org/images/2019/capabilities/hero_lg.jpg">
```

These will cause UX confusion for readers but also 404 images for social scrapers like Twitter:

![image](https://user-images.githubusercontent.com/1120896/98609375-203c8d00-22bb-11eb-8c2d-4da573a5894f.png)

**Comment by rviscomi** [comment]
I've fixed the title issues in #1469 and it appears that the 2020 hero illustrations do actually live in the [2019 directory](https://github.com/HTTPArchive/almanac.httparchive.org/tree/main/src/static/images/2019/capabilities). But it's still 404ing because it seems like the server thinks the "images" subdirectory is an invalid language: https://almanac.httparchive.org/images/2019/capabilities/hero_lg.jpg

![image](https://user-images.githubusercontent.com/1120896/98610522-c2f60b00-22bd-11eb-98d1-bf7d6431e0b3.png)

I'll try to get the 2019 chapter image directory served again, but we should keep this issue open to avoid confusion about 2020 content served from 2019 directories, especially for chapters that didn't exist in 2019.

**Comment by rviscomi** [comment]
The 404 was because the chapter hero image URLs were missing the `/static` part of the path. Fixed in #1470 and also added dynamic year to chapter metadata in non-English localized templates.

**Comment by bazzadp** [comment]
> I'll try to get the 2019 chapter image directory served again, but we should keep this issue open to avoid confusion about 2020 content served from 2019 directories, especially for chapters that didn't exist in 2019.

Ah think I misunderstood https://github.com/HTTPArchive/almanac.httparchive.org/pull/1358#discussion_r504239477. Thought you were asking to keep in 2019 directory but now see you mean to have them in 2020 directory with either copies of 2019 for reused chapters, or fallback to there. Yes let's leave that open until that's fixed.

> I've force-pushed these changes to the production server without a deploy, so they will be picked up in the next formal deployment.

Not a fan of this to be honest. Was really confused for ages as to why I wasn't seeing the problem on production. Version numbers are cheap and would rather be clear when re-releasing.

**Comment by bazzadp** [comment]
Closing this as moved the remaining hero image issue to #1558
