### ISSUE TITLE
Write content: Chapter 17. CDN

### ISSUE THREAD

**Issue by rviscomi** [HTTPArchive/almanac.httparchive.org#149]
Part | Chapter | Authors | Reviewers | Analysts | Metrics | Analysis
-- | -- | -- | -- | -- | -- | --
IV. Content Distribution | 17. CDN | @andydavies @colinbendell | @yoavweiss @paulcalvano @pmeenan | @raghuramakrishnan71 @rviscomi | #19 | #98

### Due by: October 7

- [x] Review the [results spreadsheet](https://docs.google.com/spreadsheets/d/1Y7kAxjxUl8puuTToe6rL3kqJLX1ftOb0nCcD8m3lZBw/edit?usp=sharing) and work with your analyst(s) (@raghuramakrishnan71 @rviscomi) if you have any questions about the data.
- [x] Write the contents of your chapter and get it peer reviewed (@yoavweiss @paulcalvano @pmeenan).
- [ ] File a PR to merge your written contents in markdown format to the [src/content/en/2019](https://github.com/HTTPArchive/almanac.httparchive.org/tree/master/src/content/en/2019) directory.

Refer to the [Authors' Guide](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Authors'-Guide) for writing advice.

**Comment by rviscomi** [comment]
👋 Greetings! Just checking in to make sure this is progressing and remind you of the October 7 deadline timed so we can launch at Chrome Dev Summit.

The checklist above indicates that you still need to review the results, write content, and get it reviewed. Feel free to reach out if you have any questions about the process.

**Comment by rviscomi** [comment]
🛎 just a ping to see if any progress has been made on this. Let me know!

**Comment by andydavies** [comment]
I'm on it…

How long do you expect the chapter to be?

**Comment by rviscomi** [comment]
Thanks @andydavies! The [Authors' Guide](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Authors'-Guide) has some advice about chapter length, to summarize feel free to make it as long or short as needed to get your point across. This chapter has ~25 metrics so if you discuss all of them it could be long, but you can pick and choose to discuss only the most interesting results. Up to you.

**Comment by andydavies** [comment]
Just noticed that 17_02d queries sites that load 3rd-party content from a CDN rather than uses a public library CDN

Was trying to drive down the library route so we have some idea how much effect cache partioning is going to have

**Comment by rviscomi** [comment]
@andydavies per our chat offline:

> I was wondering about limiting it to the common JS library hosts - I have a list somewhere will dig it out when I get home

Could you post the list of hosts when you get a chance?

**Comment by colinbendell** [comment]
Pre-Draft document is here: https://docs.google.com/document/d/1qZF_J-E9qOWgpVA_7pOIH8W3skPJVZvWyaZoncMldFw/edit#

**Comment by rviscomi** [comment]
The draft is in great shape. I see @yoavweiss did a thorough review and left some comments recently. Once those are resolved we're ready to get this converted to markdown and merged. Thanks everyone!

**Comment by rviscomi** [comment]
🛎 gentle ping! We'd love to start editing this chapter as soon as the markdown is merged. Hope to get it launched on time.

**Comment by rviscomi** [comment]
🛎 🛎 sorry to nag! We really need this markdown in today if possible!

**Comment by andydavies** [comment]
No need to apologise (herding cats is never fun)

I’ll turn it into markdown tomorrow

How do I reference the charts when I switch formats

**Comment by rviscomi** [comment]
If the charts are images they can be uploaded to `/static/images/2019/17_CDN/` and referenced using that relative path name in the markdown. If they're embedded Sheets charts, see https://github.com/HTTPArchive/almanac.httparchive.org/issues/237#issuecomment-547741549

**Comment by bazzadp** [comment]
Though also see https://github.com/HTTPArchive/almanac.httparchive.org/issues/369#issuecomment-551927884 so I think you should do images if possible.

**Comment by rviscomi** [comment]
Yes, I'll update my data viz process to include images.

**Comment by bazzadp** [comment]
Any update on this @andydavies ?

Can you start the markdown file with the following please?

```
---
part_number: IV
chapter_number: 17
title: CDN
description: CDN chapter of the 2019 Web Almanac covering ...
authors: [andydavies, colinbendell]
reviewers: [yoavweiss, paulcalvano, pmeenan]
discuss: 1772
published: 2019-11-11T00:00:00.000Z
published: 2019-11-11T00:00:00.000Z
---

## Introduction
```

The description should be filled out with a description for https://github.com/HTTPArchive/almanac.httparchive.org/issues/292. I've been using the H2 headings (except Introduction and Conclusion). See [the other chapters](https://github.com/HTTPArchive/almanac.httparchive.org/tree/master/src/content/en/2019) for examples, and I've given the HTTP/2 one below:

```
description: HTTP/2 chapter of the 2019 Web Almanac covering adoption and impact of HTTP/2, HTTP/2 Push, HTTP/2 Issues, and HTTP/3
```

**Comment by andydavies** [comment]
We should add Erik Nygren to the reviewers, do we have bio for him anywhere?

**Comment by bazzadp** [comment]
> We should add Erik Nygren to the reviewers, do we have bio for him anywhere?

Reference him as enygren as he's already in the config file:

https://github.com/HTTPArchive/almanac.httparchive.org/blob/774e963a321029f675d6d6a1bd314e4c956e9577/src/config/2019.json#L1002-L1011

Reviewers don't get bios, only authors.
