### ISSUE TITLE
Translate 2019 Japanese ebook description on Google Books

### ISSUE THREAD

**Issue by rviscomi** [HTTPArchive/almanac.httparchive.org#1496]
The [English](https://www.google.com/books/edition/The_2019_Web_Almanac/EAr5DwAAQBAJ?hl=en) and [Japanese](https://books.google.com/books?id=tPACEAAAQBAJ) ebooks are available for free on Google Play and Google Books. The Japanese version is using a custom English description I wrote just for the bookstore:

> The Web Almanac is an annual research project by the web development community to better understand how the web is built and experienced. Industry experts and a team of peer reviewers and data analysts research the state of the web, one chapter at a time, focused in areas of web page composition, user experience, content publishing, and content delivery. The result is a richly detailed report brimming with insightful analysis written by subject matter experts built on a solid foundation of statistics aggregated over millions of top websites.

Would anyone be able to translate this text into Japanese? No PR needed, just reply in a comment. Thank you!

**Comment by MSakamaki** [comment]
@rviscomi I have some time this weekend to translate for japanese.

**Comment by MSakamaki** [comment]
@rviscomi 
I translated into Japanese.
It would be helpful if @ksakae1216  could check it too!

> Web Almanacは、Web開発コミュニティが毎年実施している調査プロジェクトで、Webがどのように構築され体験されているのかをより深く理解することを目的としています。業界の専門家とピアレビュアーやデータアナリストのチームが、Webページのコンテンツやユーザー体験、コンテンツ公開、コンテンツ配信の分野に焦点を当てて、Webの状態を1章ずつ調査しました。その成果として、数百万を超える上位Webサイトを集計した統計の強固な基盤に基づいた、内容領域専門家による優れた洞察と分析による詳細がレポートとしてまとまっています。

**Comment by ksakae1216** [comment]
@MSakamaki I checked, OK.
Thanks translate.

**Comment by rviscomi** [comment]
Thank you @MSakamaki @ksakae1216! This change is live: https://books.google.com/books?id=tPACEAAAQBAJ

![image](https://user-images.githubusercontent.com/1120896/99200885-09dc7880-2776-11eb-8a6f-f133e777a8ad.png)

**Comment by bazzadp** [comment]
Presume this can be closed @rviscomi ? Reopen if I'm mistaken.
