### ISSUE TITLE
Finalize assignments: Chapter 13. Ecommerce

### ISSUE THREAD

**Issue by rviscomi** [HTTPArchive/almanac.httparchive.org#15]
Section | Chapter | Coauthors | Reviewers
-- | -- | -- | --
III. Content Publishing | 13. Ecommerce | @samdutton @alankent | @voltek62

**Due date:** To help us stay on schedule, please complete the action items in this issue by June 3.

**To do:**
- [x] Assign subject matter experts (coauthors)
- [ ] Assign peer reviewers
- [x] Finalize metrics

**Current list of metrics:**

Top ecommerce platforms:
- Marketplace: for example, eBay or Etsy.
- Hosted shop: for example, Shopify.
- Hosted platform: for example, Magento Commerce.
- Self-hosted platform: for example, Magento Open Source.
- Not on a platform or marketplace: sites that show payment activity but don't appear to be on a platform or marketplace.

Stats for sites that appear to be e-commerce sites (as above):
- Images: quantity, format, byte size, pixel dimensions, etc.
- Home page HTML size.
- Performance stats.
- Third-party content: total weight and number of requests (and performance impact if possible).
- Analytics providers.
- Ad providers.
- Indexability.
- Qualification (or not) as a PWA.

👉**AI (coauthors):** Assign peer reviewers. These are trusted experts who can support you when brainstorming metrics, interpreting results, and writing the report. Ideally this chapter will have 2 or more reviewers who can promote a diversity of perspectives.

👉 **AI (coauthors):** Finalize which metrics you might like to include in an annual "state of ecommerce" report powered by HTTP Archive. Community contributors have initially sketched out a few ideas to get the ball rolling, but it's up to you, the subject matter experts, to know exactly which metrics we should be looking at. You can use [the brainstorming doc](https://docs.google.com/document/d/1sCIMeErYvaQb5x9Acdb6ImYdn0-buHRhYGvz2HoysmM/edit#heading=h.iznoa2266s2c) to explore ideas.

The metrics should paint a holistic, data-driven picture of the ecommerce landscape. The HTTP Archive does have its limitations and blind spots, so if there are metrics out of scope it's still good to identify them now during the brainstorming phase. We can make a note of them in the final report so readers understand why they're not discussed and the HTTP Archive team can make an effort to improve our telemetry for next year's Almanac.

**Next steps:** Over the next couple of months analysts will write the queries and generate the results, then hand everything off to you to write up your interpretation of the data.

**Additional resources:**
- [All chapter assignments](https://github.com/HTTPArchive/httparchive.org/issues/140)
- [Project timeline](https://docs.google.com/spreadsheets/d/1LR29JpI2XJSjan_z6uP1YpRy4EYYivYZPqCIG-9sfFY/edit?usp=sharing)
- [About the project](https://discuss.httparchive.org/t/planning-the-web-almanac-2019/1553)

**Comment by rviscomi** [comment]
@samdutton @alankent @voltek62 we're hoping to finalize the reviewers and metrics for each chapter today. PTAL at https://github.com/HTTPArchive/almanac.httparchive.org/issues/15#issue-446806335 and edit it with anything that's missing. When it's in good shape, tick off the remaining checklist items and close this issue. Thanks!

**Comment by samdutton** [comment]
Still confirming reviewers — apologies for delay. Metrics finalized.

**Comment by rviscomi** [comment]
Thanks @samdutton!

**Comment by rviscomi** [comment]
Since the list of metrics LGTM I'll close this issue and we can try to get more reviewers in time for the chapter to be written.

**Comment by rviscomi** [comment]
Welcome @wizardlyhel to the Ecommerce chapter reviewers!
