### ISSUE TITLE
Language code for Traditional Chinese

### ISSUE THREAD

**Issue by bazzadp** [HTTPArchive/almanac.httparchive.org#1516]
We are currently using `zh-CHT` as the language code for Traditional Chinese. The [Nu Validator says this is not a valid `lang` code](https://validator.w3.org/nu/?doc=https%3A%2F%2Falmanac.httparchive.org%2Fen%2F2020%2F).

Googling around [it appears](https://stackoverflow.com/questions/732109/chinese-language-codes) that `zh-CHT` was used in the past, `zh-HANT` is official way, but `zh-TW` is the most common.

Well we have access to a database of crawl stats to confirm this and [the Markup chapter has even done the work for us](https://docs.google.com/spreadsheets/d/1Ta7amoUeaL4pILhWzH-SCzMX9PsZeb1x_mwrX2C4eY8/edit#gid=2047285366)! Here's the `zh` usage on mobile (in lowercase):

client | freq | html_lang | %
-- | -- | -- | --
mobile | 36,357 | zh-tw | 0.57%
mobile | 8,304 | zh-cn | 0.13%
mobile | 4,844 | zh-hant | 0.08%
mobile | 4,012 | zh | 0.06%
mobile | 2,719 | zh-hant-tw | 0.04%
mobile | 1,545 | zh-hk | 0.02%
mobile | 1,021 | zh_tw | 0.02%
mobile | 564 | zh-hans | 0.01%
mobile | 399 | zh-cmn-hans | 0.01%
mobile | 198 | zh_cn | 0.00%
mobile | 125 | zh-hant-hk | 0.00%
mobile | 98 | zh_hk | 0.00%
mobile | 96 | zh-cmn-hant | 0.00%
mobile | 56 | zh-hans-cn | 0.00%
mobile | 48 | zh-hans-tw | 0.00%
mobile | 21 | zh-cmn-hans-cn | 0.00%
mobile | 11 | zh-cmn | 0.00%
mobile | 10 | zh-cmn-hant-tw | 0.00%
mobile | 9 | zh-en | 0.00%
mobile | 9 | zh-sg | 0.00%
mobile | 8 | zh-hang-tw | 0.00%
mobile | 8 | zh-cht | 0.00%

So it does appear that `zh-CHT` is not commonly used and `zh-TW` is indeed the preferred usage, with `zh-HANT` a distant second (`zh-CN` is for Simplified Chinese so not the same). `zh-TW` is also what [MDN uses](https://developer.mozilla.org/zh-TW/) for example.

@AbbyTsai what's your thoughts here as you picked this lang code. Should we change to `zh-TW`? This would mean it's more likely to be auto selected by going to https://almanac.httparchive.org and I would prefer to have "valid" HTML.

**Comment by rviscomi** [comment]
> Well we have access to a database of crawl stats to confirm this and the Markup chapter has even done the work for us!

I love when that happens! 😁

**Comment by AbbyTsai** [comment]
sure, It may be better to gain common readers of Traditional Chinese in zh-TW.

**Comment by bazzadp** [comment]
OK let's change it. Will wait until we land #1523 (needed to allow us to move) and #1508 (touches these files) and then submit a PR to move it.

**Comment by AbbyTsai** [comment]
got these warm notes. thanks.

**Comment by bazzadp** [comment]
Definitely should change this as Google doesn't like it:

![Google Search Console International Targeting](https://user-images.githubusercontent.com/10931297/99371280-9d1cc780-28b6-11eb-9778-0d0abe98f7af.png)

**Comment by AbbyTsai** [comment]
nice reminder in target audience by location and language.
