### ISSUE TITLE
Linking to the ebook

### ISSUE THREAD

**Issue by rviscomi** [HTTPArchive/almanac.httparchive.org#1517]
We have https://almanac.httparchive.org/en/2019/ebook which is a single page version of the entire 2019 publication. On the TOC page we have an [Ebook](https://almanac.httparchive.org/en/2019/table-of-contents#ebook) section that links directly to the downloadable PDF, along with an obligatory notice about the download size and credit to the Prince tool. In the new TOC dropdown UI, the ebook part sticks out very prominently:

![image](https://user-images.githubusercontent.com/1120896/99157804-52beff00-269a-11eb-95bb-23276d5d9c83.png)

I'd like to propose a couple of changes:

- Rather than linking directly to the PDF from the TOC dropdown and page, link instead to the /ebook page as another part of the Appendix section.
- On the /ebook page, include some kind of callout for readers to download the PDF, along with the necessary disclaimers about file size and Prince. This can be styled with `media: screen` to ensure that it wouldn't be included in the printout version or generated PDF. I wonder if it's also worth styling it like other appendix pages with a header/footer and maybe a "scroll to top" button for people not to get lost in the middle.

IMO this is an improvement because /ebook is just another page in the TOC appendix, and the Prince formalities are tucked away where only interested ebook readers will see it.

@barrypollard was /ebook ever meant to be a user-visible page?

**Comment by bazzadp** [comment]
> @barrypollard was /ebook ever meant to be a user-visible page?

No not really. It was created more to generate the PDF. It's not included in the sitemap and also set to not be indexed, so it doesn't steal SEO juice from the PDF.

To me the HTML version is better as individual chapters with the table of contents on the left. The ebook also doesn't include the Google Sheets figures but just the fallback images – and if it did the page itself would be massive!

If we were going to expose the /ebook URL then think we should include a ToC menu on the left, either to each chapter or perhaps to all the sections (though that might be quite long). But really I question the value. If you want a downloadable version use the PDF, if you want an online version use the website. What's the benefit of one page version?

**Comment by rviscomi** [comment]
If user's are never meant to land on that page, we shouldn't serve it in production. Maybe a compromise is to create a standalone "ebook download page". We could have prominent "Download" CTA, file size and Prince disclaimers, links to our entries in Google Books and the Play store, and maybe instructions for self-printing the A5 version. WDYT?

**Comment by bazzadp** [comment]
Yeah the only reasons it's exposed are:
1. We need it exposed in development
2. It allows people to create their own print version if they have PrinceXML. For example if they are American and don't like the the A5 page size we used.

https://github.com/HTTPArchive/almanac.httparchive.org/blob/e68274c79677de4a298abc0c6e3dae859ed16f52/src/README.md#L138

Until we fix #1390 (which I'm not sure is that easy) I'm not sure we should be exposing the Google Books and Play Store links.

I've fixed the ToC drop down issue in that branch btw.

**Comment by rviscomi** [comment]
> Until we fix #1390 (which I'm not sure is that easy) I'm not sure we should be exposing the Google Books and Play Store links.

I don't see that issue as critical enough to stop us from promoting those publications. URLs are still there and can be copied into the URL bar if readers were so inclined. Was that your only concern with an ebook landing page?

**Comment by bazzadp** [comment]
> Was that your only concern with an ebook landing page?

Yeah no other issues with it and might be a good page to have. Until then think the ebook link we have is fine.
