### ISSUE TITLE
Implement Methodology page design

### ISSUE THREAD

**Issue by rviscomi** [HTTPArchive/almanac.httparchive.org#154]
See https://drive.google.com/open?id=1ud4iZWxUB7vMZlcKUrPUkLuT1haBV_B6 for desktop designs. Mobile designs coming soon.

@HTTPArchive/developers is anyone available to take this?

**Comment by rviscomi** [comment]
🛎 @HTTPArchive/developers anyone around to work on this? I think the site template is in place for the most part, but we haven't finished implementing any of the secondary (non-home) pages yet so we still need to finish up the header and main section designs.

**Comment by MSakamaki** [comment]
@rviscomi 
I am interested
Can I work with the following layouts?
https://projects.invisionapp.com/d/?origin=v7?origin=v7#/console/18009643/382374544/preview

**Comment by rviscomi** [comment]
Yes! Thanks @MSakamaki!!

And for mobile see https://projects.invisionapp.com/d/?origin=v7?origin=v7?origin=v7#/console/18174420/385501699/preview

**Comment by rviscomi** [comment]
Hi @MSakamaki have you made any progress on this?

**Comment by MSakamaki** [comment]
@rviscomi
