### ISSUE TITLE
Write content: Chapter 9. Accessibility

### ISSUE THREAD

**Issue by rviscomi** [HTTPArchive/almanac.httparchive.org#155]
Part | Chapter | Authors | Reviewers | Analysts | Metrics | Analysis
-- | -- | -- | -- | -- | -- | --
II. User Experience | 9. Accessibility | Nektarios Paisios, @nadinarama, @obto | @rachellcostello, @kleinab | @dougsillars @rviscomi @obto | #11 | #90
### Due by: October 7

- [x] Review the [results spreadsheet](https://docs.google.com/spreadsheets/d/16JGy-ehf4taU0w4ABiKjsHGEXNDXxOlb__idY8ifUtQ/edit?usp=sharing) and work with your analyst(s) (@dougsillars @rviscomi @obto) if you have any questions about the data.
- [ ] Write the contents of your chapter and get it peer reviewed (@rachellcostello, @kleinab).
- [ ] File a PR to merge your written contents in markdown format to the [src/content/en/2019](https://github.com/HTTPArchive/almanac.httparchive.org/tree/master/src/content/en/2019) directory.

Refer to the [Authors' Guide](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Authors'-Guide) for writing advice.

**Comment by obto** [comment]
1. At a first glance the data looks good. Marking this as reviewed.

2. I'm now slowly working through the data and creating a doc with my thoughts and how we might organize this. I'll share it tomorrow after I'm done :)

**Comment by obto** [comment]
Whew, took a while to analyze the data. Here's the working document which contains my thoughts on the metrics: https://docs.google.com/document/d/1RPPuBL1JykWWhte-ivXeWCLu26OKBqXLeGrq7EMdG_g/edit?usp=sharing
