### ISSUE TITLE
Data viz CSP error

### ISSUE THREAD

**Issue by rviscomi** [HTTPArchive/almanac.httparchive.org#1578]
Discovered on https://almanac.httparchive.org/en/2019/performance#fcp-by-geography

![image](https://user-images.githubusercontent.com/1120896/100276318-54f14b00-2f2f-11eb-9b74-5d7b2dca1d92.png)

> Refused to frame 'https://accounts.google.com/' because it violates the following Content Security Policy directive: "frame-src 'self' docs.google.com www.youtube.com"

**Comment by bazzadp** [comment]
Sounds like Google Docs is wanting you to log in for some reason before displaying the chart. Mostly shouldn’t need this.

Not much we can do about this to be honest as Google (quite rightly) doesn’t allow framing of their account login page: https://securityheaders.com/?q=https%3A%2F%2Faccounts.google.com&hide=on&followRedirects=on

**Comment by rviscomi** [comment]
Yeah I think you're right. I opened the iframe URL in a new tab and it prompted me to log in again. It was some kind of corp/personal account mismatch thing. Sorry for the false alarm, I think we can close this.
