### ISSUE TITLE
Write content: Chapter 8. Security

### ISSUE THREAD

**Issue by rviscomi** [HTTPArchive/almanac.httparchive.org#158]
Part | Chapter | Authors | Reviewers | Analysts | Metrics | Analysis
-- | -- | -- | -- | -- | -- | --
II. User Experience | 8. Security | @arturjanc @ScottHelme | @paulcalvano @bazzadp @ghedo @ndrnmnn | @dotjs @jrharalson | #10 | #89

### Due by: October 7

- [x] Review the [results spreadsheet](https://docs.google.com/spreadsheets/d/1Zq2tQhPE06YZUcbzryRrBE6rdZgHHlqEp2XcgS37cm8/edit?usp=sharing) and work with your analyst(s) (@dotjs @jrharalson) if you have any questions about the data.
- [x] Write the contents of your chapter and get it peer reviewed (@paulcalvano @bazzadp @ghedo @ndrnmnn).
- [x] File a PR to merge your written contents in markdown format to the [src/content/en/2019](https://github.com/HTTPArchive/almanac.httparchive.org/tree/master/src/content/en/2019) directory.

Refer to the [Authors' Guide](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Authors'-Guide) for writing advice.

**Comment by rviscomi** [comment]
Sorry for the delay getting this one analyzed. Hopefully we're still able to turn this around in a few weeks. The results spreadsheet is really big and full of interesting insights.

**Comment by rviscomi** [comment]
👋 Greetings! Just checking in to make sure this is progressing and remind you of the October 7 deadline timed so we can launch at Chrome Dev Summit.

The checklist above indicates that you still need to review the results, write content, and get it reviewed. Feel free to reach out if you have any questions about the process.

**Comment by rviscomi** [comment]
I've heard from both Scott and Artur that they plan to work on this and get something ready by Monday 👍. Bumping up to "In Progress".

**Comment by catalinred** [comment]
Hi @rviscomi,

I scrolled through the Web Almanac: Security Analysis spreadsheet and within [this issue](https://github.com/HTTPArchive/almanac.httparchive.org/issues/10#issue-446806026) but at first sight, I wasn't able to find any mentions on the `target=_blank` vulnerability.

@mathiasbynens has a [good article](https://mathiasbynens.github.io/rel-noopener/) on when `rel=noopener` can help when used in conjunction with `target=_blank`.

**Comment by rviscomi** [comment]
Thanks @catalinred. It may be too late to add new metrics for this chapter (we're launching in a few weeks) but if there's already external research we can draw from, I think it'd still be good to discuss in this chapter if the authors are interested.

**Comment by rviscomi** [comment]
@ScottHelme @arturjanc just checking in to see if you've had time to start a draft. Any updates?

**Comment by bazzadp** [comment]
Closed with https://github.com/HTTPArchive/almanac.httparchive.org/pull/204
