### ISSUE TITLE
Review 2020 contributors before launch

### ISSUE THREAD

**Issue by bazzadp** [HTTPArchive/almanac.httparchive.org#1582]
There's been some change in teams as new people have come on board and others have unfortunately not had the time they hoped to have to contribute. So this is a placeholder to review the 2020 contributors (Authors, Reviewers and Analysts) in 2020.json before launch to make sure they accurately reflect those involved.

**Comment by rviscomi** [comment]
Generally related to #1195, I've also been thinking that we should make the markdown metadata the source of truth for content contributors, as opposed to the yyyy.json files. That would help avoid problems like this where the annual config file says someone was a contributor, but none of the chapters have claimed them. Still an open question how to track platform contributors who have no attachment to particular chapters. Maybe those teams (developers, designers) are still tracked in the yearly configs.

**Comment by rviscomi** [comment]
Sorry I realize now that #1654 is a duplicate of this issue

**Comment by bazzadp** [comment]
Closing this. We can discuss the longer term issue as part of #1195
