### ISSUE TITLE
Open contributors social links in new tab

### ISSUE THREAD

**Issue by bharatagsrwal** [HTTPArchive/almanac.httparchive.org#1611]
Should we open the social links of contributors in a new tab?, as current it opens on the same page and sometimes we lost where we were, so I was thinking of opening those links in a new tab instead of the current tab.

**Comment by bazzadp** [comment]
This was a conscious decision (see #827 ). Many say best practice is NOT to open in new tabs and leave in control of users (who can right click/hold down if they really want to open in new tabs) and there are [accessibility recommendations here too](https://www.w3.org/TR/WCAG20-TECHS/G200.html). Back should in most cases return the user back to the same place.

At the very least, if opening in new tabs, the user should know this is going to happen - but that's difficult to do with without changing the design of the social link icons.

Personally my preference is to leave as is but open to hearing other opening.

**Comment by bazzadp** [comment]
Gonna close this. Feel free to reopen for discussion if you strongly disagree.
