### ISSUE TITLE
Combine contributor bylines

### ISSUE THREAD

**Issue by rviscomi** [HTTPArchive/almanac.httparchive.org#1616]
In the rare case when a single contributor is both author and analyst or reviewer and analyst, combine their bylines into one.

Current behavior:

![image](https://user-images.githubusercontent.com/1120896/100966915-0548eb80-34fc-11eb-930a-99b5a3b19d3a.png)

Desired behavior:

![image](https://user-images.githubusercontent.com/1120896/100967113-6a044600-34fc-11eb-985c-3019df331724.png)

This is low priority and not launch blocking, so I added it to the [Backlog](https://github.com/HTTPArchive/almanac.httparchive.org/milestone/12) milestone. This would be a good first issue for any new developers to learn the template and translation system.

**Comment by bazzadp** [comment]
This is presumably only when the bylines are exactly the same?

So in above example if there were additional reviewers we shouldn’t be merged despite Thomas being in both bylines? And similarly if there where additional analysts that would prevent the merge?

However if an Barry was both an additional reviewer and analyst then the Reviewr and Analyst sets are still the same so they can be merged.

That correct?

**Comment by rviscomi** [comment]
Yes, correct
