### ISSUE TITLE
Fixed position chapter CTAs

### ISSUE THREAD

**Issue by rviscomi** [HTTPArchive/almanac.httparchive.org#1617]
At the bottom of each chapter we have three calls to action (CTAs) that we suggest to readers if they'd like to continue learning about the topic:

- discuss it in the comments
- view the raw results spreadsheet
- view the underlying queries

![image](https://user-images.githubusercontent.com/1120896/100968882-2ca1b780-3500-11eb-956f-90b86d90eb77.png)

I'd like to see a design that affixes these buttons to the bottom right corner of the screen so that readers can more easily discover them. I could be dissuaded from showing the results/queries at all times, but I think showing the comment button would be great to get more engagement amongst readers and authors.

I would also propose two other CTAs:

- edit this page
- translate this page

If a reader spots a typo or bad data, they should be one click away from having a GitHub issue pre-populated with the boilerplate info. I've created [issue templates](https://github.com/HTTPArchive/almanac.httparchive.org/issues/new?assignees=&labels=bug%2C+writing&template=2020-content-issue.md&title=Issue+with+the+2020+%5BCHAPTER%5D+chapter) to help make this even more streamlined, and we can even dynamically assign issues to the relevant authors/editors/translators by appending more metadata to that URL.

If a reader is viewing a non-English version of the site but a chapter is only available in English, there should also be a CTA for that person to volunteer to translate it. It would be nice to be one click away from editing the chapter's markdown file, but the button should probably take readers to #923 or someplace where it's easy to start contributing.

For design ideas see [this article](https://web.dev/chrome-ux-report-api/) (mobile) on web.dev:

![image](https://user-images.githubusercontent.com/1120896/100968733-e51b2b80-34ff-11eb-8ef9-3b179ed48e7b.png)

Desktop:

![image](https://user-images.githubusercontent.com/1120896/100968811-0ed45280-3500-11eb-8d5c-159027697fd1.png)

Backlog item (not launch blocking)

**Comment by AbbyTsai** [comment]
Here’s my thoughts in these CTAs and would love to hear yours.

Purpose: Call to audience’s actions.

Proposed actions:
1.Explore raw results and query: position in the end of article. 
   CTA1.Review result,  CTA2.Review queries.  
2.Improve chapters: fixed position at bottom in the right corner.
   CTA3.Comments (via httparchive forum),  CTA4.Edit (via github). 
3.Increase language: fixed position at bottom in the right corner.
  CTA5.Join translator (via github).
   
After: (desktop)
![image](https://user-images.githubusercontent.com/44442451/103972410-ed722080-51a7-11eb-86d2-235179e7150f.png)
![image](https://user-images.githubusercontent.com/44442451/103972464-07abfe80-51a8-11eb-8b7d-19a235964d4b.png)

(mobile)
![image](https://user-images.githubusercontent.com/44442451/103971771-61abc480-51a6-11eb-9f68-f10bc5021e7e.png)

Questions:
- How to define the path and viewBox in `xmlns:xlink` a new svg of graphic symbols. For example, design an edit symbol into CTA.  
- How to set the viewport to mobile mode only showing svg without text and maybe a hover visibility in text to clarify the definition of graphic symbol.

**Comment by AbbyTsai** [comment]
Hi, @HTTPArchive/developers  Here would love to hear more ideas in CTAs design and share some resource in [SVG](https://developer.mozilla.org/en-US/docs/Web/SVG/Tutorial/Paths), [RWD](https://www.w3schools.com/css/css_rwd_mediaqueries.asp) on previous questions. Thanks.

**Comment by bazzadp** [comment]
I like your proposal. Only thing is I would your "Edit" button to "Suggest Edit" so it's similar size (in English at least!) to the others, rather than shorter at the moment:

![buttons](https://user-images.githubusercontent.com/10931297/104806241-03966700-57ce-11eb-80c8-47bcc16acb38.png)

And "Join Translator" should be "Help Translate" I think.

> How to define the path and viewBox in xmlns:xlink a new svg of graphic symbols. For example, design an edit symbol into CTA.

I'm afraid I don't know SVGs that well at all, so can't really help here. But don't you have all the SVG icons you need already so don't need any more so shouldn't need to change this?

> How to set the viewport to mobile mode only showing svg without text and maybe a hover visibility in text to clarify the definition of graphic symbol.

You shouldn't need to change the SVG for this.

For example we currently have this:

```html
  <a class="alt btn" href="https://discuss.httparchive.org/t/{{ metadata.get('discuss') }}">
    <svg width="18" height="18" role="img">
      <title>{{ self.discuss_this_chapter() }}</title>
      <use xmlns:xlink="http://www.w3.org/1999/xlink" xlink:href="#comment"></use>
    </svg>
    <span id="num_comments">{{ self.comments_fallback() }}
    </span> <span data-translation id="comment-singular">{{ self.comment() }}</span>
    <span data-translation id="comment-plural">{{ self.comments() }}</span>
  </a>
```

We then set `display:none` on `#comment-singular` or `#comment-plural". We do this in JavaScript based on the number of comments returned by the API call.

You could do similar to hide the text but in a media-query in CSS, rather than in JavaScript. So you don't alter the icon - it stays the exact same, you just show or hide the label in CSS. For mobile use the `@media (max-width: 600px)` section of `pages.css` starting on line 718.

**Comment by AbbyTsai** [comment]
Nice insight. I like the design idea on web.dev as well and happy to see if it could be implement here. Sorry, my technological skills seemly don't catch them.

**Comment by rviscomi** [comment]
Hi @AbbyTsai hope you're well! I wanted to check in to see if you'd be able to pick back up on the progress you've made on this issue so far. Do you still have an open branch with your code changes?

**Comment by AbbyTsai** [comment]
Not sure my magical potential could paint it. what's the schedule on it? if it's not in hurry, may I have a second try?

**Comment by rviscomi** [comment]
There's no rush to get this feature out so I'd say we have until ~November to implement it before the 2021 launch.

**Comment by AbbyTsai** [comment]
Nice knowing it. Sorry saying those're probably going longer than our plan.^^

**Comment by AbbyTsai** [comment]
thank warm y'all and lots of inspiring articles by web.dev which give the space to those try-error circles. Here's the progress love to have more thoughts in. ^^
 
![image](https://user-images.githubusercontent.com/44442451/117545964-a95e3200-b05a-11eb-9cd3-70310917b5a0.png)
![image](https://user-images.githubusercontent.com/44442451/117545994-cabf1e00-b05a-11eb-9063-5a8d80269987.png)
![image](https://user-images.githubusercontent.com/44442451/117546170-b2033800-b05b-11eb-8c15-a1989b11829b.png)

**Comment by tunetheweb** [comment]
#2196 added a single fixed CTA and some more CTAs to the "Explore this chapter" section ("Suggest edit" and "Help translate"), however in that we also discussed if we wanted more CTAs with an expandable menu so leaving this issue open for now in case there is further work on this.
