### ISSUE TITLE
Improve slugification of special characters in headings

### ISSUE THREAD

**Issue by rviscomi** [HTTPArchive/almanac.httparchive.org#1619]
Slugs are the anchor IDs generated from headings. Some special characters are stripped out, the text is converted to lowercase, and spaces are replaced by hyphens. This allows the slug to be used as an anchor in the URL.

In the 2020 HTTP/2 chapter, one heading reads "Looking Toward the Future: HTTP/3". The corresponding slug is `looking-toward-the-future--http3`. Note the double hyphen near the end.

Revisit the string transformation function that generates these slugs to prevent double hyphens.

**Comment by bazzadp** [comment]
These are generated automatically by Showdown so we’d need to either fix upstream, or hack the HTML produced post-conversion.

However we can override it by telling Showdown what anchor of to sue. And this was the solution introduced in #1464 to also handle `<span lang="en">` attributes in the translations.

So replace this:
```
## Looking Toward the Future:  HTTP/3
```
With this which includes the desired anchor id:
```
## Looking Toward the Future:  HTTP/3 {looking-toward-the-future-http3}
```

**Comment by rviscomi** [comment]
Oh wait, seeing it in monospace in your comment made me realize why it got a double hyphen: there are two spaces before "HTTP/3". This should be fixed in the heading itself.
