### ISSUE TITLE
Fix typography of Featured Chapter home page section

### ISSUE THREAD

**Issue by rviscomi** [HTTPArchive/almanac.httparchive.org#1629]
The "25.24 KB" part of the Markup chapter's featured stats appears like a bug:

![image](https://user-images.githubusercontent.com/1120896/101203087-2d3d6980-3638-11eb-8ae6-c590b831935c.png)

If possible, use nowrap to prevent stats from breaking onto multiple lines (labels are long and can still wrap).
If not possible, add more line-height to the stats so that wrapped text has more visual space.

**Comment by bharatagsrwal** [comment]
![0b3e9788-15a9-4f16-a850-f6c2571deaeb](https://user-images.githubusercontent.com/43988371/101214062-61994000-36a1-11eb-8b88-f9d375c7eaf6.gif)

Could you please help me with the screen size? as I tried in responsive in chrome dev tools.

**Comment by rviscomi** [comment]
Hi @bharatagsrwal my viewport width is 1176px with a DPR of 2

**Comment by bharatagsrwal** [comment]
![image](https://user-images.githubusercontent.com/43988371/101216891-5563b180-36a6-11eb-971e-85e7a68245d9.png)

Hey @rviscomi, I am trying to reproduce it but I am unable to get this exactly
I have tried on various widths from 890 to 910 and many others

![5a7c4c5b-a7d1-410b-b5f3-a2e0d924b558](https://user-images.githubusercontent.com/43988371/101241401-a06bdc00-371b-11eb-94ad-5eeac875163f.gif)

I got this only when I refresh page and until font does not get load

**Comment by bazzadp** [comment]
Ok but no harm adding a `no-wrap` class around these figures anyway? M

I actually added such a class in #1602 for a different reason - though I put it in page.css and we should move it to 2019.css as part of this so index.html can use it too as it doesn’t load page.css.

**Comment by bharatagsrwal** [comment]
Okay cool, adding `no-wrap` class in `2019.css` and using those classes in index.html where stats are shown

**Comment by bharatagsrwal** [comment]
Hey @rviscomi, @bazzadp I have created a pull request [https://github.com/HTTPArchive/almanac.httparchive.org/pull/1634](https://github.com/HTTPArchive/almanac.httparchive.org/pull/1634), have a look at this


![image](https://user-images.githubusercontent.com/43988371/101259364-7b449100-374e-11eb-941d-8595d364aea0.png)
without `no-wrap`

![image](https://user-images.githubusercontent.com/43988371/101259371-8697bc80-374e-11eb-98d0-2c2d6b4297c6.png)
with `no-wrap`

this text is changed from inspect element 😛

**Comment by rviscomi** [comment]
LGTM thanks for the quick fix @bharatagsrwal!
