### ISSUE TITLE
Write content: Chapter 10. SEO

### ISSUE THREAD

**Issue by rviscomi** [HTTPArchive/almanac.httparchive.org#163]
Part | Chapter | Authors | Reviewers | Analysts | Metrics | Analysis
-- | -- | -- | -- | -- | -- | --
II. User Experience | 10. SEO | @rachellcostello @ymschaap @AVGP | @clarkeclark @andylimn @voltek62 @AymenLoukil @catalinred | @ymschaap | #12 | #91

### Due by: October 7

- [x] Review the [results spreadsheet](https://docs.google.com/spreadsheets/d/1uARtBWwz9nJOKqKPFinAMbtoDgu5aBtOhsBNmsCoTaA/edit?usp=sharing) and work with your analyst(s) (@ymschaap) if you have any questions about the data.
- [x] Write the contents of your chapter and get it peer reviewed (@clarkeclark @andylimn @voltek62).
- [x] File a PR to merge your written contents in markdown format to the [src/content/en/2019](https://github.com/HTTPArchive/almanac.httparchive.org/tree/master/src/content/en/2019) directory.

Refer to the [Authors' Guide](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Authors'-Guide) for writing advice.

**Comment by ymschaap** [comment]
@rachellcostello @AVGP is it an idea to setup a call (hangout, zoom) together to discuss how to get started on this? If so, drop me your e-mail so we can set a date in calendar.

**Comment by ymschaap** [comment]
I've made a quick outline on the content:
> https://github.com/HTTPArchive/almanac.httparchive.org/commit/27a6adc68eb06abfb8f1d11bf3f13a86f681873e

Also @rachellcostello @AVGP: reminder of my idea to setup a call together.

**Comment by ymschaap** [comment]
Ok, I've sent an email with dates.

@rviscomi when is the new deadline for the content? 
https://docs.google.com/spreadsheets/d/1LR29JpI2XJSjan_z6uP1YpRy4EYYivYZPqCIG-9sfFY/ shows we are behind on schedule. Maybe provide on update on that?

**Comment by rviscomi** [comment]
The current milestones and schedule sheet are correct: October 7 is the target deadline for at least the first draft, ideally final draft.

**Comment by clarkeclark** [comment]
@rviscomi I know it's really late, but would it be possible to get the distribution of the length of the first H1 tag across sites? I'd settle for regex.

**Comment by ymschaap** [comment]
@clarkeclark we do something similar with the <title> tag, so technically it is not an issue:
> https://github.com/HTTPArchive/almanac.httparchive.org/blob/master/sql/2019/10_SEO/10_07b.sql

**Comment by rviscomi** [comment]
Added as metric 10_16: https://docs.google.com/spreadsheets/d/1uARtBWwz9nJOKqKPFinAMbtoDgu5aBtOhsBNmsCoTaA/edit#gid=758241096

**Comment by rachellcostello** [comment]
My apologies @ymschaap and @AVGP - I've just returned from annual leave so have been catching up on everything this morning! I've sent you my email address Yvo, but 9:00-12:00 BST tomorrow or 13:30-15:00 BST Friday are the best time slots for me this week. I'll also be available next week.

**Comment by rviscomi** [comment]
Just checking in to say I'm happy to see this moving along! Thanks everyone for your help getting this launched on time! 🤜💥 🤛

**Comment by ymschaap** [comment]
@rviscomi, two questions:
* do we already have to think about the charts/tables? Or are those added later? E.g. we just add placeholders?
* Are the general limitations of the web crawl already laid out to the reader (e.g. homepage only, not a Google project, etc) or do we need to emphasise those as well?

**Comment by rviscomi** [comment]
> do we already have to think about the charts/tables? Or are those added later? E.g. we just add placeholders?

For now placeholders would be great. You could generate a simple chart in Sheets and drop that in as an indicator of what you're trying to convey or just `<insert bar chart of metric 10.01 here>` for example. We're still working on the design of the data viz and will be applying that across all chapters for consistency.

> Are the general limitations of the web crawl already laid out to the reader (e.g. homepage only, not a Google project, etc) or do we need to emphasise those as well?

There will be a universal Methodology page that generally explains how HTTP Archive works and how we analyzed the data for the Almanac. It's a good idea for authors to have their own brief Methodology section to explain the scope and limitations of the chapter's analysis. For example, some metrics might only be available for mobile because they depend on Lighthouse metrics, so that would be good to remind readers.

Thanks for the questions, these would be great to include in the Author's Guide.

**Comment by rviscomi** [comment]
@ymschaap @AVGP @rachellcostello have you made any progress on the action items in https://github.com/HTTPArchive/almanac.httparchive.org/issues/163#issue-494397228? Also let me know if you have a doc of the chapter draft I could look at. Thanks everyone!

**Comment by AVGP** [comment]
Sorta. We have a shared doc where we take notes (I shared it with you) and once we got everything together, we will put that into a proper draft, proofread and get it in as a PR.

**Comment by ymschaap** [comment]
@AVGP @rachellcostello look at what Chapter 12 made:
> https://docs.google.com/document/d/1ypPGDyvpWJcil1bNuvq3D8DXcwjHN00NX2iYQtU70oo/edit#heading=h.jcincmxdwr3s

I personally:
* like their friendly tone of voice
* added relevant links, this is the web, we should to
* already added charts placeholders

Can I do anything for the parts you got assigned?

**Comment by rachellcostello** [comment]
Thanks for sharing this, it's useful to see another chapter as a reference point! And I completely agree with you.

Now that the structure is there, I'll write up a second draft today and will add in relevant links.

Would you be able to add in some placeholder charts @ymschaap? :)

**Comment by ymschaap** [comment]
Ok, to move things forward I've followed the style of chapter 12 a bit and changed the order and tried to add more context to the metrics we discuss. 

I'll also work on the Advanced topic, given that is still not finished, but I can finish that tonight.

Hello @clarkeclark @andylimn @voltek62. Your help is much appreciated to make this into an amazing chapter. Specific:

* look at the data to get an idea of what we are working with:
> https://docs.google.com/spreadsheets/d/1uARtBWwz9nJOKqKPFinAMbtoDgu5aBtOhsBNmsCoTaA/edit#gid=1962850376

Then read the draft:
> > https://docs.google.com/document/d/1Bo5sEFdGqnv_uCyxP-mEDKXrD1NCLVjGFxnH7PgUmPc/edit?usp=sharing

Note; the **advanced** section, I'm working on now, but we have a deadline :)

Help us by:
* point out things that are to raw or confusing/irrelevant
* any relevant links we should add
* any missing metric context (new / trending?)
* things you miss that aren't pointed out
* spice up the raw data 
* copyeditting :)

cc @rviscomi

**Comment by clarkeclark** [comment]
@ymschaap Will review this evening

**Comment by clarkeclark** [comment]
@ymschaap just requested access to the draft

**Comment by ymschaap** [comment]
@clarkeclark made the draft link above public. Have access now?

**Comment by clarkeclark** [comment]
@ymschaap still can't access. Pls invite me directly via jfox@venturemarketing.com

**Comment by andylimn** [comment]
@ymschaap same here, could you invite me too please and I'll take a look today (andrew.limn@artefact.com). Thanks

**Comment by AymenLoukil** [comment]
Hello ! 
I can give a hand if you want :)

**Comment by catalinred** [comment]
Hi all,

I'd be happy to help review this awesome resource you're working on!

**Comment by rviscomi** [comment]
Thanks @AymenLoukil and @catalinred! I've added you both as reviewers for this chapter.

@catalinred I've also sent you an invitation to join the Reviewers team. You can go to https://github.com/HTTPArchive to accept. Thanks again!

**Comment by catalinred** [comment]
Thank you @rviscomi 

Sorry for being so late to the party, @rachellcostello @ymschaap @AVGP I'll do my best to help you out with this!

Also, what is the preferred method to share the feedback/thoughts on the above spreadsheet and draft? Email / slack channel / this thread?

**Comment by rviscomi** [comment]
@catalinred feedback can be provided in the [draft doc](https://docs.google.com/document/d/1mI_p09005pssgtsWutUflfp5mav5MhdfreYmpy1EQo4/edit?usp=sharing).

**Comment by clarkeclark** [comment]
@ymschaap just reviewed current draft. Aside from decisions on what to include wrt AMP, it's good to go for me. Thanks for the opportunity to help out.

**Comment by rviscomi** [comment]
@ymschaap @rachellcostello @AVGP apologies for the delay, this was a hectic week! Your chapter is now edited and visualized at https://almanac.httparchive.org/en/2019/seo. It should now have responsive and accessible data visualizations. File a bug if you see anything wonky. I've removed the "unedited" tag.
