### ISSUE TITLE
Launch the 2020 Web Almanac 🚀

### ISSUE THREAD

**Issue by rviscomi** [HTTPArchive/almanac.httparchive.org#1630]
#### Content
- [x] Home page content updated - PR #1651 
- [x] Foreword added #1406
- [x] All viable chapters added #989 
- [x] Update contributors #1582 #1654 

#### QA
- [x] Staging version deployed: https://20201209t155443-dot-webalmanac.uk.r.appspot.com
- [x] Staging site manually tested for basic functionality
- [x] Automated tests of the staging site pass (LH audits)
- [x] Spell check run on QA site and final spelling mistakes fixed
- [x] Broken links crawl check completed on QA site
- [x] [Twitter](https://cards-dev.twitter.com/validator) and structured data test
- [x] Google Search Console reviewed for errors
- [x] Google Analytics checked to ensure collecting data and errors (e.g. 404s) checked.

#### Deployment
- [x] Full site release to version 2.0.0 at 10:00am UTC-5 (NYC time) on Wednesday, December 9
- [x] Sitemap submission to Google Search Console to pick up launched chapters quicker
- [x] Final QA
- [x] Formal [public announcement](https://twitter.com/rick_viscomi/status/1336718249388625921) by @rviscomi on social channels at 12:00pm UTC-5 (NYC time)
- [x] Monitor [analytics](https://datastudio.google.com/reporting/1c89f8c3-7e11-4376-8815-39966e13180e) and server logs

**Comment by bazzadp** [comment]
Submitted sitemap to Google so closing this.
