### ISSUE TITLE
Issue with the 2020 Capabilities chapter

### ISSUE THREAD

**Issue by chengxicn** [HTTPArchive/almanac.httparchive.org#1635]
**URL**
https://almanac.httparchive.org/en/2020/capabilities
**Describe the issue**
Figure 13.8, Periodic Background Sync API  figure description wrong

**Expected behavior**
Chart of **Periodic Background Sync API**  usage, based on the number of pages monitored by HTTPArchive. It compares the usage on mobile and desktop devices. Since April 2020, the API is used by one to two desktop and mobile pages.
**Screenshots**
 
![image](https://user-images.githubusercontent.com/30398527/101259921-fa45c380-3766-11eb-967a-acb0b3fa8c2c.png)

**Comment by rviscomi** [comment]
Great find @chengxicn! And this is a perfect use case for the chapter-specific issue template, I'm so glad to see it in action.

I see two minor issues with this description:

- Replace `Idle Detection API` with `Periodic Background Sync API` as you noted
- Replace `HTTPArchive` with `HTTP Archive` (global find/replace throughout the chapter)

We should also double check that the sheet/query metadata for this figure are applicable to this API.

**Comment by bazzadp** [comment]
Tagging @ksakae1216 and @lex111 whi have already translated this chapter.
