### ISSUE TITLE
Encourage authors to use HTML anchors instead of Markdown [title](url)

### ISSUE THREAD

**Issue by borisschapira** [HTTPArchive/almanac.httparchive.org#1660]
When translating a page, we can translate the title of a link but not its destination language. Even if I translate "foo" to "bar", if used in a link, 

`[foo](url)` will be translated in `[bar](url)` and compiled in `<a href="url">bar</a>`.

Even if "bar" is in the right language, the anchor should use the attribute `hreflang` to express the language of the linked page:  `<a href="url" hreflang="en">bar</a>`.

**Comment by bazzadp** [comment]
I see where you are coming from @borisschapira , and it's the same with using English words in links, which we saw a lot of in the Capabilities chapter where things like this:

```
[Progressive Web Apps](./pwa) (PWA) are a cross-platform
```

Were Translated (in Russian) to things like this (and so had to be converted to HTML):

```
<a href="./pwa">Прогрессивные веб-приложения (<span lang="en">Progressive Web Apps</span>, PWA)</a>
```

However, I'm not convinced we should encourage the Authors to do this. To me, this is a Translation issue and no an issue for the native English that the chapters are written in. Unfortunately enforcing (or even encouraging) this on the Authors (or even the Editors) is not something I believe we should do as would rather they concentrate on the writing.

But really do appreciate it does cause extra effort for the Translation team!

**Comment by borisschapira** [comment]
I understand. 
Maybe I'll work the 2019 translations again in the future to apply `hreflang` where it is useful, aka when the lang of the linked document is not the same as the current page.

**Comment by bazzadp** [comment]
Yeah that `hreflang` is a good call. Should use it more. Will definitely encourage that in the translations.
