### ISSUE TITLE
Finalize assignments: Chapter 15. Compression

### ISSUE THREAD

**Issue by rviscomi** [HTTPArchive/almanac.httparchive.org#17]
Section | Chapter | Author | Reviewers
-- | -- | -- | --
IV. Content Distribution | 15. Compression | @paulcalvano | @yoavweiss @colinbendell 

**Due date:** To help us stay on schedule, please complete the action items in this issue by June 3.

**To do:**
- [x] Assign subject matter expert (author)
- [x] Finalize peer reviewers
- [x] Finalize metrics

**Current list of metrics:**

- What compression formats are being used (gzip, brotli, etc)
- Is there anything we can tell from the level of compression
- Are there missed opportunities for compressing resources
- Compression by Content Type

👉 **AI (@paulcalvano):** Finalize which metrics you might like to include in an annual "state of third parties" report powered by HTTP Archive. Community contributors have initially sketched out a few ideas to get the ball rolling, but it's up to you, the subject matter experts, to know exactly which metrics we should be looking at. You can use [the brainstorming doc](https://docs.google.com/document/d/1sCIMeErYvaQb5x9Acdb6ImYdn0-buHRhYGvz2HoysmM/edit#heading=h.iznoa2266s2c) to explore ideas.

The metrics should paint a holistic, data-driven picture of the third party landscape. The HTTP Archive does have its limitations and blind spots, so if there are metrics out of scope it's still good to identify them now during the brainstorming phase. We can make a note of them in the final report so readers understand why they're not discussed and the HTTP Archive team can make an effort to improve our telemetry for next year's Almanac.

**Next steps:** Over the next couple of months analysts will write the queries and generate the results, then hand everything off to you to write up your interpretation of the data.

**Additional resources:**
- [All chapter assignments](https://github.com/HTTPArchive/httparchive.org/issues/140)
- [Project timeline](https://docs.google.com/spreadsheets/d/1LR29JpI2XJSjan_z6uP1YpRy4EYYivYZPqCIG-9sfFY/edit?usp=sharing)
- [About the project](https://discuss.httparchive.org/t/planning-the-web-almanac-2019/1553)

**Comment by paulcalvano** [comment]
* Compression by Content Type
*

**Comment by rviscomi** [comment]
@paulcalvano	@yoavweiss @colinbendell we're hoping to finalize the metrics for each chapter today. Could you edit https://github.com/HTTPArchive/almanac.httparchive.org/issues/17#issue-446806384 and update it with anything that's missing? We're aiming for 10 or so metrics per chapter. When that's done please tick the last TODO checkbox item and close this issue. Thanks!

**Comment by paulcalvano** [comment]
Updated.  @yoavweiss @colinbendell  - are there any other metrics you'd like to see here?

**Comment by rviscomi** [comment]
Ping @paulcalvano @yoavweiss @colinbendell. Just want to make sure this chapter is ready to go.

**Comment by rviscomi** [comment]
Last call for metrics. Speak now or forever hold your gzip.
