### ISSUE TITLE
Write content: Chapter 4. Media

### ISSUE THREAD

**Issue by rviscomi** [HTTPArchive/almanac.httparchive.org#170]
Part | Chapter | Authors | Reviewers | Analysts | Metrics | Analysis
-- | -- | -- | -- | -- | -- | --
I. Page Content | 4. Media | @dougsillars @colinbendell @Yonet | @ahmadawais @kornelski @eeeps | @dougsillars @rviscomi | #6 | #85

### Due by: October 7

- [x] Review the [results spreadsheet](https://docs.google.com/spreadsheets/d/1hj9bY6JJZfV9yrXHsoCRYuG8t8bR-CHuuD98zXV7BBQ/edit?usp=sharing) and work with your analyst(s) (@dougsillars @rviscomi) if you have any questions about the data.
- [x] Write the contents of your chapter and get it peer reviewed (@ahmadawais @kornelski @eeeps).
- [x] File a PR to merge your written contents in markdown format to the [src/content/en/2019](https://github.com/HTTPArchive/almanac.httparchive.org/tree/master/src/content/en/2019) directory.

Refer to the [Authors' Guide](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Authors'-Guide) for writing advice.

**Comment by rviscomi** [comment]
👋 Greetings! Just checking in to make sure this is progressing and remind you of the October 7 deadline timed so we can launch at Chrome Dev Summit.

The checklist above indicates that you still need to review the results, write content, and get it peer reviewed. Feel free to reach out if you have any questions about the process.

**Comment by ahmadawais** [comment]
Looking forward to reviewing the piece.

**Comment by colinbendell** [comment]
Hope to have a draft shortly. coordinating schedules with @dougsillars

**Comment by dougsillars** [comment]
Here is the video section:
https://docs.google.com/document/d/10Mecaxg_IlVqJonm7zqikMYc-d_fqBLKWcEiosqKIxc/edit?usp=sharing

**Comment by ahmadawais** [comment]
Thanks for sharing, @dougsillars — just reviewed it. Looks great. Sent some minor nitpicks.

**Comment by rviscomi** [comment]
Adding @eeeps as an official reviewer for this chapter :)

**Comment by colinbendell** [comment]
I've completed the overhaul of the images section. Lots of things that we will have to defer for another iteration.

**Comment by rviscomi** [comment]
@colinbendell @dougsillars the draft is in great shape! Could someone convert it to markdown and submit a PR so we can close this out?

**Comment by rviscomi** [comment]
🛎 friendly ping. @colinbendell @dougsillars are either of you able to do the markdown PR?

**Comment by ahmadawais** [comment]
I just finished my review. Left suggestions in the Google Doc. Everything else seems to be on point and 👌

**Comment by dougsillars** [comment]
Rick,

I'll work on this tomorrow.

Doug

**Comment by rviscomi** [comment]
Closed by #338
