### ISSUE TITLE
Write content: Chapter 7: Performance

### ISSUE THREAD

**Issue by rviscomi** [HTTPArchive/almanac.httparchive.org#171]
Part | Chapter | Authors | Reviewers | Analysts | Metrics | Analysis
-- | -- | -- | -- | -- | -- | --
II. User Experience | 7. Performance | @rviscomi | @JMPerez @obto @sergeychernyshev @zeman | @rviscomi @raghuramakrishnan71 | #9 | #88

### Due by: October 7

- [x] Review the [results spreadsheet](https://docs.google.com/spreadsheets/d/1zWzFSQ_ygb-gGr1H1BsJCfB7Z89zSIf7GX0UayVEte4/edit?usp=sharing) and work with your analyst(s) (@rviscomi @raghuramakrishnan71) if you have any questions about the data.
- [x] Write the contents of your chapter and get it peer reviewed (@JMPerez @obto @sergeychernyshev).
- [x] File a PR to merge your written contents in markdown format to the [src/content/en/2019](https://github.com/HTTPArchive/almanac.httparchive.org/tree/master/src/content/en/2019) directory.

Refer to the [Authors' Guide](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Authors'-Guide) for writing advice.

**Comment by rviscomi** [comment]
@zeman I've sketched out a very rough outline of the chapter [here](https://github.com/HTTPArchive/almanac.httparchive.org/blob/master/src/content/en/2019/performance.md). How does that look to you?

Any questions/concerns about the lab data in the [results sheet](https://docs.google.com/spreadsheets/d/1zWzFSQ_ygb-gGr1H1BsJCfB7Z89zSIf7GX0UayVEte4/edit?usp=sharing)?

**Comment by zeman** [comment]
@rviscomi the outline looks promising. Unfortunately this is really poor timing for me as I'm away on holiday till the 14th. If the deadline is the 7th then I'm afraid I can't take on the writing. I'm still happy to be a reviewer when I'm back.

**Comment by rviscomi** [comment]
Ahh ok thanks for the update @zeman. We can stall the release of this chapter, or at least the Lab section, until you're available. I'd still love to have your contributions. I'll check in with you again after you're back from holiday.

**Comment by rviscomi** [comment]
@JMPerez @obto @sergeychernyshev please have a look at [this draft](https://docs.google.com/document/d/1S0De_lBFCuqLWa2ZlB31SKQZE_zkboweeAUWLrcDuLw/edit?usp=sharing) of the field performance section. When @zeman's lab performance section is complete we can work on a unified intro/conclusion.

**Comment by obto** [comment]
@rviscomi I'm planning on reviewing this over the weekend. I'll let you know when I've finished :)

**Comment by sergeychernyshev** [comment]
Same here.

**Comment by rviscomi** [comment]
Thanks @obto and @sergeychernyshev!

**Comment by sergeychernyshev** [comment]
Left a few comments in the doc.

**Comment by rviscomi** [comment]
I heard from Mark via email that he's unable to commit to writing the Lab section. Given the state of the deadline let's stretch the Field section to the entire chapter. I'll work on rewriting it to fit the new context.

**Comment by rviscomi** [comment]
@sergeychernyshev @obto @JMPerez @zeman @hakimalek I've revised the intro/conclusion and it's ready for another review: https://docs.google.com/document/d/1S0De_lBFCuqLWa2ZlB31SKQZE_zkboweeAUWLrcDuLw/edit?usp=sharing

**Comment by hyperpress** [comment]
I'll do a review later tonight or morning. Thanks.

**Comment by rviscomi** [comment]
I'll be rewriting a bit of our FCP and FID analysis to include new and unreleased (_shhhh!_) PSI thresholds:

Metric | Fast | Slow | Moderate
-- | -- | -- | --
FCP | p75 at 1000ms | p25 at 3000ms | Everything else
FID | p95 at 100ms | p05 at 300ms | Everything else

Notable changes:

- rename "average" to "moderate"
- lower barrier to fast FCP from p90 to p75
- increase barrier to fast FID from 50ms to 100ms

I plan to include the old results for comparison and also for a more accurate representation of "the state of web performance as of July 2019". Having these new thresholds in the Almanac will go a long way to making these results more relevant at CDS.

cc @igrigorik
