### ISSUE TITLE
Large figures create horizontal scroll

### ISSUE THREAD

**Issue by sudheendrachari** [HTTPArchive/almanac.httparchive.org#1717]
Large figures/numbers are causing horizontal scroll in mobile view. These should ideally wrap to next line

![A11y - Large figures overflow horizontal](https://user-images.githubusercontent.com/10291571/101674255-47cf7280-3a7e-11eb-9660-3d5f1af3393a.png)

**Comment by bazzadp** [comment]
I added a slightly smaller `medium-number` class for another chapter. We should use this one here. Fancy seeing if it resolves for the screen size you're looking at and then submitting a PR for that?

**Comment by bazzadp** [comment]
Ok just seen it in [the Security chapter](https://almanac.httparchive.org/en/2020/security#fig-9) and yes needs overflow scroll at very least as currently overflows the whole page.

![742A9CEA-B7FD-4D2C-A732-7435E02C9ED4](https://user-images.githubusercontent.com/10931297/101737206-78360180-3abc-11eb-8ba5-e729428afafc.jpeg)
