### ISSUE TITLE
Write content: Chapter 16: Caching

### ISSUE THREAD

**Issue by rviscomi** [HTTPArchive/almanac.httparchive.org#172]
Part | Chapter | Authors | Reviewers | Analysts | Metrics | Analysis
-- | -- | -- | -- | -- | -- | --
IV. Content Distribution | 16. Caching | @paulcalvano | @yoavweiss @colinbendell | @paulcalvano @obto | #18 | #97

### Due by: October 7

- [x] Review the results spreadsheet (TBD) and work with your analyst(s) (@paulcalvano @obto) if you have any questions about the data.
- [x] Write the contents of your chapter and get it peer reviewed (@yoavweiss @colinbendell).
- [x] File a PR to merge your written contents in markdown format to the [src/content/en/2019](https://github.com/HTTPArchive/almanac.httparchive.org/tree/master/src/content/en/2019) directory.

Refer to the [Authors' Guide](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Authors'-Guide) for writing advice.

**Comment by rviscomi** [comment]
@paulcalvano if you've started writing this chapter could you share the draft doc?

**Comment by paulcalvano** [comment]
@rviscomi  - sure, here's the work-in-progress draft.   It's a big chapter, and I'm hoping to finish it up tomorrow (Tuesday). https://docs.google.com/document/d/1iDkOLgQXj8dV_lh2JWzyj4TUEGPFcIrEXa4Z4ixVhCg/edit?usp=sharing

**Comment by paulcalvano** [comment]
Hello - this chapter is ready for review.   // cc @colinbendell  @yoavweiss  @obto 

https://docs.google.com/document/d/1iDkOLgQXj8dV_lh2JWzyj4TUEGPFcIrEXa4Z4ixVhCg/edit?usp=sharing

**Comment by obto** [comment]
I'll give it a read tonight!

**Comment by obto** [comment]
@paulcalvano Finished my review. Was a lovely read.

Left a few questions and comments, but most of the suggestions were for grammar and tightening up sentences.

**Comment by bazzadp** [comment]
FYI @paulcalvano I've started copyediting this. Will have something for you later today, or tomorrow am at the latest.
