### ISSUE TITLE
Issue with the 2020 [JavaScript] chapter

### ISSUE THREAD

**Issue by faraixyz** [HTTPArchive/almanac.httparchive.org#1732]
**URL**

https://almanac.httparchive.org/en/2020/javascript#correlating-javascript-use-to-lighthouse-scoring

**Describe the issue**
Fig 2.22 is missing. Visiting https://almanac.httparchive.org/static/images/2020/javascript/correlations.png returns an error

**Expected behavior**
There should be an image for "Correlations of JavaScript on various aspects of user experience."

**Screenshots**
![Correlations of JavaScript on various aspects of user experience alt text is shown](https://user-images.githubusercontent.com/8890986/101772684-5bb5bb80-3af4-11eb-90e8-c30a625d7927.png)

**Comment by bazzadp** [comment]
Thanks for reporting! This is fixed in #1724 and we'll be releasing that later today

**Comment by bazzadp** [comment]
Fix was released.
