### ISSUE TITLE
Incorrect Twitter handle for cqueern

### ISSUE THREAD

**Issue by cqueern** [HTTPArchive/almanac.httparchive.org#1742]
**URL**
https://almanac.httparchive.org/en/2020/contributors

**Describe the issue**
The twitter handle on my Contributor tile is  _cqueern_

**Expected behavior**
The twitter handle on my Contributor tile should be  _httpsecheaders_ ( https://twitter.com/httpsecheaders )

Thanks!

**Comment by bazzadp** [comment]
Can you submit a PR to fix this?

For simple one like this you can just do it on GitHub:
- Go to https://github.com/HTTPArchive/almanac.httparchive.org/blob/main/src/config/2020.json
- Click the pencil button to edit it
- Make your edit
- Scroll to bottom and choose the "Create a new branch and start a pull request" option.

**Comment by bazzadp** [comment]
Never mind. @lex111 has done it for you!

**Comment by cqueern** [comment]
Thanks @lex111  @bazzadp !
