### ISSUE TITLE
Issue with the 2020 JavaScript chapter

### ISSUE THREAD

**Issue by developit** [HTTPArchive/almanac.httparchive.org#1771]
**URL**
https://almanac.httparchive.org/en/2020/javascript#frameworks

**Describe the issue**
There are a few references to a "frameworks" graph that doesn't seem to be present:
https://almanac.httparchive.org/en/2020/javascript#:~:text=The%20graph%20below%20shows%20the%20median%20bytes%20for%20pages%20where%20any%20of%20the%20top%2035%20most%20commonly%20detected%20frameworks%20were%20found%2C%20broken%20down%20by%20client.

https://almanac.httparchive.org/en/2020/javascript#:~:text=We%20get%20a%20very%20similar%20picture%20when%20looking%20at%20main%20thread%20time%20for%20pages%20where%20these%20tools%20were%20detected.

**Expected behavior**
These graphs should be embedded:
[main thread time, by framework](https://docs.google.com/spreadsheets/d/1cgXJrFH02SHPKDGD0AelaXAdB3UI7PIb5dlS0dxVtfY/edit#gid=160832134&range=O41)

[Bytes shipped, by framework](https://docs.google.com/spreadsheets/d/1cgXJrFH02SHPKDGD0AelaXAdB3UI7PIb5dlS0dxVtfY/edit#gid=1206934500&range=K2)

**Comment by rviscomi** [comment]
Thanks for filing these. We recently merged edits to resolve this in #1737 (still unreleased).

**Comment by rviscomi** [comment]
Just did a deploy, these changes should be fixed now.

![image](https://user-images.githubusercontent.com/1120896/102299963-f4e43800-3f21-11eb-9889-77484fa96069.png)
