### ISSUE TITLE
Update % of unused script bytes stat in 2020 JavaScript chapter

### ISSUE THREAD

**Issue by rviscomi** [HTTPArchive/almanac.httparchive.org#1783]
Thinking more about the discussion spurred by [this Twitter thread](https://twitter.com/_developit/status/1338984616397508609), the stat about the % of unused script bytes has a couple of flaws:

1. It combines two independent distributions, dividing one median by another. This is probably ok but we can be more precise and directly calculate the % of unused bytes for each page and take the median of that distribution.
2. The numerator (from Lighthouse) is the uncompressed number of bytes while the denominator is the number of (optionally) compressed bytes.
3. IIUC the Lighthouse audit includes inline script blocks in unused code analysis, but we don't measure inline script size.

2 and 3 mean that the reported value is higher than the actual value. We can at least address 1 and 2, so here's an updated query to take them into consideration:

```sql
CREATE TEMPORARY FUNCTION GET_UNCOMPRESSED_JS_BYTES(payload STRING) RETURNS INT64 DETERMINISTIC LANGUAGE js AS '''
try {
  var $ = JSON.parse(payload);
  return $._objectSizeUncompressed || $._objectSize || $._bytesIn || null;
} catch (e) {
  return null;
}
''';

SELECT
  percentile,
  APPROX_QUANTILES(SAFE_DIVIDE(unused_js, total_js), 1000 IGNORE NULLS)[OFFSET(percentile * 10)] AS pct_unused_js
FROM (
  SELECT
    url,
    CAST(JSON_EXTRACT_SCALAR(report, "$.audits.unused-javascript.details.overallSavingsBytes") AS INT64) AS unused_js
  FROM
    `httparchive.lighthouse.2020_08_01_mobile`)
JOIN (
  SELECT
    page AS url,
    SUM(GET_UNCOMPRESSED_JS_BYTES(payload)) AS total_js
  FROM
    `httparchive.almanac.requests`
  WHERE
    date = '2020-08-01' AND
    client = 'mobile' AND
    type = 'script'
  GROUP BY
    page)
USING (url),
  UNNEST([1, 5, 10, 25, 50, 75, 90, 95, 99, 100]) AS percentile
GROUP BY
  percentile
ORDER BY
  percentile
```

percentile | pct_unused_js
-- | --
1 | 0.00%
5 | 0.00%
10 | 1.83%
25 | 8.09%
50 | 12.54%
75 | 17.54%
90 | 26.82%
95 | 38.75%
99 | 63.37%
100 | 2385972.55%

(Also updated the JS chapter [results sheet](https://docs.google.com/spreadsheets/d/1cgXJrFH02SHPKDGD0AelaXAdB3UI7PIb5dlS0dxVtfY/edit#gid=626708926))

The 100th percentile (maximum) shows that something is still off. I think this could be attributed to item 3, inline script blocks.

In any case, I'm more confident in these results, even though they're a bit less sensational: 13% of bytes are unused at the median as opposed to 37%.

cc @developit @brendankenny

**Comment by tkadlec** [comment]
Huh. I can't believe I used compressed and uncompressed bytes together. That's a pretty obvious and silly mistake. :/

When I get back to my computer I'll have a closer look here. That percentage is surprisingly low to me, but I admit that my experience has mostly been with folks who needed perf help so the bias of what I've seen certainly leans towards more extreme cases.

**Comment by tkadlec** [comment]
Quick thought, mostly as a note to myself, but I wonder if some of the gap there between what I expect to see and am seeing has to do with the LH audit versus running code coverage directly?

**Comment by rviscomi** [comment]
No worries @tkadlec! That `bytesJs` refers to transfer size is admittedly poorly documented/named on our end (along with all of the other response size metrics). I often overlook the distinction myself and I think this might be the first time I've even queried `_objectSizeUncompressed`.

I agree the 37% stat did feel intuitively right, and 13% feels low. Especially all the jQuery code out there, surely most of that is unused on the initial page load. Would it be helpful if I pulled out a few example websites that we can spot check together?

@brendankenny @paulirish do you have any insights into how LH does the unused JS audit, specifically:

- does it count uncompressed bytes
- does it look at both 1P and 3P scripts
- does it include inline script blocks and/or external scripts
- how does it compare to the code coverage stats in DevTools

**Comment by tkadlec** [comment]
I just ran a LH audit on a page versus code coverage. LH is indeed reporting transfer size, not uncompressed bytes. So as long as the audit JSON data aligns (and I assume it would) then we were indeed looking at transfer size versus transfer size originally.

**Comment by rviscomi** [comment]
Well that changes things! If that's the case, sorry for the false alarm. I guess LH would be looking at the % of unused code and multiplying that by the transfer size, and not even considering inline script blocks. So the reasoning would be that the amount of unused bytes hurts users in terms of download times, in which case transfer size matters more than compressed size, as opposed to counting the uncompressed bytes' effect on decompression/parse times, which makes sense I guess.

**Comment by developit** [comment]
One reason estimates here might be on the low side is that, if I recall correctly, LH uses a more approximate calculation of unused code (at the block level instead of at the statement level) during loading.
