### ISSUE TITLE
eCommerce query - Sites are counted multiple times due to a technology belonging to multiple categories in Wappalyzer

### ISSUE THREAD

**Issue by rockeynebhwani** [HTTPArchive/almanac.httparchive.org#1810]
This issue is for query - https://github.com/HTTPArchive/almanac.httparchive.org/blob/main/sql/2020/16_Ecommerce/pct_ecommsites_bydevice_compare20192020.sql

As in Wappalyzer, a particular app/technology can belong to multiple categories, it' possible that multiple technologies are listed under a single category for a site and current query results in over counting (In face, as far as I can see this was an issue with 2019 query also)

For example, If I take 2020 part of the query listed above and see output for one such domain (https://direct.asda.com), you can see this happening 

SELECT
  _TABLE_SUFFIX AS client,
   2020 AS year,
   url,
   category,
   app,
  COUNT(0) AS freq,
  total,
  COUNT(0) / total AS pct
FROM
  `httparchive.technologies.2020_08_01_*`
JOIN (
  SELECT
    _TABLE_SUFFIX,
    COUNT(0) AS total
  FROM
    `httparchive.summary_pages.2020_08_01_*`
  GROUP BY
    _TABLE_SUFFIX)
USING
  (_TABLE_SUFFIX)
WHERE
  category = 'Ecommerce'
  and url = 'https://direct.asda.com/'
--    and 
--  app != 'Cart Functionality'
GROUP BY
  client,
  total,
    url,
   category,

![image](https://user-images.githubusercontent.com/1718757/102697868-33833680-4231-11eb-8571-749623cedc51.png)

We need to modify all eCommerce queries to not double count.

Rockey

**Comment by rockeynebhwani** [comment]
If I take query listed in https://github.com/HTTPArchive/almanac.httparchive.org/blob/main/sql/2020/16_Ecommerce/pct_ecommsites_bydevice_compare20192020.sql and add just one domain to it and modify like below - 

SELECT
  _TABLE_SUFFIX AS client,
   2020 AS year,
  COUNT(0) AS freq,
  total,
  COUNT(0) / total AS pct
FROM
  `httparchive.technologies.2020_08_01_*`
JOIN (
  SELECT
    _TABLE_SUFFIX,
    COUNT(0) AS total
  FROM
    `httparchive.summary_pages.2020_08_01_*`
  GROUP BY
    _TABLE_SUFFIX)
USING
  (_TABLE_SUFFIX)
WHERE
  category = 'Ecommerce'
  and url = 'https://direct.asda.com/'
--    and 
--  app != 'Cart Functionality'
GROUP BY
  client,
  total
UNION ALL
SELECT
  _TABLE_SUFFIX AS client,
   2019 AS year,
  COUNT(0) AS freq,
  total,
  COUNT(0) / total AS pct
FROM
  `httparchive.technologies.2019_08_01_*`
JOIN (
  SELECT
    _TABLE_SUFFIX,
    COUNT(0) AS total
  FROM
    `httparchive.summary_pages.2019_08_01_*`
  GROUP BY
    _TABLE_SUFFIX)
USING
  (_TABLE_SUFFIX)
WHERE
  category = 'Ecommerce'
    and url = 'https://direct.asda.com/'
GROUP BY
  client,
  total

Output is - 

![image](https://user-images.githubusercontent.com/1718757/102698034-88737c80-4232-11eb-8ccc-cafd0100a240.png)

In this case, 2019 counts are OK as for this site, in 2019, there was only app/technology listed under Ecommerce category but that changed in 2020 and now this site is counted twice.

**Comment by bazzadp** [comment]
Ok so surely it’s as easy as replacing the inner `COUNT(0)` with `COUNT(DISTINCT url)`?

Can you work with @jrharalson on getting the queries updated?

**Comment by rockeynebhwani** [comment]
@barrypollard  - Thanks for the hint. Still not sure about @jrharalson 's availability so I have attempted to make the change. I believe 2019 query was also wrong but impact of this in 2019 was negligible. For 2020, we enhanced Wappalyzer to deduce eCommerce category by other means so fixing this for 2020 is absolutely necessary.

**Comment by rockeynebhwani** [comment]
@barrypollard  / @rviscomi  - I am not sure where else similar queries for category 'Ecommerce' have been used. Most of them possibly have this issue. 

Example - https://github.com/HTTPArchive/almanac.httparchive.org/blob/main/sql/2020/12_Mobile_Web/ecommerce_with_type_search.sql

I don't see DISTINCT in this. Can you please have a look at this and confirm if we should be modifying these?

**Comment by rviscomi** [comment]
@rockeynebhwani good catch, I agree that query should be deduplicating URLs, for example:

```sql
SELECT
  client,
  COUNT(DISTINCT IF(search_input_stats.has_inputs, url, NULL)) AS sites_with_inputs,

  COUNT(DISTINCT IF(search_input_stats.has_search_inputs, url, NULL)) AS sites_with_search_inputs,
  COUNT(DISTINCT IF(search_input_stats.has_search_inputs, url, NULL)) / COUNT(DISTINCT IF(search_input_stats.has_inputs, url, NULL)) AS perc_sites_with_search_inputs
```

or more simply changing the inner query:

```sql
  SELECT DISTINCT
    _TABLE_SUFFIX AS client,
    url
  FROM
    `httparchive.technologies.2020_08_01_*`
  WHERE
    category = 'Ecommerce'
```

cc @obto 

This applies to all queries that use the `technologies` dataset.

**Comment by bazzadp** [comment]
I ran the following SQL:

```sql
#standardSQL
# 14_01: Top CMSs
SELECT
  _TABLE_SUFFIX AS client,
  category,
  COUNT(distinct app) AS apps,
  COUNT(0) AS freq,
  COUNT(DISTINCT url) AS distinct_freq,
  COUNT(0)/COUNT(DISTINCT url) pct_diff
FROM
  `httparchive.technologies.2020_08_01_*`
GROUP BY
  client,
  category
HAVING
  COUNT(distinct app) > 1
ORDER BY
  pct_diff desc,
  client
```

Which produces the following results:


client | category | apps | freq | distinct_freq | pct_diff
-- | -- | -- | -- | -- | --
desktop | JavaScript libraries | 101 | 11673164 | 4965314 | 235%
mobile | JavaScript libraries | 98 | 12730711 | 5532177 | 230%
mobile | Payment processors | 15 | 369114 | 182194 | 203%
desktop | Payment processors | 14 | 341495 | 173474 | 197%
desktop | Ecommerce | 151 | 1811109 | 1214752 | 149%
mobile | Ecommerce | 153 | 2004678 | 1350161 | 148%
mobile | Font scripts | 30 | 5110689 | 3608255 | 142%
desktop | Font scripts | 31 | 4596721 | 3248153 | 142%
desktop | Advertising | 43 | 1127360 | 819117 | 138%
desktop | Analytics | 93 | 5652550 | 4152303 | 136%
mobile | Analytics | 92 | 6064493 | 4518961 | 134%
mobile | Advertising | 40 | 1334919 | 1014245 | 132%
desktop | Miscellaneous | 48 | 2870692 | 2183063 | 131%
mobile | Miscellaneous | 44 | 3109151 | 2402832 | 129%
mobile | JavaScript frameworks | 59 | 1665832 | 1290290 | 129%
desktop | Widgets | 34 | 2871212 | 2238329 | 128%
mobile | Widgets | 34 | 3131331 | 2475963 | 126%
desktop | JavaScript frameworks | 58 | 1508517 | 1195777 | 126%
desktop | Web server extensions | 16 | 240827 | 197696 | 122%
mobile | Web server extensions | 16 | 243981 | 201289 | 121%
mobile | UI frameworks | 24 | 2444667 | 2106385 | 116%
desktop | UI frameworks | 21 | 2226130 | 1922130 | 116%
desktop | Video players | 12 | 795210 | 727428 | 109%
mobile | Video players | 12 | 820953 | 751178 | 109%
desktop | PaaS | 22 | 424667 | 391417 | 108%
mobile | Programming languages | 17 | 4012884 | 3711317 | 108%
mobile | PaaS | 22 | 396585 | 366973 | 108%
desktop | JavaScript graphics | 37 | 230768 | 214540 | 108%
mobile | JavaScript graphics | 36 | 217582 | 203669 | 107%
desktop | CDN | 24 | 1125952 | 1062747 | 106%
mobile | CDN | 24 | 1189387 | 1126439 | 106%
desktop | Web servers | 74 | 4636848 | 4398869 | 105%
desktop | Programming languages | 19 | 3405668 | 3232549 | 105%
mobile | Web servers | 74 | 5331737 | 5071921 | 105%
desktop | Marketing automation | 24 | 240773 | 234770 | 103%
mobile | Marketing automation | 24 | 221608 | 216385 | 102%
desktop | Caching | 16 | 578395 | 566106 | 102%
desktop | Maps | 7 | 334312 | 327406 | 102%
mobile | Caching | 16 | 622158 | 609492 | 102%
desktop | Tag managers | 10 | 2241982 | 2198436 | 102%
mobile | Maps | 7 | 332482 | 326237 | 102%
mobile | Tag managers | 10 | 2409628 | 2365214 | 102%
mobile | Web frameworks | 59 | 639440 | 628061 | 102%
desktop | Cookie compliance | 18 | 246494 | 242944 | 101%
mobile | Cookie compliance | 18 | 258121 | 254462 | 101%
desktop | Static site generator | 12 | 16259 | 16032 | 101%
desktop | Development | 18 | 4150 | 4098 | 101%
desktop | Web frameworks | 62 | 649643 | 641569 | 101%
mobile | Static site generator | 11 | 11913 | 11796 | 101%
mobile | Cryptominers | 9 | 507 | 503 | 101%
desktop | Databases | 13 | 1956732 | 1941449 | 101%
mobile | Editors | 15 | 114928 | 114086 | 101%
desktop | Editors | 15 | 114194 | 113421 | 101%
mobile | Databases | 13 | 2216593 | 2201829 | 101%
mobile | Development | 16 | 3769 | 3744 | 101%
desktop | Rich text editors | 6 | 54219 | 53878 | 101%
desktop | Cryptominers | 8 | 348 | 346 | 101%
mobile | Accessibility | 12 | 39164 | 38991 | 100%
desktop | Accessibility | 12 | 40572 | 40403 | 100%
desktop | Security | 9 | 526863 | 524760 | 100%
mobile | Rich text editors | 6 | 47496 | 47317 | 100%
mobile | Security | 8 | 547413 | 545434 | 100%
desktop | Live chat | 14 | 157910 | 157353 | 100%
mobile | Live chat | 14 | 163932 | 163376 | 100%
mobile | Mobile frameworks | 14 | 84373 | 84121 | 100%
mobile | CMS | 216 | 2677849 | 2671027 | 100%
mobile | SEO | 4 | 812255 | 810307 | 100%
desktop | CMS | 219 | 2364381 | 2359208 | 100%
desktop | SEO | 4 | 724153 | 722639 | 100%
desktop | Mobile frameworks | 12 | 56143 | 56031 | 100%
desktop | Webmail | 6 | 2063 | 2059 | 100%
desktop | Issue trackers | 19 | 213844 | 213431 | 100%
desktop | Reverse proxies | 5 | 1691338 | 1688097 | 100%
desktop | Page builders | 6 | 153552 | 153267 | 100%
mobile | Reverse proxies | 5 | 1953149 | 1949711 | 100%
desktop | Operating systems | 17 | 965106 | 963678 | 100%
mobile | Operating systems | 17 | 980290 | 978862 | 100%
mobile | Page builders | 6 | 172307 | 172064 | 100%
mobile | Issue trackers | 19 | 222973 | 222745 | 100%
desktop | Documentation tools | 11 | 4137 | 4134 | 100%
desktop | Message boards | 22 | 33160 | 33138 | 100%
mobile | Search engines | 8 | 13500 | 13493 | 100%
desktop | Search engines | 8 | 14146 | 14139 | 100%
desktop | Blogs | 39 | 1932060 | 1931364 | 100%
mobile | Blogs | 35 | 2316086 | 2315323 | 100%
desktop | Comment systems | 4 | 33879 | 33872 | 100%
mobile | Comment systems | 4 | 35459 | 35453 | 100%
mobile | Message boards | 22 | 29713 | 29710 | 100%
desktop | Wikis | 13 | 21390 | 21388 | 100%
mobile | LMS | 3 | 12203 | 12202 | 100%
desktop | LMS | 3 | 13144 | 13143 | 100%
desktop | Hosting panels | 9 | 232867 | 232852 | 100%
mobile | Hosting panels | 8 | 271131 | 271116 | 100%
desktop | Photo galleries | 7 | 36602 | 36602 | 100%
desktop | CRM | 5 | 2071 | 2071 | 100%
desktop | DMS | 4 | 3789 | 3789 | 100%
desktop | User Onboarding | 2 | 261 | 261 | 100%
desktop | Database managers | 2 | 525 | 525 | 100%
desktop | SaaS | 2 | 11 | 11 | 100%
mobile | Photo galleries | 6 | 43135 | 43135 | 100%
mobile | Wikis | 13 | 7520 | 7520 | 100%
mobile | Webmail | 6 | 2043 | 2043 | 100%
mobile | Documentation tools | 11 | 2348 | 2348 | 100%
mobile | DMS | 4 | 3127 | 3127 | 100%
mobile | CRM | 5 | 1346 | 1346 | 100%
mobile | User Onboarding | 2 | 236 | 236 | 100%
mobile | Database managers | 2 | 524 | 524 | 100%
mobile | SaaS | 2 | 10 | 10 | 100%

The biggest differences are therefore:
- JavaScript libraries and Frameworks - but the JavaScript chapter which is the only one using this, [already did the correct queries](https://github.com/HTTPArchive/almanac.httparchive.org/blob/main/sql/2020/javascript/frameworks_libraries.sql).
- Analytics, Payment processors and Ecommerce - already taken care of by you spotting this @rockeynebhwani 

The rest were small percentages.

So think we can live with this, for this year, but we should ensure next years queries handle this properly.

Closing this for now.
