### ISSUE TITLE
All charts loading on intial load in Firefox in 2020 almanac

### ISSUE THREAD

**Issue by lannonbr** [HTTPArchive/almanac.httparchive.org#1822]
**URL**

Any chapter that uses the charts generated from Google Docs data. Listing the CSS page as an example.

https://almanac.httparchive.org/en/2020/css

**Describe the issue**

Loading the site in Firefox does not load in the graphs lazily, but rather all on the initial load. This results in the site loading all the content in (tested on a 2017 MacBook Pro with a 500Mbps internet connection) in about 1-2 minutes.

Loading this site in Chrome only loads the main HTML and a few of the first graphs on the top of the page.

**Expected behavior**

Firefox should load the content for the page as you scroll down it rather than all at once (like how Chrome does).

**Screenshots**

I loaded the site in both Firefox and Chrome without any scrolling down the page in either browser. Chrome only loads content fairly high up on the page (37 http requests) while Firefox ends up loading what looks like the entire contents of the page (~200 http requests).

![Firefox Screenshot. Loads in 1.4 minutes with 200 requests](https://user-images.githubusercontent.com/3685876/102788158-32a4ee80-4370-11eb-8904-df1c555d5b6f.png)

![Chrome Screenshot. Loads in ~1.13 seconds with 37 requests](https://user-images.githubusercontent.com/3685876/102788153-30db2b00-4370-11eb-8755-c3e625f85715.png)

**Comment by bazzadp** [comment]
Firefox does not yet support [lazy-loading of iFrames](https://bugzilla.mozilla.org/show_bug.cgi?id=1622090) so that is why this happens.

If you are on a low-bandwidth connection, or have data saving enabled we will not use iframes and use images and they will only be lazy-loaded as that is supported by firefox.

So this is working as intended.
