### ISSUE TITLE
Wappalyzer technology table doesn't have correct data in case of re-directed domains

### ISSUE THREAD

**Issue by rockeynebhwani** [HTTPArchive/almanac.httparchive.org#1854]
While analysing some stats, I am noticing that when three is a re-direction on domain, Wapp technology table doesn't have the correct data. I will try to explain the issue with example of eCommerce platform but I think issue is valid for all technologies. 

Example - Take domain https://www.radsone.com/. At the time of creating this issue, this domain re-directs to https://earstudio.store/. Before re-direct you see a different site which I believe is build on 'Wix' and re-directed site is using 'Shopify' as eCommerce platform. 

Now if you following query

```
SELECT *
FROM
  `httparchive.technologies.2020_10_01_mobile`
  where (url = 'https://www.radsone.com/')
  and category = 'Ecommerce'
  and app <> 'Cart Functionality'
```
Query output is 

![image](https://user-images.githubusercontent.com/1718757/103254027-a2703600-497b-11eb-99be-4191926b533e.png)

Domain https://www.radsone.com/ is not on Shopify but Wapp technology table records the eCommerce platform of 're-directed domain' also on the domain which is re-directing. 

My guess is that this site moved from 'Wix' to 'Shopify' and has a poor re-direct implementation. https://www.radsone.com/  has CRUX data from Jan-2020 till Nov-2020 (I didn't check 2019). https://earstudio.store/ has CRUX data only from Apr-2020 onwards. This possibly suggests that this transition happened around Apr-2020. 

This is also visible from this query

```
SELECT LEFT(_TABLE_SUFFIX,2) as month,
SUBSTR(_TABLE_SUFFIX,7,6) as client,
url,
app
FROM
  `httparchive.technologies.2020_*` a
  where (url = 'https://www.radsone.com/' OR url = 'https://earstudio.store/')  AND
  category = 'Ecommerce' and
  SUBSTR(_TABLE_SUFFIX,7,6) = 'mobile' and
  app <> 'Cart Functionality'
order by month asc  
```

month | client | url | app
-- | -- | -- | --
1 | mobile | https://www.radsone.com/ | Wix
2 | mobile | https://www.radsone.com/ | Wix
3 | mobile | https://www.radsone.com/ | Wix
4 | mobile | https://www.radsone.com/ | Wix
4 | mobile | https://www.radsone.com/ | Shopify
5 | mobile | https://www.radsone.com/ | Wix
5 | mobile | https://www.radsone.com/ | Shopify
6 | mobile | https://earstudio.store/ | Shopify
6 | mobile | https://www.radsone.com/ | Shopify
6 | mobile | https://www.radsone.com/ | Wix
7 | mobile | https://www.radsone.com/ | Wix
7 | mobile | https://www.radsone.com/ | Shopify
7 | mobile | https://earstudio.store/ | Shopify
8 | mobile | https://www.radsone.com/ | Wix
8 | mobile | https://earstudio.store/ | Shopify
8 | mobile | https://www.radsone.com/ | Shopify
9 | mobile | https://earstudio.store/ | Shopify
9 | mobile | https://www.radsone.com/ | Wix
9 | mobile | https://www.radsone.com/ | Shopify
10 | mobile | https://www.radsone.com/ | Shopify
10 | mobile | https://www.radsone.com/ | Wix
10 | mobile | https://earstudio.store/ | Shopify

This results in wrong data in various queries. At this stage, I don't know how big is this issue and what % of domains have re-direct. Raising this issue to add more examples and comments and may be try to correct queries somehow for 2021

**Comment by bazzadp** [comment]
Yes this is a JavaScript redirect rather than a proper server 301/302. To me this site therefore **does** use Wix and Shopify (though understand why you wouldn't to see it as Wix).

I say this is working as intended and is as you say "has a poor re-direct implementation". If they used a proper 301/302 and this was still happening this would be a bigger issue - but that shouldn't happen as with a 301/302 the original site wouldn't be loaded and so Wix wouldn't be detected.

**Comment by rockeynebhwani** [comment]
ok.. this site is really weird where it has implemented a really bad re-direct... As we discussed on our chat, I will take a different example and may be @rviscomi can weigh it. In previous example, we have instance of two different eCommerce platforms being attributed to a single business (however on two different domains). I think that's OK considering poor re-direct implementation. 

But in below example, we have proper 301 re-direct but technology table double counts all technologies...

Domains in question - 

1. http://www.ellos.com/
2. http://www.ellos.us/
3. https://www.ellos.us/

Aug-2020 crawl link is - https://webpagetest.httparchive.org/result/200803_Dx3B_6HJR/1/details/#waterfall_view_step1

It has chain of re-directs

![image](https://user-images.githubusercontent.com/1718757/103313149-101d7000-4a17-11eb-9074-42caa2df306e.png)

1st and 3rd domain in this chain in Wapp technologies table

```
select distinct url
    FROM `httparchive.technologies.2020_08_01_mobile`
    WHERE 
      url = 'https://www.ellos.us/' OR url = 'http://www.ellos.com/' OR url = 'http://www.ellos.us/'
```
There is no CRUX data for origin www.ellos.com in 2020. I see CRUX data for www.ellos.us in 2020. 

So, I guess the question here is 
- Why our crawl is starting from origin http://www.ellos.com/ and not from www.ellos.us (with or without HTTPS)? 
- Why do we have multiple entries in Wapp tech table? if seems all technologies for domain https://www.ellos.us are also getting attributed for domain http://www.ellos.com. This will result in over counting.

@barrypollard - Is there a way for you to see how many origins first request has 301 re-directs? This should give us extent of over counting (I think)

**Comment by bazzadp** [comment]
Need @rviscomi to answer the first question.

For the second question I think it makes sense. I suspect all technologies used by the page load (whether by redirect or by loading dependencies) filter back up to the original request domain to make it easy to see what that page load uses. Suspect that’s just the way WebPageTest works (@pmeenan cam you confirm?). In same way that if Google Analytics is identified by the contents of the GA script tag (I don’t know if it is btw, but go with me here) then it should also be attributed to the original page loaded - and not just www.google-analytics.com. As discussed on chat I think you should join to the `pages` table to avoid double counting rather than just sum up the `technologies` table and assume it’s only got one entry per page. @rviscomi can you confirm if this is the way the technologies table should be used?

Btw  my primary GitHub account is @bazzadp so can you use that? @barrypollard is a test account is set up that’s link to my work email, so every time you tag that I get emails there too for that message and every reply to the thread! 😀 I really should just delete that account but useful for a few things.

**Comment by rockeynebhwani** [comment]
@bazzadp  - Both these domains (http://www.ellos.com/  and https://www.ellos.us) are in pages table also. so, it won't stop double counting. I will wait for @rviscomi  to come back on 1st question as it's important to understand why http://www.ellos.com/  is part of crawl at all.

**Comment by pmeenan** [comment]
AFAIK, the CrUX urls list should be post-redirect.  Maybe the domain switched on HTTPS redirects during the CrUX reporting period or serve some pages from both.

They are different origins.  If they did migrate to always redirect then the non-https URL will stop showing up in the CrUX dataset.

WebPageTest will always allocate the results to the URL that was used to start the navigation.

**Comment by rockeynebhwani** [comment]
@pmeenan  - http://www.ellos.com is a landing page of eCommerce sites in various countries... From US, it auto-directs to https://www.ellos.us and from UK, user it stays on http://www.ellos.com So both domains seem to serve traffic.

I also now need to correct myself when I said http://www.ellos.com doesn't have CRUX data, that's not correct. I was using @rviscomi chrome search shortcut and didn't enter protocol and by default it assumes https (I think)

https://datastudio.google.com/u/0/reporting/bbc5698d-57bb-4969-9e07-68810b9fa348/page/keDQB?params=%7B%22origin%22:%22www.ellos.com%22%7D

when I correct this  to include protocol, I see the data 

https://datastudio.google.com/u/0/reporting/bbc5698d-57bb-4969-9e07-68810b9fa348/page/keDQB?params=%7B%22origin%22:%22http:%2F%2Fwww.ellos.com%22%7D

My bad.. I should have queried the `chrome-ux-report.materialized.metrics_summary` table... 

In this case, it makes sense for both domains to be CRUX DB and two entries in pages and Wapp technologies table... 

I am going to close this issue if I don't find any other examples.. but let's keep this open for couple more days.

**Comment by rockeynebhwani** [comment]
Having said the above, I think attributing technologies from final re-directed domain to domain which is initiating re-directs is still problematic in this case. http://www.ellos.com is a landing page with only jQuery being detected by Wappalyzer but it still gets all technologies from https://www.ellos.us attributed to it.

**Comment by bazzadp** [comment]
> Having said the above, I think attributing technologies from final re-directed domain to domain which is initiating re-directs is still problematic in this case. http://www.ellos.com is a landing page with only jQuery being detected by Wappalyzer but it still gets all technologies from https://www.ellos.us attributed to it.

That's understandable as are crawl runs from [US only](https://almanac.httparchive.org/en/2019/methodology#webpagetest). Therefore, as CrUX logs both domains, both are included in our crawl but, because the crawl is US-based, both end up loading the same site and, as per @pmeenan 's [comment](https://github.com/HTTPArchive/almanac.httparchive.org/issues/1854#issuecomment-752264932), both domains get the full results of the US domain.

So I still say its working as intended, within the limitations of our crawl methodology.

**Comment by rviscomi** [comment]
I agree that this does seem WAI. The URLs that we test are the home pages of origins in the global CrUX dataset. We could use the US-specific CrUX dataset; that would help avoid geo-based redirect issues like this, but it'd also cause us to lose a significant amount of coverage and also introduce pro-US bias. Unfortunately given that our test agents are located in the US, there's not a lot we can do to work around this issue.

If this were a big enough issue, it should be possible to deduplicate URLs that resolve to other URLs in the dataset by looking at the final base page URL in the redirect chain. But I think it's more effort than it's worth and I hope it's not considered a blocker for the Ecommerce chapter.

**Comment by pmeenan** [comment]
The page data should also have a _document_url field that is the URL of the document at the end of the test.  That could be used for the technology attribution instead if it is a concern (or for detecting duplicates).
