### ISSUE TITLE
Spelling in the 2020 PWA chapter

### ISSUE THREAD

**Issue by kuhlaid** [HTTPArchive/almanac.httparchive.org#1862]
**URL**
https://almanac.httparchive.org/en/2020/pwa

**Describe the issue**
Believe the author meant to use 'rely' instead of 'relay' in:
"they decided to code themselves or relay on libraries like Workbox"

**Expected behavior**
"they decided to code themselves or rely on libraries like Workbox"

**Comment by bazzadp** [comment]
Thanks for reporting. Fixed this, and a few other things I spotted, in #1863 which will be included in next release.

Please note this chapter has not been edited yet so may be other typos in there still.
