### ISSUE TITLE
colon in the bio blurb results in empty bio

### ISSUE THREAD

**Issue by dtikhonov** [HTTPArchive/almanac.httparchive.org#1865]
A colon in an author's bio trips up processing.  For example,

```
authorsname_bio: Some: bio
```

Will result in `authorname`'s bio being empty.

**Comment by bazzadp** [comment]
Fixed in #1866 but you need to use HTML entity as this is YAML (or a subset of it to be completely accruate):

```
authorsname_bio: Some&colon; bio
```

Unfortunately quotes won't work so has to be HTML entity but think that's enough.
