### ISSUE TITLE
2020 Compression: request instead of response

### ISSUE THREAD

**Issue by dtikhonov** [HTTPArchive/almanac.httparchive.org#1910]
**URL**
https://almanac.httparchive.org/en/2020/compression#what-type-of-content-should-we-compress

**Describe the issue**
The use of the word "request" instead of "response" is inexact.  Examples:
> The figure shows the percent of requests of a certain content type using either Brotli [...]

and

> [...] the percent of image requests that employ either Brotli [...]

**Expected behavior**
Certainly, it is the _response_ that is compressed.

**Comment by bazzadp** [comment]
Fair point. In HTTP Archive parlance it's measured in the `requests` table but yes it's still the response that is compressed. Fixed in #1911 along with a number of other edits.
