### ISSUE TITLE
Remove "people" from contributors section on Home

### ISSUE THREAD

**Issue by MSakamaki** [HTTPArchive/almanac.httparchive.org#195]
https://github.com/HTTPArchive/almanac.httparchive.org/issues/106#issuecomment-540472949  issues.

**Comment by rviscomi** [comment]
@MSakamaki just to confirm, you'll be working on this issue? Should we assign it to you?

**Comment by MSakamaki** [comment]
@rviscomi 
Sorry I now working on 154.
Once that is complete, I can start.
