### ISSUE TITLE
Suggestions for the 2021 Web Almanac

### ISSUE THREAD

**Issue by bazzadp** [HTTPArchive/almanac.httparchive.org#1954]
Place holder for now for people to make some early suggestions for the 2021 Web Almanac
- Who would you like to see write on each topic for the next edition?
- What new subjects should we cover? We added three this year (Capabilities, Jamstack, and Privacy)
- What things could we improve next year?

Feel free to start adding comments below. Normally we don't kick off until later in the year but it always seems like such a rush so think no harm to start thinking about it now.

Also, if you're interested in being involved then please do [register your interest](https://forms.gle/M4MxvGRvsEtBcBwr7) so we can reach out to you when it kicks off later in the year.

**Comment by axelboc** [comment]
I'd love to know the proportion of **explicit vs. implicit labelling of form elements**.

The presence of the `for` attribute on `label` elements would be a good first indicator. However, to go further, the query could check:

- whether both explicit and implicit labelling are used together,
- whether the IDs referenced in the `for` attributes actually exist,
- what kind of [labelable form elements](https://developer.mozilla.org/en-US/docs/Web/Guide/HTML/Content_categories#Form_labelable) are more likely to be explicitly vs implicitly labelled (e.g. perhaps checkbox and radio buttons are more likely to be implicitly labelled for styling purposes?)

<details>
<summary>Explicit vs. implicit labelling vs. both</summary>

### Explicit

```html
<label for="my-id">My label</label>
<input id="my-id">
```

### Implicit
```html
<label>
  My label
  <input>
</label>
```

### Both
```html
<label for="my-id">
  My label
  <input id="my-id">
</label>
```
</details>

**Comment by bazzadp** [comment]
Sounds like potentially one for the Markup chapter to consider!

We did do some analysis on label usage in the Accessibility chapter (based on the Lighthouse audits): https://almanac.httparchive.org/en/2020/accessibility#form-labels
But that didn't differentiate between the two types.

**Comment by rviscomi** [comment]
@bazzadp are you ok closing this and moving suggestions into the specific [chapter issues](https://github.com/HTTPArchive/almanac.httparchive.org/issues?q=is%3Aissue+is%3Aopen+label%3A%222021+chapter%22) or general suggestions to #2167?
