### ISSUE TITLE
Issue with the 2020 [css] chapter

### ISSUE THREAD

**Issue by noah-vdv** [HTTPArchive/almanac.httparchive.org#1960]
[Masks heading](https://almanac.httparchive.org/en/2020/css#masks)

On pc, figure 1.42 at the link above isn't showing, it says "no data". But on mobile it does show the correct image.
Also if I inspect the site and I choose the iphone x for example, it does show the image but once I change it to the ipad pro it says again "no data".

This is the phone version

![mobile-version (Phone)](https://user-images.githubusercontent.com/46689362/106518441-30d75a80-64da-11eb-9ab1-a584acc50766.jpg)

This is the pc version

![pc-version (Phone)](https://user-images.githubusercontent.com/46689362/106518590-6bd98e00-64da-11eb-8ea5-12b75c1fcb7a.png)

Also this is the pc version on mobile

![pc-version-on-mobile (Phone)](https://user-images.githubusercontent.com/46689362/106518671-8875c600-64da-11eb-8b71-164f5e4f46c3.jpg)

I have no idea if this is some kind of glitch on my part but it kept happening so I thought I'd mention it.

**Comment by noah-vdv** [comment]
Oh yeah and if I click "view image" and I then go back to the site it shows the image but once I refresh the page it's back to "no data"

**Comment by bazzadp** [comment]
Thanks for raising - this has been fixed.

The desktop view loads the charts live from the Google Sheets data, this allows you to hover over the data to get more information, but does mean if you edit the data, then it's reflected in the dataset.

The mobile view is a static screenshot PNG image, which is easier to load on constrained mobile devices, and you can't benefit from hover anyway.

@LeaVerou it looks like, from the history, that you edited the sheet 10 days ago so not sure if you broke something here? I've restored the sheet to the previous version before your edits and that seemed to sort it. Need to be careful with this. We could remove all editors access after publication to avoid this but sometimes the content team does want to make corrections to the data even after publish. Anyway something to be aware of.

BTW, on a related point, I have questioned whether the limited hover effect [is worth the performance impact of using live sheets](https://github.com/HTTPArchive/almanac.httparchive.org/issues/826). The CSS chapter as an extreme example is **over 105Mb** of resources on desktop as each of the 59 Sheets embed reloads the same 1.5MB of JavaScript for each embed (luckily cached so no download penalty, but as they are in separate iframes there is a memory impact), compared to 2.9MB on mobile.
