### ISSUE TITLE
Translations: support number-driven declension

### ISSUE THREAD

**Issue by dtikhonov** [HTTPArchive/almanac.httparchive.org#1968]
While reviewing PR #1962, I saw the following in the Russian translation:

```
состоит из {{ supported_chapters | length }} глав
```

The word глав (chapter) would take a different ending if the number preceding it ended in 1 (but not 11).

This is unlikely to be the only instance where we need to decline the noun differently depending on the number and this issue would affect Ukrainian, too.  (As well as probably all other Slavic languages were we to have translations for them.)

**Comment by bazzadp** [comment]
Can you provide the different words for chapters and when they should be used?

Think it will also people (124 people), on the home page and contributors (124 contributors), on the contributors page so if you could provide those three words as well that would be good too, and can then add logic to handle this.

I think that’s most of them as rest should be in the translations and not auto generated based off a variable. Let’s start with those anyway and address any more that crop up after that.

**Comment by dtikhonov** [comment]
OK, will do.

I keep on thinking that we are not the first ones to have come across this issue.  There have to be some system to follow when doing translations like that.

**Comment by bazzadp** [comment]
I’m finding the Jinja2 templating system we use quite powerful for things like this (first time I’ve used it!). So should be easy enough to fix.

Am sure we’re not the first to be hit with this, but at same time can’t think of any magic way to solve it an adding a library or other such dependency for such a simple thing probably isn’t the right answer either.

**Comment by bazzadp** [comment]
Then again maybe something like this is worth pulling in, if this is especially complex ( which it appears to be from their code!): https://github.com/andrewp-as-is/plural-ru.py

What do you think?

**Comment by dtikhonov** [comment]
Yeah, this could work, it's simple enough.

**Comment by dtikhonov** [comment]
I'd have to look some more to see whether the same rules apply in genitive case, it's been a few decades since I dealt with Russian cases and numbers and so on.  ...And that module does not handle 1.5. :slightly_smiling_face:
