### ISSUE TITLE
Assign subject matter experts and peer reviewers to each chapter

### ISSUE THREAD

**Issue by rviscomi** [HTTPArchive/almanac.httparchive.org#2]
Part | Chapter | Authors | Reviewers | Tracking Issue
-- | -- | -- | -- | --
I. Page Content | 1. JavaScript | @addyosmani @housseindjirdeh @mathiasbynens | @rwaldron @RReverser | #3
I. Page Content | 2. CSS | @una @argyleink | _(none)_ | #4
I. Page Content | 3. Markup | @bkardell | @zcorpan | #5
I. Page Content | 4. Media | @dougsillars @colinbendell @Yonet | @ahmadawais @kornelski | #6
I. Page Content | 5. Third Parties | @patrickhulce | @simonhearne @flowlabs @jasti @zeman | #8
I. Page Content | 6. Fonts | @davelab6 @zachleat | @hyperpress | #7
II. User Experience | 7. Performance | @rviscomi @zeman | @JMPerez @obto | #9
II. User Experience | 8. Security | @arturjanc @ScottHelme | @paulcalvano @bazzadp @ghedo | #10
II. User Experience | 9. Accessibility | Nektarios Paisios, @nadinarama, @obto | @rachellcostello, @Abigail Klein | #11
II. User Experience | 10. SEO | @rachellcostello @ymschaap @AVGP | @clarkeclark @andylimn @voltek62 | #12
II. User Experience | 11. PWA | @tomayac @jeffposnick | @hyperpress | #13
II. User Experience | 12. Mobile web | @slightlyoff @obto | @hyperpress | #14
III. Content Publishing | 13. Ecommerce | @samdutton @alankent | @voltek62 | #15
III. Content Publishing | 14. CMS | @amedina | @westonruter @mor10 @sirjonathan | #16
IV. Content Distribution | 15. Compression | @paulcalvano | @yoavweiss @colinbendell | #17
IV. Content Distribution | 16. Caching | @paulcalvano | @yoavweiss @colinbendell | #18
IV. Content Distribution | 17. CDN | @andydavies @colinbendell | @yoavweiss @paulcalvano @pmeenan | #19
IV. Content Distribution | 18. Page Weight | @khempenius @henrisGH | @paulcalvano @flowlabs | #20
IV. Content Distribution | 19. Resource Hints | @khempenius @yoavweiss | @andydavies @addyosmani | #21
IV. Content Distribution | 20. HTTP/2 | @bazzadp | @bagder @rmarx @dotjs | #22

[Reference sheet](https://docs.google.com/spreadsheets/d/1LR29JpI2XJSjan_z6uP1YpRy4EYYivYZPqCIG-9sfFY/edit?usp=sharing)

For more context about the Almanac project and how you can help, see [this post](https://discuss.httparchive.org/t/planning-the-web-almanac-2019/1553).

**Comment by Yonet** [comment]
Should we add WebXR to the content topics? I am happy to help.

**Comment by rviscomi** [comment]
Good idea! Yeah this could fit in with the Media chapter. Are you interested in writing or reviewing?

**Comment by Yonet** [comment]
@rviscomi I am happy to help as author or reviewer.

**Comment by obto** [comment]
I'd love to help author and/or review 9 and 12 as well. Just let me know :smiley:

**Comment by rviscomi** [comment]
Thanks @obto! Do you have a preference for author/reviewer for either chapter?

**Comment by obto** [comment]
I'd like to help author both if possible

**Comment by rviscomi** [comment]
Great, just added you!

**Comment by flowlabs** [comment]
@rviscomi Happy to peer review 1 or 2 from this list if you need any support?

5. Third Parties
7. Performance
15. Compression
16. Caching
17. CDN
18. Page Weight

**Comment by rviscomi** [comment]
@flowlabs that would be great! The ones most in need of reviewers are Third Parties and Page Weight. I'll put you down for those. Thanks!

**Comment by flowlabs** [comment]
@rviscomi Cool! Looking forward to helping :)

**Comment by AymenLoukil** [comment]
Hello @rviscomi i had already expressed my interest to contribute but i was in a rush period. Is that stills possible ? Please tell me on which part(s) could i help ? Thanks !

**Comment by rviscomi** [comment]
👋 Hi @AymenLoukil, it'd be great to have your help! We could use additional reviewers on the [Markup](https://github.com/HTTPArchive/almanac.httparchive.org/issues/5), [Fonts](https://github.com/HTTPArchive/almanac.httparchive.org/issues/7), [PWA](https://github.com/HTTPArchive/almanac.httparchive.org/issues/13), and [Mobile Web](https://github.com/HTTPArchive/almanac.httparchive.org/issues/14) chapters. Do any of these sound like a good fit for you?

**Comment by AymenLoukil** [comment]
Hi @rviscomi :) Great ! I could review #7 Fonts and #14 Mobile

**Comment by rviscomi** [comment]
Thanks @AymenLoukil! I've assigned you as a reviewer for those chapters and sent you an invitation to the Reviewers team. You can accept it via email or visit [https://github.com/HTTPArchive](https://github.com/HTTPArchive).

We're currently in the data analysis phase, so there won't be much work for you to do until ~August. You can learn more about our [timeline here](https://docs.google.com/spreadsheets/d/1LR29JpI2XJSjan_z6uP1YpRy4EYYivYZPqCIG-9sfFY/edit?usp=sharing). Meanwhile you can look over the list of metrics that have been agreed on for those chapters to become familiar with their contents. Let us know if anything is glaringly missing/wrong.

**Comment by AymenLoukil** [comment]
Super @rviscomi ! Thanks.
