### ISSUE TITLE
Web Stories Image warning

### ISSUE THREAD

**Issue by bazzadp** [HTTPArchive/almanac.httparchive.org#2002]
We're seeing the following warning in Google Search Console:

> AMP -> Image size smaller than recommended size

It is only affecting this page: https://almanac.httparchive.org/en/2020/stories/content-publishing

We are not seeing the same alert any of the other three stories ([page-content](https://almanac.httparchive.org/en/2020/stories/page-content), [user-experience](https://almanac.httparchive.org/en/2020/stories/page-content) or [content distribution](https://almanac.httparchive.org/en/2020/stories/content-distribution)) despite the fact that all 4 stories use almost identical meta data.

There is no more detail of which image is too small, and all 4 stories used to be fine from 20th Jan - 28th Jan, after which this one story started alerting:

![Google Search Console screenshot of valid AMP pages](https://user-images.githubusercontent.com/10931297/107950487-ab01e780-6f8e-11eb-8057-f1ea468b3df1.png)

I've tried various fixes to address this since it popped up:
- #1957 - extend height of stories meta data from 1200 x 600 to 1200 x 675 to meet [the 800,000 recommended minimum pixel size](https://developers.google.com/search/docs/data-types/article#amp)
- #1983 - correct the og height data (incorrectly left at 600) and change the publisher logo
- #1985 - Add correctly sized `poster-landscape-src` images 
- #1997 - Add 2 other image variants (1200 x 900 and 1200 x 1200) - to have [16x9, 4x3, and 1x1 versions as recommended](https://developers.google.com/search/docs/data-types/article#amp), and also make them fully qualified URLs, and add height and width attributes.

Here's the exact message:

![Google Search Console screenshot of valid AMP pages of 1 invalid AMP page](https://user-images.githubusercontent.com/10931297/107951729-adfdd780-6f90-11eb-9cf7-a6581bbbf498.png)

![Google Search Console screenshot of valid AMP pages with URL affected](https://user-images.githubusercontent.com/10931297/107951758-b9e99980-6f90-11eb-8ebc-9e665372f5e0.png)

The structured data now looks like this:

```json
    {
      "@context": "http://schema.org",
      "publisher": {
        "@type": "Organization",
        "name": "HTTP Archive",
        "logo": {
          "@type": "ImageObject",
          "url": "https://almanac.httparchive.org/static/images/ha-60px.png",
          "width": 120,
          "height": 60
        },
        "sameas": [
          "https://httparchive.org",
          "https://twitter.com/HTTPArchive",
          "https://github.com/HTTPArchive"
          ]
      },
      "@type": "Article",
      "mainEntityOfPage": "https://almanac.httparchive.org/en/2020/stories/content-publishing",
      "headline": "Web Almanac 2020 Part III: Content Publishing",
      "datePublished": "2021-01-13T00:00:00.000Z",
      "dateModified": "2021-02-14T00:00:00.000Z",
      "author": {
        "@type": "Person",
        "sameas": [
          "https://almanac.httparchive.org/en/2020/contributors#rviscomi",
          "https://twitter.com/rick_viscomi",
          "https://github.com/rviscomi"
        ],
        "name": "Rick Viscomi"
      },
      "image": [
        {
          "@type":"ImageObject",
          "url":"https://almanac.httparchive.org/static/images/home-hero-2020-part-3.png",
          "width": 1200,
          "height": 675
        },
        {
          "@type":"ImageObject",
          "url":"https://almanac.httparchive.org/static/images/home-hero-2020-part-3-1200x900.png",
          "width": 1200,
          "height": 900
        },
        {
          "@type":"ImageObject",
          "url":"https://almanac.httparchive.org/static/images/home-hero-2020-part-3-1200x1200.png",
          "width": 1200,
          "height": 1200
        }
      ]
    }
```

And the AMP story looks like this:

```html
<body>
  <amp-story role="main" standalone publisher="HTTP Archive"
             publisher-logo-src="/static/images/ha-square.png"
             title="Web Almanac 2020 Part III: Content Publishing"
             poster-portrait-src="/static/stories/web-almanac-2020-content-publishing/WA_Cover-Image_Part-III-640x853.jpg"
             poster-square-src="/static/stories/web-almanac-2020-content-publishing/WA_Cover-Image_Part-III-640x640.jpg"
             poster-landscape-src="/static/stories/web-almanac-2020-content-publishing/WA_Cover-Image_Part-III-853x640.jpg" class="i-amphtml-layout-container" i-amphtml-layout="container">
    <amp-story-page id="a9c1b17a-7e0d-4a6d-aab1-89a21a911a79" auto-advance-after="15s" class="i-amphtml-layout-container" i-amphtml-layout="container">
```

As I say that's pretty much identical to the other 3 stories that aren't complaining and I think we've met all the requirements so really confused.

@swissspidy any ideas on this? I know it's only a warning, but still - it's annoying me and tried several thinkgs to fix this and each of them haven't worked :-(

**Comment by swissspidy** [comment]
Sorry for the delay here @bazzadp. I am not too familiar with the Search Console warnings in this area and unfortunately haven't yet received a response for an internal inquiry about it.

I see you've made some more changes recently. Did this change anything with the warnings?

**Comment by bazzadp** [comment]
Did it wrong, so waiting on the results for the latest attempted fix! Should get feedback in next day or two.

Did discover that this story (unlike the others) doesn’t have any big images in the article itself so guessing that the problem as it is a difference. It kind of makes sense that just having it in Structure Data image isn’t really good enough, but on the other hand enforcing these large large image requirements doesn’t lend itself to AMP Stories where there might not be a big banner image (like this one!). For articles it kind of does makes sense, but not for Stories.

Anyway, hoping that’s it! Will update once I get the latest results back - one way or the other.

**Comment by bazzadp** [comment]
Woo hoo - it finally is accepted as fix! That was painful...

**Comment by bazzadp** [comment]
Sigh. It's back. Reopening.

**Comment by bazzadp** [comment]
The warning was removed again. I suspect it was just an old crawl catching up. Will leave this open until all 4 stories are back in the Google Index in Google Search Console, but looking more positive than I thought last time.

**Comment by bazzadp** [comment]
Closing this again. Not seen the warning since the last fix, though Google Search Console seems a little hesitant to index all the web stories:

![Only 2 out of the 4 stories are registered in Google Search Console](https://user-images.githubusercontent.com/10931297/115850619-f8328780-a41d-11eb-9167-3200b2e57a0d.png)

Not sure why to be honest but don't think there's much more we can do here.
