### ISSUE TITLE
Typo in Part I Chapter 1 CSS

### ISSUE THREAD

**Issue by robnyman** [HTTPArchive/almanac.httparchive.org#2003]
**URL**
https://almanac.httparchive.org/en/2020/css#layout

**Describe the issue**
The text reads "a far cry from the tables when tables"

**Expected behavior**
The text probably should read "a far cry from the days when tables"

**Comment by bazzadp** [comment]
Agreed. Fixed in #2004

**Comment by bazzadp** [comment]
Thanks @robnyman for reporting. That's fixed and deployed (note you may see the cached version for a few hours).

**Comment by robnyman** [comment]
Wow, that was quick! Thank you!
