### ISSUE TITLE
Write the Methodology page

### ISSUE THREAD

**Issue by rviscomi** [HTTPArchive/almanac.httparchive.org#202]
I've started [this draft doc](https://docs.google.com/document/d/1ViWF_7if4ATds36qoTJYUL3gxIigYG1jsylMqZERuaM/edit?usp=sharing). Here's the outline as of now:

- Overview (intro to HTTP Archive)
- About the dataset
  - Website corpus (why are we testing these particular URLs, home pages only)
  - WebPageTest (brief intro, how it's configured)
  - Lighthouse (version/config, mobile only, available audits)
  - Wappalyzer (technology detection)
  - Chrome UX Report (dimensions and metrics)
  - Rework CSS (stylesheet parsing)
- Analytical process (what we did to arrive at these chapters/metrics/results)
  - Brainstorm
  - Analyze
  - Interpret

Anyone can comment on the doc, so let me know if you'd like to add anything. The doc is mostly just an outline at the moment but I'll be writing more content to fill it in.

**Comment by rviscomi** [comment]
Update: I've got about half of the content written.

@paulcalvano @pmeenan @obto does everything make sense so far?

**Comment by rviscomi** [comment]
I've finished the first draft of the doc. PTAL: https://docs.google.com/document/d/1ViWF_7if4ATds36qoTJYUL3gxIigYG1jsylMqZERuaM/edit?usp=sharing

**Comment by obto** [comment]
Finished reading through and leaving my comments. Very enjoyable read 👍
