### ISSUE TITLE
Finalize assignments: Chapter 19. Resource Hints

### ISSUE THREAD

**Issue by rviscomi** [HTTPArchive/almanac.httparchive.org#21]
Section | Chapter | Authors | Reviewers
-- | -- | -- | --
IV. Content Distribution | 19. Resource Hints | @khempenius @yoavweiss |@andydavies @addyosmani 

**Due date:** To help us stay on schedule, please complete the action items in this issue by June 3.

**To do:**
- [x] Assign subject matter experts (coauthors)
- [x] Assign peer reviewers
- [x] Finalize metrics

**Current list of metrics:**

For each resource hint (preload, prefetch, preconnect, prerender):
- % of sites using $HINT; how this has changed since a year ago.
- For sites using $HINT, # of times it is used.
- `crossorigin` attribute, `as` attribute, resource priority 
- Preload/Prefetch-only: the resource types that $HINT is used for (e.g. js, document, etc.)
- Preload only: % of sites that are using `as=font`/`as=fetch` without a `crossorigin` attribute, or that are using any other `as` value with a `crossorigin` attribute.
- Preload only: % of sites where a preload of low priority is done before a load of higher priority and a different `as` attribute value.

Priority Hints:
- % of sites using this
*Note: depending on how small the sample size is the following metrics may not be worth calculating*
- Usage breakdown by tag (i.e. iframe, img, link, or script)
- Usage breakdown by Importance (i.e. low/high/auto)
- (Optional) tag x importance (e.g. do scripts tend to be "high" importance? iframes "low" importance? etc.)

👉 **AI (coauthors):** Finalize which metrics you might like to include in an annual "state of priority hints" report powered by HTTP Archive. Community contributors have initially sketched out a few ideas to get the ball rolling, but it's up to you, the subject matter experts, to know exactly which metrics we should be looking at. You can use [the brainstorming doc](https://docs.google.com/document/d/1sCIMeErYvaQb5x9Acdb6ImYdn0-buHRhYGvz2HoysmM/edit#heading=h.iznoa2266s2c) to explore ideas.

The metrics should paint a holistic, data-driven picture of the priority hints landscape. The HTTP Archive does have its limitations and blind spots, so if there are metrics out of scope it's still good to identify them now during the brainstorming phase. We can make a note of them in the final report so readers understand why they're not discussed and the HTTP Archive team can make an effort to improve our telemetry for next year's Almanac.

**Next steps:** Over the next couple of months analysts will write the queries and generate the results, then hand everything off to you to write up your interpretation of the data.

**Additional resources:**
- [All chapter assignments](https://github.com/HTTPArchive/httparchive.org/issues/140)
- [Project timeline](https://docs.google.com/spreadsheets/d/1LR29JpI2XJSjan_z6uP1YpRy4EYYivYZPqCIG-9sfFY/edit?usp=sharing)
- [About the project](https://discuss.httparchive.org/t/planning-the-web-almanac-2019/1553)

**Comment by rviscomi** [comment]
@yoavweiss you had mentioned that this chapter might be better off renamed or its scope changed to be less granular. Any other thoughts on that?

Also, @khempenius @yoavweiss have you thought of anyone who might make a good reviewer for this chapter?

**Comment by khempenius** [comment]
I agree. How about renaming this section to "Resource and Priority Hints" or "Loading Optimizations"?

Maybe @addyosmani can review?

**Comment by rviscomi** [comment]
Either rename SGTM. @yoavweiss any preference?

Added @andydavies as a reviewer. @addyosmani would you also be interested in reviewing?

**Comment by yoavweiss** [comment]
"Resource loading optimizations"? :)

**Comment by rviscomi** [comment]
Actually, "loading optimizations" may be too vague. Caching or compression are loading optimizations but not in scope for this chapter. Is "Resource Hints" a better name?

**Comment by addyosmani** [comment]
Resource Hints sgtm.

**Comment by rviscomi** [comment]
@khempenius @yoavweiss @andydavies @addyosmani we're hoping to finalize the list of metrics for each chapter today. Could you take a look at the metrics at https://github.com/HTTPArchive/almanac.httparchive.org/issues/21#issue-446806508 and tick the last TODO checkbox and close this issue if you're happy with it? Thanks!

**Comment by yoavweiss** [comment]
Belatedly updated some metrics. I think we want to try to detect sites that are using hints wrong:
  - Preloading fonts/fetches without a crossorigin attribute
  - Preloading more than X resources
  - Preloading non-critical resources before render blocking ones
  - Preconnecting to too many hosts

I'm not sure if these should be metrics on their own, or we can use collected metrics to conclude that (some just require a number, others require joining, so might be better as their own metric)

**Comment by rviscomi** [comment]
That's a good list, thanks @yoavweiss. Could you take a go at rephrasing the metrics to be more quantifiable? For example "% of websites that preload more than X resources" where X is defined. Just want to make sure that the data extracted by the analyst team matches your expectations.

**Comment by andydavies** [comment]
@yoavweiss In your pattern of "sites doing it wrong" you might want to look at how many are using multiple async CSS with preload - came across a few sites doing it and it's non-deterministic

Can you also look at how many are still using AppCache ;-p

**Comment by yoavweiss** [comment]
> That's a good list, thanks @yoavweiss. Could you take a go at rephrasing the metrics to be more quantifiable? For example "% of websites that preload more than X resources" where X is defined. Just want to make sure that the data extracted by the analyst team matches your expectations.

@rviscomi - Added something like the above for "Preloading fonts/fetches without a crossorigin attribute". "Preloading more than X resources" and "Preconnecting to too many hosts" seem to be already covered. 

Where I'm a bit stuck is "Preloading non-critical resources before render blocking ones". Is there a way to detect render blocking resources in HA? If there's nothing explicit, maybe we can infer that from network priority + destination??

**Comment by yoavweiss** [comment]
> @yoavweiss In your pattern of "sites doing it wrong" you might want to look at how many are using multiple async CSS with preload - came across a few sites doing it and it's non-deterministic

@andydavies - not sure what you mean. Can you explain?

**Comment by andydavies** [comment]
@yoavweiss this approach
https://www.filamentgroup.com/lab/async-css.html

There are sites loading multiple stylesheets using this method, and there
seems no guarantee on which order the sheets download and so are applied
(smaller files will download first)

**Comment by yoavweiss** [comment]
OK, cool. That's theoretically fine, assuming that the CSS files only add unconnected-between-them specificity, no? Also, wouldn't developers notice breakage in cases they are inter-connected?

**Comment by rviscomi** [comment]
> Where I'm a bit stuck is "Preloading non-critical resources before render blocking ones". Is there a way to detect render blocking resources in HA? If there's nothing explicit, maybe we can infer that from network priority + destination??

AFAIK that'd be difficult to get right using only heuristics. @pmeenan can you think of a more solid approach?

@yoavweiss when you're happy with the list of metrics can you close this issue?

**Comment by yoavweiss** [comment]
Added something with priorities that should be a close enough approximation (I think). Closing!

**Comment by rviscomi** [comment]
@khempenius @yoavweiss question regarding this metric:

> crossorigin attribute, as attribute, resource priority

How is priority determined? I don't think this is an attribute of the `<link>` element.

**Comment by pmeenan** [comment]
Thie "importance" attribute maybe?
