### ISSUE TITLE
Implement the Contributors page design

### ISSUE THREAD

**Issue by rviscomi** [HTTPArchive/almanac.httparchive.org#214]
![image](https://user-images.githubusercontent.com/1120896/67223708-c3470e00-f3fd-11e9-84c1-992d340b6454.png)

Desktop: https://projects.invisionapp.com/d/main#/console/18009643/386025636/inspect
Mobile: https://projects.invisionapp.com/d/main#/console/18174420/387303024/inspect

cc @HTTPArchive/developers

**Comment by rviscomi** [comment]
The avatars in https://github.com/HTTPArchive/almanac.httparchive.org/tree/master/src/static/images/avatars have a white bg. We'll also need to make them transparent. I have the source PSD file if needed.

**Comment by ymschaap** [comment]
Question, I saw the contributor lists supports [github and twitter](https://github.com/HTTPArchive/almanac.httparchive.org/blob/bf2f9f68a2d294007913d942ddfb076f4e224b1f/src/templates/en/2019/contributors.html#L115), would it make sense to add any website/blog as an option too for contributors?

**Comment by rviscomi** [comment]
@ymschaap possibly if people feel strongly, otherwise I think we should limit it to just these two.

**Comment by rviscomi** [comment]
Any @HTTPArchive/developers available to take this on?

**Comment by ymschaap** [comment]
@rviscomi looking at the bio's at #239 I see more external websites then github or twitter mentions :) this is the *web* almanac right ;) But I understand this will be extra work/designs/time.

**Comment by catalinred** [comment]
@rviscomi Is there anything I can do to help at this point?

**Comment by rviscomi** [comment]
Ok you've convinced me. But you have to promise to build the functionality! We'll need an icon (generic globe icon used everywhere) and the plumbing to render it from the config file into the Contributors page.

**Comment by ymschaap** [comment]
Haha, it was a trap.  Working on it.
