### ISSUE TITLE
Performance 2021

### ISSUE THREAD

**Issue by rviscomi** [HTTPArchive/almanac.httparchive.org#2148]
# Part II Chapter 11: Performance

![Performance illustration](https://raw.githubusercontent.com/HTTPArchive/almanac.httparchive.org/main/src/static/images/2019/performance/hero_lg.jpg)

If you're interested in contributing to the Performance chapter of the 2021 Web Almanac, please reply to this issue and indicate which role or roles best fit your interest and availability: [author](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Authors'-Guide), [reviewer](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Reviewers'-Guide), [analyst](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Analysts'-Guide), and/or [editor](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Editors'-Guide).

## Content team

| Lead | Authors | Reviewers | Analysts | Editors | Coordinator |
| --- | ------- | --------- | -------- | ------- | -- |
| @siakaramalegos | @siakaramalegos | @rviscomi @ziemek-bucko @edmondwwchan @jzyang @estelle @kevinfarrugia @samarpanda @fili  | @Nithanaroy @siakaramalegos  | @jzyang | @obto |

<details>
<summary><b>Expand for more information about each role</b></summary>

- The **[content team lead](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Content-Team-Leads'-Guide)** is the chapter owner and responsible for setting the scope of the chapter and managing contributors' day-to-day progress.
- **[Authors](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Authors'-Guide)** are subject matter experts and lead the content direction for each chapter. Chapters typically have one or two authors. Authors are responsible for planning the outline of the chapter, analyzing stats and trends, and writing the annual report.
- **[Reviewers](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Reviewers'-Guide)** are also subject matter experts and assist authors with technical reviews during the planning, analyzing, and writing phases.
- **[Analysts](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Analysts'-Guide)** are responsible for researching the stats and trends used throughout the Almanac. Analysts work closely with authors and reviewers during the planning phase to give direction on the types of stats that are possible from the dataset, and during the analyzing/writing phases to ensure that the stats are used correctly.
- **[Editors](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Editors'-Guide)** are technical writers who have a penchant for both technical and non-technical content correctness. Editors have a mastery of the English language and work closely with authors to help wordsmith content and ensure that everything fits together as a cohesive unit.
- The **[section coordinator](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Section-Leads'-Guide)** is the overall owner for all chapters within a section like "User Experience" or "Page Content" and helps to keep each chapter on schedule.

_Note: The time commitment for each role varies by the chapter's scope and complexity as well as the number of contributors._

For an overview of how the roles work together at each phase of the project, see the [Chapter Lifecycle](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Chapter-Lifecycle) doc.
</details>

### [**0. Form the content team**](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Chapter-Lifecycle#0-create-content-team)
+ [x] **May 31**: The content team has at least one author, reviewer, and analyst

### [**1. Plan content**](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Chapter-Lifecycle#1-plan-content)
+ [x] **June 15** The content team has completed the chapter outline in the [draft doc][~google-doc]

### [**2. Gather data**](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Chapter-Lifecycle#2-gather-data)
+ [x] **June 30**: Analysts have added all necessary [custom metrics](https://github.com/HTTPArchive/legacy.httparchive.org/blob/master/custom_metrics/README.md) and drafted a PR ([example](https://github.com/HTTPArchive/almanac.httparchive.org/pull/1087)) to track query progress
- **July 1 - 31**: HTTP Archive runs the July crawl

### [**3. Validate results**](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Chapter-Lifecycle#3-validate-results)
+ [x] **September 30**: Analysts have queried all metrics and saved the output to the [results sheet][~google-sheets]

### [**4. Draft content**](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Chapter-Lifecycle#4-draft-content)
+ [ ] **October 31**: The content team has written, reviewed, and edited the chapter in the [doc][~google-doc]

### [**5. Publication**](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Chapter-Lifecycle#5-publication)
+ [ ] **November 15**: The completed chapter and all required [metadata](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Authors'-Guide#metadata-to-add-at-the-top-of-your-chapters) and [figures](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Figures-Guide) are converted to markdown and submitted to [GitHub][~chapter-markdown]
- **December 1**: Target launch date 🚀

## Chapter resources

Refer to these 2021 Performance resources throughout the content creation process:

[📄 Google Docs][~google-doc] for outlining and drafting content
[🔍 SQL files][~sql-files] for committing the queries used during analysis
[📊 Google Sheets][~google-sheets] for saving the results of queries
[📝 Markdown file][~chapter-markdown] for publishing content and managing public metadata

[~google-doc]: https://docs.google.com/document/d/1kcUGQBu9RIJ4dfE19s-GBKFIV1_QaJ4jWtAJEKz1NbE/edit?usp=sharing
[~sql-files]: https://github.com/HTTPArchive/almanac.httparchive.org/tree/main/sql/2021/performance
[~google-sheets]: https://docs.google.com/spreadsheets/d/13xhPx6o2Nowz_3b3_5ojiF_mY3Lhs25auBKM6eqGZmo/edit?usp=sharing
[~chapter-markdown]: https://github.com/HTTPArchive/almanac.httparchive.org/tree/main/src/content/en/2021/performance.md

**Comment by ziemek-bucko** [comment]
Hey, I'd love to contribute here, whether it's writing, editing, translating or anything else!

**Comment by rviscomi** [comment]
Thanks @ziemek-bucko! We're usually understaffed with analysts and I see in your GH profile that you've worked with BigQuery before, so how about joining as an analyst? And there are lots of translation opportunities available now if you'd like to jump in! See #923

**Comment by jono-alderson** [comment]
Hello! Long-time fan, first-time caller.

I'd be extremely interested in authoring this section.

Why me?

I'm a web performance nerd, and I've been speaking internationally in the SEO & digital marketing space about performance for longer than I care to remember (see https://www.jonoalderson.com/speaking/). I'm also a member of the AMP Advisory Committee, and influence a lot of the performance thinking which happens at Yoast (and in our relation with / contributions to other open-source projects). I spend my evenings and weekends playing with cutting-edge, byte-by-byte optimization of all the things; I'm currently obsessed with shifting localization and fragment caching into edge workers, and what the 'perfect image tag' might look like.

Some of my performance-related writing:
- https://developer.yoast.com/blog/a-better-faster-approach-to-css-in-wordpress-themes/
- https://core.trac.wordpress.org/ticket/46370

**Comment by rviscomi** [comment]
Thanks @jono-alderson! I'll tentatively put you down as a reviewer while we see if anyone else is interested in authoring. It's also really helpful to have your credentials for when we do need to pick an author, so thanks for providing that!

**Comment by fili** [comment]
Happy to contribute as a peer reviewer here as well. Given many presentations on the topic of performance, and recently launched webvitals.dev 😁

**Comment by Nithanaroy** [comment]
I would like to be an analyst

**Comment by jono-alderson** [comment]
If we have other author candidates, I'd be happy to remain as a Reviewer, and to keep my primary focus on #2174.

**Comment by siakaramalegos** [comment]
Hi, I'd be interested in being an author. I write and speak on performance as well as perform contract work for various companies on performance. You can learn more about me on my website (including articles, talks, and workshops): https://sia.codes/

If I'm not chosen, I'm happy to be a reviewer. Thanks for your consideration.

**Comment by rviscomi** [comment]
Thanks @siakaramalegos great to have you! I've tentatively added you as a reviewer until we decide on authors.

**Comment by siakaramalegos** [comment]
I just realized I'd also probably be good in the editor role for any article, as a backup if I'm not an author.

**Comment by rviscomi** [comment]
Ok great. If there are specific chapters that you'd like to edit feel free to comment on them now. Editing also doesn't start for several months until the content takes shape so you have time to decide.

**Comment by edmondwwchan** [comment]
May I join the team to support this chapter as a peer review? Thanks.

**Comment by rviscomi** [comment]
Absolutely, welcome to the team @edmondwwchan!

**Comment by rviscomi** [comment]
@siakaramalegos thanks for your interest in authoring this chapter! As the content team lead, you'll be responsible for the scope and direction of the chapter and keeping it on schedule. We automatically monitor the staffing and progress of each chapter based on the state of the [initial comment][~chapter-metadata] so please keep that updated as you add new contributors and meet each milestone.

We've created a [Google Doc][~google-doc] for this chapter, which you're encouraged to use to collaborate with the content team on the initial outline, metrics, and ultimately the final draft.

Next steps for this chapter are:

- Due **May 31**: Complete [Milestone 0: Form the content team](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Chapter-Lifecycle#0-create-content-team)—you can check this off now since you've already got at least one author, reviewer, and analyst ✨ 
- Due **June 15**: Get started on [Milestone 1: Plan content](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Chapter-Lifecycle#1-plan-content) by brainstorming some content ideas in the [doc][~google-doc] (you may need to request edit access, cc @ziemek-bucko @jono-alderson @fili @edmondwwchan @jzyang @Nithanaroy)

@obto will be the section coordinator for this chapter, so they'll be periodically checking in with you directly to make sure the chapter is staying on schedule. Reach out to them here in this issue if you have any questions about the process.

More information about the [content team lead](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Content-Team-Leads'-Guide) and [author](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Authors'-Guide) roles and responsibilities are available for reference in the wiki if needed.

To anyone else still interested in contributing to this chapter, please comment below to join the team!


[~chapter-metadata]: https://github.com/HTTPArchive/almanac.httparchive.org/issues/2148#issue-868435877
[~google-doc]: https://docs.google.com/document/d/1kcUGQBu9RIJ4dfE19s-GBKFIV1_QaJ4jWtAJEKz1NbE/edit?usp=sharing

**Comment by rviscomi** [comment]
ℹ️ FYI 2019/2020 contributors: @JMPerez @obto @sergeychernyshev @zeman @hakimelek @raghuramakrishnan71 @thefoxis @dimension85 @borisschapira @estelle @zeman @noamr @ashrith-kulai @Zizzamia @exterkamp @max-ostapenko @dooman87

The 2021 Performance chapter is in good shape in terms of staffing, but I wanted to ping you all in case you'd still like to contribute as reviewers or analysts. It's great to have input from past years' contributors. Let us know!

**Comment by rviscomi** [comment]
@eliwilliamson were you interested in being a peer reviewer for this chapter?

**Comment by Zizzamia** [comment]
Happy to help as reviewer :-)

**Comment by samarpanda** [comment]
Can i join as a reviewer?

**Comment by estelle** [comment]
Please add me to the reviewer list.

**Comment by kevinfarrugia** [comment]
Would be happy to help as a reviewer if you're still looking for some. :)

**Comment by siakaramalegos** [comment]
Hey folks, thanks for volunteering to be on the Performance chapter team! I created a channel in the [HTTP Archive Slack](https://join.slack.com/t/httparchive/shared_invite/zt-45sgwmnb-eDEatOhqssqNAKxxOSLAaA) for this chapter - please join in for chat/discussions that don't need to be comments in this GH issue.

You can find detailed descriptions of each role in the [Chapter Lifecycle](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Chapter-Lifecycle) article in the wiki. 

**Action Item**
To confirm your participation, please add your name and email address to the Content Team portion of the [draft Google doc](https://docs.google.com/document/d/1kcUGQBu9RIJ4dfE19s-GBKFIV1_QaJ4jWtAJEKz1NbE/edit). You may need to request edit access. (@ziemek-bucko @jono-alderson @fili @edmondwwchan @jzyang @estelle @Zizzamia @kevinfarrugia @Nithanaroy @jzyang @obto)

**Comment by obto** [comment]
Hey @siakaramalegos excited to work with you and the rest of the group this year on the Almanac. I'm your go to guy if you've got any questions or need help so don't hesitate to reach out to me on github, the [Slack](https://join.slack.com/t/httparchive/shared_invite/zt-45sgwmnb-eDEatOhqssqNAKxxOSLAaA) (@obto) or email (david@davidjfox.com).

Few first steps:

1. All authors, reviewers and analysts should add themselves to the [Google Doc](https://docs.google.com/document/d/1kcUGQBu9RIJ4dfE19s-GBKFIV1_QaJ4jWtAJEKz1NbE/edit) in the format: `Name (email@example.com)`. But looks like you've already got a good handle on that.
2. I've added links within the doc to the previous years Google doc in case you'd like to mine it for ideas.
3. Would love to set up a 30 minute Zoom call in the next couple weeks to kick-start the chapter planning and brainstorming process, and put some faces to the names of the people we'll all be working with this year. I'll reach out again later this week to find a time that works.

Excited to work with you all this year.

**Comment by siakaramalegos** [comment]
@Nithanaroy are you still interested in being an analyst? Just checking in since I haven't heard from you and we need to finalize the team. If you are, please add your name and email to the Google Doc and join us in Slack. See details in [this comment](https://github.com/HTTPArchive/almanac.httparchive.org/issues/2148#issuecomment-838786943)

**Comment by obto** [comment]
@siakaramalegos @rviscomi @ziemek-bucko @jono-alderson @fili @edmondwwchan @jzyang @estelle @Zizzamia @kevinfarrugia @Nithanaroy

Hey everyone, looks like there's been a lot of progress on creating the chapter outline which is awesome!

We should be in great shape to complete it by **June 15** so we have enough time to update our crawler with any additional metrics you need this year.

Also a reminder that the team has a channel on slack (`#web-almanac-performance`), so feel free to join the discussion there as well: https://join.slack.com/t/httparchive/shared_invite/zt-45sgwmnb-eDEatOhqssqNAKxxOSLAaA

If you have any other questions don't hesitate to reach out :)

**Comment by siakaramalegos** [comment]
@obto Thanks for reminding me to post here too! In case you're not on Slack, the [first draft of the outline](https://docs.google.com/document/d/1kcUGQBu9RIJ4dfE19s-GBKFIV1_QaJ4jWtAJEKz1NbE/edit#) is done, so it's ready for reviewers to review. **All reviews should be done in a week (by June 4)** so that I have time to make final edits and work with our analyst to build queries or custom metrics.

The [list of metrics](https://docs.google.com/spreadsheets/d/1YGniwoyYDH3BcL7lUzKMd05eDrN-lYqrDvkYpq87OY8/edit#gid=1602216523) is really large. So instead of giving feedback on what’s missing, try to focus the feedback on what are the likely biggest impacts to performance that are missing. A lot will need to be cut in the final version of the chapter for it to still be read by humans so I want to focus more on biggest impacts.

[Slack](https://join.slack.com/t/httparchive/shared_invite/zt-45sgwmnb-eDEatOhqssqNAKxxOSLAaA) is the best place for longer discussions. I haven't heard from some of you yet, so after this week I'll start untagging you from the contributors on the assumption you don't have the time right now. :)

**Comment by obto** [comment]
@siakaramalegos @Nithanaroy

Hey everyone, wanted to give you a heads-up and reminder that the July website crawl has completed and chapters now need to:

1. Analysts: Please write, test and publish the results of all the queries in the draft PR you should have created last month. We've got 3 chapters (PWA, Mobile Web, Accessibility) filled with every type of query you can imagine that you can refer to if you've ever got a question for how to grab the data you need.

2. Chapter leads: Take a look at your Analysts draft PR where they have listed all the queries/data they'll be analyzing. You'll want to make sure all the ideas you discussed are listed and that nothing was lost in communication.

3. Analysts: Once your queries are completed and data has been put into the spreadsheets (along with comments), set up a time to run through the data with the Chapter lead so they know exactly how to interpret the data

That's it! Really looking forward to seeing the chapter start to take form. And if you've ever got any questions just ping me


PWA: [Queries](https://github.com/HTTPArchive/almanac.httparchive.org/pull/2272), [Results (has all their visualizations done as well)](https://docs.google.com/spreadsheets/d/16AkIdDBBkCR5Kgb7kyfYvnNLQBu23Vsh7MUSFHW9RtA/edit#gid=398503119)
Mobile Web: [Queries](https://github.com/HTTPArchive/almanac.httparchive.org/pull/2310), [Results](https://docs.google.com/spreadsheets/d/1mdma245ja_THTBApaJTeS4vmLY_Fn8VC6Kd8qx7wp-o/edit#gid=1041308066)
A11Y: [Queries](https://github.com/HTTPArchive/almanac.httparchive.org/pull/2299), [Results](https://docs.google.com/spreadsheets/d/1WjAM5ZnHjMQt-rKyHvj2eVhU_WdzzFTjpoYWMr_I0Cw/edit#gid=1329123536)

**Comment by siakaramalegos** [comment]
Hi Reviewers, in case you're not active in our Slack channel, the draft is ready for your review! I apologize for the delay - I had a whole hurricane, evacuation, and unplanned move in case you didn't know yet. I'm confident we can get back on track though!

Please review at your earliest convenience! The draft is in the same doc as before - use the outline aside to jump directly to “Draft” https://docs.google.com/document/d/1kcUGQBu9RIJ4dfE19s-GBKFIV1_QaJ4jWtAJEKz1NbE/edit#heading=h.l58oy8wsputh

@rviscomi  @ziemek-bucko @jono-alderson @fili @edmondwwchan @jzyang @estelle @Zizzamia @kevinfarrugia

**Comment by rviscomi** [comment]
Thanks @siakaramalegos I've left my comments. It's looking great!

**Comment by siakaramalegos** [comment]
@estelle @fili @Nithanaroy @kevinfarrugia @ziemek-bucko @jzyang @samarpanda @edmondwwchan for the published almanac, I need any of the following data you'd like to include - this is my example (name is required, rest is optional):

```
      "name": "Sia Karamalegos",
      "website": "https://sia.codes",
      "linkedin": "karamalegos",
      "twitter": "TheGreenGreek"
```

I already have your GitHub ID and avatar from GitHub. I'll use the name on there as a draft, but let me know if it's not how you would like it published. Please send to me in exactly this format so I can put it in the config. You can DM me on Slack also if you prefer.

**Comment by siakaramalegos** [comment]
It would be even better if you could submit a PR for your info here: Already added your names, GH id, GH avatar. Fill in the blanks for the rest or delete the line if you don't want to include it https://github.com/siakaramalegos/almanac.httparchive.org/blob/performance-2021-markdown/src/config/2021.json

**Comment by tunetheweb** [comment]
Or could suggest as a Review suggestion here if done before this is merged: https://github.com/HTTPArchive/almanac.httparchive.org/pull/2434/files

**Comment by siakaramalegos** [comment]
I'd prefer a PR to my repo so it reduces the amount of upstream fetching I have to do. Or just give me the data.

**Comment by rviscomi** [comment]
@siakaramalegos @ziemek-bucko @edmondwwchan @jzyang @estelle @kevinfarrugia @samarpanda @fili @Nithanaroy @jzyang

**Thank you** all for your hard work getting this chapter over the finish line in time for the pre-release! Congratulations on finishing the chapter, and I'm excited to see us launch the rest of the chapters along side it on Wednesday 🎉

When you get 5 minutes, I'd really appreciate if you could fill out our [contributor survey](https://forms.gle/VRzHPTyWxuwa67vF7) to tell us (the project leads) about your experience. It's super helpful to hear what went well or what could be improved for next time. 🙏
