### ISSUE TITLE
Privacy 2021

### ISSUE THREAD

**Issue by rviscomi** [HTTPArchive/almanac.httparchive.org#2149]
# Part II Chapter 12: Privacy

![Privacy illustration](https://raw.githubusercontent.com/HTTPArchive/almanac.httparchive.org/main/src/static/images/2020/privacy/hero_lg.jpg)

If you're interested in contributing to the Privacy chapter of the 2021 Web Almanac, please reply to this issue and indicate which role or roles best fit your interest and availability: [author](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Authors'-Guide), [reviewer](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Reviewers'-Guide), [analyst](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Analysts'-Guide), and/or [editor](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Editors'-Guide).

## Content team

| Lead | Authors | Reviewers | Analysts | Editors | Coordinator |
| --- | ------- | --------- | -------- | ------- | -- |
| @ydimova | @ydimova @VictorLeP  | @SaptakS @cqueern @maudnals | @max-ostapenko @VictorLeP  | - | @obto |

<details>
<summary><b>Expand for more information about each role</b></summary>

- The **[content team lead](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Content-Team-Leads'-Guide)** is the chapter owner and responsible for setting the scope of the chapter and managing contributors' day-to-day progress.
- **[Authors](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Authors'-Guide)** are subject matter experts and lead the content direction for each chapter. Chapters typically have one or two authors. Authors are responsible for planning the outline of the chapter, analyzing stats and trends, and writing the annual report.
- **[Reviewers](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Reviewers'-Guide)** are also subject matter experts and assist authors with technical reviews during the planning, analyzing, and writing phases.
- **[Analysts](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Analysts'-Guide)** are responsible for researching the stats and trends used throughout the Almanac. Analysts work closely with authors and reviewers during the planning phase to give direction on the types of stats that are possible from the dataset, and during the analyzing/writing phases to ensure that the stats are used correctly.
- **[Editors](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Editors'-Guide)** are technical writers who have a penchant for both technical and non-technical content correctness. Editors have a mastery of the English language and work closely with authors to help wordsmith content and ensure that everything fits together as a cohesive unit.
- The **[section coordinator](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Section-Leads'-Guide)** is the overall owner for all chapters within a section like "User Experience" or "Page Content" and helps to keep each chapter on schedule.

_Note: The time commitment for each role varies by the chapter's scope and complexity as well as the number of contributors._

For an overview of how the roles work together at each phase of the project, see the [Chapter Lifecycle](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Chapter-Lifecycle) doc.
</details>

### [**0. Form the content team**](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Chapter-Lifecycle#0-create-content-team)
+ [x] **May 31**: The content team has at least one author, reviewer, and analyst

### [**1. Plan content**](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Chapter-Lifecycle#1-plan-content)
+ [x] **June 15** The content team has completed the chapter outline in the [draft doc][~google-doc]

### [**2. Gather data**](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Chapter-Lifecycle#2-gather-data)
+ [x] **June 30**: Analysts have added all necessary [custom metrics](https://github.com/HTTPArchive/legacy.httparchive.org/blob/master/custom_metrics/README.md) and drafted a PR ([example](https://github.com/HTTPArchive/almanac.httparchive.org/pull/1087)) to track query progress
- **July 1 - 31**: HTTP Archive runs the July crawl

### [**3. Validate results**](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Chapter-Lifecycle#3-validate-results)
+ [x] **September 30**: Analysts have queried all metrics and saved the output to the [results sheet][~google-sheets]

### [**4. Draft content**](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Chapter-Lifecycle#4-draft-content)
+ [x] **October 31**: The content team has written, reviewed, and edited the chapter in the [doc][~google-doc]

### [**5. Publication**](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Chapter-Lifecycle#5-publication)
+ [ ] **November 15**: The completed chapter and all required [metadata](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Authors'-Guide#metadata-to-add-at-the-top-of-your-chapters) and [figures](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Figures-Guide) are converted to markdown and submitted to [GitHub][~chapter-markdown]
- **December 1**: Target launch date 🚀

## Chapter resources

Refer to these 2021 Privacy resources throughout the content creation process:

[📄 Google Docs][~google-doc] for outlining and drafting content
[🔍 SQL files][~sql-files] for committing the queries used during analysis
[📊 Google Sheets][~google-sheets] for saving the results of queries
[📝 Markdown file][~chapter-markdown] for publishing content and managing public metadata

[~google-doc]: https://docs.google.com/document/d/1rFjEKizOKNaHHUHroxfZR56zSmcKHDRAe0KTdJT528I/edit?usp=sharing
[~sql-files]: https://github.com/HTTPArchive/almanac.httparchive.org/tree/main/sql/2021/privacy
[~google-sheets]: https://docs.google.com/spreadsheets/d/148SxZICZ24O44roIuEkRgbpIobWXpqLxegCDhIiX8XA/edit?usp=sharing
[~chapter-markdown]: https://github.com/HTTPArchive/almanac.httparchive.org/tree/main/src/content/en/2021/privacy.md

**Comment by SaptakS** [comment]
I would love to join as a co-author

**Comment by cqueern** [comment]
I might be able to support as a Peer Reviewer.

**Comment by rviscomi** [comment]
Thanks @SaptakS @cqueern I've tentatively put you both down as peer reviewers. @SaptakS if you had to pick between the Privacy and Security chapters, which are you more interested in authoring?

**Comment by SaptakS** [comment]
@rviscomi I would be more interested in authoring the Privacy chapters.

**Comment by cqueern** [comment]
Possible topics to explore this year may include:

- [FLOC](https://blog.google/products/chrome/privacy-sustainability-and-the-importance-of-and/)
- [Referer Policy](https://scotthelme.co.uk/a-new-security-header-referrer-policy/)

**Comment by bazzadp** [comment]
Referer policy’s gonna be pointless soon. If Apple ever gets with the program! https://twitter.com/manicode/status/1387062161718104065?s=21

However Features-Policy and the newer Permission-Policy and Document-Policy headers are definitely something we should look at more!

**Comment by SaptakS** [comment]
Permission-Policy has become even more important for websites to opt out of FLoC

**Comment by maudnals** [comment]
Hey all!
@rviscomi if you need one more peer reviewer, I'd e happy to contribute as one.

**Comment by rviscomi** [comment]
Welcome @maudnals! Added you as a reviewer.

**Comment by rviscomi** [comment]
📟 paging 2020 contributors: @ydimova @ldevernay @max-ostapenko

Would any of you be interested to contribute to the 2021 chapter? I'd especially like to see more 2019/2020 authors become 2021 reviewers to help ease the transition and similarly I think prior reviewers would make great 2021 authors, being familiar with the process already. And prior analysts would make excellent 2021 analysts 😁

Or is there anyone new you'd like to see?

**Comment by max-ostapenko** [comment]
Sure, please add me as an analyst!

**Comment by ydimova** [comment]
@rviscomi Looks like there are enough reviewers, I would like to help out as an author.

**Comment by rviscomi** [comment]
@ydimova thanks for your interest in authoring this chapter! As the content team lead, you'll be responsible for the scope and direction of the chapter and keeping it on schedule. We automatically monitor the staffing and progress of each chapter based on the state of the [initial comment][~chapter-metadata] so please keep that updated as you add new contributors and meet each milestone.

We've created a [Google Doc][~google-doc] for this chapter, which you're encouraged to use to collaborate with the content team on the initial outline, metrics, and ultimately the final draft.

Next steps for this chapter are:

- Due **May 31**: Complete [Milestone 0: Form the content team](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Chapter-Lifecycle#0-create-content-team)—you can check this off now since you've already got at least one author, reviewer, and analyst ✨
- Due **June 15**: Get started on [Milestone 1: Plan content](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Chapter-Lifecycle#1-plan-content) by brainstorming some content ideas in the [doc][~google-doc] (you may need to request edit access)

@obto will be the section coordinator for this chapter, so they'll be periodically checking in with you directly to make sure the chapter is staying on schedule. Reach out to them here in this issue if you have any questions about the process.

More information about the [content team lead](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Content-Team-Leads'-Guide) and [author](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Authors'-Guide) roles and responsibilities are available for reference in the wiki if needed.

To anyone else interested in contributing to this chapter, please comment below to join the team!


[~chapter-metadata]: https://github.com/HTTPArchive/almanac.httparchive.org/issues/2149#issue-868435900
[~google-doc]: https://docs.google.com/document/d/1rFjEKizOKNaHHUHroxfZR56zSmcKHDRAe0KTdJT528I/edit?usp=sharing

**Comment by rviscomi** [comment]
I have @ydimova and @maudnals's emails and have given them edit access to the doc. @SaptakS @cqueern could you request edit access? Once everyone's in the doc you all could get started on sketching out the chapter outline.

**Comment by cqueern** [comment]
> I have @ydimova and @maudnals's emails and have given them edit access to the doc. @SaptakS @cqueern could you request edit access? Once everyone's in the doc you all could get started on sketching out the chapter outline.

I've requested access

**Comment by VictorLeP** [comment]
If you can still use the help, I would like to contribute as an analyst and/or author :slightly_smiling_face:

**Comment by obto** [comment]
@ydimova @SaptakS @cqueern @maudnals @max-ostapenko

Hey everyone, wanted to check in and give you all a few reminder as we close in on our second deadline:

1. Please make sure you've requested edit access to the [Google Planning Doc](https://docs.google.com/document/d/1rFjEKizOKNaHHUHroxfZR56zSmcKHDRAe0KTdJT528I/edit) and added your name to the first page as a reviewer, author or analyst.

2. Reminder that we need to have the chapter outline complete by **June 15** so we have enough time to update our crawler with any additional metrics you need this year.

3. The team has a channel on slack (`#web-almanac-privacy`), so feel free to join everyone there as well: https://join.slack.com/t/httparchive/shared_invite/zt-45sgwmnb-eDEatOhqssqNAKxxOSLAaA

If you have any other questions don't hesitate to reach out :)


Also, @ydimova I'd love to setup a 30 minute Google Meet next week to kick-start the chapter planning and brainstorming process, and put some faces to the names of the people we'll all be working with this year. What times are you and the team available?

**Comment by rviscomi** [comment]
Hi @ydimova just a nudge to take a minute to edit https://github.com/HTTPArchive/almanac.httparchive.org/issues/2149#issue-868435900 and check off "Milestone 0" now that you have a complete content team. Keeping your contributors/milestones in sync is helpful for us to see how everyone is doing at a glance. Thanks!

**Comment by obto** [comment]
@ydimova Reminder that we've got just over a week to complete the chapter outline (June 15th). Please also work with your analysts (@max-ostapenko @VictorLeP) to run through all the metrics you'd like to look at and their feasibility. You should aim to have any metrics requiring custom code decided by EOD June 23rd, so your analysts have time to write them.

@max-ostapenko @SaptakS @cqueern Please add yourself to the [Google Doc](https://docs.google.com/document/d/1rFjEKizOKNaHHUHroxfZR56zSmcKHDRAe0KTdJT528I/edit) metadata and leave your thoughts on the current outline

**Comment by obto** [comment]
@ydimova @max-ostapenko @VictorLeP

Hey everyone, wanted to give you a heads-up and reminder that the July website crawl has completed and chapters now need to:

1. Analysts: Please write, test and publish the results of all the queries in the draft PR you should have created last month. We've got 3 chapters (PWA, Mobile Web, Accessibility) filled with every type of query you can imagine that you can refer to if you've ever got a question for how to grab the data you need.

2. Chapter leads: Take a look at your Analysts draft PR where they have listed all the queries/data they'll be analyzing. You'll want to make sure all the ideas you discussed are listed and that nothing was lost in communication.

3. Analysts: Once your queries are completed and data has been put into the spreadsheets (along with comments), set up a time to run through the data with the Chapter lead so they know exactly how to interpret the data

That's it! Really looking forward to seeing the chapter start to take form. And if you've ever got any questions just ping me


PWA: [Queries](https://github.com/HTTPArchive/almanac.httparchive.org/pull/2272), [Results (has all their visualizations done as well)](https://docs.google.com/spreadsheets/d/16AkIdDBBkCR5Kgb7kyfYvnNLQBu23Vsh7MUSFHW9RtA/edit#gid=398503119)
Mobile Web: [Queries](https://github.com/HTTPArchive/almanac.httparchive.org/pull/2310), [Results](https://docs.google.com/spreadsheets/d/1mdma245ja_THTBApaJTeS4vmLY_Fn8VC6Kd8qx7wp-o/edit#gid=1041308066)
A11Y: [Queries](https://github.com/HTTPArchive/almanac.httparchive.org/pull/2299), [Results](https://docs.google.com/spreadsheets/d/1WjAM5ZnHjMQt-rKyHvj2eVhU_WdzzFTjpoYWMr_I0Cw/edit#gid=1329123536)

**Comment by max-ostapenko** [comment]
@ydimova @VictorLeP all the visualisations are in [the sheets](https://docs.google.com/spreadsheets/d/148SxZICZ24O44roIuEkRgbpIobWXpqLxegCDhIiX8XA/edit#gid=380107930)

Please mention me in comments if anything needs to be adjusted (described)

**Comment by tunetheweb** [comment]
@max-ostapenko @VictorLeP I don't see the CNAME queries in the repo. Can you add them?

**Comment by VictorLeP** [comment]
> @max-ostapenko @VictorLeP I don't see the CNAME queries in the repo. Can you add them?

deferring to @ydimova, she is responsible for these queries.

**Comment by rviscomi** [comment]
@ydimova @VictorLeP @SaptakS @cqueern @maudnals @max-ostapenko @tunetheweb

**Thank you** all for your hard work getting this chapter over the finish line in time for the pre-release! Congratulations on finishing the chapter, and I'm excited to see us launch the rest of the chapters along side it on Wednesday 🎉

When you get 5 minutes, I'd really appreciate if you could fill out our [contributor survey](https://forms.gle/VRzHPTyWxuwa67vF7) to tell us (the project leads) about your experience. It's super helpful to hear what went well or what could be improved for next time. 🙏

**Comment by maudnals** [comment]
(Note for the 2022 edition, capturing this here for later reference: consider using https://chromestatus.com/metrics/feature/popularity#UserDataFieldFilledPreviously for a metric on user data collected in forms)
