### ISSUE TITLE
CMS 2021

### ISSUE THREAD

**Issue by rviscomi** [HTTPArchive/almanac.httparchive.org#2154]
# Part III Chapter 17: CMS

![CMS illustration](https://raw.githubusercontent.com/HTTPArchive/almanac.httparchive.org/main/src/static/images/2019/cms/hero_lg.jpg)

If you're interested in contributing to the CMS chapter of the 2021 Web Almanac, please reply to this issue and indicate which role or roles best fit your interest and availability: [author](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Authors'-Guide), [reviewer](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Reviewers'-Guide), [analyst](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Analysts'-Guide), and/or [editor](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Editors'-Guide).

## Content team

| Lead | Authors | Reviewers | Analysts | Editors | Coordinator |
| --- | ------- | --------- | -------- | ------- | -- |
| @alonkochba | @alonkochba @logicalphase | @saterchris @jdevalk | @TosinArasi | - | @logicalphase |

<details>
<summary><b>Expand for more information about each role</b></summary>

- The **[content team lead](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Content-Team-Leads'-Guide)** is the chapter owner and responsible for setting the scope of the chapter and managing contributors' day-to-day progress.
- **[Authors](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Authors'-Guide)** are subject matter experts and lead the content direction for each chapter. Chapters typically have one or two authors. Authors are responsible for planning the outline of the chapter, analyzing stats and trends, and writing the annual report.
- **[Reviewers](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Reviewers'-Guide)** are also subject matter experts and assist authors with technical reviews during the planning, analyzing, and writing phases.
- **[Analysts](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Analysts'-Guide)** are responsible for researching the stats and trends used throughout the Almanac. Analysts work closely with authors and reviewers during the planning phase to give direction on the types of stats that are possible from the dataset, and during the analyzing/writing phases to ensure that the stats are used correctly.
- **[Editors](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Editors'-Guide)** are technical writers who have a penchant for both technical and non-technical content correctness. Editors have a mastery of the English language and work closely with authors to help wordsmith content and ensure that everything fits together as a cohesive unit.
- The **[section coordinator](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Section-Leads'-Guide)** is the overall owner for all chapters within a section like "User Experience" or "Page Content" and helps to keep each chapter on schedule.

_Note: The time commitment for each role varies by the chapter's scope and complexity as well as the number of contributors._

For an overview of how the roles work together at each phase of the project, see the [Chapter Lifecycle](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Chapter-Lifecycle) doc.
</details>

### [**0. Form the content team**](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Chapter-Lifecycle#0-create-content-team)
+ [x] **May 31**: The content team has at least one author, reviewer, and analyst

### [**1. Plan content**](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Chapter-Lifecycle#1-plan-content)
+ [x] **June 15** The content team has completed the chapter outline in the [draft doc][~google-doc]

### [**2. Gather data**](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Chapter-Lifecycle#2-gather-data)
+ [x] **June 30**: Analysts have added all necessary [custom metrics](https://github.com/HTTPArchive/legacy.httparchive.org/blob/master/custom_metrics/README.md) and drafted a PR ([example](https://github.com/HTTPArchive/almanac.httparchive.org/pull/1087)) to track query progress
- **July 1 - 31**: HTTP Archive runs the July crawl

### [**3. Validate results**](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Chapter-Lifecycle#3-validate-results)
+ [x] **September 30**: Analysts have queried all metrics and saved the output to the [results sheet][~google-sheets]

### [**4. Draft content**](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Chapter-Lifecycle#4-draft-content)
+ [x] **October 31**: The content team has written, reviewed, and edited the chapter in the [doc][~google-doc]

### [**5. Publication**](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Chapter-Lifecycle#5-publication)
+ [x] **November 15**: The completed chapter and all required [metadata](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Authors'-Guide#metadata-to-add-at-the-top-of-your-chapters) and [figures](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Figures-Guide) are converted to markdown and submitted to [GitHub][~chapter-markdown]
- **December 1**: Target launch date 🚀

## Chapter resources

Refer to these 2021 CMS resources throughout the content creation process:

[📄 Google Docs][~google-doc] for outlining and drafting content
[🔍 SQL files][~sql-files] for committing the queries used during analysis
[📊 Google Sheets][~google-sheets] for saving the results of queries
[📝 Markdown file][~chapter-markdown] for publishing content and managing public metadata

[~google-doc]: https://docs.google.com/document/d/1107H58WlpqPOrIsRZMCK7q8h-f8rmNfLPr3BU6qGUqc/edit?usp=sharing
[~sql-files]: https://github.com/HTTPArchive/almanac.httparchive.org/tree/main/sql/2021/cms
[~google-sheets]: https://docs.google.com/spreadsheets/d/1gAJh4VcSEU6-6aQxBiTFl-7cbyHukfdhg-Iaq9y5pnc/edit?usp=sharing
[~chapter-markdown]: https://github.com/HTTPArchive/almanac.httparchive.org/tree/main/src/content/en/2021/cms.md

**Comment by jdevalk** [comment]
I’d be happy to be an author of (a part of) this chapter!

**Comment by rviscomi** [comment]
Thanks @jdevalk! Tentatively adding you as a reviewer while we gather interest from other authors.

**Comment by rviscomi** [comment]
📟 paging 2019/2020 contributors: @amedina @ernee @westonruter @mor10 @sirjonathan @alexdenning @GregBrimble

Would any of you be interested to contribute to the 2021 chapter? I'd especially like to see more 2019/2020 authors become 2021 reviewers to help ease the transition and similarly I think prior reviewers would make great 2021 authors, being familiar with the process already. And prior analysts would make excellent 2021 analysts 😁

Or is there anyone new you'd like to see?

**Comment by mor10** [comment]
I'm already pledged to the Jamstack chapter. I urge you to pursue diversity in your quest here so a broader spectrum of voices can be heard. This chapter is uniquely suited for contribution by a broad range of people from all over the world and with different sets of expertise. It would be valuable for example to see parts of the chapter contrasting CMS use and expectations in different regions of the world, multilingual and non-LTR language challenges and adoption, etc.

**Comment by saterchris** [comment]
Also happy to help out here, probably best suited as a reviewer but may also be able to assist with some authoring.

**Comment by hidde** [comment]
I would be interested in helping authoring. I am involved in a project around the accessibility of CMSes, this may be an interesting angle to cover. Legislation worldwide says website owners should have accessible sites, CMSes with accessibility features can help them get it right.

**Comment by rviscomi** [comment]
Welcome @hidde! I'll defer to @jdevalk as the content team lead for this chapter to onboard you as coauthor/reviewer as needed. Meanwhile you can get started by requesting edit access to the [draft doc](https://docs.google.com/document/d/1107H58WlpqPOrIsRZMCK7q8h-f8rmNfLPr3BU6qGUqc/edit?usp=sharing) and adding your ideas.

**Comment by logicalphase** [comment]
Checking in this evening. Thank you @hidde  👍

**Comment by hidde** [comment]
Thanks for the warm welcome, just requested access to the doc.

**Comment by rviscomi** [comment]
@jdevalk as we continue looking for an analyst to join the chapter, would you have any interest in taking on the analyst role? I know you've been familiarizing yourself with the dataset so it could work out if you have the extra time.  I was last year's analyst for this chapter so I can help get you up to speed and answer any questions if needed.

**Comment by alonkochba** [comment]
Hi, I would be happy to assist and participate in the CMS chapter as a reviewer.
I lead many of the performance efforts at Wix and the performance of CMSs across the web is very interesting for us.

**Comment by rviscomi** [comment]
⚠️ @jdevalk just checking in. This chapter seems to be pretty far behind in terms of the milestones. How can we help?

The [outline](https://docs.google.com/document/d/1107H58WlpqPOrIsRZMCK7q8h-f8rmNfLPr3BU6qGUqc/edit?usp=sharing) hasn't been started, and that puts this chapter at risk of not being able to get new metrics implemented before the July crawl starts, which is what all chapters will refer to in their analysis. You'll still have access to everything analyzed in 2019-2020, but not necessarily new metrics. Have you been working on an outline in another doc by any chance?

I'd encourage you to coordinate with the rest of your content team to immediately start brainstorming content/metrics for the outline. As of now @saterchris is the only reviewer listed in your [chapter metadata](https://github.com/HTTPArchive/almanac.httparchive.org/issues/2154#issue-868436109) but I see a few other people have also volunteered (@hidde and @alonkochba). Remember to please keep the metadata updated by adding new contributors and checking off milestones as you complete them. (it helps us track all chapters' progress at a glance)

This chapter is also missing an analyst, which is holding it back from completing Milestone 0. I'm happy to step up to help as needed here, but I'll defer to other contributors if they're available.

And if your situation has changed where you're no longer able to commit to leading the chapter, no worries, just let us know ASAP so we can make alternate plans.

Thanks for your help getting this chapter back on track!

**Comment by jdevalk** [comment]
Yeah sorry about this people. I do think I can run most of the analyses needed, but would love some help from @hidde on the outline and maybe everyone else here who has ideas on what to cover. I saw @mor10 had input / ideas on topics and would love to discuss those either here or in the Google doc.

I'll get started on an outline myself right now using the input above.

**Comment by rviscomi** [comment]
Thanks @jdevalk. Glad to hear you're able to take on the analysis work. Let me know (or ping #web-almanac-analysts) if you have any questions or need any help. I've put your name down as the team analyst in the chapter metadata and checked off Milestone 0 for you.

I've left a couple of comments in the outline. Thanks for kicking that off!

**Comment by logicalphase** [comment]
Hey @jdevalk - Can you confirm that you're good to go on gathering metrics for analysis? If so, I'd we'd like to mark item #2 as complete. Thank you again for your assistance.

**Comment by jdevalk** [comment]
I'm good to go on that!

**Comment by logicalphase** [comment]
Thanks so much. I'll mark that ask as done.

**Comment by konfirmed** [comment]
Hi, I'll like to help here if needed

**Comment by logicalphase** [comment]
@konfirmed Thank you for your interest in working on the project. Since we're many months into the process for 2021, it would be helpful to specifically what your interests are and what role you would be most interested in. The descriptions can be found under the content team table above. Cheers!

**Comment by konfirmed** [comment]
@logicalphase Depending on where help is wanted, I would like to be a reviewer.

**Comment by rviscomi** [comment]
⚠️ @jdevalk it doesn't look like there's been much progress on this chapter in a while. We're coming up on the due date for Milestone 3 (running all of the queries) but it doesn't look like you've completed Milestone 2 yet, so I just want to make sure this chapter is able to launch on time.

Let us know ASAP you need help running the queries, I'd be happy to jump in if that unblocks your progress.

**Comment by TosinArasi** [comment]
@jdevalk @rviscomi Hi guys, I would love to help out here as an analyst. I see help is needed and I have already started writing scripts on my own for this chapter.

**Comment by logicalphase** [comment]
All help is deeply appreciated. Thank you for volunteering to step up and
help us move the progress forward!

**Comment by logicalphase** [comment]
@jdevalk I need your help. We've not gotten an update from you since June, and I totally understand that life can throw curves at us. In consultation with the leads for the project today, the CMS chapter is at real peril of being closed for this year unless we can confirm participation. @TosinArasi has offered to help with the analyst tasks, which is awesome, but we need to know if you can still help. Can you still author the chapter? If you can provide an update I'd be grateful. Thanks again.

**Comment by alonkochba** [comment]
> @jdevalk I need your help. We've not gotten an update from you since June, and I totally understand that life can throw curves at us. In consultation with the leads for the project today, the CMS chapter is at real peril of being closed for this year unless we can confirm participation. @TosinArasi has offered to help with the analyst tasks, which is awesome, but we need to know if you can still help. Can you still author the chapter? If you can provide an update I'd be grateful. Thanks again.

I don't want to be biased, but IMHO this is a very important year to include the CMS chapter with the large shift in platforms performance partially due to CWV and the investment in performance, and also with the changing landscape post Covid.. Let me know if we can assist in any way. I was hoping to go deeper into performance and geographies this year, but at the very least let's use last year as a template with updated data?

**Comment by rviscomi** [comment]
@alonkochba if needed could you help with authoring? We'll give @jdevalk time to reply before any restructuring, but it'd be good to know if we have any backup options to keep the chapter on track. @saterchris are you still available to help review?

**Comment by saterchris** [comment]
Yep, still happy to help review! Probably can't commit to much authoring,
but would also be happy to brainstorm on topics and structure (a bit of
pre-reviewing) if helpful, given the tight turnaround.

**Comment by alonkochba** [comment]
> @alonkochba if needed could you help with authoring? We'll give @jdevalk time to reply before any restructuring, but it'd be good to know if we have any backup options to keep the chapter on track. @saterchris are you still available to help review?

A bit tight with the current schedule, but I think I'll should be able to author it.. will probably need analysis help, but https://github.com/HTTPArchive/almanac.httparchive.org/pull/2343 is a good start.. let's give @jdevalk another day or two and decide what to do by Monday?

**Comment by rviscomi** [comment]
⚠️ @jdevalk @saterchris @alonkochba @logicalphase @TosinArasi

Hi everyone, given that we haven't heard from @jdevalk in a while, we're going to have to move forward without him. I sincerely wish @jdevalk the best.

After speaking with @alonkochba and @logicalphase here and via Slack, I think the best course of action is to assign @alonkochba the role of content team lead. He and @logicalphase will be coauthors.

@saterchris will continue to review and we can move @jdevalk into a reviewer role if/when he returns.

@TosinArasi has kindly stepped up to help analyze the data.

I'll update the chapter [metadata](https://github.com/HTTPArchive/almanac.httparchive.org/issues/2154#issue-868436109) accordingly.

👉 @alonkochba as the new team lead, can you take command of the day-to-day logistics to get this chapter's analysis completed ASAP and get started on writing? The draft of the chapter is due in 4 weeks so things will have to move quickly.

Appreciate everyone's flexibility to make sure we can launch a CMS chapter this year!

**Comment by logicalphase** [comment]
Thanks @rviscomi! @alonkochba please let me know when we can get together on a slack chat, etc. I'm here to help take help with the remaining authoring tasks. Cheers!

**Comment by alonkochba** [comment]
Thanks, will start looking at the content this week.
I think I will start with last year's article as a template, with updated data, and if we will have time we can add more interesting breakdowns. A lot of this data is already available in the Tech Report, so just need to write about it.

I also want to use some of the newer metrics you included @rviscomi  (JS size, image size etc.)

@logicalphase let's try to chat this week, I'll open #web-almanac-cms now - I'm in Israel but we'll try to sync across timezones :)

**Comment by logicalphase** [comment]
Done. Left message there. 👍

**Comment by rviscomi** [comment]
Reopening until we complete the editing

**Comment by rviscomi** [comment]
@alonkochba @logicalphase @saterchris @jdevalk @TosinArasi

🎉 This chapter is fully written, reviewed, edited, and ready to be launched on Wednesday! **Thank you** to all of the contributors who put in the time and effort to make this a great chapter.

When you get 5 minutes, I'd really appreciate if you could fill out our [contributor survey](https://forms.gle/VRzHPTyWxuwa67vF7) to tell us (the project leads) about your experience. It's super helpful to hear what went well or what could be improved for next time. 🙏 

Congratulations and thank you all again. I'm excited for this to launch soon!
