### ISSUE TITLE
Page Weight 2021

### ISSUE THREAD

**Issue by rviscomi** [HTTPArchive/almanac.httparchive.org#2157]
# Part IV Chapter 19: Page Weight

![Page Weight illustration](https://raw.githubusercontent.com/HTTPArchive/almanac.httparchive.org/main/src/static/images/2019/page-weight/hero_lg.jpg)

If you're interested in contributing to the Page Weight chapter of the 2021 Web Almanac, please reply to this issue and indicate which role or roles best fit your interest and availability: [author](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Authors'-Guide), [reviewer](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Reviewers'-Guide), [analyst](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Analysts'-Guide), and/or [editor](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Editors'-Guide).

## Content team

| Lead | Authors | Reviewers | Analysts | Editors | Coordinator |
| --- | ------- | --------- | -------- | ------- | -- |
| @logicalphase | @logicalphase | @siakaramalegos | @jessthebp | @RMHolmlund | @rviscomi |

<details>
<summary><b>Expand for more information about each role</b></summary>

- The **[content team lead](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Content-Team-Leads'-Guide)** is the chapter owner and responsible for setting the scope of the chapter and managing contributors' day-to-day progress.
- **[Authors](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Authors'-Guide)** are subject matter experts and lead the content direction for each chapter. Chapters typically have one or two authors. Authors are responsible for planning the outline of the chapter, analyzing stats and trends, and writing the annual report.
- **[Reviewers](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Reviewers'-Guide)** are also subject matter experts and assist authors with technical reviews during the planning, analyzing, and writing phases.
- **[Analysts](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Analysts'-Guide)** are responsible for researching the stats and trends used throughout the Almanac. Analysts work closely with authors and reviewers during the planning phase to give direction on the types of stats that are possible from the dataset, and during the analyzing/writing phases to ensure that the stats are used correctly.
- **[Editors](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Editors'-Guide)** are technical writers who have a penchant for both technical and non-technical content correctness. Editors have a mastery of the English language and work closely with authors to help wordsmith content and ensure that everything fits together as a cohesive unit.
- The **[section coordinator](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Section-Leads'-Guide)** is the overall owner for all chapters within a section like "User Experience" or "Page Content" and helps to keep each chapter on schedule.

_Note: The time commitment for each role varies by the chapter's scope and complexity as well as the number of contributors._

For an overview of how the roles work together at each phase of the project, see the [Chapter Lifecycle](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Chapter-Lifecycle) doc.
</details>

### [**0. Form the content team**](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Chapter-Lifecycle#0-create-content-team)
+ [x] **May 31**: The content team has at least one author, reviewer, and analyst

### [**1. Plan content**](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Chapter-Lifecycle#1-plan-content)
+ [x] **June 15** The content team has completed the chapter outline in the [draft doc][~google-doc]

### [**2. Gather data**](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Chapter-Lifecycle#2-gather-data)
+ [x] **June 30**: Analysts have added all necessary [custom metrics](https://github.com/HTTPArchive/legacy.httparchive.org/blob/master/custom_metrics/README.md) and drafted a PR ([example](https://github.com/HTTPArchive/almanac.httparchive.org/pull/1087)) to track query progress
- **July 1 - 31**: HTTP Archive runs the July crawl

### [**3. Validate results**](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Chapter-Lifecycle#3-validate-results)
+ [x] **September 30**: Analysts have queried all metrics and saved the output to the [results sheet][~google-sheets]

### [**4. Draft content**](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Chapter-Lifecycle#4-draft-content)
+ [x] **October 31**: The content team has written, reviewed, and edited the chapter in the [doc][~google-doc]

### [**5. Publication**](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Chapter-Lifecycle#5-publication)
+ [x] **November 15**: The completed chapter and all required [metadata](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Authors'-Guide#metadata-to-add-at-the-top-of-your-chapters) and [figures](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Figures-Guide) are converted to markdown and submitted to [GitHub][~chapter-markdown]
- **December 1**: Target launch date 🚀

## Chapter resources

Refer to these 2021 Page Weight resources throughout the content creation process:

[📄 Google Docs][~google-doc] for outlining and drafting content
[🔍 SQL files][~sql-files] for committing the queries used during analysis
[📊 Google Sheets][~google-sheets] for saving the results of queries
[📝 Markdown file][~chapter-markdown] for publishing content and managing public metadata

[~google-doc]: https://docs.google.com/document/d/1FP4KY_xwFUBiiYXPXzasIzbiDYymnp1MqFc1kdMmZ68/edit?usp=sharing
[~sql-files]: https://github.com/HTTPArchive/almanac.httparchive.org/tree/main/sql/2021/page-weight
[~google-sheets]: https://docs.google.com/spreadsheets/d/1XApPAC8m2jLJR3Ok1yAoc9PzAFtq-Z41LoakXHUVeag/edit?usp=sharing
[~chapter-markdown]: https://github.com/HTTPArchive/almanac.httparchive.org/tree/main/src/content/en/2021/page-weight.md

**Comment by siakaramalegos** [comment]
Hi, I'd be interested in being an author. I write and speak on performance as well as perform contract work for various companies on performance. You can learn more about me on my website (including articles, talks, and workshops): https://sia.codes/

If I'm not chosen as an author on this or any other page, I'm happy to be a reviewer. Thanks for your consideration.

**Comment by rviscomi** [comment]
📟 paging 2019/2020 contributors: @khempenius @tammyeverts @paulcalvano @flowlabs @henrihelvetica @borisschapira

Would any of you be interested to contribute to the 2021 chapter? I'd especially like to see more 2019/2020 authors become 2021 reviewers to help ease the transition and similarly I think prior reviewers would make great 2021 authors, being familiar with the process already. And prior analysts would make excellent 2021 analysts 😁

Or is there anyone new you'd like to see?

**Comment by logicalphase** [comment]
I'm in full remission and back at work full time. I'd like to author this one. It fits with my work on web sustainability and performance. If you agree, sign me up. Thanks.

**Comment by jessthebp** [comment]
Hi, I'd be interested in working on this chapter as a reviewer or analyst.

**Comment by rviscomi** [comment]
@logicalphase so glad to hear you're doing better and thanks for your interest in authoring this chapter! As the content team lead, you'll be responsible for the scope and direction of the chapter and keeping it on schedule. We automatically monitor the staffing and progress of each chapter based on the state of the [initial comment][~chapter-metadata] so please keep that updated as you add new contributors and meet each milestone.

We've created a [Google Doc][~google-doc] for this chapter, which you're encouraged to use to collaborate with the content team on the initial outline, metrics, and ultimately the final draft.

Next steps for this chapter are:

- Due **May 31**: Complete [Milestone 0: Form the content team](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Chapter-Lifecycle#0-create-content-team)—you can check this off now since you've already got at least one author, reviewer, and analyst ✨ 
- Due **June 15**: Get started on [Milestone 1: Plan content](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Chapter-Lifecycle#1-plan-content) by brainstorming some content ideas in the [doc][~google-doc] (you may need to request edit access, cc @boosef @Navaneeth-akam @akshay-ranganath @IsaacSichangi)

There's not currently a section coordinator for this chapter, so I'll be periodically checking in with you directly to make sure the chapter is staying on schedule. Reach out here in this issue if you have any questions about the process.

More information about the [content team lead](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Content-Team-Leads'-Guide) and [author](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Authors'-Guide) roles and responsibilities are available for reference in the wiki if needed.

To anyone else interested in contributing to this chapter, please comment below to join the team!


[~chapter-metadata]: https://github.com/HTTPArchive/almanac.httparchive.org/issues/2157#issue-868436240
[~google-doc]: https://docs.google.com/document/d/1FP4KY_xwFUBiiYXPXzasIzbiDYymnp1MqFc1kdMmZ68/edit?usp=sharing

**Comment by logicalphase** [comment]
Perfect. I'm reaching out to a few people also working in this area, and will report back. Excited about 2021 almanac as always. Thanks again, Rick. Look forward to working with and on it.

**Comment by siakaramalegos** [comment]
Just wanted to note that I'm authoring a different chapter so I'll won't be authoring this one (please volunteer to author!). @rviscomi , I can still review if it's still needed and the workload is timed ok with authoring.

**Comment by logicalphase** [comment]
You can add @RMHolmlund as editor. She's awesome with content 🙂

**Comment by rviscomi** [comment]
@logicalphase as the lead, you've got control of this issue now and you should have edit access, so feel free to modify https://github.com/HTTPArchive/almanac.httparchive.org/issues/2157#issue-868436240 as you get new contributors and also as you meet new milestones. For example, you can add @RMHolmlund to the Editors column and check off Milestone 0.

**Comment by logicalphase** [comment]
Got it. Thanks again.

**Comment by logicalphase** [comment]
Greetings @siakaramalegos, @jessthebp, and @RMHolmlund , and thank you for joining the Page Weight team. I look forward to working with each of you. I'll send an update in day or two on next steps. In the meantime please let me know if you have questions or if I can assist. Cheers.

**Comment by rviscomi** [comment]
Hi @logicalphase just checking in to help keep the chapter on track. One tip: coordinate with the rest of the content team to request edit access to the [doc](https://docs.google.com/document/d/11Aoamljwb90T8En6o0kVDWYJQhX6EKIV6dyUwqXUgZw/edit?usp=sharing) and start brainstorming an outline for the chapter. We're looking to have an outline completed by June 15.

Also, thank you for being the first chapter to _actually check off_ Milestone 0! 😄 🙌

**Comment by rviscomi** [comment]
Sounds great! I'll check in on your progress again in about a week but feel free to ping me if you have any questions/concerns.

**Comment by logicalphase** [comment]
👍

**Comment by logicalphase** [comment]
In looking at the 2020 Page Weight product, I think it touches on all the right data points. I may add some analysis to the previous work. If anyone on the team can take some time to review https://almanac.httparchive.org/en/2020/page-weight and offer any additional thoughts on shaping the next release I'd be grateful. My plan is to to complete milestone 1 over the weekend and move on to the next. That keeps us on schedule given Google IO this week. Thank you.

**Comment by siakaramalegos** [comment]
In the Performance Chapter, we were thinking of looking to see if there is a correlation between page weight and performance (Core Web Vitals) - this is our tracking issue for now: https://github.com/siakaramalegos/performance-almanac/issues/15

Let me know if you're interested in covering it instead, and then we could point to your chapter.

**Comment by logicalphase** [comment]
Hi @siakaramalegos  - I'm fine with adding content that can be linked to by the performance product. Good to go.

**Comment by rviscomi** [comment]
@logicalphase the [outline](https://docs.google.com/document/d/1FP4KY_xwFUBiiYXPXzasIzbiDYymnp1MqFc1kdMmZ68/edit?usp=sharing) is looking good so far! I've left a couple of comments. @siakaramalegos @jessthebp @RMHolmlund be sure to also request edit access to the doc so you can leave your suggestions/feedback. As a reminder the chapter outline should be completed by **June 15** to leave enough time for changes to the test pipeline as needed before the July 1 crawl begins, but it looks like you're on track to finish early 🚀

**Comment by logicalphase** [comment]
THank you, @rviscomi. Just to bring  @siakaramalegos @jessthebp @RMHolmlund further up to date, I  completed the draft of the [outline](https://docs.google.com/document/d/1FP4KY_xwFUBiiYXPXzasIzbiDYymnp1MqFc1kdMmZ68/edit?usp=sharing) for 2021. Now, I really need your help in the form of suggestions, proposed changes, and questions you may have. Your feedback is important. Ideally, I'd like to complete this milestone this weekend at the latest. So, if you would be so kind as to give the outline linked to above, and post your comments, we can close this milestone and get a welcomed head start on analysis. Thank you all again.

**Comment by rviscomi** [comment]
Thanks for completing the chapter outline on time @logicalphase! 🏆

**Comment by logicalphase** [comment]
Hey @jessthebp - based on the criteria set forth in item #1 - the outline document. Can you take a quick look to make sure you're good to go on custom metrics, etc. for analysis. If so I'd like to mark item #3 complete. Thanks again for your help.

**Comment by rviscomi** [comment]
👋 Hi @logicalphase @jessthebp, just checking in on the chapter progress. How is the analysis coming along?

**Comment by logicalphase** [comment]
Hi Rick,

Admittedly, I've gotten behind this past couple of weeks implementing org changes with acquisition of company and today is another stuffed day of meetings. I'm hoping @jessthebp can help pull me along on the data issues outstanding, so I can step back in on Wednesday when done here and forge ahead.

**Comment by jessthebp** [comment]
Hi, @logicalphase - I'm working on the analysis this week and will keep you updated.

**Comment by logicalphase** [comment]
Thanks. Much appreciated!

**Comment by rviscomi** [comment]
Hi @logicalphase @jessthebp any updates? A good first step would be to draft the analysis PR. I noticed the Milestone 2 checkbox was checked, but I don't see the draft PR open so I went ahead and unchecked it.

**Comment by rviscomi** [comment]
@logicalphase @siakaramalegos @jessthebp @RMHolmlund

🎉 This chapter is fully written, reviewed, edited, and ready to be launched on Wednesday! **Thank you** to all of the contributors who put in the time and effort to make this a great chapter.

When you get 5 minutes, I'd really appreciate if you could fill out our [contributor survey](https://forms.gle/VRzHPTyWxuwa67vF7) to tell us (the project leads) about your experience. It's super helpful to hear what went well or what could be improved for next time. 🙏 

Congratulations and thank you all again. I'm excited for this to launch soon!
