### ISSUE TITLE
CDN 2021

### ISSUE THREAD

**Issue by rviscomi** [HTTPArchive/almanac.httparchive.org#2159]
# Part IV Chapter 21: CDN

![CDN illustration](https://raw.githubusercontent.com/HTTPArchive/almanac.httparchive.org/main/src/static/images/2019/cdn/hero_lg.jpg)

If you're interested in contributing to the CDN chapter of the 2021 Web Almanac, please reply to this issue and indicate which role or roles best fit your interest and availability: [author](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Authors'-Guide), [reviewer](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Reviewers'-Guide), [analyst](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Analysts'-Guide), and/or [editor](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Editors'-Guide).

## Content team

| Lead | Authors | Reviewers | Analysts | Editors | Coordinator |
| --- | ------- | --------- | -------- | ------- | -- |
| @Navaneeth-akam | @Navaneeth-akam | @boosef @jzyang @keane234 | @paulcalvano | @jzyang | @rviscomi |

<details>
<summary><b>Expand for more information about each role</b></summary>

- The **[content team lead](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Content-Team-Leads'-Guide)** is the chapter owner and responsible for setting the scope of the chapter and managing contributors' day-to-day progress.
- **[Authors](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Authors'-Guide)** are subject matter experts and lead the content direction for each chapter. Chapters typically have one or two authors. Authors are responsible for planning the outline of the chapter, analyzing stats and trends, and writing the annual report.
- **[Reviewers](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Reviewers'-Guide)** are also subject matter experts and assist authors with technical reviews during the planning, analyzing, and writing phases.
- **[Analysts](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Analysts'-Guide)** are responsible for researching the stats and trends used throughout the Almanac. Analysts work closely with authors and reviewers during the planning phase to give direction on the types of stats that are possible from the dataset, and during the analyzing/writing phases to ensure that the stats are used correctly.
- **[Editors](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Editors'-Guide)** are technical writers who have a penchant for both technical and non-technical content correctness. Editors have a mastery of the English language and work closely with authors to help wordsmith content and ensure that everything fits together as a cohesive unit.
- The **[section coordinator](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Section-Leads'-Guide)** is the overall owner for all chapters within a section like "User Experience" or "Page Content" and helps to keep each chapter on schedule.

_Note: The time commitment for each role varies by the chapter's scope and complexity as well as the number of contributors._

For an overview of how the roles work together at each phase of the project, see the [Chapter Lifecycle](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Chapter-Lifecycle) doc.
</details>

### [**0. Form the content team**](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Chapter-Lifecycle#0-create-content-team)
+ [x] **May 31**: The content team has at least one author, reviewer, and analyst

### [**1. Plan content**](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Chapter-Lifecycle#1-plan-content)
+ [x] **June 15** The content team has completed the chapter outline in the [draft doc][~google-doc]

### [**2. Gather data**](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Chapter-Lifecycle#2-gather-data)
+ [x] **June 30**: Analysts have added all necessary [custom metrics](https://github.com/HTTPArchive/legacy.httparchive.org/blob/master/custom_metrics/README.md) and drafted a PR ([example](https://github.com/HTTPArchive/almanac.httparchive.org/pull/1087)) to track query progress
- **July 1 - 31**: HTTP Archive runs the July crawl

### [**3. Validate results**](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Chapter-Lifecycle#3-validate-results)
+ [x] **September 30**: Analysts have queried all metrics and saved the output to the [results sheet][~google-sheets]

### [**4. Draft content**](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Chapter-Lifecycle#4-draft-content)
+ [x] **October 31**: The content team has written, reviewed, and edited the chapter in the [doc][~google-doc]

### [**5. Publication**](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Chapter-Lifecycle#5-publication)
+ [x] **November 15**: The completed chapter and all required [metadata](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Authors'-Guide#metadata-to-add-at-the-top-of-your-chapters) and [figures](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Figures-Guide) are converted to markdown and submitted to [GitHub][~chapter-markdown]
- **December 1**: Target launch date 🚀

## Chapter resources

Refer to these 2021 CDN resources throughout the content creation process:

[📄 Google Docs][~google-doc] for outlining and drafting content
[🔍 SQL files][~sql-files] for committing the queries used during analysis
[📊 Google Sheets][~google-sheets] for saving the results of queries
[📝 Markdown file][~chapter-markdown] for publishing content and managing public metadata

[~google-doc]: https://docs.google.com/document/d/1OJBK345mSYsWxm0dhvMVgGY0pfUqC8jUjmvgwK8I3Fw/edit?usp=sharing
[~sql-files]: https://github.com/HTTPArchive/almanac.httparchive.org/tree/main/sql/2021/cdn
[~google-sheets]: https://docs.google.com/spreadsheets/d/1DL7Pn1vbBwYmQZ5JPAjD69oCOvUidbuoNvdrw--j00U/edit?usp=sharing
[~chapter-markdown]: https://github.com/HTTPArchive/almanac.httparchive.org/tree/main/src/content/en/2021/cdn.md

**Comment by boosef** [comment]
I can help review and/or edit! :)

**Comment by Navaneeth-akam** [comment]
I would like to be an author/co-author for this chapter

**Comment by rviscomi** [comment]
Hi @Navaneeth-akam thanks for your interest in this chapter! I've tentatively put you down as a reviewer as we wait for more interest from authors. Could you tell us about your experience with the CDN space?

**Comment by jzyang** [comment]
I'd like to sign up for reviewer and editor.

**Comment by rviscomi** [comment]
📟 paging 2019 contributors: @andydavies @colinbendell @yoavweiss @paulcalvano @pmeenan @raghuramakrishnan71 

Would any of you be interested to contribute to the 2021 chapter? I'd especially like to see more 2019/2020 authors become 2021 reviewers to help ease the transition and similarly I think prior reviewers would make great 2021 authors, being familiar with the process already. And prior analysts would make excellent 2021 analysts 😁

Or is there anyone new you'd like to see?

**Comment by rviscomi** [comment]
@ianand @boosef were either of you interested in authoring this chapter?

**Comment by rviscomi** [comment]
@ianand ok sounds great. Of the two chapters, [Jamstack](https://github.com/HTTPArchive/almanac.httparchive.org/issues/2156) is the only other one in urgent need of an author. The [Performance](https://github.com/HTTPArchive/almanac.httparchive.org/issues/2148) chapter is pretty well staffed.

**Comment by Navaneeth-akam** [comment]
> Hi @Navaneeth-akam thanks for your interest in this chapter! I've tentatively put you down as a reviewer as we wait for more interest from authors. Could you tell us about your experience with the CDN space?

Hi @rviscomi , I've been in Akamai (leader in CDN technology) for close to 10yrs now and have worked as an implementation specialist for Akamai's CDN products ( for 4yrs), partly worked for the cloud security space in Akamai and also as a pre-sales engineer (for 5yrs). During this time, i have interacted with other players in CDN space (like Amazon Cloudfront, Cloudflare, BitGravity etc.,), the different architectures of CDN setup (centralized v/s distributed), experienced/involved in the evolution of CDN landscape from a simple "cache and deliver" network to a cloud security and serverless edge compute platform....which is where most CDN platforms today are evolving into and becoming an integral part of application architecture.

**Comment by rviscomi** [comment]
@Navaneeth-akam thanks for your interest in authoring this chapter! As the content team lead, you'll be responsible for the scope and direction of the chapter and keeping it on schedule. We automatically monitor the staffing and progress of each chapter based on the state of the [initial comment][~chapter-metadata] so please keep that updated as you add new contributors and meet each milestone.

We've created a [Google Doc][~google-doc] for this chapter, which you're encouraged to use to collaborate with the content team on the initial outline, metrics, and ultimately the final draft.

Next steps for this chapter are:

- Due **May 31**: Complete [Milestone 0: Form the content team](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Chapter-Lifecycle#0-create-content-team) by finding someone to be the analyst
- Due **June 15**: Get started on [Milestone 1: Plan content](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Chapter-Lifecycle#1-plan-content) by brainstorming some content ideas in the [doc][~google-doc] (you may need to request edit access)

There's not currently a section coordinator for this chapter, so I'll be periodically checking in with you directly to make sure the chapter is staying on schedule. Reach out here in this issue if you have any questions about the process.

More information about the [content team lead](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Content-Team-Leads'-Guide) and [author](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Authors'-Guide) roles and responsibilities are available for reference in the wiki if needed.

To anyone else interested in contributing to this chapter, please comment below to join the team!


[~chapter-metadata]: https://github.com/HTTPArchive/almanac.httparchive.org/issues/2159#issue-868436342
[~google-doc]: https://docs.google.com/document/d/1OJBK345mSYsWxm0dhvMVgGY0pfUqC8jUjmvgwK8I3Fw/edit?usp=sharing

**Comment by rviscomi** [comment]
@Navaneeth-akam @boosef @jzyang please be sure to request edit access to the [CDN chapter doc](https://docs.google.com/document/d/1OJBK345mSYsWxm0dhvMVgGY0pfUqC8jUjmvgwK8I3Fw/edit?usp=sharing) and begin outlining the chapter content. The due date to have the outline complete is **June 15** to ensure that we have enough time to update the testing pipeline with any additional metrics as needed before the crawl begins on July 1.

@Navaneeth-akam I've also sent you an invite to join the Almanac team on GitHub. You can accept by visiting https://github.com/HTTPArchive. Membership gives you the ability to update the [top comment](https://github.com/HTTPArchive/almanac.httparchive.org/issues/2159#issue-868436342) to keep the list of contributors and completed milestones up to date. Doing so helps us monitor each chapter's progress at a glance in #2179. 🙏  

@HTTPArchive/analysts this chapter is also in need of an analyst, any help would be greatly appreciated!

**Comment by Navaneeth-akam** [comment]
@rviscomi Thanks for the details. I think I have received the edit access for Google Doc. Will be adding the list of topics for this chapter. I see that we are still missing an analyst for this chapter. While I'm trying to see if anyone who has been analyst before can help with it, it would be great if you have any suggestions here.

**Comment by jzyang** [comment]
I've already checked my access earlier and put my name down for Reviewer, I
believe.  :)

**Comment by colinbendell** [comment]
I'm happy to be a reviewer as well.

**Comment by rviscomi** [comment]
Hey @Navaneeth-akam, could you give us status update on the outline? It's looking like there are a few good topics as of now, but I'm not sure if you're still working on it. We were hoping to have it done by today. Could you check off Milestone 1 [above](https://github.com/HTTPArchive/almanac.httparchive.org/issues/2159#issue-868436342) when you're satisfied with it? Thanks!

**Comment by rviscomi** [comment]
@Navaneeth-akam just following up on the state of the outline. How's it going, and is there anything we can do to help?

**Comment by rviscomi** [comment]
@HTTPArchive/analysts this is the only chapter still without any analysts. Is anyone able to take this one on? 🙏

**Comment by keane234** [comment]
Hi, I can helo for the review too.

**Comment by Navaneeth-akam** [comment]
@rviscomi : I had a chat with @paulcalvano few weeks back and he will help us with analysis on this. I have also updated few milestones based on current progress

**Comment by Navaneeth-akam** [comment]
> Hi, I can helo for the review too.

Thanks @keane234 !!! Will update you in the list of reviewers

**Comment by rviscomi** [comment]
👋 Hi @Navaneeth-akam @paulcalvano, just checking in on the chapter progress. How is the analysis coming along?

**Comment by rviscomi** [comment]
Unchecking Milestone 2 until the draft PR is created

**Comment by rviscomi** [comment]
@Navaneeth-akam @paulcalvano adding the ASAP label back since Milestone 2 is long overdue (creating the draft PR was due on June 30). Any update on the analysis?

Also, @Navaneeth-akam do you still need additional contributors? If not you can remove the "help wanted" labels from the issue.

**Comment by rviscomi** [comment]
⛔ @Navaneeth-akam @paulcalvano this chapter is at serious risk of missing the launch. The analysis work for Milestone 3 was due yesterday but I'm not seeing any signs that it was ever started. I don't see a plausible way for this chapter to meet Milestone 4 (writing, reviewing, and editing the chapter) by the October 31 deadline unless the analysis is _completely done_ by the end of next week. Are you both able to commit to that timeline? Otherwise we may need to close this chapter and focus on getting the viable chapters ready for launch, which I would hate to do.

**Comment by paulcalvano** [comment]
Hey @rviscomi , @Navaneeth-akam .   I'll be working on the analysis for this today/tomorrow, so should have some progress to share shortly.   Sorry for the delay!

**Comment by jzyang** [comment]
@rviscomi  Well, I reached out to @Navaneeth-akam in June about this over Slack, after seeing no movement.  He said he'd have something mid-June but I never heard back from him again with any other updates.  I've checked back on the doc pages in August but I haven't seen any movements.  I'm still available to help review this and other chapters, but nothing I've signed up for seemed to have texts available for review.  @paulcalvano I don't think you indicated you had time to write anything this year though.  Is that still true?

**Comment by paulcalvano** [comment]
@jzyang  - I synced up with @Navaneeth-akam last week and we reviewed the queries that I'd be rerunning from 2019, and some new ones I needed to write.  I've been the blocker on getting the analysis done - so apologies for that.   Navaneeth is still planning on writing the chapter.  I'm happy to help out wherever needed too.

**Comment by jzyang** [comment]
@paulcalvano good to hear from you!  Yeah, let me know when you need my services.  I'm on-call next week, starting Monday, so I will be busy but I should be available again the Monday after next.

**Comment by rviscomi** [comment]
Thank you both for the updates, and I'm glad to see the PR open now to track the queries. I'm optimistic that we can get this chapter back on track in time for launch.

**Comment by jzyang** [comment]
Oh sorry, I just saw this.  I already started making comments and some
changes to the doc.  I'm planning to finish my first round by end of day.
I'm available for a call but I'm on PST time.  I guess I can do Tues
8:30-9:30AM PST and 10:30AM-12PM PST (I believe that 9-10PM and
11PM-12:30AM IST) and I'm free on Wed from 9-10AM PST and 11AM-12PM PST.
Tuesday I must end exactly at 9:30AM for a team meeting.  I prefer Wed
though.  I don't relish waking up at 7:30AM on Tues to get ready for work.

**Comment by jzyang** [comment]
Oh, and I guess I'm also available after 8PM PST Tuesday (since I'm at the
office that day and that's usually when I get home) and I'm available after
6PM on Wednesday.

**Comment by Navaneeth-akam** [comment]
Thanks @jzyang ! I have to write one more section in the google doc. I'll be doing during evening hours in India. In the meanwhile, you can review and edit rest of the sections.
@boosef @keane234 : you guys can also review and add your comments in the google doc. If you have issues accessing the doc, let me know.

**Comment by Navaneeth-akam** [comment]
@jzyang : I have reviewed your comments and edits. The draft has been updated with the same. Would be helpful if you can verify the edits.
Also, i have added the 2 sections to the draft (HTTP/2 and HTTP/3 Adoption and Conclusion). Please review the same.

**Comment by boosef** [comment]
@Navaneeth-akam I don't have edit access to the doc yet, so I'll leave some of my feedback here - I have a few minor suggestions that I can make in-line once the doc permissions have been modified. :) 

- I think it would be nice to have a section on how CDNs are still relevant even though most cloud platforms now have global pops, autoscale functionality etc. - perhaps pointing to the stats we have on perf, with and without CDNs (where can I find this data, btw? It's mentioned in the sheet, but I don't know where the graphs/tables actually are) would help here.
- There's mention of Brotli and how CDNs help with with image and video management, serverless compute and web security, but no mention of _why_ or what value users get from using that kind of functionality at the edge. Is this out of scope for the doc?
- Along with TLS1.3 and h2, worth talking about how helpful CDNs have been in IPv6 adoption also.

**Comment by boosef** [comment]
Ok, yay. I now have access! (thanks @rviscomi 😁)

@Navaneeth-akam - I've gone through about half the document for now, will do the rest tomorrow. I've made all my edits in "Suggesting" mode, so I'm sorry if the number of comments seem a little overwhelming! Most of them are very minor edits, but I figured I'd start with the proofreading while going through the content. :) 

Something I noticed was that the order in which topics are covered doesn't quite match what's mentioned in the **Outline** page - I know you're still working on the doc though, so let's chat and see if things need to be reordered/added once you're done? Miiight just be easier to do that part on a call, but happy to do this async also if that's more convenient for everyone. :)

**Comment by Navaneeth-akam** [comment]
> @Navaneeth-akam I don't have edit access to the doc yet, so I'll leave some of my feedback here - I have a few minor suggestions that I can make in-line once the doc permissions have been modified. :)
> 
> * I think it would be nice to have a section on how CDNs are still relevant even though most cloud platforms now have global pops, autoscale functionality etc. - perhaps pointing to the stats we have on perf, with and without CDNs (where can I find this data, btw? It's mentioned in the sheet, but I don't know where the graphs/tables actually are) would help here.
> * There's mention of Brotli and how CDNs help with with image and video management, serverless compute and web security, but no mention of _why_ or what value users get from using that kind of functionality at the edge. Is this out of scope for the doc?
> * Along with TLS1.3 and h2, worth talking about how helpful CDNs have been in IPv6 adoption also.

@boosef : Thanks for your suggestions. Here are my responses:
1. Since the crawling for web almanac is executed using a single node in US west coast, its a single point test if we have to measure performance. This off course has its limitations and the results may not be true representation of the performance impact each CDN is adding. Hence, to be fair and neutral on this, we are not including any performance data.
2. Topics like serverless compute, Image and video management, web security are areas which we found is difficult to get info on by looking at only request-response parameters. The data we have today is based on the crawls that were executed. That limits the scope of what we can write about and how much info CDN providers are able to expose in public requests. For contect, we did explore option to send CDN specific debug headers in request to expose some data in response, but not every CDN supports such mechanism. Over that, for security reasons CDN's do block such attempts without the right authorizations. Hence, we dropped it.
3. Brotli assessment is in the works. I'm waiting for analysis data to come in to write about it. Thats work in progress and will be covered :)
4. Good suggestion on IPv6 adoption analysis. Totally missed this one. I'm checking with Paul (analyst) if we have the data for this. WIll keep you posted on this

**Comment by Navaneeth-akam** [comment]
> Ok, yay. I now have access! (thanks @rviscomi 😁)
> 
> @Navaneeth-akam - I've gone through about half the document for now, will do the rest tomorrow. I've made all my edits in "Suggesting" mode, so I'm sorry if the number of comments seem a little overwhelming! Most of them are very minor edits, but I figured I'd start with the proofreading while going through the content. :)
> 
> Something I noticed was that the order in which topics are covered doesn't quite match what's mentioned in the **Outline** page - I know you're still working on the doc though, so let's chat and see if things need to be reordered/added once you're done? Miiight just be easier to do that part on a call, but happy to do this async also if that's more convenient for everyone. :)

Thanks for reviewing @boosef! I'll go thru the suggestions in google doc. Yes, the order of the topic may not match the outline I came up with. Quite a few topics went out of contention after I outlined what I wanted to cover and few other topics has technical feasibility challenges. Hence, you see this discrepancy :)

**Comment by Navaneeth-akam** [comment]
@paulcalvano : let me know once we the results for the last set of queries?

@rviscomi : we are in the final leg of the draft. The current draft is reviewed by @boosef and @jzyang. Their suggestions and recommendations were discussed and incorporated. Once the last few results of queries are in place, I'll draft the last few pieces for reviewing and editing.

**Comment by Navaneeth-akam** [comment]
@jzyang @boosef : I have drafted a new section in CDN Chapter for "Brotli Adoption. Please review and comment on the same.

**Comment by jzyang** [comment]
@Naveen Sharma ***@***.***> should we be reviewing in
the Google doc or should be do it in the git?  I suggest git so we can get
you closer to completion.

**Comment by jzyang** [comment]
Oh darn, I tagged the wrong person.  @Navaneeth-akam
<https://github.com/Navaneeth-akam> see previous comment.  Sorry for the
confusion @Naveen Sharma ***@***.***> , please ignore!

**Comment by Navaneeth-akam** [comment]
@jzyang : lets finish off the content in Google doc as i'm more comfortable modifying and editing it there. Once the doc is finalized, then we can submit it to git in one go

**Comment by jzyang** [comment]
@Navaneeth-akam <https://github.com/Navaneeth-akam> done.

**Comment by Navaneeth-akam** [comment]
@jzyang @boosef : More edits and corrections made to the google doc draft. There were few charts that needed some correction and @paulcalvano helped finish them today. Do review and edit the same.
I might have to do one more correction since one of the chart data might change. Will keep you guys posted on it

**Comment by Navaneeth-akam** [comment]
@jzyang : thanks for reviewing and editing. I have looked at your corrections and accepted them as required.
@boosef : let me know once you do a final review of the draft.
@paulcalvano : I know you are our analyst, but it would be great if you can read the draft and give me your thoughts :)
@rviscomi : I'm happy with the content for CDN chapter. When we get final comments from @boosef , we should be good to merge this for publishing.

**Comment by rviscomi** [comment]
Sounds good @Navaneeth-akam. Do you want to start the markdown conversion and finish the review in the GitHub PR?

**Comment by Navaneeth-akam** [comment]
> Sounds good @Navaneeth-akam. Do you want to start the markdown conversion and finish the review in the GitHub PR?

Yeah, we can do that. Let me know how we can go about this

**Comment by rviscomi** [comment]
@Navaneeth-akam @boosef @jzyang @keane234 @paulcalvano @jzyang

🎉 This chapter is fully written, reviewed, edited, and ready to be launched on Wednesday! **Thank you** to all of the contributors who put in the time and effort to make this a great chapter.

When you get 5 minutes, I'd really appreciate if you could fill out our [contributor survey](https://forms.gle/VRzHPTyWxuwa67vF7) to tell us (the project leads) about your experience. It's super helpful to hear what went well or what could be improved for next time. 🙏 

Congratulations and thank you all again. I'm excited for this to launch soon!

**Comment by Navaneeth-akam** [comment]
Thanks @jzyang @boosef and @paulcalvano for your help and support in getting the CDN chapter completed in time for Web Almanac 2021 launch. I enjoyed authoring my first ever chapter in Web Almanac and with your support i learnt a lot along the way.
Hope to connect with you guys beyond Web Almanac. Stay safe and enjoy the upcoming holidays :)
