### ISSUE TITLE
table of contents lost when desktop resolution?

### ISSUE THREAD

**Issue by MSakamaki** [HTTPArchive/almanac.httparchive.org#216]
I saw the latest master  (f5cd6cc055fb94cb38da0925b707ac23424c336b) .

Apparently, the table of contents in the footer seems to disappear only in desktop mode.
Should I fix this to show up on my desktop mode?

<img width="1005" alt="スクリーンショット 2019-10-22 11 39 35" src="https://user-images.githubusercontent.com/2183053/67256304-48472b80-f4c1-11e9-9ca5-29969856243f.png">
<img width="476" alt="スクリーンショット 2019-10-22 11 39 25" src="https://user-images.githubusercontent.com/2183053/67256307-4bdab280-f4c1-11e9-9abe-31c256ba6611.png">

**Comment by rviscomi** [comment]
Yes, good catch! ToC should exist in both header/footer for desktop/mobile.

Let's move the HTTP Archive logo to the second line to make room for the ToC link on the first line. Hopefully this doesn't require any additional media queries in case things overflow for certain viewport widths.

**Comment by MSakamaki** [comment]
All right!
Take issues when # 210 settles down.
