### ISSUE TITLE
Compression 2021

### ISSUE THREAD

**Issue by rviscomi** [HTTPArchive/almanac.httparchive.org#2160]
# Part IV Chapter 22: Compression

![Compression illustration](https://raw.githubusercontent.com/HTTPArchive/almanac.httparchive.org/main/src/static/images/2019/compression/hero_lg.jpg)

If you're interested in contributing to the Compression chapter of the 2021 Web Almanac, please reply to this issue and indicate which role or roles best fit your interest and availability: [author](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Authors'-Guide), [reviewer](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Reviewers'-Guide), [analyst](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Analysts'-Guide), and/or [editor](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Editors'-Guide).

## Content team

| Lead | Authors | Reviewers | Analysts | Editors | Coordinator |
| --- | ------- | --------- | -------- | ------- | -- |
| @lvandeve | @lvandeve @jyrkialakuijala | @paulcalvano | @paulcalvano | - | - | @rviscomi |

<details>
<summary><b>Expand for more information about each role</b></summary>

- The **[content team lead](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Content-Team-Leads'-Guide)** is the chapter owner and responsible for setting the scope of the chapter and managing contributors' day-to-day progress.
- **[Authors](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Authors'-Guide)** are subject matter experts and lead the content direction for each chapter. Chapters typically have one or two authors. Authors are responsible for planning the outline of the chapter, analyzing stats and trends, and writing the annual report.
- **[Reviewers](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Reviewers'-Guide)** are also subject matter experts and assist authors with technical reviews during the planning, analyzing, and writing phases.
- **[Analysts](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Analysts'-Guide)** are responsible for researching the stats and trends used throughout the Almanac. Analysts work closely with authors and reviewers during the planning phase to give direction on the types of stats that are possible from the dataset, and during the analyzing/writing phases to ensure that the stats are used correctly.
- **[Editors](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Editors'-Guide)** are technical writers who have a penchant for both technical and non-technical content correctness. Editors have a mastery of the English language and work closely with authors to help wordsmith content and ensure that everything fits together as a cohesive unit.
- The **[section coordinator](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Section-Leads'-Guide)** is the overall owner for all chapters within a section like "User Experience" or "Page Content" and helps to keep each chapter on schedule.

_Note: The time commitment for each role varies by the chapter's scope and complexity as well as the number of contributors._

For an overview of how the roles work together at each phase of the project, see the [Chapter Lifecycle](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Chapter-Lifecycle) doc.
</details>

### [**0. Form the content team**](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Chapter-Lifecycle#0-create-content-team)
+ [x] **May 31**: The content team has at least one author, reviewer, and analyst

### [**1. Plan content**](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Chapter-Lifecycle#1-plan-content)
+ [x] **June 15** The content team has completed the chapter outline in the [draft doc][~google-doc]

### [**2. Gather data**](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Chapter-Lifecycle#2-gather-data)
+ [x] **June 30**: Analysts have added all necessary [custom metrics](https://github.com/HTTPArchive/legacy.httparchive.org/blob/master/custom_metrics/README.md) and drafted a PR ([example](https://github.com/HTTPArchive/almanac.httparchive.org/pull/1087)) to track query progress
- **July 1 - 31**: HTTP Archive runs the July crawl

### [**3. Validate results**](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Chapter-Lifecycle#3-validate-results)
+ [x] **September 30**: Analysts have queried all metrics and saved the output to the [results sheet][~google-sheets]

### [**4. Draft content**](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Chapter-Lifecycle#4-draft-content)
+ [x] **October 31**: The content team has written, reviewed, and edited the chapter in the [doc][~google-doc]

### [**5. Publication**](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Chapter-Lifecycle#5-publication)
+ [ ] **November 15**: The completed chapter and all required [metadata](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Authors'-Guide#metadata-to-add-at-the-top-of-your-chapters) and [figures](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Figures-Guide) are converted to markdown and submitted to [GitHub][~chapter-markdown]
- **December 1**: Target launch date 🚀

## Chapter resources

Refer to these 2021 Compression resources throughout the content creation process:

[📄 Google Docs][~google-doc] for outlining and drafting content
[🔍 SQL files][~sql-files] for committing the queries used during analysis
[📊 Google Sheets][~google-sheets] for saving the results of queries
[📝 Markdown file][~chapter-markdown] for publishing content and managing public metadata

[~google-doc]: https://docs.google.com/document/d/1RHgHEb4wv2CmAJoJihy7MQPhNzBw6fvirxS4Fog0-yQ/edit?usp=sharing
[~sql-files]: https://github.com/HTTPArchive/almanac.httparchive.org/tree/main/sql/2021/compression
[~google-sheets]: https://docs.google.com/spreadsheets/d/1-FQlNvtBw9ai8cBF7wEich_AcXnrNkNGW7dMYvHFl2w/edit?usp=sharing
[~chapter-markdown]: https://github.com/HTTPArchive/almanac.httparchive.org/tree/main/src/content/en/2021/compression.md

**Comment by rviscomi** [comment]
📟 paging 2019/2020 contributors: @paulcalvano @yoavweiss @colinbendell @mo271 @jyrkialakuijala @sboukortt @veluca93 @AbbyTsai 

Would any of you be interested to contribute to the 2021 chapter? I'd especially like to see more 2019/2020 authors become 2021 reviewers to help ease the transition and similarly I think prior reviewers would make great 2021 authors, being familiar with the process already. And prior analysts would make excellent 2021 analysts 😁

Or is there anyone new you'd like to see?

**Comment by jyrkialakuijala** [comment]
I'd be happy to either review or author.

**Comment by rviscomi** [comment]
@jyrkialakuijala sounds great, welcome back! Are you interested in being the content team lead for the chapter (responsible for overall content direction and staffing coauthors/reviewers as needed)?

**Comment by paulcalvano** [comment]
Awesome!   Would love to contribute on this chapter as well.  I'm happy to be an analyst and reviewer.    Looking forward to working with you @jyrkialakuijala !

**Comment by rviscomi** [comment]
Thanks Paul! I've added you to the reviewer/analyst roles in the chapter metadata at the top. @jyrkialakuijala can you confirm if you're open to taking on the content team lead role for this chapter? You'd effectively be the lead author.

**Comment by jyrkialakuijala** [comment]
Thank you! I will happily take the content team lead role.

**Comment by rviscomi** [comment]
@jyrkialakuijala thanks for your interest in authoring this chapter! As the content team lead, you'll be responsible for the scope and direction of the chapter and keeping it on schedule. We automatically monitor the staffing and progress of each chapter based on the state of the [initial comment][~chapter-metadata] so please keep that updated as you add new contributors and meet each milestone. First, you'll need to go to https://github.com/HTTPArchive/ to accept the invitation to join the GitHub team. That will give you the necessary permissions to edit this issue.

We've created a [Google Doc][~google-doc] for this chapter, which you're encouraged to use to collaborate with the content team on the initial outline, metrics, and ultimately the final draft.

Next steps for this chapter are:

- Due **May 31**: Complete [Milestone 0: Form the content team](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Chapter-Lifecycle#0-create-content-team)—**you can check this off now** since you've already got at least one author, reviewer, and analyst ✨ 
- Due **June 15**: Get started on [Milestone 1: Plan content](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Chapter-Lifecycle#1-plan-content) by brainstorming some content ideas in the [doc][~google-doc] (**you will need to request edit access**)

There's not currently a section coordinator for this chapter, so I'll be periodically checking in with you directly to make sure the chapter is staying on schedule. Reach out here in this issue if you have any questions about the process.

More information about the [content team lead](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Content-Team-Leads'-Guide) and [author](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Authors'-Guide) roles and responsibilities are available for reference in the wiki if needed.

To anyone else still interested in contributing to this chapter, please comment below to join the team!


[~chapter-metadata]: https://github.com/HTTPArchive/almanac.httparchive.org/issues/2160#issue-868436386
[~google-doc]: https://docs.google.com/document/d/1RHgHEb4wv2CmAJoJihy7MQPhNzBw6fvirxS4Fog0-yQ/edit?usp=sharing

**Comment by rviscomi** [comment]
Hey @jyrkialakuijala, I know we've been emailing but could you give a status update on the outline in the [doc](https://docs.google.com/document/d/1RHgHEb4wv2CmAJoJihy7MQPhNzBw6fvirxS4Fog0-yQ/edit?disco=AAAAInPQVpQ)?Do you expect you'll be able to get it done by the end of the week?

**Comment by rviscomi** [comment]
⚠️ @jyrkialakuijala any updates on the chapter [outline](https://docs.google.com/document/d/1RHgHEb4wv2CmAJoJihy7MQPhNzBw6fvirxS4Fog0-yQ/edit)?

**Comment by lvandeve** [comment]
Hi, I'm one of Jyrki's reports and would like to contribute.

The outline is the same as last year (with new text but comparable data), with the addition of information about compression levels, and I added in the [doc](https://docs.google.com/document/d/1RHgHEb4wv2CmAJoJihy7MQPhNzBw6fvirxS4Fog0-yQ/edit#) under TOC under outline

For the metrics: it would be interesting to gather data about compression levels used (gzip level 1 to 9 or more optimized such as zopfli, brotli level 1 to 11). These levels are not directly stored in the data (but could be estimated with various methods), and I'd like to check: does it sound feasible to get a proxy for this from the data?

**Comment by rviscomi** [comment]
Welcome @lvandeve! I'll defer to @paulcalvano on the feasibility of the metrics, but I look forward to seeing the new data.

**Comment by lvandeve** [comment]
I'm going to drive the authoring side of the Compression 2021 chapter. I propose the following division for analysis:

@paulcalvano to run the same analysis as last year

@lvandeve with the help of other authors to run the new analysis on compression levels

**Comment by rviscomi** [comment]
👋 Hi @lvandeve @jyrkialakuijala @paulcalvano, just checking in on the chapter progress. How is the analysis coming along?

**Comment by rviscomi** [comment]
@lvandeve @paulcalvano I see that the results sheet has a lot of data already and Milestone 2 is checked off, but I don't see any queries added to this chapter's [sql dir](https://github.com/HTTPArchive/almanac.httparchive.org/tree/main/sql/2021/compression). Could you make sure that any queries used to generate results in the sheet are backed up to the repo?

Besides that, any other blockers or is the analysis generally complete?

**Comment by rviscomi** [comment]
@lvandeve @paulcalvano ping on my previous comment, any update on getting the PR started to check in the SQL?

**Comment by paulcalvano** [comment]
Hey @rviscomi .   The analysis is complete, and I'll submit a PR with the queries shortly.  Apologies for the delay.

**Comment by rviscomi** [comment]
@lvandeve @jyrkialakuijala @paulcalvano

🎉 This chapter is fully written, reviewed, edited, and ready to be launched on Wednesday! **Thank you** to all of the contributors who put in the time and effort to make this a great chapter.

When you get 5 minutes, I'd really appreciate if you could fill out our [contributor survey](https://forms.gle/VRzHPTyWxuwa67vF7) to tell us (the project leads) about your experience. It's super helpful to hear what went well or what could be improved for next time. 🙏 

Congratulations and thank you all again. I'm excited for this to launch soon!
