### ISSUE TITLE
Caching 2021

### ISSUE THREAD

**Issue by rviscomi** [HTTPArchive/almanac.httparchive.org#2161]
# Part IV Chapter 23: Caching

![Caching illustration](https://raw.githubusercontent.com/HTTPArchive/almanac.httparchive.org/main/src/static/images/2019/caching/hero_lg.jpg)

If you're interested in contributing to the Caching chapter of the 2021 Web Almanac, please reply to this issue and indicate which role or roles best fit your interest and availability: [author](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Authors'-Guide), [reviewer](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Reviewers'-Guide), [analyst](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Analysts'-Guide), and/or [editor](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Editors'-Guide).

## Content team

| Lead | Authors | Reviewers | Analysts | Editors | Coordinator |
| --- | ------- | --------- | -------- | ------- | -- |
| @Zizzamia | @Zizzamia | @jessnicolet @WilhelmWillie @roryhewitt @boosef | @rviscomi | - | @rviscomi |

<details>
<summary><b>Expand for more information about each role</b></summary>

- The **[content team lead](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Content-Team-Leads'-Guide)** is the chapter owner and responsible for setting the scope of the chapter and managing contributors' day-to-day progress.
- **[Authors](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Authors'-Guide)** are subject matter experts and lead the content direction for each chapter. Chapters typically have one or two authors. Authors are responsible for planning the outline of the chapter, analyzing stats and trends, and writing the annual report.
- **[Reviewers](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Reviewers'-Guide)** are also subject matter experts and assist authors with technical reviews during the planning, analyzing, and writing phases.
- **[Analysts](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Analysts'-Guide)** are responsible for researching the stats and trends used throughout the Almanac. Analysts work closely with authors and reviewers during the planning phase to give direction on the types of stats that are possible from the dataset, and during the analyzing/writing phases to ensure that the stats are used correctly.
- **[Editors](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Editors'-Guide)** are technical writers who have a penchant for both technical and non-technical content correctness. Editors have a mastery of the English language and work closely with authors to help wordsmith content and ensure that everything fits together as a cohesive unit.
- The **[section coordinator](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Section-Leads'-Guide)** is the overall owner for all chapters within a section like "User Experience" or "Page Content" and helps to keep each chapter on schedule.

_Note: The time commitment for each role varies by the chapter's scope and complexity as well as the number of contributors._

For an overview of how the roles work together at each phase of the project, see the [Chapter Lifecycle](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Chapter-Lifecycle) doc.
</details>

### [**0. Form the content team**](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Chapter-Lifecycle#0-create-content-team)
+ [x] **May 31**: The content team has at least one author, reviewer, and analyst

### [**1. Plan content**](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Chapter-Lifecycle#1-plan-content)
+ [x] **June 15** The content team has completed the chapter outline in the [draft doc][~google-doc]

### [**2. Gather data**](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Chapter-Lifecycle#2-gather-data)
+ [x] **June 30**: Analysts have added all necessary [custom metrics](https://github.com/HTTPArchive/legacy.httparchive.org/blob/master/custom_metrics/README.md) and drafted a PR ([example](https://github.com/HTTPArchive/almanac.httparchive.org/pull/1087)) to track query progress
- **July 1 - 31**: HTTP Archive runs the July crawl

### [**3. Validate results**](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Chapter-Lifecycle#3-validate-results)
+ [x] **September 30**: Analysts have queried all metrics and saved the output to the [results sheet][~google-sheets]

### [**4. Draft content**](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Chapter-Lifecycle#4-draft-content)
+ [x] **October 31**: The content team has written, reviewed, and edited the chapter in the [doc][~google-doc]

### [**5. Publication**](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Chapter-Lifecycle#5-publication)
+ [x] **November 15**: The completed chapter and all required [metadata](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Authors'-Guide#metadata-to-add-at-the-top-of-your-chapters) and [figures](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Figures-Guide) are converted to markdown and submitted to [GitHub][~chapter-markdown]
- **December 1**: Target launch date 🚀

## Chapter resources

Refer to these 2021 Caching resources throughout the content creation process:

[📄 Google Docs][~google-doc] for outlining and drafting content
[🔍 SQL files][~sql-files] for committing the queries used during analysis
[📊 Google Sheets][~google-sheets] for saving the results of queries
[📝 Markdown file][~chapter-markdown] for publishing content and managing public metadata

[~google-doc]: https://docs.google.com/document/d/1BSdljOv86CPAP5T0A9jcV6bU7NJp1f2mTFa4ZZ7xxe8/edit?usp=sharing
[~sql-files]: https://github.com/HTTPArchive/almanac.httparchive.org/tree/main/sql/2021/caching
[~google-sheets]: https://docs.google.com/spreadsheets/d/1-v3yR0LZIC3t4zWtqTgR3jJsKjjRMP-HATU2caP8e2c/edit?usp=sharing
[~chapter-markdown]: https://github.com/HTTPArchive/almanac.httparchive.org/tree/main/src/content/en/2021/caching.md

**Comment by roryhewitt** [comment]
More than willing to be the author again.

**Comment by rviscomi** [comment]
Thanks @roryhewitt! I'll tentatively put you down as a peer reviewer to let someone else author if interested (see #2165 for context).

**Comment by boosef** [comment]
Happy to review and/or edit!

**Comment by roryhewitt** [comment]
Peer reviewer it is! As long as we have a cat pic, I'm fine... :)

**Comment by rviscomi** [comment]
📟 paging 2019/2020 contributors: @paulcalvano @yoavweiss @colinbendell @obto @csswizardry @jzyang @jaisanth @Soham-S-Sarkar @raghuramakrishnan71

Would any of you be interested to contribute to the 2021 chapter? I'd especially like to see more 2019/2020 authors become 2021 reviewers to help ease the transition and similarly I think prior reviewers would make great 2021 authors, being familiar with the process already. And prior analysts would make excellent 2021 analysts 😁

Or is there anyone new you'd like to see?

**Comment by Zizzamia** [comment]
@rviscomi Happy to take this one as Lead Author for 2021 🔥

**Comment by rviscomi** [comment]
@Zizzamia thanks for your interest in authoring this chapter! As the content team lead, you'll be responsible for the scope and direction of the chapter and keeping it on schedule. We automatically monitor the staffing and progress of each chapter based on the state of the [initial comment][~chapter-metadata] so please keep that updated as you add new contributors and meet each milestone.

We've created a [Google Doc][~google-doc] for this chapter, which you're encouraged to use to collaborate with the content team on the initial outline, metrics, and ultimately the final draft.

Next steps for this chapter are:

- Due **May 31**: Complete [Milestone 0: Form the content team](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Chapter-Lifecycle#0-create-content-team) by finding contributors to help with the analysis
- Due **June 15**: Get started on [Milestone 1: Plan content](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Chapter-Lifecycle#1-plan-content) by brainstorming some content ideas in the [doc][~google-doc] (you may need to request edit access)

There's not currently a section coordinator for this chapter, so I'll be periodically checking in with you directly to make sure the chapter is staying on schedule. Reach out here in this issue if you have any questions about the process.

More information about the [content team lead](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Content-Team-Leads'-Guide) and [author](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Authors'-Guide) roles and responsibilities are available for reference in the wiki if needed.

To anyone else interested in contributing to this chapter, please comment below to join the team!


[~chapter-metadata]: https://github.com/HTTPArchive/almanac.httparchive.org/issues/2161#issue-868436431
[~google-doc]: https://docs.google.com/document/d/1BSdljOv86CPAP5T0A9jcV6bU7NJp1f2mTFa4ZZ7xxe8/edit?usp=sharing

**Comment by Zizzamia** [comment]
Niiiice! This is going to be fun!  🌲 🚀 🌕

**Comment by Zizzamia** [comment]
Alright, to have @jessnicolet and @WilhelmWillie as reviewers. Anyone interested to join as **Analysts**?

**Comment by roryhewitt** [comment]
@Zizzamia feel free to do a complete rewrite. You don't even need to keep the picture of my cat (as long as you include **a** picture of a cat :)

**Comment by Zizzamia** [comment]
LOL @roryhewitt, what if I don't like cats?!? 😆
But yeah, I usually do a full rewrite, and I use the old version as point of reference in what topic were covered so we can do a nice 2019 vs 2020 vs 2021 data comparison. Looking forward to hear your feedbacks in the coming months as the chapter shapes out.

**Comment by rviscomi** [comment]
Hi @Zizzamia just checking in. Here are some tips to help keep the chapter on track:

- Coordinate with the rest of the content team to request edit access to the [doc](https://docs.google.com/document/d/1BSdljOv86CPAP5T0A9jcV6bU7NJp1f2mTFa4ZZ7xxe8/edit?usp=sharing) and start brainstorming an outline for the chapter
- Consider announcing to your professional networks that you're looking for co-contributors knowledgable in caching to join the chapter
- Edit the [top comment](https://github.com/HTTPArchive/almanac.httparchive.org/issues/2161#issue-868436431) to keep the chapter metadata in sync with all coauthors/reviewers/analysts and also any completed milestones (this is helpful for us to monitor progress at a glance in https://github.com/HTTPArchive/almanac.httparchive.org/issues/2179)

**Comment by rviscomi** [comment]
Reminder for the content team (@Zizzamia @jessnicolet @WilhelmWillie @roryhewitt @boosef) please request edit access to the [Caching chapter doc](https://docs.google.com/document/d/1BSdljOv86CPAP5T0A9jcV6bU7NJp1f2mTFa4ZZ7xxe8/edit?usp=sharing) and begin outlining the chapter. The outline is due on **June 15** to ensure that we have enough time to make any necessary changes to the testing pipeline before the crawl starts on July 1.

@HTTPArchive/analysts this chapter is still in need of an analyst. Can anyone help out? 🙏

**Comment by rviscomi** [comment]
@Zizzamia as we continue looking for an analyst, do you have any interest in taking on the role in the interim? I'd be happy to walk you through the dataset and answer any questions as needed. There's also a supportive community of analysts in the #web-almanac-analysts Slack channel.

**Comment by Zizzamia** [comment]
@rviscomi oh interesting, I am not on that Slack yet. Would you mind share an invite, so I can make the request in the #web-almanac-analysts channel.

**Comment by rviscomi** [comment]
Join us! https://join.slack.com/t/httparchive/shared_invite/zt-45sgwmnb-eDEatOhqssqNAKxxOSLAaA

**Comment by rviscomi** [comment]
Hey @Zizzamia, today is the deadline for the chapter outline to be completed but it doesn't look like anything is in the [doc](https://docs.google.com/document/d/1BSdljOv86CPAP5T0A9jcV6bU7NJp1f2mTFa4ZZ7xxe8/edit?disco=AAAAMsv77Qw) yet. Could you give us an update on when you'd be able to get that completed?

⚠️ Given that this chapter is behind on staffing (analysts) and planning, it's at risk of getting cut from the Almanac unless we can make progress on it soon. If you can get the planning done ASAP I can pick up the analysis work until we find a permanent contributor.

**Comment by Zizzamia** [comment]
@rviscomi thank you for the ping, the outline will be added by Friday Evening 😄

**Comment by Zizzamia** [comment]
Hey team (@jessnicolet @WilhelmWillie @roryhewitt @boosef @rviscomi),
feel free to review the initial outline in the [draft doc](https://docs.google.com/document/d/1BSdljOv86CPAP5T0A9jcV6bU7NJp1f2mTFa4ZZ7xxe8/edit#), few notes on it:
- so far taking inspiration from the 2020 chapter in terms of query and content will be best to continue evolve
- extend the caching conversation not only on Browser Caching but also Client caching like Cookies, LocalStorage and IndexedDB

How can you help me? Well let me know if there is a particular query you think it should be included, or a new topic we should include in the Future section that explores new ways of caching.

I am going to keep re-read the queries and the outline this weekend so they are both pretty solid in the coming days.

**Comment by rviscomi** [comment]
Thanks @Zizzamia! I've reviewed the outline and left comments on anything unclear related to the analysis. I've also drafted #2254 to organize which queries need to be written and their implementation.

The only metric that may need to be implemented as a runtime metric (hard deadline at the end of the month) is "how big is the biggest CacheStorage value". I left a comment in the doc for clarification.

Reviewers: please review the outline and suggest any new metrics ASAP. I'll update my draft analysis PR accordingly but anything that requires a runtime metric needs to be implemented very soon or else it won't be measurable.

**Comment by rviscomi** [comment]
@Zizzamia @jessnicolet @WilhelmWillie @roryhewitt @boosef queries have been written and results saved to the [results sheet](https://docs.google.com/spreadsheets/d/1-v3yR0LZIC3t4zWtqTgR3jJsKjjRMP-HATU2caP8e2c/edit?usp=sharing). Could you all please review the results and leave comments if anything looks fishy? (you'll need to request access in order to comment)

**Comment by rviscomi** [comment]
The queries have all been written, reviewed, and merged in #2254, so I've checked off Milestone 3 in the top comment above.

@Zizzamia @jessnicolet @WilhelmWillie @roryhewitt @boosef please review the [results in the sheet](https://docs.google.com/spreadsheets/d/1-v3yR0LZIC3t4zWtqTgR3jJsKjjRMP-HATU2caP8e2c/edit?usp=sharing) and leave comments if anything doesn't look right. Otherwise, the chapter draft is ready to start being written.

**Comment by rviscomi** [comment]
@Zizzamia  have you had time to review the results? FYI the draft is due in 4 weeks. Let me know if there's anything I can do to help.

**Comment by Zizzamia** [comment]
Morning, sorry for the extreme delay. I had several personal matter that put on-hold all my Open Source contributions in the last 4 months.

I will start working on the draft this week, so hopefully we have something to review soon.

And if anyone wants to help, is more than welcome 🙏

**Comment by Zizzamia** [comment]
As I am quite behind on writing this chapter, I decided to write directly the draft in this PR https://github.com/HTTPArchive/almanac.httparchive.org/pull/2443.

Reviewers (@jessnicolet @WilhelmWillie @roryhewitt @boosef) and Analysts (@rviscomi), as I am going to write more over the next few days, feel free to add suggestions, edits or share a feedback at anytime. 🙏

**Comment by tunetheweb** [comment]
@Zizzamia | @jessnicolet @WilhelmWillie @roryhewitt 

🎉 This chapter is fully written, reviewed, edited, and launched! **Thank you** to all of the contributors who put in the time and effort to make this a great chapter.

When you get 5 minutes, I'd really appreciate if you could fill out our [contributor survey](https://forms.gle/VRzHPTyWxuwa67vF7) to tell us (the project leads) about your experience. It's super helpful to hear what went well or what could be improved for next time. 🙏 

Congratulations and thank you all again. I'm excited for this to launch soon!
