### ISSUE TITLE
📣 Contribute to the 2021 Web Almanac

### ISSUE THREAD

**Issue by rviscomi** [HTTPArchive/almanac.httparchive.org#2167]
Hi @HTTPArchive/almanac-contributors, it's that special time of year again when we kick off another edition of the Web Almanac "state of the web" report!

At this early stage, we're starting with assigning teams of contributors to each chapter. A chapter's content team consists of [authors](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Authors'-Guide), [reviewers](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Reviewers'-Guide), [analysts](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Analysts'-Guide), and [editors](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Editors'-Guide). See [this discussion](https://github.com/HTTPArchive/almanac.httparchive.org/discussions/2165) for more info about how authors are selected.

ℹ️  **To get involved, choose a chapter from the list below and reply to its respective issue to indicate which role(s) you'd be interested in.** You can also filter issues for those labelled ["2021 chapter" and "help wanted"](https://github.com/HTTPArchive/almanac.httparchive.org/issues?q=is%3Aopen+is%3Aissue+label%3A%222021+chapter%22+label%3A%22help+wanted%22) to see what's available.

Here's the current lineup for 2021:

#### Page Content

- [CSS](https://github.com/HTTPArchive/almanac.httparchive.org/issues/2140)
- [JavaScript](https://github.com/HTTPArchive/almanac.httparchive.org/issues/2141)
- [Markup](https://github.com/HTTPArchive/almanac.httparchive.org/issues/2142)
- [Structured Data](https://github.com/HTTPArchive/almanac.httparchive.org/issues/2174) 🆕
- [Fonts](https://github.com/HTTPArchive/almanac.httparchive.org/issues/2143)
- [Media](https://github.com/HTTPArchive/almanac.httparchive.org/issues/2144)
- [WebAssembly](https://github.com/HTTPArchive/almanac.httparchive.org/issues/2168) 🆕
- [Third Parties](https://github.com/HTTPArchive/almanac.httparchive.org/issues/2145)

#### User Experience

- [SEO](https://github.com/HTTPArchive/almanac.httparchive.org/issues/2146)
- [Accessibility](https://github.com/HTTPArchive/almanac.httparchive.org/issues/2147)
- [Localization](https://github.com/HTTPArchive/almanac.httparchive.org/issues/2169) 🆕
- [Performance](https://github.com/HTTPArchive/almanac.httparchive.org/issues/2148)
- [Privacy](https://github.com/HTTPArchive/almanac.httparchive.org/issues/2149)
- [Security](https://github.com/HTTPArchive/almanac.httparchive.org/issues/2150)
- [Mobile Web](https://github.com/HTTPArchive/almanac.httparchive.org/issues/2151)
- [Capabilities](https://github.com/HTTPArchive/almanac.httparchive.org/issues/2152)
- [PWA](https://github.com/HTTPArchive/almanac.httparchive.org/issues/2153)

#### Content Publishing

- [CMS](https://github.com/HTTPArchive/almanac.httparchive.org/issues/2154)
- [Ecommerce](https://github.com/HTTPArchive/almanac.httparchive.org/issues/2155)
- [Jamstack](https://github.com/HTTPArchive/almanac.httparchive.org/issues/2156)

#### Content Distribution

- [Page Weight](https://github.com/HTTPArchive/almanac.httparchive.org/issues/2157)
- [Resource Hints](https://github.com/HTTPArchive/almanac.httparchive.org/issues/2158)
- [CDN](https://github.com/HTTPArchive/almanac.httparchive.org/issues/2159)
- [Compression](https://github.com/HTTPArchive/almanac.httparchive.org/issues/2160)
- [Caching](https://github.com/HTTPArchive/almanac.httparchive.org/issues/2161)
- [HTTP](https://github.com/HTTPArchive/almanac.httparchive.org/issues/2162)

Are there any other major topics on the web that we're missing? Any suggestions to organize the content differently? We'd love to hear your ideas in the comments.

For all chapter-specific questions/discussions, head over to the issues linked above.

And if you're interested to contribute to the project beyond a specific chapter, there are also opportunities to join the [translators](https://github.com/HTTPArchive/almanac.httparchive.org/issues/923), [developers](https://github.com/HTTPArchive/almanac.httparchive.org/issues/2172), and [designers](https://github.com/HTTPArchive/almanac.httparchive.org/issues/2173) teams!

The Web Almanac is supported entirely by the web community, so **thank you all** for your interest and support to keep this valuable resource going year after year!

**Comment by cqueern** [comment]
@rviscomi with the growing interest in ESG (Environmental, Social, and Corporate Governance) do you foresee a time when there may be a chapter on energy consumption features of the web?

**Comment by SaptakS** [comment]
I wonder if localization can also be a topic. I know there's various different work going on in localization and internationalization for languages that are not ltr from logical css to fonts to other stuff.

**Comment by RReverser** [comment]
> Are there any other major topics on the web that we're missing?

We definitely want to try and add WebAssembly data this year.

**Comment by rviscomi** [comment]
> @rviscomi with the growing interest in ESG (Environmental, Social, and Corporate Governance) do you foresee a time when there may be a chapter on energy consumption features of the web?

@cqueern  That's a great idea and a really important topic. What do you think about dedicating a section to that as part of the Page Weight (#2157) chapter, given how it's a function of bytes?

> I wonder if localization can also be a topic. I know there's various different work going on in localization and internationalization for languages that are not ltr from logical css to fonts to other stuff.

> We definitely want to try and add WebAssembly data this year.

Thanks @SaptakS and @RReverser I've added those chapters to the list! See #2169 and #2168

**Comment by cqueern** [comment]
> @cqueern That's a great idea and a really important topic. What do you think about dedicating a section to that as part of the Page Weight (#2157) chapter, given how it's a function of bytes?

That may make the most sense; not sure. There are likely other factors beyond bytes such as the use of script timers that impact the energy consumption of a page. In any case excited to explore it, and make whatever signals visible that we can.

**Comment by shantsis** [comment]
The original interest form had a designer role as well. Where does that fit in?

**Comment by rviscomi** [comment]
@shantsis great question, I've just opened https://github.com/HTTPArchive/almanac.httparchive.org/issues/2173 to recruit for the design team and point to open design issues.

**Comment by soulcorrosion** [comment]
@rviscomi what about Ajax? As far as I know there's no chapter covering it. Understanding the current state of Ajax use, via various apis, like XMLHttpRequest, fetch or even beacon looks like a good addition to the almanac.

**Comment by rviscomi** [comment]
Thanks for the suggestion @soulcorrosion. I think that would be a good topic to explore in the JavaScript chapter. Would you be interested to join that team as a reviewer?

**Comment by alangdm** [comment]
Hi there, I would be interested in collaborating with the translations. I could help with either Japanese or Spanish. Where could I get more information about that?

**Comment by bazzadp** [comment]
Would love to have your help @alangdm ! I've just sent you GitHub invites to the project there so you'll be able to edit and be assigned to issues.

Japanese is being tracked in #586 and is making great progress by @ksakae1216 . 2019 is dome, and 2020 is more than half done.

Spanish is being tracked in #498 and currently only has one 2020 translation and a handful of 2019, but the ground work is all done so ready to go!

There's more info in our [Translator's Guide](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Translators'-Guide) but feel to comment on either of above two issues if you have any questions!

**Comment by alangdm** [comment]
@bazzadp Thanks for the invite, I'll check the issues and see what I can help with 👍

**Comment by gerrymcgovernireland** [comment]
> 
> 
> @rviscomi with the growing interest in ESG (Environmental, Social, and Corporate Governance) do you foresee a time when there may be a chapter on energy consumption features of the web?

Really important issue. I've been doing a good bit of research around the environmental impact of data and digital devices, so if there's any way I can help, I'd be happy to.

**Comment by TrevorFSmith** [comment]
@rviscomi I'd like to add information about WebXR usage this year along with @Yonet, who is the co-chair of the W3C Immersive Web Working Group that created the API.

**Comment by cqueern** [comment]
Team, @rviscomi suggested we explore what data the HTTP Archive might offer to investigate the carbon impact of websites [over on the HTTP Archive forum](https://discuss.httparchive.org/t/how-can-we-explore-the-carbon-impact-of-websites-using-the-http-archive-web-almanac/2139). Look forward to your thoughts!

@ericwbailey @aardrian @noah-vdv @gerrymcgovernireland

**Comment by rviscomi** [comment]
Hi @TrevorFSmith, we had a section for WebXR in the [2019 Media](https://github.com/HTTPArchive/almanac.httparchive.org/issues/6) chapter but it never materialized. @Yonet do you remember what the reason was for dropping it? Looking through the queries, I only see one basic query for XR libraries based on script file names. If you feel like there is enough content to research and talk about this year I'd be super excited to see us include a section in the 2021 Media chapter. Let me know what you both think and I can add you to the Media team.

**Comment by TrevorFSmith** [comment]
@rviscomi Based on the stories I've found for each week of the Immersive Web Weekly there was a large uptick in WebXR usage in 2020 that continues today. If nothing else, we can update the query that you linked to include common libraries like react-three-fiber and wonderland.
I have not yet looked into what can and can't be queried but is it possible to look for calls to specific web APIs like `navigator.xr` and the spatial mixer in WebAudio?

**Comment by rviscomi** [comment]
@TrevorFSmith sounds good, let's discuss in #2144

**Comment by mgechev** [comment]
I'm interested joining as a reviewer of the JavaScript section. ✨

**Comment by soulcorrosion** [comment]
> Thanks for the suggestion @soulcorrosion. I think that would be a good topic to explore in the JavaScript chapter. Would you be interested to join that team as a reviewer?

Hi @rviscomi, sure, I'll be glad to help.

**Comment by rabimba** [comment]
I was thinking if we can also have Immersive Web (WebXR) as a chapter too. It would be wonderful to finally have it as a separate chapter

**Comment by Yonet** [comment]
@rabimba we are adding WebXR to Media. Check out [#2144 ](https://github.com/HTTPArchive/almanac.httparchive.org/issues/2144).
