### ISSUE TITLE
Update the chapter progress tracker for 2021

### ISSUE THREAD

**Issue by rviscomi** [HTTPArchive/almanac.httparchive.org#2171]
Similar to #989, let's update the progress tracker GH action to parse the 2021 chapter issues and generate a live view of all chapters' milestones and contributors.

cc @ibnesayeed

**Comment by ibnesayeed** [comment]
I can take care of this!

**Comment by bazzadp** [comment]
@ibnesayeed I got the basics up and running in the [`chapter-tracker-2021 branch`](https://github.com/HTTPArchive/almanac.httparchive.org/tree/chapter-tracker-2021) and created the tracking issues in #2179.

It's not picking up the contributors which would be really handy now for chapter planning whenever you get a chance to have a look.

**Comment by ibnesayeed** [comment]
@rviscomi, now that there are 5 different roles (two more from the last year), does the following statement in #2179 still hold true? If so, a handful of chapters have completed the 0th milestone.

```
0. May 31: Form the content team: The content team has at least one author, reviewer, and analyst
```

Should #2179 be pinned now?

And while we are at it, the SEO chapter now has a quorum, so it should get a check mark.

**Comment by rviscomi** [comment]
Yeah the milestone is still correct, as editors aren't needed until there's a draft and coordinators are assigned at the section- rather than chapter-level.

We can only pin 3 issues at a time, so I'm waiting a bit to give the other issues more prominence.

You're right that some chapters have already met the first milestone, but I'm hoping that the content team leads will get into the habit of keeping their chapter metadata up to date, so I'm refraining from checking them off myself 😆

**Comment by ibnesayeed** [comment]
> but I'm hoping that the content team leads will get into the habit of keeping their chapter metadata up to date

Sounds like a good thing to remind the leads to keep an eye on the chapter progress and keep theirs up to date, perhaps after a while when the dust is settled and most of the chapters have a leader. :)
