### ISSUE TITLE
Join the 2021 Developers team!

### ISSUE THREAD

**Issue by rviscomi** [HTTPArchive/almanac.httparchive.org#2172]
Calling all @HTTPArchive/developers! Let us know if you're interested in collaborating on the 2021 edition.

Browse issues tagged with [`development`](https://github.com/HTTPArchive/almanac.httparchive.org/labels/development)

**Comment by SaptakS** [comment]
Interested!

**Comment by bazzadp** [comment]
A reminder of some of the more interesting development task's we've under taken in this project to show case some of the features talked about in the chapters: https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Technical-accomplishments

**Comment by jdevalk** [comment]
Happy to help, and also involve people on our team like @jono-alderson.

**Comment by rviscomi** [comment]
Thanks @jdevalk!! Great to have you!

**Comment by siakaramalegos** [comment]
I might be interested - it depends on how much I'm playing in other roles for the almanac this year :)

**Comment by rviscomi** [comment]
👋  Welcome Sia! What other roles were you interest in?

**Comment by siakaramalegos** [comment]
@rviscomi I think you've seen now, but I'd like to be an author on a few articles (posted in my top 2). If not chosen as an author, I could be a reviewer or editor on one and maybe also be a developer. You probably best know how much demand each role is and if you can combine.

**Comment by fili** [comment]
I do most of my stuff on app engine with python (I have since 2008, when working at Google 😁). As such I am intimately familiar with app engine. If there is any way to assist with this, I am happy to contribute.

**Comment by bazzadp** [comment]
Oh excellent @fili - would love to see if you (or any others) can suggest any improvements to our current set up?

Our [developer’s guide](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Developers'-Guide) details our tech stack setup and the [`src/README.md`](https://github.com/HTTPArchive/almanac.httparchive.org/blob/main/src/README.md) file details how to run it locally, so suggest those interested in developing get that up and running as a first step.

We also have [`web-almanac-developers`](https://join.slack.com/t/httparchive/shared_invite/zt-45sgwmnb-eDEatOhqssqNAKxxOSLAaA) slack channel so come join that and say high and I’d be happy to answer any questions or chat on anything here.

**Comment by ibnesayeed** [comment]
Please count me in!

**Comment by bharatagsrwal** [comment]
Interested!, Please count me in!!

**Comment by bazzadp** [comment]
@HTTPArchive/developers adding the [metadata discussed in this issue](https://github.com/HTTPArchive/almanac.httparchive.org/issues/1325) should be a relatively easy one for those wanting to learn how our templates are created. Happy to guide someone through it.

**Comment by kartikderasari** [comment]
I'm interested to contribute, please count me in :)

**Comment by bazzadp** [comment]
Invite sent. Feel free to browse the issues tagged with [`development`](https://github.com/HTTPArchive/almanac.httparchive.org/labels/development) and comment on issues you'd like to help with!

**Comment by fili** [comment]
I see plenty of volunteers here, so I will bow out and refocus my attention to the chapters I am reviewing. Happy to consult when needed.

**Comment by siakaramalegos** [comment]
Same - I'm leading a chapter so I think this will be too much for me to do too.

**Comment by LucasBona05** [comment]
I'm interested! Specially in the issue #2209 which is a good first issue.

**Comment by bazzadp** [comment]
Excellent! Happy to walk you through this if you need help. Reach out to me on that issue or on [our slack channel](https://join.slack.com/t/httparchive/shared_invite/zt-45sgwmnb-eDEatOhqssqNAKxxOSLAaA).
