### ISSUE TITLE
Join the 2021 design team!

### ISSUE THREAD

**Issue by rviscomi** [HTTPArchive/almanac.httparchive.org#2173]
Join the @HTTPArchive/designers team and work with web developers to improve and create new user experiences on the Web Almanac website. Comment in this issue if you're interested.

Browse open issues tagged with [`design`](https://github.com/HTTPArchive/almanac.httparchive.org/labels/design)

**Comment by shantsis** [comment]
Interested in helping out

**Comment by GeekBoySupreme** [comment]
Hey @rviscomi would love to help out with the design

**Comment by rviscomi** [comment]
Great, thank you both! Do any of the open [design](https://github.com/HTTPArchive/almanac.httparchive.org/labels/design) issues interest you @shantsis @GeekBoySupreme?

**Comment by shantsis** [comment]
@rviscomi I left a comment on #1764 a few days ago. I can look at others too and pick up some more.

**Comment by GeekBoySupreme** [comment]
@rviscomi would love to pick up #1237 to start off

**Comment by bazzadp** [comment]
Cool! Excited to see some thoughts on these.

**Comment by GeekBoySupreme** [comment]
I was wondering if we should keep a largely same visual theme for this year.
Or we can try going a bit on the overdrive

**Comment by GeekBoySupreme** [comment]
Makes sense. Avoids huge re-writes and maintains a consistency.

**Comment by shantsis** [comment]
Keeping what we have makes sense. I suppose if there's possible enhancements we see within other issues we can bring them up.

**Comment by rviscomi** [comment]
One very small thing that I think might still be doable for 2020+ is to change the accent color:

![image](https://user-images.githubusercontent.com/1120896/117910840-ad808e80-b2aa-11eb-954b-97915cedfeef.png)

Is there a palette of accent colors that would work nicely with the background color for each year? Since the year is displayed prominently in this accent color, it may be a good way to distinguish each annual edition at a glance. We could retroactively change 2020 so that each year has a different accent color, or maybe the current year is always yellow but past years change color. Not sure. Thoughts?

**Comment by shantsis** [comment]
I like the idea of having the current year one color, and the past another. Helps make it more scalable :)

**Comment by shantsis** [comment]
Is the original yellow color based on some contrast value?

**Comment by rviscomi** [comment]
Not aware of the reasoning behind it. The current design was commissioned by an agency.

**Comment by rviscomi** [comment]
📟 @yuseyhan
