### ISSUE TITLE
Rethinking chapter comments

### ISSUE THREAD

**Issue by rviscomi** [HTTPArchive/almanac.httparchive.org#2192]
I'd like to reevaluate our use of discuss.httparchive.org for chapter comments. It's been relatively underused and one thing I dislike is that the comments aren't visible on the chapter page itself.

WDYT about embedding a comments widget in each chapter where readers can give feedback without leaving the page? Something like [Disqus](https://disqus.com/).

Alternatively, we could go all-in on discuss.httparchive.org and use its API to more tightly integrate it with the chapter page. For example, on the [HTTP Archive website](https://httparchive.org/#:~:text=posts-,Featured,Discussions,-Topic) we use the API to list recent and top discussion threads and pull out some metadata like number of replies, title, and commenters. We could similarly extract the contents of each comment and show them on the page. The forum has built-in moderation and spam prevention, which is a nice bonus. But my biggest concern would be the registration flow for new users. Maybe embedding the comments is all we need to do and new comments and registrations can still happen on the forum itself?

**Comment by bazzadp** [comment]
Yes it has been relatively underused, and it not being directly on the page is almost certainly an extra barrier.

However, in my opinion comments on posts seems to be a dying art. On my own (admittedly low-traffic-ed) blog, which uses Disqus, I've noticed them drop to basically zero. Even [popular articles I've published on high trafficed sites like Smashing Magazine](https://www.smashingmagazine.com/2021/04/complete-guide-measure-core-web-vitals/) only pick up a few comments. I really do think it's a bit of a dying medium to be honest though some sites like [Dev.to](https://dev.to/) and [CSS Tricks](https://css-tricks.com/) do seem to get a fair amount of comments, though the quality varies.

I wonder if we're better with something like Web Mentions ([example](https://nooshu.github.io/blog/2019/11/18/implementing-webmentions/)) that pick up from the likes of Twitter are a better option? Many often see them as more privacy preserving and performant too as Disqus has a bad name here.

But keen to hear other's thoughts!

**Comment by rviscomi** [comment]
Web Mentions is a great idea and I'd be happy ditching comments in favor of that!

**Comment by ibnesayeed** [comment]
I second the adoption of Web Mentions!

**Comment by bazzadp** [comment]
I experimented a bit with Web Mentions in my own blog and have actually gone off the idea a bit. It makes the chapter seem a little messy to be honest.

And it seems from #1325 we're trying to position ourselves as a serious bit of research so not sure that's in keeping with the listing of "likes" and random comments on the same page below.

I think if we could surface the discussion CTA a bit more — as is being discussed in #2196 then maybe we'd be better sticking with that?

WDYT?

**Comment by rviscomi** [comment]
TBH I don't feel like pinning the comments CTA goes far enough in addressing this issue. I'd love to find a solution that allows us to integrate the comments (or mentions) directly in the chapter itself and I wouldn't feel like that'd detract from the seriousness of our research.

**Comment by bazzadp** [comment]
Well let's see what the @HTTPArchive/designers can come up with!

Designers, Web Mentions are a form of comments (like Disqus) where you get notified if another service (e.g. Twitter) mentions the URL.

Here's an example of a blog post that uses them: https://nicolas-hoizey.com/articles/2017/07/27/so-long-disqus-hello-webmentions/

![image](https://user-images.githubusercontent.com/10931297/119786824-77592680-bec8-11eb-8fff-68e1ca0692be.png)

As you just call an API to get the likes/mentions/reports/comments, you can style it whatever way you want. So another way of doing it is with tabs, like i this post: https://keithjgrant.com/posts/2019/02/adding-webmention-support-to-a-static-site/

![image](https://user-images.githubusercontent.com/10931297/119786965-9fe12080-bec8-11eb-97ce-07c5408ff5d5.png)

Which can then be clicked on to show the content:

![image](https://user-images.githubusercontent.com/10931297/119787037-b0919680-bec8-11eb-9b62-d662a4efd279.png)

![image](https://user-images.githubusercontent.com/10931297/119787092-bedfb280-bec8-11eb-8120-f667f3f0faf5.png)

Any thoughts on best way to do this for the Web Almanac?

Alternatively we could pull in the comments from the current discussion thread for that chapter without moving to Web Mentions? We already do this on the parent https://httparchive.org website:

![image](https://user-images.githubusercontent.com/10931297/119787363-09612f00-bec9-11eb-9698-e6cc8c2caa16.png)

Thoughts?

**Comment by shantsis** [comment]
Here's 2 quick ideas, open to feedback :)
I like the tab structure to keep it neat, especially if there's a lot in any section
![reactions](https://user-images.githubusercontent.com/22671477/120033048-12392a00-bfc9-11eb-9a20-69dfdd339649.jpg)
![replies](https://user-images.githubusercontent.com/22671477/120033059-15ccb100-bfc9-11eb-8991-a9a929a09dc7.jpg)

**Comment by tunetheweb** [comment]
OK webmentions.io account is set up.

@rviscomi we need [brid.gy](https://brid.gy/) linked to the HTTPArchive twitter account if we want it to pick up Tweets with Almanac URLs in them since Twitter doesn't support WebMentions natively. Can you set up an account and link it? I only have "post as" permissions and not full account access.

After that, we should see posts start to come in in next 24 hours at URLs like this: https://webmention.io/api/mentions?perPage=500&jsonp=parseWebmentions&target=https://almanac.httparchive.org/en/2020/css (change last part depending on chapter).

Can then look at UI changes to display them to @shantsis 's design above, but would be great if someone wiht more JS and CSS skills could help out with that!

Still first step is all this infra set up and to see them coming in. Would be good to get that bit at least completed before launch of 2021 so ready for it. And ideally the UI too if any of the @HTTPArchive/developers wanna help here?

**Comment by tunetheweb** [comment]
Woo hoo, can see all the links from the recent Russian publication:

https://webmention.io/api/mentions?perPage=500&jsonp=parseWebmentions&target=https://almanac.httparchive.org/ru/2020/css

Will give it 24 hours and should hopefully see similar for all our other URLs.

**Comment by tunetheweb** [comment]
And also should auto update going forward now.

So now ust need the UI built to use this data...
