### ISSUE TITLE
Retro: Chapter 17. CDN

### ISSUE THREAD

**Issue by andydavies** [HTTPArchive/almanac.httparchive.org#220]
Place holder for thoughts / issues / improvements identified during analysis of CDN data

# CDN for firstHTML vs CDN for Resources

Connecting to another origin for resources key resources involves the delay of creating a new connection, and creates H2 prioritisation challenges

Can we separate sites that serve resources from a CDN over a single H2 connection, versus those that use a resources CDN?

# Public Library CDNs

How many sites that are already using a CDN for resources, also make requests to public library CDNs e.g. cdnjs.cloudfront.net etc.

# SANs

Differentiate between certificates with SANs for the same legal entity, versus certificates with SANs for multiple customers

# Cache Control

Explore cache lifetimes versus the age of the resources, and the usage of s-maxage versus other validation directives such as stale-while-revalidate.

**Comment by rviscomi** [comment]
@andydavies @colinbendell I'm going to close this issue since no action is necessary, but feel free to continue adding your thoughts to it.

**Comment by andydavies** [comment]
Makes sense - Will do
