### ISSUE TITLE
Chapter numbers missing from chapter footer navigation

### ISSUE THREAD

**Issue by rviscomi** [HTTPArchive/almanac.httparchive.org#2209]
![image](https://user-images.githubusercontent.com/1120896/119563436-8a0f1680-bd75-11eb-9f96-2bb0c143220a.png)

https://almanac.httparchive.org/en/2020/cms#authors

Expected: "Chapter 16 / Ecommerce"
Actual: "Chapter / Ecommerce"

**Comment by bazzadp** [comment]
Assigned - got for it!
