### ISSUE TITLE
Give readers the ability to discover queries, results, and comments for each chapter

### ISSUE THREAD

**Issue by rviscomi** [HTTPArchive/almanac.httparchive.org#221]
Each chapter has a subdir in [sql/2019](https://github.com/HTTPArchive/almanac.httparchive.org/tree/master/sql/2019) with all of its queries and a corresponding spreadsheet with the results.

We should make these resources available to readers as they're on a chapter page. These aren't included in the design so we'll need to create it from scratch using the existing visual language of the site.

In the chapter designs (#130) we have a section for info about each author at the bottom of the page. We can use this space to also call attention to the chapter's SQL subdir and results sheet.

Additionally, I'd like to provide readers with an easy way to react to, report issues with, and comment on chapters. I'm not really sure what the best approach is, so I'm open to ideas. One idea is to create a GitHub issue for each chapter devoted to reader feedback. I don't really like keeping issues open perpetually, though, and GitHub isn't meant to be a discussion forum. We do have the HTTP Archive discussion forum at discuss.httparchive.org where we can do something similar. Thoughts?

---

- [x] Add a new field to each chapter's markdown metadata `discuss` whose value is the four digit thread ID corresponding to the chapter's discussion post. For example `1756` is the ID for the JavaScript thread: https://discuss.httparchive.org/t/chapter-1-javascript/1756
- [x] Add a UI component to the end of the chapter template to encourage readers to discuss their thoughts. It could be something simple like a link button with a chat icon and the label "Comments".
- [x] Generate the link href value based on the chapter's metadata.

Commenting is the biggest priority for launch. We can follow up with UI to discover the queries and results later.

@HTTPArchive/developers

**Comment by catalinred** [comment]
The HTTP Archive discussion forum would be a good place to share and gather feedback for the almanac chapters. It is its purpose (being a forum), after all :)

As you said above, each chapter's bottom could contain some call to actions or sections like the following:

- Discuss on HTTP Archive forum (report issues, comment and send feedback)
- View chapter's code (SQL subdir and results sheet)

Also, in order to avoid a potential three-way GitHub/almanac.httparchive.org/discuss.httparchive.org feedback sharing/gathering chaos, I wouldn't add a comments section on the almanac chapters and instead, rely and focus on the above existing actions/sections for each chapter. 

Hope this helps!

**Comment by rviscomi** [comment]
Thanks for your feedback @catalinred.

I agree the Discuss forum is the best place for comments. I've created a new category [Web Almanac 2019](https://discuss.httparchive.org/c/web-almanac-2019) and seeded it with a thread for each chapter.

We should link from each chapter page to its respective thread on the forum.

**Comment by bazzadp** [comment]
Short term why don’t we make the figure captions links to the data sheets in the markdown?

**Comment by bazzadp** [comment]
I’m happy to do that this weekend btw.

**Comment by rviscomi** [comment]
> Short term why don’t we make the figure captions links to the data sheets in the markdown?

It wouldn't be clear what the caption is linking to. Similar to #382 I think we could get away with a button at the bottom of the chapter with a spreadsheet icon and link text "View the raw results" or something. Same for discovering queries. We can have a row of buttons.

**Comment by rviscomi** [comment]
Pushing the query/results discovery bits to the post-launch milestone.
