### ISSUE TITLE
Methodology page has some broken styles

### ISSUE THREAD

**Issue by rviscomi** [HTTPArchive/almanac.httparchive.org#224]
Per #223, there are some CSS tweaks needed on the Methodology page:

- [x] style the tables
- [x] ensure tables fit in small viewports
- [x] add borders under nested list items in the index
- [x] ensure all links have hover/focus styles (related #210)
- [ ] make the index sticky on desktop so it's visible while scrolling (max-height 100% and overflow-y scroll)
- [x] ensure the H1 has the colored "overline" similar to other pages
- [ ] ensure the hero image is as wide as the hero on chapter pages (866px on desktop)
- [x] the "index" doesn't open on tap for mobile (**important**)

The [Chapter designs](https://projects.invisionapp.com/d/main#/console/18009643/379965127/inspect) include a mockup of a table that we should implement in `2019.css`:

![image](https://user-images.githubusercontent.com/1120896/67425534-2d9ab280-f5a6-11e9-9f2e-51b7b425c6a9.png)

And one optional piece of functionality:

- [ ] as the page is scrolled, update the "active" index item with a green highlight (using IntersectionObserver)

cc @MSakamaki

**Comment by bkardell** [comment]
The head image causes some serious horizontal scrolling on mobile.. that seems probably not specific to this page, but ..

**Comment by rviscomi** [comment]
I think the image issue was fixed by a recent commit that has not yet been pushed to the live website.

**Comment by rviscomi** [comment]
@HTTPArchive/developers anyone interested in working on this issue? I think this is a fun one (using IntersectionObserver and sticky positioning) 😄

**Comment by rviscomi** [comment]
Assigning @ymschaap who is looking into tables in #333

**Comment by rviscomi** [comment]
@ymschaap are you looking into the remaining TODO items for this issue?

**Comment by ymschaap** [comment]
No sorry, I don't have time available this week to do more work on this.

**Comment by rviscomi** [comment]
No worries, thank you!

@HTTPArchive/developers does anyone have time to look into this?

**Comment by rviscomi** [comment]
The styles aren't "broken" any more so I'll close this and open a FR for the new improvements.
