### ISSUE TITLE
Chapter illustrations for new 2021 chapters

### ISSUE THREAD

**Issue by tunetheweb** [HTTPArchive/almanac.httparchive.org#2245]
We have 2 new chapters this year:
- Structured Data
- WebAssembly

We have chapter banners images for each chapter created in 2019, and we managed to create three new ones for the new chapters added in 2020 (Capabilities, Jamstack, and Privacy).

So we would need similar ones created for Structured Data and WebAssembly. We have the PSD files to allow you to reuse some of the resources like the characters.

Unfortunately the designers that created these in 2019 and 2020 are unavailable this year.

@HTTPArchive/designers do any of you have the necessary design skills to do this?

**Comment by shantsis** [comment]
I do not sorry, this is very much not my expertise 🙁
