### ISSUE TITLE
Reorganise contributor JSON file

### ISSUE THREAD

**Issue by tunetheweb** [HTTPArchive/almanac.httparchive.org#2246]
At the moment we have a contributors section in each year's JSON file ([2019.json](https://github.com/HTTPArchive/almanac.httparchive.org/blob/main/src/config/2019.json), [2020.json](https://github.com/HTTPArchive/almanac.httparchive.org/blob/main/src/config/2020.json), and [2021.json](https://github.com/HTTPArchive/almanac.httparchive.org/blob/main/src/config/2021.json)).

Should we merge these into a contributors.json to avoid duplication? We could then have a contributions section for each profile. So for example mine might be:

```JSON
    "tunetheweb": {
      "name": "Barry Pollard",
      "avatar_url": "https://avatars3.githubusercontent.com/u/10931297?v=4&s=200",
      "website": "https://www.tunetheweb.com",
      "github": "tunetheweb",
      "linkedin": "tunetheweb",
      "twitter": "tunetheweb",
      "contributions": {
        "2019": [
          "brainstormers",
          "authors",
          "reviewers",
          "editors",
          "developers"
        ],
        "2020": [
          "analysts",
          "authors",
          "developers",
          "editors",
          "leads",
          "reviewers"
        ],
        "2021": [
          "developers",
          "leads"
        ]
      }
    },
```

Might also want to note the chapters contributed to in each year but above would be a start to give what we have.

Some things to consider:
- We have a contributors page for each year that should only show that years contributors and the total number of contributors for that year.
- the `npm run generate` script has some checks to ensure we don't have someone down as an author, analyst...etc. unless they are also down for that role in one of the chapters meta data so it would need to be updated too.

This would require a bit of Python, Jinja and JavaScript knowledge but happy to work with someone to help them if they are not used to our tech stack.

**Comment by tunetheweb** [comment]
This could help with #1195 and is probably a necessary first step towards that.

**Comment by Shaleen-25** [comment]
Hey, @tunetheweb , I am interested in working on this issue, can you please assign this issue to me.

**Comment by tunetheweb** [comment]
Done! Let me know if you have any questions on need to bounce ideas or approach off of someone.
