### ISSUE TITLE
How to avoid ranking duplicates?

### ISSUE THREAD

**Issue by tunetheweb** [HTTPArchive/almanac.httparchive.org#2251]
CrUX introduced a `rank` grouping to each origin with the following buckets:
- 1,000 (i.e. the top 1,000 most popular sites)
- 10,000
- 100,000
- 1,000,000
- 10,000,000 (in reality topped at the 6-7 million websites in CrUX).

This is available in the `experimental.popularity.rank` column, in the `chrome-ux-report.all.202105` table for example (note we'll be using the 202107 table when it's available) and I see it being a popular source of slicing and dicing our data for 2021 as it was asked for quite a bit in 2020 and 2019, but wasn't available then.

However this table is keyed off of `origin`, `form_factor`, and `effective_connection_type`. It's therefor easy to accidentally include more popular sites (which are more likely to be in CrUX for more than one combinations of these) and thus skew your data towards those more popular sites without realising if you forget to use a `DISTINCT`. I've just done this myself.

It looks like there are no origins that differ in ranking across different form_factors and ECT - @rviscomi is this possible or is the ranking across ALL CrUX data?

Should we create a table in CrUX (`chrome-ux-report.ranking.202105`?) to avoid having to use the `all` table, which is a `DISTINCT` list of origins and ranking?

Or should we create the table in the `httparchive` schema instead and convert the `origin` to a `url` by appending the '/' to avoid having to do that each time?

FYI: @HTTPArchive/analysts

**Comment by rviscomi** [comment]
Rank data should be propagated in the rank field of the summary_pages dataset in HA.

**Comment by tunetheweb** [comment]
Ah perfect. Will close this then.
