### ISSUE TITLE
Form a team of data analysts

### ISSUE THREAD

**Issue by rviscomi** [HTTPArchive/almanac.httparchive.org#23]
Data analysts are responsible for working with authors to provide HTTP Archive data that match the metrics outlined in each chapter. Analysts should be familiar with the BigQuery dataset and comfortable with SQL. Mentoring is available for anyone who wants to learn!

Our current assignment is to triage all ~250 metrics. New analysts: please see #33 for more info on how to access the metrics sheet and what to do.

Join the team: @HTTPArchive/data-analysts

**Comment by rviscomi** [comment]
@matijagrcic @bkardell @patrickhulce you've all expressed interest in writing queries. Still interested?

@paulcalvano can I count you in as well?

**Comment by paulcalvano** [comment]
Count me in!

**Comment by patrickhulce** [comment]
I definitely plan on doing this for my chapter, happy to help out with anything touching Lighthouse or network requests too :)

**Comment by rviscomi** [comment]
Welcome to the team @fhoffa! 😁

**Comment by voltek62** [comment]
count me in too !

**Comment by ymschaap** [comment]
would like join as well.

**Comment by dotjs** [comment]
Would like to help

**Comment by dougsillars** [comment]
I can help with data analysis too

**Comment by beouss** [comment]
Sign me in

**Comment by bkardell** [comment]
I created the custom metrics to capture the data, but I don't recall volunteering to write queries and I don't think I have the time just now.

**Comment by rviscomi** [comment]
@dougsillars @beouss thanks! Invited you both to the Analyst team. You can confirm/accept by visiting https://github.com/HTTPArchive. (Doug's invite should have been accepted automatically, as a member of the org already).

@beouss are you able to add your full name to your GitHub profile so we can give you credit in the Almanac?

@bkardell no worries, thanks for your help with the custom metrics!

**Comment by anoblet** [comment]
I'm not sure how big of a help I will be, I will give it my best try.

**Comment by jrharalson** [comment]
I'm interested in helping pull data. Let me know

**Comment by rviscomi** [comment]
Great thanks @jrharalson! I'll send you an invite to the Analyst team. Same deal: visit https://github.com/HTTPArchive to accept. Also, please update your GitHub profile to include your full name if possible so we can give you credit in the Almanac.

**Comment by raghuramakrishnan71** [comment]
Please add my name to the analyst team. Would like to help with queries. Thanks.

**Comment by rviscomi** [comment]
Thanks @raghuramakrishnan71! Sent you an invite. You can accept at https://github.com/HTTPArchive.
