### ISSUE TITLE
Add a link to the HTTP Archive logo in footer

### ISSUE THREAD

**Issue by MSakamaki** [HTTPArchive/almanac.httparchive.org#230]
`<img src="/static/images/ha-home.png">` a question about the logo.
![スクリーンショット 2019-10-24 10 49 39](https://user-images.githubusercontent.com/2183053/67446585-0f878d80-f64c-11e9-969a-ccc9a9f722f5.png)

On mobile resolution, it is a link to https://httparchive.org/, but there is no link on the desktop resolution.
Should I add anchor tag a link?
(This was mobile and linked)

**Comment by rviscomi** [comment]
Good catch. I noticed this too and already put in a fix here: https://github.com/HTTPArchive/almanac.httparchive.org/pull/229/files#diff-0279dada08cf23c3de510939650b3555R59

**Comment by MSakamaki** [comment]
@rviscomi 
You fix speedy!
This has a slight impact on issues #216, I wait to merge.

**Comment by rviscomi** [comment]
If you have time, could you review #229? That would help unblock you.
