### ISSUE TITLE
Blink Feature Rows are triplicated

### ISSUE THREAD

**Issue by tunetheweb** [HTTPArchive/almanac.httparchive.org#2312]
Run this:

```sql
#standardSQL
SELECT *
FROM
  `httparchive.blink_features.usage`
WHERE
  yyyymmdd in ('20210701','20200101') AND 
  client = 'desktop' AND 
  feature = 'CSSPropertyListStyleImage'
ORDER BY 
  yyyymmdd
```

Notice we get back three rows for each date. And it's the same for all the features. Not sure why but looks like it's been going on for a while...

Seems to be same issue in `httparchive.blink_features.features` (which ultimately drives the usage table so not surprising).

The query in the scheduler looks fine to me so a bit confused why this is. Or how to clean it up....

Any ideas @rviscomi ?

**Comment by rviscomi** [comment]
Do you have a query that shows the duplication in the `features.features` table? I've recently deduplicated that table so I wouldn't expect it to still have issues. I haven't yet deduped the `features.usage` table so any existing redundancy is expected.

**Comment by tunetheweb** [comment]
Actually can't see any for `features.features`. Must have been mistaken about that.

**Comment by tunetheweb** [comment]
Confirmed this i no longer an issue.
