### ISSUE TITLE
Simplify footer markup

### ISSUE THREAD

**Issue by rviscomi** [HTTPArchive/almanac.httparchive.org#238]
As of now we have two sets of footer markup for desktop and mobile. This should be rewritten to have one set of markup that is styled responsively to accommodate either.

https://github.com/HTTPArchive/almanac.httparchive.org/blob/5c0e002eacb0dace823300b5f6a5f12f0f13f596/src/templates/en/2019/base.html#L55-L101

Anyone on @HTTPArchive/developers available to take this?

**Comment by MSakamaki** [comment]
I take this task.
a will send a pull-request today.

**Comment by rviscomi** [comment]
Thank you so much @MSakamaki!
