### ISSUE TITLE
Gather bios for each author

### ISSUE THREAD

**Issue by rviscomi** [HTTPArchive/almanac.httparchive.org#239]
At the top of each chapter we have a short byline to say who wrote it. For example, "By Person One and Person Two" where each name is a link to the author on the Contributors page.

At the bottom we have space for a few sentences per author for a bio. This is a good place to list your qualifications for the chapter like what your day job is or other related work (projects, books, etc).

![image](https://user-images.githubusercontent.com/1120896/67606239-a9376380-f74e-11e9-879d-fedab15f9f97.png)

@HTTPArchive/authors can you each comment on this issue with your preferred bio? If you're writing multiple chapters it's also ok to have a custom version for each, if you'd like.

- [x] 	1. JavaScript	@housseindjirdeh
- [x] 	2. CSS	@una @argyleink
- [x] 	3. Markup	@bkardell
- [x] 	4. Media	@dougsillars @colinbendell
- [x] 	5. Third Parties	@patrickhulce
- [x] 	6. Fonts @zachleat
- [x] 	7. Performance	@rviscomi
- [x] 	8. Security	@arturjanc @ScottHelme
- [x] 	9. Accessibility	Nektarios Paisios @obto @kleinab
- [x] 	10. SEO	@rachellcostello @ymschaap @AVGP
- [x] 	11. PWA	@tomayac @jeffposnick
- [x] 	12. Mobile web	@obto
- [x] 	13. Ecommerce	@samdutton @alankent
- [x] 	14. CMS	@amedina @ernee
- [x] 	15. Compression	@paulcalvano
- [x] 	16. Caching	@paulcalvano
- [x] 	17. CDN	@andydavies @colinbendell
- [x] 	18. Page Weight	@khempenius @tammyeverts
- [x] 	19. Resource Hints	@khempenius
- [x] 	20. HTTP/2	@bazzadp

**Comment by ymschaap** [comment]
SEO, @ymschaap, bio: "Founder at technical SEO consultancy [build.amsterdam](https://build.amsterdam/)"

**Comment by dougsillars** [comment]
Doug Sillars is a freelance digital nomad working on the intersection of performance and media.  He tweets @dougsillars, and blogs regularly at dougsillars.com.

**Comment by tammyeverts** [comment]
Short bio:

Tammy Everts is CXO at [SpeedCurve](https://speedcurve.com/), co-chair of the [performance.now() conference](https://perfnow.nl/), and author of the O'Reilly book _[Time Is Money: The Business Value of Performance](http://shop.oreilly.com/product/0636920041450.do)_. 

Longer bio:

Tammy Everts has spent more than two decades studying usability and UX. For the past ten years, she's focused on the intersection of UX with web performance and business. She is CXO at [SpeedCurve](https://speedcurve.com/), co-chair of the [performance.now() conference](https://perfnow.nl/), and author of the O'Reilly book _[Time Is Money: The Business Value of Performance](http://shop.oreilly.com/product/0636920041450.do)_.

**Comment by bazzadp** [comment]
Barry Pollard is a software developer and author of the Manning book [HTTP/2 in Action](https://www.manning.com/books/http2-in-action). He thinks the web is amazing but wants to make it even better. You can find him tweeting [@tunetheweb](https://twitter.com/tunetheweb) and blogging at [www.tunetheweb.com](https://www.tunetheweb.com).

**Comment by ScottHelme** [comment]
Scott Helme is a Security Researcher and founder of [report-uri.com](https://report-uri.com) and [securityheaders.com](https://securityheaders.com). You can find him talking about security on Twitter [@Scott_Helme](https://twitter.com/Scott_Helme) and blogging at [scotthelme.co.uk](https://scotthelme.co.uk).

**Comment by samdutton** [comment]
Sam Dutton has worked with the Google Chrome team as a Developer Advocate since 2011. 

---

Sam Dutton has worked with the Google Chrome team as a Developer Advocate since 2011. He has organised and presented at a number of events, created and taught several web development courses, and worked on a range of videos, codelabs and written guidance covering PWA, performance, media, image and 'Next Billion Users' initiatives. 

He maintains [simpl.info](https:/simpl.info), which provides simplest possible examples of HTML, CSS and JavaScript. 

Sam grew up in South Australia, went to university in Sydney, and has lived since 1986 in London.

**Comment by samdutton** [comment]
Sam Dutton has worked with the Google Chrome team as a Developer Advocate since 2011. 

---

Sam Dutton has worked with the Google Chrome team as a Developer Advocate since 2011. He has organised and presented at a number of events, created and taught several web development courses, and worked on a range of videos, codelabs and written guidance covering PWA, performance, media, image and 'Next Billion Users' initiatives. 

He maintains [simpl.info](https:/simpl.info), which provides simplest possible examples of HTML, CSS and JavaScript. 

Sam grew up in South Australia, went to university in Sydney, and has lived since 1986 in London.

**Comment by zachleat** [comment]
Zach is a Web Developer with [Filament Group](http://www.filamentgroup.com/). He’s currently fixated on [web fonts](https://www.zachleat.com/web/fonts/) and [static site generators](https://www.zachleat.com/web/introducing-eleventy/). His [public speaking résumé](https://www.zachleat.com/web/speaking/) includes talks in eight different countries at events like JAMstack_conf, Beyond Tellerrand, Smashing Conference, CSSConf, and [The White House](https://www.zachleat.com/web/whitehouse/). He also helps herd [NEJS CONF](http://nejsconf.com/) and the [NebraskaJS](http://nebraskajs.com) meetup.

**Comment by tomayac** [comment]
Thomas Steiner is a Web Developer Advocate at Google Hamburg, focused on making the Web a better place through standardization, creating and sharing best practices, and doing research. He blogs at [blog.tomayac.com](https://blog.tomayac.com/) and tweets as [@tomayac](https://twitter.com/tomayac).

**Comment by rachellcostello** [comment]
Rachel Costello is a Technical SEO & Content Manager at [DeepCrawl](https://www.deepcrawl.com/).

--------

Rachel Costello is a Technical SEO & Content Manager at [DeepCrawl](https://www.deepcrawl.com/) and an international conference speaker who spends her time researching and communicating the latest developments in search. Rachel currently manages the production of [technical SEO white papers](https://www.deepcrawl.com/knowledge/white-papers/) and research pieces for DeepCrawl, and is a regular columnist for [Search Engine Journal](https://www.searchenginejournal.com/author/rachel-costello/).

**Comment by khempenius** [comment]
Katie Hempenius is an engineer on the Chrome team where she works on making the web faster.

**Comment by AVGP** [comment]
Martin Splitt is a developer advocate on the web ecosystem team at Google where he works on keeping the web discoverable

**Comment by bkardell** [comment]
Brian Kardell is developer advocate at [Igalia](https://igalia.com),  standards contributor, [blogger](https://bkardell.com), and is currently the W3C Advisory Committee Representative for the [Open JS Foundation](https://openjsf.org/). He was a founder of the Extensible Web Community Group and co-author of [The Extensible Web Manifesto](https://extensiblewebmanifesto.org).

**Comment by patrickhulce** [comment]
Patrick Hulce, author of [third-party-web](https://github.com/patrickhulce/third-party-web).

-----------------

Patrick Hulce is an ex-Chrome engineer, founder of [Eris Ventures](https://eris.ventures/), core team member of [Lighthouse](https://github.com/GoogleChrome/lighthouse) and [Lighthouse CI](https://github.com/GoogleChrome/lighthouse-ci), co-organizer of the [DallasJS](https://www.meetup.com/DallasJS/) meetup, and author of the [third-party-web](https://github.com/patrickhulce/third-party-web) project.

**Comment by alankent** [comment]
Alan Kent is a Developer Advocate at Google focusing on e-commerce and content ecosystems. He blogs at alankent.me and tweets as @akent99.

**Comment by paulcalvano** [comment]
Paul Calvano is a Web Performance Architect at [Akamai](https://www.akamai.com/), where he helps businesses improve the performance of their websites. He's also a co-maintainer of the HTTP Archive project. You can find him tweeting at [@paulcalvano](https://twitter.com/paulcalvano), blogging at [http://paulcalvano.com](http://paulcalvano.com) and sharing HTTP Archive research at [https://discuss.httparchive.org](https://discuss.httparchive.org).

**Comment by arturjanc** [comment]
Artur Janc is an Information Security Engineer at Google, working on designing and adopting web platform security mechanisms across Google and the web at large. He argues with people on the internet as @arturjanc on Twitter.

**Comment by una** [comment]
Una Kravets is a Brooklyn-based international public speaker, technical writer, and Developer Advocate for Material Design at Google. Una hosts the [Designing the Browser](https://www.youtube.com/watch?v=YK8GZBx3hpg) web series and the [Toolsday](https://spec.fm/podcasts/toolsday) developer podcast. Follow her on [Twitter](https://twitter.com/una) to find her musings on creative CSS, user experiences, and web development best practices.

**Comment by rviscomi** [comment]
Here's mine:

> Rick Viscomi is a Senior Developer Programs Engineer at Google, working on web transparency projects like the HTTP Archive and Chrome UX Report, and studying the intersection of how websites are built and experienced. Rick is the host of [The State of the Web](https://www.youtube.com/playlist?list=PLNYkxOF6rcIBGvYSYO-VxOsaYQDw5rifJ) in which experts discuss how the web is trending. Rick is the coauthor of [Using WebPageTest](http://usingwpt.com/), a guide for testing web performance, and writes frequently about the web on [dev.to](https://dev.to/rick_viscomi) and on Twitter at [@rick_viscomi](https://twitter.com/rick_viscomi).

I've also got bios for a couple of Accessibility authors via email.

@kleinab:

> Abigail Klein is a Google software engineer. She worked on Google Docs, Sheets, and Slides web accessibility where she improved screen reader support and added [automatic captions to Google Slides](https://www.blog.google/outreach-initiatives/accessibility/whats-you-say-present-captions-google-slides/). She currently works on Google Chrome and ChromeOS accessibility. She has a bachelor's and master's degree in computer science from MIT, where she co-founded an assistive technology hackathon and was a lab assistant and guest lecturer of the assistive technology class.

Nektarios Paisios:

> Nektarios Paisios is a software engineer working on Chrome accessibility for the last 5 years. He primarily focuses on making Chrome compatible with third party assistive software such as screen readers and screen magnifiers. Before working on Chrome accessibility, Nektarios worked in various other roles at the company, such as GSuite accessibility and display ads. Nektarios holds a Ph.D. in Computer Science from New York University.

**Comment by andydavies** [comment]
Short:

Andy Davies is a Freelance Web Performance Consultant. Co-author of using WebPageTest, and also an organiser of the London Web Performance meet up.

Long:

Andy Davies is a Freelance Web Performance Consultant and has helped some of the UK's leading retailers, newspapers and financial services companies to make their sites faster.

He wrote The Pocket Guide to Web Performance, is coauthor of Using WebPageTest and also an organiser of the London Web Performance meetup. 

You can find Andy on Twitter as [@AndyDavies](https://twitter.com/andydavies), and he occasionally blogs at [https://andydavies.me](https://andydavies.me)

**Comment by kleinab** [comment]
Abigail Klein is a Google software engineer. She worked on Google Docs, Sheets, and Slides web accessibility where she added [automatic captions to Google Slides](https://www.blog.google/outreach-initiatives/accessibility/whats-you-say-present-captions-google-slides/), as well as improving screen reader, braille, screen magnifier, and high contrast support. She currently works on Google Chrome and ChromeOS accessibility. She has a bachelor's and master's degree in computer science from MIT, where she co-founded an assistive technology hackathon and was a lab assistant and guest lecturer of the assistive technology class.

**Comment by ernee** [comment]
Renee Johnson is a web and product consultant. She spends most of her time supporting individuals, small businesses, and teams on their web projects.

**Comment by rviscomi** [comment]
Only remaining bios needed are: @housseindjirdeh @colinbendell @obto @amedina. When you all get a chance, can you please add them here? Thank you!

**Comment by amedina** [comment]
Alberto Medina is a Developer Advocate in the Web Content Ecosystems Team at Google, focusing on advancing the proliferation of quality content on the web via progressive technologies such as Amp, and the use of modern Web APIs. Alberto's work currently has a strong focus on Content Management Systems as he leads an area of Content Ecosystem called CMS Developer Relations.

**Comment by colinbendell** [comment]
Colin is part of the CTO Office at [Cloudinary](https://cloudinar.com) and co-author of the O'Reilly book [High Performance Images](https://www.oreilly.com/library/view/high-performance-images/9781491925799/). He spends much of his time at the intersection of high volume data, media, browsers and standards. You can find him on tweeting [@colinbendell](https://twitter.com/colinbendell) and at blogging at [https://bendell.ca](https://bendell.ca)

**Comment by housseindjirdeh** [comment]
Houssein is a Developer Advocate at Google working on speed, performance and the web framework ecosystem. He tweets at @hdjirdeh and blogs at https://houssein.me/.

**Comment by obto** [comment]
David Fox is the lead usability researcher and founder of LookZook, a company obsessed with finding out everything there is to know about building web experiences that meet user expectations. He is a website psychologist who digs into sites to learn not just what users are struggling with, but why, and how to best improve their experience. He is also a Google Chromium contributor, speaker, and provider of webinars and UX training.
