### ISSUE TITLE
Focus on the search input field after expanding the search widget

### ISSUE THREAD

**Issue by rviscomi** [HTTPArchive/almanac.httparchive.org#2396]
After clicking on the "Search" heading, the search widget expands to reveal the input field and submit button. When the field is revealed, I would expect it to receive focus so that I can immediately start typing. On one hand it seems like an accessibility improvement to reduce the number of steps to complete an action, but on the other it may be disorienting to click a button then have the focus moved somewhere else. If necessary, is there any way we could mitigate the latter with ARIA?

![image](https://user-images.githubusercontent.com/1120896/138190554-4da68fd1-2cb2-457b-b81e-ac00e82b3983.png)

**Comment by tunetheweb** [comment]
Go for it!

**Comment by tunetheweb** [comment]
@nhandota how you getting on? Anything I can do to help?
