### ISSUE TITLE
Form a team of web designers and developers

### ISSUE THREAD

**Issue by rviscomi** [HTTPArchive/almanac.httparchive.org#24]
We're looking for web designers and developers to help build the UX of the Almanac itself. It will be a static website home to each annual report and read like an ebook to help users navigate the various sections and chapters.

Designers should have the bandwidth throughout July and August to conceptualize the UX of the website and the data visualizations used by the chapters. This is a big burden so we're open to contracting this out. See [this Upwork post](https://www.upwork.com/jobs/~01a935116ea4200f1c) for the full details of the design work.

_Update: We've hired contractors to do the illustration and design work. You can join the discussion in the [#web-almanac-design](bit.ly/http-archive-slack) Slack channel._

Developers will be responsible for implementing the designers' vision and merging it with the authors' written content, while following accessibility and SEO best practices.

Join the team: @HTTPArchive/developers 
See open issues: [Development label](https://github.com/HTTPArchive/almanac.httparchive.org/issues?q=is%3Aissue+is%3Aopen+label%3ADevelopment)

**Comment by rviscomi** [comment]
@matijagrcic @tjmonsi you've expressed interest in helping with web development. Still interested?

**Comment by mikegeyser** [comment]
Hi! If I can be of assistance, I would love to help.

**Comment by mikegeyser** [comment]
According to the plan, there should already be some development activity. I presume that the development will be concentrated towards the end of the project, but is there anything that we can get started on so long? Also, which would be the most appropriate medium for questions/discussion? (before I spam this thread)

**Comment by rviscomi** [comment]
Great question! We have a few media for discussion:

- development specific topics can be discussed in the GitHub team chat at https://github.com/orgs/HTTPArchive/teams/developers
- general Almanac topics can be discussed in the #web-almanac channel on the [HTTP Archive Slack](bit.ly/http-archive-slack)
- specific tasks can be discussed in GitHub issues

In this case the specific task is "start building the development environment", so I'll create that issue and we can discuss implementation details there.

**Comment by tjmonsi** [comment]
Hi Rick,

Yep I am still interested. I just need to know what to do and how I can
help. I am not really adept yet on implementing the data to graphs (from
BigQuery or even knowing the query string on Bigquery to show the data).

**Comment by rviscomi** [comment]
Thanks @tjmonsi! If you're also interested in learning how to query the dataset and extracting stats for each chapter you can join the @HTTPArchive/data-analysts team. For this team we're looking for web developers/designers to help build the UX of the Almanac website. If that still sounds like something you're interested in, you can join the dev team at this link: @HTTPArchive/developers, and also see #25 for our first issue.

**Comment by noahblon** [comment]
Hi @rviscomi!  I'd be down with helping on the development side.

**Comment by chaluvadis** [comment]
Hi @rviscomi I would love to help in UI development.

**Comment by gustavofsantos** [comment]
Hi 🖐️ I can help too

**Comment by rviscomi** [comment]
Thanks @noahblon @chaluvadis @gustavofsantos!! Added each of you to the @HTTPArchive/developers team. ❤️

**Comment by tjmonsi** [comment]
@rviscomi it seems I can't find the @HTTPArchive/developers team :) I also like to understand bigquery because I am also working on it on a different project. Learning how you guys do it will essentially make my work on another project easier :)

**Comment by matijagrcic** [comment]
@rviscomi Still interested. Sorry if not active, loads of things happening. What's needed implementing?

**Comment by rviscomi** [comment]
Great. @tjmonsi @matijagrcic I've added you both to the team. Right now we're just getting the web server set up in #25. Once that's done we'll move on to creating some base templates and a temporary splash page to be deployed to almanac.httparchive.org while the project is under construction.

**Comment by arswaw** [comment]
Maybe we could use Vue for this? We could combine it with ES6 Modules. Therefore we could keep the website static but interactive, and not have to add Node to the mix.

**Comment by rviscomi** [comment]
@arswaw mind if we move the discussion of tech stack to #25?

**Comment by KJLarson** [comment]
Are there any jobs that a junior web developer just getting started could help with?

**Comment by rviscomi** [comment]
@KJLarson we're just getting off the ground but I'm sure there will be opportunities for folks like yourself! We'll tag intro-level tasks with the [Good First Issue](https://github.com/HTTPArchive/almanac.httparchive.org/labels/good%20first%20issue) label so you can more easily find them. If you're interested I'll add you to the developer team.

**Comment by KJLarson** [comment]
@rviscomi - I would love to be part of the team!

**Comment by rviscomi** [comment]
Great! I've sent you an invite to @HTTPArchive/developers. You may need to go to https://github.com/HTTPArchive to accept if you don't see the email.

**Comment by MSakamaki** [comment]
@rviscomi  I want to help UI development!

**Comment by rviscomi** [comment]
Added. Thanks @MSakamaki!

**Comment by tanhengyeow** [comment]
Hi @rviscomi !! I'll be happy to help with the development side 😄

**Comment by Mehedihasan-wp** [comment]
I Would Love To join your project 
It Will Be An Amazing Experience

**Comment by rviscomi** [comment]
Thanks @tanhengyeow @Mehedihasan-wp! I've invited you both to the developers team. You can accept the invite at https://github.com/HTTPArchive or via email.

@Mehedihasan-wp are you able to add your full name to your GitHub profile so we can credit you in the Almanac?

**Comment by anoblet** [comment]
I'm interested in helping on the UI/UX side. I have experience with lit-html and lit-element.

**Comment by rviscomi** [comment]
Would be great to have you @anoblet! Sent you an invite to the Developers team! You can start exploring open [Development](https://github.com/HTTPArchive/almanac.httparchive.org/labels/Development) issues to get caught up on what we're working on.

**Comment by AymenLoukil** [comment]
@rviscomi count me in for the SEO part. I could assist designers and developers to follow SEO best practices (review, SEO-QA..Etc).

**Comment by rviscomi** [comment]
Great thanks @AymenLoukil! I can think of something SEO related for you to do right away. I'll create the issue and assign it to you.
