### ISSUE TITLE
Update 2021 contributors config

### ISSUE THREAD

**Issue by rviscomi** [HTTPArchive/almanac.httparchive.org#2409]
Update [2021.json](https://github.com/HTTPArchive/almanac.httparchive.org/blob/main/src/config/2021.json) with the info and team assignments for all 2021 contributors.

**Comment by tunetheweb** [comment]
Note there's a check in our CI that won't allow people to be added to the config, until the chapter includes them in the meta data (and vice versa).

But can add non-chapter people: developers (have been doing this throughout), designers...etc.
