### ISSUE TITLE
Create HTTP Archive Discuss topic.

### ISSUE THREAD

**Issue by tunetheweb** [HTTPArchive/almanac.httparchive.org#2414]
Even though we might be adding additional ways to comment on chapters in #2192 we should still have https://discuss.httparchive.org topics for each chapter as well I think.

Rick do you want to do the honours and create these as we're going to need these soon as people start converting to markdown.

**Comment by rviscomi** [comment]
I was thinking that we would use web mentions instead of comments, rather than in addition to them. Engagement hasn't been high enough to justify keeping the comments IMO.
