### ISSUE TITLE
Suggestion for the 2022 edition: no systematic distinction of desktop vs. mobile?

### ISSUE THREAD

**Issue by maudnals** [HTTPArchive/almanac.httparchive.org#2423]
(Initially raised in the Privacy chapter review)

The mobile/desktop distinction may be very relevant for some metrics, say performance, and typically less relevant for others. 
Some examples: "% websites that have a privacy policy", "% websites that have a Referrer-Policy header", etc.

I definitely understand the argument for consistency across the Almanac.
But for next year, I'm wondering whether some sections could free themselves of this distinction⏤we could gain in concision and signal vs noise, maybe?

cc @VictorLeP for thoughts!

**Comment by tunetheweb** [comment]
Some of the chapters (e.g. [CSS 2020](https://almanac.httparchive.org/en/2020/css#:~:text=We%20crawl%20our%20pages%20in%20both%20desktop%20and%20mobile%20mode%20but%20for%20a%20lot%20of%20the%20data%20they%20give%20similar%20results%20so%2C%20unless%20otherwise%20noted%2C%20stats%20presented%20in%20this%20chapter%20refer%20to%20the%20set%20of%20mobile%20pages.)) make the following note:

> We crawl our pages in both desktop and mobile mode but for a lot of the data they give similar results so, unless otherwise noted, stats presented in this chapter refer to the set of mobile pages.

So, where it's not relevant, you don't need to include analysis of both. And there is definitely no need to include two charts if they are near identical.

However, some chapters are also surprised when they see differences, as they may have assumed there would not be any, and I'd be concerned we'd make those assumptions by not including analysis of both.

Additionally, for many charts (but not all, I agree) including both sets of data is no additional effort. But as I say if a particular chart is only showing data for one, then there is no need to include both in the chapter as long as you add a caveat like above.

**Comment by maudnals** [comment]
Great I wasn't aware, thank you @tunetheweb for the example disclaimer and insights.

**Comment by tunetheweb** [comment]
BTW worth noting that when you've a choice between the two, and need to decide which to show and it doesn't matter which, then we generally prefer to use the mobile stats (unless there's a good reason to use desktop) for the following reasons:
- We're in a mobile-first world nowadays
- Dataset is bigger
- Lighthouse only available for mobile
