### ISSUE TITLE
Avoid converting double hyphens to emdashes

### ISSUE THREAD

**Issue by rviscomi** [HTTPArchive/almanac.httparchive.org#2445]
When writing markdown content that includes two consecutive hyphens (`--`), ~prettier~ smartypants converts it into an emdash (`—`). This is a nice shortcut for blocks of text, but there may be use cases where the hyphens are preferable. Consider disabling this prettier feature.

Two use cases I ran into:

1. HTML comments in the markdown file: `<!-- {{ figure_markup(...) }} -->`. I got a prettier parser error like this:
  ```
  SyntaxError: Unexpected character "EOF" (651:9)
    649 | ) }}
    650 |
  > 651 | &#8212;>
  ```
  `&#8212;` is the HTML entity for emdash. I worked around this by switching to Jinja comments instead: `{# {{ figure_markup(...) }} #}`

2. Describing CSS custom property names, for example [`--*`](https://docs.google.com/spreadsheets/d/12vQIA0xsC5Jr3J9Sh03AcAvgFjMAmP1xSS6Tjai9LF0/edit#embedrangeref=[[[%22204136042%22,1,8,6,9]]]). There isn't a parser error this time, but `—*` is not the correct CSS. I worked around this by using the HTML entity for the hyphen instead: `&#8209;&#8209;*`.

**Comment by tunetheweb** [comment]
I think this is Showdown not Prettier.

I would say the following:
1. This should be a Jinja comment IMHO. Shouldn't really be exposing our internals externally (even in comments).
2. This should be wrapped in code formatting. Then it doesn't convert.

Saying that, can't see any reason NOT to turn this off, as don't need it and would avoid above issues (even if technically I don't think we should be using them). But can't find an easy way to turn this off. But will keep digging. Worst case we can convert back with some custom JS.

**Comment by tunetheweb** [comment]
Found it. It's not prettier but smartypants (the library we use for typographic quotes).

PR coming up - though still think you should change to use code formatting for code.
