### ISSUE TITLE
Filter performance metrics by sites that use service workers

### ISSUE THREAD

**Issue by demianrenzulli** [HTTPArchive/almanac.httparchive.org#2454]
Hi folks,

From our meeting with @siakaramalegos in the context of the analysis of performance and connection types, we thought that it would be interesting in 2022 to go deeper into the relationship between performance and service workers, to see if we can extract some conclusions.

At a minimum a simple idea could be to cross the data obtained by the writers of the performance chapter, with our [service worker heuristic](https://github.com/HTTPArchive/legacy.httparchive.org/blob/7f590757132e4680aebf6409173d6d9620571c6f/custom_metrics/pwa.js#L152) and create a separate performance chart only for sites that use service workers. 
To make sure that we don't count those sites that have an empty SW or use it only for push notifications, we could even go beyond and only filter those that use service workers and the cache object, for example.

I'm leaving this issue so we can consider this analysis in future iterations.

cc // @rviscomi @tunetheweb @jeffposnick @philipwalton

**Comment by tunetheweb** [comment]
It’s certainly something we could do and I could easy knock up a query and chart on the Core Web Vitals numbers from CrUX based on our service worker heuristic for this years chapter of you wish.

However, if worry about drawing too many conclusions from this. As you’ve shown in your chapter, Service Workers are still a relatively advanced and niche technology. So are sites that use SW also sites that are more aware of performance optimisations? So is it the fact these sites are into advanced  technologies that make them faster? Or is it the presence of service workers that makes them faster? That’s assuming they are faster of course - it could be that they are actually slower!

Another option would be to add detection to Wappalyzer so they will show in the [Core Web Vitals Technology report](https://datastudio.google.com/u/0/reporting/55bc8fad-44c2-4280-aa0b-5f3f0cd3d2be/page/M6ZPC). Could either add service worker detection for for popular libraries like Workbox. We’ve shown neither of these are easy or without false positives but maybe you could take your learnings of your heuristic and submit a PR to them for some of this?

**Comment by demianrenzulli** [comment]
> As you’ve shown in your chapter, Service Workers are still a relatively advanced and niche technology. So are sites that use SW also sites that are more aware of performance optimisations? So is it the fact these sites are into advanced technologies that make them faster? 

I believe this is correct. If we add the service worker filter, we might be implicitly counting more sophisticated sites, and it's likely that they'll have a better performance just for having more resources to invest on it.

In any case, I have to admit that I'm curious about the results of that analysis (but perhaps not to include in a chapter). Another thing that might be interesting to compare is: how the performance of sites that use service workers varies when using / not using Workbox?

> Another option would be to add detection to Wappalyzer so they will show in the Core Web Vitals Technology report. 

I'm not very familiar with this report. Is [this](https://discuss.httparchive.org/t/new-dashboard-the-core-web-vitals-technology-report/2178) the best resource to know more about it? Where can we file an issue so they can consider this proposal?

**Comment by tunetheweb** [comment]
The report is driven by Wappalyzer which we run during our crawl and then join with CrUX data for the report. So to add have a look at the Wappalyzer repo: https://github.com/AliasIO/wappalyzer

Wappalyzer is a third-party app, not part of HTTP Archive nor CrUX and they detect technologies by looking for signatures (e.g. a unique JS variable or a script name). We then use it in our crawl. If you hunt round that repo you should be able to see lots of other examples of how it detects things. Or raise and issue with the necessary technical details and hope the maintainers pick it up. But much better if you can do the PR 🙂

**Comment by demianrenzulli** [comment]
Cool, I'm closing this issue by now and I'll take a look at that repo to see if it makes more sense to move it there. Thank you!

**Comment by tunetheweb** [comment]
> In any case, I have to admit that I'm curious about the results of that analysis (but perhaps not to include in a chapter). Another thing that might be interesting to compare is: how the performance of sites that use service workers varies when using / not using Workbox?

Ran the stats and they are not good for PWA advocates!

![image](https://user-images.githubusercontent.com/10931297/140830923-7572c0e0-2480-4554-b46c-5083a039e607.png)

Further breakdown for mobile:

![image](https://user-images.githubusercontent.com/10931297/140830980-ae7ad212-1d10-4361-9372-841911749263.png)


My only thoughts are that PWA sites could be more complex in nature than many home sites and that would explain why they perform poorer?

Data here: https://docs.google.com/spreadsheets/d/1fIRdjSui_Px3N-OUeVSQPL_7Ts-GTqScHSXWj_3TTOE/edit?usp=sharing
