### ISSUE TITLE
Correct 'sameAs' schema

### ISSUE THREAD

**Issue by jono-alderson** [HTTPArchive/almanac.httparchive.org#2459]
Various templates and partials declare 'sameAs' schema, but do so using the lowercase string `sameas`. 
See https://github.com/HTTPArchive/almanac.httparchive.org/search?q=sameas

This is technically invalid (though most consumers should manage reasonably well); the string should be corrected to `sameAs`.

**Comment by rviscomi** [comment]
Great catch! @HTTPArchive/developers this seems like a good first issue if anyone is looking for a small task.
