### ISSUE TITLE
i18n bug on TOC page: "English - not available in English"

### ISSUE THREAD

**Issue by rviscomi** [HTTPArchive/almanac.httparchive.org#2476]
![image](https://user-images.githubusercontent.com/1120896/141606475-0e968e74-1027-4b97-8cef-0c6a3a16d8ec.png)

https://20211112t235731-dot-webalmanac.uk.r.appspot.com/en/2021/table-of-contents

While staging https://github.com/HTTPArchive/almanac.httparchive.org/pull/2447/ I ran into an i18n edge case. Not totally sure how I got into this state. It had to do with trying to switch langs/years to find the Russian translation of the 2021 PWA chapter.

Chapters that were written in English say "English - not available in English". I wouldn't expect this to be added at all when the current lang is `en`.

**Comment by rviscomi** [comment]
This might just be a bug as long as 2021 is unreleased

**Comment by tunetheweb** [comment]
Usually a sign you haven't done an `npm run generate` or a server restart since the `src/config/2021.json` file was updated.

An English chapter should always either be available or "coming soon".

**Comment by rviscomi** [comment]
That seems to have been the case, good call!
