### ISSUE TITLE
Create an early release of the 2021 edition

### ISSUE THREAD

**Issue by rviscomi** [HTTPArchive/almanac.httparchive.org#2508]
- [x] Launch all written, reviewed, and edited chapters.
- [x] Any chapters at risk of missing the full launch on December 1 should be omitted from the Table of Contents to avoid overpromising. (Note: if these chapters are caught up by December 1, they'll be released as usual)
- [x] The 2021 home page should be changed from "Coming soon" to the usual text, including the contributor section and 2021 featured chapters.
- [x] Update the Contributors page to reflect as many 2021 contributors as possible, in addition to those who worked on the completed chapters.
- [x] Include the updated 2021 Methodology page.
- Leave the Foreword blank for now.
- Go live Tuesday, November 16 or Wednesday the 17th.

**Comment by VictorLeP** [comment]
Possibly relevant comment from https://github.com/HTTPArchive/almanac.httparchive.org/pull/2507#issuecomment-969474344:
> How much of an issue is it that we're linking to an unfinished chapter, in our case the Security _[and actually also HTTP]_ chapter? It throws up a page with not much more than a big [TODO](https://20211112t221945-dot-webalmanac.uk.r.appspot.com/en/2021/security) (which comes from how the Markdown files are [initialized](https://github.com/HTTPArchive/almanac.httparchive.org/blob/main/src/content/en/2021/security.md) - something like "Coming soon!" would be nicer, but the TODO is effectively hardcoded for now) 

> They should redirect back to the home page for now. Will check it out before the first launch.

**Comment by tunetheweb** [comment]
Fixed in https://github.com/HTTPArchive/almanac.httparchive.org/pull/2509

**Comment by tunetheweb** [comment]
Think we're good to go. Staged URL of `main` at the moment: https://20211116t102359-dot-webalmanac.uk.r.appspot.com/en/2021/

(P.S. Remember to run `rm -f ./templates/*/*/chapters/*` is restaging to remove old chapters you might have generated from other branches. The `deploy` script will do this automatically for you but not the `stage` script cause of you want to re-stage without having to do a full regeneration).

**Comment by rviscomi** [comment]
Updated the staging URL with `main`
