### ISSUE TITLE
Blockquotes count as a figure

### ISSUE THREAD

**Issue by VictorLeP** [HTTPArchive/almanac.httparchive.org#2520]
Blockquotes seem to be turned into a figure (and can be linked to as such), see [Figure "1" of the Performance chapter](https://20211116t102359-dot-webalmanac.uk.r.appspot.com/en/2021/performance#fig-1). However, this "figure" has no caption, having the strange effect that the first figure whose number is visible is [Figure 9.2](https://20211116t102359-dot-webalmanac.uk.r.appspot.com/en/2021/performance#fig-2). Is this intentional?

**Comment by tunetheweb** [comment]
Fixed and re-staged to same URL. Thanks!
