### ISSUE TITLE
Edit 2021 chapters

### ISSUE THREAD

**Issue by tunetheweb** [HTTPArchive/almanac.httparchive.org#2525]
📢  Attention Editors: this issue will be used to track progress on the 2021 chapters that are ready for editing.

When you're ready to edit a chapter, edit this comment to put your name next to the first unchecked and unclaimed chapter. Chapters will be added to the queue as they become ready for editing.

Refer to the [Editors' Guide](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Editors'-Guide) for general best practices.

Staged URL (with all above chapters turned on): https://20211116t174953-dot-webalmanac.uk.r.appspot.com/en/2021/

- [x] Structured Data - @tunetheweb 
- [x] Third Parties - @rviscomi 
- [x] Performance - @rviscomi / @tunetheweb 
- [x] Privacy - @tunetheweb 
- [x] Capabilities - @tunetheweb 
- [x] PWA - @rviscomi 
- [x] Resource Hints - @rviscomi 
- [x] CSS - @shantsis 
- [x] CMS - @shantsis 
- [x] Mobile Web - @shantsis 
- [x] Ecommerce - @shantsis 
- [x] Accessibility - @tunetheweb 
- [x] CDN - @shantsis 
- [x] Security - @tunetheweb 
- [x] WebAssembly - @shantsis 
- [x] JavaScript - @shantsis @rviscomi 
- [x] Page Weight - @tunetheweb 
- [x] Compression - @shantsis 
- [x] Jamstack - @shantsis 
- [x] SEO - @tunetheweb 
- [x] HTTP - @shantsis 
- [x] Markup - @rviscomi 
- [x] Media - @tunetheweb 
- [x] Caching - @tunetheweb

**Comment by rviscomi** [comment]
@HTTPArchive/editors if you're available please grab a chapter to edit! 🙏 🚀

**Comment by tunetheweb** [comment]
Added the stage URL which I'll try to keep up to date with all chapters (including unedited ones) for those unable to run the site locally themselves.

**Comment by tunetheweb** [comment]
CDN chapter is available for editing (staging link at top updated).

**Comment by shantsis** [comment]
> CDN chapter is available for editing (staging link at top updated).

Claimed!

**Comment by tunetheweb** [comment]
It's almost like I was hoping you'd say that! 😁

**Comment by tunetheweb** [comment]
WebAssembly is ready for editing. I've already done a pass through on technical side.

**Comment by shantsis** [comment]
> WebAssembly is ready for editing. I've already done a pass through on technical side.

I’ll take it and start in the next day or 2

**Comment by tunetheweb** [comment]
JavaScript has ready for copy editing. Again a technical check has been completed on markup/figures/structure so just need to concentrate on the copy.

**Comment by tunetheweb** [comment]
Jamstack is ready for copy editing if you have a chance @shantsis

**Comment by shantsis** [comment]
> Jamstack is ready for copy editing if you have a chance @shantsis

Sweet I’ll open a PR for it later today

**Comment by tunetheweb** [comment]
HTTP is ready for editing. Warning, there's a fair bit of text and background in this one but I'm OK with it. I've given it an initial go through, but been working on this chapter a fair bit so could do with an independent pair of eyes to be honest!

**Comment by rviscomi** [comment]
Markup is ready for editing. I've done a light edit already in the Doc so this should be relatively quick.
