### ISSUE TITLE
Licensing and attribution

### ISSUE THREAD

**Issue by rviscomi** [HTTPArchive/almanac.httparchive.org#26]
In the interest of openness and transparency, we want the Almanac to be free, shareable, and extensible. At the same time, authors deserve attribution for their content. And everyone else who has helped build this report (now over 50 people!) should get some kind of recognition.

It's my intent to give credit to everyone who participates in the project in any form on a "Contributors" page. Each chapter will also name their respective authors and reviewers.

We should also provide an easy way to grab quotes from anywhere in the Almanac and see exactly how we expect them to be attributed. For example, if I write something in the Performance chapter that gets quoted, maybe we should annotate it with "Rick Viscomi, 2019 Web Almanac (II.6)" or similar.

What would not be ok is if someone scrapes all of the content and sells it. Our license should have protections against that sort of thing. This repo is marked as [Apache 2.0](https://github.com/HTTPArchive/almanac.httparchive.org/blob/master/LICENSE) which permits commercial use, but that should apply only to our _source code_ not the authored content.

Does anyone have experience with this kind of thing? Any ideas for protecting our work while making it as open as possible?

**Comment by lflores-ms** [comment]
Hi @rviscomi -- curious if there was any conclusion on attribution of content from reports? Looking to quote data from Web Almanac and monthly httparchive reports. Is there some recommendation for how to do it?

**Comment by tunetheweb** [comment]
A simple "According to the 2024 Web Almanac" or similar is sufficient. Or if including our charts, this is included in the chart.

For more academic-style quotes we have started providing Bibex details. For example: https://almanac.httparchive.org/en/2024/javascript#cite
