### ISSUE TITLE
Optimize home page images

### ISSUE THREAD

**Issue by rviscomi** [HTTPArchive/almanac.httparchive.org#262]
See https://webspeedtest.cloudinary.com/results/191031_ZB_fcfd29e8019c163d4634ca8a87eb27ab

Some of the illustrated characters are used on other pages and I'm not sure if these suggested optimizations would negatively affect their resolution. But everything else LGTM.

- [x] Compress methodology-characters.png
- [x] Compress home-hero-2019.png
- [ ] Compress home-hero.png and ensure it is only loaded for small viewports (see #361)
- [x] Upload a higher resolution version of logo.png and retest
- [x] Upload another version of ha-home.png and retest (this one seems like a few pixels got cut off on the left side)

**Comment by ymschaap** [comment]
* I added retina support for logo.png in #268

**Comment by AymenLoukil** [comment]
Methodoly page image could be more compressed
https://almanac.httparchive.org/static/images/methodology-banner.png
Another issue ?

**Comment by rviscomi** [comment]
@AymenLoukil could you file a new issue?

**Comment by JMPerez** [comment]
I'm thinking of sending a PR where I optimize all images in the static folder. In order to avoid regressions, we could as well integrate something like https://imgbot.net/ or https://github.com/calibreapp/image-actions. What do you think?

**Comment by rviscomi** [comment]
@JMPerez sounds like a great idea. We may also want something more manual for handling desktop/mobile size variations but a lossless optimizer would be a big help.
