### ISSUE TITLE
Unversioned file webmentions.js was used

### ISSUE THREAD

**Issue by rviscomi** [HTTPArchive/almanac.httparchive.org#2625]
While running the site locally with `npm run start` I'm seeing this error:

```
ERROR:root:An un-versioned file was used: /static/js/webmentions.js
```

**Comment by tunetheweb** [comment]
That’s expected. It’s not in the versioned file yet(which is created on each  release), so doesn’t have a cache buster url param yet. Which if it went out to prod would be a potential problem if we needed a breaking change to this whole. It’ll be there after tomorrow’s release.

probably should create a dummy entry when adding new JS files in the future to avoid this.
