### ISSUE TITLE
Optimize web font loading

### ISSUE THREAD

**Issue by rviscomi** [HTTPArchive/almanac.httparchive.org#263]
See https://www.webpagetest.org/result/191031_ZB_fcfd29e8019c163d4634ca8a87eb27ab/3/details/#waterfall_view_step1

![image](https://user-images.githubusercontent.com/1120896/67912113-2dc71f00-fb5f-11e9-81a3-03dba3bcbb12.png)

Requests 21-23 for the web fonts are blocked on DNS, TCP, and SSL connection steps. Use a preconnect hint to warm up the request to https://fonts.gstatic.com.

**Comment by welenofsky** [comment]
@rviscomi I created PR #265 to add the preconnect to two of the templates that had google fonts.
