### ISSUE TITLE
Enable deep-linking to each contributor

### ISSUE THREAD

**Issue by rviscomi** [HTTPArchive/almanac.httparchive.org#264]
On the [Contributors page](https://almanac.httparchive.org/en/2019/contributors) each contributor element should have a unique ID attribute equal to the contributor ID. This way we could navigate to the page with a URL of `/contributors#rviscomi` or similar and the page will jump down to my entry on the page.

**Comment by ymschaap** [comment]
I will pick this up in #268.

**Comment by ymschaap** [comment]
I've fixed this in #268.
