### ISSUE TITLE
Webmention Replies not rendered properly on mobile

### ISSUE THREAD

**Issue by tunetheweb** [HTTPArchive/almanac.httparchive.org#2666]
https://almanac.httparchive.org/en/2021/third-parties#reactions

![image](https://user-images.githubusercontent.com/10931297/144296380-c131f72a-02b9-40aa-8bdd-7b1ae0c38ba1.png)

**Comment by SaptakS** [comment]
I will take a look at it in a bit.

**Comment by SaptakS** [comment]
Seems a padding is getting overwritten. Will put in a fix soon.

**Comment by tunetheweb** [comment]
OK I went with a different fix in #2667 but happy to go with yours if it's the better way.

**Comment by SaptakS** [comment]
Left a comment on the PR. I think this fix uses the space better, whereas mine would make it look exactly like the desktop (which wastes some space in the left I guess and space is crucial in mobile screen)
