### ISSUE TITLE
Investigate 404s

### ISSUE THREAD

**Issue by rviscomi** [HTTPArchive/almanac.httparchive.org#2675]
The App Engine logs are showing some 404 errors. Investigate if there are any bad internal links that we can fix.

URI | # Errors
-- | --
/apple-touch-icon.png/ | 239
/apple-touch-icon-precomposed.png/ | 200
/static/images/2021/css/favicon.ico | 66
/.well-known/assetlinks.json/ | 15
/en/2021/linear-gradient(rgba(0,%200,%200,%200)%20calc(70%%2 | 14
/apple-touch-icon-120x120.png/ | 13
/apple-touch-icon-120x120-precomposed.png/ | 13
/it/2020/en | 12
/en/2021/null | 12
/en/2020/en | 9
/static/images/2021/markup/favicon.ico | 7
/static/images/2021/javascript/favicon.ico | 6
/feed/ | 6
/rss/ | 5
/static/pdfs/web_almanac_2021_de.pdf | 5
/en/2021/javascript%E2%80%A6 | 4
/en/2021/2020/page-weight | 4
/wp-login.php/ | 4
/wp-admin/css/ | 3
/en/2021/ecommerc | 3

**Comment by tunetheweb** [comment]
Some of this is just regular internet spam or typos.

/apple-touch-icon.png/
/apple-touch-icon-precomposed.png/

We should add redirects for those even though [they apparently don't need to be in the root folder](https://stackoverflow.com/questions/25041622/does-the-apple-touch-icon-have-to-be-in-the-root-folder/25041921). They do exist in out static directory (and that's what's listed in the HTML source) but easy enough to redirect for those that don't read the source.

A better check would be the GA events for our 404 page (cause we know that's an actual browser). But looks like that's broken as tries to use gtag before it's loaded. Will fix that.

Never got a chance to run the link checker, or spell checker for launch. Will try to do at some point.
