### ISSUE TITLE
Contributor filters not working in mobile portrait mode

### ISSUE THREAD

**Issue by bazzadp** [HTTPArchive/almanac.httparchive.org#269]
When selecting the filters on my iPhone (Safari on iOS13.2) in Portrait mode they don’t do anything:

![67C951DF-309F-43DA-8EAE-AC3725ED0B2E](https://user-images.githubusercontent.com/10931297/67926544-2c711300-fbae-11e9-93a4-63223e0d348f.png)

Weirdly, rotating the phone 90 degrees causing the filter to take effect:

![1556D552-6913-4B9D-A793-0021769F8921](https://user-images.githubusercontent.com/10931297/67926648-6b06cd80-fbae-11e9-9fbd-e3db6ed888ea.png)

Also changing filter in landscape mode works, whereas it didn’t in Portrait mode.

I didn’t have to reload either - they both just started working by rotating my phone.

Very weird...

**Comment by bazzadp** [comment]
Ah @ymschaap is this fixed by https://github.com/HTTPArchive/almanac.httparchive.org/pull/268 ?

Just saw you “Mobile render bug .teams img” comment on that.

**Comment by bazzadp** [comment]
Same thing happens in Chrome Dev Tools in mobile or responsive mode. Which should at least make it easier to debug!

**Comment by ymschaap** [comment]
Fixed in #268, closing this.
