### ISSUE TITLE
2021 SEO chapter: fix bio

### ISSUE THREAD

**Issue by kartashovio** [HTTPArchive/almanac.httparchive.org#2712]
I have started translating 2021 SEO Chapter and discovered, that two sentences don't showing in bio of authors. Check this chapter in repository: [link](https://github.com/HTTPArchive/almanac.httparchive.org/blob/main/src/content/en/2021/seo.md). Quotes:
> In his spare time, he enjoys hiking and playing poker.

> You can find him pedaling his bike up Seattle's ridiculous hills.

I don't see this on [2021 SEO Chapter page](https://almanac.httparchive.org/en/2021/seo). I think this is because of the line breaks.
If I have not confused anything, I think I would be nice reviewer 😁 can and should i create PR for this?

**Comment by tunetheweb** [comment]
Good spot! Yes please do submit PRs for them.

Translations are always a good second review pass and on occasion find things like this we missed with the initial English version so it's not unusually to lump in some English changes with the translation PR.

So up to you whether you want to wait and include this fix in the Translation PR, or open a second PR for this? If nearly finished I'd advise to just lump in, but if it's going to take you a bit of time to finish that out then a separate PR would be appreciated!
