### ISSUE TITLE
Truncate long web mentions

### ISSUE THREAD

**Issue by rviscomi** [HTTPArchive/almanac.httparchive.org#2762]
1. Go to https://almanac.httparchive.org/en/2021/css
2. Scroll down and toggle the Mentions tab
3. Scroll down to many of the reposted "roundup" blog posts

![image](https://user-images.githubusercontent.com/1120896/148632969-37c6be08-79e6-449e-b14e-082214512e89.png)

It seems the entire text contents of the post are getting embedded into the web mention. A couple of other ideas:

- truncate after the first N characters
- search the text for something relevant (ie the URL or "Web Almanac") and truncate N/2 characters before and after

**Comment by tunetheweb** [comment]
Yeah noticed that on my Third-Party chapter and been meaning to do something about it. PR coming up...
