### ISSUE TITLE
Optimize Methodology page image 

### ISSUE THREAD

**Issue by AymenLoukil** [HTTPArchive/almanac.httparchive.org#278]
The Methodology page header image is not well compressed 
https://almanac.httparchive.org/en/2019/methodology
https://almanac.httparchive.org/static/images/methodology-banner.png
I'll compress it and make a PR

**Comment by JMPerez** [comment]
@AymenLoukil using ImageOptim it can be brought down to 371kB (11.6% savings). I realized that making the window narrower the image is not resized and overflows, so I wonder if as part of the optimization we should look into making the image 100% width and introduce responsive images.

**Comment by rviscomi** [comment]
FWIW the live website doesn't reflect the latest code. It should have `max-width: 100%` now. But we should still reduce its file size.

**Comment by rviscomi** [comment]
I think this has been resolved by the img optimization bot?

**Comment by JMPerez** [comment]
@rviscomi yes, it has. Thanks for closing it.

**Comment by AymenLoukil** [comment]
Yes thank you :)
