### ISSUE TITLE
Ensure all contributors have accepted team invitations

### ISSUE THREAD

**Issue by rviscomi** [HTTPArchive/almanac.httparchive.org#28]
We have GitHub teams for each of the 4 roles: authors, reviewers, analysts, and developers. It's important that everyone who wants to contribute in these areas is on the team so they can be notified all at once using @[team] as needed.

All teams should be set up so that you can manually request to join. I should have also sent individual invitations to everyone who has expressed interest in a team. (Some people _just_ got theirs as I was making this list!) Invites are sent to your GH email, but if you didn't get it you can accept by going to the organization page: https://github.com/HTTPArchive

If your name is below, please accept your invitation! As a bonus, all teams have write access for this repo so you can check your own name off when you've accepted!

### Authors
- [x] @Yonet
- [x] @davelab6
- [x] @zachleat (role discussion pending 😇)
- [x] @ScottHelme
- [ ] @henrisgh

### Reviewers
- [x] @rwaldron
- [x] @zcorpan
- [ ] @simonhearne
- [x] @jasti
- [x] @hyperpress
- [x] @JMPerez
- [x] @zeman
- [x] @clarkeclark
- [x] @mor10
- [x] @rmarx
- [x] @dotjs
- [x] @sergeychernyshev

### Analysts
- [x] @fhoffa
- [x] @dotjs
- [ ] @beouss

### Developers
- [x] @gustavofsantos
- [x] @matijagrcic
- [ ] @Mehedihasan-wp

Coordinating a project with 64+ contributors will be challenging. Thank you for helping to make it easier!

**Comment by rviscomi** [comment]
🛎 Gentle ping for the following people to please accept your team invitations:

  @Yonet
  @davelab6
  @zachleat
  @ScottHelme
  @henrisgh
  @rwaldron
  @zcorpan
  @simonhearne
  @jasti
  @hyperpress
  @JMPerez
  @zeman
  @clarkeclark
  @mor10
  @rmarx
  @dotjs
  @fhoffa
  @dotjs
  @gustavofsantos
  @matijagrcic

Check your inbox or visit https://github.com/HTTPArchive to accept. Thank you!

**Comment by ScottHelme** [comment]
@rviscomi I believe I have, did I miss something?

**Comment by rviscomi** [comment]
You're good @ScottHelme sorry for the false alarm. I edited the names in the ping but not before the notifications already went out. Thanks for being on top of it!

**Comment by rviscomi** [comment]
🛎 Last attempt to ping the following people to accept team invites:

@davelab6
@zachleat
@henrisgh
@rwaldron
@simonhearne
@mor10
@rmarx
@fhoffa
@matijagrcic

There are over 80 contributors now and I'd appreciate all of your help by forming into teams for easier communication. You can accept your invitations by visiting https://github.com/HTTPArchive.

Not interested in contributing anymore? Let me know ASAP!

Thanks everyone!

**Comment by matijagrcic** [comment]
@rviscomi not sure why it's showing as not accepted?

**Comment by rviscomi** [comment]
@matijagrcic hmm, you're still appearing as a pending invitation. I'll try resending it.

![image](https://user-images.githubusercontent.com/1120896/59053762-26c20c00-8860-11e9-8221-7509915dadcd.png)

**Comment by matijagrcic** [comment]
Accepted again. Is all ok from your side now?

**Comment by rviscomi** [comment]
Yes! Looks good now! 
![image](https://user-images.githubusercontent.com/1120896/59057420-52e18b00-8868-11e9-8b66-26442eabcb4c.png)

**Comment by zachleat** [comment]
Hey @rviscomi I am interested in contributing and will accept this invite but I’m not sure what time commitment is required for the “Authors” role (and how I was assigned this role 😇)? Our previous communication here: https://twitter.com/rick_viscomi/status/1129115283132751872

(Happy to communicate over Twitter DM too if helpful)

**Comment by rviscomi** [comment]
Hey @zachleat! Yes, from that conversation I took your reply to mean that you're interested in either role (author or reviewer). Sorry if that wasn't clear. You can read more about the differences between roles in [this post](https://discuss.httparchive.org/t/planning-the-web-almanac-2019/1553?u=rviscomi).

The [June 3 milestone](https://github.com/HTTPArchive/almanac.httparchive.org/milestone/1) was for authors to have come up with a list of metrics to represent their respective chapters and for reviewers to LGTM those lists.

[In August](https://github.com/HTTPArchive/almanac.httparchive.org/milestone/3) we will have extracted those metrics from HTTP Archive authors would be expected to write up their interpretations of the results (blog post style, if that's helpful) and reviewers would be the guardrails to keep authors on the right track based on the data and writing guidelines.

Here's the [full timeline](https://docs.google.com/spreadsheets/d/1LR29JpI2XJSjan_z6uP1YpRy4EYYivYZPqCIG-9sfFY/edit?usp=sharing) for more info. Hope that clarifies and sorry again for any miscommunication.
