### ISSUE TITLE
Markdown compiler adding line breaks

### ISSUE THREAD

**Issue by rviscomi** [HTTPArchive/almanac.httparchive.org#282]
The showdown compiler should be more tolerant of line breaks in md and not convert them to `<br>` tags in the markup.

For example:

```md
this long line would be 
split up in the HTML
```

```html
<p>
this long line would be <br />
split up in the HTML
</p>
```

(contrived example, not actual compiler output)

For a real example see https://github.com/HTTPArchive/almanac.httparchive.org/pull/273/files#r341347538

**Comment by mikegeyser** [comment]
I don't think we should have any `<br />` at all. Would it be alright to simply remove all of them from the compiled output?
