### ISSUE TITLE
Audit the website for SEO issues

### ISSUE THREAD

**Issue by rviscomi** [HTTPArchive/almanac.httparchive.org#286]
Since we have SEO experts on-hand it'd be great if we can make sure that we're following our own best practices on the website. 

The version pushed to https://almanac.httparchive.org has most of the site structure except for the chapter content (the most important part) so if needed we can revisit the website when that's pushed in ~a week or we can audit the local website. The website is also missing translations, so we won't be able to check for that class of SEO issues yet.

CC @ymschaap @rachellcostello @AVGP @clarkeclark @andylimn @voltek62 @AymenLoukil @catalinred

**Comment by AymenLoukil** [comment]
Already started ;)

**Comment by AymenLoukil** [comment]
I made a first check pass and wrote down my findings in draft mode. I'll create an issue for each one + details on how to correct / enhance :) 
Here is the draft document : feel free for every one who want to add things

**Comment by bazzadp** [comment]
> http => https 307 temporary redirect should be 301 one

This one is not quite correct. 307 is because of HSTS which the browser has cached. It’s an internal browser redirect added by your browser. If you use an online tool like https://wheregoes.com/ on http://almanac.httparchive.org then you’ll see it does a 302 to https://almanac.httparchive.org/ (this should probably be a 301) and then a further 302 https://almanac.httparchive.org/en/2019/ (which probably needs to stay as a 302 because next year it will redirect to the 2020 directory so it is a temporary redirect -albeit a year long temporary redirect).

**Comment by AymenLoukil** [comment]
Yeah, the point is http=>https should be 301 and not 302, 307 or any other redirection type.

**Comment by AymenLoukil** [comment]
The second 302 is not because 1 year redirect. It is mainly for language detection. When the translations will be added, if your accept-language is for example es, it should redirect to /es/2019 with 302.

**Comment by rachellcostello** [comment]
I ran a crawl of the site in its current state, and everyone can access the findings [here](https://app.deepcrawl.com/accounts/22614/projects/299664/crawls/2425042?token=qPu5rVvQqK3Xlkfc9r1LboJOH3TLpTcc3D94W-tkX_MVFosTyrtNRhpP0LwkgkHQNRBBnLBKTdDKc_tBkAu5lQ).

In addition to the points in @AymenLoukil's Google doc:

* Multiple H1 tags on the home page and methodology page (not a huge issue for SEO but would recommend maintaining one H1 per page and moving the rest to H2s / H3s etc for more clarity for screen readers)
* Missing Twitter cards and Open Graph tags

I'll schedule another crawl when the chapters have been added in to look for any other issues, and am happy to run more as we go along and share those as and when needed.

**Comment by catalinred** [comment]
> I made a first check pass and wrote down my findings in draft mode. I'll create an issue for each one + details on how to correct / enhance :)
> Here is the draft document : feel free for every one who want to add things
> https://docs.google.com/document/d/1k_HnRaS1portw8RzvA7CRQTTxzn4VcfkT28VFz3zl6M/edit?usp=sharing

In addition to your doc, the `rel=nooopener` for external links should be added only when you open another page using `target=_blank` - in this case within the contributors page.

**Comment by bazzadp** [comment]
> Yeah, the point is http=>https should be 301 and not 302, 307 or any other redirection type.

Agreed but my point is the 307 isn’t a real redirect served by the server. It’s a fake one generated by Chrome to represent the automatic upgrade to HTTPS that HSTS does (see here: https://www.seroundtable.com/googlebot-hsts-redirects-301-307-21405.html). So you can’t “fix” this (and in fact there is nothing to fix). But you are 100% right about the first 302.

**Comment by AymenLoukil** [comment]
> > Yeah, the point is http=>https should be 301 and not 302, 307 or any other redirection type.
> 
> Agreed but my point is the 307 isn’t a real redirect served by the server. It’s a fake one generated by Chrome to represent the automatic upgrade to HTTPS that HSTS does (see here: https://www.seroundtable.com/googlebot-hsts-redirects-301-307-21405.html). So you can’t “fix” this (and in fact there is nothing to fix). But you are 100% right about the first 302 (that those clients who have not loaded the HSTS instruction will use - including GoogleBot) - which is basically the point you were making!

Yeah yeah i confirm @bazzadp ! You right on the 307. I went too fast on this :)

**Comment by rviscomi** [comment]
> I'll schedule another crawl when the chapters have been added in to look for any other issues, and am happy to run more as we go along and share those as and when needed.

@rachellcostello two chapters are currently live and ready for another audit: [Markup](http://127.0.0.1:8080/en/2019/markup) and [Performance](http://127.0.0.1:8080/en/2019/performance).

**Comment by rachellcostello** [comment]
The updated crawl can be accessed [here](https://app.deepcrawl.com/accounts/22614/projects/299664/crawls/2435661?token=vyoKHhAclQBvlvUVKuUhukzrN04jX71YB1bsID1Lb3ZVpyDgEfxjiTJ8gEVKkCPlWJCbdo0udMUgh9Q3jCEOaA).

It confirms that the canonical tags are being picked up and the author link errors have been resolved.

Page reports for the [Markup](https://app.deepcrawl.com/accounts/22614/projects/299664/crawls/2435661/pages/YnT6L7TOlRD35pBow-zNytYqRBATaF1aYqmFZh-zNqF-3SKzC-xae0Sx8YJNPQALLRPWGE1iX03ccuc_nQ2U_Q==?token=GEG4nMTjWcnUM4wpcW9wLxqj0O5S0CH4JCHP25qoWT8wrJrV93nB6TRXa9ypN1t3JypsmrhTE7790PrFXlhHJA) and [Performance](https://app.deepcrawl.com/accounts/22614/projects/299664/crawls/2435661/pages/aXeP62qfAbkxPbo6-V9U3vI_IOUuxBDWeZkSQuGqPHVJzozzjvgqjQqsaCVMSWedVqj7qyS9vCaQ0Y-CdXemlA==?token=VVdyACkC5cQd43x5Z-LBAN1nC3Zu9wjI0u1qQAIBXeGPx5cxGqyrDyfJjQPIWqvbvTWOFVl5iVt6K-DmqKVFWA) chapters aren't showing any issues, which is good!

**Comment by bazzadp** [comment]
OK so at the moment the issues I see are:

- No Sitemap - being tracked in https://github.com/HTTPArchive/almanac.httparchive.org/issues/318 about to be fixed with https://github.com/HTTPArchive/almanac.httparchive.org/pull/345
- No alt for images - should be completed in each chapter edit.
- Add nooopener for external links - more a security issue, than an SEO one and we don't hold secure information so not sure it's worth it.
- Add native lazy loading for all the imgs / iframes - I like this, but not sure how feasible it is. More a performance recommendation than SEO (and yes I know good performance is good for SEO)
- Static assets browser cache - checked a few of these out manually and looks fine to me
- http => https 307 temporary redirect should be 301 one - @rviscomi not show how this is configured on production? Don't think it's a biggy as this will be https all the way.

So looks to me that once we add the Sitemap then hopefully there is no further work required here other than rerunning a scan when full site is launched. So let's hold it open until then but wanted to make sure there was no expectation that any other work was ongoing here. Let me know if there is!

**Comment by AymenLoukil** [comment]
Add native lazy loading for all the imgs / iframes  
=> https://web.dev/native-lazy-loading/

**Comment by bazzadp** [comment]
> Add native lazy loading for all the imgs / iframes
> => https://web.dev/native-lazy-loading/

Raised https://github.com/HTTPArchive/almanac.httparchive.org/issues/351 for this.

**Comment by AymenLoukil** [comment]
> Add nooopener for external links - more a security issue, than an SEO one and we don't hold secure information so not sure it's worth it.
It is a security + performance issue :)

**Comment by AymenLoukil** [comment]
I'm running a  new check to validate the new implementations :) @rviscomi @bazzadp

**Comment by rviscomi** [comment]
Hmm. Just got this email from Google Search Console:

> Google has detected that some pages on your site have implemented the rel-alternate-hreflang tag incorrectly. In particular, there seems to be a problem with incorrect language and region codes, or incorrect bi-directional linking (if page A links with hreflang to page B, there must be a link back from B to A as well). Google uses the hreflang attributes to serve the correct language or regional URL to the right users in search results.
>
> Until you correct the errors on the hreflang links, your website will not benefit from additional language or region targeting.

I also submitted the sitemap.xml file and it returned a few errors similar to this:

```
An invalid date was found. Please fix the date or formatting before resubmitting.

Line 52
Parent tag: url
Tag: lastmod
```

**Comment by AymenLoukil** [comment]
For the sitemap
![image](https://user-images.githubusercontent.com/5750656/68542445-e0438100-03ac-11ea-8054-dfee35ff172b.png)

**Comment by rviscomi** [comment]
Oh no! I'll regenerate the file and push it again.

**Comment by bazzadp** [comment]
No still needs a fix. Working on it.

**Comment by AymenLoukil** [comment]
Regarding the hreflang, since we don't yet have other languages, we could not have the bidirectional issue. 
I think that the issue comes from the HTML lang attribute

> <html lang="en-US">
 
As i previously sais, we should target english generic (en) without any region targeting. (en-US).

In my crawl check i see no other issues. If you want you can share me a SC access. @rviscomi

**Comment by AymenLoukil** [comment]
@rviscomi @bazzadp 
I found where also comes the hreflang issue. URL of alternates must be fully qualified and not relative 

> Alternate URLs must be fully-qualified, including the transport method (http/https), so:

> https://example.com/foo, not //example.com/foo or /foo

https://support.google.com/webmasters/answer/189077?hl=en

**Comment by bazzadp** [comment]
OK will fix that with my sitemap fix PR.

**Comment by bazzadp** [comment]
Any ideas if these are resolved now? Guessing the Sitemap is, but does it list hreflang issues in GSC so can see if fixed there (may not be until it’s next crawled)?

**Comment by rviscomi** [comment]
Not sure. I wasn't able to view the error anywhere other than the vague email. I'll keep an eye out for any more vague emails.

**Comment by rviscomi** [comment]
One of the great things about staffing CDS is that there are real live humans who work on Search Console here! They helped identify the hreflang issue we were seeing and pointed me to this support doc: https://support.google.com/webmasters/answer/189077?hl=en

> Missing return links: If page X links to page Y, page Y must link back to page X. If this is not the case for all pages that use hreflang annotations, those annotations may be ignored or not interpreted correctly.

It's still kind of unclear what SC is complaining about, but maybe 

```
<link rel="alternate" href="https://almanac.httparchive.org/en/2019/" hreflang="en" />
```

should be

```
<link rel="alternate" href="https://almanac.httparchive.org/en/2019/" hreflang="x-default" />
```

**Comment by bazzadp** [comment]
Could it be you shouldn’t implement it unless you have more than one language?

**Comment by AymenLoukil** [comment]
> It's still kind of unclear what SC is complaining about, but maybe

<link rel="alternate" href="https://almanac.httparchive.org/en/2019/" hreflang="en" />

> should be

<link rel="alternate" href="https://almanac.httparchive.org/en/2019/" hreflang="x-default" />

No @rviscomi.

We implemented it right. Just as i said earlier, modify en-US to en. and paths must be absolute. That's it.

Could you please resubmit the website in SC and ask for indexing. + submitting the Sitemap.xml ?

**Comment by rviscomi** [comment]
Ok so this `<html lang="en-US">` should be this `<html lang="en">`?

**Comment by bazzadp** [comment]
https://www.seroundtable.com/one-language-hreglang-google-23970.html

I really think we should add an if statement around this so it doesn't show until the second language is launched. It makes no sense to have it as of now.

**Comment by bazzadp** [comment]
It's a two line change to base.html:

```
    {% if supported_languages | length > 1%}
    {% for l in supported_languages %}
    <link rel="alternate" href="https://almanac.httparchive.org{{ url_for(request.endpoint, **get_view_args(lang=l.lang_code)) }}" hreflang="{{ l.lang_code}}" />
    {% endfor %}
    {% endif %}
```

**Comment by bazzadp** [comment]
> Ok so this `<html lang="en-US">` should be this `<html lang="en">`?

Both versions are fine: https://support.google.com/webmasters/answer/189077?hl=en.

However agree we should just do the language and not the country since we are unlikely to have `en-GB` or similar so this will be the only `en` version.

**Comment by AymenLoukil** [comment]
> Ok so this `<html lang="en-US">` should be this `<html lang="en">`?

Yes :)

**Comment by AymenLoukil** [comment]
> https://www.seroundtable.com/one-language-hreglang-google-23970.html
> 
> I really think we should add an if statement around this so it doesn't show until the second language is launched. It makes no sense to have it as of now.

OK for that. When we implemented the hreflang tags, i thought that we will have at least another language at launch (es). So why not hide them until we publish new language.

**Comment by bazzadp** [comment]
> > Ok so this `<html lang="en-US">` should be this `<html lang="en">`?
> 
> Yes :)

Agree, as per here: https://support.google.com/webmasters/answer/189077?hl=en:

> If you have several alternate URLs targeted at users with the same language but in different locales, it's a good idea also to provide a catchall URL for geographically unspecified users of that language. For example, you may have specific URLs for English speakers in Ireland (en-ie), Canada (en-ca), and Australia (en-au), but should also provide a generic English (en) page for searchers in, say, the US, UK, and all other English-speaking locations. It can be one of the specific pages, if you choose.

We have no `en` page so in theory, only US people will currently be shown that page! As we have no other English pages, we should remove the `-US` completely.

Included a fix for that in https://github.com/HTTPArchive/almanac.httparchive.org/pull/474/commits/5e9bebab301f90f7446ccd65efc34ca5660b4cf8

I that, I say that we support region codes, but I'm not 100% sure we do since directory structure is based on language only, so probably more clean up we could do but that will do for now and can look again when we have more languages and/or regions as difficult to test with just the one we have now.

> The x-default one is for telling what's the default page (if we are an international company, it could be the language selector page). It is optional but we could add it.

Included in https://github.com/HTTPArchive/almanac.httparchive.org/commit/0810d2dc878ea18119c4a8703c0f5afa84ded2aa

Could do with thoroughly testing this when first additional language goes live! Should we raise an issue for that separate to this one?

**Comment by rviscomi** [comment]
The hreflang issue appears to have been resolved.

![image](https://user-images.githubusercontent.com/1120896/68801860-b9d24f80-0611-11ea-9264-292f6dfc3c72.png)

@AymenLoukil do you feel comfortable closing this issue?

**Comment by AymenLoukil** [comment]
@rviscomi good!
I'm on my way back from London. Could I have more time to make global sanity / qa  check?

**Comment by rviscomi** [comment]
Of course! Thank you!

**Comment by rviscomi** [comment]
Of course! Thank you!

**Comment by AymenLoukil** [comment]
Ok i did checked again the SEO aspects of the website.

Figures images don't have decriptive file names and no alt values. It could be better to give them good ones. Here is the list : 

https://almanac.httparchive.org/static/images/2019/05_Third_Parties/fig5.png
https://almanac.httparchive.org/static/images/2019/05_Third_Parties/fig7.png
https://almanac.httparchive.org/static/images/2019/02_CSS/fig18.png
https://almanac.httparchive.org/static/images/2019/02_CSS/fig21.png
https://almanac.httparchive.org/static/images/2019/02_CSS/fig30.png
https://almanac.httparchive.org/static/images/2019/02_CSS/fig35.png
https://almanac.httparchive.org/static/images/2019/02_CSS/fig2.png
https://almanac.httparchive.org/static/images/2019/02_CSS/fig12.png
https://almanac.httparchive.org/static/images/2019/02_CSS/fig27.png
https://almanac.httparchive.org/static/images/2019/02_CSS/fig14.png
https://almanac.httparchive.org/static/images/2019/02_CSS/fig3.png
https://almanac.httparchive.org/static/images/2019/02_CSS/fig33.png
https://almanac.httparchive.org/static/images/2019/02_CSS/fig20.png
https://almanac.httparchive.org/static/images/2019/02_CSS/fig7.png
https://almanac.httparchive.org/static/images/2019/02_CSS/fig15.png
https://almanac.httparchive.org/static/images/2019/02_CSS/fig28.png
https://almanac.httparchive.org/static/images/2019/02_CSS/fig37.png
https://almanac.httparchive.org/static/images/2019/02_CSS/fig9.png
https://almanac.httparchive.org/static/images/2019/02_CSS/fig4.png
https://almanac.httparchive.org/static/images/2019/02_CSS/fig32.png
https://almanac.httparchive.org/static/images/2019/02_CSS/fig16.png
https://almanac.httparchive.org/static/images/2019/02_CSS/fig10.png
https://almanac.httparchive.org/static/images/2019/02_CSS/fig29.png
https://almanac.httparchive.org/static/images/2019/02_CSS/fig25.png
https://almanac.httparchive.org/static/images/2019/02_CSS/fig31.png
https://almanac.httparchive.org/static/images/2019/02_CSS/fig8.png
https://almanac.httparchive.org/static/images/2019/02_CSS/fig38.png
https://almanac.httparchive.org/static/images/2019/02_CSS/fig5.png
https://almanac.httparchive.org/static/images/2019/02_CSS/fig1.png
https://almanac.httparchive.org/static/images/2019/02_CSS/fig17.png
https://almanac.httparchive.org/static/images/2019/02_CSS/fig26.png
https://almanac.httparchive.org/static/images/2019/14_CMS/fig22.png
https://almanac.httparchive.org/static/images/2019/14_CMS/fig14.png
https://almanac.httparchive.org/static/images/2019/14_CMS/fig6.png
https://almanac.httparchive.org/static/images/2019/14_CMS/fig7.png
https://almanac.httparchive.org/static/images/2019/14_CMS/fig18.png
https://almanac.httparchive.org/static/images/2019/14_CMS/fig10.png
https://almanac.httparchive.org/static/images/2019/14_CMS/fig23.png
https://almanac.httparchive.org/static/images/2019/14_CMS/fig4.png
https://almanac.httparchive.org/static/images/2019/14_CMS/fig16.png
https://almanac.httparchive.org/static/images/2019/14_CMS/fig11.png
https://almanac.httparchive.org/static/images/2019/14_CMS/fig20.png
https://almanac.httparchive.org/static/images/2019/14_CMS/fig21.png
https://almanac.httparchive.org/static/images/2019/14_CMS/fig5.png
https://almanac.httparchive.org/static/images/2019/14_CMS/fig12.png
https://almanac.httparchive.org/static/images/2019/13_Ecommerce/fig4.png
https://almanac.httparchive.org/static/images/2019/13_Ecommerce/fig22.png
https://almanac.httparchive.org/static/images/2019/13_Ecommerce/fig19.png
https://almanac.httparchive.org/static/images/2019/13_Ecommerce/fig13.png
https://almanac.httparchive.org/static/images/2019/13_Ecommerce/fig5.png
https://almanac.httparchive.org/static/images/2019/13_Ecommerce/fig8.png
https://almanac.httparchive.org/static/images/2019/13_Ecommerce/fig21.png
https://almanac.httparchive.org/static/images/2019/13_Ecommerce/fig20.png
https://almanac.httparchive.org/static/images/2019/13_Ecommerce/fig11.png
https://almanac.httparchive.org/static/images/2019/13_Ecommerce/fig12.png
https://almanac.httparchive.org/static/images/2019/13_Ecommerce/fig7.png
https://almanac.httparchive.org/static/images/2019/13_Ecommerce/fig15.png
https://almanac.httparchive.org/static/images/2019/13_Ecommerce/fig17.png
https://almanac.httparchive.org/static/images/2019/13_Ecommerce/fig18.png
https://almanac.httparchive.org/static/images/2019/13_Ecommerce/fig6.png
https://almanac.httparchive.org/static/images/2019/12_Mobile_Web/fig5.png
https://almanac.httparchive.org/static/images/2019/17_CDN/fig15.png
https://almanac.httparchive.org/static/images/2019/17_CDN/fig22.png
https://almanac.httparchive.org/static/images/2019/17_CDN/fig11.png
https://almanac.httparchive.org/static/images/2019/17_CDN/fig18.png
https://almanac.httparchive.org/static/images/2019/17_CDN/fig27.png
https://almanac.httparchive.org/static/images/2019/17_CDN/fig19.png
https://almanac.httparchive.org/static/images/2019/17_CDN/fig1.png
https://almanac.httparchive.org/static/images/2019/17_CDN/fig17.png
https://almanac.httparchive.org/static/images/2019/17_CDN/fig26.png
https://almanac.httparchive.org/static/images/2019/17_CDN/fig20.png
https://almanac.httparchive.org/static/images/2019/17_CDN/fig16.png
https://almanac.httparchive.org/static/images/2019/17_CDN/fig13.png
https://almanac.httparchive.org/static/images/2019/16_Caching/fig21.png
https://almanac.httparchive.org/static/images/2019/16_Caching/fig3.png
https://almanac.httparchive.org/static/images/2019/16_Caching/fig12.png
https://almanac.httparchive.org/static/images/2019/16_Caching/fig2.png
https://almanac.httparchive.org/static/images/2019/16_Caching/fig14.png
https://almanac.httparchive.org/static/images/2019/16_Caching/fig7.png
https://almanac.httparchive.org/static/images/2019/16_Caching/fig5.png
https://almanac.httparchive.org/static/images/2019/16_Caching/fig9.png
https://almanac.httparchive.org/static/images/2019/16_Caching/fig22.png
https://almanac.httparchive.org/static/images/2019/16_Caching/fig6.png
https://almanac.httparchive.org/static/images/2019/16_Caching/fig13.png
https://almanac.httparchive.org/static/images/2019/15_Compression/fig5.png
https://almanac.httparchive.org/static/images/2019/15_Compression/fig6.png
https://almanac.httparchive.org/static/images/2019/15_Compression/ch15_fig8_lighthouse.jpg
https://almanac.httparchive.org/static/images/2019/15_Compression/fig11.png
https://almanac.httparchive.org/static/images/2019/15_Compression/fig2.png
https://almanac.httparchive.org/static/images/2019/15_Compression/fig3.png
https://almanac.httparchive.org/static/images/2019/15_Compression/fig12.png
https://almanac.httparchive.org/static/images/2019/15_Compression/fig7.png
https://almanac.httparchive.org/static/images/2019/15_Compression/fig4.png
https://almanac.httparchive.org/static/images/2019/15_Compression/fig8.png
https://almanac.httparchive.org/static/images/2019/20_HTTP_2/ch20_fig13_what_push_is_used_for.png
https://almanac.httparchive.org/static/images/2019/01_JavaScript/fig5.png
https://almanac.httparchive.org/static/images/2019/01_JavaScript/fig18.png
https://almanac.httparchive.org/static/images/2019/01_JavaScript/fig17.png
https://almanac.httparchive.org/static/images/2019/01_JavaScript/fig16.png
https://almanac.httparchive.org/static/images/2019/01_JavaScript/fig3.png
https://almanac.httparchive.org/static/images/2019/01_JavaScript/fig1.png
https://almanac.httparchive.org/static/images/2019/01_JavaScript/fig10.png
https://almanac.httparchive.org/static/images/2019/01_JavaScript/fig2.png
https://almanac.httparchive.org/static/images/2019/01_JavaScript/fig13.png
https://almanac.httparchive.org/static/images/2019/01_JavaScript/fig9.png
https://almanac.httparchive.org/static/images/2019/01_JavaScript/fig12.png
https://almanac.httparchive.org/static/images/2019/01_JavaScript/fig8.png
https://almanac.httparchive.org/static/images/2019/01_JavaScript/fig15.png
https://almanac.httparchive.org/static/images/2019/01_JavaScript/fig7.png
https://almanac.httparchive.org/static/images/2019/01_JavaScript/fig14.png
https://almanac.httparchive.org/static/images/2019/01_JavaScript/fig6.png
https://almanac.httparchive.org/static/images/2019/03_Markup/fig3.png
https://almanac.httparchive.org/static/images/2019/03_Markup/fig9.png
https://almanac.httparchive.org/static/images/2019/03_Markup/fig10.png
https://almanac.httparchive.org/static/images/2019/03_Markup/fig6.png
https://almanac.httparchive.org/static/images/2019/03_Markup/fig5.png
https://almanac.httparchive.org/static/images/2019/03_Markup/fig7.png
https://almanac.httparchive.org/static/images/2019/09_Accessibility/fig4.png
https://almanac.httparchive.org/static/images/2019/09_Accessibility/fig8.png
https://almanac.httparchive.org/static/images/2019/09_Accessibility/fig3.png
https://almanac.httparchive.org/static/images/2019/09_Accessibility/fig2.png
https://almanac.httparchive.org/static/images/2019/09_Accessibility/fig6.png
https://almanac.httparchive.org/static/images/2019/09_Accessibility/fig5.png
https://almanac.httparchive.org/static/images/2019/04_Media/fig10.png
https://almanac.httparchive.org/static/images/2019/04_Media/fig8.png
https://almanac.httparchive.org/static/images/2019/04_Media/fig19.png
https://almanac.httparchive.org/static/images/2019/09_Accessibility/fig9.png
https://almanac.httparchive.org/static/images/2019/04_Media/fig4.png
https://almanac.httparchive.org/static/images/2019/04_Media/fig15.png
https://almanac.httparchive.org/static/images/2019/04_Media/fig11.png
https://almanac.httparchive.org/static/images/2019/04_Media/fig1.png
https://almanac.httparchive.org/static/images/2019/04_Media/fig5.png
https://almanac.httparchive.org/static/images/2019/04_Media/fig17.png
https://almanac.httparchive.org/static/images/2019/04_Media/fig12.png
https://almanac.httparchive.org/static/images/2019/04_Media/fig20.png
https://almanac.httparchive.org/static/images/2019/04_Media/fig21.png
https://almanac.httparchive.org/static/images/2019/04_Media/fig16.png
https://almanac.httparchive.org/static/images/2019/04_Media/fig13.png
https://almanac.httparchive.org/static/images/2019/04_Media/fig2.png
https://almanac.httparchive.org/static/images/2019/08_Security/fig1.png
https://almanac.httparchive.org/static/images/2019/08_Security/fig3.png
https://almanac.httparchive.org/static/images/2019/08_Security/fig8.png
https://almanac.httparchive.org/static/images/2019/08_Security/fig2.png
https://almanac.httparchive.org/static/images/2019/07_Performance/fig13.png
https://almanac.httparchive.org/static/images/2019/07_Performance/fig3.png
https://almanac.httparchive.org/static/images/2019/07_Performance/fig17.png
https://almanac.httparchive.org/static/images/2019/07_Performance/fig4.png
https://almanac.httparchive.org/static/images/2019/07_Performance/fig14.png
https://almanac.httparchive.org/static/images/2019/07_Performance/fig9.png
https://almanac.httparchive.org/static/images/2019/07_Performance/fig5.png
https://almanac.httparchive.org/static/images/2019/07_Performance/fig18.png
https://almanac.httparchive.org/static/images/2019/07_Performance/fig6.png
https://almanac.httparchive.org/static/images/2019/07_Performance/fig1.png
https://almanac.httparchive.org/static/images/2019/07_Performance/fig15.png
https://almanac.httparchive.org/static/images/2019/07_Performance/fig2.png
https://almanac.httparchive.org/static/images/2019/07_Performance/fig10.png
https://almanac.httparchive.org/static/images/2019/07_Performance/fig12.png
https://almanac.httparchive.org/static/images/2019/07_Performance/fig16.png
https://almanac.httparchive.org/static/images/2019/07_Performance/fig7.png
https://almanac.httparchive.org/static/images/2019/07_Performance/fig11.png
https://almanac.httparchive.org/static/images/2019/04_Media/fig7.png
https://almanac.httparchive.org/static/images/2019/04_Media/fig14.png
https://almanac.httparchive.org/static/images/2019/04_Media/fig22.png
https://almanac.httparchive.org/static/images/2019/04_Media/fig3.png

The rest LGTM

**Comment by AymenLoukil** [comment]
Also, contributors page is shuffling on reload which is not the best choice from SEO POV.

**Comment by bazzadp** [comment]
> Also, contributors page is shuffling on reload which is not the best choice from SEO / crawl POV.

Yeah I don't think it's a big deal, and it's nicer to our contributors so I say we accept this.

@AymenLoukil are we good to close this issues? Alt-tags is being tracked in #379 and rest have either been dealt with or can be accepted IMHO.

**Comment by AymenLoukil** [comment]
What about the figures files names ? 

> Also, contributors page is shuffling on reload which is not the best choice from SEO / crawl POV.

> Yeah` I don't think it's a big deal, and it's nicer to our contributors so I say we accept this.

You create a separate issue ?

**Comment by bazzadp** [comment]
> What about the figures files names ?

I think it's a minor thing. And having done the last big bulk update not too inclined to do another!

I care much more about the content being SEO-friendly than the mages anyway. Another item could be that we should watermark all the images with "© HTTP Web Almanac 2019" in case anyone uses them, but again I think that's one for next year unless anyone takes that on?

> > Also, contributors page is shuffling on reload which is not the best choice from SEO / crawl POV.
> 
> > Yeah I don't think it's a big deal, and it's nicer to our contributors so I say we accept this.
> 
> You create a separate issue ?

Nope. I'm saying we accept it. This was a conscious decision and I don't see the big SEO lose with it to be honest.

**Comment by AymenLoukil** [comment]
> I think it's a minor thing. And having done the last big bulk update not too inclined to do another!
> I care much more about the content being SEO-friendly than the images anyway.

Visual search is so important and one of the 3 pillars of Google search announced on its 20th birthday. Images are part of the content and text is not more or less important. Having a descriptive/SEO file name is one of the basics of images SEO. 

> And having done the last big bulk update not too inclined to do another!

I understand. We could imagine make use of the figure title to slugify it for the image filename.
example : Figure 2. Distribution of JavaScript per page by device. => distribution-of-javascript-per-page-by-device.png 

> Nope. I'm saying we accept it. This was a conscious decision and I don't see the big SEO lose with it to be honest.

There is no big SEO loose here. The fact is we are making Google receive a different answer on each time it crawls the page. but it is ok.

**Comment by bazzadp** [comment]
> Visual search is so important and one of the 3 pillars of Google search announced on its 20th birthday. Images are part of the content and text is not more or less important. Having a descriptive/SEO file name is one of the basics of images SEO.

Personally I think the effort involved - particularly with the translations well underway now - far outweighs any benefit here.

to prove a point I just Googled which I think might be a typical search request that one of the title might help with:

![image](https://user-images.githubusercontent.com/10931297/69582163-e7cf7080-0fcf-11ea-8f02-7e859ceb944a.png)

As you can see we are **already** as the 3rd and 5th search results. I really don't think there will be a noticeable improvement from this by renaming the image files. They are already loaded with context from text around them, `alt` attributes, `figcaptions` and aria descriptions. That's a wealth of SEO right there and the file names will add little beyond this but require a lot of effort and disruption of translations.

**Comment by rviscomi** [comment]
I think this issue is ok to close and we can open new issues for anything SEO related that comes up.
