### ISSUE TITLE
CSS 2022

### ISSUE THREAD

**Issue by rviscomi** [HTTPArchive/almanac.httparchive.org#2879]
# CSS 2022

![CSS illustration](https://raw.githubusercontent.com/HTTPArchive/almanac.httparchive.org/main/src/static/images/2019/css/hero_lg.jpg)

If you're interested in contributing to the CSS chapter of the 2022 Web Almanac, please reply to this issue and indicate which role or roles best fit your interest and availability: [author](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Authors'-Guide), [reviewer](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Reviewers'-Guide), [analyst](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Analysts'-Guide), and/or [editor](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Editors'-Guide).

## Content team

| Lead | Authors | Reviewers | Analysts | Editors | Coordinator |
| ---- | ------- | --------- | -------- | ------- | ----------- |
| @rachelandrew | @rachelandrew | @j9t @meyerweb @svgeesus | @rviscomi | @dereknahman | @siakaramalegos  |

<details>
<summary><b>Expand for more information about each role 👀</b></summary>

- The **[content team lead](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Content-Team-Leads'-Guide)** is the chapter owner and responsible for setting the scope of the chapter and managing contributors' day-to-day progress.
- **[Authors](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Authors'-Guide)** are subject matter experts and lead the content direction for each chapter. Chapters typically have one or two authors. Authors are responsible for planning the outline of the chapter, analyzing stats and trends, and writing the annual report.
- **[Reviewers](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Reviewers'-Guide)** are also subject matter experts and assist authors with technical reviews during the planning, analyzing, and writing phases.
- **[Analysts](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Analysts'-Guide)** are responsible for researching the stats and trends used throughout the Almanac. Analysts work closely with authors and reviewers during the planning phase to give direction on the types of stats that are possible from the dataset, and during the analyzing/writing phases to ensure that the stats are used correctly.
- **[Editors](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Editors'-Guide)** are technical writers who have a penchant for both technical and non-technical content correctness. Editors have a mastery of the English language and work closely with authors to help wordsmith content and ensure that everything fits together as a cohesive unit.
- The **[section coordinator](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Section-Leads'-Guide)** is the overall owner for all chapters within a section like "User Experience" or "Page Content" and helps to keep each chapter on schedule.

_Note: The time commitment for each role varies by the chapter's scope and complexity as well as the number of contributors._

For an overview of how the roles work together at each phase of the project, see the [Chapter Lifecycle](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Chapter-Lifecycle) doc.
</details>

### [**0. Form the content team**](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Chapter-Lifecycle#0-create-content-team)
+ [x] **May 1**: The content team has at least one author, reviewer, and analyst

### [**1. Plan content**](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Chapter-Lifecycle#1-plan-content)
+ [x] **May 15** The content team has completed the chapter outline in the [draft doc][~google-doc]

### [**2. Gather data**](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Chapter-Lifecycle#2-gather-data)
+ [x] **June 1**: Analysts have added all necessary [custom metrics](https://github.com/HTTPArchive/custom-metrics/blob/main/README.md) and drafted a PR ([example](https://github.com/HTTPArchive/almanac.httparchive.org/pull/1087)) to track query progress
- **June 1 - 15**: HTTP Archive runs the June crawl

### [**3. Validate results**](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Chapter-Lifecycle#3-validate-results)
+ [x] **August 1**: Analysts have queried all metrics and saved the output to the [results sheet][~google-sheets]

### [**4. Draft content**](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Chapter-Lifecycle#4-draft-content)
+ [x] **September 1**: The content team has written, reviewed, and edited the chapter in the [doc][~google-doc]

### [**5. Publication**](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Chapter-Lifecycle#5-publication)
+ [ ] **September 15**: The completed chapter and all required [metadata](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Authors'-Guide#metadata-to-add-at-the-top-of-your-chapters) and [figures](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Figures-Guide) are converted to markdown and submitted to [GitHub][~chapter-markdown]
- **September 26**: Target launch date 🚀

## Chapter resources

Refer to these 2022 CSS resources throughout the content creation process:

[📄 Google Docs][~google-doc] for outlining and drafting content
[🔍 SQL files][~sql-files] for committing the queries used during analysis
[📊 Google Sheets][~google-sheets] for saving the results of queries
[📝 Markdown file][~chapter-markdown] for publishing content and managing public metadata
[💬 #web-almanac-css on Slack][~slack-channel] for team coordination

[~google-doc]: https://docs.google.com/document/d/1aKTQht_HeLdskNOeELI_e3rhTev5ldyiSl72Qbm18O0/edit?usp=sharing
[~sql-files]: https://github.com/HTTPArchive/almanac.httparchive.org/tree/main/sql/2022/css
[~google-sheets]: https://docs.google.com/spreadsheets/d/1OU8ahxC5oYU8VRryQs9BzHToaXcOntVlh6KUHjm15G4/edit?usp=sharing
[~chapter-markdown]: https://github.com/HTTPArchive/almanac.httparchive.org/tree/main/src/content/en/2022/css.md
[~slack-channel]: https://join.slack.com/t/httparchive/shared_invite/zt-45sgwmnb-eDEatOhqssqNAKxxOSLAaA

**Comment by rachelandrew** [comment]
As discussed, happy to be an author for CSS.

**Comment by rviscomi** [comment]
Yes thank you @rachelandrew! I've added you to the roster above and added myself as an analyst. A few formalities...

As the content team lead you'll be ultimately responsible for setting the narrative for the chapter, keeping it on schedule, and coordinating with the rest of the content team. A coordinator will be assigned to this chapter to help with any process/logistical questions, but you can always reach out to me if anything comes up.

The contributor roster and milestone checklist above are this chapter's source of truth for how it's progressing. We use automation to monitor all chapters at a glance, so please try to keep these sections up to date as best you can.

The chapter resources section above contains a few canonical links unique to this chapter. These are the shared resources that you and your content team can use to coordinate throughout the project, including a Google Doc for planning and drafting content and a Google Sheet for analyzing the results.

Thanks again, looking forward to collaborating on this chapter with you!

**Comment by j9t** [comment]
Happy to review.

**Comment by svgeesus** [comment]
Happy to review again this year

**Comment by dereknahman** [comment]
Hello! I'd like to register my interest for the Editor role. I have previous lives in Editorial Management and writing for trade news outlets before I became a dev, so I think I can be of some use to this project.

**Comment by rviscomi** [comment]
Welcome @dereknahman! I've added you as the Editor for this chapter.

@rachelandrew @j9t @meyerweb @svgeesus @dereknahman could you all make sure you have access to the [planning doc](https://docs.google.com/document/d/1aKTQht_HeLdskNOeELI_e3rhTev5ldyiSl72Qbm18O0/edit?usp=sharing) and start adding content to the outline? What topics would you like to see covered this year; what's new or what should we revisit from previous years? We're hoping to have the outline completed by May 15, to give us time to add any required custom metrics to the crawl before it starts on June 1. Thanks!

**Comment by svgeesus** [comment]
For comparison, here is the 2021 [planning doc](https://docs.google.com/document/d/18OV1ngkQxdJdENkYzHOdNRtzMLo1vVv9Tg6a9pGfSSE/edit#heading=h.8z91yaf1dmft) and [results sheet](https://docs.google.com/spreadsheets/d/12vQIA0xsC5Jr3J9Sh03AcAvgFjMAmP1xSS6Tjai9LF0/edit#gid=1420025896)

**Comment by rachelandrew** [comment]
I've added an outline, mostly based on last year so we can do comparisons year on year, with a few extras, things that have landed this year. Please add any additions, I'm also going to run this by a few folks outside of the team who might have opinions on specific bits of CSS!

**Comment by siakaramalegos** [comment]
@rachelandrew and team, is the outline complete? The deadline was May 15. We now have less than 2 weeks to finalize any custom metrics so getting to outline completion is critical. When it's complete, please check the milestone off. Thanks for your contributions!

**Comment by svgeesus** [comment]
Is it possible to add another metric for this year? Recent discussions in CSS WG considered allowing mixed percentages and numbers in color functions (til now, you needed either three percentages or three numbers for the likes of `rgb()` or `color()`. [The big unknown is](https://github.com/w3c/csswg-drafts/issues/7338#issuecomment-1159566416):

> whether there are currently usages of number and percentage mixtures (that currently break but would work after that change and cause a visual difference)

So this is a "how badly would we break the Web if we made this change and caused these to be accepted" query.

**Comment by svgeesus** [comment]
@rachelandrew I was looking at the draft doc just now and see some unanswered questions. I helped with some but I think most are directed at yourself.

**Comment by rviscomi** [comment]
>Is it possible to add another metric for this year? Recent discussions in CSS WG considered allowing mixed percentages and numbers in color functions (til now, you needed either three percentages or three numbers for the likes of rgb() or color().

@svgeesus I'm happy to decouple that question from the Almanac analysis and share the results with the CSS WG as soon as the data is available. I'll defer to @rachelandrew as content team lead to decide if the data is generally interesting enough to include in the chapter.

**Comment by svgeesus** [comment]
> @svgeesus I'm happy to decouple that question from the Almanac analysis and share the results with the CSS WG as soon as the data is available

Fantastic. Yes, better to decouple. I wondered if it might be interesting enough to discuss in the chapter, depends on what we find.

**Comment by siakaramalegos** [comment]
@rviscomi it looks like the analysis is almost complete - can you give us an idea of % complete and timeline on the rest?

@rachelandrew when do you think you can begin the draft? Just as a reminder, the due date at the end of the month is for post-review and post-edit, so you'll need to set aside at least a week for those and preferably more.

**Comment by rviscomi** [comment]
I've just merged the analysis PR with 68 of 73 metrics. Their results are available in the [spreadsheet](https://docs.google.com/spreadsheets/d/1OU8ahxC5oYU8VRryQs9BzHToaXcOntVlh6KUHjm15G4/edit?usp=sharing). Sorry for the delay, everyone.

The remaining metrics have open questions in the [draft doc](https://docs.google.com/document/d/1aKTQht_HeLdskNOeELI_e3rhTev5ldyiSl72Qbm18O0/edit?disco=AAAAZZbH_tQ). If we can get those addressed, I'll follow up with the additional queries/results.

@rachelandrew @j9t @meyerweb @svgeesus let me know if any of the results look off.

Over to @rachelandrew to start the draft of the chapter.

**Comment by rachelandrew** [comment]
thanks @rviscomi I'll go through those questions today.

**Comment by rviscomi** [comment]
Thanks for following up on those open questions @rachelandrew. I've implemented the remaining queries and saved their results to the sheet. Back over to you.

**Comment by siakaramalegos** [comment]
Haven't seen any updates in the draft doc so just wanted to ping again @rachelandrew when do you think you can begin the draft? What's the plan for completing it? THanks

**Comment by siakaramalegos** [comment]
@rachelandrew great job starting the draft - when do you think it will be ready for review? We only have 4 days left for the review and editing cycles, and the reviewers need some time (cc @j9t @meyerweb @svgeesus)

**Comment by rachelandrew** [comment]
@j9t @meyerweb @svgeesus @siakaramalegos I should be finished a first pass this weekend but feel free to follow me down the doc (right now I've just finished feature queries). I've a few comments where I've called out interesting looking things, or places where I don't understand where the change might have come from. I'd appreciate eyes on color in particular as that's not my area of knowledge.

I need to do things like add figure captions, an intro and so on, but I'll do those when I do my second pass, so don't worry about missing stuff like that.

**Comment by rachelandrew** [comment]
@j9t @meyerweb @svgeesus @siakaramalegos I've got through all the sections, there are a few to dos, I need to write an intro and conclusion. But PTAL, and I'll follow up in a day or so, and tidy up.

**Comment by j9t** [comment]
(On it—need a few days to read through but will give feedback asap.)

**Comment by siakaramalegos** [comment]
I haven't seen much change since last week and we're past the deadline now. What's the plan to get the draft completed, reviewed, and comments incorporated @rachelandrew ? (cc @j9t @meyerweb @svgeesus)

**Comment by rachelandrew** [comment]
@siakaramalegos sorry for the delay in wrapping up, I really can only work on this at the weekend. Other than a couple of small comments this is done from my point of view. I'll have a look tomorrow in case anything else comes in.

**Comment by svgeesus** [comment]
This looks to be in good shape to me. I made whatever comments seemed appropriate so my review is essentially complete but I will keep checking back if there are new comments or changes.

**Comment by svgeesus** [comment]
>  I'd appreciate eyes on color in particular as that's not my area of knowledge.

Naturally that was where I started reading and I don't have any more suggestions to add in that area. Web-in-the-wild is very conservative and a bit cargo-cultish so naturally we see very little uptake of newer color stuff (even of hsl!!) though that might change if Interop-2022 bears fruit but meanwhile the color situation is "same as last year pretty much".

**Comment by siakaramalegos** [comment]
@rachelandrew looks good to me other than one table that will probably be too small to be readable on the web layout - I noted it in Slack since I didn't have access already to comment in the doc. 

It sounds like it's ready for edit @dereknahman. When do you think you can take a look?

**Comment by dereknahman** [comment]
Hi all. So sorry but I won’t be able to take a look. My responsibilities have snowballed this past week after a family emergency. I’m sorry I forgot to update you.

**Comment by rviscomi** [comment]
No worries @dereknahman. I'll start the markdown conversion now and I can take care of the editing in the process.
