### ISSUE TITLE
JavaScript 2022

### ISSUE THREAD

**Issue by rviscomi** [HTTPArchive/almanac.httparchive.org#2880]
# JavaScript 2022

![JavaScript illustration](https://raw.githubusercontent.com/HTTPArchive/almanac.httparchive.org/main/src/static/images/2019/javascript/hero_lg.jpg)

If you're interested in contributing to the JavaScript chapter of the 2022 Web Almanac, please reply to this issue and indicate which role or roles best fit your interest and availability: [author](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Authors'-Guide), [reviewer](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Reviewers'-Guide), [analyst](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Analysts'-Guide), and/or [editor](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Editors'-Guide).

## Content team

| Lead | Authors | Reviewers | Analysts | Editors | Coordinator |
| ---- | ------- | --------- | -------- | ------- | ----------- |
| @malchata | @malchata @ibnesayeed | @mgechev @pankajparkar @NishuGoel @seldo @housseindjirdeh @kevinfarrugia | @NishuGoel @kevinfarrugia | @DesignrKnight @rviscomi | @siakaramalegos |

<details>
<summary><b>Expand for more information about each role 👀</b></summary>

- The **[content team lead](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Content-Team-Leads'-Guide)** is the chapter owner and responsible for setting the scope of the chapter and managing contributors' day-to-day progress.
- **[Authors](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Authors'-Guide)** are subject matter experts and lead the content direction for each chapter. Chapters typically have one or two authors. Authors are responsible for planning the outline of the chapter, analyzing stats and trends, and writing the annual report.
- **[Reviewers](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Reviewers'-Guide)** are also subject matter experts and assist authors with technical reviews during the planning, analyzing, and writing phases.
- **[Analysts](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Analysts'-Guide)** are responsible for researching the stats and trends used throughout the Almanac. Analysts work closely with authors and reviewers during the planning phase to give direction on the types of stats that are possible from the dataset, and during the analyzing/writing phases to ensure that the stats are used correctly.
- **[Editors](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Editors'-Guide)** are technical writers who have a penchant for both technical and non-technical content correctness. Editors have a mastery of the English language and work closely with authors to help wordsmith content and ensure that everything fits together as a cohesive unit.
- The **[section coordinator](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Section-Leads'-Guide)** is the overall owner for all chapters within a section like "User Experience" or "Page Content" and helps to keep each chapter on schedule.

_Note: The time commitment for each role varies by the chapter's scope and complexity as well as the number of contributors._

For an overview of how the roles work together at each phase of the project, see the [Chapter Lifecycle](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Chapter-Lifecycle) doc.
</details>

### [**0. Form the content team**](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Chapter-Lifecycle#0-create-content-team)
+ [x] **May 1**: The content team has at least one author, reviewer, and analyst

### [**1. Plan content**](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Chapter-Lifecycle#1-plan-content)
+ [x] **May 15** The content team has completed the chapter outline in the [draft doc][~google-doc]

### [**2. Gather data**](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Chapter-Lifecycle#2-gather-data)
+ [x] **June 1**: Analysts have added all necessary [custom metrics](https://github.com/HTTPArchive/custom-metrics/blob/main/README.md) and drafted a PR ([example](https://github.com/HTTPArchive/almanac.httparchive.org/pull/1087)) to track query progress
- **June 1 - 15**: HTTP Archive runs the June crawl

### [**3. Validate results**](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Chapter-Lifecycle#3-validate-results)
+ [x] **August 1**: Analysts have queried all metrics and saved the output to the [results sheet][~google-sheets]

### [**4. Draft content**](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Chapter-Lifecycle#4-draft-content)
+ [x] **September 1**: The content team has written, reviewed, and edited the chapter in the [doc][~google-doc]

### [**5. Publication**](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Chapter-Lifecycle#5-publication)
+ [x] **September 15**: The completed chapter and all required [metadata](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Authors'-Guide#metadata-to-add-at-the-top-of-your-chapters) and [figures](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Figures-Guide) are converted to markdown and submitted to [GitHub][~chapter-markdown]
- **September 26**: Target launch date 🚀

## Chapter resources

Refer to these 2022 JavaScript resources throughout the content creation process:

[📄 Google Docs][~google-doc] for outlining and drafting content
[🔍 SQL files][~sql-files] for committing the queries used during analysis
[📊 Google Sheets][~google-sheets] for saving the results of queries
[📝 Markdown file][~chapter-markdown] for publishing content and managing public metadata
[💬 #web-almanac-javascript on Slack][~slack-channel] for team coordination

[~google-doc]: https://docs.google.com/document/d/12Mqcp5ME04fn15ujO-J65eMZJlQ6ADEbXozttx0MJw8/edit?usp=sharing
[~sql-files]: https://github.com/HTTPArchive/almanac.httparchive.org/tree/main/sql/2022/javascript
[~google-sheets]: https://docs.google.com/spreadsheets/d/1vOeFUyfEtWRen3Xj57ZsWav40n5tlcJoV0HmAxmNE_I/edit?usp=sharing
[~chapter-markdown]: https://github.com/HTTPArchive/almanac.httparchive.org/tree/main/src/content/en/2022/javascript.md
[~slack-channel]: https://join.slack.com/t/httparchive/shared_invite/zt-45sgwmnb-eDEatOhqssqNAKxxOSLAaA

**Comment by mgechev** [comment]
I'd love to help as a reviewer!

**Comment by pankajparkar** [comment]
I'm interested in reviewing this chapter

cc- @NishuGoel

**Comment by rviscomi** [comment]
@malchata is interested in the author role! 🎉

**Comment by NishuGoel** [comment]
Would love to contribute as an analyst + reviewer for JS chapter this year!

**Comment by siakaramalegos** [comment]
@seldo we heard you might be interested in contributing to the JS chapter - maybe as a reviewer? Pinging you here in case...

**Comment by seldo** [comment]
> @seldo we heard you might be interested in contributing to the JS chapter - maybe as a reviewer? Pinging you here in case...

Yep, I don't consider myself deep enough in JS itself to write, but more than happy to review.

**Comment by malchata** [comment]
I'll be the writer for this chapter, and I'm looking forward to having you review @seldo!

**Comment by housseindjirdeh** [comment]
I'll be happy to review as well if there's a need for more reviewers :)

**Comment by siakaramalegos** [comment]
@housseindjirdeh we could also use reviewers on #2886 if you're interested in Third Parties

**Comment by kevinfarrugia** [comment]
Would be happy to pitch in as analyst + reviewer if needed.

**Comment by ibnesayeed** [comment]
I can co-author, but can't be the lead author.

**Comment by malchata** [comment]
That's okay @ibnesayeed, I think I'm the _de facto_ lead author. I'd welcome the help if you wanted to co-author!

**Comment by malchata** [comment]
@siakaramalegos @rviscomi, it appears our team is mostly complete, just short an editor. Did anyone volunteer to edit and I just missed this?

**Comment by DesignrKnight** [comment]
I would love to join the team and volunteer as an Editor.

**Comment by malchata** [comment]
I've added you to the editor column, @DesignrKnight!

If anyone else is interested in editing, please indicate interest here and I'll add you!

**Comment by rviscomi** [comment]
Thanks @DesignrKnight! FYI there's not much work for [editors](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Editors'-Guide) to do until the draft is written, so that's why we don't require those roles to be filled before starting on the planning phase. If you'd like to be involved with the planning phase, you may also be interested in the [reviewer](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Reviewers'-Guide) role.

**Comment by malchata** [comment]
@rviscomi, I'll be doing the outline this weekend. If anyone needs access, just ping me or Rick.

**Comment by malchata** [comment]
cc: @siakaramalegos, @rviscomi 

I now have a [draft outline available(https://docs.google.com/document/d/12Mqcp5ME04fn15ujO-J65eMZJlQ6ADEbXozttx0MJw8/edit?usp=sharing). Anyone reading this who doesn't have access, please request it. The outline is similar in structure to last year's, but with additional content. I left a flurry of comments in the draft outline, addressed openly to anyone who wants to engage.

**Comment by siakaramalegos** [comment]
@ibnesayeed @mgechev @pankajparkar @NishuGoel @seldo @housseindjirdeh @kevinfarrugia just a reminder to open up the draft doc, add your name and email address to confirm your participation, and provide feedback on the outline Jeremy started. The outline is due in 2 days and he will need time to incorporate your feedback. Thanks!

**Comment by malchata** [comment]
Outline is complete. cc: @rviscomi, @siakaramalegos

**Comment by malchata** [comment]
@kevinfarrugia, @NishuGoel what's the status of the custom metrics? Are we set for the June crawl?

**Comment by malchata** [comment]
@kevinfarrugia, are all metrics ready? I'm thinking I'd like to get a draft going next month.

**Comment by kevinfarrugia** [comment]
@malchata there are a few remaining queries and visualisations. Will pick them up over the next 3/4 days so you have time to review before the end of the month.

**Comment by malchata** [comment]
Awesome! I appreciate your hard work on this, Kevin!

**Comment by malchata** [comment]
@kevinfarrugia, I'm beginning to write the JavaScript chapter, and noticed that many of the links to results spreadsheets are now broken. Do you think you can restore these so I can continue writing?

**Comment by kevinfarrugia** [comment]
@malchata Yep, completely forgot about them. All links are now updated. Keep me in the loop if you have any feedback.

**Comment by siakaramalegos** [comment]
@kevinfarrugia  it looks like the analysis is almost complete - can you give us an idea of % complete and timeline on the rest, if any?

@malchata Thanks for beginning the draft! Just as a reminder, the due date at the end of the month is for post-review and post-edit, so you'll need to set aside at least a week for those and preferably more.

**Comment by malchata** [comment]
Thanks for the heads up @siakaramalegos! I'm going to allocating more time to tackle this over the next couple of weeks so I can get it all wrapped up for review.

Just a note, I will be in South Korea during the review due date, but anticipate I will have time to get it across the finish line in time for 9/15.

**Comment by kevinfarrugia** [comment]
@siakaramalegos analysis is complete and and all results are updated on the result sheet. 

@malchata I left the comments on the outline. Let me know if I missed something or you need anything else from my end. 

Thanks both.

**Comment by malchata** [comment]
I'll be working more on the draft this weekend, so I'll hit you up if I see anything missing. Thanks for all your hard work, @kevinfarrugia! LOTS of data here to pore over for the remainder of the draft.

**Comment by siakaramalegos** [comment]
Hi reviewers (@mgechev @pankajparkar @NishuGoel @seldo @housseindjirdeh @kevinfarrugia), @malchata only has two small sections to finish writing, but all the other content is done. Can you start reviewing now so we can try to still hit the deadline? I can backfill for review on the last bit if you're not free then.

**Comment by DesignrKnight** [comment]
Should I also start looking at the style guide as an editor in a preliminary fashion in parallel or do I do it after the review is done?

**Comment by rviscomi** [comment]
@DesignrKnight yes definitely start familiarizing yourself with the [Editors' Guide](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Editors'-Guide). Ideally the editing pass will be done after the technical review because the text is still changing, but given the tight timeline, I'd suggest leaving your non-technical edit suggestions in the doc when you're ready. Then you can give it a quicker final pass after the technical review is done.

**Comment by malchata** [comment]
@rviscomi @kevinfarrugia I'm nearly done with the text, but I do need additional graphs/visualizations for the minification section that were present in the 2021 almanac's JavaScript chapter.

**Comment by kevinfarrugia** [comment]
Sure, I will prepare them tomorrow.

**Comment by DesignrKnight** [comment]
> @DesignrKnight yes definitely start familiarizing yourself with the [Editors' Guide](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Editors'-Guide). Ideally the editing pass will be done after the technical review because the text is still changing, but given the tight timeline, I'd suggest leaving your non-technical edit suggestions in the doc when you're ready. Then you can give it a quicker final pass after the technical review is done.

Awesome, sounds good. Will do as per the suggestion.

**Comment by kevinfarrugia** [comment]
@malchata Added the visualizations for the minification section (two sheets). Heads up that the `pct` value was calculated incorrectly on `lighthouse_unminified_js.sql` and I have now updated it.

**Comment by malchata** [comment]
@siakaramalegos, @rviscomi: the first draft is complete!

cc reviewers @mgechev @pankajparkar @NishuGoel @seldo @housseindjirdeh @kevinfarrugia. The draft link is here: https://docs.google.com/document/d/12Mqcp5ME04fn15ujO-J65eMZJlQ6ADEbXozttx0MJw8/edit#

**Comment by rviscomi** [comment]
Thanks @malchata! I gave it a read and left lots of small suggestions mostly about the charts and data precision. Overall this is really really well-polished and well-written, great work to you and the rest of the team! 🎉 

I can sign off on it from an editorial perspective once those comments are resolved. @DesignrKnight it'd still be great if you could also give it a read through and leave editing/non-technical feedback in case I missed anything.

I see @ibnesayeed is listed as a coauthor but don't see any additions to the writing in the edit history. Should we move him to the reviewer role instead?

Speaking of which, @mgechev @pankajparkar @NishuGoel @seldo @housseindjirdeh @kevinfarrugia over to you all for technical / peer review feedback.

**Comment by malchata** [comment]
I wrote the whole thing from top to bottom, so if @ibnesayeed is interested, they can jump in on the review.

Thanks for the kind words, Rick. Was glad I could get this in a draft before September.

**Comment by DesignrKnight** [comment]
> Thanks @malchata! I gave it a read and left lots of small suggestions mostly about the charts and data precision. Overall this is really really well-polished and well-written, great work to you and the rest of the team! 🎉 
> 
> I can sign off on it from an editorial perspective once those comments are resolved. @DesignrKnight it'd still be great if you could also give it a read through and leave editing/non-technical feedback in case I missed anything.


Surely @rviscomi . I'll take a look at it today (Tuesday) before end of the day and add my thoughts on the document.

**Comment by DesignrKnight** [comment]
I took a first-pass look at the chapter's first half. It is pretty amazing to see such a detailed well-articulated chapter. Fantastic

**Comment by siakaramalegos** [comment]
Great job so far @malchata and team! Do you think you can finish reviewing and incorporating comments within the next few days? We'd really like to get this published in the first round. cc  @mgechev @pankajparkar @NishuGoel @seldo @housseindjirdeh @kevinfarrugia

**Comment by malchata** [comment]
I can work on it over the weekend!

**Comment by siakaramalegos** [comment]
It looks like we still need some more reviewers - I've only seen 1 reviewer comment from Kevin Farrugia. @mgechev @pankajparkar @NishuGoel @seldo @housseindjirdeh can you review in the next day or two? We're now behind schedule and at risk for publishing on time. Please post when you're done with your review so that @malchata can more quickly integrate feedback. Editing can't begin until the technical review cycle is done.

**Comment by malchata** [comment]
Hey @siakaramalegos,

@rviscomi is going to get this over the finish line for me, as I have a trip to South Korea next week for JSConf. But do keep me in the loop, and if you need anything from me specifially!

Cheers,
Jeremy

**Comment by pankajparkar** [comment]
@siakaramalegos @rviscomi I had a look at the complete article. I have added a comment from my end. 

@malchata Great Job! Very well written 🙌 🙌
