### ISSUE TITLE
Fonts 2022

### ISSUE THREAD

**Issue by rviscomi** [HTTPArchive/almanac.httparchive.org#2883]
# Fonts 2022

![Fonts illustration](https://raw.githubusercontent.com/HTTPArchive/almanac.httparchive.org/main/src/static/images/2019/fonts/hero_lg.jpg)

If you're interested in contributing to the Fonts chapter of the 2022 Web Almanac, please reply to this issue and indicate which role or roles best fit your interest and availability: [author](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Authors'-Guide), [reviewer](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Reviewers'-Guide), [analyst](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Analysts'-Guide), and/or [editor](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Editors'-Guide).

## Content team

| Lead | Authors | Reviewers | Analysts | Editors | Coordinator |
| ---- | ------- | --------- | -------- | ------- | ----------- |
| @bramstein | @bramstein | @RoelN @svgeesus @jmsole @alexnj | @konfirmed | @shantsis | @siakaramalegos  |

<details>
<summary><b>Expand for more information about each role 👀</b></summary>

- The **[content team lead](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Content-Team-Leads'-Guide)** is the chapter owner and responsible for setting the scope of the chapter and managing contributors' day-to-day progress.
- **[Authors](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Authors'-Guide)** are subject matter experts and lead the content direction for each chapter. Chapters typically have one or two authors. Authors are responsible for planning the outline of the chapter, analyzing stats and trends, and writing the annual report.
- **[Reviewers](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Reviewers'-Guide)** are also subject matter experts and assist authors with technical reviews during the planning, analyzing, and writing phases.
- **[Analysts](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Analysts'-Guide)** are responsible for researching the stats and trends used throughout the Almanac. Analysts work closely with authors and reviewers during the planning phase to give direction on the types of stats that are possible from the dataset, and during the analyzing/writing phases to ensure that the stats are used correctly.
- **[Editors](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Editors'-Guide)** are technical writers who have a penchant for both technical and non-technical content correctness. Editors have a mastery of the English language and work closely with authors to help wordsmith content and ensure that everything fits together as a cohesive unit.
- The **[section coordinator](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Section-Leads'-Guide)** is the overall owner for all chapters within a section like "User Experience" or "Page Content" and helps to keep each chapter on schedule.

_Note: The time commitment for each role varies by the chapter's scope and complexity as well as the number of contributors._

For an overview of how the roles work together at each phase of the project, see the [Chapter Lifecycle](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Chapter-Lifecycle) doc.
</details>

### [**0. Form the content team**](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Chapter-Lifecycle#0-create-content-team)
+ [x] **May 1**: The content team has at least one author, reviewer, and analyst

### [**1. Plan content**](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Chapter-Lifecycle#1-plan-content)
+ [x] **May 15** The content team has completed the chapter outline in the [draft doc][~google-doc]

### [**2. Gather data**](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Chapter-Lifecycle#2-gather-data)
+ [x] **June 1**: Analysts have added all necessary [custom metrics](https://github.com/HTTPArchive/custom-metrics/blob/main/README.md) and drafted a PR ([example](https://github.com/HTTPArchive/almanac.httparchive.org/pull/1087)) to track query progress
- **June 1 - 15**: HTTP Archive runs the June crawl

### [**3. Validate results**](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Chapter-Lifecycle#3-validate-results)
+ [x] **August 1**: Analysts have queried all metrics and saved the output to the [results sheet][~google-sheets]

### [**4. Draft content**](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Chapter-Lifecycle#4-draft-content)
+ [x] **September 1**: The content team has written, reviewed, and edited the chapter in the [doc][~google-doc]

### [**5. Publication**](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Chapter-Lifecycle#5-publication)
+ [ ] **September 15**: The completed chapter and all required [metadata](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Authors'-Guide#metadata-to-add-at-the-top-of-your-chapters) and [figures](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Figures-Guide) are converted to markdown and submitted to [GitHub][~chapter-markdown]
- **September 26**: Target launch date 🚀

## Chapter resources

Refer to these 2022 Fonts resources throughout the content creation process:

[📄 Google Docs][~google-doc] for outlining and drafting content
[🔍 SQL files][~sql-files] for committing the queries used during analysis
[📊 Google Sheets][~google-sheets] for saving the results of queries
[📝 Markdown file][~chapter-markdown] for publishing content and managing public metadata
[💬 #web-almanac-fonts on Slack][~slack-channel] for team coordination

[~google-doc]: https://docs.google.com/document/d/148AtE9qzz4JZB3fyoimUJavmBRrbrFtJjm49xzloj-A/edit?usp=sharing
[~sql-files]: https://github.com/HTTPArchive/almanac.httparchive.org/tree/main/sql/2022/fonts
[~google-sheets]: https://docs.google.com/spreadsheets/d/1A1XwuGa1DkqNLaF-lSXz4ndxO9G6SfACHwUvvywHgbQ/edit?usp=sharing
[~chapter-markdown]: https://github.com/HTTPArchive/almanac.httparchive.org/tree/main/src/content/en/2022/fonts.md
[~slack-channel]: https://join.slack.com/t/httparchive/shared_invite/zt-45sgwmnb-eDEatOhqssqNAKxxOSLAaA

**Comment by konfirmed** [comment]
I'll like to be an analyst in this chapter.

**Comment by RoelN** [comment]
I'd like to apply for reviewer, and figuring out what interesting details to pull from the huge heap of font data!

**Comment by bramstein** [comment]
I'd be happy to review as well (if you need more than one.)

**Comment by siakaramalegos** [comment]
@bramstein the more the merrier! Thanks!

**Comment by siakaramalegos** [comment]
I just re-read the 2020 chapter, and noticed a lot of performance stuff in it. If someone is interested in authoring but isn't as confident in the performance side, I can be a backup co-author for that. I'd prefer not to be because I'm also a section coordinator, but I really want this chapter to happen this year so offering just in case it's needed :)

**Comment by svgeesus** [comment]
I'm happy to be a reviewer, and can also contribute towards some of the content planning.

Given the previous couple of years, what is definitely needed is a strong overall lead and primary author; and I'm not able to put myself forward for that role given my other commitments over the same time period.

**Comment by jmsole** [comment]
I don't know if you need any more reviewers but I'd like to propose myself as one, in case my experience is useful. I'm the Font Development Technical Manager at Dalton Maag, a digital font foundry based in London. I have 10 years of experience in the type industry and a ton of experience making fonts for clients of all sizes, both as a designer as well as from a technical implementation perspective.

**Comment by siakaramalegos** [comment]
Hi @RoelN @bramstein @svgeesus @jmsole, we still need a lead author. If we don't get one by May 1, then we'll probably have to drop the chapter so that we can focus on the viable ones. If you're willing to step up, please let us know. Or, if you could poke your font friends to try to get another volunteer, that would be helpful. My offer still stands to help with the performance stuff, if needed.

**Comment by bramstein** [comment]
If no one comes forward before the 1st of May, I can take on the writing.

**Comment by siakaramalegos** [comment]
@konfirmed just confirming @rviscomi already has your email address to set you up so you're not charged in Big Query

**Comment by konfirmed** [comment]
@siakaramalegos I think so, but will send it to @rviscomi

**Comment by siakaramalegos** [comment]
@bramstein looks like you're an author now :) Are you interested in being lead also? I sent you an email to get started. Let me know if you didn't receive it.

**Comment by bramstein** [comment]
@siakaramalegos Indeed :) I can be lead as well. I received your email, will get back to you shortly.

**Comment by rviscomi** [comment]
@bramstein @RoelN @svgeesus @jmsole @konfirmed could you all make sure you have access to the [chapter planning doc](https://docs.google.com/document/d/148AtE9qzz4JZB3fyoimUJavmBRrbrFtJjm49xzloj-A/edit?usp=sharing) and start adding your ideas to the outline? What's new with web fonts this year, or what would be interesting to revisit from previous years? We're aiming to have the outline completed by May 15 in order to have enough time to add any needed custom metrics before the June crawl kicks off. Thanks!

**Comment by bramstein** [comment]
@konfirmed I don't have your email. Could you send me an email to b.l.stein@gmail.com ? Thanks!

**Comment by konfirmed** [comment]
@bramstein I sent you an email, hope you received it.

**Comment by bramstein** [comment]
@konfirmed Got it, thanks!

**Comment by siakaramalegos** [comment]
@RoelN @svgeesus @jmsole just a reminder that the outline is due in 2 days so make sure you open the doc, add your name and email to confirm your participation, and provide feedback on the outline that Bram started (scroll down to a new Ideas section). Thanks!

**Comment by siakaramalegos** [comment]
@bramstein and team, is the outline complete? The deadline was May 15. We now have less than 2 weeks to finalize any custom metrics so getting to outline completion is critical. When it's complete, please check the milestone off. Thanks for your contributions!

**Comment by siakaramalegos** [comment]
@konfirmed and team - how is the query generation going? We want to be ready to run them once the run is finished.

**Comment by siakaramalegos** [comment]
@konfirmed and team - all the data should now be ready to query. It looks like you have 3 queries written - what's your plan for finishing up the rest and starting the analysis? Do you need any help? Checking in to make sure we can keep progress toward publication

**Comment by konfirmed** [comment]
@siakaramalegos Hi I do need help. I should be able to dedicate this coming week to writing the remaining queries

**Comment by siakaramalegos** [comment]
Hi @konfirmed what kind of help do you need? Let me know here, or you can ask in the analyst channel in Slack. Depending on what it is, want to get you the right help.

**Comment by siakaramalegos** [comment]
@konfirmed @bramstein  it looks like the queries are almost complete - can you give us an idea of % complete and timeline on the rest? Also, you're pretty behind on the analysis so I'm getting worried about the viability of this chapter - the deadline for writing is the end of this month.

@bramstein  when do you think you can begin the draft? Just as a reminder, the due date at the end of the month is for post-review and post-edit, so you'll need to set aside at least a week for those and preferably more.

**Comment by alexnj** [comment]
I can be a reviewer if help is needed!

**Comment by siakaramalegos** [comment]
@bramstein Just wanted to ping again - I noticed the PR for the queries is merged, but I don't see any data or analysis in the results sheet yet nor anything in the draft yet. What's the plan to get the analysis done and the writing complete in time for review? Thanks

**Comment by bramstein** [comment]
@siakaramalegos Thanks for trying to keep things on track! I'm still trying to catch up. The queries have been merged and I manually saved the query results locally. I'll add the results to the sheet over the weekend. Then I'll start on the first draft.

**Comment by siakaramalegos** [comment]
Thanks for the update!

**Comment by rviscomi** [comment]
@bramstein you might be interested in @kevinfarrugia's [tool](https://github.com/kevinfarrugia/csv_to_sheets) to take local CSV results and automatically import them into Sheets to streamline the process. More [discussion](https://httparchive.slack.com/archives/C016QLMT0BZ/p1657545852826349) about it in the #web-almanac-analysts channel on Slack.

**Comment by bramstein** [comment]
@rviscomi @siakaramalegos Thanks! I went through the data today and made some writing notes for the chapter (and fixed a couple things, #3080). I've used the tool to upload the query results to Sheets.

**Comment by siakaramalegos** [comment]
great job so far @bramstein and review team! What are the final steps to get the reviews done and incorporated? We'd love to get this published in the first round.

**Comment by svgeesus** [comment]
I just did a complete end-to-end read in one sitting and really, this is very clear, detailed, good logical flow, easy to understand. A quality chapter. I think I had like one or two tiny suggestions this time, and the chapter would be totally fine without either being changed.
