### ISSUE TITLE
Third Parties 2022

### ISSUE THREAD

**Issue by rviscomi** [HTTPArchive/almanac.httparchive.org#2886]
# Third Parties 2022

![Third Parties illustration](https://raw.githubusercontent.com/HTTPArchive/almanac.httparchive.org/main/src/static/images/2019/third-parties/hero_lg.jpg)

If you're interested in contributing to the Third Parties chapter of the 2022 Web Almanac, please reply to this issue and indicate which role or roles best fit your interest and availability: [author](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Authors'-Guide), [reviewer](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Reviewers'-Guide), [analyst](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Analysts'-Guide), and/or [editor](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Editors'-Guide).

## Content team

| Lead | Authors | Reviewers | Analysts | Editors | Coordinator |
| ---- | ------- | --------- | -------- | ------- | ----------- |
| @imeugenia | @imeugenia | @tunetheweb @housseindjirdeh @pepelsbey @kevinfarrugia @alexnj  | @kevinfarrugia | - | @siakaramalegos  |

<details>
<summary><b>Expand for more information about each role 👀</b></summary>

- The **[content team lead](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Content-Team-Leads'-Guide)** is the chapter owner and responsible for setting the scope of the chapter and managing contributors' day-to-day progress.
- **[Authors](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Authors'-Guide)** are subject matter experts and lead the content direction for each chapter. Chapters typically have one or two authors. Authors are responsible for planning the outline of the chapter, analyzing stats and trends, and writing the annual report.
- **[Reviewers](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Reviewers'-Guide)** are also subject matter experts and assist authors with technical reviews during the planning, analyzing, and writing phases.
- **[Analysts](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Analysts'-Guide)** are responsible for researching the stats and trends used throughout the Almanac. Analysts work closely with authors and reviewers during the planning phase to give direction on the types of stats that are possible from the dataset, and during the analyzing/writing phases to ensure that the stats are used correctly.
- **[Editors](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Editors'-Guide)** are technical writers who have a penchant for both technical and non-technical content correctness. Editors have a mastery of the English language and work closely with authors to help wordsmith content and ensure that everything fits together as a cohesive unit.
- The **[section coordinator](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Section-Leads'-Guide)** is the overall owner for all chapters within a section like "User Experience" or "Page Content" and helps to keep each chapter on schedule.

_Note: The time commitment for each role varies by the chapter's scope and complexity as well as the number of contributors._

For an overview of how the roles work together at each phase of the project, see the [Chapter Lifecycle](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Chapter-Lifecycle) doc.
</details>

### [**0. Form the content team**](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Chapter-Lifecycle#0-create-content-team)
+ [x] **May 1**: The content team has at least one author, reviewer, and analyst

### [**1. Plan content**](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Chapter-Lifecycle#1-plan-content)
+ [x] **May 15** The content team has completed the chapter outline in the [draft doc][~google-doc]

### [**2. Gather data**](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Chapter-Lifecycle#2-gather-data)
+ [x] **June 1**: Analysts have added all necessary [custom metrics](https://github.com/HTTPArchive/custom-metrics/blob/main/README.md) and drafted a PR ([example](https://github.com/HTTPArchive/almanac.httparchive.org/pull/1087)) to track query progress
- **June 1 - 15**: HTTP Archive runs the June crawl

### [**3. Validate results**](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Chapter-Lifecycle#3-validate-results)
+ [x] **August 1**: Analysts have queried all metrics and saved the output to the [results sheet][~google-sheets]

### [**4. Draft content**](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Chapter-Lifecycle#4-draft-content)
+ [x] **September 1**: The content team has written, reviewed, and edited the chapter in the [doc][~google-doc]

### [**5. Publication**](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Chapter-Lifecycle#5-publication)
+ [x] **September 15**: The completed chapter and all required [metadata](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Authors'-Guide#metadata-to-add-at-the-top-of-your-chapters) and [figures](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Figures-Guide) are converted to markdown and submitted to [GitHub][~chapter-markdown]
- **September 26**: Target launch date 🚀

## Chapter resources

Refer to these 2022 Third Parties resources throughout the content creation process:

[📄 Google Docs][~google-doc] for outlining and drafting content
[🔍 SQL files][~sql-files] for committing the queries used during analysis
[📊 Google Sheets][~google-sheets] for saving the results of queries
[📝 Markdown file][~chapter-markdown] for publishing content and managing public metadata
[💬 #web-almanac-third-parties on Slack][~slack-channel] for team coordination

[~google-doc]: https://docs.google.com/document/d/1QB5AGi8ye21TqX8ySq7XIWODXZakJ903hIITne1IKOc/edit?usp=sharing
[~sql-files]: https://github.com/HTTPArchive/almanac.httparchive.org/tree/main/sql/2022/third-parties
[~google-sheets]: https://docs.google.com/spreadsheets/d/1YqoRRsyiNsrEabVLu2nRU98JIG_0zLLuoQhC2nX8xbM/edit?usp=sharing
[~chapter-markdown]: https://github.com/HTTPArchive/almanac.httparchive.org/tree/main/src/content/en/2022/third-parties.md
[~slack-channel]: https://join.slack.com/t/httparchive/shared_invite/zt-45sgwmnb-eDEatOhqssqNAKxxOSLAaA

**Comment by imeugenia** [comment]
Hello! I would like to be a co-author for this chapter.

**Comment by housseindjirdeh** [comment]
I can be a reviewer for this chapter 🙏

**Comment by pepelsbey** [comment]
I can be a reviewer for this chapter

**Comment by kevinfarrugia** [comment]
Would be happy to pitch in as analyst + reviewer if needed.

**Comment by siakaramalegos** [comment]
@kevinfarrugia awesome, thanks so much! Glad to see you contribute again!

**Comment by tunetheweb** [comment]
@imeugenia I invited @msolercanals to the HTTP Archive Team as requested.

@msolercanals check your emails for the invite and then reach out to @kevinfarrugia to coordinate analysis. He's an old hand at this so can help you out. And make sure you both send your emails to @rviscomi to get added to the HTTP Archive BigQuery account so queries are charged there.

**Comment by rviscomi** [comment]
ℹ️ @imeugenia @tunetheweb @housseindjirdeh @pepelsbey @kevinfarrugia @msolercanals reminder for anyone who hasn't yet accessed the [chapter planning doc](https://docs.google.com/document/d/1QB5AGi8ye21TqX8ySq7XIWODXZakJ903hIITne1IKOc/edit?usp=sharing) and added your ideas to the outline. I see a lot of great progress, so thank you to everyone who has contributed so far! Just checking in to make sure we're on track to complete the outline by May 15, to leave enough time in case there are any new metrics we need to add to the June crawl. Thanks!

**Comment by siakaramalegos** [comment]
@imeugenia | @tunetheweb @housseindjirdeh @pepelsbey @kevinfarrugia | @kevinfarrugia @msolercanals just a reminder that the outline is due in 2 days. Make sure you open the doc, add your name and email address, and provide feedback on the ideas started there. Also, Eugenia, we'll need to understand what part is the final outline. Thanks!

**Comment by siakaramalegos** [comment]
@imeugenia and team, is the outline complete? The deadline was May 15. We now have less than 2 weeks to finalize any custom metrics so getting to outline completion is critical. When it's complete, please check the milestone off. Thanks for your contributions!

**Comment by siakaramalegos** [comment]
@kevinfarrugia  it looks like the analysis is almost complete - can you give us an idea of % complete and timeline on the rest?

@imeugenia  when do you think you can begin the draft? Just as a reminder, the due date at the end of the month is for post-review and post-edit, so you'll need to set aside at least a week for those and preferably more.

**Comment by kevinfarrugia** [comment]
@siakaramalegos I think we're done from queries. :)

**Comment by alexnj** [comment]
I'd be happy to be a reviewer if help is needed!

**Comment by siakaramalegos** [comment]
@imeugenia when do you think you can start working on the draft? What's the plan to get back on track for completion? Thanks

**Comment by tunetheweb** [comment]
@kevinfarrugia / @imeugenia one thing that came to light today. The Sustainability chapter ran some Third Party SQL and got smaller results than you. Turns out they were using the Canonical Domain from the third-party dataset which groups together third-party domains into one.

For example the following are distinct domains:
- `3461206.fls.doubleclick.net`
- `690327.fls.doubleclick.net`
- `10180635.fls.doubleclick.net`

But they are grouped under the `adservice.google.com` canonical domain.

So depending how you count it, someone using all three is using "three third parties" (or at least "three third party domains") or "one third party". I can see the argument for both views - though the former should probably be clarified as "domains".

Checking out the queries we seem to have used them inconsistently, sometimes using one, sometimes the other. This is not @kevinfarrugia 's fault - the same mistake was made last year (where I was both analyst and author) and also the previous year, and most queries were copied year to year.

I don't think we should change this now, and would lose ability to compare with previous year. But think we should we should probably review the graphs and make clear if it's "Third Parties" or "Third Party domains".

WDYT?

FYI @fershad

**Comment by kevinfarrugia** [comment]
Not all queries are affected. I will go through the queries and see which would need to be fixed. Then we can decide the way forward.

**Comment by kevinfarrugia** [comment]
@imeugenia I have added a new sheet [number_of_canonical_third_parties_by_rank.sql](https://docs.google.com/spreadsheets/d/1YqoRRsyiNsrEabVLu2nRU98JIG_0zLLuoQhC2nX8xbM/edit#gid=1428106498) based on @tunetheweb 's feedback above. From what I can see, only one query was needed.

The difference between the new sheet and [number_of_third_parties_by_rank.sql](https://docs.google.com/spreadsheets/d/1YqoRRsyiNsrEabVLu2nRU98JIG_0zLLuoQhC2nX8xbM/edit#gid=759454652) is that the former will count multiple requests to the same provider as one third party (adservice.google.com); while the latter is counting the number of distinct 3P domains (10180635.fls.doubleclick.net, 690327.fls.doubleclick.net...etc). Hope that's clear.

**Comment by tunetheweb** [comment]
Great work @kevinfarrugia !

**Comment by siakaramalegos** [comment]
@imeugenia @tunetheweb @housseindjirdeh @pepelsbey @alexnj from what I can tell, we only have 1 technical review so far from Kevin Farrugia. I think we need more than 1 to be ideal. Can you review in the next day or two so that Eugenia can incorporate that feedback and we can move to the editorial review step? We're already more than a week behind so really want to wrap this up as soon as possible. Thanks!

**Comment by shantsis** [comment]
Hello all, I've taken a read through the doc and left a few small editing comments :)
