### ISSUE TITLE
Security 2022

### ISSUE THREAD

**Issue by rviscomi** [HTTPArchive/almanac.httparchive.org#2892]
# Security 2022

![Security illustration](https://raw.githubusercontent.com/HTTPArchive/almanac.httparchive.org/main/src/static/images/2019/security/hero_lg.jpg)

If you're interested in contributing to the Security chapter of the 2022 Web Almanac, please reply to this issue and indicate which role or roles best fit your interest and availability: [author](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Authors'-Guide), [reviewer](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Reviewers'-Guide), [analyst](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Analysts'-Guide), and/or [editor](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Editors'-Guide).

## Content team

| Lead | Authors | Reviewers | Analysts | Editors | Coordinator |
| ---- | ------- | --------- | -------- | ------- | ----------- |
| @SaptakS | @SaptakS @feross @lirantal | @kushaldas @tomvangoethem @nrllh @clarkio  | @VictorLeP @vikvanderlinden @GJFR | - | @foxdavidj |

<details>
<summary><b>Expand for more information about each role 👀</b></summary>

- The **[content team lead](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Content-Team-Leads'-Guide)** is the chapter owner and responsible for setting the scope of the chapter and managing contributors' day-to-day progress.
- **[Authors](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Authors'-Guide)** are subject matter experts and lead the content direction for each chapter. Chapters typically have one or two authors. Authors are responsible for planning the outline of the chapter, analyzing stats and trends, and writing the annual report.
- **[Reviewers](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Reviewers'-Guide)** are also subject matter experts and assist authors with technical reviews during the planning, analyzing, and writing phases.
- **[Analysts](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Analysts'-Guide)** are responsible for researching the stats and trends used throughout the Almanac. Analysts work closely with authors and reviewers during the planning phase to give direction on the types of stats that are possible from the dataset, and during the analyzing/writing phases to ensure that the stats are used correctly.
- **[Editors](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Editors'-Guide)** are technical writers who have a penchant for both technical and non-technical content correctness. Editors have a mastery of the English language and work closely with authors to help wordsmith content and ensure that everything fits together as a cohesive unit.
- The **[section coordinator](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Section-Leads'-Guide)** is the overall owner for all chapters within a section like "User Experience" or "Page Content" and helps to keep each chapter on schedule.

_Note: The time commitment for each role varies by the chapter's scope and complexity as well as the number of contributors._

For an overview of how the roles work together at each phase of the project, see the [Chapter Lifecycle](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Chapter-Lifecycle) doc.
</details>

### [**0. Form the content team**](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Chapter-Lifecycle#0-create-content-team)
+ [x] **May 1**: The content team has at least one author, reviewer, and analyst

### [**1. Plan content**](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Chapter-Lifecycle#1-plan-content)
+ [x] **May 15** The content team has completed the chapter outline in the [draft doc][~google-doc]

### [**2. Gather data**](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Chapter-Lifecycle#2-gather-data)
+ [x] **June 1**: Analysts have added all necessary [custom metrics](https://github.com/HTTPArchive/custom-metrics/blob/main/README.md) and drafted a PR ([example](https://github.com/HTTPArchive/almanac.httparchive.org/pull/1087)) to track query progress
- **June 1 - 15**: HTTP Archive runs the June crawl

### [**3. Validate results**](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Chapter-Lifecycle#3-validate-results)
+ [x] **August 1**: Analysts have queried all metrics and saved the output to the [results sheet][~google-sheets]

### [**4. Draft content**](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Chapter-Lifecycle#4-draft-content)
+ [ ] **September 1**: The content team has written, reviewed, and edited the chapter in the [doc][~google-doc]

### [**5. Publication**](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Chapter-Lifecycle#5-publication)
+ [ ] **September 15**: The completed chapter and all required [metadata](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Authors'-Guide#metadata-to-add-at-the-top-of-your-chapters) and [figures](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Figures-Guide) are converted to markdown and submitted to [GitHub][~chapter-markdown]
- **September 26**: Target launch date 🚀

## Chapter resources

Refer to these 2022 Security resources throughout the content creation process:

[📄 Google Docs][~google-doc] for outlining and drafting content
[🔍 SQL files][~sql-files] for committing the queries used during analysis
[📊 Google Sheets][~google-sheets] for saving the results of queries
[📝 Markdown file][~chapter-markdown] for publishing content and managing public metadata
[💬 #web-almanac-security on Slack][~slack-channel] for team coordination

[~google-doc]: https://docs.google.com/document/d/1vit05gwIZI9oE-AM1D0hZDNDl3sZ-8fAMlLIJ4b8Cg0/edit?usp=sharing
[~sql-files]: https://github.com/HTTPArchive/almanac.httparchive.org/tree/main/sql/2022/security
[~google-sheets]: https://docs.google.com/spreadsheets/d/1cwJ43NL2IN2PxJa5oiOoJCRkSh566XE_k9uHnGJdWeg/edit?usp=sharing
[~chapter-markdown]: https://github.com/HTTPArchive/almanac.httparchive.org/tree/main/src/content/en/2022/security.md
[~slack-channel]: https://join.slack.com/t/httparchive/shared_invite/zt-45sgwmnb-eDEatOhqssqNAKxxOSLAaA

**Comment by SaptakS** [comment]
Happy to co-author or review (if there are others who want to author instead of the same team).

**Comment by kushaldas** [comment]
I would love to help in review this year.

**Comment by foxdavidj** [comment]
Hey @SaptakS, would you be interested in taking the Chapter Lead role for the Security chapter?

**Comment by SaptakS** [comment]
@foxdavidj I don't think I will have enough availability to take the Chapter Lead role this time.

**Comment by nrllh** [comment]
I'd like to contribute this year as a reviewer :)

**Comment by foxdavidj** [comment]
@awareseven @cqueern @edmondwwchan @nrllh @tomvangoethem 

Would any of you be interested in leading the chapter this year? I know some of you have already signed up to be a reviewer, but we're in need of a Lead in order to get this chapter off the ground.

And as contributors in past years, we'd love to welcome you back to the role

**Comment by cqueern** [comment]
Given other commitments I’m not going to be able to lead. Sorry.

**Comment by foxdavidj** [comment]
@awareseven @cqueern @edmondwwchan @nrllh @tomvangoethem

Hi all. We need some help finding a Lead for this chapter. Right now it looks like we'll miss our first milestone (May 1st) which will put the chapter at risk of being dropped.

Can you all reach out to anyone you feel may be a good fit for a Lead/Authoring role for the chapter?

Thanks

**Comment by tunetheweb** [comment]
@lirantal would you have any interesting in getting involved in this chapter this year?

**Comment by SaptakS** [comment]
I talked with @feross and he said he is interested in co-authoring.

**Comment by lirantal** [comment]
@tunetheweb thank you for the mention.
Between @clarkio and myself, we'd love to join this year's report. I think it would be too short of a notice to join as analysts. Potentially can make it as authors, but definitely note us down as reviewers. We'd love to take part!

**Comment by foxdavidj** [comment]
@SaptakS can you add both lirantal and clarikio to the content team in the chapter comment above?

**Comment by foxdavidj** [comment]
Hey @SaptakS,

Heads-up that we're fast approaching the May 15th deadline of having an [outline for the chapter](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Chapter-Lifecycle#1-plan-content) put together.

Instead of waiting for the kick-off meeting, it'd be a good idea to start working on the outline with the team. Especially if there are any new [custom metrics](https://github.com/HTTPArchive/custom-metrics/blob/main/README.md) the chapter requires.

**Comment by rviscomi** [comment]
@gjfr any interest in being the analyst for the chapter again this year?

**Comment by SaptakS** [comment]
@lirantal @clarkio do you want me to add both of you as author or reviewer? I would like at least one more author (since security is usually pretty big chapter), so it would be great if at least one of you would be interested to be a co-author.

**Comment by clarkio** [comment]
@SaptakS looks like there are two authors so I'm happy to join as a reviewer and/or editor if that is helpful to you all

**Comment by foxdavidj** [comment]
@AAgar would you be interested in being an analyst for the Security chapter this year?

**Comment by GJFR** [comment]
Hi guys, I would like to help out but I think the workload would be too high if I'm the only analist, because of other projects. However @VictorLeP en @vikvanderlinden, you mentioned that you're also interested in joining?

**Comment by VictorLeP** [comment]
> Hi guys, I would like to help out but I think the workload would be too high if I'm the only analist, because of other projects. However @VictorLeP en @vikvanderlinden, you mentioned that you're also interested in joining?

Yes, I would like to join as an analyst as well :)

**Comment by vikvanderlinden** [comment]
> Hi guys, I would like to help out but I think the workload would be too high if I'm the only analist, because of other projects. However @VictorLeP en @vikvanderlinden, you mentioned that you're also interested in joining?

Yes, me too!

**Comment by foxdavidj** [comment]
@SaptakS Doesn't look like you edited the github chapter description above with the analysts names. Can you quick edit it?

**Comment by brumka** [comment]
Hi all.  I can volunteer as a reviewer.  Few words about myself: ex-Akamai where I worked a lot with WAF/bot management, security of 3rd party JS.  CISSP/CCSP/pen tester/yadda-yadda.  Now at MSFT, tinkering with Azure internals.

**Comment by SaptakS** [comment]
@foxdavidj we have a rough outline ready. I think we can start looking into writing custom metrics, if any needed.

**Comment by foxdavidj** [comment]
@SaptakS terrific news. It may be helpful to document/notate in the planning doc what custom metrics you'd be looking for so your analysts can work on building them.

Reminder that they need to be impl'd, approved, and merged by May 27th. So time quickly running short

**Comment by SaptakS** [comment]
Yes. I will discuss that with my analysts and put it in the docs.

**Comment by SaptakS** [comment]
@foxdavidj  here's a brief note on the current status of this chapter:
- We have a rough outline ready. It may change slightly during writing depending on things we get to see from custom metrics, and exact placement of a sub-topic, but the topics to be discussed in the outline are ready.
- @vikvanderlinden has been working on writing custom metrics for two main new things that we are looking at this year:
  - New `.well-known` URIs : https://github.com/HTTPArchive/custom-metrics/pull/22 (Already merged)
  - Visibility Observer API to test if websites are using [UI Security standards](url) : https://github.com/HTTPArchive/custom-metrics/pull/23. The other part of the UI Security is related to CSP directives, which we are already collecting so no custom metrics needed,

**Comment by foxdavidj** [comment]
Thanks for the update! Excited to see those new custom metrics :)

**Comment by clarkio** [comment]
It's great to get acquainted with all this and see the progress so far. Is there anything needed for my and @lirantal's role as reviewers here yet?

**Comment by SaptakS** [comment]
@clarkio I think @lirantal was added as an author. So I am hoping to divide the work and start writing by July end, since the query results should start coming in by then. Me, @lirantal and @feross will need to divide the writing that time among us and start writing the draft in the [google docs](https://docs.google.com/document/d/1vit05gwIZI9oE-AM1D0hZDNDl3sZ-8fAMlLIJ4b8Cg0/edit?usp=sharing). Once that process is started (or at the end of the process whichever you prefer as a reviewer), the reviewers can start leaving comments in the docs, which the authors can then address. All that should be done by September 1st.

So I would say you can definitely leave any thoughts about the outline or suggestions you think we should keep in mind while writing for now. I hope you all have access to the google docs. If not, please request access.

**Comment by SaptakS** [comment]
Just to keep everyone in the loop:
- @vikvanderlinden @VictorLeP @GJFR have run the queries and put most of the data in excel spreadsheet. They have also started making the charts. Few queries needed update, which have now been merged.
- I (@SaptakS ) has contacted both @feross and @lirantal to discuss who writes what parts of the outline.
- I (@SaptakS ) have started writing a rough draft of the chapter already seeing the data from the spreadsheet.
- Once the chapter draft is at a good place, I will nudge the reviewers to start leaving comments.

cc @foxdavidj

**Comment by VictorLeP** [comment]
A few more query updates will still be needed, but those are mostly done (just need to write them up according to standards), bur since I'm travelling, it might take a day to finish and push them.

**Comment by foxdavidj** [comment]
@SaptakS How's the chapter coming along? Looks like it's in great shape so far

**Comment by SaptakS** [comment]
@foxdavidj I would say we are mostly on track for the release. The queries have been ran and graphs have been generated. Thanks @GJFR @VictorLeP @vikvanderlinden for the amazing work! I am midway through the writing process. Also pinged @feross and @lirantal about writing their sections.

**Comment by brumka** [comment]
Suggestion: should we call out "CNAME Tracking" (aka "CNAME collusion") mentioned in the Privacy chapter as a security issue?  By using such technique, the tracking companies can get full access to the first party cookies despite the countermeasures built into browsers.

**Comment by SaptakS** [comment]
> Suggestion: should we call out "CNAME Tracking" (aka "CNAME collusion") mentioned in the Privacy chapter as a security issue? By using such technique, the tracking companies can get full access to the first party cookies despite the countermeasures built into browsers.

Definitely can add a link to the privacy chapter section with a line about this technique. Would you agree that the best place to put this would be in the Cookies outline?

**Comment by brumka** [comment]
> > Suggestion: should we call out "CNAME Tracking" (aka "CNAME collusion") mentioned in the Privacy chapter as a security issue? By using such technique, the tracking companies can get full access to the first party cookies despite the countermeasures built into browsers.
> 
> Definitely can add a link to the privacy chapter section with a line about this technique. Would you agree that the best place to put this would be in the Cookies outline?

Yes, that would make a perfect sense.  Thank you.

**Comment by SaptakS** [comment]
@clarkio are you still interested in reviewing? I don't see you in slack, but I think the chapter has enough draft content right now that the reviewing can start. Let me know if you have any questions. Thanks!

**Comment by clarkio** [comment]
@SaptakS yes happy to still help in reviewing. Sorry I didn't catch there was a slack 😅

**Comment by lirantal** [comment]
FYI all - just chiming in here to update that things are going as plan and I'm aiming to finish with my assigned `Content Inclusion` content by the weekend. I'll work with @SaptakS about getting all of it in formally as I'm new to the actual process, formatting, etc :-)

**Comment by foxdavidj** [comment]
@SaptakS We're now past the September 15th deadline, but it looks like the chapter has gotten some healthy review (🎉) which is great.

I really want to get this in front of editors ASAP. How confident are you about getting the conclusion written and the reviews addressed by Mon, Sep 19?


Thanks for putting in so much time with your chapters. I know you've also been hard at work rescuing the A11Y chapter ❤️

**Comment by SaptakS** [comment]
> I really want to get this in front of editors ASAP. How confident are you about getting the conclusion written and the reviews addressed by Mon, Sep 19?

I will write the conclusion by tonight. I think @tunetheweb  had already started editing the rest of the chapter. I have addressed most of the reviews. I will need to add some links which I will do.

**Comment by tunetheweb** [comment]
Yeah, I've done about half the edit. So hope a very light technical edit that can wait for the PR after I finish that.

**Comment by lirantal** [comment]
Thank you all for the reviews! 🙌🏽

**Comment by clarkio** [comment]
Let me know if you all need anything else from my end 👍
