### ISSUE TITLE
PWA 2022

### ISSUE THREAD

**Issue by rviscomi** [HTTPArchive/almanac.httparchive.org#2895]
# PWA 2022

![PWA illustration](https://raw.githubusercontent.com/HTTPArchive/almanac.httparchive.org/main/src/static/images/2019/pwa/hero_lg.jpg)

If you're interested in contributing to the PWA chapter of the 2022 Web Almanac, please reply to this issue and indicate which role or roles best fit your interest and availability: [author](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Authors'-Guide), [reviewer](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Reviewers'-Guide), [analyst](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Analysts'-Guide), and/or [editor](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Editors'-Guide).

## Content team

| Lead | Authors | Reviewers | Analysts | Editors | Coordinator |
| ---- | ------- | --------- | -------- | ------- | ----------- |
| @diekus | @diekus @Suzzicks | @aarongustafson @webmaxru @Schweinepriester @tropicadri @beth-panx @tropicadri | @beth-panx | @siwinlo | @foxdavidj |

<details>
<summary><b>Expand for more information about each role 👀</b></summary>

- The **[content team lead](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Content-Team-Leads'-Guide)** is the chapter owner and responsible for setting the scope of the chapter and managing contributors' day-to-day progress.
- **[Authors](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Authors'-Guide)** are subject matter experts and lead the content direction for each chapter. Chapters typically have one or two authors. Authors are responsible for planning the outline of the chapter, analyzing stats and trends, and writing the annual report.
- **[Reviewers](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Reviewers'-Guide)** are also subject matter experts and assist authors with technical reviews during the planning, analyzing, and writing phases.
- **[Analysts](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Analysts'-Guide)** are responsible for researching the stats and trends used throughout the Almanac. Analysts work closely with authors and reviewers during the planning phase to give direction on the types of stats that are possible from the dataset, and during the analyzing/writing phases to ensure that the stats are used correctly.
- **[Editors](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Editors'-Guide)** are technical writers who have a penchant for both technical and non-technical content correctness. Editors have a mastery of the English language and work closely with authors to help wordsmith content and ensure that everything fits together as a cohesive unit.
- The **[section coordinator](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Section-Leads'-Guide)** is the overall owner for all chapters within a section like "User Experience" or "Page Content" and helps to keep each chapter on schedule.

_Note: The time commitment for each role varies by the chapter's scope and complexity as well as the number of contributors._

For an overview of how the roles work together at each phase of the project, see the [Chapter Lifecycle](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Chapter-Lifecycle) doc.
</details>

### [**0. Form the content team**](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Chapter-Lifecycle#0-create-content-team)
+ [x] **May 1**: The content team has at least one author, reviewer, and analyst

### [**1. Plan content**](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Chapter-Lifecycle#1-plan-content)
+ [x] **May 15** The content team has completed the chapter outline in the [draft doc][~google-doc]

### [**2. Gather data**](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Chapter-Lifecycle#2-gather-data)
+ [x] **June 1**: Analysts have added all necessary [custom metrics](https://github.com/HTTPArchive/custom-metrics/blob/main/README.md) and drafted a PR ([example](https://github.com/HTTPArchive/almanac.httparchive.org/pull/1087)) to track query progress
- **June 1 - 15**: HTTP Archive runs the June crawl

### [**3. Validate results**](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Chapter-Lifecycle#3-validate-results)
+ [x] **August 1**: Analysts have queried all metrics and saved the output to the [results sheet][~google-sheets]

### [**4. Draft content**](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Chapter-Lifecycle#4-draft-content)
+ [x] **September 1**: The content team has written, reviewed, and edited the chapter in the [doc][~google-doc]

### [**5. Publication**](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Chapter-Lifecycle#5-publication)
+ [ ] **September 15**: The completed chapter and all required [metadata](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Authors'-Guide#metadata-to-add-at-the-top-of-your-chapters) and [figures](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Figures-Guide) are converted to markdown and submitted to [GitHub][~chapter-markdown]
- **September 26**: Target launch date 🚀

## Chapter resources

Refer to these 2022 PWA resources throughout the content creation process:

[📄 Google Docs][~google-doc] for outlining and drafting content
[🔍 SQL files][~sql-files] for committing the queries used during analysis
[📊 Google Sheets][~google-sheets] for saving the results of queries
[📝 Markdown file][~chapter-markdown] for publishing content and managing public metadata
[💬 #web-almanac-pwa on Slack][~slack-channel] for team coordination

[~google-doc]: https://docs.google.com/document/d/14riy6CwQslsBtR0iuhMe-V28AycTsTRilq2wn4yzRJU/edit?usp=sharing
[~sql-files]: https://github.com/HTTPArchive/almanac.httparchive.org/tree/main/sql/2022/pwa
[~google-sheets]: https://docs.google.com/spreadsheets/d/1PbzjhN--jU9MGuWobw5L9EsmlVzI9tlbCe3_NKA7giU/edit?usp=sharing
[~chapter-markdown]: https://github.com/HTTPArchive/almanac.httparchive.org/tree/main/src/content/en/2022/pwa.md
[~slack-channel]: https://join.slack.com/t/httparchive/shared_invite/zt-45sgwmnb-eDEatOhqssqNAKxxOSLAaA

**Comment by Suzzicks** [comment]
I can help if you want me to Lead or Author this topic.

**Comment by webmaxru** [comment]
Hello!
My pleasure to be a Reviewer for this year again!

**Comment by Schweinepriester** [comment]
Hello everyone! 👋
Same as @webmaxru, I'm happy to be a reviewer again :)

**Comment by siwinlo** [comment]
hello! I'd be happy to join as an editor!

**Comment by foxdavidj** [comment]
@webmaxru @Schweinepriester @siwinlo

Hi all, we need your help. We currently don't have a Lead for this chapter, which means we'll likely miss our first milestone (May 1st) which will put the chapter at risk of being dropped.

Can you all reach out to anyone you feel may be a good fit for a Lead/Authoring role for the chapter?

Thanks so much for your interest in helping us assemble the chapter this year

**Comment by Schweinepriester** [comment]
Maybe @Suzzicks wants to step up and be Lead? :)

I had typed the following before I realized @Suzzicks [said "Lead or Author"](https://github.com/HTTPArchive/almanac.httparchive.org/issues/2895#issuecomment-1097019665), preserving just in case 0:-)

     Perhaps last years great lead @demianrenzulli, last years capabilities lead and PWA enthusiast @christianliebel and/or fugu🐡 aficionado/champion @tomayac? :)

**Comment by tomayac** [comment]
@tropicadri is fully focused on PWA on Google's side, maybe she's interested? I will help out with the Capabilities chapter already and can't commit to more at the moment.

**Comment by tropicadri** [comment]
As much as I would want to, I don't have the bandwidth to lead. I can help but can't be the main point of contact.

**Comment by webmaxru** [comment]
Let me chat with PWA v-team of Microsoft about someone leading that

**Comment by rviscomi** [comment]
⚠️ @Suzzicks @webmaxru @Schweinepriester @tropicadri @siwinlo it looks like this chapter still doesn't have a lead or an analyst and the [outline](https://docs.google.com/document/d/14riy6CwQslsBtR0iuhMe-V28AycTsTRilq2wn4yzRJU/edit?usp=sharing) hasn't been started yet. We might have to drop this chapter if it doesn't seem like there's enough interest to sustain it.

Could you help us find contributors who can staff this chapter? Meanwhile, it'd be great to start brainstorming ideas in the doc and when we get the team fully formed we can hopefully get back on track quickly.

@webmaxru is anyone at Microsoft interested in contributing?

**Comment by tropicadri** [comment]
@snugug would you have any interest in leading this chapter for the web almanac?

**Comment by webmaxru** [comment]
> @webmaxru is anyone at Microsoft interested in contributing?
I'm on it - will keep you posted asap, let's wait with the decision on dropping this chapter for a few more days please.

Meanwhile, I requested an access to the working doc - ready to be an interim Lead to create doc structure and start adding some ideas.

**Comment by aarongustafson** [comment]
I’m happy to contribute however it would be helpful.

**Comment by aarongustafson** [comment]
@webmaxru If need be. If there are others who want to lead—particularly smart folks whose perspectives we don’t often hear—I’m open to working in a supporting capacity, but if there are still no takers and we’re down to the wire, I’m happy to step up.

**Comment by Snugug** [comment]
> @Snugug would you have any interest in leading this chapter for the web almanac?

Thanks for offering! I unfortunately don't think I've got capacity to lead this right now. I also echo what @aarongustafson has said that it'd be great to get perspective from folks we don't often hear.

**Comment by aarongustafson** [comment]
Maybe @diekus or @beth-panx would be interested?

**Comment by foxdavidj** [comment]
Hey @aarongustafson would you be willing to step up as the Content lead for the chapter? If so we'd love to have you!

**Comment by diekus** [comment]
Hola. I can help if required!

**Comment by aarongustafson** [comment]
@foxdavidj I would actually love to see @diekus lead this effort if you’re cool with it. I am happy to sign on as a reviewer and even an editor.

**Comment by foxdavidj** [comment]
@diekus @aarongustafson @beth-panx @Schweinepriester @siwinlo @Suzzicks @tropicadri @webmaxru

@diekus We'd love to have you as the [Chapter Lead](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Content-Team-Leads'-Guide) for the PWA chapter! Excited to have you :)

As the PWA team lead you'll be responsible for setting the narrative for the chapter's contents, coordinating with the rest of the contributors, and generally keeping it on schedule. The top comment contains all the information/links you need, otherwise let me know if there's anything we can clarify.

A few things so we can kick-start this chapter:

1. @diekus It looks like @Suzzicks would be interested in co-authoring with you. As the chapter lead, if this is something you'd be interested in, can you follow-up with them? And then edit the top comment to reflect any changes?
2. To kick things off, I'd love to set up a 30 minute call within the next week to put any new faces to names, and give @diekus feedback on their ideas for the chapter's outline. @diekus can you find a time that works well for the team? You can see my availability via my calendly here (no need to book through it, though): https://calendly.com/foxdavid/30min

Excited to see this chapter come together.

**Comment by diekus** [comment]
Hola @foxdavidj . It'd be great to co-author with @Suzzicks! I'll look into calendars and get up to speed on all the documentation in the first post.

**Comment by diekus** [comment]
I am assuming this is the best way to communicate with the team. I am  flexible to meet during the week, but as I am based in London my preferred times are (early-ish) morning West Coast times. Can I get an idea of where you're all based to make sure we convey on a time that's friendly hopefully for all of us?

**Comment by tropicadri** [comment]
I'm in california, so pacific time, also throwing this your way: https://whenavailable.com/ I used to coordinate meeting times with groups. You create the survey and then share the link, people vote with their availability.

**Comment by diekus** [comment]
Wicked Adri! Please mark your availability for: PWA Web Almanac Chapter kick off https://whenavailable.com/invite/v8MNlWxkHdwcm5m34PeN

**Comment by webmaxru** [comment]
Hello team!
I'm based in Oslo, Norway - CEST timezone. Looking forward to meeting you online|

**Comment by foxdavidj** [comment]
Hey @diekus, two things:

1. Have you been able to contact and/or start working with @Suzzicks? She's very responsive on Twitter if not.

2. How big of an ask would it be for me to request, once a week on Friday, an update on how the chapter is doing and any progress/hurdles/questions/etc you have. And post it to the github chapter issue? Can be a simple bullet list.

   It’d help me a lot with staying in the loop (and not nagging you) and making sure I’m helping you solve problems you’re facing.

   Thoughts?

**Comment by diekus** [comment]
I've message @Suzzicks this morning on twitter (assuming it is the same handle there!).

Yes, we can set up a weekly catchup call on Fridays.

**Comment by foxdavidj** [comment]
@diekus no need for a call. A simple bullet list posted in here would be more than enough 👍

**Comment by foxdavidj** [comment]
I like to rely on offline communication as much as possible, and only hold meetings when decisions need to be made

**Comment by foxdavidj** [comment]
@diekus How is the chapter coming along? Are you and the team satisfied with the current outline?

Looked like there was some active discussion in there, so wanted to check if it was still a WIP

**Comment by diekus** [comment]
@foxdavidj still a WIP. I am taking a look at the doc and adding some stuff. I am also contacting some folks that might have interesting data about PWAs in certain platforms. 

I met with @Suzzicks last week, and I expect by end of week to have a draft outline to discuss with the reviewers.

**Comment by foxdavidj** [comment]
Pinging @aarongustafson @webmaxru @Schweinepriester @tropicadri @beth-panx @tropicadri per Diekus's message above

**Comment by aarongustafson** [comment]
The revised outline looks great to me!

**Comment by beth-panx** [comment]
> @diekus have you walked through the outline with @beth-panx, the chapter's analyst?
> 
> We're approaching the deadline (June 1) for when a draft PR ([example](https://github.com/HTTPArchive/almanac.httparchive.org/pull/1087)) should be made for the analysis

@foxdavidj FYI that @diekus, @Suzzicks,  and I have met to discuss this. We are starting the collaboration on the query list this week. Consider the team was formed later than expected, I think we will likely miss the June 1 deadline for analytics draft PR. Reading the instructions, seems like the crawl happens every month, correct? Do you foresee any problems if we get this done later in June?

**Comment by beth-panx** [comment]
@foxdavidj - I read through the instructions for analyst and patterns to follow. Trying to create the initial query draft PR for PWA chapter. Do I need contributor access to push the branch or should I create a fork with the proposed title for the branch instead?

**Comment by tunetheweb** [comment]
Just sent you the invite there via GitHub @beth-panx. While a fork would be fine, doing it on the repo will allow others to easily access and add to any draft PR.

**Comment by tunetheweb** [comment]
> Reading the instructions, seems like the crawl happens every month, correct? Do you foresee any problems if we get this done later in June?

We want the almanac to all be passed of the same months data for consistency and timeline purposes. I know an awful lot of effort was put in last year to gather a lot of extra PWA metrics, so hopefully what is already gathered will be sufficient to allow that to happen AND for you to have the data you need to write the chapter.

**Comment by beth-panx** [comment]
> > Reading the instructions, seems like the crawl happens every month, correct? Do you foresee any problems if we get this done later in June?
> 
> We want the almanac to all be passed of the same months data for consistency and timeline purposes. I know an awful lot of effort was put in last year to gather a lot of extra PWA metrics, so hopefully what is already gathered will be sufficient to allow that to happen AND for you to have the data you need to write the chapter.

Thanks for the response! I will have a comparable queries draft setup based on last year's metrics in the next few days. We can start discussing extra queries after that.

**Comment by beth-panx** [comment]
Hi all - I have added queries from 2021 that are relevant and created tasks in the draft PR for additional queries and discussion points. Please start reviewing. Thank you!

**Comment by foxdavidj** [comment]
@diekus @beth-panx

The June crawl has completed and all of the data is available to start being queried.

How are you feeling about having all of the queries written by the end of the month? Looks like @beth-panx has already made a lot of progress.

**Comment by beth-panx** [comment]
> @diekus @beth-panx friendly ping

I am waiting for the list to be reviewed but can also testing the queries against June data next week.

**Comment by diekus** [comment]
Hello! I started reviewing, I'll finish by Sunday and report back.

**Comment by diekus** [comment]
I've synced with Beth on the queries, the only one that I am not sure how to get is support for Web Share API, since this is a JS API and not easily to find out if a PWA is invoking `navigator.share`. Any ideas on how to find out this area welcome!

**Comment by diekus** [comment]
@beth-panx let's add also queries for 

*Web Share API intersects PWA
* Prefers native apps
*Display Override
* Display Override for WCO
*File System Access API intersects PWA
*Push Notifications intersects PWA
*Add to home screen

**Comment by tomayac** [comment]
The Capabilities chapter has traditionally covered some of these APIs: https://almanac.httparchive.org/en/2021/capabilities.

- Web Share API intersects PWA: https://almanac.httparchive.org/en/2021/capabilities#web-share-api
- File System Access API intersects PWA: https://almanac.httparchive.org/en/2021/capabilities#file-system-access-api

**Comment by diekus** [comment]
Indeed! We checked this when we were developing the chapter, but we wanted to make a mention of the data when intersecting with PWAs. This is, from all web apps using such APIs, which are actual PWAs? It'd be interesting to note that x% of websites using web share api are installable web apps, for example.

**Comment by beth-panx** [comment]
Hi all - Most of the queries are done, validated, and translated into graph and added to the [result sheet](https://docs.google.com/spreadsheets/d/1PbzjhN--jU9MGuWobw5L9EsmlVzI9tlbCe3_NKA7giU/edit#gid=13487225). Please feel free to review. 🚀

**Comment by beth-panx** [comment]
Queries were reviewed and merged thanks to @tunetheweb! I have updated the result sheet based on the new queries. 🧠

**Comment by foxdavidj** [comment]
Fantastic work!! Thanks so much

**Comment by foxdavidj** [comment]
The queries have been run and saved in the [results sheet](https://docs.google.com/spreadsheets/d/1PbzjhN--jU9MGuWobw5L9EsmlVzI9tlbCe3_NKA7giU/edit#gid=13487225) @diekus @Suzzicks. Writing the chapter is fully green-lit

**Comment by foxdavidj** [comment]
@diekus @Suzzicks Have you been able to review the data from the analysts?

**Comment by diekus** [comment]
Yes, reviewed the data. I'll sync up with Cindy to proceed with writing

**Comment by foxdavidj** [comment]
@diekus @Suzzicks How's the chapter coming along?

**Comment by foxdavidj** [comment]
Hi @diekus hope you're doing well. Looks like there isnt any activity in the Google Doc and the writing deadline is fast approaching.

Is this something you'll be able to commit to writing in the next couple of weeks? Because, sadly, right now this chapter is at risk of being closed so that we can focus our effort on the other chapters.

**Comment by diekus** [comment]
Hi David. You'll have an update on the text this week. Sorry for the delay

**Comment by rviscomi** [comment]
⛔ Hi everyone. Given that we're now beyond the deadline to have the draft written, reviewed, and edited but the draft has still not been started, unfortunately I think we're going to have to close the chapter. It's not looking like it'll be feasible to get the chapter back on track to be able to launch on time. Apologies to everyone who committed their time up to this point, and thanks for your understanding.

**Comment by diekus** [comment]
Hi @rviscomi , I understand that the writing is meant to be done in September, which we are still in the first week. I started writing the chapter in a word doc, and there is still some time before the 15th to get this done. Do you think there is a window here? I have the manifest bits written and can continue with the SW stuff.

**Comment by rviscomi** [comment]
Hi @diekus. To clarify the [timeline](https://github.com/HTTPArchive/almanac.httparchive.org/issues/2895#issue-1202154899), the chapter was expected to be fully written, reviewed, and edited in the [shared doc](https://docs.google.com/document/d/14riy6CwQslsBtR0iuhMe-V28AycTsTRilq2wn4yzRJU/edit?usp=sharing) by **September 1**.

The September 15 milestone to have the final draft submitted to GitHub in markdown is in 7 days. It's going to be very hard to catch up with the draft being written in private doc, so if you're still committed to landing the chapter, I'd suggest moving it into the shared doc and coordinating with the rest of your team on a plan ASAP. However, if that doesn't sound feasible without compromising on quality, then I do think closing the chapter is the best option.

**Comment by diekus** [comment]
hola @rviscomi. I have a revised chapter in markdown with all chart macros ready and published [here](https://github.com/diekus/almanac.httparchive.org/blob/PWA22-chapter/src/content/en/2022/pwa.md).  I have some questions, that you might be able to help me with.

- where should I upload the images needed for each figure?
- how can I format the stat numbers so they can show in the big bold lettering? Is this a specific guide? I have several numbers that I want to highlight this way but I do not know how to do so.
- is there anything that I am missing?

**Comment by tunetheweb** [comment]
> * where should I upload the images needed for each figure?

See the [Figures Guide](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Figures-Guide).

There's a script to do this (`npm run figure-images en/2022/pwa`) which will generate them for you automatically!

Also handy to run locally (using `npm run start` after running the following:
- `cd src`
- `npm install`
- `pip install -U requirements.txt`
- `npm run start`
- Navigate to [http://127.0.0.1:8080](http://127.0.0.1:8080)

> * how can I format the stat numbers so they can show in the big bold lettering? Is this a specific guide? I have several numbers that I want to highlight this way but I do not know how to do so.

Detailed [here](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Figures-Guide#call-out-figure-examples).

> * is there anything that I am missing?

Has anyone else reviewed this content? Normally we do that in the Google Doc as easier to review and accept changes.

**Comment by tomayac** [comment]
(Just a side remark: thanks for still making this chapter happen `<3`!)

**Comment by diekus** [comment]
@tunetheweb it has been reviewed by @aarongustafson and @tropicadri . I am making the last changes and then will be ready to commit the chapter later today with the macros for images ready.

**Comment by webmaxru** [comment]
I also completed reviewing this article. Great job, @diekus!

**Comment by Schweinepriester** [comment]
Same, good job indeed!

**Comment by diekus** [comment]
Thanks to the reviewers and editors. I have one more question @tunetheweb, how can I find out which is the name of the sql script and the google tab id for the figures?

**Comment by tunetheweb** [comment]
The sheets id is the one in the URL when viewing that data.

There should be one tab in the sheet for each of these SQL files: https://github.com/HTTPArchive/almanac.httparchive.org/tree/main/sql/2022/pwa

**Comment by diekus** [comment]
You're a life saver @tunetheweb! Thank you very much. I have added the `sheets_gid` and the `sql` to the charts and figures in the PWA chapter. 

I believe this should be completed, and if there is anything else I need to do let me know, happy to get the PWA over the finishing line. 

Apologies for the delays! 😳
