### ISSUE TITLE
Page Weight 2022

### ISSUE THREAD

**Issue by rviscomi** [HTTPArchive/almanac.httparchive.org#2899]
# Page Weight 2022

![Page Weight illustration](https://raw.githubusercontent.com/HTTPArchive/almanac.httparchive.org/main/src/static/images/2019/page-weight/hero_lg.jpg)

If you're interested in contributing to the Page Weight chapter of the 2022 Web Almanac, please reply to this issue and indicate which role or roles best fit your interest and availability: [author](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Authors'-Guide), [reviewer](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Reviewers'-Guide), [analyst](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Analysts'-Guide), and/or [editor](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Editors'-Guide).

## Content team

| Lead | Authors | Reviewers | Analysts | Editors | Coordinator |
| ---- | ------- | --------- | -------- | ------- | ----------- |
| @fellowhuman1101 | @fellowhuman1101 @dwsmart | @CSteele-gh @mordy-oberstein | @drohe | - | @paulcalvano |

<details>
<summary><b>Expand for more information about each role 👀</b></summary>

- The **[content team lead](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Content-Team-Leads'-Guide)** is the chapter owner and responsible for setting the scope of the chapter and managing contributors' day-to-day progress.
- **[Authors](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Authors'-Guide)** are subject matter experts and lead the content direction for each chapter. Chapters typically have one or two authors. Authors are responsible for planning the outline of the chapter, analyzing stats and trends, and writing the annual report.
- **[Reviewers](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Reviewers'-Guide)** are also subject matter experts and assist authors with technical reviews during the planning, analyzing, and writing phases.
- **[Analysts](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Analysts'-Guide)** are responsible for researching the stats and trends used throughout the Almanac. Analysts work closely with authors and reviewers during the planning phase to give direction on the types of stats that are possible from the dataset, and during the analyzing/writing phases to ensure that the stats are used correctly.
- **[Editors](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Editors'-Guide)** are technical writers who have a penchant for both technical and non-technical content correctness. Editors have a mastery of the English language and work closely with authors to help wordsmith content and ensure that everything fits together as a cohesive unit.
- The **[section coordinator](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Section-Leads'-Guide)** is the overall owner for all chapters within a section like "User Experience" or "Page Content" and helps to keep each chapter on schedule.

_Note: The time commitment for each role varies by the chapter's scope and complexity as well as the number of contributors._

For an overview of how the roles work together at each phase of the project, see the [Chapter Lifecycle](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Chapter-Lifecycle) doc.
</details>

### [**0. Form the content team**](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Chapter-Lifecycle#0-create-content-team)
+ [x] **May 1**: The content team has at least one author, reviewer, and analyst

### [**1. Plan content**](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Chapter-Lifecycle#1-plan-content)
+ [x] **May 15** The content team has completed the chapter outline in the [draft doc][~google-doc]

### [**2. Gather data**](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Chapter-Lifecycle#2-gather-data)
+ [x] **June 1**: Analysts have added all necessary [custom metrics](https://github.com/HTTPArchive/custom-metrics/blob/main/README.md) and drafted a PR ([example](https://github.com/HTTPArchive/almanac.httparchive.org/pull/1087)) to track query progress
- **June 1 - 15**: HTTP Archive runs the June crawl

### [**3. Validate results**](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Chapter-Lifecycle#3-validate-results)
+ [x] **August 1**: Analysts have queried all metrics and saved the output to the [results sheet][~google-sheets]

### [**4. Draft content**](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Chapter-Lifecycle#4-draft-content)
+ [ ] **September 1**: The content team has written, reviewed, and edited the chapter in the [doc][~google-doc]

### [**5. Publication**](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Chapter-Lifecycle#5-publication)
+ [ ] **September 15**: The completed chapter and all required [metadata](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Authors'-Guide#metadata-to-add-at-the-top-of-your-chapters) and [figures](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Figures-Guide) are converted to markdown and submitted to [GitHub][~chapter-markdown]
- **September 26**: Target launch date 🚀

## Chapter resources

Refer to these 2022 Page Weight resources throughout the content creation process:

[📄 Google Docs][~google-doc] for outlining and drafting content
[🔍 SQL files][~sql-files] for committing the queries used during analysis
[📊 Google Sheets][~google-sheets] for saving the results of queries
[📝 Markdown file][~chapter-markdown] for publishing content and managing public metadata
[💬 #web-almanac-page-weight on Slack][~slack-channel] for team coordination

[~google-doc]: https://docs.google.com/document/d/1sEuLeW-o1N9B8WINy8iw5FblzSIkVOSedVu0JERrJVw/edit?usp=sharing
[~sql-files]: https://github.com/HTTPArchive/almanac.httparchive.org/tree/main/sql/2022/page-weight
[~google-sheets]: https://docs.google.com/spreadsheets/d/1JvJMiRsL6T9m_NEBHFh-rrQmU5a-ufdOKriSJbrEN8M/edit?usp=sharing
[~chapter-markdown]: https://github.com/HTTPArchive/almanac.httparchive.org/tree/main/src/content/en/2022/page-weight.md
[~slack-channel]: https://join.slack.com/t/httparchive/shared_invite/zt-45sgwmnb-eDEatOhqssqNAKxxOSLAaA

**Comment by fellowhuman1101** [comment]
@dwsmart and I volunteer to author 🤘

**Comment by dwsmart** [comment]
Happy to help author on this one.

**Comment by rviscomi** [comment]
@fellowhuman1101 would you be able to take on the [content team lead](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Content-Team-Leads'-Guide) role? You'd be responsible for project-managing this chapter and keeping it on track.

**Comment by rviscomi** [comment]
@fellowhuman1101 @dwsmart also could you both request access to the [chapter planning doc](https://docs.google.com/document/d/1sEuLeW-o1N9B8WINy8iw5FblzSIkVOSedVu0JERrJVw/edit?usp=sharing) and start outlining the contents of the chapter? We also have a [`#web-almanac-page-weight`](https://join.slack.com/t/httparchive/shared_invite/zt-45sgwmnb-eDEatOhqssqNAKxxOSLAaA) channel on Slack where you and the rest of the team can coordinate.

For now the most pressing task is to staff the rest of the content team with at least one reviewer and analyst (technically due yesterday). Could you reach out to your networks to see if anyone would be interested to join? Alternatively, one of you could be the reviewer and/or analyst.

After that, the next milestone is to complete the outline by May 15.

**Comment by fellowhuman1101** [comment]
@rviscomi happy to take on project management for this chapter. Access to the planning doc requested.

**Comment by rviscomi** [comment]
Thanks @fellowhuman1101! Access granted 🟢 🟢 🟢

**Comment by drohe** [comment]
Hi! I'd be happy to take on the analyst role!

**Comment by CSteele-gh** [comment]
I'd like to be a reviewer

**Comment by rviscomi** [comment]
Great, thank you and welcome @CSteele-gh! See https://github.com/HTTPArchive/almanac.httparchive.org/issues/2899#issuecomment-1115211445 for the next steps.

@fellowhuman1101 now that the content team is filled out with at least one person in each role, you can check off Milestone 0 at the top of the issue. At this stage everyone should be collaborating on the outline in the chapter doc with the goal of having it completed by May 15.

**Comment by mordy-oberstein** [comment]
Would be happy to help

**Comment by rviscomi** [comment]
Thanks @mordy-oberstein! I presume you're interested in the [Reviewer](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Reviewers'-Guide) role?

**Comment by rviscomi** [comment]
@fellowhuman1101 @dwsmart @CSteele-gh @mordy-oberstein @drohe hi all, reminder to access the [planning doc](https://docs.google.com/document/d/1sEuLeW-o1N9B8WINy8iw5FblzSIkVOSedVu0JERrJVw/edit?usp=sharing) and start brainstorming content for the outline. We're hoping to have that completed by May 15 to stay on schedule. Thanks!

**Comment by rviscomi** [comment]
@fellowhuman1101 @dwsmart @CSteele-gh @mordy-oberstein the analysis is done and the results are available in the [sheet](https://docs.google.com/spreadsheets/d/1JvJMiRsL6T9m_NEBHFh-rrQmU5a-ufdOKriSJbrEN8M/edit?usp=sharing). Go through the results and ping @drohe if you have any questions.

@fellowhuman1101 please coordinate with your team to get the draft written, reviewed, and edited by September 1 to ensure that it's released on time. You may want to divide up the sections with @dwsmart to write in parallel. You should also give your reviewers an expectation of when the draft will be ready for review so they can carve out the time. There isn't currently an editor assigned so reach out to @paulcalvano when the draft is reviewed and we'll find one for you.

Looking forward to reading it! 🚀

**Comment by fellowhuman1101** [comment]
@paulcalvano we're ready for an editor
