### ISSUE TITLE
CDN 2022

### ISSUE THREAD

**Issue by rviscomi** [HTTPArchive/almanac.httparchive.org#2900]
# CDN 2022

![CDN illustration](https://raw.githubusercontent.com/HTTPArchive/almanac.httparchive.org/main/src/static/images/2019/cdn/hero_lg.jpg)

If you're interested in contributing to the CDN chapter of the 2022 Web Almanac, please reply to this issue and indicate which role or roles best fit your interest and availability: [author](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Authors'-Guide), [reviewer](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Reviewers'-Guide), [analyst](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Analysts'-Guide), and/or [editor](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Editors'-Guide).

## Content team

| Lead | Authors | Reviewers | Analysts | Editors | Coordinator |
| ---- | ------- | --------- | -------- | ------- | ----------- |
| @harendra | @harendra @joeviggiano | @ytkoka | @harendra @joeviggiano | @tunetheweb | @paulcalvano |

<details>
<summary><b>Expand for more information about each role 👀</b></summary>

- The **[content team lead](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Content-Team-Leads'-Guide)** is the chapter owner and responsible for setting the scope of the chapter and managing contributors' day-to-day progress.
- **[Authors](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Authors'-Guide)** are subject matter experts and lead the content direction for each chapter. Chapters typically have one or two authors. Authors are responsible for planning the outline of the chapter, analyzing stats and trends, and writing the annual report.
- **[Reviewers](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Reviewers'-Guide)** are also subject matter experts and assist authors with technical reviews during the planning, analyzing, and writing phases.
- **[Analysts](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Analysts'-Guide)** are responsible for researching the stats and trends used throughout the Almanac. Analysts work closely with authors and reviewers during the planning phase to give direction on the types of stats that are possible from the dataset, and during the analyzing/writing phases to ensure that the stats are used correctly.
- **[Editors](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Editors'-Guide)** are technical writers who have a penchant for both technical and non-technical content correctness. Editors have a mastery of the English language and work closely with authors to help wordsmith content and ensure that everything fits together as a cohesive unit.
- The **[section coordinator](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Section-Leads'-Guide)** is the overall owner for all chapters within a section like "User Experience" or "Page Content" and helps to keep each chapter on schedule.

_Note: The time commitment for each role varies by the chapter's scope and complexity as well as the number of contributors._

For an overview of how the roles work together at each phase of the project, see the [Chapter Lifecycle](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Chapter-Lifecycle) doc.
</details>

### [**0. Form the content team**](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Chapter-Lifecycle#0-create-content-team)
+ [x] **May 1**: The content team has at least one author, reviewer, and analyst

### [**1. Plan content**](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Chapter-Lifecycle#1-plan-content)
+ [x] **May 15** The content team has completed the chapter outline in the [draft doc][~google-doc]

### [**2. Gather data**](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Chapter-Lifecycle#2-gather-data)
+ [x] **June 1**: Analysts have added all necessary [custom metrics](https://github.com/HTTPArchive/custom-metrics/blob/main/README.md) and drafted a PR ([example](https://github.com/HTTPArchive/almanac.httparchive.org/pull/1087)) to track query progress
- **June 1 - 15**: HTTP Archive runs the June crawl

### [**3. Validate results**](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Chapter-Lifecycle#3-validate-results)
+ [x] **August 1**: Analysts have queried all metrics and saved the output to the [results sheet][~google-sheets]

### [**4. Draft content**](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Chapter-Lifecycle#4-draft-content)
+ [x] **September 1**: The content team has written, reviewed, and edited the chapter in the [doc][~google-doc]

### [**5. Publication**](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Chapter-Lifecycle#5-publication)
+ [x] **September 15**: The completed chapter and all required [metadata](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Authors'-Guide#metadata-to-add-at-the-top-of-your-chapters) and [figures](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Figures-Guide) are converted to markdown and submitted to [GitHub][~chapter-markdown]
- **September 26**: Target launch date 🚀

## Chapter resources

Refer to these 2022 CDN resources throughout the content creation process:

[📄 Google Docs][~google-doc] for outlining and drafting content
[🔍 SQL files][~sql-files] for committing the queries used during analysis
[📊 Google Sheets][~google-sheets] for saving the results of queries
[📝 Markdown file][~chapter-markdown] for publishing content and managing public metadata
[💬 #web-almanac-cdn on Slack][~slack-channel] for team coordination

[~google-doc]: https://docs.google.com/document/d/1lTrBZGE00XsiFesalFJg5zCzhtMbsrJ5CcdH2eQ_HKE/edit?usp=sharing
[~sql-files]: https://github.com/HTTPArchive/almanac.httparchive.org/tree/main/sql/2022/cdn
[~google-sheets]: https://docs.google.com/spreadsheets/d/1ySETT2IZ9ae5_VUphxUol2ZU3P1RJvcSVjDU5BgnK5A/edit?usp=sharing
[~chapter-markdown]: https://github.com/HTTPArchive/almanac.httparchive.org/tree/main/src/content/en/2022/cdn.md
[~slack-channel]: https://join.slack.com/t/httparchive/shared_invite/zt-45sgwmnb-eDEatOhqssqNAKxxOSLAaA

**Comment by Navaneeth-Akamai** [comment]
@rviscomi Hope you are doing good! Wanted to add my nomination to author/be the content lead for CDN Chapter 2022 :) Want to pick it up from where we left it last time and see how the CDN landscape has moved on from the last time we published it.

**Comment by rviscomi** [comment]
Welcome back @Navaneeth-Akamai! Thank you for stepping up to lead the CDN chapter again!

The most urgent need is to staff the rest of the team (Milestone 0, due yesterday). @jzyang @boosef @paulcalvano would either of you be interested to join again as reviewers and/or analysts?

While we try to find other contributors, please request access to the [chapter planning doc](https://docs.google.com/document/d/1lTrBZGE00XsiFesalFJg5zCzhtMbsrJ5CcdH2eQ_HKE/edit?usp=sharing) and join the [`#web-almanac-cdn`](https://join.slack.com/t/httparchive/shared_invite/zt-45sgwmnb-eDEatOhqssqNAKxxOSLAaA) channel on Slack to coordinate as the team fills out.

@Navaneeth-Akamai the next milestone is due May 15 and we're looking to have a completed outline for the chapter. It's fine to start with the 2021 table of contents and tweak it as needed. Thanks!

**Comment by Navaneeth-Akamai** [comment]
Thanks Rick! let me ask around if anyone i know off is ready to help us with the tasks

**Comment by rviscomi** [comment]
⚠️ @Navaneeth-Akamai any progress on finding someone to review/analyze this chapter? The [outline](https://docs.google.com/document/d/1lTrBZGE00XsiFesalFJg5zCzhtMbsrJ5CcdH2eQ_HKE/edit?usp=sharing) also doesn't seem to have been started yet so this chapter is at risk of falling behind. Would be great to get some ideas added to the doc and fill out the rest of the team ASAP. Thanks for your help!

**Comment by brassic-lint** [comment]
Hey, I'd be interested in helping out with Reviewing/Editing if you still need people!

**Comment by rviscomi** [comment]
Thanks @brassic-lint it's great to have you!

@Navaneeth-Akamai given the subject of this chapter I think it's less likely that we'll need any custom metrics, so let's extend the deadline for the completion of the outline to June 1. After that, I'd expect the team to have a firmer idea of the chapter's narrative and what metrics need to be queried in order to stay on track. Given that we're still missing an analyst, I do still consider this chapter as being at high risk of not making it into the final publication, so let's reevaluate the status on June 1.

**Comment by m-shafiul** [comment]
I would like to contribute to the project as an analyst. If there are any other aspects of the project that requires assistance, more than happy to help.

**Comment by rviscomi** [comment]
Thanks @brassic-lint @vgotluru @joeviggiano @m-shafiul for all stepping up to staff this chapter and keep it on track!

@Navaneeth-Akamai any progress on the [chapter outline](https://docs.google.com/document/d/1lTrBZGE00XsiFesalFJg5zCzhtMbsrJ5CcdH2eQ_HKE/edit?usp=sharing)? I've seeded it with the outline from [2021](https://almanac.httparchive.org/en/2021/cdn) but it'd be great to flesh it out with any more details that you'd like to cover, beyond rerunning last year's queries.

**Comment by Navaneeth-Akamai** [comment]
Sure @rviscomi! I'm on it!

**Comment by sagrao** [comment]
Would like to contribute as a Co-author for this project.

**Comment by rviscomi** [comment]
Welcome @sagrao! 🎉 

@Navaneeth-Akamai do you need help coauthoring the chapter?

Meanwhile, @sagrao it'd be great if you added your ideas to the [chapter outline](https://docs.google.com/document/d/1lTrBZGE00XsiFesalFJg5zCzhtMbsrJ5CcdH2eQ_HKE/edit?usp=sharing) (request edit access) for topics to cover beyond last year's chapter and any additional depth needed.

**Comment by harendra** [comment]
Hi this is Haren from AWS, would like to contribute as a data analyst.

**Comment by rviscomi** [comment]
👋 Welcome @harendra @abutail!

Go ahead and request access to the [chapter planning doc](https://docs.google.com/document/d/1lTrBZGE00XsiFesalFJg5zCzhtMbsrJ5CcdH2eQ_HKE/edit?usp=sharing) and add any ideas for topics to cover to the outline.

**Comment by somecloudguy** [comment]
Hi this is Karan from AWS, I would like to contribute as a co-author

**Comment by rviscomi** [comment]
⚠️ @Navaneeth-Akamai just checking in. I see that this chapter is still behind on Milestone 2 (drafting the analysis PR) and we're fast approaching the deadline for Milestone 3 (completing the analysis). Want to make sure this chapter is staying on track with the rest of the chapters to be launched in September. Could you give us a status update on when you expect to have these completed?

You should also be coordinating with your analysts @joeviggiano @m-shafiul and @harendra to get them set up on our BigQuery project and clarify what needs to be queried. This chapter is fortunate to have so many analysis so hopefully we can get it back on track quickly.

Hope all is well!

**Comment by Navaneeth-akam** [comment]
> ⚠️ @Navaneeth-Akamai just checking in. I see that this chapter is still behind on Milestone 2 (drafting the analysis PR) and we're fast approaching the deadline for Milestone 3 (completing the analysis). Want to make sure this chapter is staying on track with the rest of the chapters to be launched in September. Could you give us a status update on when you expect to have these completed?
> 
> You should also be coordinating with your analysts @joeviggiano @m-shafiul and @harendra to get them set up on our BigQuery project and clarify what needs to be queried. This chapter is fortunate to have so many analysis so hopefully we can get it back on track quickly.
> 
> Hope all is well!

@rviscomi : I was on time off for last few weeks and back now. I'll check on the status here and get this going

**Comment by rviscomi** [comment]
The analysis PR has been merged and the results available in the [sheet](https://docs.google.com/spreadsheets/d/1ySETT2IZ9ae5_VUphxUol2ZU3P1RJvcSVjDU5BgnK5A/edit?usp=sharing) with charts.

@Navaneeth-Akamai @sagrao @abutail @somecloudguy @brassic-lint @vgotluru please start reviewing the results and reach out to the analysts if you have any questions. In order to be released on time, the draft must be written, reviewed, and edited by September 1, so not much time left.

@Navaneeth-Akamai it'd be a good idea to coordinate with your coauthors on which sections they'll write so you can work in parallel. You should also coordinate with your reviewers to make sure they have time to review the draft once it's written. You don't currently have an editor assigned, so ping @paulcalvano when the draft has been peer reviewed and we'll assign you an editor to go over it.

**Comment by rviscomi** [comment]
⛔ Hi everyone. Given that we're now beyond the deadline to have the draft written, reviewed, and edited but the draft has still not been started, unfortunately I think we're going to have to close the chapter. It's not looking like it'll be feasible to get the chapter back on track to be able to launch on time. Apologies to everyone who committed their time up to this point, and thanks for your understanding.

**Comment by joeviggiano** [comment]
@rviscomi I'd like to try and get this out the door before the next two week deadline, I'll start working on the report ASAP.

**Comment by rviscomi** [comment]
Thanks for picking this back up @joeviggiano! I'm going to reiterate what I shared with the [Accessibility](https://github.com/HTTPArchive/almanac.httparchive.org/issues/2889#issuecomment-1205461932) team when they were considering reopening the chapter:

> The chapter is still closed. It's fallen too far behind for us to plan on including it in this year's publication. BUT the people I've chatted with are still very interested to salvage the chapter.
>
>If the chapter can meet the following requirements, we'll be able to reverse the decision to close it:
>
>- The chapter must be data-driven, so there needs to be a substantial amount of data backing it up. Reusing the 2021 outline and queries would accomplish this.
>- The content must be original, not a simple rewording of last year's authors.
>- The chapter must be peer reviewed and edited by someone other than the authors, following the guidelines in the wiki ([Reviewers' Guide](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Reviewers'-Guide), [Editors' Guide](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Editors'-Guide)).
>- The chapter must be fully caught up with all milestones by the publication deadline on ~September 15~ **October 10**, no exceptions.
>
>To be clear, I am strongly discouraging this plan because of the enormous amount of work to be done in a short amount of time. But I won't stop anyone from trying to get it back on track, and I'll commit to reversing the decision if the requirements are met. Thanks everyone for your understanding, this is a tough decision and I'd like to be as fair as possible.

**Anyone who still wants to contribute to the chapter is welcome to do so. Please reply here and/or coordinate in the Slack channel about tackling the remaining work.**

@joeviggiano who will be the authors and reviewers?

**Comment by joeviggiano** [comment]
I will be an author and @harendra will review. If you require more reviewers I'll try and recruit more this week.

**Comment by ytkoka** [comment]
Hi, Thank you for inviting me, I am happy to review the CDN content.

**Comment by rviscomi** [comment]
Thanks @joeviggiano @harendra @ytkoka! Reopening this issue to track its progress. Let us know how it goes.

**Comment by tunetheweb** [comment]
And it's live!!!

https://almanac.httparchive.org/en/2022/cdn

Tweet here: https://twitter.com/HTTPArchive/status/1580544982079123457?s=20&t=uI0cYaHO6Zi56twcPMdn0g
