### ISSUE TITLE
Caching 2022

### ISSUE THREAD

**Issue by rviscomi** [HTTPArchive/almanac.httparchive.org#2902]
# Caching 2022

![Caching illustration](https://raw.githubusercontent.com/HTTPArchive/almanac.httparchive.org/main/src/static/images/2019/caching/hero_lg.jpg)

If you're interested in contributing to the Caching chapter of the 2022 Web Almanac, please reply to this issue and indicate which role or roles best fit your interest and availability: [author](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Authors'-Guide), [reviewer](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Reviewers'-Guide), [analyst](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Analysts'-Guide), and/or [editor](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Editors'-Guide).

## Content team

| Lead | Authors | Reviewers | Analysts | Editors | Coordinator |
| ---- | ------- | --------- | -------- | ------- | ----------- |
| @roryhewitt | @roryhewitt | @rrajiv | @kevinfarrugia | - | @paulcalvano |

<details>
<summary><b>Expand for more information about each role 👀</b></summary>

- The **[content team lead](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Content-Team-Leads'-Guide)** is the chapter owner and responsible for setting the scope of the chapter and managing contributors' day-to-day progress.
- **[Authors](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Authors'-Guide)** are subject matter experts and lead the content direction for each chapter. Chapters typically have one or two authors. Authors are responsible for planning the outline of the chapter, analyzing stats and trends, and writing the annual report.
- **[Reviewers](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Reviewers'-Guide)** are also subject matter experts and assist authors with technical reviews during the planning, analyzing, and writing phases.
- **[Analysts](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Analysts'-Guide)** are responsible for researching the stats and trends used throughout the Almanac. Analysts work closely with authors and reviewers during the planning phase to give direction on the types of stats that are possible from the dataset, and during the analyzing/writing phases to ensure that the stats are used correctly.
- **[Editors](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Editors'-Guide)** are technical writers who have a penchant for both technical and non-technical content correctness. Editors have a mastery of the English language and work closely with authors to help wordsmith content and ensure that everything fits together as a cohesive unit.
- The **[section coordinator](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Section-Leads'-Guide)** is the overall owner for all chapters within a section like "User Experience" or "Page Content" and helps to keep each chapter on schedule.

_Note: The time commitment for each role varies by the chapter's scope and complexity as well as the number of contributors._

For an overview of how the roles work together at each phase of the project, see the [Chapter Lifecycle](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Chapter-Lifecycle) doc.
</details>

### [**0. Form the content team**](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Chapter-Lifecycle#0-create-content-team)
+ [x] **May 1**: The content team has at least one author, reviewer, and analyst

### [**1. Plan content**](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Chapter-Lifecycle#1-plan-content)
+ [ ] **May 15** The content team has completed the chapter outline in the [draft doc][~google-doc]

### [**2. Gather data**](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Chapter-Lifecycle#2-gather-data)
+ [ ] **June 1**: Analysts have added all necessary [custom metrics](https://github.com/HTTPArchive/custom-metrics/blob/main/README.md) and drafted a PR ([example](https://github.com/HTTPArchive/almanac.httparchive.org/pull/1087)) to track query progress
- **June 1 - 15**: HTTP Archive runs the June crawl

### [**3. Validate results**](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Chapter-Lifecycle#3-validate-results)
+ [ ] **August 1**: Analysts have queried all metrics and saved the output to the [results sheet][~google-sheets]

### [**4. Draft content**](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Chapter-Lifecycle#4-draft-content)
+ [ ] **September 1**: The content team has written, reviewed, and edited the chapter in the [doc][~google-doc]

### [**5. Publication**](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Chapter-Lifecycle#5-publication)
+ [ ] **September 15**: The completed chapter and all required [metadata](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Authors'-Guide#metadata-to-add-at-the-top-of-your-chapters) and [figures](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Figures-Guide) are converted to markdown and submitted to [GitHub][~chapter-markdown]
- **September 26**: Target launch date 🚀

## Chapter resources

Refer to these 2022 Caching resources throughout the content creation process:

[📄 Google Docs][~google-doc] for outlining and drafting content
[🔍 SQL files][~sql-files] for committing the queries used during analysis
[📊 Google Sheets][~google-sheets] for saving the results of queries
[📝 Markdown file][~chapter-markdown] for publishing content and managing public metadata
[💬 #web-almanac-caching on Slack][~slack-channel] for team coordination

[~google-doc]: https://docs.google.com/document/d/1mLG--jMsvP85L02ft5o3_BhbHwy_pDejl-7FH95RH4I/edit?usp=sharing
[~sql-files]: https://github.com/HTTPArchive/almanac.httparchive.org/tree/main/sql/2022/caching
[~google-sheets]: https://docs.google.com/spreadsheets/d/16wQoA9ZciYkdW65RfR6CuW9H8TdMTQjhLuTSvVlN_rs/edit?usp=sharing
[~chapter-markdown]: https://github.com/HTTPArchive/almanac.httparchive.org/tree/main/src/content/en/2022/caching.md
[~slack-channel]: https://join.slack.com/t/httparchive/shared_invite/zt-45sgwmnb-eDEatOhqssqNAKxxOSLAaA

**Comment by roryhewitt** [comment]
Well I've been an Author (2020) and a Reviewer (2021). If you need authors or reviewers for 2022, I'm in again :)

**Comment by rrajiv** [comment]
Hi @rviscomi - i'd like to be a reviewer for this chapter. Thanks.

**Comment by rviscomi** [comment]
Thank you @roryhewitt @rrajiv @kevinfarrugia for stepping up to contribute to this year's Caching chapter!

@roryhewitt I've put you down as the content team lead, so you'll be responsible for all of its chapter's project management and keeping it on schedule. I've checked off Milestone 0 now that you have a fully-formed team, but I'll leave it to you to check off the rest of the milestones as you go.

The next milestone is coming up on May 15, which is to complete the chapter outline. So everyone please request access to the [chapter planning doc](https://docs.google.com/document/d/1mLG--jMsvP85L02ft5o3_BhbHwy_pDejl-7FH95RH4I/edit?usp=sharing) and also make sure you're in the [`#web-almanac-caching`](https://join.slack.com/t/httparchive/shared_invite/zt-45sgwmnb-eDEatOhqssqNAKxxOSLAaA) channel on Slack to coordinate on progress.

Thanks everyone!

**Comment by valerojasm** [comment]
Hello! I'd love to help as an analyst too if it's still needed :)

**Comment by kevinfarrugia** [comment]
Hi @valerojasm . From my end help is always welcome. Would you like to take over the analysis role and I can pitch in if needed? (I'm contributing to other chapters too)

**Comment by rviscomi** [comment]
There are [several chapters](https://github.com/HTTPArchive/almanac.httparchive.org/issues?q=is%3Aissue+is%3Aopen+label%3A%22help+wanted%3A+analysts%22) in need of analysts so it'd be good to spread the load. Or @kevinfarrugia if you're stretched too thin we can reassign the role to @valerojasm.

**Comment by kevinfarrugia** [comment]
Whatever works best. I'm happy to continue on this chapter.

**Comment by rviscomi** [comment]
@roryhewitt @rrajiv @kevinfarrugia reminder to get access to the [planning doc](https://docs.google.com/document/d/1mLG--jMsvP85L02ft5o3_BhbHwy_pDejl-7FH95RH4I/edit?usp=sharing) and start brainstorming content to include in this year's chapter. What's new with caching, or what would be good to revisit from previous years? We're hoping to have the outline completed by May 15 to stay on schedule. Thanks for your help!

**Comment by roryhewitt** [comment]
@rviscomi @rrajiv @kevinfarrugia 

So I have come down hard with Covid over the last week, and it's left me just completely wiped out. I'm aware that I am significantly behind on doing the draft outline (@paulcalvano has pinged me a couple of times). I'm doing my best to come up with something which isn't just the exact same thing as I authored for the 2020 Caching chapter (although I quite liked that, personally).

@rrajiv  - are you able to give me a hand with this one? It's honestly hard to even put pen to paper and think...

**Comment by rrajiv** [comment]
@roryhewitt sorry to hear that. I will take a look at it this week.

**Comment by rviscomi** [comment]
@roryhewitt @rrajiv @kevinfarrugia hi all, just checking in. Just to confirm, has the lead author role officially transitioned from @roryhewitt to @rrajiv? If so @rrajiv can you update the contributor info at the top of the issue? Also @roryhewitt could you confirm if you're still able to contribute as a reviewer?

@kevinfarrugia I see your note in https://github.com/HTTPArchive/almanac.httparchive.org/pull/2941 that you're still waiting for the outline and will defer to the 2021 queries for now. Is that still the case? If so @rrajiv (or @roryhewitt) can you coordinate with @kevinfarrugia if there are any new metrics you'd like to explore this year?

The analysis phase is scheduled to end next week so I want to make sure the writing is able to start on time if possible.

Hope everyone is well!

**Comment by rrajiv** [comment]
Hi @rviscomi  - wasn't aware the role had switched ;). I had helped out earlier on the doc with some comments to update the outline since @roryhewitt was out

**Comment by kevinfarrugia** [comment]
From my end I am still waiting for the outline and I ran the queries from 2021 and updated the [Google Sheet](https://docs.google.com/spreadsheets/d/16wQoA9ZciYkdW65RfR6CuW9H8TdMTQjhLuTSvVlN_rs/edit#gid=799938635) with the data from June 2022. I see there is a request for two new standards which I can look into if needed.

**Comment by rviscomi** [comment]
Good to know thanks @rrajiv and @kevinfarrugia.

So it seems like the expectation is for @roryhewitt to continue in the lead author role. @roryhewitt are you feeling up for it? If not we may need to find an alternate lead or close the chapter. That'd be good to clarify now before @kevinfarrugia does any additional work on the analysis.

**Comment by rviscomi** [comment]
⛔ Hi everyone. Unfortunately it doesn't seem like this chapter has anyone to take the lead author role, which means we won't be able to publish it this year. I wish @roryhewitt the best and hope his recovery has been going well—one's health should always come before volunteer projects like this and I fully support stepping back to focus on recovery.

I'm going to close this issue so we can refocus our efforts on the remaining chapters. If anyone is interested to step up and lead the remaining effort, leave a comment and we can try to make it work. Given that the results are already available in the [sheet](https://docs.google.com/spreadsheets/d/16wQoA9ZciYkdW65RfR6CuW9H8TdMTQjhLuTSvVlN_rs/edit#gid=799938635), we only need two people at minimum: one to author the chapter, and one to review it. As a reminder, the due date to have the chapter fully written, reviewed, and edited is September 1.
