### ISSUE TITLE
HTTP 2022

### ISSUE THREAD

**Issue by rviscomi** [HTTPArchive/almanac.httparchive.org#2903]
# HTTP 2022

![HTTP illustration](https://raw.githubusercontent.com/HTTPArchive/almanac.httparchive.org/main/src/static/images/2019/http/hero_lg.jpg)

If you're interested in contributing to the HTTP chapter of the 2022 Web Almanac, please reply to this issue and indicate which role or roles best fit your interest and availability: [author](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Authors'-Guide), [reviewer](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Reviewers'-Guide), [analyst](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Analysts'-Guide), and/or [editor](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Editors'-Guide).

## Content team

| Lead | Authors | Reviewers | Analysts | Editors | Coordinator |
| ---- | ------- | --------- | -------- | ------- | ----------- |
| @paivaspol | @paivaspol | @tunetheweb @rmarx @LPardue | @paivaspol | | @paulcalvano |

<details>
<summary><b>Expand for more information about each role 👀</b></summary>

- The **[content team lead](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Content-Team-Leads'-Guide)** is the chapter owner and responsible for setting the scope of the chapter and managing contributors' day-to-day progress.
- **[Authors](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Authors'-Guide)** are subject matter experts and lead the content direction for each chapter. Chapters typically have one or two authors. Authors are responsible for planning the outline of the chapter, analyzing stats and trends, and writing the annual report.
- **[Reviewers](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Reviewers'-Guide)** are also subject matter experts and assist authors with technical reviews during the planning, analyzing, and writing phases.
- **[Analysts](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Analysts'-Guide)** are responsible for researching the stats and trends used throughout the Almanac. Analysts work closely with authors and reviewers during the planning phase to give direction on the types of stats that are possible from the dataset, and during the analyzing/writing phases to ensure that the stats are used correctly.
- **[Editors](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Editors'-Guide)** are technical writers who have a penchant for both technical and non-technical content correctness. Editors have a mastery of the English language and work closely with authors to help wordsmith content and ensure that everything fits together as a cohesive unit.
- The **[section coordinator](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Section-Leads'-Guide)** is the overall owner for all chapters within a section like "User Experience" or "Page Content" and helps to keep each chapter on schedule.

_Note: The time commitment for each role varies by the chapter's scope and complexity as well as the number of contributors._

For an overview of how the roles work together at each phase of the project, see the [Chapter Lifecycle](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Chapter-Lifecycle) doc.
</details>

### [**0. Form the content team**](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Chapter-Lifecycle#0-create-content-team)
+ [x] **May 1**: The content team has at least one author, reviewer, and analyst

### [**1. Plan content**](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Chapter-Lifecycle#1-plan-content)
+ [x] **May 15** The content team has completed the chapter outline in the [draft doc][~google-doc]

### [**2. Gather data**](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Chapter-Lifecycle#2-gather-data)
+ [x] **June 1**: Analysts have added all necessary [custom metrics](https://github.com/HTTPArchive/custom-metrics/blob/main/README.md) and drafted a PR ([example](https://github.com/HTTPArchive/almanac.httparchive.org/pull/1087)) to track query progress
- **June 1 - 15**: HTTP Archive runs the June crawl

### [**3. Validate results**](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Chapter-Lifecycle#3-validate-results)
+ [x] **August 1**: Analysts have queried all metrics and saved the output to the [results sheet][~google-sheets]

### [**4. Draft content**](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Chapter-Lifecycle#4-draft-content)
+ [x] **September 1**: The content team has written, reviewed, and edited the chapter in the [doc][~google-doc]

### [**5. Publication**](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Chapter-Lifecycle#5-publication)
+ [x] **September 15**: The completed chapter and all required [metadata](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Authors'-Guide#metadata-to-add-at-the-top-of-your-chapters) and [figures](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Figures-Guide) are converted to markdown and submitted to [GitHub][~chapter-markdown]
- **September 26**: Target launch date 🚀

## Chapter resources

Refer to these 2022 HTTP resources throughout the content creation process:

[📄 Google Docs][~google-doc] for outlining and drafting content
[🔍 SQL files][~sql-files] for committing the queries used during analysis
[📊 Google Sheets][~google-sheets] for saving the results of queries
[📝 Markdown file][~chapter-markdown] for publishing content and managing public metadata
[💬 #web-almanac-http on Slack][~slack-channel] for team coordination

[~google-doc]: https://docs.google.com/document/d/19MokZOX9llhgG_JxdShJTJy-XC9bFAlGE8bd-_ByRl8/edit?usp=sharing
[~sql-files]: https://github.com/HTTPArchive/almanac.httparchive.org/tree/main/sql/2022/http
[~google-sheets]: https://docs.google.com/spreadsheets/d/1NJrPOjBoJSDsHV0rAHpcZ9qBUgy6RVG3QtvbTqrj5_o/edit?usp=sharing
[~chapter-markdown]: https://github.com/HTTPArchive/almanac.httparchive.org/tree/main/src/content/en/2022/http.md
[~slack-channel]: https://join.slack.com/t/httparchive/shared_invite/zt-45sgwmnb-eDEatOhqssqNAKxxOSLAaA

**Comment by paivaspol** [comment]
I can help being a analyst and/or reviewer for this chapter.

**Comment by tunetheweb** [comment]
Happy to review too and, as last year’s analyst, happy to help this years analyst with any questions or queries.

**Comment by rviscomi** [comment]
Thanks for your interest in contributing to the HTTP chapter this year @paivaspol @tunetheweb @rmarx!

We still don't have an author/lead for this chapter, which puts us behind on Milestone 0 and at risk of having to shut it down. Please consider reaching out to your professional networks to see if anyone else would be interested to contribute.

Meanwhile, it's not too early to start making progress on Milestone 1, which is to complete the chapter outline and is due on May 15. Make sure you have access to the [chapter planning doc](https://docs.google.com/document/d/19MokZOX9llhgG_JxdShJTJy-XC9bFAlGE8bd-_ByRl8/edit?usp=sharing) and also the [`#web-almanac-http`](https://join.slack.com/t/httparchive/shared_invite/zt-45sgwmnb-eDEatOhqssqNAKxxOSLAaA) channel on Slack. Even without an author committed yet, you can still start adding your ideas to the doc for things that should be covered this year.

Thanks everyone!

**Comment by paivaspol** [comment]
Hi @tunetheweb @rmarx! Excited to be working with both of you. This is my first time contributing so I'll have a lot to learn from both of you.

I added a rough outline in the doc--basically short phrases on the high level idea in that topic borrowing some ideas from previous years :) . Please take a look, make changes, and leave any comments. I think once we have our outline relatively set, we can add specifics of the data that we need to support each point. 

@rviscomi I can be an author. You can remove me from a reviewer.

**Comment by rviscomi** [comment]
Great thanks @paivaspol! 🎉

As the lead author, you'll be responsible for keeping this chapter on schedule and meeting the milestones at the top of this issue. You have edit access to that comment, so please keep it updated as you complete your milestones or if the contributors change. You'll also be responsible for coordinating with the rest of the team to make sure everyone is contributing as needed. Let us know if you have any questions/concerns. Thanks again!

**Comment by tunetheweb** [comment]
This is an interesting one we haven't explored in the HTTP Chapter before: https://twitter.com/HTTPArchive/status/1521667976969310208?s=20&t=Ac330HAr5spnTOfup3hC8w

We could look at TTFB for home pages from HTTP Archive crawl, and from origin-level (in CrUX dataset) and see how TTFB for our HTTP connections are impacting web performance?

Or maybe it's one for Performance chapter?

**Comment by paivaspol** [comment]
IMO, it might be more appropriate in the Performance chapter as the HTTP protocol itself isn't the only impacting factor and RTT could be the larger impacting factor. 

Tangentially, a challenge that I can think of is that TTFB from HTTP Archive crawl may not line up with TTFB from CrUX? I've never looked at it myself, but it wouldn't be surprised if they don't line up as one is from a lab setting and the other is RUM.

That said, if we compare the TTFB results from HTTP Archive and CrUX and they don't align, there might be a potential for a small section pointing out the importance of having both synthetic measurements and using RUM. What do you think?

**Comment by paivaspol** [comment]
@rviscomi we currently do not have an editor, while I have some experience writing in the past, I'm sure my writing is far from perfect. :) I'm wondering what would be the process without an editor?

**Comment by tunetheweb** [comment]
WebPageTest (which HTTP Archive uses for the crawl) grabs the CrUX TTFT, originally to display this in the WebPageTest website for that test, but luckily for us it saves that CrUX TTFT in the result ready for us to query.

Agree the crawl TTFB is of limited use as from US data centre and lab-based. The CrUX TTFT (which, as per above, we also get now) is much more useful.

**Comment by rmarx** [comment]
@paivaspol I can act as editor and potentially also co-author for some specific parts if you need/want assistance :)

**Comment by tunetheweb** [comment]
Think you might be better as Reviewer (check technical accurancy and also help suggest and review content) rather than Editor (check for typos, formatting and consistency with rest of Web Almanac) @rmarx ?

**Comment by rmarx** [comment]
Let's call it a Reviewing Editor or Editing Reviewer then and split the difference? :) I will of course also still review the contents (if wanted)

**Comment by paivaspol** [comment]
@rmarx Thank you! You help is very welcomed especially for the HTTP/3 parts of the chapter.

**Comment by rmarx** [comment]
@paivaspol Holy Hell! I've only just now realized you're the first author of the Vroom paper! Big fan of your work :)

**Comment by rviscomi** [comment]
Just wanted to say the outline is looking great, nice work team! 🚀

**Comment by paivaspol** [comment]
Added a section on the metrics needed for the section. 

@rmarx @tunetheweb I left some comments specifically on the metrics. Can you please take a look and leave your thoughts there? I'm relocating towards the end of this month, so I plan to start on the metrics earlier so that we can hit the June 1 deadline for the metrics. Thanks!

**Comment by LPardue** [comment]
I'm happy to lend some reviewing or editing help once the chapter is formed up a bit more.

**Comment by paivaspol** [comment]
@LPardue Thank you for helping! I added you as an editor in the top comment above.

**Comment by tunetheweb** [comment]
Similar to comment above, I'd suggest @LPardue 's expertise on the subject makes him a Reviewer rather than an Editor. Some light editing is expected of reviewers while reviewing obviously, but the Editor role is specifically about enforcing Spelling, grammar and Web Almanac standards to the chapter.

**Comment by paivaspol** [comment]
@rmarx @tunetheweb @LPardue @rviscomi I completed most of the queries except for one on quantifying number of `link rel="preload"` and quantifying the HTTP versions announced via `alt-svc` headers. I'll finish those by this upcoming weekend or latest mid-next week.

For the ones that I completed, I created a section called Takeaways in the chapter doc. The link to the spreadsheet is provided at the beginning of the Takeaway chapter. Can you please take a look and let me know your thoughts? If there's an error to the query, please let me know as well. The queries are in the PR linked above.

Finally, I started putting together some text for the chapter draft. Right now, nothing is worth looking at. I'll keep you posted once I have a more reasonable draft to make a pass on.

**Comment by paivaspol** [comment]
@rmarx @paulcalvano @rviscomi @rmarx I completed the first draft for the chapter. Please take a look and let me know what you think.

**Comment by rmarx** [comment]
I have just completed a full editing/reviewing pass on the first draft. 

Most of this was replacing literal repetitions in the same sentence / subsequent sentences with acronyms or removing them (you have a tendency to repeat yourself a lot apparently, @paivaspol :P). Some minor sentences/parts were edited for correctness/clarity. I've done all this as suggestions to make it easier to track. 

There are still some open comments that need to be addressed for the final version though, especially in the HTTP/3 part, though none seem to be much work.

Thanks for writing the text for this year @paivaspol. It's a nice, to-the-point chapter that discusses the high-level challenges and potential solutions, as well as the necessary data to back it up!

**Comment by LPardue** [comment]
Thanks for the work @paivaspol . I plan to review post comments by ~4 days from now.

**Comment by paivaspol** [comment]
Thanks everyone for the help! There are some comments left that I haven't got a chance to get to. I'll address them this weekend.

**Comment by paivaspol** [comment]
I resolved most of the comments in the text. Can you please take a look?

**Comment by LPardue** [comment]
@paivaspol I just completed my review.

Firstly, a big thank you for penning everything here! It is a good and interesting read.

I've mainly pointed out minor things that are mostly editorial but verge a little on the technical side. I hope that these are straightforward to resolve quickly.

I noted a few other things that might be interesting to dig into. But that is probably me coming too late to the table - so I completely understand if they are closed with no action in order for us to publish the chapter.

**Comment by paivaspol** [comment]
I think the chapter is in a good state. Thanks @rmarx @LPardue and @tunetheweb for all the valuable feedback! 

Currently, there are two comments left in the chapter:
1. On whether we want to see if sites with HTTP/2+ have better CWV metrics. @tunetheweb do you still want to run some queries on that? I'm okay with not having that measurements too.
1. On some queries that is returning weird results for resources served from Google. I also mentioned this in more detail at https://github.com/HTTPArchive/almanac.httparchive.org/pull/3108/files.

@LPardue you mentioned that there might be some external reviewers who are interested. feel free to share the chapter with them and let me know if there are any comments / concerns.

I'll start converting the other sections of the chapter into Markdown. Finally, I'll be offline between 9/9 - 9/12 but will get try to get this done by 9/15.

**Comment by paivaspol** [comment]
Thanks again everyone for the help! I think we are at a good state.

I've converted the chapter into markdown, generated the charts, and populated all the required data / metadata. The PR for the chapter is at #3128.
