### ISSUE TITLE
Join the 2022 Developers team!

### ISSUE THREAD

**Issue by rviscomi** [HTTPArchive/almanac.httparchive.org#2904]
Calling all @HTTPArchive/developers! Let us know if you're interested in collaborating on the 2022 edition.

Browse issues tagged with [`development`](https://github.com/HTTPArchive/almanac.httparchive.org/labels/development)

**Comment by ibnesayeed** [comment]
Count me in please!

**Comment by tunetheweb** [comment]
Woo hoo - good to have you back @ibnesayeed !

**Comment by aashutoshrathi** [comment]
Interested!

**Comment by Hilal1782** [comment]
Count me in too, please!

**Comment by capjamesg** [comment]
I am interested in assisting!
