### ISSUE TITLE
Add 2021 to the search result filters

### ISSUE THREAD

**Issue by rviscomi** [HTTPArchive/almanac.httparchive.org#2907]
For example: https://almanac.httparchive.org/en/search?q=accessibility#gsc.tab=0&gsc.q=accessibility&gsc.page=1

<img width="447" alt="image" src="https://user-images.githubusercontent.com/1120896/163032393-f29678b3-a98f-4db6-a634-7e0b00a956b3.png">

I see filters for 2019 and 2020. Would be good to add one for 2021 content.

**Comment by tunetheweb** [comment]
Ooops - forgot to do this for 2021 launch!

Added now here: https://programmablesearchengine.google.com/cse/search/refinements

Though took a while getting ordering right (I had to basically delete the old labels and re-add them in the order I wanted to get 2021 first).
