### ISSUE TITLE
Broken links [Contributors page]

### ISSUE THREAD

**Issue by AymenLoukil** [HTTPArchive/almanac.httparchive.org#291]
In contributors page, there are these broken links : 

- [x] https://almanac.httparchive.org/en/2019/www.bendell.ca 
- [x] https://almanac.httparchive.org/en/2019/dougsillars.com

**Comment by rviscomi** [comment]
Removed @colinbendell's website from his config. Even if we add https, I still get an ERR_TOO_MANY_REDIRECTS error. Colin, if there's a better URL or if you're able to fix the redirect problem we can add it back in.
