### ISSUE TITLE
SEO Chapter - New robots tag: indexifembedded 

### ISSUE THREAD

**Issue by Tiggerito** [HTTPArchive/almanac.httparchive.org#2911]
The SEO chapter could check the use of the new [indexifembedded meta tag option](https://developers.google.com/search/blog/2022/01/robots-meta-tag-indexifembedded) if possible. The custom metrics code would have to look into iframe content. 

The article also uses 'value' in place of 'content' for the meta tag. I wonder how many people make this mistake on their meta tags? Googlebot supports 'value', but the custom metrics code does not.

**Comment by rviscomi** [comment]
Thanks @Tiggerito. I'm going to copy this into the #2888 issue as a new comment.
