### ISSUE TITLE
2021 media japanese translation: fix "dropped" translation

### ISSUE THREAD

**Issue by pekeq** [HTTPArchive/almanac.httparchive.org#2919]
Hello,
Thank you for your great work to translation.

I found a bit of error in 2021 media japanese translation. (https://github.com/HTTPArchive/almanac.httparchive.org/blob/main/src/content/ja/2021/media.md)

In the current translation, "the `<img>` tag dropped" is translated as "`<img>` タグが削除されました".
This Japanese sentence means that "`<img>` tag was deleted".
Since I think "dropped" in this sentence means "added", this Japanese has the opposite meaning.

I would suggest "`<img>` タグが生まれました" (the `<img>` tag was born) instead of this translation, but you don't have to use it if you have a better one.

Thanks,

**Comment by tunetheweb** [comment]
I agree “dropped” here means “landed” or “arrived”.

@ksakae1216 you OK with this change?

**Comment by ksakae1216** [comment]
@pekeq @tunetheweb Thanks 😄 
I think "`<img>` タグが生まれました".
I will translate.
