### ISSUE TITLE
Create Meta descriptions [All pages]

### ISSUE THREAD

**Issue by AymenLoukil** [HTTPArchive/almanac.httparchive.org#292]
We should create meta descriptions for each page.

(edit - @bazzadp added table below)

- [x]	1. JavaScript
- [x]	2. CSS
- [x]	3. Markup
- [x]	4. Media
- [x]	5. Third Parties
- [x]	6. Fonts
- [x]	7. Performance
- [x]	8. Security
- [x]	9. Accessibility
- [x]	10. SEO
- [x]	11. PWA
- [x]	12. Mobile web
- [x]	13. Ecommerce
- [x]	14. CMS
- [x]	15. Compression
- [x]	16. Caching 
- [ ]	17. CDN
- [x]	18. Page Weight
- [x]	19. Resource Hints
- [x]	20. HTTP/2
- [x] Methodology
- [x] Table of Contents
- [x] Contributors
- [x] Home

**Comment by rviscomi** [comment]
Hmm this is a good reminder that we should have a short description for each chapter.

**Comment by bazzadp** [comment]
> Hmm this is a good reminder that we should have a short description for each chapter.

I think these should go in each Chapter Markdown to allow different languages. Have done that for HTTP/2 chapter as part of #302. Let me know your thoughts on that.

**Comment by rviscomi** [comment]
Yes, good idea!

**Comment by rviscomi** [comment]
@bazzadp we're still missing CDN (landing any moment) but how are the JS and CSS chapters looking? Can we check them off?

**Comment by bazzadp** [comment]
> @bazzadp we're still missing CDN (landing any moment) but how are the JS and CSS chapters looking? Can we check them off?

Will file a PR to add them. Was waiting for the CDN chapter to do them all at once. After that I will list them all here in a table so SEO experts can view and suggest any improvements, but I think they are pretty good:
- < 160 chars except one IIRC
- descriptive

**Comment by bazzadp** [comment]
OK here are the English Meta Descriptions:

**Chapters**

|Page|Length|Description|
|---|---|---|
|accessibility|145|Accessibility chapter of the 2019 Web Almanac covering ease of reading, media, ease of navigation, and compatibility with assistive technologies.|
|caching|154|Caching chapter of the 2019 Web Almanac covering cache-control, expires, TTLs, validitaty, vary, set-cookies, AppCache, Service Workers and opportunities.|
|cdn|*TBC*|*CDN chapter of the 2019 Web Almanac covering ... (TBC).*|
|cms|145|CMS chapter of the 2019 Web Almanac covering CMS adoption, how CMS suites are built, User experience of CMS powered websites, and CMS innovation.|
|compression|152|Compression chapter of the 2019 Web Almanac covering HTTP compression, algorithms, content types, 1st party and 3rd party compression and opportunities.|
|css|173|CSS chapter of the 2019 Web Almanac covering color, units, selectors, layout, typography and fonts, spacing, decoration, animation, media queries, and page level statistics.
|ecommerce|132|Ecommerce chapter of the 2019 Web Almanac covering ecommerce platforms, payloads, images, third parties, performance, seo, and PWAs.|
|fonts|147|Fonts chapter of the 2019 Web Almanac covering where fonts are loaded from, font formats, font loading performance, variable fonts and color fonts.|
|http2|118|HTTP/2 chapter of the 2019 Web Almanac covering adoption and impact of HTTP/2, HTTP/2 Push, HTTP/2 Issues, and HTTP/3.|
|javascript|155|JavaScript chapter of the 2019 Web Almanac covering how much JavaScript we use on the web, compression, libraries and frameworks, loading, and source maps.|
|markup|118|Markup chapter of the 2019 Web Almanac covering elements used, custom elements, value, products, and common use cases.|
|media|148|Media chapter of the 2019 Web Almanac covering image file sizes and formats, responsive images, client hints, lazy loading, accessibility and video.|
|mobile-web|153|Mobile Web chapter of the 2019 Web Almanac covering page loading, textual content, zooming and scaling, buttons and links, and ease of filling out forms.|
|page-weight|159|Page Weight chapter of the 2019 Web Almanac covering why page weight matters, bandwidth, complex pages, page weight over time, page requests, and file formats.|
|performance|138|Performance chapter of the 2019 Web Almanac covering First Contentful Paint (FCP), Time to First Byte (TTFB), and First Input Delay (FID).|
|pwa|157|PWA chapter of the 2019 Web Almanac covering service workers (registations, installability, events and filesizes), Web App Manifests properties, and Workbox.|
|resource-hints|163|Resource Hints chapter of the 2019 Web Almanac covering usage of dns-prefetch, preconnect, preload, and prefetch as well as priority hints and native lazy loading.|
|security|151|Security chapter of the 2019 Web Almanac covering Transport Layer Security (TLS(), mixed content, security headers, cookies, and Subresource Integrity.|
|seo|157|SEO chapter of the 2019 Web Almanac covering content, meta tags, indexability, linking, speed, structured data, internationalization, SPAs, AMP and security.|
|third-parties|156|Third Parties chapter of the 2019 Web Almanac covering data of what third parties are used, what they are used for, performance impacts and privacy impacts.|
|---|---|---|
|default chapter|~79|`Title` chapter of the 2019 Web Almanac probing into the use of `Title` on the web.|
|contributors.html|167|The `contributors count` people who contributed to the 2019 Web Almanac from HTTP Archive as Analysts, Authors, Brainstormers, Designers, Developers, Editors, Reviewers and Translators.|
|index.html|162|The 2019 Web Almanac by HTTP Archive is an annual state of the web combining the raw stats and trends of the HTTP Archive with the expertise of the web community.|
|methodology.html|127|Describes how the 2019 Web Almanac from HTTP Archive was put together: The Datasets and Tools used and how the project was run.|
|table_of_contents.html|157|Table of Contents for the 2019 Web Almanac from HTTP Archive, listing each section: Page Contents, User Experience, Content Publishing, Content Distribution.|

@AymenLoukil and @rachellcostello if you can review these that would be great.
