### ISSUE TITLE
Create a robots.txt file 

### ISSUE THREAD

**Issue by AymenLoukil** [HTTPArchive/almanac.httparchive.org#293]
We should create a [robots.txt file ](https://support.google.com/webmasters/answer/6062596?hl=en)

**Comment by rviscomi** [comment]
Can we add sitemap.xml to this issue or should that be done separately?

**Comment by rviscomi** [comment]
As far as what should go in the robots file, I don't think we want to disallow anyone from anywhere. So is it simply going to contain the following?

```
User-agent: *
Allow: /
```

**Comment by AymenLoukil** [comment]
> Can we add sitemap.xml to this issue or should that be done separately?

I think it should be done separately. When the sitemap will be ok we will modify the robots.txt to add its reference.

**Comment by AymenLoukil** [comment]
> As far as what should go in the robots file, I don't think we want to disallow anyone from anywhere. So is it simply going to contain the following?
> 
> ```
> User-agent: *
> Allow: /
> ```

Yeah. For the moment we allow everything. Later we could adjust.
