### ISSUE TITLE
Add link rel canonical tags [All pages]

### ISSUE THREAD

**Issue by AymenLoukil** [HTTPArchive/almanac.httparchive.org#294]
We could add link rel canonical tag for each page.

**Comment by rviscomi** [comment]
Each page includes `rel=alternate` for its own URL. Is that ok or should we change it to canonical? Should we have both? For example, on the home page:

```html
<link rel="alternate" href="/en/2019/" hreflang="en">
```

Also does it matter if the URL is relative or should it be absolute?

**Comment by bazzadp** [comment]
According to this https://webmasters.stackexchange.com/questions/61534/should-i-include-the-current-language-code-in-link-rel-alternate-hreflang we should include it for current language and also include  and this: https://yoast.com/hreflang-ultimate-guide/#hreflang-canonical we should have both and think it's fine for them to be relative (https://stackoverflow.com/questions/28291574/are-relative-links-valid-in-link-rel-alternate-hreflang-tags).
