### ISSUE TITLE
Featured Chapter blockquote

### ISSUE THREAD

**Issue by catalinred** [HTTPArchive/almanac.httparchive.org#296]
Fix the index "Featured Chapter" blockquote as right now it uses an image called `quote.png` with a dimension of 8192x7973 px :/

Proposed solution: replace quote.png with a text CSS pseudo element and get rid of that HTTP request completely.

**Comment by rviscomi** [comment]
8192x7973 px?! 😱

**Comment by catalinred** [comment]
> 8192x7973 px?! 😱

I know, Halloween thing :)
