### ISSUE TITLE
Show publication and last modified dates in chapters

### ISSUE THREAD

**Issue by rviscomi** [HTTPArchive/almanac.httparchive.org#3001]
Even though it should be clear which year a given chapter corresponds to, I think it could still be helpful to display the exact publication date and optionally the last modified date at the top of the content area, near the contributor names.

I'd be curious to hear if anyone disagrees or if there's a better place to show this info.

**Comment by tunetheweb** [comment]
See mock up discussed here: https://github.com/HTTPArchive/almanac.httparchive.org/issues/518#issuecomment-555663257

We have all the data to easily make this happen. Just need to decide on design.

@HTTPArchive/designers any thoughts here?

**Comment by shantsis** [comment]
Mockup looks good, and great idea!
