### ISSUE TITLE
Fix alignment of mobile menu icons

### ISSUE THREAD

**Issue by rviscomi** [HTTPArchive/almanac.httparchive.org#301]
The HTTP Archive and social links should be on the same line. They're appearing on different lines:

![image](https://user-images.githubusercontent.com/1120896/68049637-6c6cee80-fcb1-11e9-89cc-d9973f4fe225.png)

Original design for reference:

![image](https://user-images.githubusercontent.com/1120896/68049592-4f382000-fcb1-11e9-845b-0e8acdb37ae2.png)

**Comment by catalinred** [comment]
On it, I will fix it on #297 if that's ok.
