### ISSUE TITLE
HTML validation - divs in H1 in chapters

### ISSUE THREAD

**Issue by bazzadp** [HTTPArchive/almanac.httparchive.org#309]
The Chapters have the following:

```
      <h1 class="title">
        <div class="subtitle">Part IV Chapter 20</div>
        HTTP/2
      </h1>
```

Is it valid to have a div as part of a H1? The W3 validator (https://validator.w3.org/nu/) doesn't think so:

> **Error:** Element div not allowed as child of element h1 in this context. (Suppressing further errors from this subtree.)

Could also cause SEO/Accessibility issues.

Tried to move the `<h1>` tags around just the title itself in the template but that changed the style so thought best to leave to someone more familiar with the CSS to change this hence opening this issue.

**Comment by rviscomi** [comment]
Thanks @bazzadp. I wrote this. Probably best to take the subtitle out of the H1 and restyle. I can take this if I get time, otherwise anyone from @HTTPArchive/developers can feel free to self-assign.
