### ISSUE TITLE
HTML validation - duplicate ids when tables with same column names are used

### ISSUE THREAD

**Issue by bazzadp** [HTTPArchive/almanac.httparchive.org#310]
Looking at the [HTTP/2 chapter](https://github.com/HTTPArchive/almanac.httparchive.org/blob/master/src/templates/en/2019/chapters/http2.html) for example, it has generated multiple instances of the following (as I used pretty much the same headings in all my tables):

```
      <table>
        <thead>
          <tr>
            <th id="protocol">Protocol</th>
            <th id="desktop">Desktop</th>
            <th id="mobile">Mobile</th>
            <th id="both">Both</th>
          </tr>
        </thead>
```

HTML states that there should only be one `id` of each name. Additionally using the column name like this could break the ToC chapter links if a h1-h6 heading has the same name as a table column heading.

Can we prefix these ids with the table name? Or just not use ids for column headings at all? Not familiar enough with the library we are using to convert the markdown to know how to fix this myself hence opening this issue.

**Comment by rviscomi** [comment]
Good catch. I don't think we ever need `th` to have an ID, so this can be removed if possible.
