### ISSUE TITLE
Edit 2022 Chapters

### ISSUE THREAD

**Issue by tunetheweb** [HTTPArchive/almanac.httparchive.org#3123]
📢  Attention Editors: this issue will be used to track progress on the 2022 chapters that are ready for editing.

When you're ready to edit a chapter, edit this comment to put your name next to an unchecked chapter listed below that you would be interested in editing. Chapters will be added to the queue as they become ready for editing.

Refer to the [Editors' Guide](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Editors'-Guide) for general best practices.

Staged URL (from `main` branch which may, or may not include below chapters):
https://20220920t102908-dot-webalmanac.uk.r.appspot.com/en/2022/

- [x] Mobile Web - @rviscomi 
- [x] Fonts - @shantsis 
- [x] Security - @tunetheweb 
- [x] Third Parties - @shantsis 
- [x] [CSS](../pull/3140) - @rviscomi 
- [x] Sustainability - @tunetheweb
- [x] CMS - @dknauss
- [x] HTTP - @tunetheweb 
- [x] Accessibility - @dereknahman & @tunetheweb 
- [x] SEO - @MichaelLewittes and @tunetheweb 
- [x] WASM - @tunetheweb 
- [x] Capabilities - @tunetheweb 
- [x] Privacy - @DesignrKnight 
- [x] JavaScript - @DesignrKnight and @rviscomi 
- [x] Markup - @tunetheweb 
- [x] Page Weight - @tunetheweb
- [x] PWA - @ siwinlo and @tunetheweb 
- [x] Interoperability - @tunetheweb 
- [x] Media - @MichaelLewittes and @tunetheweb 

Not finished writing yet:
- [x] Structured Data
- [x] Performance
- [x] Jamstack (mostly done so might be worth starting edit on this one)

**Comment by shantsis** [comment]
I don't see pull requests for fonts or third parties - should we edit in the google doc for now?

**Comment by tunetheweb** [comment]
Yes. But make sure in Suggest mode and not Edit more so Authors can accept (or argue back!). Much easier to do in Docs before Markdown. Can then do a technical edit of the PR rather than a full content + technical edit.

We used to do as separate PR after markdown PR was merged but authors really didn’t like that.

**Comment by foxdavidj** [comment]
@tunetheweb Privacy chapter is ready for editing

**Comment by rviscomi** [comment]
Thanks @DesignrKnight feel free to take it

**Comment by tunetheweb** [comment]
@shantsis / @DesignrKnight are either of you free to look at WASM or Page Weight?

**Comment by shantsis** [comment]
I won’t be able to take it on in time for the launch, sorry!

**Comment by DesignrKnight** [comment]
> @shantsis / @DesignrKnight are either of you free to look at WASM or Page Weight?

I'll be able to finish privacy chapter by tomorrow (Sunday). I can take a look at WASM next and finish it within couple of days.

Does that work?

**Comment by tunetheweb** [comment]
I edited WASM myself. Was quite small and I'd already given it a pass previous that I'd forgotten about!

**Comment by DesignrKnight** [comment]
> I edited WASM myself. Was quite small and I'd already given it a pass previous that I'd forgotten about!

Aah, nice. I'll inform here when I'm done with Privacy Chapter. I'm almost done with editing Privacy Chapter. If there's a pending chapter then, I'll pick it up.

**Comment by DesignrKnight** [comment]
Have finished my part of the editing review on the Privacy Chapter. Can take up another chapter next if unassigned.

**Comment by tunetheweb** [comment]
Jamstack best next if you have time ([doc](https://docs.google.com/document/d/15RLaaTVqoqb5AuDrlBt6L0J_BMx1ltKW4t8VWX-sN_g/edit#heading=h.8z91yaf1dmft)) as other still going through substantial rewrites. Jamstack isn't quite done, but pretty close to ready for an edit IMHO.

**Comment by DesignrKnight** [comment]
Okay, requested access. I will take it up next

**Comment by DesignrKnight** [comment]
I have taken a first-pass of editing review of the Jamstack chapter. If there are additional chapters I can volunteer for, I can do it over the week to assist in finishing up before the next release
