### ISSUE TITLE
Should we keep the featured chapter section?

### ISSUE THREAD

**Issue by rviscomi** [HTTPArchive/almanac.httparchive.org#3146]
Do we have existing analytics on featured chapter usage? We don't annotate navigations that come from that section, so I'm not sure. We could add it and measure usage on the upcoming 2022 release.

It's not that much effort to define featured content in the markdown, but if the gains are also very low then I wonder if we can simplify things by removing it.

**Comment by tunetheweb** [comment]
Personally I like it.

It breaks up the home page a bit. Without that, we'd need a redesign as home page to break up the top section where the diagonal banner breaks into the grey methodology section.

It's also useful to have a set of stats for each chapter, whether for AMP Stories we've done in the past, Tweets, or we talked last year about a Tweet bot using them (though never got round to implementing).

**Comment by tunetheweb** [comment]
@HTTPArchive/designers any thoughts?

**Comment by shantsis** [comment]
I actually quite like it on the homepage, it's a cool sneak peak into what the almanac contains. It also cycles through over time right?

**Comment by tunetheweb** [comment]
Yeah it changes randomly on each page reload. However as we have a 15 minute caching time and it changes server side, it means it actually only changes every 15 mins as should get a CDN cache hit between those times.
