### ISSUE TITLE
Next/Prev chapter broken styles

### ISSUE THREAD

**Issue by rviscomi** [HTTPArchive/almanac.httparchive.org#315]
When there are no previous chapters, the next/prev widget at the bottom of the chapter page appears to lose its vertical centering and spacing:

![image](https://user-images.githubusercontent.com/1120896/68149196-4d10d400-fef2-11e9-8d5b-8c9e96d9e326.png)

It should look consistent with this:

![image](https://user-images.githubusercontent.com/1120896/68149240-63b72b00-fef2-11e9-9a49-af7e45fed0ef.png)

@tyohan can you take a look at this or unassign yourself if not?

**Comment by rviscomi** [comment]
No word from @tyohan, unassigning.

Any @HTTPArchive/developers available to take this?

**Comment by catalinred** [comment]
> No word from @tyohan, unassigning.
> 
> Any @HTTPArchive/developers available to take this?

I can do it.

**Comment by rviscomi** [comment]
Thanks @catalinred!
