### ISSUE TITLE
Set up .devcontainer for codespaces

### ISSUE THREAD

**Issue by rviscomi** [HTTPArchive/almanac.httparchive.org#3150]
https://docs.github.com/en/codespaces/setting-up-your-project-for-codespaces/introduction-to-dev-containers

I'm primarily using codespaces now for Web Almanac development. To help standardize the container used for cloud development and encourage more contributions, let's create this config file to make it even easier to get up and running.

**Comment by DesignrKnight** [comment]
If this is not urgent, I'll be happy to volunteer for this after the editing work for 2022 Edition is over.

**Comment by tunetheweb** [comment]
Closed with #3424
