### ISSUE TITLE
Finish writing the Fonts chapter

### ISSUE THREAD

**Issue by rviscomi** [HTTPArchive/almanac.httparchive.org#316]
This chapter has some remaining work to do to get it over the finish line:

- write introduction and conclusion sections to give the chapter a narrative arc
- organize analysis sections to be grouped by related topics and give the chapter more of an arc
- expand on each section to give more background info for readers who may be unfamiliar with the technologies being analyzed

I'd love to see this written this week so we have a shot at including it in the launch one week from today. If it's not possible to get this included in the launch, we can release it when ready.

**Comment by rviscomi** [comment]
@zachleat do you have any time to work on this chapter in the next day or two? If not I'm afraid there's no chance we'll have it ready for the launch on Monday 😞

**Comment by zachleat** [comment]
Hey @rviscomi taking a pass at this now. Can you elaborate about bullet 3? Would some kind of glossary be helpful there?

**Comment by zachleat** [comment]
My other question as I craft more of a narrative from this—what’s the best way to reference individual queries or results here?

**Comment by rviscomi** [comment]
Thanks @zachleat! I was thinking of having a few sentences of primer about what the thing is, why it matters, etc. Assume a beginner level of understanding from readers. For example, in the [SEO](https://github.com/HTTPArchive/almanac.httparchive.org/blob/master/src/content/en/2019/seo.md#page-titles) chapter, here's a quote from when it discusses the metric on page titles:

> ### Page titles
> Page titles are an important way of communicating the purpose of a page to a user or search engine. <title> tags are also used as headings in the SERPS and as the title for the browser tab when visiting a page, so it's no surprise to see that 97.1% of mobile pages have a document title.
>
>Even though Google usually displays the first 50-60 characters of a page title within a SERP, the median length of the <title> tag was only 21 characters for mobile pages and 20 characters for desktop pages. Even the 75th percentile is still below the cutoff length. This suggests that some SEOs and content writers aren't making the most of the space allocated to them by search engines for describing their home pages in the SERPs.
>
> (graph histogram length <title> Source: 10.07b, column C, desktop & mobile)

That also answers your other question about referencing the results. Just leave a placeholder in the chapter with the data you'd like to include. We'll generate the chart for you and embed it in the page before publishing. Or if you're comfortable making charts in Sheets I'll make sure you have edit access to the results sheet and you can create your own charts, which we'll tweak later to fit the Almanac style guide.

**Comment by zachleat** [comment]
Still chugging away on this, unfortunately. Hoping to have a PR ready by tomorrow morning

**Comment by zachleat** [comment]
Hey @rviscomi I pushed changes to the `fonts-316` branch.

There is still one outstanding TODO in there, specifically around the question posed here: https://github.com/HTTPArchive/almanac.httparchive.org/pull/192#discussion_r343967930

After I get that resolved I can put up a PR

**Comment by zachleat** [comment]
Hmm, well I ended up deleting that section because something seemed really off about that data? The distributions seemed to suggest that pages were more likely to have a higher font request count than a @font-face block count. Given that _most_ font requests depend on a @font-face block and low CSS Font Loading API usage data this was kinda smelly to me.

Maybe I’m not thinking about it right?

Anyway with this removal, I think we’re good to go if someone else wants to do a quick review pass at the PR here: https://github.com/HTTPArchive/almanac.httparchive.org/pull/370

**Comment by rviscomi** [comment]
Totally fine to trim it. Thanks for keeping this moving, I'm happy to see it nearing the finish line!
