### ISSUE TITLE
(nit) Issue with the 2022 seo chapter

### ISSUE THREAD

**Issue by softplus** [HTTPArchive/almanac.httparchive.org#3189]
"[Figure 10.31.](https://almanac.httparchive.org/en/2022/seo#fig-31) Rw versus rendered canonical." -> "[Figure 10.31.](https://almanac.httparchive.org/en/2022/seo#fig-31) Raw versus rendered canonical."

**Comment by rviscomi** [comment]
Thanks for flagging that!
