### ISSUE TITLE
Broken query link in 2022 JS fig 2.7

### ISSUE THREAD

**Issue by rviscomi** [HTTPArchive/almanac.httparchive.org#3215]
[This figure's](https://almanac.httparchive.org/en/2022/javascript#fig-7) query links to https://github.com/HTTPArchive/almanac.httparchive.org/tree/main/sql/2022/javascript/breakdown_of_pages_using_async_defer_module_nomodule.sql. However, this is a 404 page.

The correct URL is https://github.com/HTTPArchive/almanac.httparchive.org/blob/main/sql/2022/javascript/breakdown_of_scripts_using_async_defer_module_nomodule.sql, with the only difference being `tree` vs `blob` in the path name.

Need to understand how this happens, as other figures correctly link to the `blob` version of queries.

**Comment by tunetheweb** [comment]
Nope. The other difference is **pages** versus **scripts**.

**Comment by rviscomi** [comment]
Ah good catch, the correct URL should be https://github.com/HTTPArchive/almanac.httparchive.org/blob/main/sql/2022/javascript/breakdown_of_pages_using_async_defer.sql (no module info in the URL)
