### ISSUE TITLE
Jamstack chapter: Netlify’s conflict of interest should be clearer

### ISSUE THREAD

**Issue by dieulot** [HTTPArchive/almanac.httparchive.org#3227]
https://almanac.httparchive.org/en/2022/jamstack

> Disclosure: the two authors of this report were Netlify employees. This report and the underlying analysis were reviewed and approved by others not affiliated with Netlify.

It’s unclear from this that “Jamstack” as a buzzword was invented at Netlify.

> All three of the above definitions come from Jamstack.org: in 2020, 2021, and 2022 respectively. It’s hard to think of a more authoritative source for the definition of Jamstack.

That Jamstack.org is owned by Netlify should also be made crystal clear given that paragraph, I believe.

Something to the effect of `Netlify invented the term Jamstack and owns Jamstack.org.` between the two existing disclosure sentences would work well I think.

I don’t know if there are any other masqueraded marketing text in the chapter as I haven’t read much farther (it’s not my cup of tea). 😅

**Comment by rviscomi** [comment]
Hi @dieulot thanks for flagging this concern. My feeling is that it'd be overkill to repeat the disclosure from the intro in specific places throughout the chapter. However, I'd be supportive of expanding it to clarify Netlify's connection to Jamstack, which I agree seems to be more implied than explicitly stated.

@seldo @whitep4nth3r WDYT?

**Comment by seldo** [comment]
I'm happy to include whatever disclaimer you feel warranted! This was why we got volunteers from non-Netlify folks originally but in the event they ended up not having time to participate.

**Comment by dieulot** [comment]
> My feeling is that it'd be overkill to repeat the disclosure from the intro in specific places throughout the chapter. 

Same, I was proposing updating the disclosure.
