### ISSUE TITLE
Update Lighthouse methodology to include desktop testing

### ISSUE THREAD

**Issue by rviscomi** [HTTPArchive/almanac.httparchive.org#3240]
This line from the [Lighthouse](https://almanac.httparchive.org/en/2022/methodology#lighthouse) section of the Methodology page is no longer applicable:

> HTTP Archive runs the latest version of Lighthouse for all of its mobile web pages — desktop pages are not included because of limited resources.

We should update this text to reflect that desktop tests were included in the June dataset and add the desktop configuration.

@pmeenan could you confirm the desktop config? For reference, here's what we show for the mobile config:

Config | Value
-- | --
CPU slowdown | 1x/4x
Download throughput | 1.6 Mbps
Upload throughput | 0.768 Mbps
RTT | 150 ms

**Comment by pmeenan** [comment]
All lighthouse tests use the same "3G Fast" connectivity profile since the Lighthouse scores are calibrated against times from that speed.  Desktop uses the same speed as Mobile for Lighthouse.

CPU throttling is not applied for desktop though so there is no CPU slowdown.
