### ISSUE TITLE
Center align featured stats

### ISSUE THREAD

**Issue by rviscomi** [HTTPArchive/almanac.httparchive.org#3243]
While the area covering all three featured stats may be centered, it feels off because the middle stat itself is not center-aligned.

![image](https://user-images.githubusercontent.com/1120896/197404825-7e5f143f-c658-4114-ab41-bd77a8741494.png)

**Comment by tunetheweb** [comment]
It's cause we use flexbox for the featured status, and flexbox is... [flexible!](https://css-tricks.com/equal-columns-with-flexbox-its-more-complicated-than-you-might-think/):

https://github.com/HTTPArchive/almanac.httparchive.org/blob/b64e7ac98e9046626f1f0dcf7bd9a82f0965c002/src/static/css/index.css#L164-L169

You could change it to grid to be even columns by changing that first line of CSS to:

```css
.featured-chapter-content-data {
    display: grid;
    grid-template-columns: 1fr 1fr 1fr;
```

**Comment by tunetheweb** [comment]
Oh you'll need to change that back to flex on mobile.

Or change it to be one column only on mobile:

```css
    grid-template-columns: 1fr;
```
