### ISSUE TITLE
Feedback about dynamic `import()` in JS chapter

### ISSUE THREAD

**Issue by rviscomi** [HTTPArchive/almanac.httparchive.org#3248]
From the 2022 [JS chapter](https://almanac.httparchive.org/en/2022/javascript#dynamic-import):

> A staggeringly low 0.34% of all observed mobile pages currently use dynamic import(), while 0.41% of desktop pages use it. This is a missed opportunity to ship less code during startup. Perhaps dynamic import() is not seeing much use because it shifts the loading of JavaScript on-demand for features, rather than upfront.

I got feedback that this section might be overlooking other ways of doing code splitting. Assigning to @malchata to think if we can better phrase this.

**Comment by rviscomi** [comment]
> My understanding is most bundlers transpile dynamic import() into something that works in ES5 browsers, so while 0.34% is probably accurate in terms of actual feature use. I don't think it follows that most sites aren't using code splitting.

**Comment by malchata** [comment]
Ah, gotcha. I can work on an amendment to this.
