### ISSUE TITLE
Randomize order of contributors

### ISSUE THREAD

**Issue by rviscomi** [HTTPArchive/almanac.httparchive.org#346]
Low priority but I'd like to see the Contributors page sorted randomly as opposed to alphabetically. Gives everyone a chance to be featured at the top :)

cc @HTTPArchive/developers

**Comment by c-torres** [comment]
Can this be closed? Not sure what's the workflow.

**Comment by bazzadp** [comment]
I think yes. Next time if you say. "Closes #346" or "Fixes #346" as the first line in your PR it will be closed automatically.
