### ISSUE TITLE
Preference for Twitter Card size?

### ISSUE THREAD

**Issue by bazzadp** [HTTPArchive/almanac.httparchive.org#348]
Twitter allows two types of Twitter cards which display if you have certain meta data on the page you are linking too.

A _Summary Card_ which renders like this:

![Twitter Summary Card example](https://user-images.githubusercontent.com/10931297/68334625-ed255380-00d2-11ea-805f-63f8cdd19307.png)

Or a _Summary Card with Large Image_ which renders like this:

![Twitter Summary Card with Large Image example](https://user-images.githubusercontent.com/10931297/68336033-7473c680-00d5-11ea-8ed7-b41d4660d8eb.png)

Both show the Image (cut off in the first one) and a bit of the Description.

As part of #302 I added Twitter Summary Cards (the first smaller one):

```
<meta name="twitter:card" content="summary" />
<meta name="twitter:site" content="@HTTPArchive" />
<meta name="twitter:title" content="{{ self.title() }}" />
<meta name="twitter:image" content="https://almanac.httparchive.org/static/images/2019/{{ get_chapter_image_dir(metadata) }}/hero_sm.jpg" />
<meta name="twitter:description" content="{{ self.description() }}" />
```

I'm now thinking of changing this to the larger one, which would be a simple change to one line in a few places:

```
<meta name="twitter:card" content="summary_large_image" />
```

The same image meets the criteria for the larger card anyway and this would prevent the images being cut off (as they are with the smaller Twitter Card).

Before I did this, I thought I'd throw this out there for any opinions as to which is best. Are the big ones a bit annoyingly big and obnoxious? Or will they have a bigger impact and make better use of our pretty images?

Any thoughts @rviscomi , @AymenLoukil , @rachellcostello or anyone else?

**Comment by rviscomi** [comment]
Bigger is better IMO!

**Comment by obto** [comment]
I agree. Looks much nicer.

**Comment by bazzadp** [comment]
100% right call guys - they look brilliant and wouldn’t have been half as good with the smaller ones I originally implemented!!
