### ISSUE TITLE
Add native lazy loading for chapter images (inc iframes)

### ISSUE THREAD

**Issue by bazzadp** [HTTPArchive/almanac.httparchive.org#351]
Some of the chapters might have a lot of graphics. If possible we should add [native lazy loading](https://web.dev/native-lazy-loading/) for the chapter graphics (except for the chapter heading and the logo).

I'm not sure that is possible as we are writing in markdown and using [showdown](https://github.com/showdownjs/showdown/wiki) to convert to HTML and it doesn't look to have an option to add attributes to image tags.

Could do a bulk edit for image tags in body section at end of chapter generation but that sounds kind of hacky...

Easiest option might be to change all images in chapter markdown to native HTML instead of markdown? Once-off pain for long term gain?

Thoughts @rviscomi , @mikegeyser ?

**Comment by rviscomi** [comment]
Yeah I think this would be a nice improvement. Best approach IMO would be to implement this in the markup generator, since we want to encourage authors to write simple markdown like `![foo](./img.png)`.

**Comment by mikegeyser** [comment]
I think the simplest would be to implement it the same way as the `generate_figure_ids` with a nifty regex replace and add in the `loading="lazy"` attribute. I can have a go at it a little later.
