### ISSUE TITLE
Horizontal sliding bar

### ISSUE THREAD

**Issue by AymenLoukil** [HTTPArchive/almanac.httparchive.org#352]
In chapter template, in the bottom and at the next / previous chapter narrows there is an horizontal sliding bar 
![image](https://user-images.githubusercontent.com/5750656/68345553-e823cc80-00f1-11ea-9e84-1014daf8dfd3.png)

**Comment by bazzadp** [comment]
I can't repeat this.

Think they'll need to know:
- what browser, versions and OS?
- what site (http://127.0.0.1:8080/en/2019/mobile-web or https://almanac.httparchive.org/en/2019/mobile-web)?
- if local dev site, then what branch (master?) and is the branch up to date?
- what dimensions do you see the scrollbar? Always? Or just at certain widths.

**Comment by mikegeyser** [comment]
I'm also seeing it. Chrome 78 on a 2018 macbook pro. Will try and look at it now.

![image](https://user-images.githubusercontent.com/105242/68363507-ba5f7780-0133-11ea-8147-6cc5fee7d57d.png)

**Comment by mikegeyser** [comment]
It seems to be `overflow: auto;` set on the `#chapter-navigation` style. Removing it fixes the issue for me, but I'm not sure if it was put there for a reason? Is that an acceptable fix?

**Comment by rviscomi** [comment]
Caused by #341

cc @catalinred

**Comment by catalinred** [comment]
> It seems to be `overflow: auto;` set on the `#chapter-navigation` style. Removing it fixes the issue for me, but I'm not sure if it was put there for a reason? Is that an acceptable fix?

Would recommend `overflow: hidden` then, to fix #315. I wrote a [comment here](https://github.com/HTTPArchive/almanac.httparchive.org/pull/356#issuecomment-550960325). Hope that helps.
