### ISSUE TITLE
Data tables should be shrink-wrapped and centered

### ISSUE THREAD

**Issue by rviscomi** [HTTPArchive/almanac.httparchive.org#353]
Current appearance:
![image](https://user-images.githubusercontent.com/1120896/68356365-fb6d7280-00c6-11ea-84aa-9fd29098b11d.png)

Expected appearance:
![image](https://user-images.githubusercontent.com/1120896/68356440-37a0d300-00c7-11ea-89e6-a797790e53d1.png)

@ymschaap can you take a look?

**Comment by ymschaap** [comment]
Apologies for the commit to master, did a revert commit as well. 

See #362
