### ISSUE TITLE
Image requests for social media sharing

### ISSUE THREAD

**Issue by bazzadp** [HTTPArchive/almanac.httparchive.org#358]
Currently we are using the same image for 4 pages (index, ToC, Contributors and Methodology) for our social media sharing and it would be good to have different ones.

Can we get the following:

- A white background version of [methodology-characters.png](https://almanac.httparchive.org/static/images/methodology-characters.png).

- A white background version of [home-hero-2019.png](https://raw.githubusercontent.com/HTTPArchive/almanac.httparchive.org/master/src/static/images/home-hero-2019.png)

Or other suggested images using our charaters are more than welcome. Images must be ([at least 696 pixels wide](https://developers.google.com/search/docs/data-types/article#non-amp-sd)) and the current images are in the [src/static/images](https://github.com/HTTPArchive/almanac.httparchive.org/tree/master/src/static/images) directory and the [chapters](https://github.com/HTTPArchive/almanac.httparchive.org/tree/master/src/static/images/2019) subdirectory of that.

This will allow us to correct some issues identified as part of https://github.com/HTTPArchive/almanac.httparchive.org/pull/349#discussion_r343417564

Thanks,
Barry

**Comment by rviscomi** [comment]
methodology-banner is 1200px wide?

**Comment by bazzadp** [comment]
Ah Chrome was putting height and width attributes on it! Will update to use that then and don't need this then?
