### ISSUE TITLE
Structured Data 2024

### ISSUE THREAD

**Issue by nrllh** [HTTPArchive/almanac.httparchive.org#3594]
# Structured Data 2024

![Structured Data illustration](https://raw.githubusercontent.com/HTTPArchive/almanac.httparchive.org/main/src/static/images/2021/structured-data/hero_lg.jpg)

If you're interested in contributing to the Structured Data chapter of the 2024 Web Almanac, please reply to this issue and indicate which role or roles best fit your interest and availability: [author](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Authors'-Guide), [reviewer](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Reviewers'-Guide), [analyst](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Analysts'-Guide), and/or [editor](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Editors'-Guide). You might be interested in exploring the changes to this year's version [here](https://github.com/HTTPArchive/almanac.httparchive.org/discussions/3619).

## Content team

| Lead | Authors | Reviewers | Analysts | Editors | Coordinator |
| ---- | ------- | --------- | -------- | ------- |    -------  |
|  @cyberandy | @cyberandy  | @jvandriel, @rrlevering   | @nrllh  | @capjamesg  | -  | 

<details>
<summary><b>Expand for more information about each role 👀</b></summary>

- The **[content team lead](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Content-Team-Leads'-Guide)** is the chapter owner and responsible for setting the scope of the chapter and managing contributors' day-to-day progress.
- **[Authors](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Authors'-Guide)** are subject matter experts and lead the content direction for each chapter. Chapters typically have one or two authors. Authors are responsible for planning the outline of the chapter, analyzing stats and trends, and writing the annual report.
- **[Reviewers](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Reviewers'-Guide)** are also subject matter experts and assist authors with technical reviews during the planning, analyzing, and writing phases.
- **[Analysts](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Analysts'-Guide)** are responsible for researching the stats and trends used throughout the Almanac. Analysts work closely with authors and reviewers during the planning phase to give direction on the types of stats that are possible from the dataset, and during the analyzing/writing phases to ensure that the stats are used correctly.
- **[Editors](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Editors'-Guide)** are technical writers who have a penchant for both technical and non-technical content correctness. Editors have a mastery of the English language and work closely with authors to help wordsmith content and ensure that everything fits together as a cohesive unit.
- The **[section coordinator](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Section-Leads'-Guide)** is the overall owner for all chapters within a section like "User Experience" or "Page Content" and helps to keep each chapter on schedule.

_Note: The time commitment for each role varies by the chapter's scope and complexity as well as the number of contributors._

For an overview of how the roles work together at each phase of the project, see the [Chapter Lifecycle](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Chapter-Lifecycle) doc.
</details>

### [0. Form the content team](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Chapter-Lifecycle#0-create-content-team)
- [x] 📆 `April 15` Complete program and content committee - 🔑 *Organizing committee*
  - The content team has at least one author, reviewer, and analyst.

### [1. Plan content](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Chapter-Lifecycle#1-plan-content)
- [x] 📆 `May 1` **First meeting to outline the chapter contents** - 🔑 *Content team*
  - The content team has completed the chapter outline.

### [2. Gather data](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Chapter-Lifecycle#2-gather-data)
- [x] 📆 `June 1` **Custom metrics completed** - 🔑 *Analysts*
  - Analysts have added all necessary [custom metrics](https://github.com/HTTPArchive/custom-metrics/blob/main/README.md) and drafted a PR ([example](https://github.com/HTTPArchive/almanac.httparchive.org/pull/1087)) to track query progress. 
- [x]  📆 `June 1` **HTTP Archive Crawl** - 🔑 *HA Team*
  - HTTP Archive runs the June crawl.

### [3. Validate results](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Chapter-Lifecycle#3-validate-results)
- [x] 📆 `August 15` **Query Metrics & Save Results** - 🔑 *Analysts*
  - Analysts have queried all metrics and saved the output.

### [4. Draft content](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Chapter-Lifecycle#4-draft-content)
- [x] 📆 `September 15` **First Draft of Chapter** - 🔑 *Authors*
  - Authors has written the chapter. 
- [x] 📆 `October 10` **Review & Edit Chapter** - 🔑 *Reviewers & Editors*
  - Reviewers and  Editors has processed the the chapter.

### [5. Publication](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Chapter-Lifecycle#5-publication)
- [ ] 📆 `October 15` **Chapter Publication (Markdown & PR)** - 🔑 *Authors*
  - Authors has converted the chapter to markdown and drafted a PR.
- [ ] 📆 `November 1` **Launch of 2024 Web Almanac 🚀** - 🔑 *Organizing committee*
 
### [6. Virtual conference](#)
- [ ] 📆 `November 20` **Virtual Conference** - 🔑 *Content Team*

<a id="chapter-resources"></a>
## [Chapter resources](#chapter-resources)
Refer to these 2024 Structured Data resources throughout the content creation process:
[📄 Google Docs](https://docs.google.com/document/d/1DIe6aPWqzYIZsZ-ZdehLkPVuezAHdrMffY_U4BuX0s0/edit) for outlining and drafting content
[🔍 SQL files](https://github.com/HTTPArchive/almanac.httparchive.org/tree/main/sql/2024/structured-data/README.md) for committing the queries used during analysis
[📊 Google Sheets](https://docs.google.com/spreadsheets/d/1GWniSGupK6KgME7urV7ff0iWStzopGXqnQvJ3_-ynD4/edit#gid=1778117656) for saving the results of queries
[📝 Markdown file](https://github.com/HTTPArchive/almanac.httparchive.org/tree/main/src/content/en/2024/structured-data.md) for publishing content and managing public metadata
[💻 Collab notebook](https://colab.research.google.com/drive/1cYFlIVQAHbIAUua7pUcXlfQfYMFRwRVH) for collaborative coding in Python - if needed
[💬 #web-almanac-structured-data](https://join.slack.com/t/httparchive/shared_invite/zt-45sgwmnb-eDEatOhqssqNAKxxOSLAaA) on Slack for team coordination

**Comment by cyberandy** [comment]
Happy to join as I did in the past.

**Comment by cyberandy** [comment]
I am fine with author role.

*Andrea Volpini*


*WordLift <https://wordlift.io>*

**Comment by nrllh** [comment]
Thank you, @cyberandy!

**Comment by nrllh** [comment]
Hey  @JohnBarrettWDW @SeoRobt @jasonbellwebdataworks @jonoalderson  @JasmineDW - awesome contributors from previous years 🙂 Are you interested in joining us again this year?

**Comment by SeoRobt** [comment]
Hey Nurullah,

Thanks for reaching out, unfortunately I won’t be able to participate this year due to some personal timing constraints. Plan on returning in 2025, cheers until then!

From: Nurullah Demir ***@***.***>
Date: Tuesday, April 9, 2024 at 6:36 PM
To: HTTPArchive/almanac.httparchive.org ***@***.***>
Cc: Rob Teitelman ***@***.***>, Mention ***@***.***>
Subject: Re: [HTTPArchive/almanac.httparchive.org] Structured Data 2024 (Issue #3594)

Hey @JohnBarrettWDW<https://github.com/JohnBarrettWDW> @SeoRobt<https://github.com/SeoRobt> @jasonbellwebdataworks<https://github.com/jasonbellwebdataworks> @jonoalderson<https://github.com/jonoalderson> @JasmineDW<https://github.com/JasmineDW> - awesome contributors from previous years 🙂 Are you interested in joining us again this year?

**Comment by jonoalderson** [comment]
Unfortunately I'm likely to be tied up with other commitments! :(

**Comment by cyberandy** [comment]
@jvandriel would be a great contributor!! Sorry @jonoalderson and @SeoRobt not to have you in the crew this year.

**Comment by jvandriel** [comment]
Sounds good to me @cyberandy.

**Comment by nrllh** [comment]
> Sounds good to me @cyberandy.

Great! Would you like to contribute as analyst?

**Comment by jvandriel** [comment]
I fear the analyst role is beyond my skillset @nrllh (I never learned SQL). Reviewer probably suits me best.

**Comment by nrllh** [comment]
All right, thank you!

**Comment by capjamesg** [comment]
I am happy to contribute as an editor. I am a professional technical writer (4+ years) and community contributor to various open standards initiatives (microformats2, W3C Social Web Community Group).

**Comment by rrlevering** [comment]
I am interested in being involved as a reviewer as well.

**Comment by capjamesg** [comment]
@cyberandy Thank you for the link! I am unavailable next week, but I can meet any week after that. If there is a document with the outline that I can review, please send it over and I can provide async feedback.

**Comment by cyberandy** [comment]
Thanks @capjamesg I have added a few slots on the week after and of course, don't worry if you can't make it. I will share here the link of the outline once ready. On another note, @nrllh when will the data be available?

**Comment by nrllh** [comment]
> Thanks @capjamesg I have added some additional slots for the week after (same link > https://doodle.com/meeting/participate/id/b8OMl9la) and of course, don't worry if you can't make it. I will share here the link of the outline once ready. On another note, @nrllh when will the data be available?

It's cool to see the progress! The data will be available by this Friday.

**Comment by nrllh** [comment]
@cyberandy the results are already in [the sheet](https://docs.google.com/spreadsheets/d/1GWniSGupK6KgME7urV7ff0iWStzopGXqnQvJ3_-ynD4/edit?gid=1778117656#gid=1778117656). Please check. The JSON-LD relationships and timeseries comparisons should be completed; the other results are already there.

**Comment by cyberandy** [comment]
thanks @nrllh, when do you think the time series comparisons can be completed?

**Comment by nrllh** [comment]
Today ;) I'll ping you in the next few hours

**Comment by nrllh** [comment]
> thanks @nrllh, when do you think the time series comparisons can be completed?

The data is there, except for the last two figures. I'm still working on them.

**Comment by nrllh** [comment]
> just a confirmation that the data focuses, also this year, on the top-level page (home page) only
We analyze both home pages and inner pages, but when reporting, we do so at the site level. This means we do not count a site more than once.

> will it be possible to extract structured data from Initial HTML (before JS execution) and compare it with structured data extracted from the Final DOM (after JS execution)? This way we could see what are the common practices on this front.
We have access to the response of all requests, including the root page's response. Could you please provide more details on what you exactly want to compare?

**Comment by cyberandy** [comment]
Thanks @nrllh for the clarifications. If my understanding is correct structured data from inner pages is aggregated with the top-level page.

Regarding the second point, the key aspect we’d like to explore is the percentage of websites that rely on client-side JavaScript for structured data injection versus those that serve it directly from the server. Additionally, it would be insightful to analyze the correlation between the types of entities represented in JSON-LD and whether they are injected via JavaScript or delivered server-side. Many thanks in advance!

**Comment by cyberandy** [comment]
Dear @danbri @rrlevering @jvandriel @capjamesg please update the Google Docs in the next few days and I'll proceed with the opening of the PR for the markdown in the next few days. 

I hope everyone can have a chance to review / contribute to the final document.

**Comment by capjamesg** [comment]
I have left comments in the linked PR.
