### ISSUE TITLE
Third Parties 2024

### ISSUE THREAD

**Issue by nrllh** [HTTPArchive/almanac.httparchive.org#3598]
# Third Parties 2024

![Third Parties illustration](https://raw.githubusercontent.com/HTTPArchive/almanac.httparchive.org/main/src/static/images/2019/third-parties/hero_lg.jpg)

If you're interested in contributing to the Third Parties chapter of the 2024 Web Almanac, please reply to this issue and indicate which role or roles best fit your interest and availability: [author](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Authors'-Guide), [reviewer](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Reviewers'-Guide), [analyst](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Analysts'-Guide), and/or [editor](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Editors'-Guide). You might be interested in exploring the changes to this year's version [here](https://github.com/HTTPArchive/almanac.httparchive.org/discussions/3619).

## Content team

| Lead | Authors | Reviewers | Analysts | Editors | Coordinator |
| ---- | ------- | --------- | -------- | ------- |    -------  |
| @zubairshafiq  | @zubairshafiq, @Yash-Vekaria, @ChrisBeeti   | @turban1988  | @Yash-Vekaria, @ChrisBeeti  | @neriiavr  | @turban1988   | 

<details>
<summary><b>Expand for more information about each role 👀</b></summary>

- The **[content team lead](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Content-Team-Leads'-Guide)** is the chapter owner and responsible for setting the scope of the chapter and managing contributors' day-to-day progress.
- **[Authors](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Authors'-Guide)** are subject matter experts and lead the content direction for each chapter. Chapters typically have one or two authors. Authors are responsible for planning the outline of the chapter, analyzing stats and trends, and writing the annual report.
- **[Reviewers](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Reviewers'-Guide)** are also subject matter experts and assist authors with technical reviews during the planning, analyzing, and writing phases.
- **[Analysts](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Analysts'-Guide)** are responsible for researching the stats and trends used throughout the Almanac. Analysts work closely with authors and reviewers during the planning phase to give direction on the types of stats that are possible from the dataset, and during the analyzing/writing phases to ensure that the stats are used correctly.
- **[Editors](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Editors'-Guide)** are technical writers who have a penchant for both technical and non-technical content correctness. Editors have a mastery of the English language and work closely with authors to help wordsmith content and ensure that everything fits together as a cohesive unit.
- The **[section coordinator](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Section-Leads'-Guide)** is the overall owner for all chapters within a section like "User Experience" or "Page Content" and helps to keep each chapter on schedule.

_Note: The time commitment for each role varies by the chapter's scope and complexity as well as the number of contributors._

For an overview of how the roles work together at each phase of the project, see the [Chapter Lifecycle](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Chapter-Lifecycle) doc.
</details>

### [0. Form the content team](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Chapter-Lifecycle#0-create-content-team)
- [x] 📆 `April 15` Complete program and content committee - 🔑 *Organizing committee*
  - The content team has at least one author, reviewer, and analyst.

### [1. Plan content](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Chapter-Lifecycle#1-plan-content)
- [x] 📆 `May 1` **First meeting to outline the chapter contents** - 🔑 *Content team*
  - The content team has completed the chapter outline.

### [2. Gather data](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Chapter-Lifecycle#2-gather-data)
- [x] 📆 `June 1` **Custom metrics completed** - 🔑 *Analysts*
  - Analysts have added all necessary [custom metrics](https://github.com/HTTPArchive/custom-metrics/blob/main/README.md) and drafted a PR ([example](https://github.com/HTTPArchive/almanac.httparchive.org/pull/1087)) to track query progress. 
- [x]  📆 `June 1` **HTTP Archive Crawl** - 🔑 *HA Team*
  - HTTP Archive runs the June crawl.

### [3. Validate results](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Chapter-Lifecycle#3-validate-results)
- [x] 📆 `August 15` **Query Metrics & Save Results** - 🔑 *Analysts*
  - Analysts have queried all metrics and saved the output.

### [4. Draft content](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Chapter-Lifecycle#4-draft-content)
- [x] 📆 `September 15` **First Draft of Chapter** - 🔑 *Authors*
  - Authors has written the chapter. 
- [x] 📆 `October 10` **Review & Edit Chapter** - 🔑 *Reviewers & Editors*
  - Reviewers and  Editors has processed the the chapter.

### [5. Publication](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Chapter-Lifecycle#5-publication)
- [x] 📆 `October 15` **Chapter Publication (Markdown & PR)** - 🔑 *Authors*
  - Authors has converted the chapter to markdown and drafted a PR.
- [ ] 📆 `November 1` **Launch of 2024 Web Almanac 🚀** - 🔑 *Organizing committee*
 
### [6. Virtual conference](#)
- [ ] 📆 `November 20` **Virtual Conference** - 🔑 *Content Team*

<a id="chapter-resources"></a>
## [Chapter resources](#chapter-resources)
Refer to these 2024 Third Parties resources throughout the content creation process:
[📄 Google Docs](https://docs.google.com/document/d/1BOJHpyGVOzQUUnAdDBxfjP6Lj1wwd6B3u830UVT8YBg/edit) for outlining and drafting content
[🔍 SQL files](https://github.com/HTTPArchive/almanac.httparchive.org/tree/main/sql/2024/third-parties/README.md) for committing the queries used during analysis
[📊 Google Sheets](https://docs.google.com/spreadsheets/d/18uTDBygSqgT_PNFldOz4guLSuXyMzDthRGnAG5if4sU/edit#gid=1778117656) for saving the results of queries
[📝 Markdown file](https://github.com/HTTPArchive/almanac.httparchive.org/tree/main/src/content/en/2023/third-parties.md) for publishing content and managing public metadata
[💻 Collab notebook](https://colab.research.google.com/drive/1bevj7ZX_8yZ3WH5w83QGVsmKIxTcyHLD) for collaborative coding in Python - if needed
[💬 #web-almanac-third-parties](https://join.slack.com/t/httparchive/shared_invite/zt-45sgwmnb-eDEatOhqssqNAKxxOSLAaA) on Slack for team coordination

**Comment by neriiavr** [comment]
I'm interested being an editor

**Comment by zubairshafiq** [comment]
I'm interested in being an author/editors. If needed, I can also help with the analysis

**Comment by Yash-Vekaria** [comment]
I'm interested in being author/analyst.

**Comment by ChrisBeeti** [comment]
I'm interested in being an author/analyst.

**Comment by turban1988** [comment]
I am interested in being an reviewer.

**Comment by nrllh** [comment]
Great team here! We're still open to more contributors, so the call continues.

**Comment by turban1988** [comment]
Hi @zubairshafiq,
Thank you very much for volunteering to lead the writing of this chapter! Could you please organize a kick-off meeting for this chapter (example: https://github.com/HTTPArchive/almanac.httparchive.org/issues/3603#issuecomment-2064351177) to organize the writing of the chapter? 

Furthermore, it would be helpful if you and all other contributors (@Yash-Vekaria, @ChrisBeeti , @ineriiavr) could join the slack channel of the HTTPArchive (https://join.slack.com/t/httparchive/shared_invite/zt-2hfkn28ts-~uXN4UGS0mXsKpzzhtZcow)

Thanks!

**Comment by zubairshafiq** [comment]
Hi @Yash-Vekaria, @ChrisBeeti, @turban1988, @neriiavr

Thanks for volunteering to contribute to the Third Parties chapter of the 2024 Web Alamnac. Three points:

1. To start off, let's schedule a kickoff meeting to settle on the content we want to have in the chapter. Please provide your availability here for the next two weeks: https://whenisgood.net/cneb587. Please be generous with your availability, as we have folks across several time zones.

2. Before the meeting, please take a look at the 2022 edition of the chapter: https://almanac.httparchive.org/en/2022/third-parties.  

3. Please join the #web-almanac-third-parties Slack channel: https://httparchive.slack.com/archives/C01CRFV97K4

**Comment by turban1988** [comment]
Sorry, the message somehow slipped through. I entered my availability.

**Comment by zubairshafiq** [comment]
Hi @turban1988 @Yash-Vekaria, we don't have any common availability. Can you folks make yourself available for more time slots? Also pining @ChrisBeeti @neriiavr 

<img width="1033" alt="image" src="https://github.com/HTTPArchive/almanac.httparchive.org/assets/16942427/c1fe742e-e670-4433-84cd-1cab683db8b4">

**Comment by turban1988** [comment]
I made more choices. Please keep in mind that due to the time shift, most of these times are not very well-placed (i.e., during the night).

![timetable_3rd_parties](https://github.com/HTTPArchive/almanac.httparchive.org/assets/29097632/a03ef572-bf48-4cc7-8801-3e485768f859)

**Comment by zubairshafiq** [comment]
Thank you for being accommodative. I have sent an invite for tomorrow.
