### ISSUE TITLE
Performance 2024

### ISSUE THREAD

**Issue by nrllh** [HTTPArchive/almanac.httparchive.org#3602]
# Performance 2024

![Performance illustration](https://raw.githubusercontent.com/HTTPArchive/almanac.httparchive.org/main/src/static/images/2019/performance/hero_lg.jpg)

If you're interested in contributing to the Performance chapter of the 2024 Web Almanac, please reply to this issue and indicate which role or roles best fit your interest and availability: [author](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Authors'-Guide), [reviewer](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Reviewers'-Guide), [analyst](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Analysts'-Guide), and/or [editor](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Editors'-Guide). You might be interested in exploring the changes to this year's version [here](https://github.com/HTTPArchive/almanac.httparchive.org/discussions/3619).

## Content team

| Lead | Authors | Reviewers | Analysts | Editors | Coordinator |
| ---- | ------- | --------- | -------- | ------- |    -------  |
| @ines-akrap  | @ines-akrap, @imeugenia   | @rviscomi, @siakaramalegos   | @kevinfarrugia, @guaca   | @Cherry  | @turban1988  | 

<details>
<summary><b>Expand for more information about each role 👀</b></summary>

- The **[content team lead](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Content-Team-Leads'-Guide)** is the chapter owner and responsible for setting the scope of the chapter and managing contributors' day-to-day progress.
- **[Authors](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Authors'-Guide)** are subject matter experts and lead the content direction for each chapter. Chapters typically have one or two authors. Authors are responsible for planning the outline of the chapter, analyzing stats and trends, and writing the annual report.
- **[Reviewers](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Reviewers'-Guide)** are also subject matter experts and assist authors with technical reviews during the planning, analyzing, and writing phases.
- **[Analysts](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Analysts'-Guide)** are responsible for researching the stats and trends used throughout the Almanac. Analysts work closely with authors and reviewers during the planning phase to give direction on the types of stats that are possible from the dataset, and during the analyzing/writing phases to ensure that the stats are used correctly.
- **[Editors](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Editors'-Guide)** are technical writers who have a penchant for both technical and non-technical content correctness. Editors have a mastery of the English language and work closely with authors to help wordsmith content and ensure that everything fits together as a cohesive unit.
- The **[section coordinator](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Section-Leads'-Guide)** is the overall owner for all chapters within a section like "User Experience" or "Page Content" and helps to keep each chapter on schedule.

_Note: The time commitment for each role varies by the chapter's scope and complexity as well as the number of contributors._

For an overview of how the roles work together at each phase of the project, see the [Chapter Lifecycle](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Chapter-Lifecycle) doc.
</details>

### [0. Form the content team](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Chapter-Lifecycle#0-create-content-team)
- [x] 📆 `April 15` Complete program and content committee - 🔑 *Organizing committee*
  - The content team has at least one author, reviewer, and analyst.

### [1. Plan content](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Chapter-Lifecycle#1-plan-content)
- [x] 📆 `May 1` **First meeting to outline the chapter contents** - 🔑 *Content team*
  - The content team has completed the chapter outline.

### [2. Gather data](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Chapter-Lifecycle#2-gather-data)
- [x] 📆 `June 1` **Custom metrics completed** - 🔑 *Analysts*
  - Analysts have added all necessary [custom metrics](https://github.com/HTTPArchive/custom-metrics/blob/main/README.md) and drafted a PR ([example](https://github.com/HTTPArchive/almanac.httparchive.org/pull/1087)) to track query progress. 
- [x]  📆 `June 1` **HTTP Archive Crawl** - 🔑 *HA Team*
  - HTTP Archive runs the June crawl.

### [3. Validate results](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Chapter-Lifecycle#3-validate-results)
- [x] 📆 `August 15` **Query Metrics & Save Results** - 🔑 *Analysts*
  - Analysts have queried all metrics and saved the output.

### [4. Draft content](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Chapter-Lifecycle#4-draft-content)
- [x] 📆 `September 15` **First Draft of Chapter** - 🔑 *Authors*
  - Authors has written the chapter. 
- [x] 📆 `October 10` **Review & Edit Chapter** - 🔑 *Reviewers & Editors*
  - Reviewers and  Editors has processed the the chapter.

### [5. Publication](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Chapter-Lifecycle#5-publication)
- [ ] 📆 `October 15` **Chapter Publication (Markdown & PR)** - 🔑 *Authors*
  - Authors has converted the chapter to markdown and drafted a PR.
- [ ] 📆 `November 1` **Launch of 2024 Web Almanac 🚀** - 🔑 *Organizing committee*
 
### [6. Virtual conference](#)
- [ ] 📆 `November 20` **Virtual Conference** - 🔑 *Content Team*

<a id="chapter-resources"></a>
## [Chapter resources](#chapter-resources)
Refer to these 2024 Performance resources throughout the content creation process:
[📄 Google Docs](https://docs.google.com/document/d/1O0uoOq-7ScqY4LJAzlT_HcMSnXS3Y_OA2jm77SpRr-w/edit) for outlining and drafting content
[🔍 SQL files](https://github.com/HTTPArchive/almanac.httparchive.org/tree/main/sql/2024/performance/README.md) for committing the queries used during analysis
[📊 Google Sheets](https://docs.google.com/spreadsheets/d/15038wEIoqY53Y_kR8U6QWM-PBO31ZySQGi147ABTNBc/edit#gid=1778117656) for saving the results of queries
[📝 Markdown file](https://github.com/HTTPArchive/almanac.httparchive.org/tree/main/src/content/en/2023/performance.md
) for publishing content and managing public metadata
[💻 Collab notebook](https://colab.research.google.com/drive/1RbSvm6nUIgZaKDdF6EAxNGXUa0cxouBG) for collaborative coding in Python - if needed
[💬 #web-almanac-performance](https://join.slack.com/t/httparchive/shared_invite/zt-45sgwmnb-eDEatOhqssqNAKxxOSLAaA) on Slack for team coordination

**Comment by Cherry** [comment]
For my first Web Almanac contribution, I’m interested in being an editor for this chapter.

**Comment by ines-akrap** [comment]
Happy to contribute to this chapter in any role :)

**Comment by imeugenia** [comment]
Hello :) Would be happy to co-author this chapter. 

It would be my second contribution as I authored Third Parties chapter last time. 
I don't have experience in analytics but if there will be workshops teaching how to do it, happy to learn!

**Comment by kevinfarrugia** [comment]
I would be happy to join as an analyst if needed.

**Comment by rviscomi** [comment]
Happy to review this year :)

**Comment by guaca** [comment]
Happy to join as an analyst! But I’m also open for other roles, if needed 😊

**Comment by nrllh** [comment]
> It would be my second contribution as I led the Third Parties chapter last time. I don't have experience in analytics but if there will be workshops teaching how to do it, happy to learn!

@imeugenia  We have a [guidline for analysts](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Analysts%27-Guide) ;) 

We have also here a great team, thank you all! I assigned you all ;)

**Comment by siakaramalegos** [comment]
Happy to help as a reviewer!

**Comment by nrllh** [comment]
@siakaramalegos thank you!

**Comment by turban1988** [comment]
Hi @ines-akrap,
Thank you very much for volunteering to lead the writing of this chapter! Could you please organize a kick-off meeting for this chapter (example: https://github.com/HTTPArchive/almanac.httparchive.org/issues/3603#issuecomment-2064351177) to organize the writing of the chapter? 

Furthermore, it would be helpful if you and all other contributors (@imeugenia , @rviscomi, @ines-akrap @siakaramalegos , @kevinfarrugia, @guaca , @Cherry) could join the slack channel of the HTTPArchive (https://join.slack.com/t/httparchive/shared_invite/zt-2hfkn28ts-~uXN4UGS0mXsKpzzhtZcow)

Thanks!

**Comment by ines-akrap** [comment]
Hi everyone, 

I just set up and shared a link to the meeting availability tool in our slack channel, so please go there (https://join.slack.com/t/httparchive/shared_invite/zt-2hfkn28ts-~uXN4UGS0mXsKpzzhtZcow) and fill it out :) 

Thanks

**Comment by nrllh** [comment]
> Hi @ines-akrap Like the 2022 performance chapter, I'm now keen on participating as an analyst/reviewer for the upcoming performance chapter. Would it be possible for me to join?

I appreciate your interest! We still need for some chapters [analysts](https://github.com/HTTPArchive/almanac.httparchive.org/issues?q=is%3Aissue+is%3Aopen+label%3A%22help+wanted%3A+analysts%22) and [authors](https://github.com/HTTPArchive/almanac.httparchive.org/issues?q=is%3Aissue+is%3Aopen+label%3A%22help+wanted%3A+coauthors%22). Please have a look at them.

**Comment by mikaelaraujo** [comment]
@ines-akrap, @imeugenia, @rviscomi, @siakaramalegos, @kevinfarrugia, @guaca, and @Cherry. Once you contributed at 2024 edition of this chapter, it will be great if you can contribute at [Performance 2025](https://github.com/HTTPArchive/almanac.httparchive.org/issues/4082#issuecomment-2892295380) edition!

**Comment by kevinfarrugia** [comment]
I'm sorry but from my end I am unable to commit to it this year. Feel free to reach out if you have any questions on last year's queries though.
