### ISSUE TITLE
Privacy 2024

### ISSUE THREAD

**Issue by nrllh** [HTTPArchive/almanac.httparchive.org#3603]
# Privacy 2024

![Privacy illustration](https://raw.githubusercontent.com/HTTPArchive/almanac.httparchive.org/main/src/static/images/2020/privacy/hero_lg.jpg)

If you're interested in contributing to the Privacy chapter of the 2024 Web Almanac, please reply to this issue and indicate which role or roles best fit your interest and availability: [author](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Authors'-Guide), [reviewer](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Reviewers'-Guide), [analyst](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Analysts'-Guide), and/or [editor](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Editors'-Guide). You might be interested in exploring the changes to this year's version [here](https://github.com/HTTPArchive/almanac.httparchive.org/discussions/3619).

## Content team

| Lead | Authors | Reviewers | Analysts | Editors | Coordinator |
| ---- | ------- | --------- | -------- | ------- |    -------  |
| @UmarIqbal  | @umariqbal, @ChrisBeeti,  @shaoormunir, @turban1988, @ydimova     | @lord-r3, @AlbertoFDR | @Yash-Vekaria, @max-ostapenko, @bstandaert-wustl | @cqueern  | @turban1988   | 

<details>
<summary><b>Expand for more information about each role 👀</b></summary>

- The **[content team lead](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Content-Team-Leads'-Guide)** is the chapter owner and responsible for setting the scope of the chapter and managing contributors' day-to-day progress.
- **[Authors](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Authors'-Guide)** are subject matter experts and lead the content direction for each chapter. Chapters typically have one or two authors. Authors are responsible for planning the outline of the chapter, analyzing stats and trends, and writing the annual report.
- **[Reviewers](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Reviewers'-Guide)** are also subject matter experts and assist authors with technical reviews during the planning, analyzing, and writing phases.
- **[Analysts](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Analysts'-Guide)** are responsible for researching the stats and trends used throughout the Almanac. Analysts work closely with authors and reviewers during the planning phase to give direction on the types of stats that are possible from the dataset, and during the analyzing/writing phases to ensure that the stats are used correctly.
- **[Editors](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Editors'-Guide)** are technical writers who have a penchant for both technical and non-technical content correctness. Editors have a mastery of the English language and work closely with authors to help wordsmith content and ensure that everything fits together as a cohesive unit.
- The **[section coordinator](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Section-Leads'-Guide)** is the overall owner for all chapters within a section like "User Experience" or "Page Content" and helps to keep each chapter on schedule.

_Note: The time commitment for each role varies by the chapter's scope and complexity as well as the number of contributors._

For an overview of how the roles work together at each phase of the project, see the [Chapter Lifecycle](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Chapter-Lifecycle) doc.
</details>

### [0. Form the content team](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Chapter-Lifecycle#0-create-content-team)
- [x] 📆 `April 15` Complete program and content committee - 🔑 *Organizing committee*
  - The content team has at least one author, reviewer, and analyst.

### [1. Plan content](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Chapter-Lifecycle#1-plan-content)
- [x] 📆 `May 1` **First meeting to outline the chapter contents** - 🔑 *Content team*
  - The content team has completed the chapter outline.

### [2. Gather data](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Chapter-Lifecycle#2-gather-data)
- [x] 📆 `June 1` **Custom metrics completed** - 🔑 *Analysts*
  - Analysts have added all necessary [custom metrics](https://github.com/HTTPArchive/custom-metrics/blob/main/README.md) and drafted a PR ([example](https://github.com/HTTPArchive/almanac.httparchive.org/pull/1087)) to track query progress. 
- [x]  📆 `June 1` **HTTP Archive Crawl** - 🔑 *HA Team*
  - HTTP Archive runs the June crawl.

### [3. Validate results](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Chapter-Lifecycle#3-validate-results)
- [x] 📆 `August 15` **Query Metrics & Save Results** - 🔑 *Analysts*
  - Analysts have queried all metrics and saved the output.

### [4. Draft content](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Chapter-Lifecycle#4-draft-content)
- [x] 📆 `September 15` **First Draft of Chapter** - 🔑 *Authors*
  - Authors has written the chapter. 
- [x] 📆 `October 10` **Review & Edit Chapter** - 🔑 *Reviewers & Editors*
  - Reviewers and  Editors has processed the the chapter.

### [5. Publication](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Chapter-Lifecycle#5-publication)
- [ ] 📆 `October 15` **Chapter Publication (Markdown & PR)** - 🔑 *Authors*
  - Authors has converted the chapter to markdown and drafted a PR.
- [ ] 📆 `November 1` **Launch of 2024 Web Almanac 🚀** - 🔑 *Organizing committee*
 
### [6. Virtual conference](#)
- [ ] 📆 `November 20` **Virtual Conference** - 🔑 *Content Team*

<a id="chapter-resources"></a>
## [Chapter resources](#chapter-resources)
Refer to these 2024 Privacy resources throughout the content creation process:
[📄 Google Docs](https://docs.google.com/document/d/14XXHV7A8WI1a-UQqmlRj4dKYIJjZMqo__CN5POfM9Po/edit) for outlining and drafting content
[🔍 SQL files](https://github.com/HTTPArchive/almanac.httparchive.org/tree/main/sql/2024/privacy/README.md) for committing the queries used during analysis
[📊 Google Sheets](https://docs.google.com/spreadsheets/d/18r8cT6x9lPdM-rXvXjsqx84W7ZDdTDYGD59xr0UGOwg/edit#gid=1778117656) for saving the results of queries
[📝 Markdown file](https://github.com/HTTPArchive/almanac.httparchive.org/tree/main/src/content/en/2023/privacy.md) for publishing content and managing public metadata
[💻 Collab notebook](https://colab.research.google.com/drive/1n9CeYIt3-Rtzvu1o6khn0KKc4I7ofkQK) for collaborative coding in Python - if needed
[💬 #web-almanac-privacy](https://join.slack.com/t/httparchive/shared_invite/zt-45sgwmnb-eDEatOhqssqNAKxxOSLAaA) on Slack for team coordination

**Comment by Yash-Vekaria** [comment]
I'm interested in being author/analyst.

**Comment by lord-r3** [comment]
I would volunteer to review this chapter.

**Comment by ChrisBeeti** [comment]
I'm interested in being an author/analyst.

**Comment by shaoormunir** [comment]
I am interested in being an author/analysis/reviewer.

**Comment by turban1988** [comment]
I am interested in being an author/reviewer.

**Comment by max-ostapenko** [comment]
✋🏽 Going for analyst. Oh, yeah!

**Comment by bstandaert-wustl** [comment]
I'm interested in being an author or analyst.

**Comment by AlbertoFDR** [comment]
I would like to review this chapter.

**Comment by ydimova** [comment]
I'm interested in being an author for this chapter

**Comment by nrllh** [comment]
> I'm interested in being an author or analyst.
Thank you for your interest, @bstandaert-wustl! Could you provide a brief bio of yourself?

**Comment by nrllh** [comment]
Thanks, everyone! This year's privacy chapter is going to be great!

**Comment by UmarIqbal** [comment]
@nrllh I worked with @bstandaert-wustl last year at WashU. He is phenomenal : )

**Comment by nrllh** [comment]
We're thrilled to have such a phenomenal analyst on board this year. Thank you for your interest, @bstandaert-wustl!

**Comment by bstandaert-wustl** [comment]
@nrllh Thanks, looking forward to it!

**Comment by UmarIqbal** [comment]
@ChrisBeeti, @shaoormunir, @turban1988, @ydimova, @lord-r3, @AlbertoFDR, @Yash-Vekaria, @max-ostapenko, @bstandaert-wustl, @cqueern, @turban1988

Hi everyone! I am very excited about this and looking forward to collaborating with all of you! 

Our first deadline is fast approaching and we need to outline the chapter content soon! 

To start off, I would like to schedule a 30-60 minute meeting to start the planning and brainstorming process. So please provide your availability here for the next two weeks: https://www.when2meet.com/?24680171-cUOH1 (please be generous with your availability, as we have folks across several time zones).

Also, here is an agenda for what we might want to discuss on the kickoff call: https://docs.google.com/document/d/1WJT9kfKHxwNl5HNAhIddefWC0vCvH3DUIxajT1gQWao/edit?usp=sharing (please request access).

Also a gentle reminder to join the #web-almanac-privacy channel on Slack (https://join.slack.com/t/httparchive/shared_invite/zt-2hfkn28ts-~uXN4UGS0mXsKpzzhtZcow)

**Comment by UmarIqbal** [comment]
Thank you all for sharing your availability. I see that most of you are available on May 1 (Wednesday) at 1 PM CT / 11 AM PT. So let's plan on meeting on May 1. I will share a zoom link with you all shorty on Slack (please join slack if you have not already)! 

Please also read the last year's report (https://docs.google.com/document/d/1r1TU1rH3v-686t7EaqQQ0mXg7unNKZlFYmUmbscQRtM/) and think of potential new analysis that you would like to add in this year's report.

**Comment by UmarIqbal** [comment]
Thank you to all those who made it to the meeting today! We have listed the potential analyses that we plan to conduct here: https://docs.google.com/document/d/1WJT9kfKHxwNl5HNAhIddefWC0vCvH3DUIxajT1gQWao/edit?usp=sharing (you can still add additional stuff)

We are planning to meet next time to discuss the feasibility of analysis and finalize it. Please provide your availability here: https://www.when2meet.com/?24857542-z4Maf

**Comment by max-ostapenko** [comment]
[Privacy 2024 custom metrics PR](https://github.com/HTTPArchive/custom-metrics/pull/117)

**Comment by max-ostapenko** [comment]
Here is a PR for chapter markdown #3817

Please move the chapter content there and don't forget to add yourself to contributors.
It will allow to preview the chapter on the staging server before pushing it to public website.
