### ISSUE TITLE
Security 2024

### ISSUE THREAD

**Issue by nrllh** [HTTPArchive/almanac.httparchive.org#3604]
# Security 2024

![Security illustration](https://raw.githubusercontent.com/HTTPArchive/almanac.httparchive.org/main/src/static/images/2019/security/hero_lg.jpg)

If you're interested in contributing to the Security chapter of the 2024 Web Almanac, please reply to this issue and indicate which role or roles best fit your interest and availability: [author](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Authors'-Guide), [reviewer](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Reviewers'-Guide), [analyst](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Analysts'-Guide), and/or [editor](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Editors'-Guide). You might be interested in exploring the changes to this year's version [here](https://github.com/HTTPArchive/almanac.httparchive.org/discussions/3619).

## Content team

| Lead | Authors | Reviewers | Analysts | Editors | Coordinator |
| ---- | ------- | --------- | -------- | ------- |    -------  |
| @GJFR  | @GJFR, @vikvanderlinden | @lord-r3, @SaptakS, @AlbertoFDR, @clarkio | @JannisBush | @cqueern, @joeleonjr | @tomvangoethem   | 

<details>
<summary><b>Expand for more information about each role 👀</b></summary>

- The **[content team lead](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Content-Team-Leads'-Guide)** is the chapter owner and responsible for setting the scope of the chapter and managing contributors' day-to-day progress.
- **[Authors](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Authors'-Guide)** are subject matter experts and lead the content direction for each chapter. Chapters typically have one or two authors. Authors are responsible for planning the outline of the chapter, analyzing stats and trends, and writing the annual report.
- **[Reviewers](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Reviewers'-Guide)** are also subject matter experts and assist authors with technical reviews during the planning, analyzing, and writing phases.
- **[Analysts](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Analysts'-Guide)** are responsible for researching the stats and trends used throughout the Almanac. Analysts work closely with authors and reviewers during the planning phase to give direction on the types of stats that are possible from the dataset, and during the analyzing/writing phases to ensure that the stats are used correctly.
- **[Editors](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Editors'-Guide)** are technical writers who have a penchant for both technical and non-technical content correctness. Editors have a mastery of the English language and work closely with authors to help wordsmith content and ensure that everything fits together as a cohesive unit.
- The **[section coordinator](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Section-Leads'-Guide)** is the overall owner for all chapters within a section like "User Experience" or "Page Content" and helps to keep each chapter on schedule.

_Note: The time commitment for each role varies by the chapter's scope and complexity as well as the number of contributors._

For an overview of how the roles work together at each phase of the project, see the [Chapter Lifecycle](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Chapter-Lifecycle) doc.
</details>

### [0. Form the content team](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Chapter-Lifecycle#0-create-content-team)
- [x] 📆 `April 15` Complete program and content committee - 🔑 *Organizing committee*
  - The content team has at least one author, reviewer, and analyst.

### [1. Plan content](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Chapter-Lifecycle#1-plan-content)
- [x] 📆 `May 1` **First meeting to outline the chapter contents** - 🔑 *Content team*
  - The content team has completed the chapter outline.

### [2. Gather data](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Chapter-Lifecycle#2-gather-data)
- [x] 📆 `June 1` **Custom metrics completed** - 🔑 *Analysts*
  - Analysts have added all necessary [custom metrics](https://github.com/HTTPArchive/custom-metrics/blob/main/README.md) and drafted a PR ([example](https://github.com/HTTPArchive/almanac.httparchive.org/pull/1087)) to track query progress. 
- [x]  📆 `June 1` **HTTP Archive Crawl** - 🔑 *HA Team*
  - HTTP Archive runs the June crawl.

### [3. Validate results](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Chapter-Lifecycle#3-validate-results)
- [x] 📆 `August 15` **Query Metrics & Save Results** - 🔑 *Analysts*
  - Analysts have queried all metrics and saved the output.

### [4. Draft content](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Chapter-Lifecycle#4-draft-content)
- [x] 📆 `September 15` **First Draft of Chapter** - 🔑 *Authors*
  - Authors has written the chapter. 
- [ ] 📆 `October 10` **Review & Edit Chapter** - 🔑 *Reviewers & Editors*
  - Reviewers and  Editors has processed the the chapter.

### [5. Publication](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Chapter-Lifecycle#5-publication)
- [ ] 📆 `October 15` **Chapter Publication (Markdown & PR)** - 🔑 *Authors*
  - Authors has converted the chapter to markdown and drafted a PR.
- [ ] 📆 `November 1` **Launch of 2024 Web Almanac 🚀** - 🔑 *Organizing committee*
 
### [6. Virtual conference](#)
- [ ] 📆 `November 20` **Virtual Conference** - 🔑 *Content Team*

<a id="chapter-resources"></a>
## [Chapter resources](#chapter-resources)
Refer to these 2024 Security resources throughout the content creation process:
[📄 Google Docs](https://docs.google.com/document/d/1jBGxgkBDIi9nDQ-n2eVFkwDZXk_9rQkLiKfnHkknsAs/edit) for outlining and drafting content
[🔍 SQL files](https://github.com/HTTPArchive/almanac.httparchive.org/tree/main/sql/2024/security/README.md) for committing the queries used during analysis
[📊 Google Sheets](https://docs.google.com/spreadsheets/d/1b9IEGbfQjKCEaTBmcv_zyCyWEsq35StCa-dVOe6V1Cs/edit#gid=1778117656) for saving the results of queries
[📝 Markdown file](https://github.com/HTTPArchive/almanac.httparchive.org/tree/main/src/content/en/2023/security.md) for publishing content and managing public metadata
[💻 Collab notebook](https://colab.research.google.com/drive/1me28THvNzV2cGxAake1S10FXPBQOsp88) for collaborative coding in Python - if needed
[💬 #web-almanac-security](https://join.slack.com/t/httparchive/shared_invite/zt-45sgwmnb-eDEatOhqssqNAKxxOSLAaA) on Slack for team coordination

**Comment by lord-r3** [comment]
I would volunteer to review this chapter.

**Comment by vikvanderlinden** [comment]
I'd be happy to join as author for this chapter!

**Comment by JannisBush** [comment]
I would like to join as either an author or an analyst for this chapter.

**Comment by SaptakS** [comment]
Having led the chapter twice, I would be happy to take the role of a reviewer this time.

**Comment by turban1988** [comment]
I am interested in being an reviewer.

**Comment by GJFR** [comment]
I'd like to volunteer as author!

**Comment by AlbertoFDR** [comment]
I would like to review this chapter.

**Comment by joeleonjr** [comment]
I'd be happy to join as an author or analyst. Specifically, I'm interested in reviewing the data for secrets leaking in front-end source code. I think this could be a cool addition to the project.

**Comment by clarkio** [comment]
Hi all, I'm a bit late to this but wanted to offer up help and support as I've contributed in the last security chapter as a reviewer and author. @lirantal (who has also contributed before) might be interested as well. If you're all set for this year, no worries but do keep us in mind in the future. Thanks!

**Comment by nrllh** [comment]
> Hi all, I'm a bit late to this but wanted to offer up help and support as I've contributed in the last security chapter as a reviewer and author. @lirantal (who has also contributed before) might be interested as well. If you're all set for this year, no worries but do keep us in mind in the future. Thanks!

Thanks for offering your help and support! We'd like to have you involved again this year. Which role would you be interested in?

**Comment by clarkio** [comment]
Oh nice ok. I'm interested in reviewing if that works.

**Comment by tomvangoethem** [comment]
Hey folks! How are you feeling about the upcoming deadline regarding outlining the chapter? It could be nice to set up a quick call with all volunteers of this chapter to get quickly aligned on how everyone envisions it. 
@GJFR, could you perhaps set up a meeting? (preferably early this upcoming coming week, though later would also work). Thanks & looking forward to seeing the chapter take more shape 👍

**Comment by GJFR** [comment]
Hi everyone!

I’m currently still on holiday, and will only be back on the 7th of May. We can already plan our meeting though.

@vikvanderlinden, @joeviggiano, @lord-r3, @SaptakS, @AlbertoFDR, @clarkio could you fill out this whenisgood?
https://whenisgood.net/5gpmxp7

You should be able to select your own timezone. If none of these slots work for you, please let me know.

Looking forward to discussing the chapter!

**Comment by GJFR** [comment]
Friendly reminder to fill in the whenisgood if you haven't already.
To give our analysts enough time to take care of the custom metrics, let's lock in a meeting date by Tuesday.

If you can't make it for some reason, feel free to share any ideas you might have in our HTTP Archive Slack channel.

**Comment by GJFR** [comment]
Hi @joeleonjr, it seems like we accidentally tagged another Joe! This should be solved now. Have you already registered on HTTP Archive's Slack channel? I can't seem to find you there.

**Comment by joeleonjr** [comment]
Just joined! Apologies for the delay.

**Comment by GJFR** [comment]
No worries! You can check the [planning doc](https://docs.google.com/document/d/1jBGxgkBDIi9nDQ-n2eVFkwDZXk_9rQkLiKfnHkknsAs/edit) to get up to speed on what we want to include in this year's chapter.

Next deadline is June 1st, by which all custom metrics have to be finished. Best to check with your co-analyst @JannisBush about that.

Don't hesitate to contact me if something is not clear!
