### ISSUE TITLE
Jamstack 2024

### ISSUE THREAD

**Issue by nrllh** [HTTPArchive/almanac.httparchive.org#3610]
# Jamstack 2024

![Jamstack illustration](https://raw.githubusercontent.com/HTTPArchive/almanac.httparchive.org/main/src/static/images/2020/jamstack/hero_lg.jpg)

If you're interested in contributing to the Jamstack chapter of the 2024 Web Almanac, please reply to this issue and indicate which role or roles best fit your interest and availability: [author](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Authors'-Guide), [reviewer](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Reviewers'-Guide), [analyst](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Analysts'-Guide), and/or [editor](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Editors'-Guide). You might be interested in exploring the changes to this year's version [here](https://github.com/HTTPArchive/almanac.httparchive.org/discussions/3619).

## Content team

| Lead | Authors | Reviewers | Analysts | Editors | Coordinator |
| ---- | ------- | --------- | -------- | ------- |    -------  |
| @mneumegen | @mneumegen  | @thomkrupa  | @guaca  | - | @turban1988  |

<details>
<summary><b>Expand for more information about each role 👀</b></summary>

- The **[content team lead](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Content-Team-Leads'-Guide)** is the chapter owner and responsible for setting the scope of the chapter and managing contributors' day-to-day progress.
- **[Authors](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Authors'-Guide)** are subject matter experts and lead the content direction for each chapter. Chapters typically have one or two authors. Authors are responsible for planning the outline of the chapter, analyzing stats and trends, and writing the annual report.
- **[Reviewers](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Reviewers'-Guide)** are also subject matter experts and assist authors with technical reviews during the planning, analyzing, and writing phases.
- **[Analysts](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Analysts'-Guide)** are responsible for researching the stats and trends used throughout the Almanac. Analysts work closely with authors and reviewers during the planning phase to give direction on the types of stats that are possible from the dataset, and during the analyzing/writing phases to ensure that the stats are used correctly.
- **[Editors](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Editors'-Guide)** are technical writers who have a penchant for both technical and non-technical content correctness. Editors have a mastery of the English language and work closely with authors to help wordsmith content and ensure that everything fits together as a cohesive unit.
- The **[section coordinator](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Section-Leads'-Guide)** is the overall owner for all chapters within a section like "User Experience" or "Page Content" and helps to keep each chapter on schedule.

_Note: The time commitment for each role varies by the chapter's scope and complexity as well as the number of contributors._

For an overview of how the roles work together at each phase of the project, see the [Chapter Lifecycle](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Chapter-Lifecycle) doc.
</details>

### [0. Form the content team](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Chapter-Lifecycle#0-create-content-team)
- [x] 📆 `April 15` Complete program and content committee - 🔑 *Organizing committee*
  - The content team has at least one author, reviewer, and analyst.

### [1. Plan content](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Chapter-Lifecycle#1-plan-content)
- [x] 📆 `May 1` **First meeting to outline the chapter contents** - 🔑 *Content team*
  - The content team has completed the chapter outline.

### [2. Gather data](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Chapter-Lifecycle#2-gather-data)
- [x] 📆 `June 1` **Custom metrics completed** - 🔑 *Analysts*
  - Analysts have added all necessary [custom metrics](https://github.com/HTTPArchive/custom-metrics/blob/main/README.md) and drafted a PR ([example](https://github.com/HTTPArchive/almanac.httparchive.org/pull/1087)) to track query progress. 
- [x]  📆 `June 1` **HTTP Archive Crawl** - 🔑 *HA Team*
  - HTTP Archive runs the June crawl.

### [3. Validate results](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Chapter-Lifecycle#3-validate-results)
- [x] 📆 `August 15` **Query Metrics & Save Results** - 🔑 *Analysts*
  - Analysts have queried all metrics and saved the output.

### [4. Draft content](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Chapter-Lifecycle#4-draft-content)
- [x] 📆 `September 15` **First Draft of Chapter** - 🔑 *Authors*
  - Authors has written the chapter. 
- [x] 📆 `October 10` **Review & Edit Chapter** - 🔑 *Reviewers & Editors*
  - Reviewers and  Editors has processed the the chapter.

### [5. Publication](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Chapter-Lifecycle#5-publication)
- [ ] 📆 `October 15` **Chapter Publication (Markdown & PR)** - 🔑 *Authors*
  - Authors has converted the chapter to markdown and drafted a PR.
- [ ] 📆 `November 1` **Launch of 2024 Web Almanac 🚀** - 🔑 *Organizing committee*
 
### [6. Virtual conference](#)
- [ ] 📆 `November 20` **Virtual Conference** - 🔑 *Content Team*

<a id="chapter-resources"></a>
## [Chapter resources](#chapter-resources)
Refer to these 2024 Jamstack resources throughout the content creation process:
[📄 Google Docs](https://docs.google.com/document/d/17nSxLz18zVQBLTbo2NTIfaLmEPKrDl0MfltRjE1v6vI/edit) for outlining and drafting content
[🔍 SQL files](https://github.com/HTTPArchive/almanac.httparchive.org/tree/main/sql/2024/jamstack/README.md) for committing the queries used during analysis
[📊 Google Sheets](https://docs.google.com/spreadsheets/d/1wKswSnp8TuN4aZb63ir7hE5eCikIu8zEdQYPp4Xo6O0/edit#gid=807625051) for saving the results of queries
[📝 Markdown file](https://github.com/HTTPArchive/almanac.httparchive.org/tree/main/src/content/en/2023/jamstack.md) for publishing content and managing public metadata
[💻 Collab notebook](https://colab.research.google.com/drive/18_lhg-flADW1oAC9xSykoHnF8tssiqat?usp=drive_link) for collaborative coding in Python - if needed
[💬 #web-almanac-jamstack](https://join.slack.com/t/httparchive/shared_invite/zt-45sgwmnb-eDEatOhqssqNAKxxOSLAaA) on Slack for team coordination

**Comment by ianand** [comment]
What is the definition of "Jamstack" that the 2024 version of the almanac will use? The official definition (Jamstack.org) has shifted over the years, as has the definition used by the web almanac. In 2020/2021 it was a framework-centric definition and in 2022 it was performance-centric definition.

**Comment by nrllh** [comment]
> What is the definition of "Jamstack" that the 2024 version of the almanac will use? The official definition (Jamstack.org) has shifted over the years, as has the definition used by the web almanac. In 2020/2021 it was a framework-centric definition and in 2022 it was performance-centric definition.

Thank you for sharing your concern. We are focused on the framework-centric domain; however, the analysis and outline are shaped by the content team.

**Comment by nrllh** [comment]
@ianand, would you be interested in contributing as an author?

**Comment by S3gillu** [comment]
Would love to contribute as a reviewer for jamstack

**Comment by nrllh** [comment]
Hey @seldo @whitep4nth3r @GregBrimble @Nutlope @seldo - awesome contributors from previous years 🙂 Are you interested in joining us again this year?

**Comment by seldo** [comment]
I appreciate the invitation, but it doesn't really fit my current job description!

**Comment by Nutlope** [comment]
Likewise, I will pass thank you!

**Comment by whitep4nth3r** [comment]
I'm afraid I don't have capacity this year, but I'm sharing this with someone who I think might be up for it.

**Comment by mneumegen** [comment]
hey @nrllh, I've been working on a [community project](https://thefutureofjamstack.org/)  to figure out where Jamstack goes from here, happy be involved if I can be useful.

**Comment by nrllh** [comment]
Thank you, @mneumegen! So you are now the lead autor ;) We need an analyst and a reviewer, then we are fine with this chapter!

**Comment by nrllh** [comment]
Thank you, @thomkrupa!

Do you (@thomkrupa, @mneumegen) think you could also take on the role of analyst for this chapter? Unfortunately, we still do not have any analysts.

**Comment by mneumegen** [comment]
Is there any documentation of the data and analyst tools available? I'm new to this so I'm not quite sure what I'm getting into taking on a whole chapter.

**Comment by tunetheweb** [comment]
Mostly wee query the HTTP Archive dataset which is based on a monthly crawl of the top X million websites in the world. It gathers all the stuff that makes up the homepage (what resources it loads, the size of those… etc.), and one secondary page. For both mobile simulation ame desktop simulation. It also runs a Wappalyzer detection to try to detect what technologies are used by the site based on JS it sees, HTTP headers and HTML markup. All this data is stored in a massive BugQuery dataset.

There’s an Analyst’s guide here: https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Analysts'-Guide

And the 2022 queries are here if you can read SQL:
https://github.com/HTTPArchive/almanac.httparchive.org/tree/main/sql/2022/jamstack

At its simplest you can copy and paste the queries to a 2024 folder and update the dates. And then run them through BigQuery (we’ll provide access to that as some of these queries are chunky!).

For a more interesting chapter, it’ll mean seeing what _new stuff_ you can query for. That’s a brainstorming exercise between the author, the analyst and reaching out to some HTTP Archive experts (including myself) to see what’s possible. For example, In 2022 they went in a whole new direction as to what they defined as a Jamstack. You can continue that, or revert to 2021 definition and queries. Or come up with something new again!

And if there’s stuff that’s not available that you can pick up from the page using JavaScript the you can write that script and we’ll help you get it added to the next crawl so you can gather that data. So JavaScript knowledge would be good if that’s needed. Or alternatively you can update our technologies detection config to catch and new technologies we’re not detecting.

So read the previous years chapters to familiarise yourself with the type of stuff that can be queried. That ask yourself what you as a Jamstack subject matter expert like to know on the topic? What’s did previous years not cover that would be interesting to dig into?

You can also browse the other chapters to see what they include to further understand what’s possible, and maybe give inspiration.

**Comment by guaca** [comment]
Hi there!

I'm happy to join as an analyst 😃 

BTW, I love @tunetheweb's suggestion about brainstorming to see what new things we can query for 👍

**Comment by ianand** [comment]
> @ianand, would you be interested in contributing as an author?

Sorry for the delay. Realize it's a moot point now but I didn't have the bandwidth. Glad to see @mneumegen is on it though! Curious to see what you come up with given the past approaches and challenges.

**Comment by nrllh** [comment]
> Sorry for the delay. Realize it's a moot point now but I didn't have the bandwidth. Glad to see @mneumegen is on it though! Curious to see what you come up with given the past approaches and challenges.

thank you, @ianand! We are still looking for contributors for this chapter. Please let us know, if you want to contribute to the chapter =)

**Comment by mneumegen** [comment]
Let's do it @guaca & @thomkrupa. I've sent a Calendar event for next week to talk about first steps. @turban1988 & @S3gillu if you're keen to join, send an email over to mike@cloudcannon.com.

Thanks!
