### ISSUE TITLE
Some visualisations are not viewable in iOS Safari

### ISSUE THREAD

**Issue by bazzadp** [HTTPArchive/almanac.httparchive.org#369]
The following don't display in the Markdown chapter (presumably a permission issue with sheets?).

- Figure 3
- Figure 5
- Figure 6
- Figure 7
- Figure 9
- Figure 10

This is on production: https://almanac.httparchive.org/en/2019/markup

**Comment by bazzadp** [comment]
Same issue with other chapters (e.g. Performance, Accessibility).

**Comment by bazzadp** [comment]
Actually think it's just an iOS Safari issue (iOS 13.2 on an iPhone Xs). Seems fine on Desktop Safari though.

**Comment by bazzadp** [comment]
And today I learned how to use Web Inspector for iOS using your Mac 😀

This is the error I get: 

> Canvas area exceeds the maximum limit (width * height > 16777216).

I tried a few different [URL options](https://stackoverflow.com/questions/23446449/google-sheet-embed-url-documentation) but none made it work.

I wonder do we need to revert back to screenshots - at least on mobile?

**Comment by rviscomi** [comment]
WEIRD! I am starting to think images are the best or at least only feasible option for mobile. The only problem is the work required to screenshot everything, get them uploaded, update the figures, and make them responsive. If anyone has the time, we should absolutely do it. I'm swamped :(

**Comment by bazzadp** [comment]
At least we can screenshot them from the chapters and the auto compressing on commit is cool! So might not take as long as we think. Will concentrate on editing for not and see if I get a chance to look later.

**Comment by rviscomi** [comment]
I've started addressing this in #384 as a precedent of the new process outlined in #237. I think we can close this issue as it's being addressed in #237 now that I've updated the process to specify images on mobile.
