### ISSUE TITLE
Issue with the 2022 sustainability chapter - Fix Broken Link to planetcentricdesign.com

### ISSUE THREAD

**Issue by LarsFlieger** [HTTPArchive/almanac.httparchive.org#3708]
At https://almanac.httparchive.org/en/2022/sustainability#designing-for-stakeholders

![image](https://github.com/user-attachments/assets/8f64fc1c-de38-4a37-9650-2f5bb58b2571)

The link to planetcentricdesign.com is currently broken as the website appears to be down.

There are some links in web archive: https://web.archive.org/web/20240000000000*/planetcentricdesign.com

**Comment by tunetheweb** [comment]
Looks like the link is back.
