### ISSUE TITLE
CSS Issues with Feature Chapter on home Page

### ISSUE THREAD

**Issue by bazzadp** [HTTPArchive/almanac.httparchive.org#375]
**Issue 1**

See this:

![image](https://user-images.githubusercontent.com/10931297/68505218-9b113900-025e-11ea-9957-f5db0386a565.png)

Note the cut-off quote text at the end and missing third stat.

Seems to be fixed by adding this CSS:

```
#home section {
  line-height: 115
}
```

![image](https://user-images.githubusercontent.com/10931297/68505387-f93e1c00-025e-11ea-869e-d7b56f02b6b5.png)

But not sure of other implications of that.

Edit - looks to be due to Contributor Count: https://github.com/HTTPArchive/almanac.httparchive.org/issues/399

**Issue 2**

In mobile view the stats % text should be more centred as looks weird stepped:

![image](https://user-images.githubusercontent.com/10931297/68525492-0f34f680-02ca-11ea-9e50-f05455168047.png)

**Comment by bazzadp** [comment]
Not seeing this now. Did you fix this @rviscomi ? In which case can we close this?

**Comment by bazzadp** [comment]
Though in mobile view the stats % text should be more centred as looks weird stepped:

![image](https://user-images.githubusercontent.com/10931297/68525492-0f34f680-02ca-11ea-9e50-f05455168047.png)

**Comment by rviscomi** [comment]
No I didn't work on this. Not sure if anyone did. But let's leave this issue open to fix the alignment issue you found.

**Comment by rviscomi** [comment]
Fixed by https://github.com/HTTPArchive/almanac.httparchive.org/commit/6b94bafa32520537d401a937dddc78e91a5b3e5b
