### ISSUE TITLE
Add keyboard shortcuts for previous/next chapter

### ISSUE THREAD

**Issue by rviscomi** [HTTPArchive/almanac.httparchive.org#377]
Not launch blocking.

It would be nice to be able to "page" through the chapters using keyboard shortcuts and not have to scroll to the bottom of the page for the prev/next links.

I was thinking of using either the "p" and "n" keys or "," and "." (< and >). We should also make these shortcuts discoverable somehow, ideally, for both accessibility and convenience.

**Comment by arsenicraghav** [comment]
Hi.. wanted to work on this one but not sure how to run/load the project, have cloned the repo and went through README.md. Thanks

**Comment by bazzadp** [comment]
> Hi.. wanted to work on this one but not sure how to run/load the project, have cloned the repo and went through README.md. Thanks

Did you get all the way through the README? Can you run `python main.py` from the src directory and then see the website at http://127.0.0.1:8080 ?

**Comment by arsenicraghav** [comment]
Can you assign this one to me ?

**Comment by bazzadp** [comment]
Done. Remember to add yourself as a developer to the `src/config/2019.json` as part of your first PR so you’ll appear as a contributor on the website!
