### ISSUE TITLE
Sync contributors

### ISSUE THREAD

**Issue by rviscomi** [HTTPArchive/almanac.httparchive.org#378]
The [list of contributors](https://docs.google.com/spreadsheets/d/1LR29JpI2XJSjan_z6uP1YpRy4EYYivYZPqCIG-9sfFY/view#gid=770177464) that I maintain seems to be slightly out of sync with 2019.json. We should go through and make sure everyone is getting the credit they deserve.

Three new reviewers I've added (for contributions to the CDN and CSS chapters):
- Patrick Meenan
- Erik Nygren
- Eric A. Meyer

I'm seeing a total of 78 contributors now. But we have 77 contributors in the JSON config, so there seem to be two other people that I wasn't keeping track of. Would be great to cross reference each list to be sure.

**Comment by bazzadp** [comment]
Think I've found them hiding in the Security chapter. Alessandro Ghedini (@ghedo) and André Naumann (@ndrnmnn) were in your Spreadsheet as Security chapter Reviewers but not in JSON.

Will add them to Brainstormers as part of Security chapter copyediting that I'm working on as not sure they'll get a chance to actually review now (though if you do have time this weekend guys then more than happy to take your feedback!).

Below is what I'll add but let me know if any data is missing or incorrect (or either of you on Twitter):

```
    "ghedo": {
      "name": "Alessandro Ghedini",
      "teams": [
        "brainstormers"
      ],
      "avatar_url": "https:\/\/avatars3.githubusercontent.com\/u\/117643?v=4&s=200",
      "website": "https:\/\/ghedini.me\/",
      "github": "ghedo"
    },
    "ndrnmnn": {
      "name": "André Naumann",
      "teams": [
        "brainstormers"
      ],
      "avatar_url": "https:\/\/avatars2.githubusercontent.com\/u\/22891577?v=4&s=200",
      "github": "ndrnmnn"
    }
```

**Comment by rviscomi** [comment]
Those LGTM.

While checking the ancient [brainstorm doc](https://docs.google.com/document/d/1sCIMeErYvaQb5x9Acdb6ImYdn0-buHRhYGvz2HoysmM/edit?usp=sharing) I also found a couple of uncredited brainstormers: Morten (@mor10) and Weston (@westonruter). Could you add them to the config as well?

Erik Nygren joined recently to help review the CDN chapter. @colinbendell could you help me identify which of [these people](https://github.com/search?q=Erik+Nygren&type=Users) he is? Has anyone else helped you with any of your chapters?

**Comment by bazzadp** [comment]
Will do!

**Comment by bazzadp** [comment]
Looks to me like its @enygren so have added these to the change I am working on:

```

    "mor10": {
      "name": "Morten Rand-Hendriksen",
      "teams": [
        "brainstormers"
      ],
      "avatar_url": "https:\/\/avatars3.githubusercontent.com\/u\/1132200?v=4&s=200",
      "website": "http:\/\/mor10.com\/",
      "github": "mor10",
      "twitter": "mor10"
    },
    "westonruter": {
      "name": "Weston Rutern",
      "teams": [
        "brainstormers"
      ],
      "avatar_url": "https:\/\/avatars2.githubusercontent.com\/u\/134745?v=4&s=200",
      "website": "https:\/\/weston.ruter.net\/",
      "github": "westonruter",
      "twitter": "westonruter"
    },
    "enygren": {
      "name": "Erik Nygren",
      "teams": [
        "brainstormers"
      ],
      "avatar_url": "https:\/\/avatars2.githubusercontent.com\/u\/6840678?v=4&s=200",
      "website": "https:\/\/erik.nygren.org\/",
      "github": "enygren",
      "twitter": "akanygren"
    }
```

Let me know if anything's wrong or anything you don't want published here! This is what it will look like: https://almanac.httparchive.org/en/2019/contributors

**Comment by rviscomi** [comment]
@bazzadp were these changes merged? Can we close this?

**Comment by bazzadp** [comment]
No, they are part of https://github.com/HTTPArchive/almanac.httparchive.org/pull/393/. Which I think we should merge as per my comment just there 😀

**Comment by bazzadp** [comment]
Closed with https://github.com/HTTPArchive/almanac.httparchive.org/pull/393
