### ISSUE TITLE
Translate Japanese, Spanish, and Russian

### ISSUE THREAD

**Issue by rviscomi** [HTTPArchive/almanac.httparchive.org#38]
Per #29 and #35, before launch we should translate the Almanac into our P0 languages: Japanese, Spanish, and Russian.

Translation assignments:

Language | Primary Translator | Secondary
-- | -- | --
Japanese | @MSakamaki | _(none)_
Spanish | @c-torres | @taytus @JMPerez
Russian | @Pavel-Evdokimov | _(none)_

If anyone would like to sign up to review/assist translations for any of the three languages, let me know.

**Comment by rviscomi** [comment]
Renaming this issue to unblock the launch on translation. I think it's an overly optimistic target, given that most of the content is still unfinished. It'd be a lot to ask our @HTTPArchive/translators to finish translating 20 chapters plus the methodology/home/chapter/outline pages in a matter of weeks. Does this sound ok?

**Comment by MSakamaki** [comment]
@rviscomi 
Yes, I can started.

**Comment by c-torres** [comment]
I'm OK with this. Wondering if we have any work that can be started?

**Comment by rviscomi** [comment]
Unfortunately we don't have any chapters locked down and guaranteed not to change between now and launch.

**Comment by MSakamaki** [comment]
I cloned the latest repository and tried to verify the `current src/content/en/2019` with gitlocalize.com.

Then, the past verification project disappeared and 500 error occurred during registration.
Sending "contanct us" and waiting for a reply.

If the problem persists, you may need a pull request based translation .
(shar information)

**Comment by rviscomi** [comment]
Oh thanks for checking on that. I agree that PR translation might be the best way forward. In any case, let's not worry about it until we get all 20 chapters written, which probably won't be for a couple of weeks.

**Comment by MSakamaki** [comment]
Thanks reply.
I continuing to verify that the current markdown works without problems on gitlocalize.com.
I will share it if anything happens.

**Comment by rviscomi** [comment]
Two chapters are edited and should be stable enough to start translation: Markup and Performance.

**Comment by MSakamaki** [comment]
Immediately, gitlocalize integration I will start.
I want to register an assigned member as an administrator here.

**Comment by MSakamaki** [comment]
@rviscomi 
An error occurred during integration.
Apparently, auth with an administer account is necessary.
Is it possible to authlization?

![スクリーンショット 2019-11-06 10 40 29](https://user-images.githubusercontent.com/2183053/68261737-6ba6d480-0084-11ea-81b0-247eb96892b8.png)

**Comment by c-torres** [comment]
@MSakamaki I loged in into gitlocalize and linked my account c-torres.

**Comment by JMPerez** [comment]
@c-torres, @taytus are you guys using gitlocalize to translate the content, or will you be sending PRs directly for the content files?

**Comment by c-torres** [comment]
I was thinking on going with gitlocalize but I believe the integration process has not been finished. If that's the case I can start doing manual PRs as it might be faster. 

Do you have any preference @JMPerez?

**Comment by rviscomi** [comment]
I've been getting emails requesting authorization for gitlocalize to integrate with our repo and I've been accepting them. Not sure what the issue is if any.

**Comment by c-torres** [comment]
@rviscomi Performance and Markup chapters, and the Table of Contents template have been translated into Spanish. Please let us know which others sections should be ready for translation by now. Thanks!

**Comment by rviscomi** [comment]
Other chapters are changing slightly as we approach launch day on Monday. After that we should be in a more stable place to start translating other content.

One worry I have is that after launch with so many eyes on the chapters, people will point out typos we missed, so the content would actually be churning frequently, making it hard for translation to keep up. Generally, we do need a process for ensuring that every content change propagates to all of the translations.

**Comment by MSakamaki** [comment]
I'm sorry, I was proceeding with the integration of gitlocalize, but I understood that it can only be integrated by the repository owner.

Can @rviscomi  do gitlocalize integration?
If it seems difficult, I would like to work on translation of the pull request.

I also start pull request translation.

**Comment by rviscomi** [comment]
@MSakamaki Per https://github.com/HTTPArchive/almanac.httparchive.org/issues/38#issuecomment-552058045 I've accepted all of the requests to integrate, not sure what else I can do. Let's start with PR translations to get this moving.

**Comment by rviscomi** [comment]
@HTTPArchive/translators I've been thinking about how we can effectively translate the content and keep it in sync with all of the other web dev and editing work that's happening simultaneously.

Most of the editing is done, per #218. There are still a few chapters that are in flux. My goal is to wrap that up this week.

There is still a lot of development work being done. My worry is that it will become a nightmare to keep `templates/en` changes in sync with other `templates/<lang>` files. Developers shouldn't have to replicate a simple HTML fix in 3+ almost identical files. We need a better technical solution for separating the translatable content from the structure of the page. I don't have a good answer to this yet.

I think the highest priority is to translate the contents of the chapters. Rather than blocking the launch of a new language on the entire website being translated, let's roll out chapter-specific translations as they're completed. We'll need a chapter-specific widget to toggle between languages.

And now that we're already launched, I'd say that all languages are equally important. I don't think we should limit ourselves to "P0 languages" like Japanese, Spanish, and Russian. If translators have the bandwidth to work on Italian, let's roll that out when ready.

Even though the chapter contents are _mostly_ finalized, there will still be occasional issues discovered and fixed. We'll need a process for marking that as requiring a new translation. I'll think about this, but open to ideas.

How does all this sound?

**Comment by MSakamaki** [comment]
I'll think we that there is something to gain from the others translation project I have seen.
This is not a method of using third-party tools, but is covered by github operation.

In my experience, a successful translation is a clone of the repository.

Angular
https://github.com/angular/angular-ja

Even if html is included, it seems to absorb changes.
However, this requires technique and is heavy to deploy and refurbish.

I also feel the possibility of cloning the repository from a long-term perspective, but I like to see only the changes as it is because the project has the basics of translation.

I am working on this. By taking the git hash and comparing the differences as follows, I can extract only the differences that have changed since translation. (This idea was received from https://github.com/nrwl/nx).
If you have a mechanism to notify this by ci such as github actions, you can notify the contents and the differences that are out of date.

ex. 
```sh
// Japanese
git diff `git log --pretty=format:"%h" --no-patch ./src/content/ja/2019/markup.md` `git rev-parse HEAD` ./src/content/en/2019/markup.md

// Spanish
git diff `git log --pretty=format:"%h" --no-patch ./src/content/es/2019/markup.md` `git rev-parse HEAD` ./src/content/en/2019/markup.md
```

Note: This idea is just a hash difference of the file from the previous time, so it is necessary to complete the translation of one file every time.

This content is so wonderful that I would like many people to read it.
I will continue to focus on Japanese translation.

**Comment by bazzadp** [comment]
@HTTPArchive/translators can you have a read of https://github.com/HTTPArchive/almanac.httparchive.org/issues/507 and add your names to the meta data when translating chapters?

Translators go in the translated chapter markdown and not the base English chapter markdown.

Let me know if any questions!

Barry

**Comment by bazzadp** [comment]
All did we end up giving up on gitlocalize or are we still using it? Not familiar with it or what it does, but other translators coming on board now (see https://github.com/HTTPArchive/almanac.httparchive.org/issues/539 and https://github.com/HTTPArchive/almanac.httparchive.org/issues/540) so wondering what advice to give them to get them started.

**Comment by SilentJMA** [comment]
> All did we end up giving up on gitlocalize or are we still using it? Not familiar with it or what it does, but other translators coming on board now (see #539 and #540) so wondering what advice to give them to get them started.

Can you please advice me before i get started on #539 & #540  ?

**Comment by c-torres** [comment]
For Spanish, we have been working with manual PR so far.

**Comment by SilentJMA** [comment]
> manual PR

okay i will be using it manual

**Comment by bazzadp** [comment]
Closing this as being tracked in separate issues now: #586 , #498 and #587
