### ISSUE TITLE
Heavy images

### ISSUE THREAD

**Issue by AymenLoukil** [HTTPArchive/almanac.httparchive.org#380]
These images are sized over 100 KB

https://almanac.httparchive.org/static/images/home-hero.png
https://almanac.httparchive.org/static/images/home-hero-2019.png
https://almanac.httparchive.org/static/images/methodology-banner.png
https://almanac.httparchive.org/static/images/2019/07_Performance/nav-timing.png
https://almanac.httparchive.org/static/images/2019/14_CMS/cms-logos.png
https://almanac.httparchive.org/static/images/2019/12_Mobile_Web/example-of-a-site-shifting-content-while-it-loads-lookzook.gif
https://almanac.httparchive.org/static/images/2019/03_Markup/element_categories.png
https://almanac.httparchive.org/static/images/2019/18_Page_Weight/ch18_fig2_conversion_graph.png
https://almanac.httparchive.org/static/images/2019/18_Page_Weight/ch18_fig3_gif_cdf.png
https://almanac.httparchive.org/static/images/2019/16_Caching/ch16_fig8_resource_age.jpg
https://almanac.httparchive.org/static/images/2019/16_Caching/ch16_fig13_cookies_on_cacheable_responses.jpg
https://almanac.httparchive.org/static/images/2019/16_Caching/ch16_fig15_lighthouse_example.jpg

**Comment by rviscomi** [comment]
Good catch. Even if the Calibre tool minifies the file size, the images themselves may be too big.

**Comment by AymenLoukil** [comment]
> Good catch. Even if the Calibre tool minifies the file size, the images themselves may be too big.

Yes. Should resize

**Comment by hyperpress** [comment]
I've got this one over on #141. Will be finishing that up tomorrow latest.

**Comment by bazzadp** [comment]
I think 100 KB is a bit strict.

The only ones I'm worried about are:

- https://almanac.httparchive.org/static/images/methodology-banner.png - 403Kb. I've got that down to 152 KB but it is a big image so I'm fine with that.
- https://almanac.httparchive.org/static/images/2019/18_Page_Weight/ch18_fig2_conversion_graph.png - 1.3 MB!!! And the irony that this is an image for the page-weight chapter is apparently lost on us all 😀Got it down to 35 KB!!!!

Will submit these as a PR and then OK to close out this issue or really think we should look at the rest?
