### ISSUE TITLE
BibTex box misses spaces around author names

### ISSUE THREAD

**Issue by JannisBush** [HTTPArchive/almanac.httparchive.org#3852]
The addition of the bibtex box is great but it seems to be missing some spaces here: https://github.com/HTTPArchive/almanac.httparchive.org/blob/dcddcc89ddb30b9511fbabfb06d0cfbd6d9ad282/src/templates/base/base_chapter.html#L351

At least at the staging environment it currently looks like this (missing spaces around and):
![Image](https://github.com/user-attachments/assets/b6df3247-648f-4701-9e20-71d7c95c55e6)

**Comment by nrllh** [comment]
Thank you for the report! Yes, we should will fix it. We also need to add all contributors, as they are part of the chapter.

**Comment by SaptakS** [comment]
Working on this.

**Comment by SaptakS** [comment]
Seems like @tunetheweb already fixed it.

**Comment by tunetheweb** [comment]
Yeah some languages (Japanese, Chinese) don't use spaces around "and", so I moved that out of the templates (but forgot to add into the block!). Fixed now.
