### ISSUE TITLE
Issue with chart on the 2024 cms chapter

### ISSUE THREAD

**Issue by adamsilverstein** [HTTPArchive/almanac.httparchive.org#3865]
I noticed the dates in the table are formatted as percentages: 

https://almanac.httparchive.org/en/2024/cms#top-5-cms-adoption-growth

![Image](https://github.com/user-attachments/assets/a8c9e2b0-1f15-4372-bf26-6b7b5c116de0)

**Comment by tunetheweb** [comment]
Oops. Fixed for desktop. Will retake the images for mobile and release.

**Comment by tunetheweb** [comment]
Actually looks like image was fine so this is fixed.
