### ISSUE TITLE
Generate TOC using localized markdown

### ISSUE THREAD

**Issue by rviscomi** [HTTPArchive/almanac.httparchive.org#398]
As noted in https://github.com/HTTPArchive/almanac.httparchive.org/pull/387#issue-338953011 the Table of Contents is English-only due to the reliance on the global 2019.json config. We should rewire this to be dependent on the `content/<lang>/*` chapter markdown.

When we generate the markup at compile time, the JSON metadata for each chapter should also be merged into a single language-specific config file. That way the TOC page can generate a language-specific index for each chapter.

**Comment by bazzadp** [comment]
As per https://github.com/HTTPArchive/almanac.httparchive.org/issues/568#issuecomment-559600995 I wonder if we could use a [lookup table](https://stackoverflow.com/questions/18670606/how-to-use-a-lookup-table-in-jinja) in the language specific templates with fallback to English if a language-specific lookup doesn't exist? Might avoid the JSON config getting unwieldy...
