### ISSUE TITLE
Home page contributor count style bug

### ISSUE THREAD

**Issue by rviscomi** [HTTPArchive/almanac.httparchive.org#399]
The contributor count on the home page is not styled correctly and mispositioned on the page, overlapping with the featured chapter section:

![image](https://user-images.githubusercontent.com/1120896/68535246-3a344000-02f4-11ea-9219-3b61b787169a.png)

This might be a side-effect of the contributor count being dynamic and not designed for this particular width value.

cc @bazzadp I think this is similar to what you saw that one time.
cc @HTTPArchive/developers

**Comment by bazzadp** [comment]
Yes you are right. This is the cause of the initial reason for https://github.com/HTTPArchive/almanac.httparchive.org/issues/375 (though though added a second issue to that after). Thought it was an issue with featured chapter, but it's actually the contributor count which is causing the issue.

**Comment by mikegeyser** [comment]
I'll take a look at this. I don't have access to the screen mockups, would it be possible to post a screenshot of what it should ideally look like?

**Comment by rviscomi** [comment]
Mockup:

![image](https://user-images.githubusercontent.com/1120896/68541759-29b5b100-0358-11ea-911e-4affa56dbea6.png)

**Comment by bazzadp** [comment]
See also here where People was discussed: https://github.com/HTTPArchive/almanac.httparchive.org/issues/106#issuecomment-540659009

**Comment by bazzadp** [comment]
> Note that we got rid of the "PEOPLE"

Oh see you beat me to it with an edit @rviscomi !
