### ISSUE TITLE
Validate chapters by year

### ISSUE THREAD

**Issue by rviscomi** [HTTPArchive/almanac.httparchive.org#400]
As a follow-up to #392, we shouldn't hardcode the list of chapters. It should support any given year and pull the chapter IDs from the config.

**Comment by arsenicraghav** [comment]
Is this being worked on by someone ?

**Comment by bazzadp** [comment]
> Is this being worked on by someone ?

Nope, not had a chance to look at it yet - go for it!

**Comment by arsenicraghav** [comment]
Sure! I will give it a shot. can you assign it ?

**Comment by bazzadp** [comment]
> can you assign it ?

Are you not able to grab it yourself by clicking on the "assign yourself" link?

![image](https://user-images.githubusercontent.com/10931297/69609023-8aafdb00-1020-11ea-8cce-1ff7ff728681.png)

**Comment by arsenicraghav** [comment]
No, I don't think so. I don't see an option.

**Comment by rviscomi** [comment]
Need to add @arsenicraghav to the GitHub Almanac team for them to be assignable

**Comment by bazzadp** [comment]
> Need to add @arsenicraghav to the GitHub Almanac team for them to be assignable

Well we should add him to there anyway. And to developers. Can you permission me to be able to do that?

However I am able to assign him. So not convinced he _needs_ to be in there. But then that could be cause of my permissions and I can assign anyone? So not sure if it's a permission thing or a UX thing - I think assigning issues in GitHub isn't the most obvious UX and is easily missed!

**Comment by arsenicraghav** [comment]
>pull the chapter IDs from the config.

@rviscomi  do you mean to say from an existing config file ?

**Comment by rviscomi** [comment]
Yes, see 2019.json https://github.com/HTTPArchive/almanac.httparchive.org/blob/master/src/config/2019.json

**Comment by bazzadp** [comment]
> Yes, see 2019.json https://github.com/HTTPArchive/almanac.httparchive.org/blob/master/src/config/2019.json

He's already done that as part of #541 .

Think he's asking how he can get access to assign items himself. Just confirmed people in the team can't assign issues to themselves. Can we permission him to be able to do that without full permissions for the repo if we want to keep that locked down a bit for now?

**Comment by rviscomi** [comment]
I've just given @bazzadp @obto and @mikegeyser permission to add members to the [Almanac Contributors team](https://github.com/orgs/HTTPArchive/teams/almanac-contributors) and sent @arsenicraghav an invitation to join the Developers subteam.

**Comment by bazzadp** [comment]
> I've just given @bazzadp @obto and @mikegeyser permission to add members to the [Almanac Contributors team](https://github.com/orgs/HTTPArchive/teams/almanac-contributors) and sent @arsenicraghav an invitation to join the Developers subteam.

I can't seem to invite new people :-( Am I doing something stupid?

![image](https://user-images.githubusercontent.com/10931297/69717459-0171d480-1104-11ea-889b-f43d061ffaf2.png)

Also don't have permission to add people to sub-teams.

**Comment by rviscomi** [comment]
That's weird, I don't know why you wouldn't be able to add new members.

![image](https://user-images.githubusercontent.com/1120896/69718788-2b63d080-10dd-11ea-88c6-f74848721157.png)

I've also given you maintainer role on the Developers subteam. Maybe that helps?

**Comment by bazzadp** [comment]
No still can only move people around that are already part of HTTPArchive org.

So I can add anoblet to Alamanac Contributors or Developers as he's part of HTTP Archive Developers, but I can't add people to Almanac who are completely new (like SilentJMA).

**Comment by rviscomi** [comment]
Ok. There's also a way for people to request to join a team, I think we should try that instead.

**Comment by rviscomi** [comment]
@arsenicraghav any update on this?

**Comment by bazzadp** [comment]
We asked @arsenicraghav to pause working on this in https://github.com/HTTPArchive/almanac.httparchive.org/pull/557#issuecomment-559807009 until we'd figured out #561 - which we haven't figured out yet! 😀

**Comment by rviscomi** [comment]
Thanks for the reminder :sweat_smile:
