### ISSUE TITLE
Add ja-JP templates

### ISSUE THREAD

**Issue by rviscomi** [HTTPArchive/almanac.httparchive.org#42]
We should test out the i18n routing by creating a Japanese translation of the "coming soon" home page and serve it from https://almanac.httparchive.org/ja-JP/.

- [x] translate the coming soon page to Japanese
- [x] route /ja-JP/ to the Japanese index template (#43)

@MSakamaki can you manually translate the [English version](https://github.com/HTTPArchive/almanac.httparchive.org/blob/master/src/templates/en-US/index.html) and add it to a new ja-JP template directory?

When that's done I can help with the next two items.

cc @HTTPArchive/translators

**Comment by MSakamaki** [comment]
> translate the coming soon page to Japanese

Yes, I can help.
work will be start as soon as #41 is merged into master branch to avoid conflicts.

**Comment by rviscomi** [comment]
Great, #41 is merged now

**Comment by MSakamaki** [comment]
@rviscomi 
Now looks like a mixed of part/chapter/section.
This will cause some confusion in the translation.

It is "Section -> Chapter" in [brainstorming documents](https://docs.google.com/document/d/1sCIMeErYvaQb5x9Acdb6ImYdn0-buHRhYGvz2HoysmM/edit#) and [coming soon page](https://almanac.httparchive.org/).

In issues #2 it is "Part -> Chapter".

What will it be in the future?
(This effect the translation of Section and Chapter a little)

In the case of LaTeX, it is "Part => Chapter", may by help to translation.
https://www.overleaf.com/learn/latex/Sections_and_chapters#Document_Sectioning

**Comment by rviscomi** [comment]
Yeah let's go with Part > Chapter > Section in increasing order of specificity, like LaTeX. Good catch.

**Comment by MSakamaki** [comment]
The translation according to current index.html is supported with # 44.
I think fix my translation when modifying English index.html

**Comment by rviscomi** [comment]
Sounds good. Merged.
