### ISSUE TITLE
Fallback when Google Sheets is not available

### ISSUE THREAD

**Issue by bazzadp** [HTTPArchive/almanac.httparchive.org#428]
Some companies (including my employer!) block Google Sheets for various reasons. Not sure if some countries do this similarly.

As we have fall back graphics for mobile, it would be nice if we could run a bit of JavaScript on a page to check for that blocking, and then hide the iframes and unhide the images.

**Comment by rviscomi** [comment]
Yeah if the iframes take too long to load for any reason (blocked, latency, outage) we should fall back to the static images.

**Comment by bazzadp** [comment]
BTW I think this should be in [SHIP-IT] milestone (https://github.com/HTTPArchive/almanac.httparchive.org/milestone/5) and not [Apres-Ski](https://github.com/HTTPArchive/almanac.httparchive.org/milestone/6). A non-trivial number of users will not be getting visuals. Hence why I've prioritised this.
