### ISSUE TITLE
pmeenan missing from Contributors

### ISSUE THREAD

**Issue by rviscomi** [HTTPArchive/almanac.httparchive.org#433]
@pmeenan's full name is not showing up on the CDN chapter for which he's a reviewer and he has no entry on the Contributors page.

![image](https://user-images.githubusercontent.com/1120896/68551517-8fd71e00-03c2-11ea-8c58-b99f1ed88d3b.png)

**Comment by bazzadp** [comment]
I'll fix.

Another question. Data Visualisation - is that a team? Should I add the three of you to a new team? Or add @paulcalvano to Editors (you other two are already in there)? Or are they covered by being in Analysts?

**Comment by rviscomi** [comment]
I consider data viz part of development. Not strictly opposed to a new team but everyone who'd be in it is already represented somewhere else so it may be superfluous.

If @paulcalvano edited any chapters (I don't recall, everything is a blur) then yeah he can be added to the team. If he revised his own chapters' drafts, that's just being an author IMO ;)

**Comment by bazzadp** [comment]
> If @paulcalvano edited any chapters (I don't recall, everything is a blur) then yeah he can be added to the team. If he revised his own chapters' drafts, that's just being an author IMO ;)

No it was more if we considered adding Data Viz as part fo the Editing process. Cause he's not currently an editor. He's not in Development team either but personally I think it's best being part of Analysts (which you all already are) if not a separate team.

**Comment by rviscomi** [comment]
Hell, throw him on the developers team 😁

**Comment by bazzadp** [comment]
This OK for pmeenan? Got all his teams?

```
    "pmeenan": {
      "name": "Patrick Meenan",
      "teams": [
        "brainstormers",
        "reviewers"
      ],
      "avatar_url": "https:\/\/avatars0.githubusercontent.com\/u\/444165?v=4&s=200",
      "website": "https:\/\/www.webpagetest.org\/",
      "github": "pmeenan",
      "twitter": "patmeenan"
    }
```

**Comment by rviscomi** [comment]
LGTM

**Comment by bazzadp** [comment]
![image](https://user-images.githubusercontent.com/10931297/68551857-d8b1c580-0408-11ea-99c6-742bd63674c7.png)
