### ISSUE TITLE
HTML validation errors on Home Page

### ISSUE THREAD

**Issue by bazzadp** [HTTPArchive/almanac.httparchive.org#439]
Similar to https://github.com/HTTPArchive/almanac.httparchive.org/issues/309 index.html has the following:

- line 167 - `<h1><div class="alt-bg decorative-line"></div>`
- line 184 - `<h2><div class="decorative-line-center"></div>`
- line 221 - `<h2><div class="decorative-line"></div>`
- line 228 - `<h2><div class="decorative-line-center"></div>`

Divs are not allowed in heading tags. Tried a few fixes but decided to leave to someone with better CSS than me!

Also the following `<img>` tags could do with `alt=""` properties (assuming we're happy with that as these are just decorative): 

- line 221 - character-markup.png
- line 222 - character-star.png
- line 223 - character-hat.png

**Comment by catalinred** [comment]
@bazzadp An easy validation fix would be to transform `<div class="decorative-line-center">` into `<span class="alt-bg decorative-line"></span>` and then add `display: block` to the `selector`. This way we could avoid any potential new issue without rewriting the  `.decorative-line`.

Alternatively, we could rewrite the `.decorative-line` to use CSS pseudo-elements instead. Either way, I could help with this.

**Comment by rviscomi** [comment]
The decorative line is a vestige of an earlier style implementation. I rewrote it on the chapter/methodology/TOC pages but didn't realize we're still using it on the home page. We should be able to do this style entirely in CSS without the need for additional markup.

**Comment by catalinred** [comment]
> The decorative line is a vestige of an earlier style implementation. I rewrote it on the chapter/methodology/TOC pages but didn't realize we're still using it on the home page. We should be able to do this style entirely in CSS without the need for additional markup.

If that's ok, you could assign me to merge the chapter/methodology/TOC  `.title` and index/homepage's `.decorative-line`.

I'll also add `alt=""` as @bazzadp suggested above for the decorative images/
