### ISSUE TITLE
Some figures and markdown links not rendering on mobile

### ISSUE THREAD

**Issue by obto** [HTTPArchive/almanac.httparchive.org#446]
Was checking out the mobile web chapter on my phone and noticed three things:

1. The linked youtube video in the mobile web chapter doesnt display 
![image](https://user-images.githubusercontent.com/684747/68563084-51ad1f00-0401-11ea-8794-a23031768672.png)

2. Some markdown links are not rendering 
![image](https://user-images.githubusercontent.com/684747/68563065-3f32e580-0401-11ea-9018-bf5453bcd16b.png)

3. No images of the data viz are displaying (taken from a11y chapter): 
![image](https://user-images.githubusercontent.com/684747/68563129-80c39080-0401-11ea-91c7-c071227c7158.png)

I assume a lot of these are known issues, but wanted to document them in case one of these was not known.

**Comment by rviscomi** [comment]
Are you on an iPhone? Related: https://github.com/HTTPArchive/almanac.httparchive.org/issues/369

**Comment by obto** [comment]
Was on my pixel 3 when i noticed the issues, but took those screenshots in the mobile emulator in chrome

**Comment by rviscomi** [comment]
Ok I can reproduce the issue. I'll work on a fix. Thanks for reporting it!

**Comment by obto** [comment]
Np, sorry to be that guy haha

**Comment by rviscomi** [comment]
Don't be sorry, it's a good catch!

**Comment by obto** [comment]
The mobile chapter is working now, but others like the A11Y chapter are still missing their figures.

**Comment by rviscomi** [comment]
Ah missed that one. Thanks for verifying. Fixing now.

**Comment by obto** [comment]
Yup looks good. Only remaining issue I see is some figures don't have data
annotations, so you can't see the actual values. Like figure 2 on
https://almanac.httparchive.org/en/2019/compression

**Comment by rviscomi** [comment]
That's a good point. Without interactivity it's difficult/impossible to grasp some of the values. Let's tackle this in a separate issue.
