### ISSUE TITLE
Optimize Twitter share card

### ISSUE THREAD

**Issue by rviscomi** [HTTPArchive/almanac.httparchive.org#449]
The hero image and text get cut off. Might be good to optimize the metadata for this use case.

![image](https://user-images.githubusercontent.com/1120896/68567000-c5085e00-040c-11ea-9d7d-7f43a26f0a02.png)

The hero image could be the one without "2019" and resized to fit better in the Twitter card
The title could be simplified to "The 2019 Web Almanac"
The description could be made less redundant to: "HTTP Archive's annual state of the web report combining[...]"

**Comment by bazzadp** [comment]
I knew this would be helpful later: https://github.com/HTTPArchive/almanac.httparchive.org/pull/371#issuecomment-551936027 😀

**Comment by bazzadp** [comment]
FYI running the page through the [Twitter Card Validator](https://cards-dev.twitter.com/validator) has refreshed Twitter’s cache.
