### ISSUE TITLE
Improve index sidebar styles

### ISSUE THREAD

**Issue by rviscomi** [HTTPArchive/almanac.httparchive.org#454]
Carrying over a few feature requests from #224. For pages with an index sidebar (chapter and methodology templates):

- [ ] make the index sticky on desktop so it's visible while scrolling (max-height 100% and overflow-y scroll)
- [ ] as the page is scrolled, update the "active" index item with a green highlight (using IntersectionObserver)

The "active" style is already implemented, we just have to apply the class name at the right time using JS.

cc @HTTPArchive/developers

**Comment by catalinred** [comment]
I might be able to help out with this.

**Comment by catalinred** [comment]
I'm on a  4k 3840x2160 px display at work and even at this size, it would be so hard to make that floating box both sticky and useful, in terms of UX. 

Before making it sticky and deciding to add extra JS lines on IntersectionObserver, I'd suggest shrinking its height first, so the UX to be effective when applying the `active` class to its list elements.

### The current height for the floating sidebar box:
![floating-box](https://user-images.githubusercontent.com/1867900/69241971-94f95180-0ba8-11ea-9dea-63a9e70e9390.png)

### Here's an updated & shrunk version
The below is supposed to be more effective in terms of UX when it comes to scrolling and update of the current active state
![floating-box-updated](https://user-images.githubusercontent.com/1867900/69242427-7fd0f280-0ba9-11ea-874c-d6bb8b702ea2.png)

What do you think?
Hope the above makes sense :)

**Comment by rviscomi** [comment]
IIUC you're suggesting reducing the padding of the list items in the index. If possible I'd like to find  a way to keep the index contents styled as they are, but affix the container so it doesn't move away when scrolling. For small viewports or large lists of contents, the index should be no more than 100% of the viewport height, so it too vertically scrolls.

When scrolling through the chapter, we can scroll to the relevant heading in the index and apply the `active` class so it's always visible to the reader.

**Comment by bazzadp** [comment]
I had a go at this in #732 

Also deployed a test site if you want to have a play with it: https://20200414t004714-dot-webalmanac.uk.r.appspot.com

**Comment by bazzadp** [comment]
Actually just realised you already had a style so used that instead. New test site: https://20200414t005510-dot-webalmanac.uk.r.appspot.com

**Comment by bazzadp** [comment]
Third times a charm. Got a better way to do it after sleeping on it: https://20200414t081104-dot-webalmanac.uk.r.appspot.com
