### ISSUE TITLE
Typos, typos, typos

### ISSUE THREAD

**Issue by bazzadp** [HTTPArchive/almanac.httparchive.org#460]
This is a cool tool that crawls your site looking for typos (inc British spelling): https://www.internetmarketingninjas.com/online-spell-checker.php

Type in the base URL: https://almanac.httparchive.org/en/2019/
And crawl up to 100 links.

Below is a set of Words to Ignore (might want to commit this to git?).

These are the possible typos it's found and many look like they do need fixing:

![image](https://user-images.githubusercontent.com/10931297/68577356-d6328880-0467-11ea-83c4-64362511eb26.png)

I've run out of time to continue looking at this for now, but will have a look after work if no one's picked it up in the meantime.

**Ignore word list:**

accesskey
activeview
admin
alankent
amsterdam
andydavies
antipatterns
apps
argyleink
arturjanc
async
autocomplete
autoplay
autoplaying
backend
badssl
basehref
bendell
bootstrapcdn
brotli
bufferbloat
bulktest
cacheable
cacheability
cdnjs
charset
clickjacking
cloudflare
cloudinary
codebase
codelabs
colinbendell
columnheader
conf
contentinfo777777
cowpaths
crawlability
crawlable
crossorigin
cryptocurrency
csscriptdict
cufon
cufontext
currentcolor
cwebp
darkgray
datacenter
datalist
datamine
deprioritize
detectible
doubleclick
dougsillars
ebay
ecommerce
endlock
eval
fallback
favicon
fbevents
filesize
flexbox
frontend
geolocation
geos
gifs
github
google
googleads
googleadservices
googleapis
googletagservices
gstatic
gunicorn
gzip
hackathon
hostname
hostnames
href
hreflang
htaccess
httparchive
iarc
iframe
iframes
inbox
indexability
inline
inlining
installability
interoperable
jank
javascript
jdiv
jeffy
jpegs
jquery
json
kbytes
keyframe
keyframes
lang
leaderboards
lightgray
linux
maxage
meetup
meetups
metadata
microsites
middleboxes
mozilla
namespace
namespaces
namespacing
nginx
nocache
noindex
nopush
nosniff
notificationclick
notificationclose
obscuresite
offline
offscreen
olark
onload
openresty
opensans
opsz
outlier
outsized
pagead
paywalls
paulcalvano
pclass
performant
permalink
plugin
plugins
plusone
pngs
podcast
popups
posinset
precached
preconnect
preconnecting
precompress
precompressed
precompression
prefetch
prefetching
preload
preloading
prerender
prioritization
proxying
queryable
readible
repurposed
roboto
rollout
rowheader
safelist
sameorigin
scotthelme
screenshot
screenshots
searchbox
securityheaders
serviceworker
setsize
sharding
shoesbycolin
shopify
sitelinks
slategray
smartphones
snuck
spriting
srcset
ssllabs
staticxx
stylesheet
stylesheets
subdomains
subpar
subresource
subresources
subsampling
tailwindcss
terabytes
textarea
textbox
timeline
timeseries
timestamp
tomayac
tunetheweb
uber
unsecurely
uptick
userland
versioned
viewport
viewports
vmax
vmin
wdth
webdotdev
webinars
webm
webp
wght
whitelist
whitelisted
whitelisting
whitelists
woff
workflows
ymaps
youtube
yvoschaap

**Comment by bazzadp** [comment]
Also "making migration to HTTP easier." in security chapter, should be "making migration to ~~HTTP~~ **HTTPS** easier".

**Comment by rviscomi** [comment]
Below http://127.0.0.1:8080/en/2019/javascript#fig-17 there is an incomplete sentence:

> Atomics (0.38%) and SharedArrayBuffer (0.20%) are barely visible on this chart since they are used on such few pages. Each of the other APIs here
