### ISSUE TITLE
Missing youtube video in Mobile Web chapter

### ISSUE THREAD

**Issue by obto** [HTTPArchive/almanac.httparchive.org#464]
The youtube video shows up on mobile devices but not desktops: 
![image](https://user-images.githubusercontent.com/684747/68608571-201b6e80-0468-11ea-9326-9d0892bc6c18.png)

**Comment by rviscomi** [comment]
Fixed by https://github.com/HTTPArchive/almanac.httparchive.org/commit/7f5b00bf76fcf89f642308fab2e9d90667889dd3
