### ISSUE TITLE
Home page text contrast issue on mobile when zoomed

### ISSUE THREAD

**Issue by rviscomi** [HTTPArchive/almanac.httparchive.org#470]
Got this UX issue in a DM:

![image](https://user-images.githubusercontent.com/1120896/68620289-06872080-0482-11ea-9681-8bdf69f62c4a.png)

The user is on a mobile device with the page zoomed in.

cc #303

**Comment by catalinred** [comment]
cc https://github.com/HTTPArchive/almanac.httparchive.org/issues/413#issuecomment-552175467 as well

Curious about how to reproduce the above zoomed in behavior.

**Comment by rviscomi** [comment]
Yeah I wasn't able to reproduce this in Dev Tools.

**Comment by catalinred** [comment]
> Yeah I wasn't able to reproduce this in Dev Tools.

Me neither, I tried on my iPhone as well. At first sight, I thought it might be an iOS text size setting but no.

**Comment by rviscomi** [comment]
It seems the OS-level magnification settings need to be configured to 160% to trigger this bug.

![image](https://user-images.githubusercontent.com/1120896/68812874-fbbac000-0628-11ea-847f-b1699f9dce36.png)

**Comment by catalinred** [comment]
In case it helps, I did try text scaling on iOS and wasn't able to reproduce this behavior, the above screenshot looks like is taken on an Android phone.

Either way, IMO this issue is due to the fact that the main background image `intro-background-fit.png` is set on the body and not on the HTML element that wraps the above text and button, e.g. `<section class="intro-container">`.  Related to #485

**Comment by rviscomi** [comment]
Yeah, I think one of the reasons for doing it this way is because it also needs to appear behind the `<header>`.

**Comment by mikegeyser** [comment]
They are definitely related, but even if it was set on the `intro-container` it would still cut off the text, wouldn't it? Because the header image is set to a fixed `background-height`.

**Comment by catalinred** [comment]
@rviscomi yes, technically the current header content and intro-container should be wrapped together in HTML to apply that background somehow, therefore to avoid zooming issues.

@mikegeyser those ‘background-size’ hardcoded px unit values are indeed part of the issue. 

Will try to work on a solution tomorrow (I’m on EET timezone) and keep you updated.

**Comment by rviscomi** [comment]
Related #512
