### ISSUE TITLE
cannot found <pclass="ddc-font-size-large"> link of chapter 3 markup

### ISSUE THREAD

**Issue by MSakamaki** [HTTPArchive/almanac.httparchive.org#475]
[Products (and libraries) and their custom markup](https://almanac.httparchive.org/en/2019/markup#products-and-libraries-and-their-custom-markup) in Chapter 3, cannot found `<pclass = "ddc-font-size-large">`  link destination.

I see `Cannot GET /permalink/3214f840b6ae3ef1074291f60fa1be4b9d9df401fe0190bfaff4bb078c8614a5.html`.

**Comment by bazzadp** [comment]
Related: https://github.com/HTTPArchive/almanac.httparchive.org/issues/452#issuecomment-552357511

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by rviscomi** [comment]
Thank you @MSakamaki! We're tracking this in #452 so I'll close this one as a duplicate.
