### ISSUE TITLE
Upgrade App Engine environment to Python 3

### ISSUE THREAD

**Issue by anoblet** [HTTPArchive/almanac.httparchive.org#48]
Does it make sense to upgrade to Python 3 as early as possible?

**Comment by rviscomi** [comment]
It wouldn't be a bad idea before we write too much 2.7 code. Let me think about it.

**Comment by rviscomi** [comment]
Yeah I think we should commit to 3 now. Especially given that this can become a multi-year project and 2 is being deprecated next year, we don't want to fall behind.

**Comment by anoblet** [comment]
Is updating app.yaml the only thing left to do? I don't have much experience with Python/Flask and don't want to break anything.

**Comment by rviscomi** [comment]
Everyone must also upgrade their local development environment to Python 3 to simulate the production environment..

1. Go to https://www.python.org/downloads/
2. Download and install 3.7.x
3. Run `python3 --version` to verify that it works

@anoblet Our scripts should also switch to using the explicit `python3` command rather than `python`.

**Comment by anoblet** [comment]
For me, scripts defaulted to 3 (I guess because it was the first version I installed) I needed to specify -p in virtualenv to use python 2. I'm not sure I know the difference between a standard/flexible environment and might need a little time to understand the differences.

**Comment by anoblet** [comment]
The only difference I can find between the current (flex) codebase and the standard codebase are the
```
env: flex
- url: /.*
  script: auto
```

**Comment by rviscomi** [comment]
We change this:

```yaml
runtime: python
env: flex
runtime_config:
  python_version: 3
```

to this:

```yaml
runtime: python37
```
