### ISSUE TITLE
Fix Table of Contents margin

### ISSUE THREAD

**Issue by rviscomi** [HTTPArchive/almanac.httparchive.org#480]
The margin on the TOC page is not consistent with other pages. The main section of the page should always be as wide as the header.

![image](https://user-images.githubusercontent.com/1120896/68694779-a4382980-052e-11ea-9c26-5e65c8162658.png)

**Comment by catalinred** [comment]
What is the desired result on the main menu pages, in terms of `width` and alignment?

Right now, the Methodology page has `article.main {max-width: 1324px}` and both Table of Contents & Contributors rely on using the following CSS rule `.content, section.main { max-width: 1024px}`

---

Also, in terms of overall UI, compared to the index page where we have the "Start Exploring" button on the right, the main menu looks kind of strange and broken here and there when it comes to the above three pages.  Also, a blank `class="cta"` div is rendered over there.

Also #497 might be related.

**Comment by rviscomi** [comment]
Yeah I think the header nav links should utilize the horizontal space better too.

> What is the desired result on the main menu pages, in terms of width and alignment?

The body should always be as wide as the header.
