### ISSUE TITLE
Bad data for fonts per page in CSS chapter

### ISSUE THREAD

**Issue by rviscomi** [HTTPArchive/almanac.httparchive.org#494]
Desktop p90 is 0, which is smaller than p75. Doesn't make sense.

https://almanac.httparchive.org/en/2019/css#fig-15

![image](https://user-images.githubusercontent.com/1120896/68948858-d5ab3200-0786-11ea-9710-ef7116da57c9.png)

**Comment by bazzadp** [comment]
@rviscomi [rerunning the query](https://github.com/HTTPArchive/almanac.httparchive.org/blob/master/sql/2019/02_CSS/02_22.sql) gives this:
![Data from rerun of query](https://user-images.githubusercontent.com/10931297/79067243-e3250380-7cb5-11ea-9cf1-abb2864ebf4f.png)

Compared to the Google Sheets for that chapter which shows:
![Google Sheets data](https://user-images.githubusercontent.com/10931297/79067271-0485ef80-7cb6-11ea-8118-68874b7dddd9.png)

So think someone just copied and pasted this wrong.

Can you correct or give me edit permission to the sheet so I can.

We'll also need to update the fallback PNG image.
