### ISSUE TITLE
Header nav sometimes wraps

### ISSUE THREAD

**Issue by rviscomi** [HTTPArchive/almanac.httparchive.org#497]
This is a weird one. I'd be navigating pages when all of a sudden the header nav wraps

![image](https://user-images.githubusercontent.com/1120896/68981065-41fe5380-07d0-11ea-9a10-68b4c62c6dd8.png)

Reloading doesn't always fix it, but if I resize the window 1px in either direction, it corrects itself. I've seen this a few times today. Working from a new computer in a viewport 1313px wide, which may explain why I just started seeing it. Anyone else notice anything weird like this?

**Comment by catalinred** [comment]
Wasn't able to reproduce this 1313px behavior, neither on macOS nor on Windows, tried multiple browsers. Can you please give more info on OS and browser?

**Comment by rviscomi** [comment]
I was using Chrome on MacOS. If we can resolve this in #480 I'll close this.
