### ISSUE TITLE
Build a language switcher

### ISSUE THREAD

**Issue by rviscomi** [HTTPArchive/almanac.httparchive.org#50]
@HTTPArchive/developers 

Somewhere on the page we should have a dropdown field for users to change the language. The expected UX of the field is:

- the default/selected option is the current language
- clicking the field will open a switcher with the other supported languages displayed
- selecting any other language will reload the current page with the language specified in the URL

For example, if on `/` and the user selects Japanese, the new URL will be `/ja/`. Similarly, if on `/2019/outline` the new URL will be `/ja/2019/outline`. Switching to English will force the `/en` URL path prefix for simplicity.

In terms of implementation, it should be built into the `templates/base.html` template. We can look at the `{{ lang }}` property and set an option as `selected` if it matches. For accessibility, does this need to have anchor elements or are there equivalent ARIA attributes we can use?

Design questions:

- is there a common place for this UI to go? header/footer?
- should we show flags as the options as a way to convey the language in a way not dependent on translation? (need a text-based fallback anyway for accessibility)
- should the options be translated in the destination language?

**Comment by rviscomi** [comment]
📟Paging @chaluvadis @gustavofsantos @matijagrcic @noahblon @tanhengyeow @tjmonsi @tyohan @Mehedihasan-wp.

Would any of you like to work on your first development issue? This one needs an owner. 😃

**Comment by tanhengyeow** [comment]
I would like to attempt this! I've not worked with Flask before but would try my best to learn it as I go 😄 

> For accessibility, does this need to have anchor elements or are there equivalent ARIA attributes we can use?

I was thinking of using anchor tags for the different language options. We can use the [`aria-describedby`](https://www.w3.org/TR/wai-aria/#aria-describedby) or [`aria-labelledby`](https://www.w3.org/TR/wai-aria/#aria-labelledby) property to describe the anchor tags.

> is there a common place for this UI to go? header/footer?

I think the header would be a reasonable place. I saw #46 and it seems like the design of the home page has not been finalized yet, so this might change. In that case, should I implement a generic language switcher first?

> should we show flags as the options as a way to convey the language in a way not dependent on translation? (need a text-based fallback anyway for accessibility)

This sounds good to me. Do we want to maintain our own assets for the flag icons? Alternatively we can use [flag-icon-css](https://cdnjs.com/libraries/flag-icon-css).

> should the options be translated in the destination language?

It makes sense to me to translate them to the destination language. Open to other suggestions too.

**Comment by rviscomi** [comment]
Great thanks for stepping up @tanhengyeow! I've assigned this issue to you.

> I was thinking of using anchor tags for the different language options. We can use the aria-describedby or aria-labelledby property to describe the anchor tags.

I think as long as we use `aria-label` on the anchor content it will be accessible. The part I was mostly curious about was the dropdown menu behavior and how we can make sure that the widget is easily discoverable, understandable, and usable.

> should I implement a generic language switcher first?

Yeah you can built it in the header of the index.html template and we will go through in the design phase and style it. For now it should just be functional and not necessarily pretty.

> Do we want to maintain our own assets for the flag icons? Alternatively we can use flag-icon-css.

Good question. Let's add the individual SVG files from flag-icon-css for the languages we currently support to a local `src/static/images/lang` directory.
