### ISSUE TITLE
Add translator to translated chapters

### ISSUE THREAD

**Issue by bazzadp** [HTTPArchive/almanac.httparchive.org#507]
If a chapter is translated then the markdown should include the translator(s) like this:

```
---
part_number: II
chapter_number: 7
title: パフォーマンス
description: コンテンツの初回ペイント（FCP）、最初のバイトまでの時間（TTFB）、初回入力遅延（FID）を取り扱う2019 Web Almanac パフォーマンスの章。
authors: [rviscomi]
reviewers: [JMPerez,obto,sergeychernyshev,zeman]
translators: [MSakamaki]
discuss: 1762
published: 2019-11-11T00:00:00.000Z
last_updated: 2019-11-07T21:46:11.000Z 
---
```

And the translators should then be listed on that translated page to give them credit for the translation and also so they can be a point of contact for any translation issues.

I'm, thinking in a similar way as the reviewers, but open to other opinions here:

![image](https://user-images.githubusercontent.com/10931297/69014004-e1ad1480-097d-11ea-9ff9-89d94535df1b.png)

**Comment by rviscomi** [comment]
+1 I think that's the best way to do it.
