### ISSUE TITLE
No, Q is not the most popular physical CSS unit of length

### ISSUE THREAD

**Issue by rviscomi** [HTTPArchive/almanac.httparchive.org#513]
Regarding https://almanac.httparchive.org/en/2019/css#units @zcorpan on Twitter asked:

> What is using the Q unit? Is it Japanese sites, or some common third-party CSS?

I started looking into this and I'm seeing many cases where Q was detected on stylesheets with base64-encoded data. I think these are false positives triggered by a weak regex I wrote for [02_07.sql](https://github.com/HTTPArchive/almanac.httparchive.org/blob/master/sql/2019/02_CSS/02_07.sql):

https://github.com/HTTPArchive/almanac.httparchive.org/blob/87970a7a63fe7fb28ec2beb7b9f4b0bf413441b8/sql/2019/02_CSS/02_07.sql#L6-L12

I reran the query with one small change: ignore any value longer than 20 characters. Most values should be small like `250px` or `1.6Q !important`. The ones that are longer than 20 characters are probably made up of mostly base64 crap. Just a heuristic but it seems to have made a big difference:
 
![image](https://user-images.githubusercontent.com/1120896/69084140-9cd2bd80-0a11-11ea-8293-0784d7cfcc72.png)

Q is much further down the list where we'd expect it. And the major units are mostly unchanged.

I'll coordinate with @argyleink and @una to rewrite this section with the revised data.

**Comment by una** [comment]
Oh wow! Yes, good catch there @rviscomi

**Comment by zcorpan** [comment]
Nice catch!

Does the CSS parser you use only give you a string for the whole value? More robust could be to use a CSS parser that gives you a list of component values, where you can iterate each component value and if it's a `<dimension-token>`, ask for its unit. Although that would probably also be slower to run.

It looks like the query only picks up the first length in a value when there are multiple. Right? That could miscount if pages do things like `margin: 0px 1cm` or so, though maybe that's so uncommon as to not change the outcome?

Would also be interesting to know about typoed units and use of non-standard units (like `mozmm` or `__qem`).

**Comment by rviscomi** [comment]
> Does the CSS parser you use only give you a string for the whole value? More robust could be to use a CSS parser that gives you a list of component values, where you can iterate each component value and if it's a `<dimension-token>`, ask for its unit. Although that would probably also be slower to run.

Yeah it's only a string value. More granular tokenization would be super useful, but not supported by [this parser](https://almanac.httparchive.org/en/2019/methodology#rework-css).

> Would also be interesting to know about typoed units and use of non-standard units (like mozmm or __qem).

Yes! A value tokenizer would be a big help for questions like this.

> It looks like the query only picks up the first length in a value when there are multiple. Right? That could miscount if pages do things like margin: 0px 1cm or so, though maybe that's so uncommon as to not change the outcome?

You're right. I don't think it would be significant.

**Comment by zcorpan** [comment]
OK, thanks. https://github.com/tabatkins/parse-css could be used maybe as a wholesale drop-in replacement for next year, or just for tokenizing values specifically (with `parseAListOfComponentValues()` or maybe just  `tokenize()`). cc @tabatkins

**Comment by rviscomi** [comment]
The fix is live in prod: https://almanac.httparchive.org/en/2019/css#units

**Comment by tabatkins** [comment]
> OK, thanks. https://github.com/tabatkins/parse-css could be used maybe as a wholesale drop-in replacement for next year, or just for tokenizing values specifically (with parseAListOfComponentValues() or maybe just tokenize()). cc @tabatkins

Just straight `tokenize()` should work great; `parseAListOfComponentValues` will slurp up the contents of functions and blocks (in particular, the stuff between {} in a style block) and require you to tree-walk to find all the dimension tokens anyway. You just want the straight list of tokens.

(And from what I've heard, tokenize() is pretty dang fast, faster than regex-based methods that people had been using before switching to my library.)
