### ISSUE TITLE
Show page view counts for each chapter

### ISSUE THREAD

**Issue by rviscomi** [HTTPArchive/almanac.httparchive.org#518]
I'm open to hearing dissenting opinions on this one. It's not entirely necessary. But I have a suspicion that every time we look up the number of comments on each chapter's discussion thread, it [increments the thread's view count](https://meta.discourse.org/t/does-hitting-a-topics-json-endpoint-count-towards-its-views/133763). I'm waiting to hear back from the Discourse people if this is really happening, otherwise 10K people clicked JavaScript's comment button, which is nearly 100% of page viewers, so not likely.

Anyway, we could make the most of this odd "feature" by exposing the view count on the chapter page itself. It should be part of the same JSON metadata response as the comment count. A stat about the chapter's popularity might be good to drive engagement, similar to showing the comment count to encourage people to comment (which they haven't, really, as most chapters have 0 comments).

**Comment by bazzadp** [comment]
I think it would be an interesting stat. Only concern would be if Discourse "fix" this issue? could always remove it then if they do I suppose.

On a similar note, I also think we should add a "Date Published" and "Last Updated" section. The year in the URL kind of gives it away, but no harm being more explicit about how up to date (or not!) the information in the page is - especially as we're tracking this (though not 100% accurately!) for Structured Date and Sitemap anyway.

**Comment by bazzadp** [comment]
Throwing out some ideas:

![91B797A3-C6B5-4723-8944-490D3BD1C829](https://user-images.githubusercontent.com/10931297/69177423-67a49900-0aff-11ea-8e5e-7273233b0fa6.png)

Probably a bit too busy - especially for chapters with multiple authors. And on mobile.

Could leave either one or both dates off:

![44CCC69A-45A3-46BF-B0C3-A9B29D7E1D35](https://user-images.githubusercontent.com/10931297/69177746-09c48100-0b00-11ea-950b-a4327510cf69.png)

Personally I think Published Date is good to have at top in blog posts (though maybe year in URL makes this less important in this case?) and Last Updated can wait until the bottom of the page.

**Comment by arsenicraghav** [comment]
Can make the page view count manual using pageviewCustomEvent ?

**Comment by bazzadp** [comment]
> pageviewCustomEvent

Sorry not sure what you mean by this? You mean as a GTM custom event?

If so, I presume we'd still need it to call something to track the page views and seems we've luckily got something that does this already (even if unintentionally!) so why not just use that - as @rviscomi suggests?

Or are you suggesting this as a fix to my concern that Discourse may fix this? If so still not convined it's worth the effort nd would say revisit it if/when they do.

**Comment by bazzadp** [comment]
BTW, since we use the same discussion threads for translations, this thread count will be the same for each translation. That's not necessarily a reason not to do this, but just something to be aware of if we do do it.

**Comment by rviscomi** [comment]
I'm ok closing this out. The view count is not a high priority and I'd like to start shifting our focus from 2019 improvements to building the new 2020 edition.
