### ISSUE TITLE
Ability to force non-interactive data viz

### ISSUE THREAD

**Issue by rviscomi** [HTTPArchive/almanac.httparchive.org#520]
In some cases, like printing a paper copy or saving to PDF, it's better to have static images than interactive iframes. The images fit the screen better and don't require interactivity.

I'd like to add support for something like a `?print` querystring parameter on chapter pages that forces all figures to use images. For now it must also disable lazy loading due to a [bug in Chrome](https://bugs.chromium.org/p/chromium/issues/detail?id=875403) that doesn't load images below the fold when printing.

This is a small step towards a "PDF-friendly" version of the Almanac per #37.

**Comment by bazzadp** [comment]
This should be fairly simple once https://github.com/HTTPArchive/almanac.httparchive.org/pull/511 is merged by either looking at the query string or [detecting whether in print mode](https://stackoverflow.com/questions/1234008/detecting-browser-print-event) and then _not_ upgrading to interactive visualisations in `upgradeInteractiveFigures`, and also removing the lazy-loading tags.
