### ISSUE TITLE
Home page on mobile and bouncing

### ISSUE THREAD

**Issue by bazzadp** [HTTPArchive/almanac.httparchive.org#524]
On mobile the home page seems to be slightly wider than the viewport - you can bounce it from left to right a little, which makes scrolling up and down slightly more difficult.

This is not possible on the other pages (ToC, Contributors, Methodology or Chapters).

**Comment by catalinred** [comment]
This should be fixed by #523

**Comment by bazzadp** [comment]
Thanks! - that was annoying me 😀

**Comment by catalinred** [comment]
Thanks for the heads up! 😀
