### ISSUE TITLE
Logo tweak

### ISSUE THREAD

**Issue by rviscomi** [HTTPArchive/almanac.httparchive.org#531]
![Screenshot_20191122-092256](https://user-images.githubusercontent.com/1120896/69409722-c9d0ea00-0d09-11ea-83c3-c07521adfd72.png)

Extend the yellow line of the logo to extend fully to the right edge of the word "almanac". It occurred to me right now that it appears to underline the letters "man" which looks weird.

**Comment by catalinred** [comment]
I'll extend that yellow line, convert this to an SVG and get rid of the obsolete 2x image approach.

**Comment by bazzadp** [comment]
While we're on Logo tweaks the HTTPArchive logo rudely cutting off the 'a' has been bugging me for a while. 

![image](https://user-images.githubusercontent.com/10931297/69676841-8542a700-1099-11ea-8d9d-ef401071d548.png)

Do we have a better version of this @rviscomi ? Or @catalinred could you create one?

**Comment by catalinred** [comment]
> While we're on Logo tweaks the HTTPArchive logo rudely cutting off the 'a' has been bugging me for a while.
> 
> ![image](https://user-images.githubusercontent.com/10931297/69676841-8542a700-1099-11ea-8d9d-ef401071d548.png)
> 
> Do we have a better version of this @rviscomi ? Or @catalinred could you create one?

I'll check this as well and let you know @bazzadp ;)

**Comment by rviscomi** [comment]
We have an SVG version of the HTTP Archive logo here: https://github.com/HTTPArchive/legacy.httparchive.org/blob/master/images/http-archive-logo-color-nogradient.svg

Related #262

**Comment by catalinred** [comment]
> We have an SVG version of the HTTP Archive logo here: https://github.com/HTTPArchive/legacy.httparchive.org/blob/master/images/http-archive-logo-color-nogradient.svg
> 
> Related #262

Awesome, because I didn't find it within the .psd file you sent me a while ago. Thank you!
