### ISSUE TITLE
Use larger images for social metadata

### ISSUE THREAD

**Issue by rviscomi** [HTTPArchive/almanac.httparchive.org#534]
For example, the appearance of this chapter image is a bit low-res:

![image](https://user-images.githubusercontent.com/1120896/69476162-a031c480-0dd6-11ea-9770-f4c3c3726def.png)

We should use `hero_lg.jpg` for these images as opposed to `hero_sm.jpg`

https://github.com/HTTPArchive/almanac.httparchive.org/blob/d52cb47873d3bcbd558a523d4697d71f269ed92b/src/templates/en/2019/chapter.html#L27-L32

**Comment by bazzadp** [comment]
Worth giving it a go but not convinced it’ll solve it. Twitter is well-known for compressing images and sometimes losing a little in the process.

Maybe should convert to PNGs? And [add a transparent pixel to prevent conversion back](https://lifehacker.com/stop-twitter-from-turning-your-pngs-into-jpgs-1822461989)?

**Comment by bazzadp** [comment]
Did some tests and does look to make a difference. Will submit a PR.
