### ISSUE TITLE
Home page a bit broken on IE11

### ISSUE THREAD

**Issue by bazzadp** [HTTPArchive/almanac.httparchive.org#538]
Not sure if we care (it's only 1.12% of our traffic according to Google Analytics), but just noticed the home page image isn't in the right place on IE11 and so merges with the "Start Exploring" button. See below

![image](https://user-images.githubusercontent.com/10931297/69495261-e6f9ea00-0ebc-11ea-90ae-c045627e5285.png)

**Comment by rviscomi** [comment]
I think this is due to lack of grid support. Working as intended IMO.

**Comment by bazzadp** [comment]
> I think this is due to lack of grid support. Working as intended IMO.

Grand. Happy to close.
