### ISSUE TITLE
Relative paths and the readme

### ISSUE THREAD

**Issue by anoblet** [HTTPArchive/almanac.httparchive.org#54]
Should the repro instructions from the src/readme be in the main readme? If not, would it make sense to change /src/README.md to include instructions relative to the project root?

`pip install -r requirements.txt` >  `pip install -r src/requirements.txt`
`python main.py` >  `python src/main.py`

Not sure if this is an issue for many people

**Comment by rviscomi** [comment]
@mikegeyser had some opinions about this early on

**Comment by rviscomi** [comment]
Usually the README is from the perspective of being in the repo root. In this case I think we want to assume the developer executed `cd src`.

@HTTPArchive/developers any other opinions?

**Comment by mikegeyser** [comment]
I think that's completely reasonable.

**Comment by anoblet** [comment]
I'm ok with either one

**Comment by rviscomi** [comment]
Ok, I'll close this as it's working as intended. Feel free to reopen if anyone feels strongly.
