### ISSUE TITLE
Translate content to Arabic

### ISSUE THREAD

**Issue by SilentJMA** [HTTPArchive/almanac.httparchive.org#540]
These are the chapters to be translated, and they exist in the [content directory](https://github.com/HTTPArchive/almanac.httparchive.org/tree/master/src/content):
- [ ] accessibility
- [ ] caching
- [ ] cdn
- [ ] cms
- [ ] compression
- [ ] css
- [ ] ecommerce
- [ ] fonts
- [ ] http2
- [ ] javascript
- [ ] markup
- [ ] media
- [ ] mobile-web
- [ ] page-weight
- [ ] performance
- [ ] pwa
- [ ] resource-hints
- [ ] security
- [ ] seo
- [ ] third-parties

Additionally the following pages need translated too in the [language specific templates directory](https://github.com/HTTPArchive/almanac.httparchive.org/tree/master/src/templates):
- [ ] base.html
- [ ] base_chapter.html
- [ ] contributors.html
- [ ] error.html
- [ ] index.html
- [ ] featured_chapters.html
- [ ] methodology.html
- [ ] table_of_contents.html
- [ ] accessibility_statement.html

There is no need to translate the chapters HTML pages are they are generated off the markdown combined with the above templates.

Common notes for writing consistency are here: https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Translators'-Guide. Feel free to edit that and/or add Arabic-specific extras by editing this comment.

Arabic-specific extra advice:
- None yet

**Comment by bazzadp** [comment]
Greats stuff @SilentJMA - I've updated your first comment showing what needs to be done. Feel free to stick your name against an item, clone the repo, and submit pull requests (PRs) with your translations.

Note a lot of the visualisation graphics are due to change in https://github.com/HTTPArchive/almanac.httparchive.org/pull/511 so might want to hold off for that for some of the chapters, but the JavaScript, Accessibility and HTML chapters are good to go now.

Unfortunately my Arabic is non-existent so would be good to have someone else fluent in the language to review your PRs. I'm happy to give PRs a once over for other technical issues though.

**Comment by SilentJMA** [comment]
> Greats stuff @SilentJMA - I've updated your first comment showing what needs to be done. Feel free to stick your name against an item, clone the repo, and submit pull requests (PRs) with your translations.
> 
> Note a lot of the visualisation graphics are due to change in #511 so might want to hold off for that for some of the chapters, but the JavaScript, Accessibility and HTTP/2 chapters are good to go now.
> 
> Unfortunately my Arabic is non-existent so would be good to have someone else fluent in the language to review your PRs. I'm happy to give PRs a once over for other technical issues though.

in #540 we will need a change from Left to Right is it possible because it's different to FR/EN/ES.. which start from left to right

**Comment by bazzadp** [comment]
> in #540 we will need a change from Left to Right is it possible because it's different to FR/EN/ES.. which start from left to right

Yes this is possible.

Everything inherits based off of the `src/templates/_LANG_/2019/base.html` template. This will need to be translated anyway.

This language-specific base.html inherits from the main, language-independent, `src/templates/base.html` file which has the following at the top of the file:

```
<!doctype html>
<html lang="{% block lang %}{{ language.lang_attribute }}{% endblock %}">
```

It is possible to override `{% %}` blocks, so when creating the `src/templates/ar/2019/base.html` file as part of your translation process, override the `{% block lang %}` section of the main `src/templates/base.html` file to add [the `dir` attribute](https://www.w3.org/International/questions/qa-html-dir) by adding the following after the `{% extends "base.html" %}` line:

`{%block lang %}{{ language.lang_attribute }}" dir="rtl{% endblock %}`

This will make it evaluate to:

`<html lang="ar" dir="rtl">`

Now this is a bit of a hack to be honest as I'm basically setting the language to `ar" dir="rtl` and depending on the quotes matching. But it'll do for now and we'll fix it up in a better way later.

**Comment by SilentJMA** [comment]
> > in #540 we will need a change from Left to Right is it possible because it's different to FR/EN/ES.. which start from left to right
> 
> Yes this is possible.
> 
> Everything inherits based off of the `src/templates/_LANG_/2019/base.html` template. This will need to be translated anyway.
> 
> This language-specific base.html inherits from the main, language-independent, `src/templates/base.html` file which has the following at the top of the file:
> 
> ```
> <!doctype html>
> <html lang="{% block lang %}{{ language.lang_attribute }}{% endblock %}">
> ```
> 
> It is possible to override `{% %}` blocks, so when creating the `src/templates/ar/2019/base.html` file as part of your translation process, override the `{% block lang %}` section of the main `src/templates/base.html` file to add [the `dir` attribute](https://www.w3.org/International/questions/qa-html-dir) by adding the following after the `{% extends "base.html" %}` line:
> 
> `{%block lang %}{{ language.lang_attribute }}" dir="rtl{% endblock %}`
> 
> This will make it evaluate to:
> 
> `<html lang="ar" dir="rtl">`
> 
> Now this is a bit of a hack to be honest as I'm basically setting the language to `ar" dir="rtl` and depending on the quotes matching. But it'll do for now and we'll fix it up in a better way later.

Maybe i can fix it if i try but i don't know i will test it later and see .........

**Comment by bazzadp** [comment]
> Maybe i can fix it if i try but i don't know i will test it later and see .........

Submitted #551 to add this ability. will leave you to do the hard part (the translations!). 😀

**Comment by bazzadp** [comment]
Interesting article I came across about handling rtl text: https://www.rtlstyling.com/posts/rtl-styling/

Reminded me of this issue so I thought I’d post here (in part to remind myself!) in case we need to do any more with the styling after translations are done.

**Comment by bazzadp** [comment]
There's been no progress on this in last few months so am going to close this. We can reopen if we get translators.

@SilentJMA  let us know if you plan on actioning this and want to re-open it?
