### ISSUE TITLE
Migrate translated chapters to new Data Visualisation Formats

### ISSUE THREAD

**Issue by bazzadp** [HTTPArchive/almanac.httparchive.org#542]
@HTTPArchive/translators , we have just pushed an update to all the English chapters that updates the format of the Figures markdown. This allows us to only load the interactive Sheets visuals when the client supports them and will use them (mobile devices won't use them, iPads don't support them...etc.). This also added much deeper descriptions of the visuals.

Unfortunately this means we need to revisit the chapters that have already been translated.

Can I ask you to review any chapters you have already translated or which are in progress and check the figure markup?

Below are the chapters that have been committed already so likely need to change:

- [ ] ES - Ecommerce
- [ ] ES - Markup
- [ ] ES - Performance
- [x] JA - Markup
- [x] JA - Performance

Apologies for that and hopefully this will be the last bulk update of this sort (for 2019 at least!).

Let me know if you have any questions.

Thanks,
Barry

**Comment by MSakamaki** [comment]
OK, I currently translating the SEO chapter, I will start after it is complete. (It will weekend)

**Comment by bazzadp** [comment]
Looks like this was only closed for Japanese but needs to be reopened for Spanish ones as they were not completed.

**Comment by bazzadp** [comment]
Moved the Spanish ones to the new format, but only added the text in English so this will still need to be translated.
