### ISSUE TITLE
How to handle chapter visualisations in translations?

### ISSUE THREAD

**Issue by bazzadp** [HTTPArchive/almanac.httparchive.org#558]
CC: @HTTPArchive/translators 

So @rviscomi and I had a brief chat on this last time we met up, but almost of the graphics have English text in them (titles, labels... etc.). Most of them are created by Google Sheets that we are entirely in control of. We currently embed the sheets as iFrames when the client supports it and fall back to locally hosted images when they don’t.

Options for translations that I see include:

- Don’t translate and serve English versions.
- Translate temporarily, save screenshots, serve screenshots only.
- Create a translated copy of the Sheets visual and Share that so it can be embedded. Also take a screenshot of the translated copy as a fallback.
- Some other technical magic that Google Sheets does that I don’t know about.

The first two items involve a lesser experience for our foreign readers so neither are satisfactory answers IMHO.

The third however may become a maintenance nightmare - especially as languages supported increase. Though thankfully at least the actual changes to the graphics since publication have been rare, so maybe over worrying about this?

Other concern is that we might accidentally break an existing language when adding a new language. I don’t think we should have hundreds of people with edit access to the sheets for example, but also don’t want to have a few of us being the bottleneck. Would also mean us few need to actually do the translations which will likely lead to errors - especially with different character sets! Tricky...

The final “magic” option doesn’t exist as far as I know. Though don’t use Sheets much so maybe I’m wrong?

There’s also the question of other graphics were we don’t have the original.

Anyway thought I’d open this issue to kick off the discussion and so that someone can tell me the magic solution to this tricky problem, that I can’t see 😀

**Comment by bazzadp** [comment]
Or could copy the graphics from English sheet to a new French sheet, for example, and give French translator team edit access to that sheet? That way we de-risk breaking the other chapters but also allow the appropriate team to do the translation?

Could even link the data back to the original sheet I presume so if it is changed it should auto update?

**Comment by bazzadp** [comment]
@HTTPArchive/translators anyone any thoughts on this?

**Comment by SilentJMA** [comment]
If we made separate sheet that belong to every language is good but the other question how we will deal if we switch the language to arabic for exampl?

**Comment by bazzadp** [comment]
Then we create a separate sheet for Arabic. Sorry I don’t understand why that would be an issue?

**Comment by SilentJMA** [comment]
> Then we create a separate sheet for Arabic. Sorry I don’t understand why that would be an issue?

The RTL because in arabic the text is from right to left

**Comment by bazzadp** [comment]
> The RTL because in arabic the text is from right to left

Yeah but then in the Arabic version just change the labels to make them read RTL. That’s the whole benefit of having own sheet with own version of graphs and images - can make the labels say whatever you need in whatever way is most appropriate for that language.

**Comment by rviscomi** [comment]
Language-specific sheets SGTM and seems like the lowest friction option.

**Comment by bazzadp** [comment]
Closing this. The technical solution is there (copy data to language specific sheet) should a translation team wish to do this.

**Comment by dtikhonov** [comment]
> The technical solution is there (copy data to language specific sheet) should a translation team wish to do this.

I did some spot checking: it seems no translation team has actually done this.

**Comment by bazzadp** [comment]
Correct. At the moment the effort of just translating the text has been more than enough to keep them occupied so we're stuck with English graphics.

Not ideal but I honestly don't think we should do any more on this, and should live with what we've got unless and until we move to an alternative to Google Sheets for figures. The effort of translating the graphics, and creating image files for mobile (where we don't use Google embeds) versus the gains make it not worth it IMHO.

Additionally we have very detailed descriptions for each graphic in the translated language.

**Comment by dtikhonov** [comment]
OK.  I was just looking to find the status of this.  That the visualizations are not translated along with text is something that jumped out at me right away, so that's why I inquire.  If "do nothing" is the consensus approach, I am fine with it.
