### ISSUE TITLE
Add Search Functionality

### ISSUE THREAD

**Issue by tunetheweb** [HTTPArchive/almanac.httparchive.org#559]
I think we should have the ability to search this amazing collection of data.

We could use Google Custom Search or similar. I’ve used SiteSearch360 a bit since Google stopped offering to accept money for ad-free version of GCS. Though lot of contributors and some sponsorship coming from Google so that’s probably not a runner.

Or alternatively just use main Google with a `site:https://almanac.httparchive.org/en/2019` option. That’s probably the simplest and would also make it easy to change the URL searched and option passed to serve different languages and/or years. For example French pages could search www.google.fr with `site:https://almanac.httparchive.org/fr/2019` option.

Or could do something server side?

Thoughts?

**Comment by catalinred** [comment]
I've used https://community.algolia.com/docsearch/ in the past: it's fast, modern and has a very good documentation.

Also, it's used in the wild with success by lots of open-source projects, e.g. https://reactjs.org/

**Comment by rviscomi** [comment]
This is a "nice to have" and not business critical so I do encourage us to look into it but not spend a lot of time designing or building an elaborate solution.

**Comment by rviscomi** [comment]
Triaging old issues. I think this is still a good feature to add. @bazzadp are you still thinking of the search action taking the user off-site, or could we implement something server side?

**Comment by bazzadp** [comment]
Would still love to have this! However in my experience site search is used less than you'd think so I still think investing in a back end solution is overkill. Plus natural language processing search might not be as good as the likes of Google Search.

So let's just use Google Search!

Could you sign up for a Web Almanac ["Programmable Search Engine"](https://programmablesearchengine.google.com/about/) account (formerly known as Google Custom Search). This uses the power of Google Search but allows you to have it surfaced on a page on your site (/search maybe?).

It also means you only have to optimise for SEO once - if it works on Google, it works on your site search.

I see Google have option of ad-free version again! But I'd just sign up for the free, ad-backed version for now. Can decide if we want the ad-free version later. Or could even host ads on this and make a small amount into our Open Collective account?

Anyway I've used this before and it's very easy to set up (basically a bit of JS on the page). So the most difficult decision would be one for the @HTTPArchive/designers as to where to put the search bar on desktop and mobile!

**Comment by shantsis** [comment]
Perhaps for desktop we can show an input or just a button depending on the screen size.
For mobile, it can be within the menu before the select boxes.
![web-large](https://user-images.githubusercontent.com/22671477/116828404-71438480-ab6c-11eb-9918-0debb1db356b.png)
![web-small](https://user-images.githubusercontent.com/22671477/116828406-74d70b80-ab6c-11eb-86e8-42d69a91acfe.png)
![mobile](https://user-images.githubusercontent.com/22671477/116828410-76a0cf00-ab6c-11eb-9c0a-310686aea891.png)
