### ISSUE TITLE
Get a source of country flags

### ISSUE THREAD

**Issue by bazzadp** [HTTPArchive/almanac.httparchive.org#565]
What's the source of the country flag pngs? Or were they created from scratch?

For example: https://github.com/HTTPArchive/almanac.httparchive.org/blob/master/src/static/images/es.png

Need a French one and am sure that won't be the last!

**Comment by c-torres** [comment]
I got the Spanish flag from https://assets.adobe.com/public/44a4899f-53d1-4340-4f28-2eb282e2dc85 but seems like it won't be enough to add flags for all the languages.

**Comment by catalinred** [comment]
When needed for the website, a solution would be maybe to rely on getting/downloading the flags from an open-source repo like https://restcountries.eu/ which also provides the flags in an SVG format? (e.g. https://restcountries.eu/data/col.svg).

**Comment by rviscomi** [comment]
Let's try to find a new source for the flags. IIRC the one the designer used required attribution and the images are extremely unoptimized. Would be nice to find a service that is permissive and doesn't require optimizing.

**Comment by borisschapira** [comment]
Here's a whole set of flags downloaded from Wikipedia and checked to be in
Public Domain or otherwise exempt from Copyright: https://github.com/google/region-flags 

Can it help?

**Comment by bazzadp** [comment]
Nice find! I think they’ll do nicely.

Now just need to check how they integrate into the design (the current examples are circular I think so may need some CSS to fit in) and then check in the ones we need.

**Comment by AymenLoukil** [comment]
Hi!
Adding Countries flags is not coherent since we are not targeting specific regions. All the contents on Web Almanac are targeting language only and not language-country.

**Comment by borisschapira** [comment]
@AymenLoukil Interesting take. Maybe we could only display the language code in a future iteration.

**Comment by bazzadp** [comment]
An interesting thought though not sure I agree 100%. It’s definitely American English for example. So it’s right to show the American flag rather than the UK or English flag.

I imagine the other translations will be similar and will be slanted towards one county’s use of that language (probably set but the first translator for that language who will likely set the standard for the translations for that language).

They are [set up in the code (somewhat) as language-region rather than just language](https://github.com/HTTPArchive/almanac.httparchive.org/blob/6e7eda5fc88a4d6e065fd873dc8ba9260c7d4fec/src/language.py#L28) though it would need more work to make that really work as other parts treat them as just language.

On their other hand I also agree with you somewhat, since we’re unlikely to have an en-UK version to go along with the en-US version for example (unless someone with a lot of time on their hands gets really annoyed with the Americanisms!), though that may not be as true for other languages.

**Comment by rviscomi** [comment]
Let's just remove the flags from the UI and rely on the translated name of the language per [Best practice for presenting languages](http://www.flagsarenotlanguages.com/blog/best-practice-for-presenting-languages/).

**Comment by bazzadp** [comment]
Please leave open. Updating the branch to follow your suggestion. Will let you know when good to go (almost done).
