### ISSUE TITLE
i18n - Reimplement Almanac logo using text and CSS instead of SVG

### ISSUE THREAD

**Issue by borisschapira** [HTTPArchive/almanac.httparchive.org#567]
The [PNG Logo](https://almanac.httparchive.org/static/images/logo.png) contains English wording. It looks like it's created from [the SVG logo](https://github.com/HTTPArchive/almanac.httparchive.org/blob/master/src/static/images/logo.svg) unfortunately, the SVG logo has been optimized for Performance and all original text has been replaced by paths.

Is there a way to get an editable version to localize the "By" wording (in French, "par").

**Comment by bazzadp** [comment]
CC @catalinred

**Comment by catalinred** [comment]
Either you optimize an SVG logo for performance or not, you only want paths/shapes in a final logo SVG outcome. Because if you don't do that, and you rely on a font, you can expect different logos rendering in different OS's due to missing fonts or FOUT(Flash of Unstyled Text) maybe.

I understand your concern when it comes to i18n, but maybe a potential issue is that the logo has too much text itself - which is not that common. Also, FWIW, in terms of a11y, we do serve an appropriate `alt` attribute for the logo img.

**Comment by bazzadp** [comment]
> Because if you don't do that, and you rely on a font, you can expect different logos rendering in different OS's due to missing fonts or FOUT(Flash of Unstyled Text) maybe.

That makes total sense!

So options that I see now are:

1. Live with it and only have English Logo.
2. Create language specific versions of the Logo.
3. Make the Logo less language specific - for example by removing the "by" part:

![image](https://user-images.githubusercontent.com/10931297/69833301-ccac6d00-122a-11ea-8642-8d0a5b5f393c.png)

Or:

![image](https://user-images.githubusercontent.com/10931297/69833314-e64db480-122a-11ea-9ba3-ac3c35b8a669.png)

Thoughts on 1, 2 or 3? Or anyone got other options?

**Comment by catalinred** [comment]
On this premise, considering we're not actually using the proper ["HTTP Archive" custom logo](https://github.com/HTTPArchive/almanac.httparchive.org/blob/master/src/static/images/ha-home.svg) we should translate the "Archive" word too, so I think this path leads nowhere.

I think we shouldn't change it, at least for now. For the 2020 release, maybe we could think about it and revamp a bit the Web Almanac logo to contain the original HTTP Archive logo. That would be challenging!

**Comment by bazzadp** [comment]
> On this premise, considering we're not actually using the proper ["HTTP Archive" custom logo](https://github.com/HTTPArchive/almanac.httparchive.org/blob/master/src/static/images/ha-home.svg) we should translate the "Archive" word too, so I think this path leads nowhere.

Disagree on that. HTTP Archive is the brand name whether we are using the official logo or not and so am fine with that not being translated. Similarly with Web Almanac IMHO. Apple iPhone isn’t Pomme iTéléphone in France - it’s Apple iPhone.

**Comment by rviscomi** [comment]
Yeah "Web Almanac" and "HTTP Archive" are brand names and shouldn't be translated. I see the point about translating "by".

TBH we might just want to consider reimplementing the logo using text and CSS, which will allow us to translate it as needed.

**Comment by bazzadp** [comment]
> TBH we might just want to consider reimplementing the logo using text and CSS, which will allow us to translate it as needed.

I think we should do this.

**Comment by rviscomi** [comment]
@HTTPArchive/developers any takers?

**Comment by catalinred** [comment]
I will do it.

**Comment by rviscomi** [comment]
Thanks for fixing this @catalinred! I've also finally updated this repo's social media image to be a screenshot of this new logo.
![image](https://user-images.githubusercontent.com/1120896/86170223-c9db6880-bae8-11ea-883f-1c51a4a7c968.png)
