### ISSUE TITLE
i18n - Add a way to localize teams' names.

### ISSUE THREAD

**Issue by borisschapira** [HTTPArchive/almanac.httparchive.org#568]
Current team names (Analysts, Authors, Brainstormers, Designers…) are use on [the Contributors page](https://almanac.httparchive.org/en/2019/contributors) to filter people. We should think about a way to localize theses teams' names.

**Comment by bazzadp** [comment]
Related: https://github.com/HTTPArchive/almanac.httparchive.org/issues/398 and https://github.com/HTTPArchive/almanac.httparchive.org/issues/561

@borisschapira short term, can’t we just have buttons with local wording on the buttons but using the English categories to filter? Though I’m guessing that currently the buttons are dynamically generated so this would mean hard coding the team names? Not ideal but also I wouldn’t expect to add new teams that often so maybe acceptable...

**Comment by borisschapira** [comment]
Short term, I've added "(noms anglais)", aka "(English names)" to the "Filter by teams:" translation, because the buttons are generated from `config.teams.items()` and I don't know the app well enough to know where I could put a key-value mapping dictionary with the translations.

**Comment by bazzadp** [comment]
Yes but could just replace this:

```html
    {% for id, team in config.teams.items() %}
      <button class="{{ id }}" type="button">{{ team.name }}</button>
    {% endfor %}
```

with this:

```html
      <button class="analysts" type="button">Analystes</button>
      <button class="authors" type="button">Auteurs</button>
      <button class="brainstormers" type="button">Brainstormers</button>
      ....etc.
```

Hardcoding as a say, but maybe sufficient - at least in short term

**Comment by borisschapira** [comment]
This presents a risk if a new team is added but if it's okay with everyone, I can do it that way.

**Comment by bazzadp** [comment]
Agreed but think that's relatively unlikely and think it's far friendlier to French visitors so I say go for it for now. Leave this issue open for longer term options.

Also doing this for now will also give us the translations to use for when (if?) we do implement a better option. Which might be a [lookup table](https://stackoverflow.com/questions/18670606/how-to-use-a-lookup-table-in-jinja) in the Contributors chapter. @mikegeyser any thoughts on this?

**Comment by mikegeyser** [comment]
I think it would make sense for the base template to read the team names from a variable, and then each specific translation can override the variables in the contributors page. Something similar to how we set metadata in the `chapter.html`? (I think it's probably close to what you mean by a lookup table @bazzadp)

**Comment by bazzadp** [comment]
Yes that’s what I was thinking.
