### ISSUE TITLE
Optimize website for wide viewports

### ISSUE THREAD

**Issue by bazzadp** [HTTPArchive/almanac.httparchive.org#574]
As noted [in a recent PR](https://github.com/HTTPArchive/almanac.httparchive.org/pull/573#discussion_r352280309) there are a couple of inconsistencies with the home page, design, notably:

- [ ] - It's full width, but the other pages are constrained (to 1280px or 1324 - note bringing these inline with above PR)
- [x] - The Start Exploring button in the top right, means the other navigation items (TOC, Contributors, and Methodology) are in a different place on the home page than every other page and "jump" as you navigate to/from this - Completed in #684 

Are these items we want to fix? Or happy this should be different? The [original design](https://github.com/HTTPArchive/almanac.httparchive.org/issues/46#issuecomment-515966879) seemed to have a more constrained width (except for the header) though did always have the Start Exploring button in the same place as currently.

Thoughts?

**Comment by bazzadp** [comment]
I'm gonna suggest constraining the home page width to the same width as the other pages. Gimme a 👍if you agree or a 👎is you prefer it to remain full width.

**Comment by bazzadp** [comment]
I'm gonna suggest we move the "Start Exploring" button down from the header into the body, so we have a consistent header. Gimme a 👍if you agree or a 👎is you prefer it to remain where it is.

**Comment by bazzadp** [comment]
@HTTPArchive/developers anyone got an opinion on this?

**Comment by catalinred** [comment]
> I'm gonna suggest constraining the home page width to the same width as the other pages. Gimme a 👍if you agree or a 👎is you prefer it to remain full width.

The index shouldn't necessarily use a fixed page width as the other pages, as it can use a mix from both worlds .e.g. full width header, fixed-width featured chapter, then full-width contributors block design etc.

I do agree on the point that stuff should be implemented consistently, therefore the index page should use indeed the newly added `.container` used within #573 but that's another story and task.

> I'm gonna suggest we move the "Start Exploring" button down from the header into the body, so we have a consistent header. Gimme a 👍if you agree or a 👎is you prefer it to remain where it is.

At this time, on the index page, the "Start Exploring"  is indeed redundant as it links to `/table-of-contents`, as the "Table of Contents" menu item does too.  So I guess this is a valid point as we have two links that go to same resource. 

We should either link to the first Table of Contents chapter (to justify the "Start exploring" meaning) or just remove it completely from the header as @bazzadp suggests, as it's already in the "HTTP Archive's annual state of the web report" section below.

Thanks for raising these questions @bazzadp

**Comment by bazzadp** [comment]
> At this time, on the index page, the "Start Exploring" is indeed redundant as it links to /table-of-contents, as the "Table of Contents" menu item does too. So I guess this is a valid point as we have two links that go to same resource.
> 
> We should either link to the first Table of Contents chapter (to justify the "Start exploring" meaning) or just remove it completely from the header as @bazzadp suggests, as it's already in the "HTTP Archive's annual state of the web report" section below.

To be clear, I have no problem with multiple links to the same page especially if some of those links are in the header and if we specially want to call them out in the body. And I actually quite like the “Start Exploring” call to action. I just think it’s current location is problematic as the menu items jump between pages so it’s not consistent so think it should be moved down out of the header.

**Comment by catalinred** [comment]
To be clear as well, I was just trying to add to the conversation as you asked above for an opinion and as you know, I also raised the "jumping" header issue  [here](https://github.com/HTTPArchive/almanac.httparchive.org/pull/573#discussion_r352284312).

FWIW, I still believe multiple links to the same page within a menu is a UX issue.

**Comment by bazzadp** [comment]
Oh within a menu I agree with you.

I just meant I like having the “Start Exploring” call to action itself, just not in the menu. It should be moved down the page IMHO. But actually, I forgot there is already another “Start Exploring” button there (in yellow)!

![EF51A841-60D6-4315-B2EC-D5E77E4AD80C](https://user-images.githubusercontent.com/10931297/70257793-514b3e00-178b-11ea-8c23-a4c909a3399f.jpeg)

So yeah we definitely don’t need it in the menu.

So think we’re agreeing with each other? 😀

**Comment by rviscomi** [comment]
+1 to fixed width

Not sure about the Start Exploring button consistency issue. 40% of visitors land on the home page and I think it's good to have as many prominent calls to action as the UI can afford. The header links jumping is a valid point but there are other home-specific aspects of the UI that change as well (eg the header background) so I'm not too concerned about it.

**Comment by bazzadp** [comment]
BTW this gets worse when you add the Language switcher:

![image](https://user-images.githubusercontent.com/10931297/71856733-d6a07600-30dc-11ea-8f9b-3172a69e8786.png)

Without this extra CTA it's much neater IMHO with logo on left, nav in middle, and language on right:

![image](https://user-images.githubusercontent.com/10931297/71856758-ecae3680-30dc-11ea-8d73-e68772fda089.png)

So I still think we should remove it from the header.

It would also be interesting to see which of the **four** CTAs to table of contents is used most. @rviscomi can you enable [Enhanced Link Attribution](https://support.google.com/analytics/answer/7377126?hl=en&ref_topic=2558810) in GA->Properties and in Google Analytics tag in GTM to allow this to be seen?

**Comment by bazzadp** [comment]
And btw another design issue on the home page is the buttons:

- Top right "Start Exploring" CTA is filled yellow (empty on hover).
- Next "Start Exploring" CTA is empty (yellow on hover).
- Featured Chapter CTA is filled dark blue (empty on hover).
- "See all Contributors" CTA is empty (yellow on hover).
- "Learn about our Methodology" CTA is empty (dark on hover)

Shouldn't these be more consistent UX? Or is the alternating filled/not-filled part of the design?

**Comment by rviscomi** [comment]
> So I still think we should remove it from the header.

I have no strong feelings about this so your idea SGTM.

> @rviscomi can you enable Enhanced Link Attribution in GA->Properties and in Google Analytics tag in GTM to allow this to be seen?

I don't think this will give us much better visibility without also adding unique IDs to the buttons.

> Shouldn't these be more consistent UX? Or is the alternating filled/not-filled part of the design?

At the time our designer gave me a good reason for these but it's not obvious to me now. I agree that we can be more consistent.

**Comment by bazzadp** [comment]
> I don't think this will give us much better visibility without also adding unique IDs to the buttons.

Oh good point! Yes either the link or a parent needs an I’d. Happy to turn these on if I submit a PR with this? Think it would also be good for future anyway in case a question like this arises.

**Comment by bazzadp** [comment]
Going to close this. We solved one of my concerns and the full width home page, while a little inconsistent, isn’t that unusual and is per the design.

**Comment by bazzadp** [comment]
Reopening this after discussion in #947 

I still think we should revisit the home page on ultra-wide monitors. Should we limit this the intor paragraph and icon to a max certain width to avoid the big blank space?:

![Home page on ultra-wide monitor with big grey section in the middle](https://user-images.githubusercontent.com/10931297/86489493-65c0da80-bd5c-11ea-8a29-74e62e1e1dea.png)

Happy for background image to stretch to full width - though need to test that text remains readable aty all widths and we don't lose the grey back ground for any of the white text. E.g. in this extreme example you can see the featured chapter text already has a problem that we should fix as part of this if easy:

![Zoomed out home page](https://user-images.githubusercontent.com/10931297/86506983-5da08380-bdcc-11ea-9359-1ebe8eea56d6.png)

I'd also prefer the navigation menu to be same size as chapters for consistency and to avoid having to scroll right across the screen to use it! This may be fixed as part of #951 

Also, while the contributors can have a higher max than the intro-paragraph/image it probably should still be constrained at some point as above extreme example shows.

**Comment by bazzadp** [comment]
@HTTPArchive/developers anyone with good CSS skills fancy tackling this one?

**Comment by catalinred** [comment]
If that's ok, I'll take a look and try to come up with something.
