### ISSUE TITLE
Finding authors for 2020

### ISSUE THREAD

**Issue by rviscomi** [HTTPArchive/almanac.httparchive.org#593]
I know, I'm supposed to be on vacation, but I had a thought about the 2020 edition that I wanted to write down before I forget. To encourage different perspectives, I think it's important to have new first-time authors. Who better to nominate the 2020 author of a chapter than its 2019 author?

My idea is to ask all 2019 authors to nominate a ranked list of 3 people who they would like to see take over their chapters in 2020. One stipulation I would ask of 2019 authors is to consider nominating people who don't necessarily _think like, look like, nor work with_ them, to ensure we're not creating echo chambers. This is nice because subject matter experts know other experts in that area and can recommend good people. I also think passing the baton is a good way to chain the editions together.

What does everyone think of this strategy? Any other ideas for finding authors?

cc @HTTPArchive/authors

**Comment by bazzadp** [comment]
SGTM. I'd also say the editors of each chapter would be natural fits as well - though perhaps not fitting with the "new voice" you're looking for?

And could also add a tagline to each chapter ("Interested in HTTP/2? We're looking for expert Authors for the 2020 edition to please apply through [our interest form](InterestFormURL)")

**Comment by ozcoder** [comment]
It would be great if we could hear from people _working in the trenches_ trying to improve **legacy** code bases where they still have to support **IE8** and have good progressive enhancement techniques. Note, I am not volunteering for this.
