### ISSUE TITLE
Graphic ressouce: need a French flag

### ISSUE THREAD

**Issue by borisschapira** [HTTPArchive/almanac.httparchive.org#594]
As for the French translation, we are going to need a Français.png (maybe change the way the file is name to remove the diacritic), on the model of https://github.com/HTTPArchive/almanac.httparchive.org/blob/master/src/static/images/English.png, used on the language selector when multiple languages are available.

**Comment by bazzadp** [comment]
Going to close this @borisschapira as already being tracked in https://github.com/HTTPArchive/almanac.httparchive.org/issues/565.
