### ISSUE TITLE
Reviewed the Japanese translation of markup and found a problem

### ISSUE THREAD

**Issue by ksakae1216** [HTTPArchive/almanac.httparchive.org#596]
- Figure 4. Histogram of Hixie's 2005 analysis of element types per page. 日本語訳「2005年にHixieが分析したページ毎の要素タイプのヒストグラム。」に"図４"がない 

- 「フnoframes」 is typo  

- Unnecessary underbar "0.01％でさえ_20万のサイト_"   

- The first part not translated 「Products (and libraries) and their custom markup」    

- 「Figure 10. Other popular elements in the context of product-specific and native elements with under 5% adoption.」 no link comment

**Comment by bazzadp** [comment]
Thanks for reviewing @ksakae1216 but I think for these small tweaks you can go straight to submitting as a pull request. @MSakamaki can then either approve or comment on it and then we can accept it more easily.

**Comment by MSakamaki** [comment]
Thank @ksakae1216 !
I check soon! Please wait for a while.

**Comment by ksakae1216** [comment]
@bazzadp , Thanks for comment.
I see.

**Comment by ksakae1216** [comment]
Thanks @MSakamaki 
I will pull-request from next time
