### ISSUE TITLE
Finalize assignments: Chapter 4. Media

### ISSUE THREAD

**Issue by rviscomi** [HTTPArchive/almanac.httparchive.org#6]
Section | Chapter | Coauthors | Reviewers
-- | -- | -- | --
I. Page Content | 4. Media | @dougsillars @colinbendell @Yonet | @ahmadawais @kornelski

**Due date:** To help us stay on schedule, please complete the action items in this issue by June 3.

**To do:**
- [x] Assign subject matter experts (coauthors)
- [x] Finalize peer reviewers
- [x] Finalize metrics

**Current list of metrics:**

- Image formats
  - Lighthouse data on responsiveness, format, quality, lazy loading
  - adoption of newer image formats like WebP
  - SVG
    - Inline versus external sources (from css or otherwise)
    - comments volume v. total bytes
    - SVGO comparison
  - Microdata usage (og:image, twitter:image, etc)
  - Use of `<source sizes>`
  - Preloader effectiveness (initiator Source: javascript, css, vanilla-html)
  - Fallback image support for legacy devices that don’t support `<picture>` or `<srcset>`
  - Accept-CH in `<meta>` vs http
  - Photographic v. illustration score per pixel
  - Bytes per pixel for photographic
  - Use of Vary (Either User-Agent or Accept)
  - A11y: Support for Alt tags
  - TCP/TLS connection time delay (use of preconnect for cross origin hosts)
  - inlined / base64 image content
- Video formats
  - MP4 sizes, streaming info
  - how many pages are self-serving video (not YouTube)
  - JS player size, 
  - container options (mp4;hevc, v. mp4;avc1 v. webm:vp9, wbem;vp8)
  - Use of posters, autoplay, fallback image
  - A11y: Support for description or fig
- Hero media
  - how many pages include a large "hero" graphic above the fold?
  - Same or different microdata hero images
  - Orientation and pixel volume of hero images
  - Hero video usage
- Emerging media
  - WebXR (TODO @Yonet)

👉**AI (coauthors):** Assign peer reviewers. These are trusted experts who can support you when brainstorming metrics, interpreting results, and writing the report. Ideally this chapter will have 2 or more reviewers who can promote a diversity of perspectives.

👉 **AI (coauthors):** Finalize which metrics you might like to include in an annual "state of web media" report powered by HTTP Archive. Community contributors have initially sketched out a few ideas to get the ball rolling, but it's up to you, the subject matter experts, to know exactly which metrics we should be looking at. You can use [the brainstorming doc](https://docs.google.com/document/d/1sCIMeErYvaQb5x9Acdb6ImYdn0-buHRhYGvz2HoysmM/edit#heading=h.iznoa2266s2c) to explore ideas.

The metrics should paint a holistic, data-driven picture of the web image/video landscape. The HTTP Archive does have its limitations and blind spots, so if there are metrics out of scope it's still good to identify them now during the brainstorming phase. We can make a note of them in the final report so readers understand why they're not discussed and the HTTP Archive team can make an effort to improve our telemetry for next year's Almanac.

**Next steps:** Over the next couple of months analysts will write the queries and generate the results, then hand everything off to you to write up your interpretation of the data.

**Additional resources:**
- [All chapter assignments](https://github.com/HTTPArchive/httparchive.org/issues/140)
- [Project timeline](https://docs.google.com/spreadsheets/d/1LR29JpI2XJSjan_z6uP1YpRy4EYYivYZPqCIG-9sfFY/edit?usp=sharing)
- [About the project](https://discuss.httparchive.org/t/planning-the-web-almanac-2019/1553)

**Comment by rviscomi** [comment]
@Yonet is interested in writing about WebXR. I think that could fit as a subsection of this chapter. @colinbendell @dougsillars @ahmadawais how does that sound?

Not sure what kind of stats we'd be able to extract from HTTP Archive about XR but nonetheless I'm excited to include it as a topic for discussion/exploration. @Yonet what stats/metrics would be representative of "the state of WebXR"? If our dataset can't directly answer those questions we could always cite the data from outside sources.

**Comment by colinbendell** [comment]
cool!

How high do we expect the adoption of WebXR to be? If the adoption rate is
low, I wonder if maybe we should create a different section called
'emerging' to highlight this (and other?) new standards?

thoughts?
/colin

**Comment by rviscomi** [comment]
I do think adoption will be low. Not even sure how to detect it, I'll defer to @Yonet for that. As for how to organize it, I think it could fit in this chapter as a self-contained subsection. I'd prefer keeping it under the "Media" heading than something else that is more miscellaneous.

**Comment by colinbendell** [comment]
sounds good.

**Comment by dougsillars** [comment]
I agree that this will be a VERY low number in HTTP Archive data. I like the idea of "emerging media" as a section.. we could put XR, and perhaps other ideas there too. 

As for detection - I know A-Frame - are there other libraries?  There are 42 sites in April 2019 mobile that reference "aframe.min.js"  A small subset, but an interesting one.

**Comment by rviscomi** [comment]
@dougsillars @colinbendell is your idea to have "Emerging" as a section in the Media chapter, or to create a new chapter?

@Yonet, also curious to hear your thoughts on detection and organization.

**Comment by colinbendell** [comment]
Rick, out of curiosity, does HTTP Archive use an emulated Chrome Mobile, or
does it use the Android build of Chrome Mobile? If it's the actual Android
build, we could better detect XR api use since it's available in that build
(but not on desktop AFAIK).

/colin

**Comment by rviscomi** [comment]
Ah. It's emulated. Does that preclude us from detecting it, or just make it harder?

**Comment by colinbendell** [comment]
I think just harder. I'd let @yonet chime in with ideas for metrics and how
we would collect.

**Comment by kornelski** [comment]
👋

**Comment by rviscomi** [comment]
Hey @kornelski, would you be interested in reviewing this chapter?

**Comment by Yonet** [comment]
@rviscomi I think "Emerging" section makes sense since you still have to turn on experimental flags to be able to use WebXR.

**Comment by rviscomi** [comment]
Agreed. What stats would you want to use to summarize the state of XR?

**Comment by kornelski** [comment]
@rviscomi Yes, if you have any questions about images/compression/optimization I'm happy to help.

**Comment by rviscomi** [comment]
Thanks @kornelski, I've added you as a reviewer and sent you an invitation to join the Reviewers team.

@colinbendell @dougsillars @Yonet @kornelski @ahmadawais  I've pulled in the list of metrics from the brainstorming doc and edited them into the first post of this issue. Please take a look and let us know what you'd change. Today is the last day to change metrics before we hand things off to the Data Analyst team.

@Yonet I still need a couple of things from you. Please go to https://github.com/HTTPArchive and accept the invitation to join the Authors team. This ensures that you get author-specific communications, I can assign issues to you, and you can edit issues like this one. After joining, please edit this issue to include any metrics you'd need to measure the state of WebXR. We don't have any metrics as of now.

**Comment by ahmadawais** [comment]
@rviscomi everything looks on point 👍

**Suggestion**: Can we have a sub-category metric to see how websites use SVGs. Especially when it comes to tools like SVGO that optimize SVGs by removing comments and certain other stuff. Not sure if it's doable.

**Comment by rviscomi** [comment]
Sure, authors/reviewers are free to organize their chapter as they see fit. What metrics would you like to see in an SVG category? That would help us determine whether it's doable.

**Comment by ahmadawais** [comment]
I'd like to be able to see how optimized SVGs are? Are there SVGs with hidden layers and raster images in them. Not sure how that would work, but doing a mass check against SVGs with rules like ones [mentioned here](https://gist.github.com/jaydenseric/1b4cc45a61171ff80d2e8ac49527e515) with a [SVGO](https://github.com/svg/svgo) could be a useful metric.

**Comment by Yonet** [comment]
@rviscomi thank you! I am looking to see what data I am able to get as far as adaption.

**Comment by colinbendell** [comment]
ok. I think we are good here with no shortage of metrics. @yonet can you suggest which metrics you'd want to track?

**Comment by rviscomi** [comment]
@Yonet any update on which WebXR metrics you'd like us to look at?
