### ISSUE TITLE
Add alternate/hreflang link tags for translations

### ISSUE THREAD

**Issue by rviscomi** [HTTPArchive/almanac.httparchive.org#61]
Per https://support.google.com/webmasters/answer/189077 we should make alternate translations discoverable with `<link rel="alternate" hreflang="..." href="...">` elements.

These should be available on every page for all supported translations.

This is basically the metadata/SEO equivalent of #50, so there may be some opportunities to reuse code. cc @tanhengyeow

**Comment by rviscomi** [comment]
@AymenLoukil let me know if you have any questions about the implementation of this feature. Have you tried running the local development environment as a first step?

**Comment by AymenLoukil** [comment]
@rviscomi not yet, i'll try to do it today or tomorrow.

**Comment by AymenLoukil** [comment]
@rviscomi the local environment is set up and running :)
First thing i remarked (not only about hreflang)  : 

- <html lang should have en or ja only without any country code
- Language code for JP
- / and /en/ should not have the same content. The "english" home page will be / or /en/ ? One should redirect to the other.

Regarding the hreflang implementation, should we do it static or dynamic to ensure the mapping is ok (bidirectional hreflang, in case of new translations added etc ?).
Who will develop the feature ?

**Comment by rviscomi** [comment]
> html lang should have en or ja only without any country code. We are targeting people speaking languages wherever they are

Sounds good. In #69 I've added Language objects that have all of the info you need, including both language codes and localized language codes.

> Language code for Japaneese is ja and not jp

Yes, you're right. Is there anywhere that we have it wrong?

> / and /en/ should not have the same content. The "english" home page will be / or /en/ ? One should redirect to the other.

Oh interesting, this is something we've considered before but not for SEO. It would actually simplify the site a lot if we always serve content from the language-specific subdirectories. I'll make a new issue for this.

> Regarding the hreflang implementation, should we do it static or dynamic to ensure the mapping is ok (bidirectional hreflang, in case of new translations added etc ?).

Should be dynamic. In 2019 we will support at least Japanese, Russian, and Spanish, but in future editions we might not have the same support. So it would be great if the template logic can build the hreflangs only for that year's supported languages.

> Who will develop the feature ?

You? :)

**Comment by AymenLoukil** [comment]
Hmm, i've never developed in Flask but i could try.. it should be fun :)

**Comment by AymenLoukil** [comment]
PL #74
