### ISSUE TITLE
Add warning about the costs involved with Google BigQuery

### ISSUE THREAD

**Issue by craigfrancis** [HTTPArchive/almanac.httparchive.org#617]
Just taking a simple query from this repository, and modifying it just a little bit, could easily result in a £126.73 bill... not joking, that's what I've just been charged.

There are no warnings this will happen, no quotas, no limits.

The only thing you will get is a "100% of budget reached" email several hours after the damage has been done.

So please add some warnings, anything, that the SQL examples you provide can be incredibly expensive.

**Comment by bazzadp** [comment]
I think we should add a warning to the Methodology section and also the updated README talked about in #448 ? Maybe with a link to Tim Kadlec’s post on this: https://timkadlec.com/remembers/2019-12-10-using-bigquery-without-breaking-the-bank/

What do you think @rviscomi ?

**Comment by rviscomi** [comment]
I wish the data could be free to analyze but here we are. I'm sorry @craigfrancis for the unpleasantly surprising bill :confounded: 

+1 to all of @bazzadp's suggestions.

**Comment by bazzadp** [comment]
Added some suggested text in #618. @craigfrancis couldn't add you as a reviewer but feel free to comment on the PR.

**Comment by bazzadp** [comment]
Note have left the README out of this as can do in #448

**Comment by craigfrancis** [comment]
Thanks @bazzadp, I think that will help.

Just on a personal note, thinking about the pages I viewed before experimenting, I did check over the README first (so an update on that would be good), and I think the Getting Started page on the main HTTP Archive page would also be useful as well (I've just created a separate issue on that project).
