### ISSUE TITLE
Ensure Google Cloud Components is back on latest version

### ISSUE THREAD

**Issue by bazzadp** [HTTPArchive/almanac.httparchive.org#619]
As noted in https://github.com/HTTPArchive/almanac.httparchive.org/pull/533#issuecomment-557672159 I had to downgrade Google Cloud Components to get it to deploy because of an issue with Google Cloud at the time.

As noted in the [stackoverflow issued linked from above](https://stackoverflow.com/questions/59000291/cant-deploy-to-app-engine-standard-with-gcloud-components-272-0-0) this is now resolved, so putting this as a reminder to upgrade this again to latest with next deploy.

**Comment by bazzadp** [comment]
BTW did you see this @rviscomi if you are doing a deployment?

**Comment by rviscomi** [comment]
Thanks for the heads up. I did see it, but my installation seems to be ok.

**Comment by bazzadp** [comment]
Ah this my local env rather than something that's included in the deploy. OK will close. Sorry not too familiar with this Gcloud stuff!
