### ISSUE TITLE
Website architecture design

### ISSUE THREAD

**Issue by AymenLoukil** [HTTPArchive/almanac.httparchive.org#63]
I have some questions / remarks :

- Is there somewhere a document describing the target architecture of the Almanac website  (information architecture, URL structure) ? 
- I understood from reading the issues, that we aim to have a static page and every year version should go under a dedicated sub-folder /2019, /2020..etc. IMHO, it would be better to rather have this setup : 

Every year we put the content on the root (HP contains static + dynamic insights of the current version), /outline for the current outline, etc... and when we publish a new edition, we archive previous ones on subfolders.

Example : 
2019 in the main generic 'website'
2018 content goes on /2018 folder
And when we publish 2020 version, main generic 'website' should get updated with 2020 data
and we archive 2019 on /2019 folder...Etc

The pros of this method :  
- People who search for Almanac insights they find them on the root of the website, simpler. it's trivial for them to find and go to the current version
- The generic website will gain value over the years, while still allowing the older versions to be accessible if someone explicitly looks for them

What do you think ? @rviscomi

**Comment by rviscomi** [comment]
cc @HTTPArchive/developers in case anyone else wants to share their thoughts

We do currently plan to use the home page to showcase the latest version of the Almanac. Once a user lands there and drills down into the report, the URL would update to the 2019 version. We should always organize contents by year on the backend, but I'd be open to having "shorthand" URLs that omit the year and default to the latest year, similar to what we're doing on the home page.

One argument against that would be for URLs that are not backwards compatible. We should never end up in a situation where an old URL no longer works, for example if someone shares a deeplink to a specific chapter/metric, but that metric/chapter is only available in 2019. Including the year in the URL ensures that no matter when the URL is visited, it will always produce the expected results. @AymenLoukil does your suggestion account for that?

**Comment by AymenLoukil** [comment]
Defining the information architecture should answering these questions.

Consider current Mobile web chapter link : almanac.httparchive.org/mobile-web 
This page shows the current version of this year + (i suggest) links to Mobile web chapters of previous years (2018, 2017...) 
So that when some one bookmarks / links to this URL, we are sure that he will find the information.
Mobile web chapter of 2018 would always be here  almanac.httparchive.org/2018/mobile-web 

I also would love to hear  @HTTPArchive/developers thoughts on it @rviscomi

**Comment by rviscomi** [comment]
There's no guarantee that a particular chapter will be persistent throughout all versions of the Almanac. Mobile web will probably continue to be important, but you can imagine how a chapter like HTTP/2 would become outdated at some point and we might start talking about HTTP/3 or whatever.

(Also there is no 2018 version, 2019 is the first one)

**Comment by AymenLoukil** [comment]
> There's no guarantee that a particular chapter will be persistent throughout all versions of the Almanac. Mobile web will probably continue to be important, but you can imagine how a chapter like HTTP/2 would become outdated at some point and we might start talking about HTTP/3 or whatever.

Good point. I didn't thought about it
> (Also there is no 2018 version, 2019 is the first one)

Yes i know, it was just for the example.
