### ISSUE TITLE
Production missing a style

### ISSUE THREAD

**Issue by bazzadp** [HTTPArchive/almanac.httparchive.org#632]
Production is missing a [bold style for the subtitle](https://github.com/HTTPArchive/almanac.httparchive.org/blob/ae574f0796756239a91f9670cb32ac39f34ff5d0/src/static/css/2019.css#L338) despite the recent merge from master.

Not sure how it got in there but it’s been there for a while as noticed before and been meaning to investigate for a bit.

@rviscomi should we rebase production from master or just fix this directly in production branch (this is the only difference)?

**Comment by rviscomi** [comment]
Yeah that's weird. `production` should be identical to `master` at this point.

**Comment by bazzadp** [comment]
I've fixed this in a [separate commit](https://github.com/HTTPArchive/almanac.httparchive.org/commit/aa28265ebbf810345d72bfb91377273a83ac9d5f) for now and deployed to production branch.

I still think we should rebase to master branch even though technically the branches have the same code now, but am not a Git expert so will leave this open for other opinions.

@rviscomi I was going to release this to production (this and the translated by bug #635 are annoying me). However when I tried this was deployed to https://webalmanac.appspot.com instead of https://almanac.httparchive.org/. Any ideas why?

I also don't have permission to list deployments to try to change this:
```
barry@MacBook src % gcloud deployment-manager deployments list
ERROR: (gcloud.deployment-manager.deployments.list) ResponseError: code=403, message=Required 'deploymentmanager.deployments.list' permission for 'projects/webalmanac'
```

**Comment by bazzadp** [comment]
Oh wait, not it seems to be on production but it wasn't earlier. Weird. Is https://webalmanac.appspot.com 
 the same as https://almanac.httparchive.org? Or does it just take a while to deploy from one to the other?

**Comment by bazzadp** [comment]
Actually I think this is due to our caching headers added in #608 . Now production changes may take a while to roll out as Google Cloud caches them. Looking at chapters I haven't looked at are fine and show new changes, but chapters I was already looking at are still returning old pages (even on a different browser). Will check again in 3 hours (default caching policy) but may want to consider lowering this 3 hour limit.

**Comment by bazzadp** [comment]
Going to close this as ws resolved in https://github.com/HTTPArchive/almanac.httparchive.org/commit/aa28265ebbf810345d72bfb91377273a83ac9d5f.
