### ISSUE TITLE
Chapter slugs and image directories based on title so don't work for Translations

### ISSUE THREAD

**Issue by bazzadp** [HTTPArchive/almanac.httparchive.org#654]
main.py has the following:

https://github.com/HTTPArchive/almanac.httparchive.org/blob/7015c954088b525b95a2ee0179c94ea56d92e67c/src/main.py#L60-L68

This means we use the chapter title from the meta data to get the chapter slug (for the ToC) and the chapter image directory (for the chapter hero images and figures).

This does not work if we translate the title as @borisschapira has done for #652 and @SilentJMA did for #539 

I think we should change these two functions to be based on either:
1. The md or html filename (ideally at chapter generation so we're not dependent on doing this at runtime and being dependent on the URL which is user supplied data so shouldn't be trusted - at least without verification).
2. The config - but not sure how to map this (based on the part and chapter number from the meta data?).

I know we've talked about a larger restructure of the config in #561 and even changing how the chapters are generated completely in #634 but we don't seem to be making progress on those so think we need to do something in the short term to address this issue as it prevents viewing the chapters with images in another language (for checking PRs in dev) and will obviously prevent going live with any translations in prod.

@mikegeyser any thoughts?

**Comment by borisschapira** [comment]
My 2 cents: extrapolating the slug from the filename, and using it to build the dirname are common practices in the SSG world, so this seems ok for me, rather that using the translated title.
