### ISSUE TITLE
Attribute scope to add to some tables

### ISSUE THREAD

**Issue by nico3333fr** [HTTPArchive/almanac.httparchive.org#657]
Related to https://github.com/HTTPArchive/almanac.httparchive.org/pull/652/files#r372970689 we should add `scope="col"` to table headings, this is better for accessibility:

Example: 

```
<table>
    <tr>
     <th>Resource Hint</th>
     <th>Utilisation (pourcentage de sites)</th>
    </tr>
```

Would give:

```
<table>
    <tr>
     <th scope="col">Resource Hint</th>
     <th scope="col">Utilisation (pourcentage de sites)</th>
    </tr>
```

**Comment by bazzadp** [comment]
[W3 table guidelines](https://www.w3.org/WAI/tutorials/tables/) seems to suggest we only need it on complex tables:

> Header cells must be marked up with `<th>`, and data cells with `<td>` to make tables accessible. For more complex tables, explicit associations may be needed using scope, id, and headers attributes.

WebAIM table guidelines](https://webaim.org/techniques/tables/data) are a bit less cautious and advises to always add it:

> All `<th>` elements should generally always have a scope attribute. While screen readers may correctly guess whether a header is a column header or a row header based on the table layout, assigning a scope makes this unambiguous.

[MDN table guidelines](https://developer.mozilla.org/en-US/docs/Learn/HTML/Tables/Advanced#The_scope_attribute) are less strict (emphasis my own):

> A new topic for this article is the scope attribute, which _can_ be added to the `<th>` element to tell screenreaders exactly what cells the header is a header for — is it a header for the row it is in, or the column, for example?

I think ares are all simple tables and while [a few are slightly more complex](https://almanac.httparchive.org/en/2019/caching#fig-4), I'm not 100% convinced on the need for this. They also weren't flagged by any of the Accessibility tools in #645 .

Saying that, I am aiming for this website to be the crème de la crème of best practices so certainly won't complain if this gets added by someone!

**Comment by bazzadp** [comment]
Though while we're looking at this it does flag that we should use `<td></td>` instead of `<th></th>` for blank headers:

i.e. this:

```
<figure id="fig-4">
  <div class="table-wrap">
    <div class="table-wrap-container">
      <table>
        <tbody>
          <tr>
            <th></th>
            <th colspan="5">Desktop Cache TTL Percentiles (Hours)</th>
          </tr>
          <tr>
            <th></th>
            <th>10</th>
            <th>25</th>
```
  
	

should really be this:

```
<figure id="fig-4">
  <div class="table-wrap">
    <div class="table-wrap-container">
      <table>
        <tbody>
          <tr>
            <td></td>
            <th colspan="5">Desktop Cache TTL Percentiles (Hours)</th>
          </tr>
          <tr>
            <td></td>
            <th>10</th>
            <th>25</th>
```
  
Looks weird to me but apparently that's best for accessibility! So if fixing above, then we should fix that too at the same time.

**Comment by rviscomi** [comment]
Looks weird to me too, but it can't hurt so let's go for it.
