### ISSUE TITLE
Home page background color glitching

### ISSUE THREAD

**Issue by rviscomi** [HTTPArchive/almanac.httparchive.org#668]
I think this is related to #664. Playing with the `header.alt-bg` style rule's `background` style seems to toggle this glitch.

It's very fickle: it appears on page load, disappears when I open dev tools at the bottom of the screen, and reappears if I move dev tools to a separate window. If I had to guess there's something weird going on related to these styles:

```css
padding-bottom: 900px;
margin-bottom: -900px;
```

![image](https://user-images.githubusercontent.com/1120896/74563482-e496b180-4f3a-11ea-8039-350dd76de651.png)

**Comment by rviscomi** [comment]
Here's my info for debugging

Chrome version 80.0.3987.87 (Official Build) (64-bit)
MacOS Mojave version 10.14.6
Viewport width: 1312, height: 1338

**Comment by bazzadp** [comment]
Yeah got it. It's to do with #664 rather than this one. Will submit a separate PR to fix that. That's one tall screen you have there Mr!!

**Comment by rviscomi** [comment]
5K iMac 😎

**Comment by bazzadp** [comment]
Fixed in #666 in https://github.com/HTTPArchive/almanac.httparchive.org/pull/666/files#diff-dcfbc15530630ce0591f21b62fbb1237
