### ISSUE TITLE
Build custom error pages

### ISSUE THREAD

**Issue by rviscomi** [HTTPArchive/almanac.httparchive.org#68]
@HTTPArchive/developers 

If an unexpected error occurs on the server (5xx) or there's an issue with user input (4xx) we should show an error page with more information about what went wrong.

**Comment by tanhengyeow** [comment]
Hi @rviscomi 

Would be interested in this 😄 Which approach do you recommend?
1. Take inspiration from the error pages of https://httparchive.org/
2. Implement as per design mockups (not sure if there are any at the moment)
3. Implement a skeleton layout first and iterate on the design/layout later

**Comment by rviscomi** [comment]
I'd suggest 3 to get started. Thanks for working on this @tanhengyeow!
