### ISSUE TITLE
Add ability to filter contributors by team

### ISSUE THREAD

**Issue by rviscomi** [HTTPArchive/almanac.httparchive.org#73]

**Comment by tanhengyeow** [comment]
Some thoughts of the possible approaches:
1. Implement labeled tags of team names. When the tag of a team is selected, the page would display only contributors from that team. More than 1 tag may be selected. This would probably the approach that solves this issue directly.

2. Implement a search bar. Gives users more control of what to search/filter but it might be more complex to implement compared to point 1.

**Comment by rviscomi** [comment]
Yes I like the first approach. At the top of the page we can show all available team tags and they'd have selected/deselected states. The designer will be working on the overall UX but we can get started on the JS to handle the interactivity.

For the implementation, I think we could go a simple route by adding a CSS class for each team a contributor is a member of to that contributor's wrapper element. Hiding/showing contributors of a certain team can be done by querying the class names and toggling their display style.

**Comment by rviscomi** [comment]
@tanhengyeow can I assign this to you?
