### ISSUE TITLE
Improve hover state of chapter results/queries button icons

### ISSUE THREAD

**Issue by rviscomi** [HTTPArchive/almanac.httparchive.org#738]
On hover or focus, the icons in the "View results" and "View queries" buttons turn yellow.

![image](https://user-images.githubusercontent.com/1120896/79669828-6e0d6e80-818c-11ea-9345-f8ede9aad4c5.png)

![image](https://user-images.githubusercontent.com/1120896/79669823-664dca00-818c-11ea-87a7-8a77ab76716a.png)

The hover states for these icons could be improved slightly:

- only highlight the lines of the results icon, don't fill it in (similar to the comments icon)
- remove the distortion in the queries icon

Since the yellow is applied as a CSS filter, I think this can be solved by editing the icons themselves to use transparency for anything other than the gray lines/letters.

**Comment by bazzadp** [comment]
I'd love these to be SVGs as they look a bit pixelated at present.

Been chatting to @catalinred and trying to persuade him back to the project for a bit to take this on 😀

**Comment by bazzadp** [comment]
We should also move the dropdown arrow to an SVG at same time, for same reason. Ref: #729

**Comment by bazzadp** [comment]
Closing this now this immediate problem highlighted by this work has been solved. Opened #740 for the remaining work.
