### ISSUE TITLE
Move simple PNG icons to SVG

### ISSUE THREAD

**Issue by bazzadp** [HTTPArchive/almanac.httparchive.org#740]
As a follow on from #738, the below PNGs don't scale well on large screens, or when zoomed in. As they are all simple (or have Vector versions for GitHub/Twitter) we should move them to SVG format.

- [ ] discuss.png
- [ ] results.png
- [ ] queries.png
- [ ] dropdown-arrow.png
- [ ] close.png
- [ ] menu.png
- [ ] blog.png
- [ ] github.png - [Official link to Vector icons](https://github.com/logos)
- [ ] twitter.png - [Official link to SVG icons](https://github.com/logos).

Note some of these need a hover state version (the first 3 - but the dropdown-arrow, blog, github and twitter would also benefit from having this so maybe can solve at same time?).

**Comment by catalinred** [comment]
I'll add this [comment ](https://github.com/HTTPArchive/almanac.httparchive.org/pull/549#issuecomment-559030227) as a reminder to myself and will get back when I'll have a plan on "svgify" the assets.
