### ISSUE TITLE
Generate GitHub action broken due to permission changes

### ISSUE THREAD

**Issue by bazzadp** [HTTPArchive/almanac.httparchive.org#767]
@rviscomi we now get this when generate GitHub action runs ([see here](https://github.com/HTTPArchive/almanac.httparchive.org/runs/638419637?check_suite_focus=true)):

```
Commiting changes
[master 177796e] Regenerated chapters
 3 files changed, 499 insertions(+), 1 deletion(-)
 create mode 100644 src/templates/ja/2019/chapters/media.html
remote: error: GH006: Protected branch update failed for refs/heads/master.        
remote: error: You're not authorized to push to this branch. Visit https://help.github.com/articles/about-protected-branches/ for more information.        
To https://github.com/HTTPArchive/almanac.httparchive.org
 ! [remote rejected] master -> master (protected branch hook declined)
error: failed to push some refs to 'https://github.com/HTTPArchive/almanac.httparchive.org'
##[error]Process completed with exit code 1.
```

This is even though this runs under my id.

This is because even those with write permissions to master (i.e. you and I) need to approve changes and that doesn't work with GitHub actions.

Can you and I be given permission to commit directly to master?

**Comment by bazzadp** [comment]
@rviscomi you had [two conditions on the master branch protection rule](https://github.com/HTTPArchive/almanac.httparchive.org/settings/branch_protection_rules/15668314):

1. Everyone (including us) needs to have at least one review.
2. Only a maintainer (currently you or I) can push to master.

I don't think we need both, so have turned the first off.

That fixes this, without needing to do a force commit proposed in #768 , with the downsides that has.

That change also means I can merge my own requests (and you yours) whereas previously we could not approve our own, and so needed someone else's approval. Now we try not to merge without at least one approver (except for trivial changes) but, as administrators we can do this anyway (I overrode this restriction for #766 for example because GitHub allowed me to with an extra click) so not sure it's that great a check anyway. Please if we merge someone else's PR then to me that's an implicit approval anyway.

So, are you happy to not have restriction 1 and only have 2? If so we can close this.

**Comment by rviscomi** [comment]
SGTM! Pains of managing a large repo.
