### ISSUE TITLE
Wrong axis labels for Compression charts

### ISSUE THREAD

**Issue by rviscomi** [HTTPArchive/almanac.httparchive.org#804]
Figures [5](https://almanac.httparchive.org/en/2019/compression#fig-5) and [6](https://almanac.httparchive.org/en/2019/compression#fig-6) of the Compression chapter have mislabeled axes.

![image](https://user-images.githubusercontent.com/1120896/81250018-fe054200-8fed-11ea-8b46-84a5bcb2e2f5.png)

Both should have "Content Type" as the y-axis label and "Number of requests" for the x-axis label.

![image](https://user-images.githubusercontent.com/1120896/81250198-589e9e00-8fee-11ea-8466-2ca18685ccad.png)

Figures 7 and 8 should also be updated to say "Content Type" on the y-axis. Verify the data type to make sure "Percent of requests" is correct for the x-axis.

![image](https://user-images.githubusercontent.com/1120896/81250182-4e7c9f80-8fee-11ea-8358-25b60bff669a.png)

Figures 11 and 12 should have the y-axis labels removed. Verify the data type to make sure "Percent of requests" is correct for the x-axis.

**Comment by bazzadp** [comment]
@rviscomi I sent a request for edit access to this sheet and then can fix this. Just resent there now.

**Comment by bazzadp** [comment]
Friendly ping @rviscomi - can you approve my write access? Or fix yourself :-)
Might as well get this simple in the first eBook launch I'm planning on doing this weekend!

**Comment by rviscomi** [comment]
I think @paulcalvano actually owns this sheet. Paul if so could you give Barry access?

**Comment by bazzadp** [comment]
Well that explains why you're uncharacteristically ignoring me then 😀

**Comment by paulcalvano** [comment]
Oh sorry!   Just gave you access!
