### ISSUE TITLE
Translate language-specific Almanac tweets

### ISSUE THREAD

**Issue by rviscomi** [HTTPArchive/almanac.httparchive.org#809]
I'd like to tweet about the amazing work we've been doing to translate the Almanac into multiple languages. Rather than writing it in English, I think it would be much more impactful if we tweet in the languages we're promoting:

- [x] Spanish
- [x] French
- [x] Japanese

Each language will be featured in its own tweet with a link to that language's home page. The text to translate could be:

> Do you speak [English]? With the help of community translators, the 2019 Web Almanac is now available in [English]! Start exploring and share your findings with the web community!
> 🌐 https://almanac.httparchive.org/[en]/2019/

_(replace [English] with the translated language)_

Open to other ideas for content. We could try to say something about the number of chapters that have been translated, for example highlighting that the entire 20 chapters are available in Japanese.

cc @HTTPArchive/translators @bazzadp

**Comment by rviscomi** [comment]
Assigned translators for each language. If you're able to translate the tweet text in the top comment, add it as a comment to this thread. If not, let me know and we'll find someone else. In any case, I really appreciate your help and I'm looking forward to celebrating your translation efforts!

**Comment by ksakae1216** [comment]
@rviscomi , OK, I translated japanese.

> 日本語を話せますか？コミュニティの翻訳者の協力を得て、2019 Web Almanacが日本語で利用可能になりました。探索を開始して、Webコミュニティーで発見を共有してください！ 🌐https://almanac.httparchive.org/ja/2019/

**Comment by borisschapira** [comment]
Hey, great idea, here's a French version. I've added "(en partie)" which means "partly", as we didn't finish (yet).

> Vous parlez Français ? Grâce à l'aide de notre communauté de traducteur, le Web Almanac 2019 est (en partie) disponible en Français! N'hésitez pas à le parcourir et à partager vos découvertes avec la communauté du web !
🌐 https://almanac.httparchive.org/fr/2019/

**Comment by taytus** [comment]
Here is the Spanish version. 

 

> ¿Hablas Español? Con la ayuda de la comunidad de traductores, ¡el Web Alamanac se encuentra disponible en Español! Comienza a explorar y ¡comparte tus descubrimeientos con la comunidad web!
> 🌐 https://almanac.httparchive.org/es/2019/

**Comment by rviscomi** [comment]
Thanks everyone!

**Comment by rviscomi** [comment]
I'll post these throughout the week. Starting with Japanese today:

Japanese: https://twitter.com/HTTPArchive/status/1259655133249576963

**Comment by bazzadp** [comment]
Presume we’re good to close this @rviscomi since they’ve all gone out now?

**Comment by rviscomi** [comment]
Yes, thanks everyone!
