### ISSUE TITLE
Query metrics: Chapter 1. JavaScript

### ISSUE THREAD

**Issue by rviscomi** [HTTPArchive/almanac.httparchive.org#82]
Part | Chapter | Authors | Reviewers | Tracking Issue
-- | -- | -- | -- | --
I. Page Content | 1. JavaScript | @addyosmani @housseindjirdeh @mathiasbynens | @rwaldron @RReverser | #3

# READ ME!
All of the metrics in the table below have been marked as `Able To Query` during the [metrics triage](https://github.com/HTTPArchive/almanac.httparchive.org/issues/33). The analyst assigned to each metric is expected to write the corresponding query and submit a PR to [have it reviewed and added to the repo](https://github.com/HTTPArchive/almanac.httparchive.org/issues/62).

In order to stay on schedule and have the data ready for authors, **please have all metrics reviewed and merged by August 5**.

## Assignments

ID | Metric description | Analyst | Notes
-- | -- | -- | --
01.01 | Distribution of JS bytes | @rviscomi |  
01.02 | Distribution of first party JS bytes vs. third party | @rviscomi |  
01.03 | Number of JS requests | @rviscomi |  
01.04 | Number of first-party JS requests vs. third-party | @rviscomi |  
01.05 | % of gzip-compressed scripts | @rviscomi |  
01.06 | % of brotli-compressed scripts | @rviscomi |  
01.07 | Breakdown of V8 CPU times (if feasible) | @rviscomi | Confirm with pmeenan that the CPU timing is enabled
01.08 | Top N JS libraries | @rviscomi |  
01.09 | Notable changes in popularity since last year | @rviscomi |  
01.10 | Top N JS client-side frameworks (React, Vue, etc…) | @rviscomi |  
01.11 | Distribution of JS bytes on site per JavaScript framework | @rviscomi |  
01.12 | % of pages that use `<script type=module>` | @rviscomi | Added custom metric
01.13 | % of pages that use `<script nomodule>` | @rviscomi | Added custom metric
01.14 | % of pages that use `<link rel=preload>` for JS resources | @rviscomi | Resolved by link-nodes custom metric
01.15 | % of pages that use `<link rel=modulepreload>` | @rviscomi | Easiest as a DOM query
01.16 | % of pages that use `<link rel=prefetch>` for JS resources | @rviscomi | Easiest as a DOM query
01.18 | Atomics | @rviscomi |  
01.19 | Intl | @rviscomi |  
01.20 | Proxy | @rviscomi |  
01.21 | SharedArrayBuffer | @rviscomi |  
01.22 | WeakMap | @rviscomi |  
01.23 | WeakSet | @rviscomi |  
01.24 | dynamic import (by looking for "import(") | @rviscomi |  
01.25 | % of sites that ship sourcemaps | @rviscomi | X-SourceMap header or //# sourceMappingURL= in JS

## Checklist of metrics to be merged

- [x] 	01.01	Distribution of JS bytes
- [x] 	01.02	Distribution of first party JS bytes vs. third party
- [x] 	01.03	Number of JS requests
- [x] 	01.04	Number of first-party JS requests vs. third-party
- [x] 	01.05	% of gzip-compressed scripts
- [x] 	01.06	% of brotli-compressed scripts
- [x] 	01.07	Breakdown of V8 CPU times (if feasible)
- [x] 	01.08	Top N JS libraries
- [x] 	01.09	Notable changes in popularity since last year
- [x] 	01.10	Top N JS client-side frameworks (React, Vue, etc…)
- [x] 	01.11	Distribution of JS bytes on site per JavaScript framework
- [x] 	01.12	% of pages that use `<script type=module>`
- [x] 	01.13	% of pages that use `<script nomodule>`
- [x] 	01.14	% of pages that use `<link rel=preload>` for JS resources
- [x] 	01.15	% of pages that use `<link rel=modulepreload>`
- [x] 	01.16	% of pages that use `<link rel=prefetch>` for JS resources
- [x] 	01.18	Atomics
- [x] 	01.19	Intl
- [x] 	01.20	Proxy
- [x] 	01.21	SharedArrayBuffer
- [x] 	01.22	WeakMap
- [x] 	01.23	WeakSet
- [x] 	01.24	dynamic import (by looking for "import(")
- [x] 	01.25	% of sites that ship sourcemaps

**Comment by rviscomi** [comment]
👋 Hey @mathiasbynens, for the "Breakdown of V8 CPU times" metric, which metrics in particular would you like to analyze?

For reference, [here's a JSON blob](https://gist.githubusercontent.com/rviscomi/33082ab7af9a307bd098bf3c8b1df771/raw/7a452fa72f424327f6b98574c39a6bad46443ee7/http-archive-har-payload.json) of all of the data we have. And [here's a list of metrics](https://gist.githubusercontent.com/rviscomi/33082ab7af9a307bd098bf3c8b1df771/raw/7a452fa72f424327f6b98574c39a6bad46443ee7/v8%2520metrics) prefixed with cpu and v8 that you might find interesting. There are lots of them.

**Comment by mathiasbynens** [comment]
Those metrics are highly fine-grained. For this report, it'd make sense to [combine them into higher-level buckets](https://cs.chromium.org/chromium/src/v8/tools/callstats.html?l=1719-1739&rcl=46afc4f9a6008c3880fcc00783b4210cb467aa9a). I'd propose the following:

- main thread parse time
- main thread compile time
- main thread optimize time
- main thread execution time

**Comment by mathiasbynens** [comment]
If the above is too much hassle, we could just add up everything under "main thread". (Background work is not interesting, as it doesn't delay page load.)

**Comment by rviscomi** [comment]
Thanks @mathiasbynens. I've saved the results of the cumulative main thread time query to [this sheet](https://docs.google.com/spreadsheets/d/1kBTglETN_V9UjKqK_EFmFjRexJnQOmLLr-I2Tkotvic/edit?usp=sharing). Let me know if those numbers look reasonable to you or if you'd like to see the results formatted differently (histogram, quantiles, etc).
