### ISSUE TITLE
Translate ebook templates into Japanese

### ISSUE THREAD

**Issue by bazzadp** [HTTPArchive/almanac.httparchive.org#823]
As discussed in https://github.com/HTTPArchive/almanac.httparchive.org/pull/817#issuecomment-627338360 we need the following temples reviewed to allow us to launch the Japanese ebook completely in Japanese:

- `templates/ja/2019/base.html`
- `templates/ja/2019/base_ebook.html`

Just a few phrases that need translating into Japanese.

**Comment by ksakae1216** [comment]
OK, I will translate of base.html quickly.

**Comment by rviscomi** [comment]
You're the best @ksakae1216, thank you for all of your contributions!
