### ISSUE TITLE
Should we keep the Google Sheets embeds?

### ISSUE THREAD

**Issue by bazzadp** [HTTPArchive/almanac.httparchive.org#826]
Currently we use Google Sheets embeds for interactive visuals.

However I'm not sure they actually give us that much. They have a nice hover-over affect and give a bit more data on some of the charts (e.g. the detailed charts in the [Performance chapter](https://almanac.httparchive.org/en/2019/performance)).

**Downsides**

These are quite hefty in terms of JavaScript. See [these WPT for runs](https://www.webpagetest.org/video/compare.php?tests=200514_DT_6942bb1be63eb2830b1121423a70006e%2C200514_P2_e9ecdfab868ef1680e5d296a8c7e1d06&thumbSize=200&ival=100&end=visual#) comparing loading with the embedded sheets versus with just the fallback images for the Performance chapter for example, and also these Lighthouse comparisons:

![Lighthouse scores of 78 for Performance, 100 for Accessibility, 79 for Best Practices and 100 for SEO for normal chapter](https://user-images.githubusercontent.com/10931297/81992878-6c748080-963c-11ea-8b2a-4a44af213a5e.png)

![Lighthouse scores of 82 for Performance, 100 for Accessibility, 100 for Best Practices and 100 for SEO for Print URL](https://user-images.githubusercontent.com/10931297/81992913-7dbd8d00-963c-11ea-9a91-5822853a1371.png)

They also potentially have accessibility issues: FireFox accessibility audit complains of missing titles and label for them, even though the iframe itself has a title, and has aria labels and descriptions. So not sure if this is a real issue or not.

The have caused issues in the past (e.g. [not displaying on iPads](https://github.com/HTTPArchive/almanac.httparchive.org/issues/432), or [when blocked](https://github.com/HTTPArchive/almanac.httparchive.org/issues/428)), but they were all solved and not heard of any issues since.

**Reasons to drop:**
- Performance
- Accessibility
- Don't actually give us that much.
- Reduce complexity
- Have links to sheets for those that want it as of #728 
- Double downloads as download images first, then upgrade to Sheets

**Reasons to keep:**
- Need to create them anyway to create the images.
- Another way of exploring the data, and we are data centric.
- Not causing any major performance issues. Even the WPT and Lighthouse tests show they are pretty close.
- We use Lazy-loading iframes, so double downloading should be minimal, as should performance impact.
- It works! If it ain't broke don't fix it...
- We only enable them on larger screens anyway and if they will work, so should only be used when we have processing power to manage.
- Accessibility issues are questionable and may be false positives.

Thoughts?

**Comment by rviscomi** [comment]
As I wrote via DM, these are all valid points. I'm inclined to keep the charts the way they are. We've (mostly you have 😄) done a lot of work to optimize the embedded Sheets viz and I think the drop in 2019 readership has tapered off enough that further work is probably not worth the effort. Where we should be investing more effort is in 2020 data viz and my hope is that we can have something that is fast, accessible, and translation-friendly. If that's still too ambitious then we can revisit the Sheets approach for the 2020 edition.

**Comment by bazzadp** [comment]
Yup that's cool, Was in two minds myself, Closing for now.
