### ISSUE TITLE
Query metrics: Chapter 4. Media

### ISSUE THREAD

**Issue by rviscomi** [HTTPArchive/almanac.httparchive.org#85]
Part | Chapter | Authors | Reviewers | Tracking Issue
-- | -- | -- | -- | --
I. Page Content | 4. Media | @dougsillars @colinbendell @Yonet | @ahmadawais @kornelski | #6

# READ ME!
All of the metrics in the table below have been marked as `Able To Query` during the [metrics triage](https://github.com/HTTPArchive/almanac.httparchive.org/issues/33). The analyst assigned to each metric is expected to write the corresponding query and submit a PR to [have it reviewed and added to the repo](https://github.com/HTTPArchive/almanac.httparchive.org/issues/62).

In order to stay on schedule and have the data ready for authors, **please have all metrics reviewed and merged by August 5**.

## Assignments

ID | Metric description | Analyst | Notes
-- | -- | -- | --
04.01 | Lighthouse data on responsiveness, format, quality, lazy loading | @dougsillars |  
04.02 | adoption of newer image formats like WebP | @dougsillars |  
04.03 | SVG | @dougsillars | we should look a inline svgs in responses in addition to explicit responses
04.04 | Inline versus external sources (from css or otherwise) | @dougsillars | see above
04.05 | Microdata usage (og:image, twitter:image, etc) | @dougsillars |  
04.06 | Use of `<source sizes>` | @dougsillars |  
04.07 | Preloader effectiveness (initiator Source: javascript, css, vanilla-html) | @dougsillars | Im sure we can query *how many* are preloaded, and the source of the preload (and compare to other objects being preloaded, but how would we measure 'effectiveness'
04.08 | Fallback image support for legacy devices that don’t support `<picture>` or `<srcset>` | @dougsillars |  
04.09 | Accept-CH in `<meta>` or http | @dougsillars |  
04.11 | Bytes per pixel for photographic | @dougsillars | will require h&w of each image to get pixel count.. While we are at it - could we get the size it is rendered on the page too - image sizing effectiveness? natural height and intrinsic height (and widths)
04.12 | Use of Vary (Either User-Agent or Accept) | @dougsillars |  
04.13 | A11y: Support for Alt tags | @dougsillars |  
04.14 | TCP/TLS connection time delay (use of preconnect for cross origin hosts) | @dougsillars | We have DNS lookup data for each file... Can look for cross origin images, with and without preconnect
04.15 | MP4 sizes, streaming info | @dougsillars | Sizes in MB is feasible.  Dimensions would require custom metric.  (combine with the image dimensions??)
04.16 | how many pages are self-serving video (not YouTube) | @dougsillars |  
04.17 | JS player size, | @dougsillars |  
04.19 | Use of posters, autoplay, fallback image | @dougsillars |  
04.20 | A11y: Support for description or fig | @dougsillars |  
04.21 | how many pages include a large "hero" graphic above the fold? | @dougsillars | _heroElementTimes.Image
04.25 | WebXR | @dougsillars | we can query for a-frame or other XR libraries on a page.  This will be a *very* small number of sites

## Checklist of metrics to be merged

- [x] 	04.01	Lighthouse data on responsiveness, format, quality, lazy loading
- [x] 	04.02	adoption of newer image formats like WebP
- [x] 	04.03	SVG
- [x] 	04.04	Inline versus external sources (from css or otherwise)
- [ ] 	04.05	Microdata usage (og:image, twitter:image, etc)
- [x] 	04.06	Use of `<source sizes>`
- [ ] 	04.07	Preloader effectiveness (initiator Source: javascript, css, vanilla-html)
- [x] 	04.08	Fallback image support for legacy devices that don’t support `<picture>` or `<srcset>`
- [x] 	04.09	Accept-CH in `<meta>` or http
- [x] 	04.11	Bytes per pixel for photographic
- [x] 	04.12	Use of Vary (Either User-Agent or Accept)
- [x] 	04.13	A11y: Support for Alt tags
- [x] 	04.14	TCP/TLS connection time delay (use of preconnect for cross origin hosts)
- [x] 	04.15	MP4 sizes, streaming info
- [x] 	04.16	how many pages are self-serving video (not YouTube)
- [x] 	04.17	JS player size,
- [x] 	04.19	Use of posters, autoplay, fallback image
- [x] 	04.20	A11y: Support for description or fig
- [x] 	04.21	how many pages include a large "hero" graphic above the fold?
- [x] 	04.25	WebXR

**Comment by dougsillars** [comment]
pull request 1 in.
still missing
04_05
04_07
04_11
04_14
04_21

**Comment by rviscomi** [comment]
What's up with `04.06`? Did I lose something during copy/paste?

**Comment by colinbendell** [comment]
I have updates to the queries that show dramatically different results.

**Comment by rviscomi** [comment]
Ok cool, could file a PR?

**Comment by rviscomi** [comment]
Hey @colinbendell could you file a PR for any outstanding queries? Then we can close this out. (Same for CDN)
