### ISSUE TITLE
Query metrics: Chapter 6. Fonts

### ISSUE THREAD

**Issue by rviscomi** [HTTPArchive/almanac.httparchive.org#87]
Part | Chapter | Authors | Reviewers | Tracking Issue
-- | -- | -- | -- | --
I. Page Content | 6. Fonts | @davelab6 @zachleat | @hyperpress @AymenLoukil | #7

# READ ME!
All of the metrics in the table below have been marked as `Able To Query` during the [metrics triage](https://github.com/HTTPArchive/almanac.httparchive.org/issues/33). The analyst assigned to each metric is expected to write the corresponding query and submit a PR to [have it reviewed and added to the repo](https://github.com/HTTPArchive/almanac.httparchive.org/issues/62).

In order to stay on schedule and have the data ready for authors, **please have all metrics reviewed and merged by August 5**.

## Assignments

ID | Metric description | Analyst | Notes
-- | -- | -- | --
06.01 | Local vs hosted | @tjmonsi |  
06.02 | Popular hosts | @tjmonsi |  
06.03 | Font formats | @tjmonsi |  
06.04 | Font-Display usage | @tjmonsi |  
06.09 | how many fonts are loaded but also how many type-faces (families) are used | @tjmonsi |  
06.10 | Related, group by weight/style: how many people use italics? those are often left off | @tjmonsi |  
06.11 | Font formats (how many people are still using Bulletproof font face syntax?; WOFF2 use specifically) | @tjmonsi | https://www.paulirish.com/2009/bulletproof-font-face-implementation-syntax/
06.13 | CSS Font Loading API use? | @tjmonsi |  
06.14 | unicode-range use (and range size, perhaps to glean some info on subsetting) | @tjmonsi |  
06.15 | uses preconnect for web font cdn? popular preconnect domains? | @tjmonsi | use of the custom metric written by ymschaap which extracts all `link` elements in the document head and enumerates all of their attributes. We can query for the preconnects and aggregate based on the href.
06.16 | Use of local() in src | @tjmonsi |  
06.18 | how many pages in the HTTPArchive link to a variable font via `@font-face`? | @tjmonsi |  
06.19 | what percent of total pages use VFs? | @tjmonsi |  
06.21 | of those pages linking to a VF, how many are using the 4 font selectors that select on a variable font family? | @tjmonsi |  
06.23 | how many pages link to a VF, but never use it beyond old CSS3 values? | @tjmonsi | Is a VF without VF values even a VF?
06.24 | how many pages use new CSS4 values, like font-weight: 555 and not font-weight: 500? | @tjmonsi |  
06.25 | how many pages use `@supports` to screen for variations capable browsers? | @tjmonsi |  
06.26 | is font-stretch usage growing? | @tjmonsi |  
06.27 | how often is font-size selecting within opsz axis ranges? | @tjmonsi |  
06.28 | which axes are most commonly used today? "top 10 axes"? | @tjmonsi |  
06.29 | which axes are used 6-20pt, and which are used 20pt+? | @tjmonsi |  
06.30 | which axes are used in concert? | @tjmonsi |  
06.31 | top fonts globally | @rviscomi |  
06.32 | top fonts per provider - Google Fonts, AdobeFonts/TypeKit, Cloud.Typography, FontStand, etc | @rviscomi | similar to "top font hosts"
06.33 | top self-hosted fonts | @rviscomi |  
06.34 | what is the bar chart of the number of custom fonts per page? | @rviscomi |  
06.35 | which page uses the most fonts? | @rviscomi |  
06.36 | is SVG going away? | @rviscomi | this might be tricky since svg is not just for fonts
06.37 | is EOT going away? | @rviscomi |  
06.38 | is raw TTF going away? | @rviscomi |  
06.39 | how many pages do only WOFF and WOFF2? | @rviscomi |  
06.40 | how many pages do only WOFF? | @rviscomi |  
06.41 | how many pages do only WOFF2? | @rviscomi |  
06.42 | how many pages use color fonts? | @rviscomi |  
06.43 | how many pages use fonts with each of the 4 (SBIX, CBDT, CPAL, SVG) color font formats? | @rviscomi |  
06.44 | how many pages use each of the font-display properties? | @rviscomi |  
06.45 | how many pages use each of the font preloading properties? | @rviscomi |  
06.46 | how many pages place a single Google Fonts `<link>` element within `<head>`? | @rviscomi | doable with link-nodes custom metric
06.47 | how many pages place a single Google Fonts `<link>` element as the very first element within `<head>`? | @rviscomi |  

## Checklist of metrics to be merged

- [x] 	06.01	Local vs hosted
- [x] 	06.02	Popular hosts
- [x] 	06.03	Font formats
- [x] 	06.04	Font-Display usage
- [x] 	06.09	how many fonts are loaded but also how many type-faces (families) are used
- [x] 	06.10	Related, group by weight/style: how many people use italics? those are often left off
- [ ] 	06.11	Font formats (how many people are still using Bulletproof font face syntax?; WOFF2 use specifically)
- [x] 	06.13	CSS Font Loading API use?
- [x] 	06.14	unicode-range use (and range size, perhaps to glean some info on subsetting)
- [x] 	06.15	uses preconnect for web font cdn? popular preconnect domains?
- [x] 	06.16	Use of local() in src
- [x] 	06.18	how many pages in the HTTPArchive link to a variable font via `@font-face`?
- [x] 	06.19	what percent of total pages use VFs?
- [x] 	06.21	of those pages linking to a VF, how many are using the 4 font selectors that select on a variable font family?
- [ ] 	06.23	how many pages link to a VF, but never use it beyond old CSS3 values?
- [x] 	06.24	how many pages use new CSS4 values, like font-weight: 555 and not font-weight: 500?
- [x] 	06.25	how many pages use `@supports` to screen for variations capable browsers?
- [x] 	06.26	is font-stretch usage growing?
- [ ] 	06.27	how often is font-size selecting within opsz axis ranges?
- [x] 	06.28	which axes are most commonly used today? "top 10 axes"?
- [x] 	06.29	which axes are used 6-20pt, and which are used 20pt+?
- [x] 	06.30	which axes are used in concert?
- [x] 	06.31	top fonts globally
- [x] 	06.32	top fonts per provider - Google Fonts, AdobeFonts/TypeKit, Cloud.Typography, FontStand, etc
- [ ] 	06.33	top self-hosted fonts
- [x] 	06.34	what is the bar chart of the number of custom fonts per page?
- [x] 	06.35	which page uses the most fonts?
- [x] 	06.36	is SVG going away?
- [x] 	06.37	is EOT going away?
- [x] 	06.38	is raw TTF going away?
- [x] 	06.39	how many pages do only WOFF and WOFF2?
- [x] 	06.40	how many pages do only WOFF?
- [x] 	06.41	how many pages do only WOFF2?
- [x] 	06.42	how many pages use color fonts?
- [x] 	06.43	how many pages use fonts with each of the 4 (SBIX, CBDT, CPAL, SVG) color font formats?
- [x] 	06.44	how many pages use each of the font-display properties?
- [ ] 	06.45	how many pages use each of the font preloading properties?
- [x] 	06.46	how many pages place a single Google Fonts `<link>` element within `<head>`?
- [x] 	06.47	how many pages place a single Google Fonts `<link>` element as the very first element within `<head>`?

**Comment by tjmonsi** [comment]
Working on it

**Comment by tjmonsi** [comment]
@rviscomi we just copy and paste our SQL right? (assuming the gist sql that we did works)

**Comment by rviscomi** [comment]
Generally, yes. Also make sure to update the queries to the latest dataset 2019_07_01.

It'd be good to start a PR with one or two queries so I can review for code style. Then once those are through you can submit the rest. Thanks @tjmonsi!

**Comment by tjmonsi** [comment]
@rviscomi I saw that I would be doing the VF parts, but it says that you have triaged it. Do you have sample SQL iIcan work on for those?

**Comment by rviscomi** [comment]
I don't have sample queries but if you need any help understanding how to query something feel free to post on discuss.httparchive.org and someone (probably me) can help for your specific case. That helps share the knowledge around.

**Comment by tjmonsi** [comment]
@rviscomi where can I look for the preconnect again? (Custom metric values)

**Comment by tjmonsi** [comment]
I have a few more questions @rviscomi :
- 06.10: does it mean number of font-weights used per page (percentile) or approximate quantile per font-weight / font-style regardless of font?
- 06.11: am I looking at the Bulletproof (src, src -> local) or (src: woff2, then src -> local)?
- 06.14: does it mean unicode ranges in approximate quantile? or like a sample of output to understand what I need to output
- 06.20: how do i compute this?: what is the % growth over some time period (3, 6, 12 months) for VF? 
- 06.26: how do i compute this?: is font-stretch usage growing? should i just count for the month or should i check the ones before?

I think that is all for now

**Comment by rviscomi** [comment]
@davelab6 @zachleat PTAL at [this sheet](https://docs.google.com/spreadsheets/d/108g6LXdC3YVsxmX1CCwrmpZ3-DmbB8G_wwgQHX5pn6Q/edit?usp=sharing) which contains the results of all of the queries so far. I've left comments in each sheet with guidance on how to interpret the results. LMK if anything looks wrong.

My only remaining questions:

`06.11 Font formats (how many people are still using Bulletproof font face syntax?; WOFF2 use specifically)`
Looking at Paul Irish's [Bulletproof guide](https://www.paulirish.com/2009/bulletproof-font-face-implementation-syntax/), he's got a few variations. What about his approach should test for (use of local/url/format, multiple srcs)? Is this actually answered by metrics [06.39-41](https://docs.google.com/spreadsheets/d/108g6LXdC3YVsxmX1CCwrmpZ3-DmbB8G_wwgQHX5pn6Q/edit#gid=1309542313)?

`06.23 how many pages link to a VF, but never use it beyond old CSS3 values?`
What should we be looking for to see if a page uses a VF beyond old CSS3 values? Any page that uses `font-variation-settings` in addition to having a VF?

`06.27 how often is font-size selecting within opsz axis ranges?`
Is `opsz` a range? I've only seen it provided with a single number. For a page that provides an `opsz` value, should I check that somewhere in the stylesheet it sets a `font-size` to that value? :-/

`06.33 top self-hosted fonts`
For this one I can detect if a font is self-hosted based on its URL in the request, but not sure how to map that back to the font family name. Am I looking for its `url` property in the `@font-face` declaration to have a relative URL or the host of the current page? Not sure if that approach is easily doable. Is this metric particularly interesting/important? If so I'll give it some more thought/effort.

`06.45 how many pages use each of the font preloading properties?`
What are "each of the font preloading properties"? Is this referring to the [link attributes](https://developer.mozilla.org/en-US/docs/Web/HTML/Preloading_content#Cross-origin_fetches) like type/crossorigin when as=font?

**Comment by rviscomi** [comment]
Closing this issue with the questions above unresolved.
