### ISSUE TITLE
Query metrics: Chapter 7. Performance

### ISSUE THREAD

**Issue by rviscomi** [HTTPArchive/almanac.httparchive.org#88]
Part | Chapter | Authors | Reviewers | Tracking Issue
-- | -- | -- | -- | --
II. User Experience | 7. Performance | @rviscomi @zeman | @JMPerez @obto @sergeychernyshev | #9

# READ ME!
All of the metrics in the table below have been marked as `Able To Query` during the [metrics triage](https://github.com/HTTPArchive/almanac.httparchive.org/issues/33). The analyst assigned to each metric is expected to write the corresponding query and submit a PR to [have it reviewed and added to the repo](https://github.com/HTTPArchive/almanac.httparchive.org/issues/62).

In order to stay on schedule and have the data ready for authors, **please have all metrics reviewed and merged by August 5**.

## Assignments

ID | Metric description | Analyst | Notes
-- | -- | -- | --
07.01 | global distribution of FCP fast/avg/slow | @rviscomi |  
07.02 | global distribution of FID fast/avg/slow | @rviscomi |  
07.03 | % of fast FCP websites | @rviscomi |  
07.04 | % of fast FID websites | @rviscomi |  
07.05 | % of fast FCP+FID websites, per PSI definition | @rviscomi |  
07.06 | % of websites with offline experiences | @rviscomi |  
07.07 | country/region comparison of any/all of the above | @rviscomi |  
07.08 | mobile vs desktop comparison of any/all of the above | @rviscomi |  
07.09 | ECT comparison of any/all of the above | @rviscomi |  
07.10 | first/last painted hero | @raghuramakrishnan71 |  
07.11 | H1 rendering time | @raghuramakrishnan71 |  
07.12 | Largest Image | @raghuramakrishnan71 |  
07.13 | Largest Background Image | @raghuramakrishnan71 |  
07.14 | Visually Complete | @raghuramakrishnan71 | summary_pages, visualComplete
07.15 | First CPU Idle | @raghuramakrishnan71 | lighthouse, reports
07.16 | Time To Interactive | @raghuramakrishnan71 | lighthouse, reports
07.17 | Blocking CSS requests | @raghuramakrishnan71 |  
07.18 | Blocking JS request | @raghuramakrishnan71 |  
07.19 | Time To First Byte (Backend) | @raghuramakrishnan71 | summary_pages, ttfb
07.20 | Scripting CPU time | @raghuramakrishnan71 | pages, payload
07.21 | Layout CPU time | @raghuramakrishnan71 | pages, payload
07.22 | Paint CPU time | @raghuramakrishnan71 | pages, payload
07.23 | Loading CPU time | @raghuramakrishnan71 |  
07.24 | Lighthouse Performance Score | @raghuramakrishnan71 | lighthouse, reports

## Checklist of metrics to be merged

- [x] 	07.01	global distribution of FCP fast/avg/slow
- [x] 	07.02	global distribution of FID fast/avg/slow
- [x] 	07.03	% of fast FCP websites
- [x] 	07.04	% of fast FID websites
- [x] 	07.05	% of fast FCP+FID websites, per PSI definition
- [x] 	07.06	% of websites with offline experiences
- [x] 	07.07	country/region comparison of any/all of the above
- [x] 	07.08	mobile vs desktop comparison of any/all of the above
- [x] 	07.09	ECT comparison of any/all of the above
- [x] 	07.10	first/last painted hero
- [x] 	07.11	H1 rendering time
- [x] 	07.12	Largest Image
- [x] 	07.13	Largest Background Image
- [x] 	07.14	Visually Complete
- [x] 	07.15	First CPU Idle
- [x] 	07.16	Time To Interactive
- [x] 	07.17	Blocking CSS requests
- [x] 	07.18	Blocking JS request
- [x] 	07.19	Time To First Byte (Backend)
- [x] 	07.20	Scripting CPU time
- [x] 	07.21	Layout CPU time
- [x] 	07.22	Paint CPU time
- [x] 	07.23	Loading CPU time
- [x] 	07.24	Lighthouse Performance Score

**Comment by raghuramakrishnan71** [comment]
@rviscomi i have not used git for creating PR (i assume PR is a pull request) earlier. Can you please point me to documentation/steps which can help me get started? I can then start adding queries assigned to me.

**Comment by rviscomi** [comment]
@raghuramakrishnan71 sure, the GitHub Help site has a lot of useful docs:

https://help.github.com/en/articles/fork-a-repo
https://help.github.com/en/articles/about-pull-requests
https://help.github.com/en/articles/creating-a-pull-request

Worst case scenario, you can use the GitHub web UI to start the pull request by uploading files directly. Go to https://github.com/HTTPArchive/almanac.httparchive.org/tree/master/sql/2019/07_Performance and select "Create a new branch for this commit and start a pull request":

![image](https://user-images.githubusercontent.com/1120896/62147537-b5ce2c00-b2c5-11e9-8a46-197586b50f9b.png)

**Comment by rviscomi** [comment]
@zeman I've saved the results of the lab metric to [this sheet](https://docs.google.com/spreadsheets/d/1zWzFSQ_ygb-gGr1H1BsJCfB7Z89zSIf7GX0UayVEte4/edit?usp=sharing). I'll also be adding the results of the field metrics there as well. I have some ideas for the outline of our chapter, I'll share a doc to get the ball rolling.
