### ISSUE TITLE
Use more inclusive language in this project

### ISSUE THREAD

**Issue by bazzadp** [HTTPArchive/almanac.httparchive.org#880]
Following on from recent movements in other projects, I'd like to use more inclusive language in this project.

Namely:
- [x] A few instances of "whitelist" in the Security chapter for CSP. These are perfectly valid (it's in the CSP spec after all), but can easily be reworded to avoid this whole debate. #883
- [x] Rename `master` branch to `main` in Git. #881 
- [ ] Delete `master` branch after release and a period (2 weeks?), to avoid confusion.

Now I know some people have strong views as to the need, effectiveness and point of these sorts of changes, and I'm not wanting to get into the debate on whether or not these terms have anything to do with the negative connotations some might feel they have (whether intentional or not). However, I feel anything we can do to make people feel more inclusive is the right thing to do, and goes with the ethos of this project. Additionally these are very small changes for us and now is the right time to make these changes (before 2020 ramps up in earnest).

For the `master` -> `main` rename the following steps need to be done (this will keep all our commit history btw):

- Rename branch locally: `git branch -m master main`
- Push to GitHub: `git push -u origin main`
- Update [default branch](https://github.com/HTTPArchive/almanac.httparchive.org/settings/branches)
- Add [same protections for `main` branch as for `master`](https://github.com/HTTPArchive/almanac.httparchive.org/settings/branches)
- Update [`master` reference in GitHub action](https://github.com/HTTPArchive/almanac.httparchive.org/blob/master/.github/workflows/generate_chapters.yml)
- Link to license in [README](https://github.com/HTTPArchive/almanac.httparchive.org/blob/master/README.md)
- Numerous changes to master in [src/README](https://github.com/HTTPArchive/almanac.httparchive.org/blob/master/src/README.md)
- LICENCE link in base.html for each language
- SQL link in Methodology.html for each language
- SQL links in base_chapter.html
- Release new version of the website with updated references
- Delete `master` branch after a period to avoid confusion

Local copies and forks can be updated with these commands:

```
git checkout master
git branch -m master main
git fetch
git branch --unset-upstream
git branch -u origin/main
git symbolic-ref refs/remotes/origin/HEAD refs/remotes/origin/main
```
Then change your own default branch in `/settings/branches` for your repo.

Please comment if any _technical concerns_ with this proposal or other suggested names rather than `main`.

**Comment by rviscomi** [comment]
I wholeheartedly endorse these changes.

When changing content, let's be sure to loop in the original authors.

**Comment by bazzadp** [comment]
Found some more references - including links to Licence and SQL on the website.

I still think it's worth doing though.

**Comment by bazzadp** [comment]
The default branch has been moved from `master` to `main`. Please follow above steps to update any local copies or forks. We will delete the `master` branch in a week or so.

Note if you want to just reset your forked `main` branch to be the same as the main repo, then you can do the following in your fork - after completing above steps:

```
git remote add upstream git@github.com:HTTPArchive/almanac.httparchive.org.git
git fetch upstream
git checkout main
git reset --hard upstream/main  
git push origin main --force 
```

**Comment by bazzadp** [comment]
Not heard any issues from this so plan to delete the master branch in next couple of days and the. close this issue. Shout if any reason not to!

**Comment by rviscomi** [comment]
SGTM!

**Comment by bazzadp** [comment]
It is gone!
