### ISSUE TITLE
Query metrics: Chapter 8. Security

### ISSUE THREAD

**Issue by rviscomi** [HTTPArchive/almanac.httparchive.org#89]
Part | Chapter | Authors | Reviewers | Tracking Issue
-- | -- | -- | -- | --
II. User Experience | 8. Security | @arturjanc @ScottHelme | @paulcalvano @bazzadp @ghedo @ndrnmnn | #10

# READ ME!
All of the metrics in the table below have been marked as `Able To Query` during the [metrics triage](https://github.com/HTTPArchive/almanac.httparchive.org/issues/33). The analyst assigned to each metric is expected to write the corresponding query and submit a PR to [have it reviewed and added to the repo](https://github.com/HTTPArchive/almanac.httparchive.org/issues/62).

In order to stay on schedule and have the data ready for authors, **please have all metrics reviewed and merged by August 5**.

## Assignments

ID | Metric description | Analyst | Notes
-- | -- | -- | --
08.01 | SSLv2 / SSLv3 / TLSv1.0 / TLSv1.1 / TLSv1.2 / TLSv1.3 | @dotjs | request -> _securityDetails
08.02 | Unique CA issuers | @dotjs | request -> _securityDetails
08.03 | RSA certificates | @dotjs | request -> _securityDetails
08.04 | ECDSA certificates | @dotjs | request -> _securityDetails
08.06 | Suites supporting Forward Secrecy (ECDHE / DHE) | @dotjs |  
08.07 | Authenticated suites (GCM / CCM) | @dotjs |  
08.08 | Modern suites (AES GCM, ChaCha20-Polyc1305) | @dotjs |  
08.09 | Legacy suites (AES CBC, 3DES, RC4) | @dotjs |  
08.13 | Sites with degraded HTTPS UI (mixed-content) | @dotjs | possibly find http resources on a https origin request
08.14 | Policies with frame-ancestors | @dotjs | request -> headers regex
08.15 | Policies with 'nonce-*' | @dotjs | request -> headers regex
08.16 | Policies with 'hash-*' | @dotjs | request -> headers regex
08.17 | Policies with 'unsafe-inline' | @dotjs | request -> headers regex
08.18 | Policies with 'unsafe-eval' | @dotjs | request -> headers regex
08.19 | Policies with 'strict-dynamic' | @dotjs | request -> headers regex
08.20 | Policies with 'trusted-types' | @dotjs | request -> headers regex
08.21 | Policies with 'upgrade-insecure-requests' | @dotjs | request -> headers regex
08.22 | Variance in max-age | @dotjs | response headers
08.23 | Use of includeSubDomains | @dotjs | response headers
08.24 | Use of preload token | @dotjs | response headers
08.25 | Network Error Logging | @jrharalson | summary_requests_x -> respOtherHeaders, firstHtml=true
08.26 | Report To | @jrharalson | summary_requests_x -> respOtherHeaders, firstHtml=true
08.27 | Referrer Policy | @jrharalson | summary_requests_x -> respOtherHeaders, firstHtml=true
08.28 | Feature Policy | @jrharalson | summary_requests_x -> respOtherHeaders, firstHtml=true
08.29 | X-Content-Type-Options | @jrharalson | summary_requests_x -> respOtherHeaders, firstHtml=true
08.30 | X-Xss-Protection | @jrharalson | summary_requests_x -> respOtherHeaders, firstHtml=true
08.31 | X-Frame-Options | @jrharalson | summary_requests_x -> respOtherHeaders, firstHtml=true
08.32 | Cross-Origin-Resource-Policy | @jrharalson | summary_requests_x -> respOtherHeaders, firstHtml=true
08.33 | Cross-Origin-Opener-Policy | @jrharalson | summary_requests_x -> respOtherHeaders, firstHtml=true
08.34 | Vary (Sec-Fetch-* values) | @jrharalson | summary_requests_x -> respOtherHeaders, firstHtml=true
08.35 | Use of HttpOnly | @jrharalson | request -> headers -> cookie ->regex
08.36 | Use of Secure | @jrharalson | request -> headers -> cookie ->regex
08.37 | Use of SameSite | @jrharalson | request -> headers -> cookie ->regex
08.38 | Use of prefixes | @jrharalson | all cookie info is available in the response headers
08.39 | Use of SRI on subresources | @jrharalson | script or link with [integrity]
08.40 | Vulnerable JS libraries (lighthouse?) | @jrharalson | lighthouse audit
08.42 | Clear-Site-Data header | @jrharalson | respOtherHeaders

## Checklist of metrics to be merged

- [x] 	08.01	SSLv2 / SSLv3 / TLSv1.0 / TLSv1.1 / TLSv1.2 / TLSv1.3
- [x] 	08.02	Unique CA issuers
- [x] 	08.03	RSA certificates
- [x] 	08.04	ECDSA certificates
- [x] 	08.06	Suites supporting Forward Secrecy (ECDHE / DHE)
- [x] 	08.07	Authenticated suites (GCM / CCM)
- [x] 	08.08	Modern suites (AES GCM, ChaCha20-Polyc1305)
- [x] 	08.09	Legacy suites (AES CBC, 3DES, RC4)
- [x] 	08.13	Sites with degraded HTTPS UI (mixed-content)
- [x] 	08.14	Policies with frame-ancestors
- [x] 	08.15	Policies with 'nonce-*'
- [x] 	08.16	Policies with 'hash-*'
- [x] 	08.17	Policies with 'unsafe-inline'
- [x] 	08.18	Policies with 'unsafe-eval'
- [x] 	08.19	Policies with 'strict-dynamic'
- [x] 	08.20	Policies with 'trusted-types'
- [x] 	08.21	Policies with 'upgrade-insecure-requests'
- [x] 	08.22	Variance in max-age
- [x] 	08.23	Use of includeSubDomains
- [x] 	08.24	Use of preload token
- [x] 	08.25	Network Error Logging
- [x] 	08.26	Report To
- [x] 	08.27	Referrer Policy
- [x] 	08.28	Feature Policy
- [x] 	08.29	X-Content-Type-Options
- [x] 	08.30	X-Xss-Protection
- [x] 	08.31	X-Frame-Options
- [x] 	08.32	Cross-Origin-Resource-Policy
- [x] 	08.33	Cross-Origin-Opener-Policy
- [x] 	08.34	Vary (Sec-Fetch-* values)
- [x] 	08.35	Use of HttpOnly
- [x] 	08.36	Use of Secure
- [x] 	08.37	Use of SameSite
- [x] 	08.38	Use of prefixes
- [x] 	08.39	Use of SRI on subresources
- [x] 	08.40	Vulnerable JS libraries (lighthouse?)
- [x] 	08.42	Clear-Site-Data header

**Comment by cqueern** [comment]
If there's time now, or in a future edition would be nice to see metrics for the Clear Site Data header as well. Thanks for everyone's hard work.

**Comment by ScottHelme** [comment]
That's probably too hard @cqueern as it's likely only present on a minimal subset of responses. For example we use it on https://report-uri.com but only on our logout endpoint.

**Comment by cqueern** [comment]
> That's probably too hard @cqueern as it's likely only present on a minimal subset of responses. For example we use it on https://report-uri.com but only on our logout endpoint.

Hi @ScottHelme. Yes, I understand the header's intended use case would be that it only appears on certain events like logout. Agreed it would not be feasible to capture when it is sent for those events.

That said there are sites sending CSD for all visits and it would be interesting to learn adoption of that practice, if it is not much extra work.

**Comment by ScottHelme** [comment]
We should be able to look for it globally much like any other header with only a small amount of work. Hey @rviscomi is it too late to add a metric?

**Comment by rviscomi** [comment]
Sure. @jrharalson you're analyzing other security headers. Could you also include % of sites that include the CSD header on the firstHtml response? I'll add that to the todo list in the initial comment.
