### ISSUE TITLE
Reimplement home page Hero Image with year as text

### ISSUE THREAD

**Issue by bazzadp** [HTTPArchive/almanac.httparchive.org#894]
As mentioned in https://github.com/HTTPArchive/almanac.httparchive.org/pull/893#issuecomment-647521501

Currently the hero image on the home page comes in two flavours:
- On Desktop it's [an image with the year embedded in it](https://github.com/HTTPArchive/almanac.httparchive.org/blob/main/src/static/images/home-hero-2019.png).
- On Mobile it's an [image without the year](https://github.com/HTTPArchive/almanac.httparchive.org/blob/main/src/static/images/home-hero.png)

Can we make the desktop the same as mobile to allow ease of editing for 2020?

**Comment by catalinred** [comment]
I'll take a shot :)
