### ISSUE TITLE
Typo in JS featured snippet

### ISSUE THREAD

**Issue by rviscomi** [HTTPArchive/almanac.httparchive.org#895]
Small typo fix, good for a first-time contributor!

![image](https://user-images.githubusercontent.com/1120896/85321946-80a96a00-b493-11ea-847f-bf576e760c78.png)

> Sites with more 3P code **that** 1P

should be

> Sites with more 3P code **than** 1P

**Comment by satyakresna** [comment]
Hi @rviscomi, I would like to fix this issue. I will send the PR later. Anyway, what is the meaning of P in **3P code** and **1P code**?

**Comment by bazzadp** [comment]
**3P code** means "Third-party code" (i.e. things like Google Analytics, Ads marketing trackers...etc. that site developer may not have direct control over).
**1P code** means "First-party code" (i.e. code hosted by this site and so more likely written and under direct control of this site).

I agree the short names are not very obvious (they are *not* common acronyms for third-party and first-party) and were chosen as it was felt there was probably too little space to put in the full wording.

However quickly editing in dev tools shows that's maybe not the case:

![Featured snippet using 3p and 1p](https://user-images.githubusercontent.com/10931297/86089686-9aa10900-baa0-11ea-9426-044a4210faf1.png)

Looks about the same as what's there currently:

![Featured snippet using third-party and first-party](https://user-images.githubusercontent.com/10931297/86089663-8eb54700-baa0-11ea-80ae-3a8e6573ae23.png)

So if you could change this at the same time to make this clearer that would be great!

Note it's "third-party" not "thirdparty" or "third party" when used as an adjective (like here). Similarly with "first-party".

Give us a shout if you run into any issues.

**Comment by satyakresna** [comment]
Thanks @bazzadp. I just send the PR. Please help to review. :)
