### ISSUE TITLE
Accessibility 2020

### ISSUE THREAD

**Issue by obto** [HTTPArchive/almanac.httparchive.org#907]
# Part II Chapter 8: Accessibility

## Content team
| Authors | Reviewers | Analysts | Draft | Queries | Results |
| ------- | --------- | -------- | ----- | ------- | ------- |
| @oluoluoxenfree  @alextait1 |  @aardrian @ericwbailey @obto | @obto | [Doc][~draft-doc] | [*.sql][~sql-dir] | [Sheet][~results-sheet] |

**Content team lead:** @oluoluoxenfree

Welcome chapter contributors! You'll be using this issue throughout the [chapter lifecycle](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Chapter-Lifecycle) to coordinate on the content planning, analysis, and writing stages.

The **content team** is made up of the following contributors:

- [Authors](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Authors'-Guide)
- [Reviewers](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Reviewers'-Guide)
- [Analysts](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Analysts'-Guide)

**New contributors:** If you're interested in joining the content team for this chapter, just leave a comment below and the content team lead will loop you in.

_Note: To ensure that you get notifications when tagged, you must be "[watching](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Chapter-Lifecycle#notifications)" this repository._

### [**0. Form the content team**](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Chapter-Lifecycle#0-create-content-team)
+ [x] **Jul 6th**: Project owners have selected an author to be the content team lead
+ [x] **Jul 13th**: The content team has at least one author, reviewer, and analyst (minimally viable team formed)

### [**1. Plan content**](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Chapter-Lifecycle#1-plan-content)
+ [x] **Jul 20th:** The content team has completed the chapter outline in the [draft doc][~draft-doc]
+ [x] **Jul 27th**: Analysts have triaged the feasibility of all proposed metrics

### [**2. Gather data**](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Chapter-Lifecycle#1-plan-content)
+ [x] **Jul 27th**: Analysts have added all necessary [custom metrics](https://github.com/HTTPArchive/legacy.httparchive.org/blob/master/custom_metrics/README.md) and [drafted a PR](https://github.com/HTTPArchive/almanac.httparchive.org/pulls?q=is%3Apr+is%3Aopen+draft%3Atrue+label%3Aanalysis) to track query progress
- **Aug 1 - 31**: August crawl
+ [x] **Sep 7th**: Analysts have queried all metrics and saved the output to the [results sheet][~results-sheet]

### [**3. Validate results**](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Chapter-Lifecycle#3-validate-results)
+ [x] **Sep 14th**: The content team has reviewed the [results sheet][~results-sheet]

### [**4. Draft content**](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Chapter-Lifecycle#4-draft-content)
+ [x] **Nov 12th**: Authors have completed the first draft in the [doc][~draft-doc]
+ [x] **Nov 26th**: The content team has prototyped all data visualizations

### [**5. Publication**](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Chapter-Lifecycle#5-publication)
+ [x] **Nov 26th**: The content team has reviewed the final draft, converted to markdown, and filed a PR to add it to the [2020 content directory](https://github.com/HTTPArchive/almanac.httparchive.org/tree/main/src/content/en/2020)
- **Dec 9th**: Target launch date

[~draft-doc]: https://docs.google.com/document/d/1Z8CVLfTQv2WRl0PUGnRFSfH5_V6qE2JUJzy2ytJ1kjU/edit?usp=sharing
[~sql-dir]: https://github.com/HTTPArchive/almanac.httparchive.org/tree/main/sql/2020/08_Accessibility
[~results-sheet]: https://docs.google.com/spreadsheets/d/1UjEBhq0TfYxUpdpq5IuxjeHB4yqhJq4NOKEd6Dwwrdk/edit#gid=2077755325

**Comment by obto** [comment]
Would love to hear from and nominate @WilcoFiers.

We make extensive use of axe in our data collection and I'd be excited to read from an author who is not just an expert in A11Y, but one who has an intense understanding of all the data we're collecting.

**Comment by rviscomi** [comment]
@oluoluoxenfree thank you for agreeing to be the lead author for the Accessibility chapter! As the lead, you'll be responsible for driving the content planning and writing phases in collaboration with your content team, which will consist of yourself as lead, any coauthors you choose as needed, peer reviewers, and data analysts.

The immediate next steps for this chapter are:

1. Establish the rest of your content team. Several other people were interested or nominated (see below), so that's a great place to start. The larger the scope of the chapter, the more people you'll want to have on board.
2. Start sketching out ideas in your [draft doc](https://docs.google.com/document/d/1Z8CVLfTQv2WRl0PUGnRFSfH5_V6qE2JUJzy2ytJ1kjU/edit?usp=sharing).
3. Catch up on [last year's chapter](https://almanac.httparchive.org/en/2019/accessibility) and the [project methodology](https://almanac.httparchive.org/en/2019/methodology) to get a sense for what's possible.

There's a ton of info in the top comment, so check that out and feel free to ping myself or @obto with any questions!

To everyone else who has been nominated:

@aardrian
@ericwbailey
@scottaohara
@segunolalive
@bamadesigner
@rianrietveld
@SaraSoueidan
@stevefaulkner
@WilcoFiers
@scroniser

we'd still love to have you contribute as a peer reviewer or coauthor as needed. Let us know if you're still interested!

**Comment by aardrian** [comment]
Happy to take a look if you need on the technical bits, but again, as an annoying white guy I will defer to people who would bring more lived experience outside my own.

**Comment by ericwbailey** [comment]
Similar sentiments to @aardrian. Happy to pitch in on reviewing if needed, but I want to make sure people self-identified as Disabled are represented.

**Comment by rviscomi** [comment]
Thanks @aardrian @ericwbailey. I'll put you both down as reviewers for now and we can adjust as needed.

**Comment by obto** [comment]
Happy to be a reviewer and analyst this year. Was the author and analyst for last year's chapter, so if you have any questions at all I'd be more than happy to help :)

**Comment by obto** [comment]
Hey @oluoluoxenfree, just checking in:

1. How is the the chapter coming along? We're tying to have the outline and metrics settled on by the end of the week so we have time to configure the Web Crawler to track everything you need. 
2. Can you remind your team to properly add and credit themselves in your chapter's Google Doc?
3. Anything you need from me to keep things moving forward?

**Comment by bazzadp** [comment]
Hello @oluoluoxenfree | @aardrian @ericwbailey @obto ! Could I ask for some of your accessibility expertise on #892 ? We're wondering if the focus ring is needed on our site when the focus state changes the colour anyway? This is in particular for the header items and buttons - and in particular for the language and year selector where the focus ring shows even on mouse usage. Have a read of the issue if you don't mind and let us know your thoughts on it in there.

**Comment by obto** [comment]
@oluoluoxenfree How is the outline coming along? We want to have that wrapped up by the end of the week so we have time to set up our Web Crawler :)

**Comment by oluoluoxenfree** [comment]
I'm going to hopefully have a draft for you tonight; sorry I didn't keep
better track of it!

**Comment by rockeynebhwani** [comment]
@oluoluoxenfree  / @rviscomi - I think it will be interesting to look at adoption of solutions like EqualWeb and few others (UserWay, Silktide, browsealoud, Recite me, Essential Accessibility. Enable, uRemediate, Adally.). These solutions provide a lazy solution for sites to become accessible and get compliance level.

Example of EqualWeb on https://www.hobbs.com/

![image](https://user-images.githubusercontent.com/1718757/87863665-319d0a80-c955-11ea-8bef-3bbe7363ea95.png)

I don't see any category in Wappalyzer to detect this but detection for technologies like these should be straightfoward.

**Comment by rockeynebhwani** [comment]
Create an issue for Wappalyzer to detect this. https://github.com/AliasIO/wappalyzer/issues/3228

**Comment by rviscomi** [comment]
Interesting idea! Hope we can get the detections in place for August.

**Comment by rockeynebhwani** [comment]
@rviscomi  - I have completed pattern detection for all major providers in https://github.com/AliasIO/wappalyzer/issues/3228 but I think I have too many Wappalyzer PRs now. Anybody who can help?

**Comment by rviscomi** [comment]
Before we invest in the detections we should wait for @oluoluoxenfree to write the outline and set the scope of the chapter. If this is out of scope we don't need to hurry to get the detections in. Also, many of the detections are based on the presence of a specific URL, which we could easily check by looking at the network log if needed.

**Comment by ericwbailey** [comment]
Chiming in to say that if those overlay services are quantified that there should be a heavily editorial presence accompanying them, in that most of these services actually **negatively** affect a page's accessibility. In fact, a few of the more popular ones are currently getting sued because of this act. 

My perspective is it'd be irresponsible to make readers of the report aware of these services without providing this information. I'd also say it should be presented alongside the findings, and not as a footnote or an aside.

**Comment by rviscomi** [comment]
That's really good to know! Thanks @ericwbailey. If needed, you could also compare the median Lighthouse accessibility category scores per service to see if they tend to degrade accessibility.

**Comment by rockeynebhwani** [comment]
@ericwbailey - Agree. These services are used by companies as *tick in the box* exercise and we should provide necessary context and attached caveats in chapter if we end up covering this. I am seeing adoption of these services by big retail companies (I provided example of Hobbs and Lacoste in GitHub issue) and I would like to cover this in eCommerce chapter as well.

**Comment by aardrian** [comment]
When the time comes to collect resources discussing the problems with these overlays/add-ons, I have [five years of links](https://adrianroselli.com/2015/11/be-wary-of-add-on-accessibility.html#Update01) (I can create a list) and [results of my own testing](https://adrianroselli.com/2020/06/accessibe-will-get-you-sued.html) for one the tools. In short, there is a lot out there.

**Comment by rockeynebhwani** [comment]
@aardrian  .. wow :).. You seem to have lot of experience in this area. Do you mind review list of providers in https://github.com/AliasIO/wappalyzer/issues/3228 and suggest if I am missing any?

**Comment by aardrian** [comment]
@rockeynebhwani The list looks good, so I won't add more noise to that thread. Be aware that WhoIsAccessible.com is itself an enabler. It does not do reviews, it uses pay-for-placement, and its own site would fail even the most basic tests. But it _is_ a good source to see who the automated tool player are.

**Comment by ericwbailey** [comment]
@rviscomi I know at least one service deploys scripts to detect and circumvent Lighthouse, so maybe that's also something worth highlighting.

**Comment by obto** [comment]
@oluoluoxenfree Can you give us an update where you are with the outline for the chapter? The deadline for adding new metrics is the end of this week, and we really need the outline done first.

If we miss the deadline, we might not have time to add all the new metrics by the time the crawler starts on Aug 1st... which means we'll have to scrap the new metrics we'd have liked to analyze

**Comment by oluoluoxenfree** [comment]
Hi, 

Bringing @@alextait1 onboard as a co-author and she's helping me nail things down a bit; will have an outline by the end of today. Been a strange couple of weeks for me, sorry for the lack of communication.

**Comment by alextait1** [comment]
Hello from Toronto, happy to help

**Comment by rviscomi** [comment]
Thank you for checking in @oluoluoxenfree, hope all is well.

@alextait1 it's great to have you! I've just given you edit access to the doc and sent you an invite to join the 2020 Authors team on GitHub - you can accept via email or by visiting https://github.com/HTTPArchive. Also please add yourself to the [Contributors](https://almanac.httparchive.org/en/2020/contributors) page on the website by editing the [2020.json config](https://github.com/HTTPArchive/almanac.httparchive.org/blob/main/src/config/2020.json).

Feel free to reach out to @obto or me if you have any questions.

**Comment by rviscomi** [comment]
@aardrian @ericwbailey could you request edit access to the [doc](https://docs.google.com/document/d/1Z8CVLfTQv2WRl0PUGnRFSfH5_V6qE2JUJzy2ytJ1kjU/edit?usp=sharing) so you could leave comments on the outline?

@aardrian I've also sent you an invite to join the Reviewers team. You can accept at https://github.com/HTTPArchive.

Thanks!

**Comment by rockeynebhwani** [comment]
> Create an issue for Wappalyzer to detect this. [AliasIO/wappalyzer#3228](https://github.com/AliasIO/wappalyzer/issues/3228)

PR for this change has been merged. You should be able to query based on category called 'Accessibility' and all technologies mentioned in this issue post August crawl

**Comment by stevefaulkner** [comment]
@obto, late to the party, but happy to help review if needed

**Comment by obto** [comment]
@oluoluoxenfree @obto for the two milestones overdue on July 27 could you check the boxes if:

- the [outline][~outline] has been reviewed and all feasible metrics have been identified
- any necessary [custom metrics][~custom] have been created and you've created a [draft PR][~draft_pr] to track which feasible metrics have had their [queries][~queries] implemented (we've updated the milestone description to clarify this)

Keeping the milestone checklist up to date helps us to see [at a glance][~glance] how all of the chapters are progressing. Thanks for helping us to stay on schedule!

[~custom]: https://github.com/HTTPArchive/legacy.httparchive.org/blob/master/custom_metrics/README.md
[~draft_pr]: https://github.com/HTTPArchive/almanac.httparchive.org/pulls?q=is%3Apr+is%3Aopen+draft%3Atrue+label%3Aanalysis
[~glance]: https://github.com/HTTPArchive/almanac.httparchive.org/issues/989
[~outline]: https://docs.google.com/document/d/1Z8CVLfTQv2WRl0PUGnRFSfH5_V6qE2JUJzy2ytJ1kjU/edit
[~queries]: https://github.com/HTTPArchive/almanac.httparchive.org/tree/main/sql/2020/08_Accessibility

**Comment by obto** [comment]
I've updated the chapter metadata at the top of this issue to link to the [public spreadsheet][~results-sheet] that will be used for this chapter's query results. The sheet serves 3 purposes:

1. Enable authors/reviewers to analyze the results for each metric without running the queries themselves
2. Generate data visualizations to be embedded in the chapter
3. Serve as a public audit trail of this chapter's data collection/analysis, linked from the chapter footer

[~results-sheet]: https://docs.google.com/spreadsheets/d/1UjEBhq0TfYxUpdpq5IuxjeHB4yqhJq4NOKEd6Dwwrdk/edit#gid=2077755325

**Comment by obto** [comment]
@oluoluoxenfree @alextait1 All the queries have been written and the results saved here: https://docs.google.com/spreadsheets/d/1UjEBhq0TfYxUpdpq5IuxjeHB4yqhJq4NOKEd6Dwwrdk/edit#gid=2077755325

We should be good to start writing. Let me know if you have any questions

**Comment by obto** [comment]
@oluoluoxenfree in case you missed it, we've adjusted the milestones to [push the launch date back](https://github.com/orgs/HTTPArchive/teams/almanac-contributors/discussions/8) from November 9 to December 9. This gives all chapters exactly 7 weeks from now to wrap up the analysis, write a draft, get it reviewed, and submit it for publication. So the next milestone will be to complete the first draft by November 12.

However if you're still on schedule to be done by the original November 9 launch date we want you to know that this change doesn't mean your hard work was wasted, and that you'll get the privilege of being part of our "Early Access" launch.

Please see the link above for more info and reach out to @rviscomi or me if you have any questions or concerns about the timeline. We hope this change gives you a bit more breathing room to finish the chapter comfortably and we're excited to see it go live!

**Comment by alextait1** [comment]
@obto thanks for the update and the very much appreciated extension, I myself have been swamped! @oluoluoxenfree and I will get moving on this :)

**Comment by oluoluoxenfree** [comment]
@obto @rviscomi would it be possible to get an extension till Monday and a quick walkthrough of the data? 

thanks for your patience!

**Comment by rviscomi** [comment]
@oluoluoxenfree sure, moving the first draft due date to Monday won't be an issue. Thanks for checking in and hope all is well.

I'll defer to @obto to help get you up to speed on the results.

**Comment by obto** [comment]
@oluoluoxenfree Sure can. I'm available 1130a to 1230p (CT) tomorrow, and 11a to 1230p (CT) Friday

**Comment by alextait1** [comment]
@obto & @oluoluoxenfree I can do either of those times tomorrow, Friday would be harder but maybe possible

**Comment by obto** [comment]
@alextait1 @oluoluoxenfree Sent a calendar invite for tomorrow :)

**Comment by rviscomi** [comment]
@aardrian I don't have your email address, so can you request edit access in the [doc](https://docs.google.com/document/d/1Z8CVLfTQv2WRl0PUGnRFSfH5_V6qE2JUJzy2ytJ1kjU/edit?usp=sharing) so you can review and leave your feedback? We're hoping to get the draft finalized this week.

**Comment by aardrian** [comment]
@rviscomi Spent the week mostly offline for the holiday. Got your email, have opened doc to review.

**Comment by rviscomi** [comment]
@aardrian great, thanks! Hope you don't mind me snooping around for your email address :)
And hope you had a nice holiday.

**Comment by aardrian** [comment]
@rviscomi Do not mind at all; glad you did, in fact, since it was the Docs notification that I saw (not GH).

Anyway, I left comments. I hope I did what you needed/expected.

**Comment by rviscomi** [comment]
Yes, thanks for the thorough review it looks great! Between all of the reviewers it looks really solid.

**Comment by rviscomi** [comment]
@oluoluoxenfree @alextait1 please have your markdown submitted by EOD today to be included in Wednesday's launch.

**Comment by oluoluoxenfree** [comment]
@rviscomi where do I submit the markdown?

**Comment by rviscomi** [comment]
We have a markdown file stubbed out for you with TODOs at [src/content/en/2020/accessibility.md](https://github.com/HTTPArchive/almanac.httparchive.org/blob/main/src/content/en/2020/accessibility.md).

In addition to the contents of the chapter, please also update the lists of authors, reviewers, and analysts to reflect all of the actual contributors and roughly in order of most contributions first as a courtesy. There are also TODOs for authors' bios (shown at the end of the chapter) and featured quote/stats, which are shown randomly on the home page to attract new readers.

You can also refer to the [2019/accessibility.md](https://raw.githubusercontent.com/HTTPArchive/almanac.httparchive.org/main/src/content/en/2019/accessibility.md) file and [Author's Guide wiki](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Authors'-Guide#metadata-to-add-at-the-top-of-your-chapters) if needed.

**Comment by oluoluoxenfree** [comment]
thanks so much!

**Comment by oluoluoxenfree** [comment]
@rviscomi what timezone are you in? Trying to work out if I have enough time to finish

**Comment by rviscomi** [comment]
@oluoluoxenfree  I'm in New York but any time tonight would be best, I'll working late anyway. Thank you for your help getting this published. 🙏

**Comment by oluoluoxenfree** [comment]
@rviscomi I'm flagging as it's 1am here, very sorry I haven't completely finished, was hoping to but it's a lot of graphs!! I will finish putting graphs in tomorrow, sorry again

**Comment by rviscomi** [comment]
No problem, if we can get this finished tomorrow there will still be time before launch. I really appreciate your hard work on this!
