### ISSUE TITLE
Query metrics: Chapter 10. SEO

### ISSUE THREAD

**Issue by rviscomi** [HTTPArchive/almanac.httparchive.org#91]
Part | Chapter | Authors | Reviewers | Tracking Issue
-- | -- | -- | -- | --
II. User Experience | 10. SEO | @rachellcostello @ymschaap @AVGP | @clarkeclark @andylimn @voltek62 | #12

# READ ME!
All of the metrics in the table below have been marked as `Able To Query` during the [metrics triage](https://github.com/HTTPArchive/almanac.httparchive.org/issues/33). The analyst assigned to each metric is expected to write the corresponding query and submit a PR to [have it reviewed and added to the repo](https://github.com/HTTPArchive/almanac.httparchive.org/issues/62).

In order to stay on schedule and have the data ready for authors, **please have all metrics reviewed and merged by August 5**.

## Assignments

ID | Metric description | Analyst | Notes
-- | -- | -- | --
10.01 | Structured data rich results eligibility (ratings, search, etc,) | @ymschaap | html -> regex
10.02 | Lang attribute usage and mistakes (lang='en') | @ymschaap | lighthouse -> html-lang-valid, resource: See: https://discuss.httparchive.org/t/what-are-the-invalid-uses-of-the-lang-attribute/1022
10.03 | `<link>` rel="amphtml" (AMP) | @ymschaap | html -> regex
10.04 | `<link>` hreflang="en-us" (localisation usage) | @ymschaap | html -> regex + lighthouse -> hreflang
10.05 | Breakdown of type of structured data served (ld+json, microformatting, schema.org + what `@type`)? | @ymschaap | Custom Query Can we have this data: https://search.google.com/structured-data/testing-tool
10.06 | Indexability - looking at meta tags like `<meta>` noindex, `<link>` canonicals. | @ymschaap | lighthouse -> is-crawlable, lighthouse -> canonical
10.07 | `<meta>` description + `<title>` (presence & length) | @ymschaap | html -> regex
10.08 | Status codes and whether pages are accessible - 200, 3xx, 4xx, 5xx. | @ymschaap | request -> response
10.09 | Content - looking at word count, thin pages, header usage, alt attributes images | @ymschaap | lighthouse ->image-alt,  Custom Query
10.10 | Linking - extract `<a href>` count per page (internal + external) | @ymschaap | Custom Query
10.11 | Linking - fragment URLs (together with SPAs to navigate content) | @ymschaap | we have react/vue as application type + a href Custom Query
10.12 | robots.txt (It is mentioned in Lighthouse, can we parse the content or only confirm its existence? E.g. check if has a sitemap reference - seems it does list the potential issues) | @ymschaap | lighthouse -> robots-txt
10.13 | If the desktop site is responsive/mobile-ready, or a specific mobile site (redirect, UA)? (Can we find if these are different sites?) | @ymschaap | compare mobile vs desktop crawl page -> _final_url + lighthouse -> seo-mobile
10.14 | Descriptive link text usage (available in Lighthouse data) | @ymschaap | lighthouse -> link-text
10.15 | speed metrics (FCP, server response time) would be nice for SEO as well given the recent focus on fast loading sites | @ymschaap | See: https://discuss.httparchive.org/t/measuring-cms-host-ttfb-in-crux/1676/1

## Checklist of metrics to be merged

- [x] 	10.01	Structured data rich results eligibility (ratings, search, etc,)
- [x] 	10.02	Lang attribute usage and mistakes (lang='en')
- [x] 	10.03	`<link>` rel="amphtml" (AMP)
- [x] 	10.04	`<link>` hreflang="en-us" (localisation usage)
- [x] 	10.05	Breakdown of type of structured data served (ld+json, microformatting, schema.org + what `@type`)?
- [x] 	10.06	Indexability - looking at meta tags like `<meta>` noindex, `<link>` canonicals.
- [x] 	10.07	`<meta>` description + `<title>` (presence & length)
- [x] 	10.08	Status codes and whether pages are accessible - 200, 3xx, 4xx, 5xx.
- [x] 	10.09	Content - looking at word count, thin pages, header usage, alt attributes images
- [x] 	10.10	Linking - extract `<a href>` count per page (internal + external)
- [x] 	10.11	Linking - fragment URLs (together with SPAs to navigate content)
- [x] 	10.12	robots.txt (It is mentioned in Lighthouse, can we parse the content or only confirm its existence? E.g. check if has a sitemap reference - seems it does list the potential issues)
- [x] 	10.13	If the desktop site is responsive/mobile-ready, or a specific mobile site (redirect, UA)? (Can we find if these are different sites?)
- [x] 	10.14	Descriptive link text usage (available in Lighthouse data)
- [x] 	10.15	speed metrics (FCP, server response time) would be nice for SEO as well given the recent focus on fast loading sites

**Comment by rviscomi** [comment]
> 10.01	Structured data rich results eligibility

I had assumed https://github.com/GoogleChrome/lighthouse/issues/4359 was already added to Lighthouse, but it doesn't seem like it. This may be tricky to get right using only SQL. Since I was the one to add this metric, I think it's ok to change this to "Not Feasible". @ymschaap WDYT?

**Comment by ymschaap** [comment]
10.05

> > 10.01	Structured data rich results eligibility
> 
> I had assumed [GoogleChrome/lighthouse#4359](https://github.com/GoogleChrome/lighthouse/issues/4359) was already added to Lighthouse, but it doesn't seem like it. This may be tricky to get right using only SQL. Since I was the one to add this metric, I think it's ok to change this to "Not Feasible". @ymschaap WDYT?

What I did now was use 10.05 (which grabs any json+ld finds @type and @content) and looked at what `@type`s triggers [rich results](https://developers.google.com/search/docs/guides/search-gallery).

We know the JSON is valid, and we know @context + @type is set, which is pretty close to what GoogleChrome/lighthouse#4359 does. 

So imho we could keep it as long as we make sure the make clear what the limitations of this metric is in the webalmanac. On the other hand, 10.05 might already touch on this, and 10.01 would could be considered a duplicate.
