### ISSUE TITLE
Mobile Web 2020

### ISSUE THREAD

**Issue by obto** [HTTPArchive/almanac.httparchive.org#910]
# Part II Chapter 12: Mobile Web

## Content team
| Authors | Reviewers | Analysts | Draft | Queries | Results |
| ------- | --------- | -------- | ----- | ------- | ------- |
| @spanicker @mdiblasio | @malchata @obto @cheneytsai  | @obto | [Doc][~draft-doc] | [*.sql][~sql-dir] | [Sheet][~results-sheet] |

**Content team lead:** @spanicker

Welcome chapter contributors! You'll be using this issue throughout the [chapter lifecycle](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Chapter-Lifecycle) to coordinate on the content planning, analysis, and writing stages.

The **content team** is made up of the following contributors:

- [Authors](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Authors'-Guide)
- [Reviewers](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Reviewers'-Guide)
- [Analysts](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Analysts'-Guide)

**New contributors:** If you're interested in joining the content team for this chapter, just leave a comment below and the content team lead will loop you in.

_Note: To ensure that you get notifications when tagged, you must be "[watching](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Chapter-Lifecycle#notifications)" this repository._

### [**0. Form the content team**](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Chapter-Lifecycle#0-create-content-team)
+ [x] **Jul 6th**: Project owners have selected an author to be the content team lead
+ [x] **Jul 13th**: The content team has at least one author, reviewer, and analyst (minimally viable team formed)

### [**1. Plan content**](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Chapter-Lifecycle#1-plan-content)
+ [x] **Jul 20th:** The content team has completed the chapter outline in the [draft doc][~draft-doc]
+ [x] **Jul 27th**: Analysts have triaged the feasibility of all proposed metrics

### [**2. Gather data**](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Chapter-Lifecycle#1-plan-content)
+ [x] **Jul 27th**: Analysts have added all necessary [custom metrics](https://github.com/HTTPArchive/legacy.httparchive.org/blob/master/custom_metrics/README.md) and [drafted a PR](https://github.com/HTTPArchive/almanac.httparchive.org/pulls?q=is%3Apr+is%3Aopen+draft%3Atrue+label%3Aanalysis) to track query progress
- **Aug 1 - 31**: August crawl
+ [x] **Sep 7th**: Analysts have queried all metrics and saved the output to the [results sheet][~results-sheet]

### [**3. Validate results**](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Chapter-Lifecycle#3-validate-results)
+ [x] **Sep 14th**: The content team has reviewed the [results sheet][~results-sheet]

### [**4. Draft content**](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Chapter-Lifecycle#4-draft-content)
+ [x] **Nov 12th**: Authors have completed the first draft in the [doc][~draft-doc]
+ [x] **Nov 26th**: The content team has prototyped all data visualizations

### [**5. Publication**](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Chapter-Lifecycle#5-publication)
+ [x] **Nov 26th**: The content team has reviewed the final draft, converted to markdown, and filed a PR to add it to the [2020 content directory](https://github.com/HTTPArchive/almanac.httparchive.org/tree/main/src/content/en/2020)
- **Dec 9th**: Target launch date

[~draft-doc]: https://docs.google.com/document/d/1q1eAaGr6XFVVWNshWnNZSnppGMZ8yfLJy6z4-rgvz3A/edit?usp=sharing
[~sql-dir]: https://github.com/HTTPArchive/almanac.httparchive.org/tree/main/sql/2020/12_Mobile_Web
[~results-sheet]: https://docs.google.com/spreadsheets/d/1DGLY7UEWOlDL5_2dtS_j2eqMjiV-Rw5Fe2y6K6-ULvM/edit#gid=2077755325

**Comment by obto** [comment]
Would love to nominate @sergeychernyshev as lead author for this years Mobile web chapter

**Comment by obto** [comment]
Also want to nominate @malchata and [Christian Holst](https://www.linkedin.com/in/chholst/)

**Comment by malchata** [comment]
Cheers, @obto!

I have a book proposal currently being evaluated, but I would love to pitch in at least a little on this if the team would have me.

**Comment by obto** [comment]
That'd be great, I'll put you down as a reviewer :)

Do you have anyone you'd recommend yourself?

**Comment by malchata** [comment]
Happy to be a reviewer, and would even entertain doing some writing if it fits my specialties. 😄 

As for others, I could recommend:
[Aaron Turner](https://twitter.com/torch2424)
[Shubhie Panciker](https://twitter.com/shubhie) (web platform at Google)
[Stephanie Stimac](https://twitter.com/seaotta) (Microsoft)

Those are just off the top of my head for now.

**Comment by spanicker** [comment]
Ok I looked over the docs and would like to accept the author nomination. Thanks!

**Comment by rviscomi** [comment]
@spanicker thank you for agreeing to be the lead author for the Mobile Web chapter! As the lead, you'll be responsible for driving the content planning and writing phases in collaboration with your content team, which will consist of yourself as lead, any coauthors you choose as needed, peer reviewers, and data analysts.

The immediate next steps for this chapter are:

1. Establish the rest of your content team. The larger the scope of the chapter, the more people you'll want to have on board.
2. Start sketching out ideas in your [draft doc](https://docs.google.com/document/d/1q1eAaGr6XFVVWNshWnNZSnppGMZ8yfLJy6z4-rgvz3A/edit?usp=sharing).
3. Catch up on [last year's chapter](https://almanac.httparchive.org/en/2019/mobile-web) and the [project methodology](https://almanac.httparchive.org/en/2019/methodology) to get a sense for what's possible.

There's a ton of info in the top comment, so check that out and feel free to ping myself or @obto with any questions!

Aaron, Stephanie, @sergeychernyshev we'd still love to have you contribute as a peer reviewer or coauthor as needed. Let us know if you're still interested!

**Comment by sergeychernyshev** [comment]
Folks, as I mentioned to David, I can not lead the section, but let me know if this one or performance section needs a reviewer, I’ll be happy to contribute.

**Comment by obto** [comment]
Would also love to be a reviewer :)

**Comment by rviscomi** [comment]
Thanks @sergeychernyshev! [Performance](https://github.com/HTTPArchive/almanac.httparchive.org/issues/905) already has 9 reviewers (!!) so I think it's well-staffed already. This chapter could definitely use your help. I've updated this issue to add both you and @obto as reviewers.

**Comment by sergeychernyshev** [comment]
Sure, I’ll be happy to help here, glad to work with you, @spanicker, @malchata and back on the team with @obto!

**Comment by obto** [comment]
Also happy to be an analyst for the chapter again this year. I was the author for last year's chapter and added a lot of custom metrics.

So if you have any questions at all just let me know :)

**Comment by obto** [comment]
Hey @spanicker, just checking in:

1. How is the the chapter coming along? We're tying to have the outline and metrics settled on by the end of the week so we have time to configure the Web Crawler to track everything you need. 
2. Can you remind your team to properly add and credit themselves in your chapter's Google Doc?
3. Anything you need from me to keep things moving forward?

**Comment by spanicker** [comment]
@obto 
I added a rough outline in the doc, and marked items needing data / metrics with `<data>`
https://docs.google.com/document/d/1q1eAaGr6XFVVWNshWnNZSnppGMZ8yfLJy6z4-rgvz3A/edit#heading=h.vqdmpb884vdu
Haven't validated which things are easy to grab from HTTP archive yet.
Early feedback is very welcome.

Would love to request the following folks to consider being co-authors or reviewers:
[Cheney Tsai](https://twitter.com/cheneytsai)
[Michael Diblasio](https://twitter.com/mike_diblasio)
@housseindjirdeh

**Comment by jaisanth** [comment]
I'm interested in being a reviewer, not sure if this is already filled up :-)

**Comment by obto** [comment]
@spanicker awesome! I'll take a look and leave some comments tomorrow :)

**Comment by rviscomi** [comment]
@spanicker I've sent you an invite to join the 2020 Authors team, which we'll use to communicate to authors about upcoming milestones. Could you visit https://github.com/HTTPArchive to accept the invitation? I want to make sure you're included in our messages :)

**Comment by mdiblasio** [comment]
Happy to be a reviewer and am interested to co-author the Conversions and commerce on mobile section!

**Comment by cheneytsai** [comment]
Thanks @spanicker! I'd be happy to review any portions of this.

If needed, I could also co-author as content requires (but will defer to other nominees on this thread).

**Comment by rviscomi** [comment]
@housseindjirdeh do you also have bandwidth to review this chapter?

**Comment by obto** [comment]
@spanicker left several comments for you in the [Doc](https://docs.google.com/document/d/1q1eAaGr6XFVVWNshWnNZSnppGMZ8yfLJy6z4-rgvz3A/edit?usp=sharing) on Monday so I can proceed with getting the Crawler setup to track the data we need

**Comment by obto** [comment]
@spanicker @obto for the two milestones overdue on July 27 could you check the boxes if:

- the [outline][~outline] has been reviewed and all feasible metrics have been identified
- any necessary [custom metrics][~custom] have been created and you've created a [draft PR][~draft_pr] to track which feasible metrics have had their [queries][~queries] implemented (we've updated the milestone description to clarify this)

Keeping the milestone checklist up to date helps us to see [at a glance][~glance] how all of the chapters are progressing. Thanks for helping us to stay on schedule!

[~custom]: https://github.com/HTTPArchive/legacy.httparchive.org/blob/master/custom_metrics/README.md
[~draft_pr]: https://github.com/HTTPArchive/almanac.httparchive.org/pulls?q=is%3Apr+is%3Aopen+draft%3Atrue+label%3Aanalysis
[~glance]: https://github.com/HTTPArchive/almanac.httparchive.org/issues/989
[~outline]: https://docs.google.com/document/d/1q1eAaGr6XFVVWNshWnNZSnppGMZ8yfLJy6z4-rgvz3A/edit
[~queries]: https://github.com/HTTPArchive/almanac.httparchive.org/tree/main/sql/2020/12_Mobile_Web

**Comment by obto** [comment]
We should be good to go. Will work on the draft PR this weekend

**Comment by sergeychernyshev** [comment]
Folks, I know I probably stood you up, but I realized I don't have enough time and brain capacity to give enough attention as a reviewer and will have to bail on you. Sorry about that.

**Comment by obto** [comment]
@sergeychernyshev No worries and thanks for letting us know.

**Comment by obto** [comment]
I've updated the chapter metadata at the top of this issue to link to the [public spreadsheet][~results-sheet] that will be used for this chapter's query results. The sheet serves 3 purposes:

1. Enable authors/reviewers to analyze the results for each metric without running the queries themselves
2. Generate data visualizations to be embedded in the chapter
3. Serve as a public audit trail of this chapter's data collection/analysis, linked from the chapter footer

[~results-sheet]: https://docs.google.com/spreadsheets/d/1DGLY7UEWOlDL5_2dtS_j2eqMjiV-Rw5Fe2y6K6-ULvM/edit#gid=2077755325

**Comment by obto** [comment]
@spanicker in case you missed it, we've adjusted the milestones to [push the launch date back](https://github.com/orgs/HTTPArchive/teams/almanac-contributors/discussions/8) from November 9 to December 9. This gives all chapters exactly 7 weeks from now to wrap up the analysis, write a draft, get it reviewed, and submit it for publication. So the next milestone will be to complete the first draft by November 12.

However if you're still on schedule to be done by the original November 9 launch date we want you to know that this change doesn't mean your hard work was wasted, and that you'll get the privilege of being part of our "Early Access" launch.

Please see the link above for more info and reach out to @rviscomi or me if you have any questions or concerns about the timeline. We hope this change gives you a bit more breathing room to finish the chapter comfortably and we're excited to see it go live!

**Comment by rviscomi** [comment]
@spanicker @mdiblasio please have your markdown submitted by EOD today to be included in Wednesday's launch.
