### ISSUE TITLE
Design 2020

### ISSUE THREAD

**Issue by obto** [HTTPArchive/almanac.httparchive.org#911]
# Part [Num] Chapter [Num]: Design

## Content team
| Authors | Reviewers | Analysts | Draft | Queries | Results |
| ------- | --------- | -------- | ----- | ------- | ------- |
| TBD | TBD | TBD | [Doc][~draft-doc] | [*.sql][~sql-dir] | [Sheet][~results-sheet] |

**Content team lead:** TBD

Welcome chapter contributors! You'll be using this issue throughout the [chapter lifecycle](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Chapter-Lifecycle) to coordinate on the content planning, analysis, and writing stages.

The **content team** is made up of the following contributors:

- [Authors](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Authors'-Guide)
- [Reviewers](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Reviewers'-Guide)
- [Analysts](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Analysts'-Guide)

**New contributors:** If you're interested in joining the content team for this chapter, just leave a comment below and the content team lead will loop you in.

_Note: To ensure that you get notifications when tagged, you must be "[watching](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Chapter-Lifecycle#notifications)" this repository._

### [**0. Form the content team**](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Chapter-Lifecycle#0-create-content-team)
+ [ ] **Jul 6th**: Project owners have selected an author to be the content team lead
+ [ ] **Jul 13th**: The content team has at least one author, reviewer, and analyst (minimally viable team formed)

### [**1. Plan content**](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Chapter-Lifecycle#1-plan-content)
+ [ ] **Jul 20th:** The content team has completed the chapter outline in the [draft doc][~draft-doc]
+ [ ] **Jul 27th**: Analysts have triaged the feasibility of all proposed metrics

### [**2. Gather data**](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Chapter-Lifecycle#1-plan-content)
+ [ ] **Jul 27th**: Analysts have prepared all feasible metrics for testing and added queries to the [sql directory][~sql-dir]
- **Aug 1 - 31**: August crawl
+ [ ] **Sep 7th**: Analysts have queried all metrics and saved the output to the [results sheet][~results-sheet]

### [**3. Validate results**](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Chapter-Lifecycle#3-validate-results)
+ [ ] **Sep 14th**: The content team has reviewed the [results sheet][~results-sheet]

### [**4. Draft content**](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Chapter-Lifecycle#4-draft-content)
+ [ ] **Oct 12th**: Authors have completed the first draft in the [doc][~draft-doc]
+ [ ] **Oct 26th**: The content team has prototyped all data visualizations

### [**5. Publication**](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Chapter-Lifecycle#5-publication)
+ [ ] **Oct 26th**: The content team has reviewed the final draft, converted to markdown, and filed a PR to add it to the [2020 content directory](https://github.com/HTTPArchive/almanac.httparchive.org/tree/main/src/content/en/2020)
- **Nov 9th**: Target launch date

[~draft-doc]: #
[~sql-dir]: https://github.com/HTTPArchive/almanac.httparchive.org/tree/main/sql/2020/
[~results-sheet]: #

**Comment by ldevernay** [comment]
I can write something about sustainable web design.

**Comment by borisschapira** [comment]
If there's a new Design chapter, I'd love to hear from @stephanie-walter, she’s an incredible achiever and would be a great asset to the Web Almanac.

**Comment by tpgreenwood** [comment]
I'm very excited to see sustainable web design included in this issue!

**Comment by rviscomi** [comment]
@vitalyfriedman are you still interested in authoring this chapter?
@stephanie-walter are you also interested in authoring?

**Comment by rviscomi** [comment]
@ldevernay I'm happy to put you down as a coauthor for the sustainable angle. We're still looking for someone to take the lead author role who can write about the state of design in general.

📟 paging @vitalyfriedman and @stephanie-walter one more time to gauge their interest

**Comment by bazzadp** [comment]
@adactio any interest in helping out with the Web Almanac this year in either this chapter or any other (PWA, Page Weight or whatever takes your fancy)?

**Comment by rviscomi** [comment]
Unfortunately there are no interested contributors for this topic, so I'll close this issue and we can fold the content into the relevant chapters.
