### ISSUE TITLE
Capabilities 2020

### ISSUE THREAD

**Issue by obto** [HTTPArchive/almanac.httparchive.org#912]
# Part II Chapter 13: Capabilities

## Content team
| Authors | Reviewers | Analysts | Draft | Queries | Results |
| ------- | --------- | -------- | ----- | ------- | ------- |
| @christianliebel | @tomayac | @tomayac | [Doc][~draft-doc] | [*.sql][~sql-dir] | [Sheet][~results-sheet] |

**Content team lead:** @christianliebel

Welcome chapter contributors! You'll be using this issue throughout the [chapter lifecycle](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Chapter-Lifecycle) to coordinate on the content planning, analysis, and writing stages.

The **content team** is made up of the following contributors:

- [Authors](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Authors'-Guide)
- [Reviewers](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Reviewers'-Guide)
- [Analysts](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Analysts'-Guide)

**New contributors:** If you're interested in joining the content team for this chapter, just leave a comment below and the content team lead will loop you in.

_Note: To ensure that you get notifications when tagged, you must be "[watching](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Chapter-Lifecycle#notifications)" this repository._

### [**0. Form the content team**](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Chapter-Lifecycle#0-create-content-team)
+ [x] **Jul 6th**: Project owners have selected an author to be the content team lead
+ [x] **Jul 13th**: The content team has at least one author, reviewer, and analyst (minimally viable team formed)

### [**1. Plan content**](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Chapter-Lifecycle#1-plan-content)
+ [x] **Jul 20th:** The content team has completed the chapter outline in the [draft doc][~draft-doc]
+ [x] **Jul 27th**: Analysts have triaged the feasibility of all proposed metrics

### [**2. Gather data**](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Chapter-Lifecycle#1-plan-content)
+ [x] **Jul 27th**: Analysts have added all necessary [custom metrics](https://github.com/HTTPArchive/legacy.httparchive.org/blob/master/custom_metrics/README.md) and [drafted a PR](https://github.com/HTTPArchive/almanac.httparchive.org/pulls?q=is%3Apr+is%3Aopen+draft%3Atrue+label%3Aanalysis) to track query progress
- **Aug 1 - 31**: August crawl
+ [x] **Sep 7th**: Analysts have queried all metrics and saved the output to the [results sheet][~results-sheet]

### [**3. Validate results**](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Chapter-Lifecycle#3-validate-results)
+ [x] **Sep 14th**: The content team has reviewed the [results sheet][~results-sheet]

### [**4. Draft content**](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Chapter-Lifecycle#4-draft-content)
+ [x] **Nov 12th**: Authors have completed the first draft in the [doc][~draft-doc]
+ [x] **Nov 26th**: The content team has prototyped all data visualizations

### [**5. Publication**](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Chapter-Lifecycle#5-publication)
+ [x] **Nov 26th**: The content team has reviewed the final draft, converted to markdown, and filed a PR to add it to the [2020 content directory](https://github.com/HTTPArchive/almanac.httparchive.org/tree/main/src/content/en/2020)
- **Dec 9th**: Target launch date

[~draft-doc]: https://docs.google.com/document/d/1rPyoVaWmKUHvB7HGhtQpapAT4W9lF1wzF_hJHRoXou8/edit?usp=sharing
[~sql-dir]: https://github.com/HTTPArchive/almanac.httparchive.org/tree/main/sql/2020/13_Capabilities
[~results-sheet]: https://docs.google.com/spreadsheets/d/1N6j1qKv7vc51p1W9z_RrbJX9Se3Pmb-Uersfz4gWqqs/edit#gid=2077755325

**Comment by rviscomi** [comment]
@tomayac @ThomasTheDane is there anyone you'd like to nominate to author a chapter on web capabilities?

**Comment by rviscomi** [comment]
Unfortunately there are no interested contributors for this topic, so I'll close this issue and we can fold the content into the relevant chapters.

**Comment by tomayac** [comment]
> @tomayac @ThomasTheDane is there anyone you'd like to nominate to author a chapter on web capabilities?

@rviscomi Unfortunately I was OoO when this call to action was sent. Did we miss the opportunity window? If we found someone this week (of July 20), would that still work?

**Comment by logicalphase** [comment]
If need an author for this I can step up. Just let me know.

**Comment by tomayac** [comment]
@logicalphase Thanks a *ton* for the kind offer. Maybe @christianliebel would be interested, too? Both: this is of course still pending Rick's OK to go ahead, since the initial deadline was not met.

**Comment by tomayac** [comment]
Related: https://github.com/HTTPArchive/bigquery/pull/84/ and https://github.com/HTTPArchive/httparchive.org/pull/206 as part of the to-be-analyzed data.

**Comment by logicalphase** [comment]
> @logicalphase Thanks a *ton* for the kind offer. Maybe @christianliebel would be interested, too? Both: this is of course still pending Rick's OK to go ahead, since the initial deadline was not met.

Sure @tomayac, open to working with @christianliebel if it's a go. I'll keep an eye out for updates.

**Comment by obto** [comment]
@tomayac I'll discuss with @rviscomi and get back to you. If the chapter is brought back, however, there wont be time to add any new [custom metrics](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Analysts'-Guide#almanac-custom-metrics-and-udfs). Since there's a hard deadline for those to be added is the end of this week.

**Comment by christianliebel** [comment]
If it makes sense to have this chapter in the almanac based on the metrics available, I’d be happy to help. @tomayac @logicalphase

**Comment by tomayac** [comment]
Awesome, so at least the author question would be resolved. Thanks, *both*, for volunteering 👏! Now we just need to see if the organization question can be resolved, too.

**Comment by obto** [comment]
@christianliebel are you interested in being the lead author of this chapter? 

For details on what being an author entails, we've written a short guide which should answer most questions you have: https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Authors'-Guide. Happy to answer any other questions you may have.

**Comment by rviscomi** [comment]
+1 thanks everyone for stepping up! If we can get all three author/reviewer/analyst roles filled then we'd be able to get this chapter back in the lineup.

@logicalphase as you're already coauthoring the PWA chapter, would you be open to taking the reviewer role?
If @christianliebel agrees to taking the lead author role, that would only leave the analyst role. @tomayac would you be open to that and/or reviewing this chapter?

As @obto mentioned, chapter planning would need to be accelerated since it's getting such a late start, so we would be looking for an outline ASAP and any needed custom metrics implemented within the next week before the August crawl starts.

**Comment by logicalphase** [comment]
Sure @rviscomi, I'd be happy to review it. No problem.

**Comment by christianliebel** [comment]
@obto @rviscomi Author role is fine for me. 👍 I don’t have any questions right now, but I’m pretty sure they'll show up on the way.

**Comment by rviscomi** [comment]
@christianliebel great to have you on board! I've just set up your [chapter doc](https://docs.google.com/document/d/1rPyoVaWmKUHvB7HGhtQpapAT4W9lF1wzF_hJHRoXou8/edit?usp=sharing) so you can start planning the outline. I don't have your email, so please request edit access to get started.

@logicalphase please also request access to add your review.

**Comment by obto** [comment]
I've updated the chapter metadata at the top of this issue to link to the [public spreadsheet][~results-sheet] that will be used for this chapter's query results. The sheet serves 3 purposes:

1. Enable authors/reviewers to analyze the results for each metric without running the queries themselves
2. Generate data visualizations to be embedded in the chapter
3. Serve as a public audit trail of this chapter's data collection/analysis, linked from the chapter footer

[~results-sheet]: https://docs.google.com/spreadsheets/d/1N6j1qKv7vc51p1W9z_RrbJX9Se3Pmb-Uersfz4gWqqs/edit#gid=2077755325

**Comment by christianliebel** [comment]
@tomayac @logicalphase Hi there, I kindly invite you to review the [results sheet and data visualizations](https://docs.google.com/spreadsheets/d/1N6j1qKv7vc51p1W9z_RrbJX9Se3Pmb-Uersfz4gWqqs/edit#gid=2077755325). Please note that HTTP Archive doesn't have data for all APIs. Where the data is insufficient, I fall back to the percentage of page loads provided by the [Chrome Platform Status metrics](https://chromestatus.com/metrics/feature/timeline/popularity). Thank you!

**Comment by tomayac** [comment]
Thanks, @christianliebel, this looks good to me. I just changed the title of Wake Lock to Screen Wake Lock.

**Comment by obto** [comment]
@christianliebel in case you missed it, we've adjusted the milestones to [push the launch date back](https://github.com/orgs/HTTPArchive/teams/almanac-contributors/discussions/8) from November 9 to December 9. This gives all chapters exactly 7 weeks from now to wrap up the analysis, write a draft, get it reviewed, and submit it for publication. So the next milestone will be to complete the first draft by November 12.

However if you're still on schedule to be done by the original November 9 launch date we want you to know that this change doesn't mean your hard work was wasted, and that you'll get the privilege of being part of our "Early Access" launch.

Please see the link above for more info and reach out to @rviscomi or me if you have any questions or concerns about the timeline. We hope this change gives you a bit more breathing room to finish the chapter comfortably and we're excited to see it go live!

**Comment by christianliebel** [comment]
@tomayac @logicalphase The chapter itself is now also reviewable: https://github.com/christianliebel/web-almanac-2020-capabilities

@obto Thanks for the heads up. I'd indeed try to finish the article by November 9 and would be more than happy to be part of the Early Access launch.

**Comment by rviscomi** [comment]
Congratulations everyone, this chapter has been published for early access! https://almanac.httparchive.org/en/2020/capabilities

**Comment by rviscomi** [comment]
@christianliebel @tomayac thank you again for all of your hard work getting this chapter ready for launch. I have one last favor to ask: when you have a few minutes, I would love to hear your feedback about your experience contributing to the 2020 Web Almanac. We're always looking for ways to improve the process for future contributors, and your feedback will help steer us in the right direction. You can [take the survey here](https://forms.gle/LfKiXq9wRFN8gESu7). Thanks!

**Comment by christianliebel** [comment]
Done! Thanks again for your help and assistance. @rviscomi

**Comment by tomayac** [comment]
Likewise responded, thanks, @rviscomi!
