### ISSUE TITLE
Privacy 2020

### ISSUE THREAD

**Issue by obto** [HTTPArchive/almanac.httparchive.org#913]
# Part II Chapter 10: Privacy

## Content team
| Authors | Reviewers | Analysts | Draft | Queries | Results |
| ------- | --------- | -------- | ----- | ------- | ------- |
| @ydimova | @ldevernay | @ydimova @max-ostapenko | [Doc][~draft-doc] | [*.sql][~sql-dir] | [Sheet][~results-sheet] |

**Content team lead:** @ydimova

Welcome chapter contributors! You'll be using this issue throughout the [chapter lifecycle](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Chapter-Lifecycle) to coordinate on the content planning, analysis, and writing stages.

The **content team** is made up of the following contributors:

- [Authors](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Authors'-Guide)
- [Reviewers](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Reviewers'-Guide)
- [Analysts](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Analysts'-Guide)

**New contributors:** If you're interested in joining the content team for this chapter, just leave a comment below and the content team lead will loop you in.

_Note: To ensure that you get notifications when tagged, you must be "[watching](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Chapter-Lifecycle#notifications)" this repository._

### [**0. Form the content team**](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Chapter-Lifecycle#0-create-content-team)
+ [x] **Jul 6th**: Project owners have selected an author to be the content team lead
+ [x] **Jul 13th**: The content team has at least one author, reviewer, and analyst (minimally viable team formed)

### [**1. Plan content**](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Chapter-Lifecycle#1-plan-content)
+ [x] **Jul 20th:** The content team has completed the chapter outline in the [draft doc][~draft-doc]
+ [x] **Jul 27th**: Analysts have triaged the feasibility of all proposed metrics

### [**2. Gather data**](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Chapter-Lifecycle#1-plan-content)
+ [x] **Jul 27th**: Analysts have added all necessary [custom metrics](https://github.com/HTTPArchive/legacy.httparchive.org/blob/master/custom_metrics/README.md) and [drafted a PR](https://github.com/HTTPArchive/almanac.httparchive.org/pulls?q=is%3Apr+is%3Aopen+draft%3Atrue+label%3Aanalysis) to track query progress
- **Aug 1 - 31**: August crawl
+ [x] **Sep 7th**: Analysts have queried all metrics and saved the output to the [results sheet][~results-sheet]

### [**3. Validate results**](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Chapter-Lifecycle#3-validate-results)
+ [x] **Sep 14th**: The content team has reviewed the [results sheet][~results-sheet]

### [**4. Draft content**](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Chapter-Lifecycle#4-draft-content)
+ [x] **Nov 12th**: Authors have completed the first draft in the [doc][~draft-doc]
+ [x] **Nov 26th**: The content team has prototyped all data visualizations

### [**5. Publication**](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Chapter-Lifecycle#5-publication)
+ [x] **Nov 26th**: The content team has reviewed the final draft, converted to markdown, and filed a PR to add it to the [2020 content directory](https://github.com/HTTPArchive/almanac.httparchive.org/tree/main/src/content/en/2020)
- **Dec 9th**: Target launch date

[~draft-doc]: https://docs.google.com/document/d/1hIllsWd_IqfYuGT_qUFA2ruoQaIvcbuYpNHJLB4AqkU/edit?usp=sharing
[~sql-dir]: https://github.com/HTTPArchive/almanac.httparchive.org/tree/main/sql/2020/10_Privacy
[~results-sheet]: https://docs.google.com/spreadsheets/d/16bE70rv4qbmKIqbZS1zUiTRpk5eOlgxBXEabL1qiduI/edit#gid=2077755325

**Comment by bazzadp** [comment]
Great (and very relevant!) topic. Should it be merged with [Cookies](#903) though as often quite related? Or do we think there's enough for them both to be their own chapter?

**Comment by obto** [comment]
@bazzadp Good q. I think this is something that will be made clear as we brainstorm what metrics should belong in this chapter. If there ends up being a lot of overlap and not enough unique to this chapter alone... then we can talk about merging it with another chapter like Cookies

**Comment by ldevernay** [comment]
I think I could contribute as a reviewer on this topic.

**Comment by zcorpan** [comment]
I nominate @johnwilander (see https://github.com/HTTPArchive/almanac.httparchive.org/issues/876 )

**Comment by ydimova** [comment]
I would like to volunteer as an analyst/author.

**Comment by rviscomi** [comment]
Thanks @ydimova! I'll put you down as an analyst. Would you also mind sharing some of your qualifications/experience with web privacy? I'm not able to find much info from a cursory search, as your full name is not associated with your GitHub profile. Just want to check before assigning the chapter to you :)

@johnwilander are you interested in coauthoring this chapter?

**Comment by ydimova** [comment]
@rviscomi Of course! I'm a computer scientist and PhD student in web privacy and security (no publications yet). I have been using the httparchive dataset for some of my research so I think I could contribute as an analyst and coauthor.

**Comment by rviscomi** [comment]
Thanks @ydimova, you sound like a great fit for this chapter! I've added you as an author. Can I also put you down as the content team lead? You'd be the point person for keeping the chapter on schedule. You're also free to add people as coauthors/reviewers as needed.

A few resources to get you started:
- the [draft doc](https://docs.google.com/document/d/1hIllsWd_IqfYuGT_qUFA2ruoQaIvcbuYpNHJLB4AqkU/edit?usp=sharing) is where the content team will plan and draft the chapter
- [last year's Security chapter](https://almanac.httparchive.org/en/2019/security) for reference, which contained some privacy-related topics
- and the [project methodology](https://almanac.httparchive.org/en/2019/methodology) to give you an idea of the possibilities/limitations of the dataset

I've also added @ldevernay as a reviewer.

@johnwilander we'd still love to have you contribute as a coauthor/reviewer. Let us know!

**Comment by ydimova** [comment]
@rviscomi  Sure, thanks!

**Comment by obto** [comment]
Hey @ydimova, just wanted to check in and see if there's anything you need from me to keep things moving forward.

We're tying to have the outline and metrics settled on by the end of the week so we have time to configure the Web Crawler to track everything you need :)

Also, can you remind your team to properly add and credit themselves in your chapter's Google Doc?

**Comment by bazzadp** [comment]
Unfortunately we've [had to close the Cookie chapter](https://github.com/HTTPArchive/almanac.httparchive.org/issues/903#issuecomment-658527075), but think it's heavily related to Privacy anyway so that's another interesting angle to cover in this chapter if you want!

**Comment by max-ostapenko** [comment]
Migrating to this one from Cookie chapter as an analyst ;)

**Comment by obto** [comment]
@ydimova How is the outline coming along? We want to have that wrapped up by the end of the week so we have time to set up our Web Crawler :)

**Comment by obto** [comment]
@ydimova Also don't forget to join the [`#web-almanac`](https://join.slack.com/t/httparchive/shared_invite/zt-45sgwmnb-eDEatOhqssqNAKxxOSLAaA) slack if you haven't already so @paulcalvano can invite you to the Analysts channel and help set you up.

**Comment by rockeynebhwani** [comment]
@ydimova - As cookies chapter got closed, this may be of interest to this group - https://github.com/AliasIO/wappalyzer/issues/3219

It will be good to report on % of sites using cookie consent management solutions (obviously within EU, we will see higher %) and out of sites using cookie consent management solutions, how many are using explicit Vs implicit consent? Because of the way, HTTPArchive works, any sites with explicit consent will have less number of third parties reported and that can also impact Third Party chapter of Web Almanac. I am not sure if you are thinking in that direction OR any analysis has been done before.

@rviscomi  / @simonhearne  / @patrickhulce

**Comment by rviscomi** [comment]
The tests are all run from the US so these may be undercounted, but it's an interesting angle to consider. If that issue is able to be resolved and included in a Wappalyzer release before the HTTP Archive crawl begins on August 1, then we'd be able to make use of it. Otherwise I think it will only be a minor inconvenience since IIUC it's just a categorization change of technologies that we're already detecting. @rockeynebhwani are you able to work on a PR? It seems AliasIO is supportive of the change.

**Comment by ydimova** [comment]
@rockeynebhwani I think it would indeed be interesting to measure the percentage of websites using popular and less popular cookie consent managament platforms and IAB Europe's TCF (if feasible). 

@max-ostapenko @ldevernay Could you join the outline document :) 
https://docs.google.com/document/d/1hIllsWd_IqfYuGT_qUFA2ruoQaIvcbuYpNHJLB4AqkU 
Feel free to change/add anything

**Comment by rviscomi** [comment]
@ydimova I've sent you an invite to join the 2020 Authors team, which we'll use to communicate to authors about upcoming milestones. Could you visit https://github.com/HTTPArchive to accept the invitation? I want to make sure you're included in our messages :)

**Comment by rockeynebhwani** [comment]
@ydimova @bazzadp @rviscomi - Created a PR for Wappalyzer - https://github.com/AliasIO/wappalyzer/pull/3227. This team can add more technology vendors to the list on top of this.

**Comment by obto** [comment]
@ydimova @max-ostapenko Noticed there are a few metrics you might need custom metrics written for (e.g., finding policy links on a webpage). Can you make a list of what custom metrics you need by EOD tomorrow?

**Comment by rockeynebhwani** [comment]
> @rockeynebhwani I think it would indeed be interesting to measure the percentage of websites using popular and less popular cookie consent managament platforms and IAB Europe's TCF (if feasible).
> 
> @max-ostapenko @ldevernay Could you join the outline document :)
> https://docs.google.com/document/d/1hIllsWd_IqfYuGT_qUFA2ruoQaIvcbuYpNHJLB4AqkU
> Feel free to change/add anything

@ydimova - I  have done the PR and now Wappalyzer has a new category called 'Cookie Compliance' and for now I managed to add 17 vendors to this category. But while working on this, I realized that there are way too many vendors in this space and I don't have time to add all. I am not familier with IAB Europe's TCF solution but if you can tell me a pattern using which we can detect and a sample site, I think we still have time to add to my PR.

**Comment by ydimova** [comment]
@rockeynebhwani  Great, thank you! Maybe we could just stick to the biggest vendors?
The presence of the TCF framework can easily be evaluated by detecting the presence of a __cmp() function in the window element. 
For instance 'typeof window.__cmp()!== "undefined"' would work.

**Comment by rockeynebhwani** [comment]
Thanks @ydimova . Can you please give me an example site to test TCF framework?

**Comment by max-ostapenko** [comment]
@rockeynebhwani here are official framework docs from IAB: https://iabeurope.eu/tcf-2-0/
The test website will help indeed.
I was looking into vendor domain lists (e.g. https://vendorlist.consensu.org/vendorinfo.json), but no valuable data as of now.

**Comment by ydimova** [comment]
@rockeynebhwani  @max-ostapenko I found it on https://www.letudiant.fr/ by calling "window.__cmp" (without the brackets). https://www.senscritique.com/ is another one

**Comment by obto** [comment]
@ydimova @max-ostapenko for the two milestones overdue on July 27 could you check the boxes if:

- the [outline][~outline] has been reviewed and all feasible metrics have been identified
- any necessary [custom metrics][~custom] have been created and you've created a [draft PR][~draft_pr] to track which feasible metrics have had their [queries][~queries] implemented (we've updated the milestone description to clarify this)

Keeping the milestone checklist up to date helps us to see [at a glance][~glance] how all of the chapters are progressing. Thanks for helping us to stay on schedule!

[~custom]: https://github.com/HTTPArchive/legacy.httparchive.org/blob/master/custom_metrics/README.md
[~draft_pr]: https://github.com/HTTPArchive/almanac.httparchive.org/pulls?q=is%3Apr+is%3Aopen+draft%3Atrue+label%3Aanalysis
[~glance]: https://github.com/HTTPArchive/almanac.httparchive.org/issues/989
[~outline]: https://docs.google.com/document/d/1hIllsWd_IqfYuGT_qUFA2ruoQaIvcbuYpNHJLB4AqkU/edit
[~queries]: https://github.com/HTTPArchive/almanac.httparchive.org/tree/main/sql/2020/10_Privacy

**Comment by obto** [comment]
I've updated the chapter metadata at the top of this issue to link to the [public spreadsheet][~results-sheet] that will be used for this chapter's query results. The sheet serves 3 purposes:

1. Enable authors/reviewers to analyze the results for each metric without running the queries themselves
2. Generate data visualizations to be embedded in the chapter
3. Serve as a public audit trail of this chapter's data collection/analysis, linked from the chapter footer

[~results-sheet]: https://docs.google.com/spreadsheets/d/16bE70rv4qbmKIqbZS1zUiTRpk5eOlgxBXEabL1qiduI/edit#gid=2077755325

**Comment by obto** [comment]
@ydimova in case you missed it, we've adjusted the milestones to [push the launch date back](https://github.com/orgs/HTTPArchive/teams/almanac-contributors/discussions/8) from November 9 to December 9. This gives all chapters exactly 7 weeks from now to wrap up the analysis, write a draft, get it reviewed, and submit it for publication. So the next milestone will be to complete the first draft by November 12.

However if you're still on schedule to be done by the original November 9 launch date we want you to know that this change doesn't mean your hard work was wasted, and that you'll get the privilege of being part of our "Early Access" launch.

Please see the link above for more info and reach out to @rviscomi or me if you have any questions or concerns about the timeline. We hope this change gives you a bit more breathing room to finish the chapter comfortably and we're excited to see it go live!

**Comment by max-ostapenko** [comment]
@ydimova FYI There is a cookie parameters data in [Security chapter](https://docs.google.com/spreadsheets/d/1T7sxPP5BV3uwv-sXhBEZraVk-obd0tDfFrLiD49nZC0/edit#gid=253049761), in case you wanted to share some insights.
