### ISSUE TITLE
Compression 2020

### ISSUE THREAD

**Issue by obto** [HTTPArchive/almanac.httparchive.org#916]
# Part IV Chapter 19: Compression

## Content team
| Authors | Reviewers | Analysts | Draft | Queries | Results |
| ------- | --------- | -------- | ----- | ------- | ------- |
| @mo271  | @jyrkialakuijala @sboukortt @veluca93 @paulcalvano  | @AbbyTsai | [Doc][~draft-doc] | [*.sql][~sql-dir] | [Sheet][~results-sheet] |

**Content team lead:** @mo271

Welcome chapter contributors! You'll be using this issue throughout the [chapter lifecycle](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Chapter-Lifecycle) to coordinate on the content planning, analysis, and writing stages.

The **content team** is made up of the following contributors:

- [Authors](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Authors'-Guide)
- [Reviewers](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Reviewers'-Guide)
- [Analysts](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Analysts'-Guide)

**New contributors:** If you're interested in joining the content team for this chapter, just leave a comment below and the content team lead will loop you in.

_Note: To ensure that you get notifications when tagged, you must be "[watching](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Chapter-Lifecycle#notifications)" this repository._

### [**0. Form the content team**](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Chapter-Lifecycle#0-create-content-team)
+ [x] **Jul 6th**: Project owners have selected an author to be the content team lead
+ [x] **Jul 13th**: The content team has at least one author, reviewer, and analyst (minimally viable team formed)

### [**1. Plan content**](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Chapter-Lifecycle#1-plan-content)
+ [x] **Jul 20th:** The content team has completed the chapter outline in the [draft doc][~draft-doc]
+ [x] **Jul 27th**: Analysts have triaged the feasibility of all proposed metrics

### [**2. Gather data**](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Chapter-Lifecycle#1-plan-content)
+ [x] **Jul 27th**: Analysts have added all necessary [custom metrics](https://github.com/HTTPArchive/legacy.httparchive.org/blob/master/custom_metrics/README.md) and [drafted a PR](https://github.com/HTTPArchive/almanac.httparchive.org/pulls?q=is%3Apr+is%3Aopen+draft%3Atrue+label%3Aanalysis) to track query progress
- **Aug 1 - 31**: August crawl
+ [x] **Sep 7th**: Analysts have queried all metrics and saved the output to the [results sheet][~results-sheet]

### [**3. Validate results**](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Chapter-Lifecycle#3-validate-results)
+ [x] **Sep 14th**: The content team has reviewed the [results sheet][~results-sheet]

### [**4. Draft content**](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Chapter-Lifecycle#4-draft-content)
+ [x] **Nov 12th**: Authors have completed the first draft in the [doc][~draft-doc]
+ [x] **Nov 26th**: The content team has prototyped all data visualizations

### [**5. Publication**](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Chapter-Lifecycle#5-publication)
+ [x] **Nov 26th**: The content team has reviewed the final draft, converted to markdown, and filed a PR to add it to the [2020 content directory](https://github.com/HTTPArchive/almanac.httparchive.org/tree/main/src/content/en/2020)
- **Dec 9th**: Target launch date

[~draft-doc]: https://docs.google.com/document/d/1o0dJCLv3mRJ5NudHrv4xj918dOY6ioes5fFnon9W6xI/edit?usp=sharing
[~sql-dir]: https://github.com/HTTPArchive/almanac.httparchive.org/tree/main/sql/2020/19_Compression
[~results-sheet]: https://docs.google.com/spreadsheets/d/1NKbP4AqMkgCNCsVD3yLhO2d0aqIsgZ7AGLEtUDHl9yY/edit#gid=2077755325

**Comment by smatei** [comment]
Hello, I would like to contribute as an analyst. Here is my profile:

https://www.linkedin.com/in/stefan-matei-4738a255/

I contributed to a similar project:

https://www.advancedwebranking.com/html/

My contribution to that project was: scrape and parse approximately 8M web pages and store pages metadata to a database that can be queried for data.

**Comment by obto** [comment]
@smatei happy to have you. I'll add you as an analyst :)

**Comment by rviscomi** [comment]
@jyrkialakuijala is interested in authoring 🎉

**Comment by obto** [comment]
@jyrkialakuijala thank you for agreeing to be the lead author for the Compression chapter! As the lead, you'll be responsible for driving the content planning and writing phases in collaboration with your content team, which will consist of yourself as lead, any coauthors you choose as needed, peer reviewers, and data analysts.

The immediate next steps for this chapter are:

1. Establish the rest of your [content team](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Chapter-Lifecycle#0-create-content-team). The larger the scope of the chapter, the more people you'll want to have on board.
2. Start sketching out ideas in your [draft doc](https://docs.google.com/document/d/1o0dJCLv3mRJ5NudHrv4xj918dOY6ioes5fFnon9W6xI/edit?usp=sharing).
3. Catch up on [last year's chapter](https://almanac.httparchive.org/en/2019/compression) and the [project methodology](https://almanac.httparchive.org/en/2019/methodology) to get a sense for what's possible.

There's a ton of info in the top comment, so check that out and feel free to ping myself or @rviscomi with any questions!

**Comment by rviscomi** [comment]
@yoavweiss @paulcalvano would either of you be interested in reviewing?

**Comment by paulcalvano** [comment]
I'd be happy to be a reviewer for this chapter.  

@jyrkialakuijala looking forward to working with you on this.

**Comment by obto** [comment]
Hey @jyrkialakuijala, just checking in:

1. How is the the chapter coming along? We're tying to have the outline and metrics settled on by the end of the week so we have time to configure the Web Crawler to track everything you need. 
2. Can you remind your team to properly add and credit themselves in your chapter's Google Doc?
3. Anything you need from me to keep things moving forward?

**Comment by obto** [comment]
@jyrkialakuijala How is the outline for the chapter coming along? We want to get it finished by the end of the week so we have time to setup the Web Crawler :)

**Comment by sboukortt** [comment]
Hi, I am one of Jyrki’s reports and I would be happy to contribute, whether as a coauthor or as a reviewer.

**Comment by mo271** [comment]
Hi, I am also one of Jyrki's report and would also like to contribute.

**Comment by veluca93** [comment]
I also work with Jyrki and would like to contribute.

**Comment by rviscomi** [comment]
Thanks everyone! Per our email, I'll set @mo271 as the content team lead. You'll be the point of contact for the chapter and help keep it on schedule.

I see you're all already invited to the [doc](https://docs.google.com/document/d/1o0dJCLv3mRJ5NudHrv4xj918dOY6ioes5fFnon9W6xI/edit?usp=sharing). The outline is due today, but you've all just joined the project so please try to get it written ASAP. The outline sets the scope of the chapter and topics to be covered. From that, your analyst @smatei can help triage what metrics are able to be queried in the HTTP Archive or need to be added as custom metrics. This has to happen in the next week so we're ready to collect the data on August 1. @paulcalvano authored this chapter last year, is a reviewer, and also the lead analyst for the project, so he'll be able to help you out as needed.

**Comment by rviscomi** [comment]
@mo271	@jyrkialakuijala @sboukortt @veluca93 @paulcalvano just checking on. I see that the outline hasn't been started yet. Some teams work on it in another doc, so I just want to make sure that this chapter is able to stay on schedule.

**Comment by rviscomi** [comment]
@smatei can you request edit access to the [doc](https://docs.google.com/document/d/1o0dJCLv3mRJ5NudHrv4xj918dOY6ioes5fFnon9W6xI/edit?usp=sharing)?

**Comment by obto** [comment]
@mo271 @smatei for the two milestones overdue on July 27 could you check the boxes if:

- the [outline][~outline] has been reviewed and all feasible metrics have been identified
- any necessary [custom metrics][~custom] have been created and you've created a [draft PR][~draft_pr] to track which feasible metrics have had their [queries][~queries] implemented (we've updated the milestone description to clarify this)

Keeping the milestone checklist up to date helps us to see [at a glance][~glance] how all of the chapters are progressing. Thanks for helping us to stay on schedule!

[~custom]: https://github.com/HTTPArchive/legacy.httparchive.org/blob/master/custom_metrics/README.md
[~draft_pr]: https://github.com/HTTPArchive/almanac.httparchive.org/pulls?q=is%3Apr+is%3Aopen+draft%3Atrue+label%3Aanalysis
[~glance]: https://github.com/HTTPArchive/almanac.httparchive.org/issues/989
[~outline]: https://docs.google.com/document/d/1o0dJCLv3mRJ5NudHrv4xj918dOY6ioes5fFnon9W6xI/edit
[~queries]: https://github.com/HTTPArchive/almanac.httparchive.org/tree/main/sql/2020/19_Compression

**Comment by obto** [comment]
I've updated the chapter metadata at the top of this issue to link to the [public spreadsheet][~results-sheet] that will be used for this chapter's query results. The sheet serves 3 purposes:

1. Enable authors/reviewers to analyze the results for each metric without running the queries themselves
2. Generate data visualizations to be embedded in the chapter
3. Serve as a public audit trail of this chapter's data collection/analysis, linked from the chapter footer

[~results-sheet]: https://docs.google.com/spreadsheets/d/1NKbP4AqMkgCNCsVD3yLhO2d0aqIsgZ7AGLEtUDHl9yY/edit#gid=2077755325

**Comment by rviscomi** [comment]
@smatei what's the status of this chapter's analysis?

**Comment by rviscomi** [comment]
@HTTPArchive/analysts this chapter is behind on the analysis and could use some additional help to keep it moving. Please comment here if you have the time.

**Comment by obto** [comment]
@mo271 in case you missed it, we've adjusted the milestones to [push the launch date back](https://github.com/orgs/HTTPArchive/teams/almanac-contributors/discussions/8) from November 9 to December 9. This gives all chapters exactly 7 weeks from now to wrap up the analysis, write a draft, get it reviewed, and submit it for publication. So the next milestone will be to complete the first draft by November 12.

However if you're still on schedule to be done by the original November 9 launch date we want you to know that this change doesn't mean your hard work was wasted, and that you'll get the privilege of being part of our "Early Access" launch.

Please see the link above for more info and reach out to @rviscomi or me if you have any questions or concerns about the timeline. We hope this change gives you a bit more breathing room to finish the chapter comfortably and we're excited to see it go live!

**Comment by mo271** [comment]
@smatei are you making progress on the chapter's analysis? Do we need help here from @HTTPArchive/analysts ?

**Comment by AbbyTsai** [comment]
hello,  @mo271 
happy to do the query of analysis and would like to hear that what's the interesting question readers may like to see in static/dynamic compression as found it list in metric, but not in outline. thanks.

**Comment by mo271** [comment]
> hello, @mo271
> happy to do the query of analysis and would like to hear that what's the interesting question readers may like to see in static/dynamic compression as found it list in metric, but not in outline. thanks.

Hi @AbbyTsai!
Thanks for doing the  analysis for the chapter! The idea about dynamic versus static is is to understand if the compression is done on-the-fly or beforehand, for example for brotli compression. I'm not sure if this information is easily obtained.

**Comment by AbbyTsai** [comment]
thanks @mo271 for clarify.
[here](https://docs.google.com/spreadsheets/d/1NKbP4AqMkgCNCsVD3yLhO2d0aqIsgZ7AGLEtUDHl9yY/edit#gid=1365871671) we'd find the result sheet and welcome any comments.

**Comment by mo271** [comment]
> thanks @mo271 for clarify.
> [here](https://docs.google.com/spreadsheets/d/1NKbP4AqMkgCNCsVD3yLhO2d0aqIsgZ7AGLEtUDHl9yY/edit#gid=1365871671) we'd find the result sheet and welcome any comments.

Cool, thanks! Are those results complete? Can we mark the corresponding check boxes for the Milestones above?

**Comment by obto** [comment]
@mo271 If everything looks in order and you dont have any questions or edits to the data, then absolutely!

**Comment by rviscomi** [comment]
I've checked off everything up to "The content team has reviewed the results sheet". @mo271 feel free to tick that box after you've done the review, and work with @AbbyTsai and @paulcalvano to resolve any questions you have about the results.

**Comment by mo271** [comment]
I started from a copy of the 2019 results here:
https://github.com/mo271/almanac.httparchive.org/commit/7950c200e44c32f4a8421796098352a50d35b0b1
