### ISSUE TITLE
CDN 2020

### ISSUE THREAD

**Issue by obto** [HTTPArchive/almanac.httparchive.org#918]
# Part [Num] Chapter [Num]: CDN

## Content team
| Authors | Reviewers | Analysts | Draft | Queries | Results |
| ------- | --------- | -------- | ----- | ------- | ------- |
| TBD | @andydavies @colinbendell @elithrar @triblondon | @AAgar | [Doc][~draft-doc] | [*.sql][~sql-dir] | [Sheet][~results-sheet] |

**Content team lead:** TBD

Welcome chapter contributors! You'll be using this issue throughout the [chapter lifecycle](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Chapter-Lifecycle) to coordinate on the content planning, analysis, and writing stages.

The **content team** is made up of the following contributors:

- [Authors](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Authors'-Guide)
- [Reviewers](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Reviewers'-Guide)
- [Analysts](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Analysts'-Guide)

**New contributors:** If you're interested in joining the content team for this chapter, just leave a comment below and the content team lead will loop you in.

_Note: To ensure that you get notifications when tagged, you must be "[watching](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Chapter-Lifecycle#notifications)" this repository._

### [**0. Form the content team**](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Chapter-Lifecycle#0-create-content-team)
+ [ ] **Jul 6th**: Project owners have selected an author to be the content team lead
+ [ ] **Jul 13th**: The content team has at least one author, reviewer, and analyst (minimally viable team formed)

### [**1. Plan content**](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Chapter-Lifecycle#1-plan-content)
+ [ ] **Jul 20th:** The content team has completed the chapter outline in the [draft doc][~draft-doc]
+ [ ] **Jul 27th**: Analysts have triaged the feasibility of all proposed metrics

### [**2. Gather data**](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Chapter-Lifecycle#1-plan-content)
+ [ ] **Jul 27th**: Analysts have prepared all feasible metrics for testing and added queries to the [sql directory][~sql-dir]
- **Aug 1 - 31**: August crawl
+ [ ] **Sep 7th**: Analysts have queried all metrics and saved the output to the [results sheet][~results-sheet]

### [**3. Validate results**](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Chapter-Lifecycle#3-validate-results)
+ [ ] **Sep 14th**: The content team has reviewed the [results sheet][~results-sheet]

### [**4. Draft content**](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Chapter-Lifecycle#4-draft-content)
+ [ ] **Oct 12th**: Authors have completed the first draft in the [doc][~draft-doc]
+ [ ] **Oct 26th**: The content team has prototyped all data visualizations

### [**5. Publication**](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Chapter-Lifecycle#5-publication)
+ [ ] **Oct 26th**: The content team has reviewed the final draft, converted to markdown, and filed a PR to add it to the [2020 content directory](https://github.com/HTTPArchive/almanac.httparchive.org/tree/main/src/content/en/2020)
- **Nov 9th**: Target launch date

[~draft-doc]: https://docs.google.com/document/d/1bVuMgbWHZkPHmcv8eICIJTMKS4B-a1_dtqJ352fG6zc/edit?usp=sharing
[~sql-dir]: https://github.com/HTTPArchive/almanac.httparchive.org/tree/main/sql/2020/
[~results-sheet]: #

**Comment by elithrar** [comment]
Question: what changes - due to feedback or otherwise - needs to be made to 2019’s CDN content? https://almanac.httparchive.org/en/2019/cdn

(what are the biggest gaps, where can we help readers more, etc?)

**Comment by bazzadp** [comment]
> Question: what changes - due to feedback or otherwise - needs to be made to 2019’s CDN content? https://almanac.httparchive.org/en/2019/cdn
> 
> (what are the biggest gaps, where can we help readers more, etc?)

I think those are excellent questions! We did set up forums for each chapter and they are linked at the bottom of the chapters, [just below the conclusion](https://almanac.httparchive.org/en/2019/cdn#conclusion):

![Forum link for CDN chapter showing 3 comments](https://user-images.githubusercontent.com/10931297/85929027-3d8f3280-b8a9-11ea-836b-bd70d22eea2d.png)

Not everyone may be aware of these, so @obto / @rviscomi , it would be good to remind new authors (and old!) about them when considering what to put in the 2020 chapters. Unfortunately they weren't used as much as we'd have liked, and the 3 comments in there for the CDN chapter are about typos, so in this case don't help answer the question much 😔 

Also reaching out to the previous years authors to hear of any other feedback they are aware of. @andydavies / @colinbendell any feedback you are aware of?

**Comment by andydavies** [comment]
I'll re-read the chapter and the notes I had at the time. 

Did create this retro with some thoughts just after we'd finished write it - https://github.com/HTTPArchive/almanac.httparchive.org/issues/220

**Comment by colinbendell** [comment]
Two additional items:
1. CDN detection should be revised. Specifically, ASN should be evaluated in addition to the CNAME chain. Google is also problematic as it is both CDN and service hosting.
2. Non US testing would be nice

**Comment by obto** [comment]
Would love to nominate @triblondon for this years CDN chapter :)

**Comment by andydavies** [comment]
@obto One thing to watch out for with the CDN chapter is it's one of the few chapters that passes comment on commercial businesses - @colinbendell and I got some comments about that last year

**Comment by AAgar** [comment]
I would love to help out with some analysis.

**Comment by obto** [comment]
@AAgar Added you as an analyst for the chapter :)

**Comment by triblondon** [comment]
I probably have some time I can contribute if this process is noob-tolerant!

**Comment by rviscomi** [comment]
@triblondon we try to make the onboarding process as frictionless as possible! 😄 Let us know if you're ok with the [authoring commitment](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Authors'-Guide).

@andydavies @colinbendell @elithrar would any of you like to be reviewers?

**Comment by andydavies** [comment]
Yeh, I'm happy to review

**Comment by elithrar** [comment]
Happy to review as well.

**Comment by colinbendell** [comment]
Also happy to review.

**Comment by rviscomi** [comment]
@triblondon just want to confirm that you've reviewed the [authoring commitment](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Authors'-Guide) and the process works for you. It'd be great to have you!

**Comment by rviscomi** [comment]
Hi @triblondon just following up that you're able to take on the content team lead / author role for this chapter. Once we have an author lined up we can start with the [content planning](https://docs.google.com/document/d/1bVuMgbWHZkPHmcv8eICIJTMKS4B-a1_dtqJ352fG6zc/edit?usp=sharing).

**Comment by triblondon** [comment]
Sorry for the delay, having chats internally here to figure out if anyone could co-author

**Comment by obto** [comment]
@triblondon No worries. I'll put you down as a reviewer for now then :)

**Comment by triblondon** [comment]
Yes, please, and apologies for being unable to commit more.

**Comment by rviscomi** [comment]
Unfortunately, we don't have an author for this chapter and we're past the deadline to have a content team set up, so I'll close this issue for now.

**Comment by obto** [comment]
@AAgar unfortunately we had to drop this chapter, but there are [many others](https://github.com/HTTPArchive/almanac.httparchive.org/labels/help%20wanted%3A%20analysts) still looking for analsyts. Are there any you'd like to help out with? Would be super appreciated :heart:

**Comment by AAgar** [comment]
Sure, I'll join the security team. However, I think I've met my BigQuery quota.

**Comment by rviscomi** [comment]
@paulcalvano is distributing additional credits for analysts over on `#web-almanac-analysts` on [Slack](https://join.slack.com/t/httparchive/shared_invite/zt-45sgwmnb-eDEatOhqssqNAKxxOSLAaA). Have you joined?

**Comment by AAgar** [comment]
Thanks for the heads up, I'll join it now.
