### ISSUE TITLE
Page Weight 2020

### ISSUE THREAD

**Issue by obto** [HTTPArchive/almanac.httparchive.org#919]
# Part IV Chapter 18: Page Weight

## Content team
| Authors | Reviewers | Analysts | Draft | Queries | Results |
| ------- | --------- | -------- | ----- | ------- | ------- |
| @henrihelvetica | @tammyeverts @borisschapira @khempenius | @paulcalvano | [Doc][~draft-doc] | [*.sql][~sql-dir] | [Sheet][~results-sheet] |

**Content team lead:** @henrihelvetica

Welcome chapter contributors! You'll be using this issue throughout the [chapter lifecycle](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Chapter-Lifecycle) to coordinate on the content planning, analysis, and writing stages.

The **content team** is made up of the following contributors:

- [Authors](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Authors'-Guide)
- [Reviewers](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Reviewers'-Guide)
- [Analysts](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Analysts'-Guide)

**New contributors:** If you're interested in joining the content team for this chapter, just leave a comment below and the content team lead will loop you in.

_Note: To ensure that you get notifications when tagged, you must be "[watching](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Chapter-Lifecycle#notifications)" this repository._

### [**0. Form the content team**](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Chapter-Lifecycle#0-create-content-team)
+ [x] **Jul 6th**: Project owners have selected an author to be the content team lead
+ [x] **Jul 13th**: The content team has at least one author, reviewer, and analyst (minimally viable team formed)

### [**1. Plan content**](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Chapter-Lifecycle#1-plan-content)
+ [x] **Jul 20th:** The content team has completed the chapter outline in the [draft doc][~draft-doc]
+ [x] **Jul 27th**: Analysts have triaged the feasibility of all proposed metrics

### [**2. Gather data**](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Chapter-Lifecycle#1-plan-content)
+ [x] **Jul 27th**: Analysts have added all necessary [custom metrics](https://github.com/HTTPArchive/legacy.httparchive.org/blob/master/custom_metrics/README.md) and [drafted a PR](https://github.com/HTTPArchive/almanac.httparchive.org/pulls?q=is%3Apr+is%3Aopen+draft%3Atrue+label%3Aanalysis) to track query progress
- **Aug 1 - 31**: August crawl
+ [x] **Sep 7th**: Analysts have queried all metrics and saved the output to the [results sheet][~results-sheet]

### [**3. Validate results**](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Chapter-Lifecycle#3-validate-results)
+ [x] **Sep 14th**: The content team has reviewed the [results sheet][~results-sheet]

### [**4. Draft content**](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Chapter-Lifecycle#4-draft-content)
+ [x] **Nov 12th**: Authors have completed the first draft in the [doc][~draft-doc]
+ [x] **Nov 26th**: The content team has prototyped all data visualizations

### [**5. Publication**](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Chapter-Lifecycle#5-publication)
+ [x] **Nov 26th**: The content team has reviewed the final draft, converted to markdown, and filed a PR to add it to the [2020 content directory](https://github.com/HTTPArchive/almanac.httparchive.org/tree/main/src/content/en/2020)
- **Dec 9th**: Target launch date

[~draft-doc]: https://docs.google.com/document/d/1saivit-Re3cFzWl5SBSPbs0H_cEBj6RvSgsA2tmTUuM/edit?usp=sharing
[~sql-dir]: https://github.com/HTTPArchive/almanac.httparchive.org/tree/main/sql/2020/18_Page_Weight
[~results-sheet]: https://docs.google.com/spreadsheets/d/1wG4u0LV5PT9aN-XB1hixSFtI8KIDARTOCX0sp7ZT3h0/edit#gid=2077755325

**Comment by rviscomi** [comment]
@tammyeverts @khempenius any recommendations for someone to author this chapter this year? Also, would you be interested in being reviewers/analysts to help the transition?

**Comment by paulcalvano** [comment]
@henrihelvetica - any interest in working on this?

**Comment by henrihelvetica** [comment]
In. ✅

**Comment by tammyeverts** [comment]
Sweet!!!

I'll be happy to be a reviewer for this chapter... not least so I can have
some virtual quality time with Henri. :)

**Comment by obto** [comment]
@henrihelvetica thank you for agreeing to be the lead author for the Page Weight chapter! As the lead, you'll be responsible for driving the content planning and writing phases in collaboration with your content team, which will consist of yourself as lead, any coauthors you choose as needed, peer reviewers, and data analysts.

The immediate next steps for this chapter are:

1. Establish the rest of your content team. Several other people were interested or nominated (see below), so that's a great place to start. The larger the scope of the chapter, the more people you'll want to have on board.
2. Start sketching out ideas in your [draft doc](https://docs.google.com/document/d/1saivit-Re3cFzWl5SBSPbs0H_cEBj6RvSgsA2tmTUuM/edit?usp=sharing).
3. Catch up on [last year's chapter](https://almanac.httparchive.org/en/2019/page-weight) and the [project methodology](https://almanac.httparchive.org/en/2019/methodology) to get a sense for what's possible.

There's a ton of info in the top comment, so check that out and feel free to ping myself or @rviscomi with any questions!

@tammyeverts put you down as a reviewer!

@khempenius we'd still love to have you contribute as a peer reviewer. Let us know if you're still interested!

**Comment by khempenius** [comment]
Happy to be a reviewer

**Comment by borisschapira** [comment]
I'd be happy to review too.

**Comment by obto** [comment]
@khempenius @borisschapira Added both of you as reviewers :)

**Comment by paulcalvano** [comment]
I'm happy to be an analyst for this chapter

**Comment by obto** [comment]
Hey @henrihelvetica, hope you had a great weekend.

As you know, we're tying to have the outline and metrics settled on by the end of the week so we have time to configure the Web Crawler to track everything you need. Is there anything you need from me to keep things moving forward?

Also can you remind your team to properly add and credit themselves in your chapter's [Google Doc](https://docs.google.com/document/d/1saivit-Re3cFzWl5SBSPbs0H_cEBj6RvSgsA2tmTUuM/edit?usp=sharing)?

**Comment by obto** [comment]
@henrihelvetica How is the outline for the chapter coming along? We want to get it finished by the end of the week so we have time to setup the Web Crawler :)

**Comment by henrihelvetica** [comment]
Hello! Just requested access to the Google page to update the it. Thanks for everyone's patience

**Comment by henrihelvetica** [comment]
Thanks @rviscomi

**Comment by rviscomi** [comment]
Thanks @henrihelvetica for making progress on the outline!

@tammyeverts @borisschapira @khempenius @paulcalvano I've sent you all invites to edit the [doc](https://docs.google.com/document/d/1saivit-Re3cFzWl5SBSPbs0H_cEBj6RvSgsA2tmTUuM/edit?usp=sharing). Please review ASAP so we can unblock the metrics triage by the 27th.

**Comment by obto** [comment]
@paulcalvano Took a look through the chapter and it looks like the Crawler should be setup to get most if not all of the data you need. Can you verify and let me know if you find any additional data you need tracked?

Working on adding new custom metrics to the crawler right now :)

**Comment by obto** [comment]
@henrihelvetica @paulcalvano for the two milestones overdue on July 27 could you check the boxes if:

- the [outline][~outline] has been reviewed and all feasible metrics have been identified
- any necessary [custom metrics][~custom] have been created and you've created a [draft PR][~draft_pr] to track which feasible metrics have had their [queries][~queries] implemented (we've updated the milestone description to clarify this)

Keeping the milestone checklist up to date helps us to see [at a glance][~glance] how all of the chapters are progressing. Thanks for helping us to stay on schedule!

[~custom]: https://github.com/HTTPArchive/legacy.httparchive.org/blob/master/custom_metrics/README.md
[~draft_pr]: https://github.com/HTTPArchive/almanac.httparchive.org/pulls?q=is%3Apr+is%3Aopen+draft%3Atrue+label%3Aanalysis
[~glance]: https://github.com/HTTPArchive/almanac.httparchive.org/issues/989
[~outline]: https://docs.google.com/document/d/1saivit-Re3cFzWl5SBSPbs0H_cEBj6RvSgsA2tmTUuM/edit
[~queries]: https://github.com/HTTPArchive/almanac.httparchive.org/tree/main/sql/2020/18_Page_Weight

**Comment by obto** [comment]
I've updated the chapter metadata at the top of this issue to link to the [public spreadsheet][~results-sheet] that will be used for this chapter's query results. The sheet serves 3 purposes:

1. Enable authors/reviewers to analyze the results for each metric without running the queries themselves
2. Generate data visualizations to be embedded in the chapter
3. Serve as a public audit trail of this chapter's data collection/analysis, linked from the chapter footer

[~results-sheet]: https://docs.google.com/spreadsheets/d/1wG4u0LV5PT9aN-XB1hixSFtI8KIDARTOCX0sp7ZT3h0/edit#gid=2077755325

**Comment by obto** [comment]
@henrihelvetica in case you missed it, we've adjusted the milestones to [push the launch date back](https://github.com/orgs/HTTPArchive/teams/almanac-contributors/discussions/8) from November 9 to December 9. This gives all chapters exactly 7 weeks from now to wrap up the analysis, write a draft, get it reviewed, and submit it for publication. So the next milestone will be to complete the first draft by November 12.

However if you're still on schedule to be done by the original November 9 launch date we want you to know that this change doesn't mean your hard work was wasted, and that you'll get the privilege of being part of our "Early Access" launch.

Please see the link above for more info and reach out to @rviscomi or me if you have any questions or concerns about the timeline. We hope this change gives you a bit more breathing room to finish the chapter comfortably and we're excited to see it go live!

**Comment by rviscomi** [comment]
Updated the milestone checklist to reflect that the queries have all been written and the results saved to the spreadsheet.

@henrihelvetica let us know if you're on track to get the draft done this week, otherwise it may be at risk of missing the December 9 launch date.

**Comment by rviscomi** [comment]
@henrihelvetica please have your markdown submitted by EOD today to be included in Wednesday's launch.
