### ISSUE TITLE
Resource Hints 2020

### ISSUE THREAD

**Issue by obto** [HTTPArchive/almanac.httparchive.org#920]
# Part IV Chapter 21: Resource Hints

## Content team
| Authors | Reviewers | Analysts | Draft | Queries | Results |
| ------- | --------- | -------- | ----- | ------- | ------- |
| @Zizzamia  | @notwillk @giopunt @jessnicolet @pmeenan @mgechev  | @khempenius | [Doc][~draft-doc] | [*.sql][~sql-dir] | [Sheet][~results-sheet] |

**Content team lead:** @Zizzamia 

Welcome chapter contributors! You'll be using this issue throughout the [chapter lifecycle](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Chapter-Lifecycle) to coordinate on the content planning, analysis, and writing stages.

The **content team** is made up of the following contributors:

- [Authors](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Authors'-Guide)
- [Reviewers](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Reviewers'-Guide)
- [Analysts](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Analysts'-Guide)

**New contributors:** If you're interested in joining the content team for this chapter, just leave a comment below and the content team lead will loop you in.

_Note: To ensure that you get notifications when tagged, you must be "[watching](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Chapter-Lifecycle#notifications)" this repository._

### [**0. Form the content team**](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Chapter-Lifecycle#0-create-content-team)
+ [x] **Jul 6th**: Project owners have selected an author to be the content team lead
+ [x] **Jul 13th**: The content team has at least one author, reviewer, and analyst (minimally viable team formed)

### [**1. Plan content**](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Chapter-Lifecycle#1-plan-content)
+ [x] **Jul 20th:** The content team has completed the chapter outline in the [draft doc][~draft-doc]
+ [x] **Jul 27th**: Analysts have triaged the feasibility of all proposed metrics

### [**2. Gather data**](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Chapter-Lifecycle#1-plan-content)
+ [x] **Jul 27th**: Analysts have added all necessary [custom metrics](https://github.com/HTTPArchive/legacy.httparchive.org/blob/master/custom_metrics/README.md) and [drafted a PR](https://github.com/HTTPArchive/almanac.httparchive.org/pulls?q=is%3Apr+is%3Aopen+draft%3Atrue+label%3Aanalysis) to track query progress
- **Aug 1 - 31**: August crawl
+ [x] **Sep 7th**: Analysts have queried all metrics and saved the output to the [results sheet][~results-sheet]

### [**3. Validate results**](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Chapter-Lifecycle#3-validate-results)
+ [x] **Sep 14th**: The content team has reviewed the [results sheet][~results-sheet]

### [**4. Draft content**](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Chapter-Lifecycle#4-draft-content)
+ [x] **Nov 12th**: Authors have completed the first draft in the [doc][~draft-doc]
+ [x] **Nov 26th**: The content team has prototyped all data visualizations

### [**5. Publication**](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Chapter-Lifecycle#5-publication)
+ [x] **Nov 26th**: The content team has reviewed the final draft, converted to markdown, and filed a PR to add it to the [2020 content directory](https://github.com/HTTPArchive/almanac.httparchive.org/tree/main/src/content/en/2020)
- **Dec 9th**: Target launch date

[~draft-doc]: https://docs.google.com/document/d/1qsJWq7eKdif2egt54G3jmZzK4PkyoIX8g4o4UzlJGEw/edit?usp=sharing
[~sql-dir]: https://github.com/HTTPArchive/almanac.httparchive.org/tree/main/sql/2020/21_Resource_Hints
[~results-sheet]: https://docs.google.com/spreadsheets/d/1lXjd8ogB7kYfG09eUdGYXUlrMjs4mq1Z7nNldQnvkVA/edit#gid=2077755325

**Comment by rviscomi** [comment]
@Zizzamia thank you for agreeing to be the lead author for the Resource Hints chapter! As the lead, you'll be responsible for driving the content planning and writing phases in collaboration with your content team, which will consist of yourself as lead, any coauthors you choose as needed, peer reviewers, and data analysts.

The immediate next steps for this chapter are:

1. Establish the rest of your content team. Several other people were interested or nominated (see below), so that's a great place to start. The larger the scope of the chapter, the more people you'll want to have on board.
2. Start sketching out ideas in your [draft doc](https://docs.google.com/document/d/13vyY2kVC7E04br-1DDtsEjcGxwx03PkHH3uz-TbC7Fo/edit?usp=sharing).
3. Catch up on [last year's chapter](https://almanac.httparchive.org/en/2019/resource-hints) and the [project methodology](https://almanac.httparchive.org/en/2019/methodology) to get a sense for what's possible.

There's a ton of info in the top comment, so check that out and feel free to ping myself or @obto with any questions!

@MaedahBatool we'd still love to have you contribute as a peer reviewer or coauthor as needed. Let us know if you're still interested!

**Comment by Zizzamia** [comment]
Awesome, I have a couple of people I am going to ask to be reviewers as well. Of course, @MaedahBatool if you are still interested I would love you to have your help as well as a reviewer. 🌲🚀🌕

**Comment by rviscomi** [comment]
@Zizzamia I've sent you an invite to join the HTTP Archive org on the Authors team. Could you go to https://github.com/HTTPArchive to accept? You need to be a member of the org in order to have issues assigned to you, so this will help with our issue tracking. Thanks!

**Comment by Zizzamia** [comment]
@rviscomi done, and thank you!

**Comment by rviscomi** [comment]
Thanks! You also have edit access to the top comment now, so please keep that up to date as the chapter progresses.

**Comment by Zizzamia** [comment]
Ciao all! 👋

Thanks again to @rviscomi and @obto for selecting me to lead this effort. We have three people helping as reviewers at the moment (@notwillk, @giopunt, and @jessnicolet), but we don't have any analysts yet. Looking forward to having more help on the Data Analysts side. 🧪

A few places to start reading about 2019 and reflecting on what has happened with Resources Hints in 2020:
- [Web Almanac Resource Hints 2019](https://almanac.httparchive.org/en/2019/resource-hints) & [Queries](https://github.com/HTTPArchive/almanac.httparchive.org/tree/main/sql/2019/19_Resource_Hints/)
- [Web Almanac Media 2019](https://almanac.httparchive.org/en/2019/media#client-hints) & [Queries](https://github.com/HTTPArchive/almanac.httparchive.org/tree/main/sql/2019/04_Media)
- [W3C Resource Hints](https://www.w3.org/TR/resource-hints/)
- [W3C Priority Hints](https://wicg.github.io/priority-hints/)
- [HTML Links spec](https://html.spec.whatwg.org/multipage/links.html)
- [Native lazy-loading for the web](https://web.dev/native-lazy-loading/)
- [Open and close issues on Github Resource Hints](https://github.com/w3c/resource-hints/issues)
- [MDN web performance resources](https://developer.mozilla.org/en-US/docs/Learn/Performance/Web_Performance_Basics)
- Machine Learning prefetch/preload with [Guess.js](https://github.com/guess-js/guess)
- Can I use [preconnect](https://caniuse.com/#feat=link-rel-preconnect), [prefetch](https://caniuse.com/#feat=link-rel-prefetch), [preload](https://caniuse.com/#feat=link-rel-preload), [lazy-loading](https://caniuse.com/#feat=loading-lazy-attr), [crossorigin](https://caniuse.com/#feat=mdn-html_elements_link_crossorigin).

Based off of the 2019 Almanac, we can continue the conversation re:
- Adoption of resource hints.
- Median and 90th percentiles of the number of resource hints used per page out of all pages using a resource hint.
- Adoption of the `crossorigin` attribute as a percent of resource hint instances.
- The percent of resource hint instances using the `as` attribute.
- The rate of priority hint adoption.

In 2020 we can also analyze:
- Native lazy loading adoption
- HTTP2/ Push adoption with preload and prefetch
- Machine learning prefetch/preload adoption with Guess.js or similar technologies. 

That was a quick kickoff to spark ideas/suggestions for this chapter. @notwillk, @giopunt, and @jessnicolet feel free to share ideas in the comments or ping me directly on Twitter ([@zizzamia](https://twitter.com/zizzamia)). ✨

And if anyone from the web community has any other recommendations, please, I'm all 👂

**Comment by pmeenan** [comment]
If you're still looking for reviewers, I'd be happy to help.

**Comment by Zizzamia** [comment]
Just added you on the reviewer's list, and invited you on our Twitter DM group.

**Comment by rviscomi** [comment]
@Zizzamia regarding the DM group, consider moving that discussion to a public forum (this issue or the draft doc) for all of the reasons @bazzadp excellently described here: https://github.com/HTTPArchive/almanac.httparchive.org/issues/899#issuecomment-653488485

**Comment by Zizzamia** [comment]
Sounds good, we will keep all the discussion between this issue and the draft doc 😁

**Comment by Zizzamia** [comment]
We are looking for one Data Analyst, @max-ostapenko do you have enough bandwidth to help with this chapter as well? ✨

**Comment by rviscomi** [comment]
Also cc @khempenius (author and data analyst for this chapter last year)

**Comment by khempenius** [comment]
I can be the analyst for this chapter if no one else is interested.

**Comment by Zizzamia** [comment]
Grazie Mille @khempenius!
Officially the Resource Hints content team is complete 🌲🚀🌕
I am going to give a refresh on the doc over the weekend, and if anyone in the team (@notwillk, @giopunt, @jessnicolet, @pmeenan,  @khempenius) has some early ideas feel free to share it here or in the doc.

**Comment by Zizzamia** [comment]
Ciao @notwillk, @giopunt, @jessnicolet, @pmeenan, @khempenius! 😁
I just completed the [draft](https://docs.google.com/document/d/1qsJWq7eKdif2egt54G3jmZzK4PkyoIX8g4o4UzlJGEw/edit?usp=sharing) for the chapter outline, if you have ideas or suggestions feel free to add them to the Doc or share them in this thread.

@khempenius, let me know when is a good time to start writing down the metrics. I noticed we can re-use several queries from 2019, and for the new 2020 queries I am looking forward to hearing your opinions on how feasible they are, and if there are any particular new ones you are looking to add as well. 🧪

Thank you already to @jessnicolet for editing the outline and @pmeenan for answering some of my open questions. ✨

**Comment by rviscomi** [comment]
Thanks for making great progress on this chapter already @Zizzamia, I'm looking forward to seeing the final result!

**Comment by khempenius** [comment]
Thanks for taking the lead on the chapter content @Zizzamia! At first glance, those new metrics all look feasible. I'll circle back to this a little bit later to take a closer look and start putting together the queries.

**Comment by obto** [comment]
Hey @Zizzamia, this chapter is coming along great! Anything you need from me so you and your team can have the outline and metrics settled by the end of the week?

**Comment by mgechev** [comment]
I'd be happy to help reviewing the predictive prefetching section. Btw, Guess.js might not be working very efficiently with Gatsby right now. We've had conversation on distributing the model across bundles with @wardpeet in the past so we can get the same performance as with Angular, but I'm not sure where this effort currently is at.

Since this is a very specific discussion, I'll keep it outside of this thread :)

**Comment by obto** [comment]
@khempenius We've added a new channel in our slack for analysts. Just join the [`#web-almanac`](https://join.slack.com/t/httparchive/shared_invite/zt-45sgwmnb-eDEatOhqssqNAKxxOSLAaA) slack and Paul will invite you to the Analysts channel.

**Comment by Zizzamia** [comment]
@mgechev added you as reviewer and made a note in the doc where we talk about Machine Learning.

**Comment by wardpeet** [comment]
Sorry, I haven't been able to work on Gatsby's GuessJs implementation. It still works, but the more data you have, the bigger your bundle.

So, if you keep your data small like a week or two of data, it works pretty well.

**Comment by obto** [comment]
@khempenius Took a look through the chapter and it looks like the Crawler should be setup to get most if not all of the data you need. I saw @rviscomi ping you already, but let me know if you find any data you need that the Crawler is not tracking.

I'm working on adding new custom metrics to the crawler right now :)

**Comment by Zizzamia** [comment]
@khempenius, thank you for writing down all the queries for this chapter. There are a couple of comments that I left in the document related on a few extra metrics I think we need to have. Let me know if you think they are doable.

@obto one thing I am looking to track, is how many websites used **Guess.js** for "[Faster web navigation with predictive prefetching](https://web.dev/predictive-prefetching/)". Can the Crawler determine this kind of information? cc @rviscomi @mgechev

**Comment by mgechev** [comment]
I'd be curious to know this as well. Based on my understanding you can use HTTPArchive to look for globals. Guess.js exposes `__GUESS__` that can help you find out the numbers.

**Comment by rviscomi** [comment]
Yes, a custom metric could return whether that global exists. ⚠️ Today is the deadline to add any new custom metrics. ⚠️

**Comment by Zizzamia** [comment]
@khempenius sorry for last minute request, anyway we can have a query for https://github.com/HTTPArchive/almanac.httparchive.org/issues/920#issuecomment-664471088 ? Thank you

**Comment by Zizzamia** [comment]
Never mind, I just notice you already add it https://github.com/HTTPArchive/almanac.httparchive.org/pull/1090/commits/90c2064f007c82fe8d68e10f892b310f3a8c44e6, amazing 🙏

**Comment by obto** [comment]
@Zizzamia @khempenius for the two milestones overdue on July 27 could you check the boxes if:

- the [outline][~outline] has been reviewed and all feasible metrics have been identified
- any necessary [custom metrics][~custom] have been created and you've created a [draft PR][~draft_pr] to track which feasible metrics have had their [queries][~queries] implemented (we've updated the milestone description to clarify this)

Keeping the milestone checklist up to date helps us to see [at a glance][~glance] how all of the chapters are progressing. Thanks for helping us to stay on schedule!

[~custom]: https://github.com/HTTPArchive/legacy.httparchive.org/blob/master/custom_metrics/README.md
[~draft_pr]: https://github.com/HTTPArchive/almanac.httparchive.org/pulls?q=is%3Apr+is%3Aopen+draft%3Atrue+label%3Aanalysis
[~glance]: https://github.com/HTTPArchive/almanac.httparchive.org/issues/989
[~outline]: https://docs.google.com/document/d/1qsJWq7eKdif2egt54G3jmZzK4PkyoIX8g4o4UzlJGEw/edit
[~queries]: https://github.com/HTTPArchive/almanac.httparchive.org/tree/main/sql/2020/21_Resource_Hints

**Comment by obto** [comment]
I've updated the chapter metadata at the top of this issue to link to the [public spreadsheet][~results-sheet] that will be used for this chapter's query results. The sheet serves 3 purposes:

1. Enable authors/reviewers to analyze the results for each metric without running the queries themselves
2. Generate data visualizations to be embedded in the chapter
3. Serve as a public audit trail of this chapter's data collection/analysis, linked from the chapter footer

[~results-sheet]: https://docs.google.com/spreadsheets/d/1lXjd8ogB7kYfG09eUdGYXUlrMjs4mq1Z7nNldQnvkVA/edit#gid=2077755325

**Comment by rviscomi** [comment]
@Zizzamia I've iterated on @khempenius's queries and saved the results to your [chapter results sheet](https://docs.google.com/spreadsheets/d/1lXjd8ogB7kYfG09eUdGYXUlrMjs4mq1Z7nNldQnvkVA/edit?usp=sharing). Please take a look at leave a comment if you see anything awry. The SQL is still being reviewed, so the results are liable to change, but I expect it to go through soon and this will give you a good foundation to start drafting the chapter.

Peer reviewers: @notwillk @giopunt @jessnicolet @pmeenan @mgechev please also review the results and comment on anything unexpected/incorrect.

@khempenius please work with @Zizzamia to create the data viz as needed. I've made a few charts so far but not for all metrics.

go go go 🚗 💨

**Comment by rviscomi** [comment]
PR merged, so the [results](https://docs.google.com/spreadsheets/d/1lXjd8ogB7kYfG09eUdGYXUlrMjs4mq1Z7nNldQnvkVA/edit?usp=sharing) are ready for review.

**Comment by Zizzamia** [comment]
Amazing, thank you @rviscomi. Will work on them this weekend.

**Comment by obto** [comment]
@Zizzamia in case you missed it, we've adjusted the milestones to [push the launch date back](https://github.com/orgs/HTTPArchive/teams/almanac-contributors/discussions/8) from November 9 to December 9. This gives all chapters exactly 7 weeks from now to wrap up the analysis, write a draft, get it reviewed, and submit it for publication. So the next milestone will be to complete the first draft by November 12.

However if you're still on schedule to be done by the original November 9 launch date we want you to know that this change doesn't mean your hard work was wasted, and that you'll get the privilege of being part of our "Early Access" launch.

Please see the link above for more info and reach out to @rviscomi or me if you have any questions or concerns about the timeline. We hope this change gives you a bit more breathing room to finish the chapter comfortably and we're excited to see it go live!
