### ISSUE TITLE
Join the 2020 Editors team

### ISSUE THREAD

**Issue by rviscomi** [HTTPArchive/almanac.httparchive.org#922]
Editors are technical writers with a keen eye for content quality who help Almanac authors polish their final drafts. To learn more, check out the [Editors' Guide](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Editors'-Guide).

Are you interested in joining the fine folks in the @HTTPArchive/editors team? Simply comment on this thread and we'll send you an invite.

**Comment by bazzadp** [comment]
I'm in btw. Won't be able to hold myself back from reviewing anyway, so might as well get the credit for it 😀

**Comment by rachellcostello** [comment]
Just got access back to my GitHub account! I'd be happy to come back and help out as an editor again if needed

**Comment by rviscomi** [comment]
@jpmedley were you interested to join the Editors team?

**Comment by exterkamp** [comment]
👋 I can help with editing too if needed

**Comment by rviscomi** [comment]
Thank you @exterkamp! Can you edit https://github.com/HTTPArchive/almanac.httparchive.org/issues/1432#issue-738062237 and add your name to the Resource Hints chapter to get started?
