### ISSUE TITLE
Join the 2020 Developers team

### ISSUE THREAD

**Issue by rviscomi** [HTTPArchive/almanac.httparchive.org#924]
Developers are responsible for the technical infrastructure of the website and solve complex problems about accessibility, performance, internationalization, SEO, and more. To learn more, check out the [Developers' Guide](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Developers'-Guide).

Last year the development team achieved some pretty interesting, cutting edge or innovative items as shown in our [Technical accomplishments](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Technical-accomplishments) page.

Are you interested in joining the fine folks at in the @HTTPArchive/developers team? Simply comment on this thread and we'll send you an invite.

Here is a hotlist of ["good first issues"](https://github.com/HTTPArchive/almanac.httparchive.org/issues?q=is%3Aissue+is%3Aopen+label%3A%22good+first+issue%22+label%3Adevelopment) for developers. Let us know if any sound interesting to you!

**Comment by SaptakS** [comment]
I would love to join the developer's team.

**Comment by techhtml** [comment]
🙌🙌

**Comment by max-ostapenko** [comment]
Yes, please

**Comment by ahmadawais** [comment]
Count me in for smaller contributions here and there. 🙌

**Comment by bazzadp** [comment]
Welcome one and all! I'm Barry and I've been leading the development of the Almanac for the last few months. I managed a software development team in Ireland so dabble in all parts of web development though my JavaScript and CSS knowledge is a bit hobbled together so could do with much improvement! Would love you all to give a little intro to yourselves and what development in particular you're strong in, or would like to do here.

I've updated the [Developer's Guide](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Developers'-Guide) and would encourage you to read that. I also wrote a piece on ["Helping to create the Web Almanac" for the 2019 Web Performance calendar](https://calendar.perfplanet.com/2019/helping-to-create-the-web-almanac/) and that might give you a flavour of what's involved.

For now, I'd encourage you to fork the repo and try to set up and run the site locally following the instructions in the `src/README.md` file. Let me know if you run into any problems. For those who already forked it previously please not that we moved from [`master` branch to `main` recently](https://github.com/HTTPArchive/almanac.httparchive.org/issues/880) so you may need to update your fork.

There's a few [good first issue](https://github.com/HTTPArchive/almanac.httparchive.org/labels/good%20first%20issue) issues there that you can have a look at while we wait for 2020 to kick off in earnest. #895 is a very easy one for newbies for example, that could get you used to how the site is built.

So welcome on board, introduce yourselves, and get stuck in! Reach out with any questions at all - no matter how small or stupid sounding. I'm also on the [`#web-almanac`](https://join.slack.com/t/httparchive/shared_invite/zt-45sgwmnb-eDEatOhqssqNAKxxOSLAaA) channel on the HTTP Archive Slack, or on [Twitter](https://twitter.com/tunetheweb) if you're too shy to chat in public, but would encourage you to use GitHub for anything that would benefit others on this project.

**Comment by borisschapira** [comment]
Hi, you know me from translating some chapters to French, and you can count on me for 2020 on the dev. part too.
I'm getting by with JS and used both hexo, Jekyll, hugo and Eleventy for other static generated websites so I can understand the technical workflow. I can help improve the performance, or the global architecture (have we thought about a headless CMS for contribution?), and I'm *really* bad with everything's that requires graphic design.

**Comment by bazzadp** [comment]
Good to have you back for 2020 @borisschapira ! 

I’ve stuck some high level goals for 2020 here: https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Developers'-Guide#goals-for-2020-edition. That’s on top of the obvious one of getting 2020 launched!

Would love to hear your (or anyone else’s!) feedback on those or additional ones we should consider.

**Comment by elithrar** [comment]
More than happy to help & contribute here—the Almanac is an important resource in making the web more accessible/understandable 👏🏼

(I lead CDN @ Google Cloud and maintain a number of large HTTP libraries, and hence am already pretty invested in this space!)

**Comment by bazzadp** [comment]
Wow great to have such expertise @elithrar ! If you’re a CDN and HTTP expert then am sure you could contribute to those chapters too if you want: #918 and #921

**Comment by elithrar** [comment]
@bazzadp More than happy to. Let me know what needs to be done to “formalize” it so I can dedicate the right amount of time.

(I am sure a couple of others in my broader group would also be willing to contribute / act as reviewers - we have a mix of backgrounds across the team!)

**Comment by bazzadp** [comment]
Basically if willing to take on the author or reviewer role, then pipe up and volunteer yourself in one of those issues! Or volunteer others if you either think they might be interested or would like to hear from them.

Particularly for those two chapters I don't recall a lot of volunteers. Definitely weren't for the HTTP/2 one, which is how I became involved in this project! 😀

However, as you work on one of the major CDNs, do need to be conscious that we'd like to avoid any accusations of bias, so might not be picked as an author if others volunteer. Or if you are, then at least one non-Google co-author would be good IMHO.

Anyway getting off topic for this thread so let's take it up in one or both of the linked issues.

**Comment by catalinred** [comment]
Count me in!

**Comment by dsadhanala** [comment]
Interested, please include me!

**Comment by 25prathamesh** [comment]
Hi count me  in , my  developement skills  are javascript & python .  i also do web performance consulting so i can also review different topics related web performance  or code changes  related to performance

**Comment by bcinarli** [comment]
I can also help if any additional hands are needed. Can help coding related needs for accessibility, CSS or other you name it.

(I'm leading performance, frontend architectural related topics in Adidas)

**Comment by ibnesayeed** [comment]
I can help with Docker, GH Actions, and some other aspects of development. I am already part of the Reviewers team, but I can be added to the Developers team as well.

**Comment by satyakresna** [comment]
Hi, thank you for allowing me to join developer team. I'm Kresna and I [write about web development and random things in my personal blog](https://satyakresna.io) and [build an unofficial role playing game wiki](https://bfwiki.satyakresna.io) for my self and community. Usually, I develop web using HTML, CSS, JS and PHP. But, this is my first time involved in almanac project that using Python stack. I hope I can contribute in this project.

**Comment by bazzadp** [comment]
Alright developers!

We have a few issues that would be good for relative newbies:

- #944 (JavaScript developer) - add the new Core Web Vitals to our Google Analytics call so we can track performance of our own site better. Plus it's the hot new thing, so would be interesting to see these 😀.
- #947 (CSS developer) - fix up some inconsistencies on the website.
- #948 (HTML developer - perhaps with a bit of templating depending what we do here) - Update (or remove?) the copyright year from our footer so we don't look out of date. This one should be very simple but good to practice building the site and submit your first PR.
- #949 (Python developer) - clean up/refactor code

Any tackers for looking at these? As always happy to help guide you through any issues and review code so don't be scared.

Dive in and assign the issues to yourself - first come first served!

**Comment by Vrijraj** [comment]
Count me in the Development team

**Comment by bazzadp** [comment]
Good stuff.

There's a growing list of good-first issues if anyone wants to dive in: https://github.com/HTTPArchive/almanac.httparchive.org/issues?q=is%3Aissue+is%3Aopen+label%3Adevelopment+label%3A%22good+first+issue%22

Tag me in any of the issues if you have any questions.

**Comment by sudheendrachari** [comment]
Would love to contribute, please count me in.

**Comment by bazzadp** [comment]
Hey new developer volunteers!

Want to check how you’re getting on? As mentioned previously there’s items ready to start developing on now, and many will help the 2019 site/edition so will be released as soon as we can fix them. Unlike the authorship side, development is an ongoing thing and we will release your work as soon as we’re comfortable with it.

We generally don’t hand out assignments for development so it’s up to you to grab an issue and work on it if you want to help out.

And if you spot any issues with the site, the code, or our workflows then you totally should raise new issues, suggestions and then pull requests to fix!

Anyway, I’m here to help answer any questions or help out in anyway so let me know if you’ve any questions or are stuck on anything.

**Comment by bazzadp** [comment]
Oh and code reviews on pull requests are VERY much appreciated.

Especially for my own PRs as @rviscomi seems to be left with all that burden and would like him to concentrate on the 2020 chapters!

No one codes perfectly (least if all me!), and reviews are one of the best things about GitHub workflow. And approvals or a LGTM are just as valuable as suggestions to know someone else has had a look and things it’s good to go.

So if on the site and see an open PR then give it a once over. And if you’d like to be tags for reviews of particular technology so you get a notification, then let me know.

**Comment by sareg0** [comment]
Hi there, I'd like to help. I'll probably take on some of those small front-end tasks at first

**Comment by arpansac** [comment]
Super interested! 😃 
Are you still taking people in the team? 
@bazzadp

**Comment by bazzadp** [comment]
Yes @arpansac - the more the merrier as far as developers are concerned! I've sent you an invite which means you'll be able to self-assign any of the [good first development issues](https://github.com/HTTPArchive/almanac.httparchive.org/issues?q=is%3Aissue+is%3Aopen+label%3Adevelopment+label%3A%22good+first+issue%22) so grab one of the issues that takes your interest! Then clone the repo locally, follow the instructions in `src/README.md` to get the dev version running locally, branch and make your change. Team members can branch from this main repo, or fork it and work form a branch on that if you prefer.

**Comment by arpansac** [comment]
Thanks! Already browsing the issues :D

**Comment by rajasekarm** [comment]
@bazzadp I would like to contribute for this project. Can you please count me in?

Meanwhile I'll look into Good first issue and start contributing.

**Comment by bazzadp** [comment]
> @bazzadp I would like to contribute for this project. Can you please count me in?

Thanks - Invite sent to join the team!

> Meanwhile I'll look into Good first issue and start contributing.

Do - grab an issue and let's go!!! Or help review any of the open development PRs.

**Comment by bazzadp** [comment]
Hey all, I've created a Slack channel in case any of you want to discuss anything to do with Developing the Web Almanac: https://httparchive.slack.com/archives/C018PDY6C1E

**Comment by bazzadp** [comment]
I created a [Git Guide](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Git-Guide) in our wiki for those of you new to git (or wanting a refresher!).

Also come join us on [`#web-almanac Slack`](https://join.slack.com/t/httparchive/shared_invite/zt-45sgwmnb-eDEatOhqssqNAKxxOSLAaA) if not already on there, including the [`#web-almanac-developers` Channel](https://httparchive.slack.com/archives/C018PDY6C1E).

**Comment by bazzadp** [comment]
Which reminds me that I never shared this other wiki page we recently created: [Technical accomplishments](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Technical-accomplishments) wii page.

**Comment by bazzadp** [comment]
Hey @HTTPArchive/developers there's still [development tasks available](https://github.com/HTTPArchive/almanac.httparchive.org/issues?q=is%3Aissue+is%3Aopen+label%3Adevelopment) if anyone wants to get involved! Luckily we did an awful lot of work last year so we can launch 2020 with what we have but can always improve!

Here's some issues:
- [1363 - Highlight H4s in sidebar TOC](https://github.com/HTTPArchive/almanac.httparchive.org/issues/1363) - this is a very easy one to solve so great as a first start. Small JavaScript change.
- [1325 - Optimize ebook for indexing](https://github.com/HTTPArchive/almanac.httparchive.org/issues/1325) - not entirely convinced we need any of this, but would love to have a second opinion here. Meta tags in HTML and potentially look at what PrinceXML gives us.
- [1237 - Pull quotes for chapters](https://github.com/HTTPArchive/almanac.httparchive.org/issues/1237) - this should be pretty easy now we've the basis in #1236. Just needs some thought on design though so need someone with a good UX eye and HTML/CSS dev experience. Would love to get this in ASAP for 2020 launch.
- [1229 - Increase pytest coverage](https://github.com/HTTPArchive/almanac.httparchive.org/issues/1229) - We make fantastic strides in improving our automated testing this year but still feel there's more we could do on the Python side for any Python developers with testing experience out there.
- [1224 - Keeping track of Last Updated timestamps](https://github.com/HTTPArchive/almanac.httparchive.org/issues/1224) - we have a system that works here, but it involves a second pull request (created automatically by GitHub Actions). Would love to have some other opinions as to whether there's a better way.
- [1223 - Changes to the way we develop CSS and JS](https://github.com/HTTPArchive/almanac.httparchive.org/issues/1223) - would anyone with with SCSS or SASS experience like to look at a better way to organise our CSS code? Or anyone with JavaScript experience like to review our JS code and clean it up a bit?
- [1222 - Should we change to a static site?](https://github.com/HTTPArchive/almanac.httparchive.org/issues/1222) - Still keen to gather thoughts on this, but probably won't change this before 2020 launch as what we have is working well.
- [1138 - Streamline figures in markdown](https://github.com/HTTPArchive/almanac.httparchive.org/issues/1138) - We made good progress in #1236 on this but there's a second part with a drop down menu to link directly to Sheets/SQL that would be good to get in for 2020.
- [985 - Table of Contents dropdown list](https://github.com/HTTPArchive/almanac.httparchive.org/issues/985) - as a regular user of our site, I would love this. Needs some CSS, HTML and JS experience.
- [896 - [Discuss] Interactive data visualizations](https://github.com/HTTPArchive/almanac.httparchive.org/issues/896) - would love some more thoughts on this.
- [559 - Add Search Functionality](https://github.com/HTTPArchive/almanac.httparchive.org/issues/559) - a long standing request of mine here and think it would be useful - especially as our content grows! Need some thought on were to place it an how (or if) to differentiate search results by year. Should we just use Google Custom Search (makes it easier to optimise SEO for just one search engine!) or something else?
- [75 - Transform Almanac to a PWA](https://github.com/HTTPArchive/almanac.httparchive.org/issues/75) - Another long standing issues. Not 100% convinced on need for this, especially now we have the ebook for offline reading, but always willing to hear counter arguments!

Would anyone like to tackle any of these issues?

And, as always, if you have any suggestions for improvements then raise and issue for discussion!

**Comment by allemas** [comment]
Hello ! Interested count me in :)

**Comment by bazzadp** [comment]
Just sent you an invite so you can assign yourself to issues. Above list is still looking in need of love. Have a look at that or ["good first issues"](https://github.com/HTTPArchive/almanac.httparchive.org/issues?q=is%3Aissue+is%3Aopen+label%3A%22good+first+issue%22+label%3Adevelopment) or [general "development" issues](https://github.com/HTTPArchive/almanac.httparchive.org/issues?q=is%3Aissue+is%3Aopen+label%3Adevelopment) and see if anything takes you fancy!

**Comment by bharatagsrwal** [comment]
@rviscomi Hello!, I am Interested to contribute to the development.

**Comment by bazzadp** [comment]
> @rviscomi Hello!, I am Interested to contribute to the development.

Welcome onboard @bharatagsrwal ! I've just sent you an invite there so you can be assigned issues. I suggest you clone the repo and get the site up running locally as per the README. You can do that directly or via Docker.

Then have a look at the good first issues or development issues as stated in the comment above yours.

**Comment by bazzadp** [comment]
And pull request reviews of [any open development pull requests](https://github.com/HTTPArchive/almanac.httparchive.org/pulls?q=is%3Apr+is%3Aopen+label%3Adevelopment) are VERY much appreciated!

Plus join the `web-almanac-developers` channel on the [HTTP Archive Slack](https://join.slack.com/t/httparchive/shared_invite/zt-45sgwmnb-eDEatOhqssqNAKxxOSLAaA)!

**Comment by bharatagsrwal** [comment]
> > @rviscomi Hello!, I am Interested to contribute to the development.
> 
> Welcome onboard @bharatagsrwal ! I've just sent you an invite there so you can be assigned issues. I suggest you clone the repo and get the site up running locally as per the README. You can do that directly or via Docker.
> 
> Then have a look at the good first issues or development issues as stated in the comment above yours.

Thank you @bazzadp for the invitation.

**Comment by AbbyTsai** [comment]
glad to have a fun opportunity contributing web-almanac project as translator, analyst, and hope development as well.  thanks.

**Comment by bazzadp** [comment]
Closing this as 2020 edition comes to a close but developers are more than welcome to join the team at any time to either work on existing open issues, or suggest new enhancements!
