### ISSUE TITLE
Translate content to Korean, 2019 Edition

### ISSUE THREAD

**Issue by techhtml** [HTTPArchive/almanac.httparchive.org#927]
I had to start to Korean translation of 2019 Edition.

There are lists that I need to translate:
- [ ] accessibility
- [ ] caching
- [ ] cdn
- [ ] cms
- [ ] compression
- [ ] css
- [ ] ecommerce
- [ ] fonts
- [ ] http2
- [ ] javascript
- [ ] markup
- [ ] media
- [ ] mobile-web
- [ ] page-weight
- [ ] performance
- [ ] pwa
- [ ] resource-hints
- [ ] security
- [ ] SEO
- [ ] third-parties - Partie Tiers

Some page template need to translate:
- [ ] base.html
- [ ] base_chapter.html
- [ ] contributors.html
- [ ] error.html
- [ ] index.html
- [ ] featured_chapters.html
- [ ] methodology.html
- [ ] table_of_contents.html
- [ ] accessibility_statement.html
- [ ] base_ebook.html

If someone has the interest to translate, Feel free to join

**Comment by bazzadp** [comment]
Oh we were both working on this! Shall we close this and use #926 ?

**Comment by techhtml** [comment]
@bazzadp Sure. We moved to #926 haha.
