### ISSUE TITLE
Query metrics: Chapter 12. Mobile Web

### ISSUE THREAD

**Issue by rviscomi** [HTTPArchive/almanac.httparchive.org#93]
Part | Chapter | Authors | Reviewers | Tracking Issue
-- | -- | -- | -- | --
II. User Experience | 12. Mobile web | @slightlyoff @obto | @hyperpress @AymenLoukil | #14

# READ ME!
All of the metrics in the table below have been marked as `Able To Query` during the [metrics triage](https://github.com/HTTPArchive/almanac.httparchive.org/issues/33). The analyst assigned to each metric is expected to write the corresponding query and submit a PR to [have it reviewed and added to the repo](https://github.com/HTTPArchive/almanac.httparchive.org/issues/62).

In order to stay on schedule and have the data ready for authors, **please have all metrics reviewed and merged by August 5**.

## Assignments

ID | Metric description | Analyst | Notes
-- | -- | -- | --
12.01 | LH tap targets | @ymschaap |  
12.02 | LH legible font size | @ymschaap |  
12.03 | Proper font contrast | @ymschaap |  
12.04 | % sites prevent users from scaling the viewport | @ymschaap |  
12.05 | % site with a meta viewport at all | @ymschaap |  
12.06 | % sites containing any CSS breakpoints <= 600px | @ymschaap |  
12.07 | % sites locking display orientation | @ymschaap |  
12.08 | % of sites preventing pasting into password fields | @ymschaap |  
12.09 | % of sites sites making NO permission requests. Should only be making these upon a user-interaction like a click. | @ymschaap |  
12.10 | For each of the following, what % of sites make this permission request while loading: Notifications, Geolocation, Camera, Microphone | @ymschaap |  
12.11 | # of links or buttons (ideally any element with a click listener attached) only containing an icon [1] | @ymschaap | This can be tested by checking if only svg is inside the button or if a single character is (font icons), implemented as custom metric 12.11
12.12 | popularity of input types: color, date, datetime-local, email, month, number, range, reset, search, tel, time, url, week, datalist | @ymschaap |  
12.13 | % of sites using ANY of the above input types | @ymschaap |  
12.14 | popularity of input attributes: autocomplete, min or max, pattern, placeholder, required, step | @ymschaap |  
12.15 | % of sites using ANY of the above attributes (besides placeholder and required) | @ymschaap |  
12.17 | % of sites that send more JS than the size of the viewport ("Web Bloat Score") per pageload | @ymschaap | can we get the size of the viewport as a screenshot? marking this ATQ assuming we can resolve the viewport px question
12.18 | number/fraction of sites specifying a webapp manifest | @ymschaap |  
12.19 | number of sites registering a Service Worker | @ymschaap | feature counter
12.20 | cumulative layout shift | @ymschaap | CrUX

## Checklist of metrics to be merged

- [x] 	12.01	LH tap targets
- [x] 	12.02	LH legible font size
- [x] 	12.03	Proper font contrast
- [x] 	12.04	% sites prevent users from scaling the viewport
- [x] 	12.05	% site with a meta viewport at all
- [x] 	12.06	% sites containing any CSS breakpoints <= 600px
- [x] 	12.07	% sites locking display orientation
- [x] 	12.08	% of sites preventing pasting into password fields
- [x] 	12.09	% of sites sites making NO permission requests. Should only be making these upon a user-interaction like a click.
- [ ] 	12.10	For each of the following, what % of sites make this permission request while loading: Notifications, Geolocation, Camera, Microphone
- [x] 	12.11	# of links or buttons (ideally any element with a click listener attached) only containing an icon [1]
- [x] 	12.12	popularity of input types: color, date, datetime-local, email, month, number, range, reset, search, tel, time, url, week, datalist
- [x] 	12.13	% of sites using ANY of the above input types
- [x] 	12.14	popularity of input attributes: autocomplete, min or max, pattern, placeholder, required, step
- [x] 	12.15	% of sites using ANY of the above attributes (besides placeholder and required)
- [x] 	12.17	% of sites that send more JS than the size of the viewport ("Web Bloat Score") per pageload
- [x] 	12.18	number/fraction of sites specifying a webapp manifest
- [x] 	12.19	number of sites registering a Service Worker
- [x] 	12.20	cumulative layout shift

**Comment by rviscomi** [comment]
Saving query results to [this sheet](https://docs.google.com/spreadsheets/d/1dPBDeHigqx9FVaqzfq7CYTz4KjllkMTkfq4DG4utE_g/edit?usp=sharing)

**Comment by rviscomi** [comment]
@slightlyoff @obto AFAICT we don't have a way to measure this metric:

`12.10 For each of the following, what % of sites make this permission request while loading: Notifications, Geolocation, Camera, Microphone`

I checked the blink feature counters and didn't see specific counters for these. Static analysis (regex) would be unreliable but we could try it as a last resort if you're confident if would produce meaningful results. Otherwise these queries are done and I'll pass the results over to you to unblock writing the chapter.

**Comment by obto** [comment]
@rviscomi Figuring out how to write a regex to not only check if permissions are being requested... but if they are being requested during page load (instead of after a user intent like clicking a button) sounds pretty difficult haha.

Let's set this one aside and keep moving forward as you proposed.
