### ISSUE TITLE
Implement linters for Python, CSS, JS, JSON and YML files

### ISSUE THREAD

**Issue by bazzadp** [HTTPArchive/almanac.httparchive.org#938]
As discussed in https://github.com/HTTPArchive/almanac.httparchive.org/issues/933#issuecomment-651228508 GitHub has a [superlinter](https://github.blog/2020-06-18-introducing-github-super-linter-one-linter-to-rule-them-all/) which will help to find typos and ensure a consistent coding style.

This can run through a GitHub action when a pull request is submitted so the requester gets quick feedback and can correct their code.

Downsides:
- Linting can lead to a large clean up when applying to old code
- It can enforce overly strict rules that annoy more than help. Key is to tune the rules to those useful for us. And change them if we want.

**Comment by ibnesayeed** [comment]
I can review the code once a PR is up.

**Comment by bazzadp** [comment]
Was hoping you would! 😀 Coming right up!
