### ISSUE TITLE
Add Web Vitals to analytics

### ISSUE THREAD

**Issue by rviscomi** [HTTPArchive/almanac.httparchive.org#944]
The web-vitals.js library can [augment](https://github.com/GoogleChrome/web-vitals#send-the-results-to-google-analytics) Google Analytics with the largest contentful paint (LCP), first input delay (FID), and cumulative layout shift (CLS) metrics. It'd be great to include these in our existing monitoring tools.

**Comment by dsadhanala** [comment]
@rviscomi do we have google analytics setup already in place? if not, should I go ahead and create an account and embed?

**Comment by rviscomi** [comment]
Yes, it's initialized in [templates/base.html](https://github.com/HTTPArchive/almanac.httparchive.org/blob/c2a220f351862faa83e458278aaa78bbd8f1e595/src/templates/base.html#L16-L23). Thanks for working on this! 🙌

**Comment by rviscomi** [comment]
Reassigning to @max-ostapenko, who has already created the PR.
