### ISSUE TITLE
SVG?

### ISSUE THREAD

**Issue by LeaVerou** [HTTPArchive/almanac.httparchive.org#945]
I don't see an SVG chapter. Is SVG part of another chapter? I think it would deserve a chapter of its own!

**Comment by rviscomi** [comment]
We don't currently have an SVG chapter. We can incubate it in the Media chapter (#900) and spin it off into its own chapter if there's enough interest/content. WDYT?

**Comment by LeaVerou** [comment]
Sure, I'm not very familiar with the process, but if that's what it is, no objections from me :)
