### ISSUE TITLE
Finalize chapter sequence/organization

### ISSUE THREAD

**Issue by rviscomi** [HTTPArchive/almanac.httparchive.org#946]
Some chapters may need to be split/merged/dropped/added depending on changes in content brainstorming. For now, here is the list of candidate chapters for the 2020 edition:

### I. Page Content

1. CSS
2. JavaScript
3. Markup
4. Fonts
5. Media
6. Third Parties

### II. User Experience

7. SEO
8. Accessibility
9. Performance
10. Privacy
11. Security
12. Mobile Web
13. PWA

### III. Content Publishing
14. CMS
15. Ecommerce
16. JAMstack

### IV. Content Distribution
17. Page Weight
18. Compression
19. Caching
20. Resource Hints
21. HTTP/2

**Comment by rviscomi** [comment]
@obto how does this sequencing look to you? If good could you update the issues' metadata in our sheet and in their issues?

@ibnesayeed is it possible to match this sequence in #989?

**Comment by bazzadp** [comment]
Presume we’d need to do one of below to allow ordering as currently think it’s ordered by issue number:

1. Rename this issue titles (e.g. from “JavaScript” to “1.1 JavaScript”)
Or
2. Add meta data to each issue (either as a hidden tag or not)
Or
3. Add config with the correct ordering to the GitHub Action

**Comment by rviscomi** [comment]
I imagined being able to parse the chapter number from the H1 in each chapter's comment. For example: `/^#.*Chapter (\d+):/`. Some are still `Chapter [Num]` so we'd need to update them first.

**Comment by bazzadp** [comment]
Completely missed that!

**Comment by ibnesayeed** [comment]
> @ibnesayeed is it possible to match this sequence in #989?

Yes! However, the more I think about it, the more I am convinced that in the future we should move to some structured data file like YAML to store these properties and use issue tickets to communicate. Changes in the data file can be pushed to change the issue ticket, not the other way.

> ... as currently think it’s ordered by issue number:

That's correct. The default order of the API response is descending order of issue numbers, but I have explicitly asked it to return in ascending order.

> I imagined being able to parse the chapter number from the H1 in each chapter's comment. For example: `/^#.*Chapter (\d+):/`. Some are still `Chapter [Num]` so we'd need to update them first.

I was worried that chapter counter might reset under each new part, which would have been a little more work because roman numerals are not sort-friendly unless we convert them to integers.

> Completely missed that!

You are not alone! I too was thinking about updating the issue title. ;-)

**Comment by rviscomi** [comment]
> Yes! However, the more I think about it, the more I am convinced that in the future we should move to some structured data file like YAML to store these properties and use issue tickets to communicate. Changes in the data file can be pushed to change the issue ticket, not the other way.

I like having the chapter issues themselves be the source of truth. For example, we use the issues to keep track of the authors/reviewers/analysts and milestone progress. The `Chapter (#)` H1 text is a reliable source of truth if we wanted to parse that metadata for reasons like this.

**Comment by obto** [comment]
@rviscomi How did you decide the ordering of the chapters in each section? Based off of their relative popularity last year?

The names for each section look good, and I've no issues with the sections each chapter were slotted into

**Comment by ibnesayeed** [comment]
* I would make Markup the first chapter as it seems the primary aspect of a page content as a page may exist without any CSS or JS
* I am not too sure if JS should be the second chapter or CSS, but if I were to list them, I would perhaps assume people would have more interest in JS than in CSS
* I would perhaps also swap placement of Fonts and Media
* I felt that Page Weight should go under the User Experience section, but looking at the other chapters under the Content Distribution section I think it is in good company

**Comment by rviscomi** [comment]
> @rviscomi How did you decide the ordering of the chapters in each section? Based off of their relative popularity last year?

Popularity was one factor. The CSS team this year is also ~2x larger than JS so I expect it to be a more comprehensive chapter, which would be good to lead with.

@ibnesayeed thanks for your feedback. Ordering is not an exact science and I had to rely on my intuition for what would be most engaging for readers.

**Comment by obto** [comment]
@rviscomi What do you say to keeping your ordering, but moving Javascript to the bottom like so? My thought on this is that JavaScript is a destination/anchor chapter--readers will head there regardless. So moving it to the bottom would let us bubble up some of the other chapters and give them a bit more love. Thoughts?

1. CSS
2. Markup
3. Fonts
4. Media
5. Third Parties
6. JavaScript

**Comment by rviscomi** [comment]
Third Parties is more of a conceptual topic than the rest of chapters in Part I, which are resource MIME types, so that's why I wanted to group them together and end with Third Parties. Fonts coming after Third Parties in 2019 was one of the reasons why I wanted to revisit the ordering this year :)

**Comment by ibnesayeed** [comment]
> Third Parties is more of a conceptual topic than the rest of chapters in Part I, which are resource MIME types, so that's why I wanted to group them together and end with Third Parties.

Even my preference would be to keep it at the end as it sounds more like "Others" or "Miscellaneous".

**Comment by rviscomi** [comment]
I've gone through each chapter issue and updated their part/chapter numbers. This should help unblock the updated tracker in #1059

**Comment by obto** [comment]
Just sat down to get this done today. Thanks for taking care of this @rviscomi
