### ISSUE TITLE
Make header/footer padding consistent

### ISSUE THREAD

**Issue by rviscomi** [HTTPArchive/almanac.httparchive.org#947]
On the 2020 landing page, the spacing inconsistency is more obvious because there is so little main body content:

![image](https://user-images.githubusercontent.com/1120896/86488988-dfdb6a00-bd30-11ea-84b1-07889a32955e.png)

The header, body, and footer should all have the same padding. Currently the footer has less padding.

Also ensure that the spacing is consistent on mobile.

**Comment by bazzadp** [comment]
Good spot. While we're looking at this, I'm still not convinced the home page should go as wide as it does, as discussed in #574 - at least for the top part. Leaves a big old empty space in the middle on ultra-wide monitors:

![Home page on ultra-wide monitor with big grey section in the middle](https://user-images.githubusercontent.com/10931297/86489493-65c0da80-bd5c-11ea-8a29-74e62e1e1dea.png)

**Comment by dsadhanala** [comment]
@bazzadp what you think about, treating home page hero section changes as separate issue?

Incase if we want to include that change also part of this issue, couple of questions.
* can you help me understand the expected behavior?
* do we want to scale font and layout spacings to adapt wide screen sizes?

**Comment by dsadhanala** [comment]
@rviscomi QQ, I noticed, header and footer visual treatment for internal pages(other than home page) is different, example header content set to max size of 1280, where as footer resizes based on viewport no max set. Should we keep both header and footer content resize behavior consistent?

**Comment by dsadhanala** [comment]
Footer content alignment looks little odd, especially logo aligned to left and leaving whitespace on the right, then navigation links aligned center. what you think about center aligned logo to be consistent with nav links alignment? below is the screenshot for your reference.

<img src="https://user-images.githubusercontent.com/5795823/86502498-ad456780-bd58-11ea-8f29-6ed55780406c.png" width="600px" />

**Comment by rviscomi** [comment]
> Should we keep both header and footer content resize behavior consistent?

Good catch, yes that sounds like a good idea.

> what you think about center aligned logo to be consistent with nav links alignment?

Yeah that looks good. Could you also center the copyright and accessibility statement text?

**Comment by dsadhanala** [comment]
thanks, all above mentioned changes are pushed into this PR. https://github.com/HTTPArchive/almanac.httparchive.org/pull/951

**Comment by bazzadp** [comment]
> @bazzadp what you think about, treating home page hero section changes as separate issue?
> 
> Incase if we want to include that change also part of this issue, couple of questions.
> 
> * can you help me understand the expected behavior?
> * do we want to scale font and layout spacings to adapt wide screen sizes?

Good idea, will reopen #574

**Comment by bazzadp** [comment]
Closed with #951
