### ISSUE TITLE
Remove the year from the footer copyright

### ISSUE THREAD

**Issue by rviscomi** [HTTPArchive/almanac.httparchive.org#948]
@bazzadp what do you think is the best way to do this? The 2020 template extends 2019, which sets ©️ 2019 in each lang's localized base template.

I think it's ok if the copyright year was defined in one central place and all pages/langs/editions inherit the latest year. Bonus points if we don't need to manually increment it each year.

**Comment by bazzadp** [comment]
I think remove the year. That's what we did at work. It's meaningless anyway. I'm not a lawyer, but my understanding is that common-law copyright is based on when publication happens - not that you included 4 random digits at the bottom.

Even if they did matter, then technically if you updated the year then you are no longer claiming copyright from 2019 so you're outta luck if someone had a site they copied in 2019 and no has a prior claim. But that's easily disproved with proof through Internet Archive and the like. And if you don't update it, then open to arguments for any significant change it's inaccurate.

The alternative is to say "© 2019 - 2020 Web Almanac." in which case it would be very easy to just have 2019 hardcoded and the current year variable. But honestly I think it's not worth it and say just drop the year.

Google doesn't even put a copyright noticed on the footer of it's websites. Though hunting around most other big companies do (e.g. Amazon, Apple, Microsoft, GitHub, Twitter) with current year or range of years.

**Comment by rviscomi** [comment]
Either option (remove or range) SGTM
