### ISSUE TITLE
Clean up unused code and dependencies 

### ISSUE THREAD

**Issue by bazzadp** [HTTPArchive/almanac.httparchive.org#953]
I don't think we use these files (added in #114 ) any more since we changed the way we generate chapters in  #222 
- generate_chapters.py
- generate_visualisations.py
- src/data

Also means we can get rid of the following from requirements file I think:
- matplotlib
- mistune
- pandas
- scour
- weasyprint (not part of above but removed by #833 )

We may want to add some of these back in depending what we do with #896 but easy enough to re-add if we want to.

Possibly could be done at same time as #949 ?

**Comment by ibnesayeed** [comment]
If `pytest-watch` is to be removed development README should be updated to exclude a relevant instruction.

**Comment by bazzadp** [comment]
Good spot - removed that from list of suggested libraries to remove.
