### ISSUE TITLE
Fix Google Advertising CSP issue

### ISSUE THREAD

**Issue by max-ostapenko** [HTTPArchive/almanac.httparchive.org#955]
I get errors on public website:
`Refused to load the image 'https://www.google.pt/ads/ga-audiences?v=1&aip=1&t=sr&_r=4&tid=UA-22381566-3&cid=722833102.1592150741&jid=307643168&_v=j83&z=1389390864&slf_rd=1&random=3377659529' because it violates the following Content Security Policy directive: "img-src 'self' www.google-analytics.com www.googletagmanager.com stats.g.doubleclick.net *.githubusercontent.com *.google.com ssl.gstatic.com data:".
`

Should we fix it or switch it off?

Tried to switch it off by adding: `gtag('set', 'allow_google_signals', false );` but still a response is sent for a new visitor (no GA cookies).

Source: https://developers.google.com/analytics/devguides/collection/gtagjs/display-features

**Comment by max-ostapenko** [comment]
@rviscomi if we want to switch it off, there are some settings also in GA Admin Console.
Property - Tracking Info - Data Collection

**Comment by rviscomi** [comment]
Thanks @max-ostapenko. I've disabled this in the GA Admin Console.
![image](https://user-images.githubusercontent.com/1120896/86662977-3fe54100-bfbb-11ea-80c4-f1b2ec932fbd.png)

Can you verify that the changes fix the CSP issue?

**Comment by bazzadp** [comment]
Seems to be fixed for me anyway.

**Comment by bazzadp** [comment]
Actually I tell a lie. It is still broken for me. It's not explicitly enabled in GTM is it?

![GTM screenshot](https://user-images.githubusercontent.com/10931297/86666282-55249480-bfe8-11ea-86a0-2722efd59c0b.png)

**Comment by max-ostapenko** [comment]
I don't see advertising requests anymore. Looks fixed for me.
@bazzadp still not a clean console for you?

I haven't seen GTM being injected to the website, so it's controlled only by tag or Admin console settings.

**Comment by bazzadp** [comment]
Actually looks good to me now. Closing!
