### ISSUE TITLE
Query metrics: Chapter 15. Compression

### ISSUE THREAD

**Issue by rviscomi** [HTTPArchive/almanac.httparchive.org#96]
Part | Chapter | Authors | Reviewers | Tracking Issue
-- | -- | -- | -- | --
IV. Content Distribution | 15. Compression | @paulcalvano | @yoavweiss @colinbendell | #17

# READ ME!
All of the metrics in the table below have been marked as `Able To Query` during the [metrics triage](https://github.com/HTTPArchive/almanac.httparchive.org/issues/33). The analyst assigned to each metric is expected to write the corresponding query and submit a PR to [have it reviewed and added to the repo](https://github.com/HTTPArchive/almanac.httparchive.org/issues/62).

In order to stay on schedule and have the data ready for authors, **please have all metrics reviewed and merged by August 5**.

## Assignments

ID | Metric description | Analyst | Notes
-- | -- | -- | --
15.01 | What compression formats are being used (gzip, brotli, etc) | @paulcalvano |  
15.03 | Are there missed opportunities for compressing resources | @paulcalvano |  
15.04 | Compression by Content Type | @paulcalvano |  

## Checklist of metrics to be merged

- [x] 	15.01	What compression formats are being used (gzip, brotli, etc)
- [x] 	15.03	Are there missed opportunities for compressing resources
- [x] 	15.04	Compression by Content Type

**Comment by paulcalvano** [comment]
Results from the queries are here - https://docs.google.com/spreadsheets/d/1IK9kaScQr_sJUwZnWMiJcmHEYJV292C9DwCfXH6a50o/edit?usp=sharing
