### ISSUE TITLE
Translate the temp 2020 landing page

### ISSUE THREAD

**Issue by rviscomi** [HTTPArchive/almanac.httparchive.org#969]
#815 introduces a new /en/2020/ landing page with a small amount of content specific to the ongoing 2020 project. Translate this content into the following supported languages:

- [x] Spanish
- [x] French
- [x] Japanese
- [x] Chinese

**Comment by bazzadp** [comment]
@HTTPArchive/translators any takers?

**Comment by rviscomi** [comment]
@bazzadp any other languages we should target for this page?

**Comment by bazzadp** [comment]
> @bazzadp any other languages we should target for this page?

As many as we can! @HTTPArchive/translators to add more languages we'd been the following templates at a minimum translated from English to your language:

- `src/templates/en/2019/base.html`
- `src/templates/en/2019/index.html`
- `src/templates/en/2019/contributors.html`
- `src/templates/en/2020/index.html`
- `src/templates/en/2020/contributors.html`

They're all quite small - certainly a lot smaller than the chapters themselves!

> Should we remove Spanish from the 2020 language options until the landing page is translated, or is it ok to have partial translations?

Hmmm I'm in two minds. It's not ideal to have it partially translated like we do, but think we have enough to keep it for now. I'm really hopeful we get some volunteers for this very popular language to keep it for 2020 but we will have to drop it if we don't get any further volunteers as there's no point in just keeping what we have, and if none of the chapters themselves will likely be translated.

**Comment by mcmd** [comment]
I can take the ES temp 2020 landing page

**Comment by rviscomi** [comment]
I see that the Chinese translation is still taking place in https://github.com/HTTPArchive/almanac.httparchive.org/pull/1073, so I've unchecked it from the progress list.

@bazzadp should we add checkboxes for other active languages like Polish and Turkish as well?

**Comment by bazzadp** [comment]
I say not and that we close this issue. All active languages are translated now and adding this should be BAU for new languages. As always doing core templates first (including this one) should be priority for translation team - will reorganise the outstanding translation lists in each issue today.

WDYT?

**Comment by rviscomi** [comment]
The open issues for other languages seem to only track 2019, so I think it's good to also have a way to track 2020 content.

**Comment by bazzadp** [comment]
Agree we should have new issues for 2020 content when it's available, but think they should be separate issues (like they are for 2019) and think it's a bit early to open them now while we only have this little content to translate for 2020.

And I think we need to draw a line at some point, or this issue will never be closed just in case a new language ever comes along. I say we've translated all our currently supported languages, and the new language that is close to merging (Chinese) and the rest haven't made any commits yet so aren's supported yet.

**Comment by HakaCode** [comment]
Can I try to translate to PT-BR? I'm a beginner

**Comment by bazzadp** [comment]
> Can I try to translate to PT-BR? I'm a beginner

Would love to have your help @HakaCode 

I presume you mean you’re a beginner coder/translator but are fully fluent in Brazilian Portuguese?

How different is Brazilian Portuguese to European Portuguese? My understanding is it’s very similar as it’s written and most differences are in pronunciation? If is suggest we translate into generic Portuguese (`pt`) rather than classifying it specifically as Brazilian Portuguese (`pt-BR`) - much like we have `en` rather than `en-US` or `en-GB`.

As the 2020 page depends on 2019 templates we should reopen #505 and track progress through that. The 8 templates at the top are basically what we need to launch a language.

**Comment by HakaCode** [comment]
Thanks for the quick response @bazzadp .

what you said is correct, I can translate the 2019 model without problems in my free time.
