### ISSUE TITLE
Query metrics: Chapter 17. CDN 

### ISSUE THREAD

**Issue by rviscomi** [HTTPArchive/almanac.httparchive.org#98]
Part | Chapter | Authors | Reviewers | Tracking Issue
-- | -- | -- | -- | --
IV. Content Distribution | 17. CDN | @andydavies @colinbendell | @yoavweiss @paulcalvano @pmeenan | #19

# READ ME!
All of the metrics in the table below have been marked as `Able To Query` during the [metrics triage](https://github.com/HTTPArchive/almanac.httparchive.org/issues/33). The analyst assigned to each metric is expected to write the corresponding query and submit a PR to [have it reviewed and added to the repo](https://github.com/HTTPArchive/almanac.httparchive.org/issues/62).

In order to stay on schedule and have the data ready for authors, **please have all metrics reviewed and merged by August 5**.

## Assignments

ID | Metric description | Analyst | Notes
-- | -- | -- | --
17.01 | What are the top CDNs per page | @raghuramakrishnan71 | pages, payload
17.02 | What % of sites use a CDN | @raghuramakrishnan71 |  
17.02b | % of sites that use a CDN for primary domain i.e. www | @raghuramakrishnan71 |  
17.02c | % of sites that use a CDN for secondary domain e.g. static. media. | @raghuramakrishnan71 |  
17.02d | Usage of 3rd-party public CDNs e.g jQuery, apis.google etc. | @raghuramakrishnan71 |  
17.03 | CDN TTFB | @raghuramakrishnan71 | requests, payload
17.04 | header volume | @raghuramakrishnan71 | Assuming reqHeadersSize or respHeadersSize (in summary_requests)
17.05 | STS | @raghuramakrishnan71 |  
17.06 | Timing-Allow-Origin | @raghuramakrishnan71 |  
17.07 | Via | @raghuramakrishnan71 |  
17.08 | Keep-Alive | @raghuramakrishnan71 |  
17.09 | Server-Timing metrics/presence | @raghuramakrishnan71 |  
17.10 | Vary | @raghuramakrishnan71 |  
17.11 | Content-Disposition | @raghuramakrishnan71 |  
17.12 | TLS negotiation time | @raghuramakrishnan71 | WPT metric
17.13 | TLS Certificate size | @raghuramakrishnan71 |  
17.17 | Number of CDN's used per page | @rviscomi |  
17.18 | H2 push? | @rviscomi |  
17.19 | HTTPS uses 1.1 or 2? | @rviscomi |  
17.20 | s-max-age | @rviscomi |  
17.21 | stale-while-revalidate | @rviscomi |  
17.22 | nopush | @rviscomi |  
17.23 | stale-while-error | @rviscomi |  
17.24 | pre-check | @rviscomi |  
17.25 | Surrogate-Control | @rviscomi |  
17.26 | How have these patterns changed over the last year / two years | @rviscomi |  

## Checklist of metrics to be merged

- [x] 	17.01	What are the top CDNs per page
- [x] 	17.02	What % of sites use a CDN
- [x] 	17.02b	% of sites that use a CDN for primary domain i.e. www
- [x] 	17.02c	% of sites that use a CDN for secondary domain e.g. static. media.
- [x] 	17.02d	Usage of 3rd-party public CDNs e.g jQuery, apis.google etc.
- [x] 	17.03	CDN TTFB
- [x] 	17.04	header volume
- [x] 	17.05	STS
- [x] 	17.06	Timing-Allow-Origin
- [x] 	17.07	Via
- [x] 	17.08	Keep-Alive
- [x] 	17.09	Server-Timing metrics/presence
- [x] 	17.10	Vary
- [x] 	17.11	Content-Disposition
- [x] 	17.12	TLS negotiation time
- [x] 	17.13	TLS Certificate size
- [x] 	17.17	Number of CDN's used per page
- [x] 	17.18	H2 push?
- [x] 	17.19	HTTPS uses 1.1 or 2?
- [x] 	17.20	s-max-age
- [x] 	17.21	stale-while-revalidate
- [x] 	17.22	nopush
- [x] 	17.23	stale-while-error
- [x] 	17.24	pre-check
- [x] 	17.25	Surrogate-Control
- [ ] 	17.26	How have these patterns changed over the last year / two years

**Comment by rviscomi** [comment]
@raghuramakrishnan71 looking back at #19 there are a few metrics that were added late. Let's use the following metric numbering:

- 17_01: What are the top CDNs (by number of sites using rather requests?)
- 17_02: What % of sites use a CDN
- 17_02b: % of sites that use a CDN for primary domain i.e. www
- 17_02c: % of sites that use a CDN for secondary domain e.g. static. media.
- 17_02d: Usage of 3rd-party public CDNs e.g jQuery, apis.google etc.

I'll update the triage sheet and table in this issue. Can you update your queries?

**Comment by colinbendell** [comment]
The totals for 17.01 and 17.02 all appear to be the same. There are 5.2million html pages, 5.2 million 'any resource' 5.2 million 'same domain resources', 5.2 million '3p resources'. Can someone look into this asap?

**Comment by rviscomi** [comment]
Chatted with @colinbendell about the query issues. He's going to take a pass at fixing up any discrepancies.

@colinbendell I've given you edit access to the [results sheet](https://docs.google.com/spreadsheets/d/1Y7kAxjxUl8puuTToe6rL3kqJLX1ftOb0nCcD8m3lZBw/edit?usp=sharing). As you fix up the queries, please make a PR to merge the changes and save the results to the sheet. We just want to make sure all of the analysis that goes into the Almanac is publicly available/reproducible. Thanks for identifying these issues and working to get them fixed. Hopefully it doesn't delay the writing too long.

**Comment by rviscomi** [comment]
@colinbendell's note from #206 (merged here):

> After some data exploration, the CDN metrics need to be refined. Specifically the distinction between firstHtml, same domain, and third party hosting, the frequency count should be based on request/hits and not on hosts, tls negotiation timing should consider resumed vs first request and many other conditions
