### ISSUE TITLE
Remove unsafe-inline from CSP

### ISSUE THREAD

**Issue by bazzadp** [HTTPArchive/almanac.httparchive.org#984]
We allow inline-styles in case Authors want to use them. However few do and in #965 we cleaned them all up to use classes instead.

Should we remove `unsafe-inline` from [our CSP](https://github.com/HTTPArchive/almanac.httparchive.org/blob/main/src/csp.py) as per best practice?

Or do we think we want to keep the ability to have in-line styles directly in HTML elements?

We still have some `<style>` code directly in our HTML templates in the `<head>`, but they are easily handled with a nonce same as we do for scripts:

So, from this:

```
<style>
...
</style>
```

to this:

```
<style nonce="{{ csp_nonce() }}">
...
</style>
```

And would need to add `style-src` to our nonce config:

https://github.com/HTTPArchive/almanac.httparchive.org/blob/db9bc92b5fb6bd6962327c4ec9c4aa95cea86986/src/main.py#L30

As we already use this for `script-src` I think this is safe to do.

**Comment by rviscomi** [comment]
This seems like a good idea
