### ISSUE TITLE
Implement feature-policy

### ISSUE THREAD

**Issue by bazzadp** [HTTPArchive/almanac.httparchive.org#988]
[Feature Policy](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Feature-Policy) is a relatively new feature were sites can send an HTTP header to tell the browser which powerful APIs are not used by this site and so you can say shouldn't be allowed. More info in this [Smashing Magazine article](https://www.smashingmagazine.com/2018/12/feature-policy/).

This offers good protection for users so a third-party ad for example can't ask for location - which is bad for privacy and also bad for UX (as browsers may show up a pop up asking for permission before allowing it.

We don't use a lot of third-party scripts so think risk for us is low, but on other hand that means implementation risk (and effort) is also low. And we've been implementing other best practices on this site so think this would be a good one. Also its usage is likely to grow in future.

As we don't use any of these powerful APIs at the moment I'd suggest we go for a fairly restrictive Feature Policy, like below:

```
feature-policy: accelerometer 'none'; camera 'none'; geolocation 'none'; gyroscope 'none'; magnetometer 'none'; microphone 'none'; payment 'none'; usb 'none'
```

I've implemented that (or a slight variety of that) on sites I manage with no issues.

This is [fully supported by the flask-talisman](https://github.com/GoogleCloudPlatform/flask-talisman#feature-policy) security library we use so should be easy to implement.

**Comment by rviscomi** [comment]
Should be a no-op, right? Seems like a good idea to me.

**Comment by bazzadp** [comment]
It should have no-impact and not require any further thought after implementing if that’s what you mean?

So only impact is time to write this (very small - basically config for flask-talisman), extra code in our code-base (very small) and if some future feature needs one of these APIs then will have to tweak our feature policy to allow it.

**Comment by bazzadp** [comment]
[Securityheaders.com now gives us a nice green A grade](https://securityheaders.com/?q=https%3A%2F%2Falmanac.httparchive.org%2Fen%2F2019%2F&followRedirects=on):

![Screenshot of securityheaders.com for almanac.httparchive.org showing all green](https://user-images.githubusercontent.com/10931297/87241198-86ea9080-c418-11ea-9fbb-0820fa92c1d4.png)

Aiming for an A+ with #1010 😀

**Comment by paulcalvano** [comment]
Nice.   Looks like that did it :). 
![image](https://user-images.githubusercontent.com/7459458/87501546-516ac080-c62d-11ea-8d1d-e4b426f72ce0.png)
