### ISSUE TITLE
Lint SQL

### ISSUE THREAD

**Issue by rviscomi** [HTTPArchive/almanac.httparchive.org#991]
The BigQuery SQL files (eg [01_01a.sql](https://github.com/HTTPArchive/almanac.httparchive.org/blob/main/sql/2019/01_JavaScript/01_01a.sql)) for each metric are written by many analysts. It would be great to automatically enforce an SQL style guide with the linter, so that discrepancies can be caught by analysts in the PRs. Not sure how much control/customization we have at our disposal.

@paulcalvano can be in charge of defining what the SQL style guide should be.

Related: #938

**Comment by bazzadp** [comment]
It’s not in the Github Superlinter yet which would make this easier. Issue to follow: https://github.com/github/super-linter/issues/128

Still may be worth looking at the linters proposed and considering the rules we want.

**Comment by rviscomi** [comment]
@fhoffa this is a hail mary, but does BigQuery have an open source linter/formatter?

**Comment by rviscomi** [comment]
Spoke with Felipe offline and BigQuery doesn't have anything open source to help with this.

This would be nice to have for the 2020 queries, but not required. At a minimum we should have some kind of style guide or reference doc in the wiki to help analysts understand what we're looking for. @paulcalvano is that doable?

**Comment by bazzadp** [comment]
Good news - The [GitHub Superlinter just merged in sql-lint](https://github.com/github/super-linter/pull/528).

Not so good news, is that it is not [currently configurable](https://github.com/github/super-linter/blob/master/docs/disabling-linters.md#sql) so we cant turn off rules we don't like - which might be an issue for some of the weird SQL we use in Big Query. However [sql-lint just added that facility](https://github.com/joereynolds/sql-lint/issues/155) but not tagged in a release yet.

I tried to run it locally and it's complaining about functions, which looks to have been raised as [an issue with sql-lint](https://github.com/joereynolds/sql-lint/issues/154) so will monitor that issue and see if it fixes for us when resolved.

So progress, but still a bit to go. Would be lovely to get this in, in the next month but not sure how realistic that it.

**Comment by joereynolds** [comment]
Hey @bazzadp,

I'm working on fixing these issues (I'm the dev on `sql-lint`). Bit of a busy time for me but it's on the way, hope that gives some reassurance!

**Comment by bazzadp** [comment]
Thanks for responding @joereynolds ! Great to have that reassurance. I’m watching those so should be informed of updates whenever you get a chance!

**Comment by rviscomi** [comment]
@joereynolds any update on sql-lint configurability?

Another option from a quick search is [sqlint](https://pypi.org/project/sqlint/) which explicitly states support for BigQuery's Standard SQL syntax.

I'd still love to have a tool like this to help standardize our queries and catch things when PRs are created. @paulcalvano we should also continue to build up our documentation for analysts to know what our style guide is.

**Comment by joereynolds** [comment]
Hey @rviscomi 

The configurability is on the superlinter's side of thing. You can already ignore errors via sql-lint, it's just that superlinter hasn't integrated in. Is there some other configuration you had in mind?

As for general progress on sql-lint. Recent work has been done so that we can add other drivers (such as big query) easily into sql-lint. I'm not too familiar with bigquery though, some hands would be appreciated if/when someone (probably me) gets around to adding it in.

Cheers!

**Comment by bazzadp** [comment]
Discussed more in https://github.com/joereynolds/sql-lint/issues/154#issuecomment-828343702
